### ISSUE TITLE
Cannot change / edit project.

### ISSUE THREAD

**Issue by apiening** [kimai/kimai#1000]
I want to edit the project of an already existing time sheet entry.
I can click edit and select another project from the list in the edit dialog and click on ok. But the change is not persisted: Even if I reload the page or sign out and back in the project of the entry is still the same as it was before I updated it.
I'm on v1.1.0.1389 which is latest stable at the moment.
When I log into the demo system, I can edit / change the project perfectly fine but the demo system is running the dev version I think. I don't want to upgrade to the dev version and take the risk to run into other issues.

Is this a bug in the stable version?

**Comment by simonschaufi** [comment]
The demo site is running latest master. Your problem sounds like a unique problem of your server. Please check the error log in kimai.

**Comment by apiening** [comment]
Ok, do you mean the apache error logs for my kimai instance? There is nothing related to this.
Is there a kimai specific log? Where can I find it?

**Comment by simonschaufi** [comment]
there is a log module in kimai itself and the file is in temporary/logfile.txt. you should have seen that when you opened a new issue (and actually you just deleted everything!)

**Comment by apiening** [comment]
Thank you very much!
I got the message "timeEntry_edit: Column 'fixedRate' cannot be null (#1048)" in my temporary/logfile.txt. Then I entered "1" as a random number into the fixedRate field and it worked.

So problem kind of solved I guess. But I don't understand why I need to insert a value into this field. I thought that this is optional and the effort is calculated based on time x hourly rate if there is no fixedRate. I have saved the entry with 0.00 in fixed rate in the first place and it worked. Now my fixed rate is shown in the wages column, this is expected but not what I want.
Maybe you can enlighten me on this, too?

I took the messages while adding this issue as a hint on the information needed. I did not unterstand that it is meant to stay there as a template. Sorry.

Oh and I noticed that I opened the 1000th case! Did I won anything? ;-)

**Comment by simonschaufi** [comment]
this bug got fixed actually long time ago already. the best is just to go to phpmyadmin and make this column accept null values.

**Comment by apiening** [comment]
Thanks again. Everything is working great now!
