### ISSUE TITLE
Nach Zeiteintrag kein Update des übersichtsfensters mit den einträgen

### ISSUE THREAD

**Issue by neclcd** [kimai/kimai#1002]
Hallo

ich habe das problem das wenn ich einen zeiteintrag mache und ihn speicher er nicht automatisch im übersichtsfenster angezeigt wird.

Es wird nur angezeigt kein eintrag vorhanden. erst mit der rechtenmaustaste und reload auf die übersicht wird er dargestellt.

bei unserem system handelt es ich um ein Ubuntu 16.04 LTS mit allen updates.

als kimai kommt die version dev 1.2.1.1393 zum einsatz.

an den brauseren kann es nicht liegen denn in ihrer demoumgebung funktioniert es

danke & lg

JPS

**Comment by FriedrichFroebel** [comment]
Are there any errors inside the debug tab or inside the `temporary/logfile.txt` file?

**Comment by kevinpapst** [comment]
Tritt das Problem immer noch auf? Kannst Du genau schildern in welchen Fällen es auftritt? 
Liegt es vielleicht daran, wenn zuvor kein einziger Eintrag in der Liste stand?
Oder kann es sein, das Du oben im Datumsfilter einen Zeitraum gewählt hast, der den neuen Eintrag nicht einschliesst?

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
