### ISSUE TITLE
userID not defined

### ISSUE THREAD

**Issue by chipee** [kimai/kimai#1003]
Hi,
I wanted to use Kimai on a freeBSD 11.0. The version of recommended mysql and php are not available on that platform so I used php and mysql 5.6. The installation process worked great. I can log in with username Admin and password changeme.

#### Expected behaviour
The page should load properly after log in.

#### Actual behaviour
I get a warnning and an error
warnnig:
The function « getPreventDefault() » is deprecated. Use « defaultPrevented » instead.
Error :
ReferenceError: userID is not defined  init.js:54:1

The error is about some variables not declare in js/init.js I checked in mysql if those field were missing and that is not the case.

#### Steps to reproduce
Maybe use the same software
mysql 5.6
php 5.6
freeBSD 11.0

#### Reproducable on demo.kimai.org? [yes|no]
no

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai dev 1.2.1.1393 github master
kimai stable 1.1.0 on kimai.org/download

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
-

Thank for your work

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
