### ISSUE TITLE
Set multiple entrys to status "cleared"

### ISSUE THREAD

**Issue by blu-IT** [kimai/kimai#1004]
#### Expected behaviour
I would like to set multiple entrys to the status "cleared" **without** editing **every single entry** on the advanced tab of every recorded entry at the end of the month.
 
#### Actual behaviour
See abouve

#### Steps to reproduce
Edit recorded enty, pass to the advanced tab and check the cleard box and save.

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
V. 1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
-

Is there some way to do this?

Regards

**Comment by simonschaufi** [comment]
you can do that in the export tab by clicking the bullet on the right.
