### ISSUE TITLE
Sort an invoice template by useralias

### ISSUE THREAD

**Issue by drac83** [kimai/kimai#1005]
#### Expected behaviour
I have an ODT invoice template with an overview of worked time:

[row.useralias] | [row.desc] [row.description][row;block=table:table-row] | [row.date;frm='dd.mm.yyyy'] | [row.fDuration] | [row.amount;frm='0,00'] [var.currencySign]

How i can sort the timesheet by the useralias? 

#### Actual behaviour
How i can sort the the timesheet by the useralias? 

#### Steps to reproduce
Generate an invoice with a default template. 

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
Not needed.

[![bountysource](https://api.bountysource.com/badge/issue?issue_id=47382638)](https://www.bountysource.com/issues/47382638)

**Comment by simonschaufi** [comment]
currently not implemented but you can sponsor that feature! I would highly appreciate that!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
