### ISSUE TITLE
Time entries incorrectly recorded as negative

### ISSUE THREAD

**Issue by portfola** [kimai/kimai#1007]
#### Expected behaviour
I enter a time entry of 30min or 45min and it's recorded properly.

#### Actual behaviour
My 30min entry is recorded as -30min. The In and Out times are reverse to what I entered. My 45min entry is recorded as -15min. Although I entered 18:00-18:45, it is recorded as 18:30-18:15.

#### Steps to reproduce
Install a new version of v1.1.0.1389 with a clean database. Do not edit any of the default settings. Add time entries of 30 or 45min. 

I first noticed this in some entries I added recently to an installation I created last month (June). I have re-installed it several times over with different versions but continue to get this error for entries of 30 or 45 min. What could be going wrong?

#### Reproducable on demo.kimai.org? [yes|no]
No

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
22.07.2017 18:01:24] KSPI axAction (admin): add_edit_timeSheetEntry
[22.07.2017 18:01:24] timeEntry_create
[22.07.2017 18:01:25] KSPI axAction (admin): reload_timeSheet
[22.07.2017 18:03:33] KSPI axAction (admin): add_edit_timeSheetEntry
[22.07.2017 18:03:33] get_best_fitting_rate - using default rate 0.00
[22.07.2017 18:03:34] KSPI axAction (admin): reload_activities_options
[22.07.2017 18:03:34] KSPI axAction (admin): bestFittingRates
[22.07.2017 18:03:34] get_best_fitting_rate - using default rate 0.00
[22.07.2017 18:03:49] KSPI axAction (admin): add_edit_timeSheetEntry
[22.07.2017 18:03:49] timeEntry_create
[22.07.2017 18:03:50] KSPI axAction (admin): reload_timeSheet
[22.07.2017 18:04:53] KSPI axAction (admin): credits

**Comment by simonschaufi** [comment]
the problem is the time of the server and your client. they seem to be different. we store the time serverside but display it clientside. if they are not the same, then negative values are possible.

**Comment by portfola** [comment]
OK thank you for the response. I'll see what I can do about it, but likely to be little. Still, good to know.

**Comment by portfola** [comment]
@simonschaufi could you help me please to identify the files / functions for the serverside storage and clientside display of the time? I'd like to look into this but I'm new to this code.

**Comment by simonschaufi** [comment]
the main entry points are https://github.com/kimai/kimai/blob/master/core/processor.php#L140-L160
and https://github.com/kimai/kimai/blob/master/js/main.js#L326-L361

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
