### ISSUE TITLE
Kimai Install v1.1.0.1389 (halted)

### ISSUE THREAD

**Issue by oddstrange201** [kimai/kimai#1008]
#### Expected behaviour

Kimai installs on our company owned server with no issues

#### Actual behaviour

system requirements PASSED
Timezone PASSED
Write-Permissions PASSED
Database server: we use localhost:port (or localhost) username, password
NEXT STEP HALTED with the following
No database(s) found or no permission to list databases. Name of the database to use:

Unable to open that database.

We set the database up and we own the server, (not some cheap hosted install) and all the controls on the box. It tells us it cannot list, however the database already exists, possible bug??

#### Steps to reproduce

http://www,reelzproductions.com/time/installer/

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

Not sure which logs

**Comment by timlegge** [comment]
Hi

The do you have your MySql server listening on a non standard port?  If not
simply use:

hostname: loocalhost
user: a use capable of creating databases on the MySql server
password: pasword for the above user

You should be able to login to mysql with the user name and password you
provide:

mysql -u root -p

Tim

**Comment by oddstrange201** [comment]
hey tim did you say use loocalhost?

Just want to make sure i read that right

The server listens on :3306

**Comment by oddstrange201** [comment]
@timlegge  I got it! I just made a user without assigning it to a database, that was tricky!

Thanks!

**Comment by timlegge** [comment]
No worries  yes i had z typo in localhost
