### ISSUE TITLE
Tätigkeiten nicht mehr sichtbar

### ISSUE THREAD

**Issue by joergwilke** [kimai/kimai#1009]
Hallo,
Ich habe das Problem, dass die Tätigkeiten nicht mehr angezeigt werden.
Sie sind in der Datenbank vorhanden und evt_visible steht auf 1.
Im Admin-Panel sind sieht auch nicht zu sehen.
Daraufhin habe ich neue Tätigkeiten angelegt, aber auch die sind nach kurzer Zeit nicht mehr zu sehen.
Vielleicht habt Ihr einen Rat.
Wir setzen die Version v0.9.2.1306 auf einem Mac mit XAMPP 5.6.30 ein.
Vielen Dank für eure Hilfe.
Gruss
Jörg

**Comment by joergwilke** [comment]
Hallo,
Noch mal zu dem Problem. 
Ich habe jetzt das Kimai und die Datenbank umgezogen auf einen anderen Server und gleich ein Update auf die Version v1.1.0.1389 gemacht.
Das hat auch alles funktioniert. Nur das die ersten "Tätigkeiten" wieder nicht angezeigt werden.
Anbei ein Bildschirmfoto der Tabelle.
![bildschirmfoto 2017-07-28 um 15 34 55](https://user-images.githubusercontent.com/30502727/28719562-af04a310-73aa-11e7-9e88-bf4c486584cf.png)
Danke
Gruss
Jörg

**Comment by FriedrichFroebel** [comment]
Eventuell ist der Zeitbereich bei der Anzeige falsch eingestellt? (Übrigens sollten Issues vorzugsweise auf Englisch verfasst werden.)

**Comment by joergwilke** [comment]
Danke für die Antwort, aber was soll der Zeitbereich mit den Tätigkeiten zu tun haben, denn ich nirgendwo festlegen, wie lange eine Tätigkeit gültig ist.
Im Admin-Panel müsste man ja alle Tätigkeiten sehen.

**Comment by FriedrichFroebel** [comment]
Der Zeitbereich gibt an, Tätigkeiten welchen Zeitraums überhaupt angezeigt werden - das ist auch im Adminpanel nicht anders als bei jedem User. Wenn dieser Bereich zu klein eingestellt ist (zum Beispiel auf 3 Tage), kann es durchaus passieren, dass Tätigkeiten der letzten Woche nicht mehr angezeigt werden (aber eben in der Datenbank vorhanden sind und durch Ändern des Anzeige-Zeitraums sichtbar gemacht werden können).

**Comment by joergwilke** [comment]
Ich hab mal testweise den Zeitraum auf ca. Jahre angepasst und es sind trotzdem nur die zuletzt von mir angelegten Tätigkeiten zu sehen.
Schau mal bitte auf das Bild.
Vielleicht funktioniert es ja jetzt mit den neu angelegten Tätigkeiten, aber es macht mir trotztdem Sorgen, denn ich war nicht an dem Server als die anderen Tätigkeiten verschwanden.
![bildschirmfoto 2017-07-28 um 15 54 45](https://user-images.githubusercontent.com/30502727/28720329-27a3c75e-73ad-11e7-98b3-c299169f2cbd.png)

**Comment by FriedrichFroebel** [comment]
Stammen die Einträge von verschiedenen Benutzern? Im Regelfall sieht man als Administrator erst einmal nur seine eigenen Einträge, sind diese denn vorhanden?

**Comment by joergwilke** [comment]
Die Tätigkeiten hat die Kollegin am Empfang als Admin angelegt. Die ist jetzt aber nicht mehr da.

**Comment by FriedrichFroebel** [comment]
Als Administrator kann man auch Einträge für andere Benutzer anlegen statt für sich. Falls aber selbst die eigenen Einträge (die nachweisbar dem Administratorkonto zugewiesen sind) verschwinden, würde mir (als normaler Kimai-Nutzer) jetzt spontan auch erst einmal kein Grund für dieses Verhalten einfallen.

**Comment by joergwilke** [comment]
Mir fällt dazu auch nichts mehr ein, denn in der entsprechenden Tabelle ist alles in Ordnung und in der Tabelle kimai_groups_activities ist auch alles richtig.
Aber wie geschrieben, vielleicht funktioniert es ja mit den neuen Einträgen.
Danke noch mal

**Comment by joergwilke** [comment]
Hallo,
Ich habe rausbekommen, woran es gelegen hat.
In der Tabelle kimai_usr gibt es eine Spalte mit dem Namen lastEvent. Wenn dort der Wert 1 ist, dann zeigten sich auch alle Tätigkeiten.
Das habe ich über die Anlage eines neuen Benutzers herausgefunden.
Dann wünsche ich einen schönen Tag.
Gruss
Jörg

**Comment by FriedrichFroebel** [comment]
Wenn sich das Problem gelöst hat, kannst Du diesen Issue auch schließen.
