### ISSUE TITLE
Tenths of an Hour

### ISSUE THREAD

**Issue by joelaready** [kimai/kimai#1014]

**Comment by joelaready** [comment]
I would be interested in a feature that allows you to record rounding up to tenths of an hour (every six minutes). That would be helpful. Currently, only 15 minute increments are allowed.

**Comment by simonschaufi** [comment]
What kind of strange rounding is this? Would you sponsor this feature to add it?

**Comment by joelaready** [comment]
In the legal world, we bill everything in 6 minute increments. Forgive me, but what do you mean by "sponsor" it? I'm fairly new to all of this.

**Comment by simonschaufi** [comment]
As this is very customer specific, I can't do this for free. I'm ready to implement that for an invoice.
