### ISSUE TITLE
Howto sort 'Project' in the 'Timesheet' tab

### ISSUE THREAD

**Issue by jackhazeborg** [kimai/kimai#1017]
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop] v1.1.0.1389 - © 2006-17 by the Kimai-Team

How can I sort 'Project' in the 'Timesheet' tab? Is it possible?

**Comment by simonschaufi** [comment]
they are meant to be sorted alphabetically. no other sorting is possible.
