### ISSUE TITLE
BROKEN: Draw a line between entries of different days.

### ISSUE THREAD

**Issue by keteague** [kimai/kimai#1018]
#### Expected behaviour
Draw a bold line between entries that occur different days.

#### Actual behaviour
No line is drawn between entries that occur on different days.

#### Steps to reproduce
1. Login to Kimai
2. Create two new events, both of which occur on separate days.
3. Notice that there is no separator line between events that occur on different days.

#### Reproducible on demo.kimai.org? [yes|no]
Yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
dev 1.2.1.1393

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
None

#### Additional notes
There is a checkbox to enable/disable this option under the "Admin Panel".  It's enabled by default.  I've tried to disable then reenable the option, but it has no effect.  This *does* work on the stable branch.  The behaviour ought to function just like an overlapping entry that is indicated by a bold red line, but instead have a bold black line for entries that occur on separate days.

**Comment by simonschaufi** [comment]
As you say that it works on the stable branch, could you please make a screenshot that compares both versions?

**Comment by keteague** [comment]
https://goo.gl/J793yU

**Comment by simonschaufi** [comment]
thank you. could you also figure out where the differences are (php, css)?

**Comment by keteague** [comment]
~extensions/ki_timesheets/css/tables.css.php
lines 175-177 from stable branch

```
.break_day {
        border-top:1px solid black;
}
```

**Comment by keteague** [comment]
Stable v1.10.1389 branch:
extensions/ki_timesheets/templates/scripts/timeSheet.php
Line 55-56
```
        } elseif ($this->kga['show_daySeperatorLines'] && $start != $day_buffer) {
                $tdClass = " break_day";
```

master v1.2.1.1393 branch:
extensions/ki_timesheets/templates/scripts/timeSheet.php
Line 53-54
```
        } elseif ($this->kga->isShowDaySeperatorLines()['show_daySeperatorLines'] && $start != $day_buffer) {
            $tdClass = " break_day";
```

break_day still works under Exports.  I noticed that extensions/ki_export/templates/scripts/table.php has a variable at the top named $showDaySeperatorLines = $this->kga->isShowDaySeperatorLines(); which I tried adding to extensions/ki_timesheets/templates/scripts/timeSheet.php, on the line above the first IF statement which didn't work, then on the line below  the first IF statement (after the curly bracket) and still didn't work.  isShowDaySeperatorLines() also appears in Config.php as well.  As you can see, my php and css skills are lacking, to put it mildly.  I'm going to have to pass this over to you guys, the experts, to resolve.

**Comment by simonschaufi** [comment]
fixed in master
