### ISSUE TITLE
Export a bill by user

### ISSUE THREAD

**Issue by drac83** [kimai/kimai#1020]
#### Expected behaviour
Export a bill for each user.
#### Actual behaviour
Is there a solution to export a bill for each user?
#### Steps to reproduce
Create a bill, there is no filtering option per user.
#### Reproducable on demo.kimai.org? [yes|no]
yes
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
-

**Comment by simonschaufi** [comment]
duplicate: #967
