### ISSUE TITLE
Starting/Stopping tasks with rofi menu

### ISSUE THREAD

**Issue by antikdede** [kimai/kimai#1026]
Hi,

I wrote a simple script to start/stop Kimai tasks with [rofi](https://github.com/DaveDavenport/rofi) menu. I have lots of activities for a project and "search as you type" feature of rofi is very useful in such cases. I am using it on Arch Linux.

[https://github.com/antikdede/kimai-rofi](https://github.com/antikdede/kimai-rofi)

**Comment by kevinpapst** [comment]
Thanks @antikdede very cool!

Even though I have no clue what rofi is, you can sent us a PR to https://github.com/kimai/kimai.github.io/blob/master/apps.md
and it will be listed on the website instead of here in the issue section.
