### ISSUE TITLE
Date Time Format "x" not working in latest Master 

### ISSUE THREAD

**Issue by Richigeht** [kimai/kimai#1034]
#### Expected behaviour
If I set the dateformat to "x" it should be "08/25/17" 
#### Actual behaviour
I only see a "x" in the column
#### Steps to reproduce
Go to Export -> Time/dateformat and set "dateformat" to x
#### Reproducable on demo.kimai.org? [yes|no]
yes
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
github master

**Comment by simonschaufi** [comment]
use `%x`

**Comment by Richigeht** [comment]
That works awesome thanks! 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet
