### ISSUE TITLE
Fehlereintrag Undefined index: fixedRate in Apache Log beim Anlegen eines neuen Zeiteintrages

### ISSUE THREAD

**Issue by bluefire42** [kimai/kimai#1048]
#### Expected behaviour
Kein Fehler im Apache log

#### Actual behaviour
Fehler im Apache Log, siehe "Relevant log entries..."
Zeiteintrag wird aber trotzdem angelegt,

#### Steps to reproduce
Erzeugen eines neuen Zeiteintrags. 

#### Reproducable on demo.kimai.org? [yes|no]
Nicht nachvollziehbar, da kein Einblick in die Apache Logs des Demo-Servers möglich.

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
dev 1.2.1.1393 (github master)

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[Tue Sep 05 18:37:46.185517 2017] [php7:notice] [pid 2516:tid 1900] [client ::1:52870] PHP Notice:  Undefined index: fixedRate in extensions\\ki_timesheets\\processor.php on line 494, referer: http://localhost/kimai/core/kimai.php

#### First analysis
In https://github.com/kimai/kimai/blob/968bceaa009db4e6fc1ab8ec36dce04905b0b397/extensions/ki_timesheets/processor.php#L494 wird im $_REQUEST vom Browser per POST-Daten kein fixedRate übermittelt, da dies in der HTML Form in add_edit_timeSheetEntry.php über https://github.com/kimai/kimai/blob/968bceaa009db4e6fc1ab8ec36dce04905b0b397/extensions/ki_timesheets/templates/scripts/floaters/add_edit_timeSheetEntry.php#L183 ausgeblendet wird. 

Auf den ersten Blick kommt es zu keinen Folgefehlern wenn die Zeile 494 in processor.php auskommentiert wird.

**Comment by bluefire42** [comment]
Der Fehler kann aus meiner Sicht behoben werden, wenn die if-Abfrage unter https://github.com/kimai/kimai/blob/968bceaa009db4e6fc1ab8ec36dce04905b0b397/extensions/ki_timesheets/templates/scripts/floaters/add_edit_timeSheetEntry.php#L183 um einen Else-Zweig mit Versteckten Input-Feldern erweitert wird:
<?php else: ?>
    <li>
        <input id="rate" type="hidden" name="rate" value="<?php echo $this->escape($this->rate) ?>" size="5" tabindex="10"/>
        <input id="fixedRate" type="hidden" name="fixedRate" value="<?php echo $this->escape($this->fixedRate) ?>" size="5"
               tabindex="10"/>
    </li>
<?php endif; ?>
Bei mir wurden die Fehlereinträge im Log dadruch eliminiert. Kann das jemand gegenprüfen?

**Comment by simonschaufi** [comment]
Ich bin absolut gegen dirty hacks, stattdessen sollte im processor eine Abfrage gemacht werden, ob der Wert gesetzt ist.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
