### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by senaphet** [kimai/kimai#1049]
During installation step by step, the installation remains blocked after "system requirement".
The next step is displayed but contains no information, no fields, no buttons.

I get the impression that the autoconf.php file does not create.

The prerequisites seem good to me. I do this installation on a Gandi Simple Hosting server.

Permissions seem good (755).

Do you have any idea about the origin of blocking?

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]

Github master

Tanks

**Comment by senaphet** [comment]
The local installation focuses properly.
The copying to the remote server of the autoconf file (By obviously modifying the connection information to the database. A doubt about $ password_salt.) And database tables give a blank screen to the opening of Kimai.

**Comment by kevinpapst** [comment]
Sorry for the late response. Kimai needs write permissions to some fodler for creating cache files and such. That is checked during the installation. If you copy stuff over manually, you have to make sure that everything is setup properly on your own.
Please try changing permissions recursively to 777 for a first test if that is your problem.

**Comment by rasusmilch** [comment]
With latest stable 1.2.2 I get the same issue. This error was found in the log
```
[Wed Mar 28 22:37:41.923961 2018] [fcgid:warn] [pid 12476] [client xx.xx.xx.xx:xxxxx] mod_fcgid: stderr: PHP Fatal error:  Can't use method return value in write context in ../kimai/includes/func.php on line 344, referer: http://www.example.com/kimai/installer/index.php
```

I'll be trying the git version shortly.

**Comment by kevinpapst** [comment]
You are (very likely) using an incompatible PHP version. I guess we raised the requirement to PHP 5.6.
And please open a new issues
