### ISSUE TITLE
Aligning field names with table

### ISSUE THREAD

**Issue by stephenreda** [kimai/kimai#105]
I thought this was just a problem with my translation file, but it is actually a general issue:
when in the tab 'Export', the field names are not aligned with the table.
I don't know what would be the best solution here. 
Maybe working with abbreviations?
Or having the word 'cut' when the length of a field is being exceeded (maybe having the full word appear on hover over)?
This is not really an urgent issue, but it should clarify this already dense tab.

![21nqwdc](https://f.cloud.github.com/assets/2557554/142619/30c7b3f2-7305-11e2-9dbb-897e70cd928a.jpg)

**Comment by simonschaufi** [comment]
something like this will probably help us:

- http://stackoverflow.com/questions/11499973/how-to-fixed-table-header-no-jquery
- https://css-tricks.com/persistent-headers/
- http://charliepark.org/css-only-sticky-headers/
- http://mkoryak.github.io/floatThead/
- https://github.com/jmosbech/StickyTableHeaders
- http://tympanus.net/Tutorials/StickyTableHeaders/
- http://tympanus.net/codrops/2014/01/09/sticky-table-headers-columns/
