### ISSUE TITLE
Add custom field to a timesheet entry

### ISSUE THREAD

**Issue by sobryan2** [kimai/kimai#1050]
I would like to be able to add a custom field to a timesheet entry, specifically a double numeric value and have this field available for export as well.  

Not sure if there's an option to do this or if this would be a custom request / enhancement.  If there is some code changes that can be done to accomplish this, that would be great to hear as well.

Thank you

Version:
1.1.0

**Comment by simonschaufi** [comment]
There is no proper way (yet) to extend kimai. You have to "patch" kimai yourself. The best to do it properly is with git branches. That is how I do it myself. These branches can then be easily rebased.
