### ISSUE TITLE
I can't configure our User and assign a specific password

### ISSUE THREAD

**Issue by SomeSortOfName** [kimai/kimai#1053]
Hello,

yesterday I've installed Kimai on our server, the OS we're running is Windows Server 2012 R2.
The installation went without any issues and connected Kimai to our MySQL Database (MySQL Community Server). After the installation, I've logged in as an Admin and tried to configure our groups, global roles, and user. 
Shortly I came to the point where I wanted to assign a User to a specific global role but whatever I've tried the user did always get the role "admin". Furthermore did the password of every single user besides the admin resets over and over.

I'm kind of clueless what's the problem. 
Of course, I've used the actual Kimai Version. Does Kimai miss some kind of rights to write or change entries?

I would appreciate your help.
Thank you in anticipation!

**Comment by kevinpapst** [comment]
Sorry for the delay. Did you figure it out by now or have you removed Kimai due to frustration?
I would check the Mysql version first, probably there is a problem with the used version and the sql Kimai uses. Or there is a bug, which Kimai version did you try?

**Comment by simonschaufi** [comment]
no response.
