### ISSUE TITLE
Listing expenses are not working over remote API

### ISSUE THREAD

**Issue by Viras-** [kimai/kimai#1054]
#### Expected behaviour
List of expenses should be fetched over JSON API.

#### Actual behaviour
GetExpenses does not work correctly when called over the JSON API. The query is invalid.

#### Steps to reproduce
Call getExpenses over JSON API interface.

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
All versions so far

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
None

**Comment by simonschaufi** [comment]
fixed.
