### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by marty6000** [kimai/kimai#1056]
Good evening,

What ports should be forwarded on my firewall so that my mobile device may talk to the database through TimeTrapp?

Thanking you in advance.

**Comment by simonschaufi** [comment]
Sorry, we are not maintaining timetrap. please get in contact with the developer.

**Comment by Viras-** [comment]
Hi Marty - we are the maintainer of TimeTrapp.

You only need to have http or https Ports forwarded (the same ports you would use for exposing the "normal" webinterface).

In case of any questions or if you need help please contact timetrapp@senegate.at

**Comment by simonschaufi** [comment]
@Viras- could you make the source code open source? Even just creating a project on github can help report bugs so that people don't post them here.
