### ISSUE TITLE
Add new project - No list of customers and activities  

### ISSUE THREAD

**Issue by DanSman** [kimai/kimai#1058]
Hello,

i just installed Kimai under a raspberry pi stretch.

It's running with nginx, mariadb and php7. ( everything up2date)

I added a few customers and activities. Problem is if i wanna add a new project i don't get a list of the new added customers and activities. It's only the "test-customer" and "testing" ( activities). So that's the only choose able list what i get.

Debug
`[08.10.2017 19:21:43] E_NOTICE Undefined index: activity_ID @../kimai/libraries/Kimai/Database/Mysql.php line 330 ` 

Mysql.php line 330
`330                        if ($viewableElement[$idField] == $allElement[$idField]) {`

Don't know what to change there.

Checked it on the demo.kimai.org without any problems.
Kimai version is github master.

Thanks,

Dan

Edit:
I'm sorry.
The problem was the guy on front of my laptop :/ I putted the activities and customers in a different group. So i couldn't "see" them with the admin user. 
Sorry ;)

**Comment by simonschaufi** [comment]
ok. Anyway, there shouldn't be any undefined indexes. Could you please provide a stack trace to this?

**Comment by DanSman** [comment]
Sry, I'm very new to this stuff and github. What do you need?

**Comment by simonschaufi** [comment]
since kimai works on any "normal" webserver, there must be a specifig problem with your raspberry pi. Since I don't have one myself, I need your help.
I need any kind of information of an error (in nginx log for example) or any other debug information why you don't see what you expect.

**Comment by simonschaufi** [comment]
ok, issue seems to be solved.
