### ISSUE TITLE
Wondering if there are any instructions (or other success stories) about skinning/theming kimai? 

### ISSUE THREAD

**Issue by mareeba** [kimai/kimai#1059]

**Comment by mareeba** [comment]
@simonschaufi thanks for the prompt reply. I am very interested in working on some UX impovements so would you mind sharing any relevant docs or info that could assist me with this? Could you also please elaborate when you say the html templates are not able to be updated easily anymore?

**Comment by simonschaufi** [comment]
There are ni docs for design. Just have a look on the existing themes.
I mean when you change things outside of the themes folder, they will get overwritten on an update. The best is to create a git branch for that so you can always rebase your work on top of any changes that we are doing.

**Comment by kevinpapst** [comment]
Let me say: I tried it two times and I failed. By it I mean, I tried to built Kimai with a really different UI, using modern frontend frameworks. 

Kimai was just not built with a Template engine like Twig and all the javascript its tightly coupled to the html. I don't think that its doable without a lot refactoring in the main codebase.

For now, you should stick with changing the css via themes (see the linked resources by @simonschaufi )
