### ISSUE TITLE
Variable amount of expenses

### ISSUE THREAD

**Issue by amnesiemaniac** [kimai/kimai#1060]
Hey there!
While writing a new template for my invoices, I had a look on variables available. There a variables for almost everything needed

[var.ttltime] Total amount of hours
[var.vat] Total VAT sum
[var.amount] Total sum without VAT
[var.total] Total sum including VAT

Only a variable for total sum of expenses is not listed in documentation.
Is there one I didn't see or if it's not available already, can you create it?

Thanks
Michael

---- edit ---- 

a second variable could be 'days to pay' to calculate the date you want your money (Zahlungsziel)
this is not always the same so I have to edit this manually in my invoices.

**Comment by kevinpapst** [comment]
Hi Michael,
the sum of "expenses only" is currently not calculated, sorry!
Same goes for the Zahlungsziel Variable. 
That would have to be entered before sending the invoice form.

We accept Pull requests, so if you would like to add that, jou would need to add the data to the PrintModel: 
https://github.com/kimai/kimai/blob/master/libraries/Kimai/Invoice/PrintModel.php 
after calculating it somewhere around:
https://github.com/kimai/kimai/blob/master/extensions/ki_invoice/print.php#L103

**Comment by amnesiemaniac** [comment]
I'm without experience in php or using github, never pulled anything, But sources looks readable and on first impression that seems not too hard. I'll give a try.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
