### ISSUE TITLE
Secret variable

### ISSUE THREAD

**Issue by amnesiemaniac** [kimai/kimai#1061]
Hey again,

trying to list expenses in an invoice a found this in long.odt, an example from you I think.
[row.desc][row;block=table:table-row; when [row.type] = expense]

row.type is not listed in your documentation.
Wich values can it have?

**Comment by kevinpapst** [comment]
You could find that out by printing row.type instead of using it in an "if".
But I believe it can be "timesheet" or "expense".

**Comment by amnesiemaniac** [comment]
thx Kevin,
I'm trying to understand this []-Syntax but I'm not experienced with php. (It's php?)
I try to write a command to list timesheet-entrys and expenses in a table.
Your templates are a good start, I'm looking at 2016.odt and long.odt.

Timesheet-Entries:

[row.desc][row.description;if [row.description] != '';then '	'][row.description][row;block=table:table-row] | [row.date;frm='dd.mm.yyyy'] | [row.fDuration] | [row.amount;frm='0,00'] 				[var.currencySign]

For expenses i've found this:
[row.desc][row;block=table:table-row; when[row.type] = expense] | [row.comment] | [row.date] | [row.multiplier; frm='0.00']x | [row.amount;frm='0.00'][var.currencySign]

I'm not able to prevent that en expense is listed as a timesheet-entry. I don't understand how to cobine this if..and that when part. That was I have tried:

[row.desc][row.description;if [row.description] != '';then '
'][row.description][row;block=table:table-row; when [row.type] =timeSheet ]

**Comment by simonschaufi** [comment]
It's not php as this is in open office context. The 2016 template is from me. I use this myself for my invoices.
If you are more interested in the notation, here is the official documentation: http://www.tinybutstrong.com/manual.php#html_side

**Comment by amnesiemaniac** [comment]
thx 
I'll read a little bit.

**Comment by simonschaufi** [comment]
The open office context is a bit more limited as the html one but I'm sure you know that :)
