### ISSUE TITLE
PATCH for Invoices: Make customer list filterable

### ISSUE THREAD

**Issue by abaumg** [kimai/kimai#1063]
When creating an invoice, finding the right customer can be a real pain if you have lots (say, hundreds) of customers. Therefor, I created a quick patch to address this issue.

[invoices_filter_customers.patch.txt](https://github.com/kimai/kimai/files/1411010/invoices_filter_customers.patch.txt)

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
