### ISSUE TITLE
Language preferences load in wrong order

### ISSUE THREAD

**Issue by jboothe** [kimai/kimai#1064]
#### Expect to see all terms in English when setting language preference to `en`. 
<img width="452" alt="screen shot 2017-11-02 at 5 40 59 pm" src="https://user-images.githubusercontent.com/3723481/32351916-6f74754e-bff5-11e7-9c11-4732aec428c7.png">

#### Actual see a mix of English and non-English terms in the UI. 
<img width="1059" alt="screen shot 2017-11-02 at 5 40 04 pm" src="https://user-images.githubusercontent.com/3723481/32351924-75245d6a-bff5-11e7-9627-90eaf874ec8a.png">

**Comment by kevinpapst** [comment]
Thanks for the finding!
I guess I could reproduce it. 
First I tried to switch the user preference: first change to nordic, than the user language to es than back to en. Everything worked fine.
But there is a second language setting, which is in the "Advanced" section of the admin panel. That currently seems to override the users setting, which is simply wrong.
The user language preference should always overrule the system setting.

**Comment by logological** [comment]
The problem affects the [Demo installation](http://demo.kimai.org/).  Currently the demo UI shows a mixture of Russian and English. By fumbling around, I was able to locate what looks like a language setting and change it to English, but it had no effect on the UI labels.  This makes it impossible for me (and everyone else who doesn't speak Russian) to use the demo.

**Comment by kevinpapst** [comment]
I switched the demo back to english @logological

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
