### ISSUE TITLE
Time difference in time recording

### ISSUE THREAD

**Issue by TW-SWG** [kimai/kimai#1067]
#### Expected behaviour
Time difference in time recording
![kimai-zeiterfassungsproblem](https://user-images.githubusercontent.com/33417229/32436314-f286f8e4-c2e3-11e7-8ef9-e8560c549f11.JPG)

#### Actual behaviour
When starting the time recording, the time in the header differs from the start time in the list.
 What can I do to sync this time?

#### Steps to reproduce
start time recording 

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
0.9.2.1306

**Comment by simonschaufi** [comment]
make sure the server time is correct.
