### ISSUE TITLE
Multiple users recording time on same job.

### ISSUE THREAD

**Issue by carrolltondatago** [kimai/kimai#1069]
#### Expected behaviour
All users login and start recording time on the same job.

#### Actual behaviour
Will not allow them to do this consistently sometimes only 1 user allowed to record time sometimes 2 have been able to.
#### Steps to reproduce
user logs in starts time on a job
2nd user logs in starts time on job and sometimes can others can't

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
latest

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
