### ISSUE TITLE
How to prevent users to change their timesheet when status is review or closed

### ISSUE THREAD

**Issue by lboutet** [kimai/kimai#1070]
#### Expected behaviour
Would it be possible to prevent non admin users to update their timesheet when they are on review or closed ?

#### Actual behaviour
What ever the timesheet status is, a non user can change everything. We would like to have people that valide the timesheet, and when they are validated, not further change would be possible for non admin users

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Last

**Comment by simonschaufi** [comment]
As this is customer specific, we can offer you this feature as a payed feature. Please let us know if you are interested in that.

**Comment by jstifter** [comment]
I would be interested in this feature too. SimonSchaufi, can you get in touch with me please. Deutsch geht auch.
Jan

**Comment by simonschaufi** [comment]
@jstifter Since you don't have your email address made public on github and you also don't have any repo where I could find your email address, you are the one who has to contact me ;) Please use my github username @ gmail . com
