### ISSUE TITLE
Select too many users - [object Object] pop-up

### ISSUE THREAD

**Issue by julianocas** [kimai/kimai#1071]
Hello, when I select several users to extract a month, for instance, I always receive a persistent message [object Object].

![1](https://user-images.githubusercontent.com/34235653/33548382-244542d2-d8ce-11e7-9c9d-80cf12266417.PNG)

Can someone help me solve this issue? Thank you!

**Comment by julianocas** [comment]
I think I solve the issue giving more memory to PHP server.

It was with 128mb and 30 seconds to timeout. I have changed to 1024mb of cache and 5000s of timeout.

**Comment by simonschaufi** [comment]
ok. Anyway, please don't use more than 120s timeout. php scripts should rarely run so long in the frontend.
