### ISSUE TITLE
Description text with special letters is not shown 

### ISSUE THREAD

**Issue by wpcata** [kimai/kimai#1072]
I may have found one of the strangest bugs...

#### Expected behaviour
A description text with "ä", "ö", "ü" or "ß" should be shown in the timesheet-view.

#### Actual behaviour
If the 49th letter in a description is a "ä", "ö", "ü" or "ß" and the previous part contains exactly one of these special letters the description is not shown.
For example: "     ä                                          ß"

#### Steps to reproduce
Write a random description text with one special letter and a special letter on the 49th position.

#### Reproducable on demo.kimai.org? [yes|no]
Yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai 1.1.0.1389
Kimai dev 1.2.1.1393

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
---

**Comment by wpcata** [comment]
I just saw that my example string got cut...
This should (not) work:
"1234 ä234 1234 1234 1234 1234 1234 1234 1234 124ß"

**Comment by simonschaufi** [comment]
yeah, I can also confirm that on my own server in dev branch. Maybe it has something to do with multibyte character or html escaping

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
