### ISSUE TITLE
json api

### ISSUE THREAD

**Issue by datPhil** [kimai/kimai#1073]
I just testet kimai time tracking and due to the fact that I do not use a smartphone I'd like to write a client for linux.
So I call http://server/time/core/json.php with following command:
curl --data '{"jsonrpc":"2.0","method":"authenticate","params":["<user>","<pw>"],"id":"1"}' http://<server>/time/core/json.php

That works. It also worked with https. The issue I'm facing is that the apikey I get seams to be valid for ever.

I can query with the following command a week later with the same apikey.
curl --data '{"jsonrpc":"2.0","method":"getProjects","params":["<apikey>"],"id":"1"}' http://<server>/time/core/json.php

I want to get the apikey invalid after a period of time.

**Comment by simonschaufi** [comment]
What you mean is a session token, not an api key. An api key will never expire by definition.
If there needs something to be changed in kimai, please make a pull request.

**Comment by datPhil** [comment]
Well, what I get as result of an authentication is something which looks like:
{"result":{"success":true,"items":[{"apiKey":"5a07bee457c78dc1d5efab83c"}],"total":1},"id":"1","jsonrpc":"2.0"}

Whether this a apiKey or a session token - I don't mind. The fact is, that I can use this key for a very long time. I did not try to reboot the server and reuse that key.

I don't know whether there is the need to change something or if there is a possibility to solve it configurationally.


By the way - did someone ever manage to add a timerecord via json? I sorted out some inconsistencies of naming. But now I got stuck at:

 curl --data '{"jsonrpc":"2.0","method":"setTimesheetRecord","params":["5a07bee457c78dc1d5efab83c",{"start":"2017-12-12 14:00:07","end":"2017-12-12 14:30:07","projectId":"8","taskId":"2","userID":"210378711","customerID":"6","projectComment":"Test","location":null},false],"id":"1"}' http://<server>/time/core/json.php

and get result:

{"result":{"success":false,"error":{"msg":"Failed to add entry."}},"id":"1","jsonrpc":"2.0"}

and in serverlog:

[Wed Dec 13 11:15:07.556823 2017] [:error] [pid 9663] [client <clientip>:52692] PHP Notice:  Undefined index: billable in /var/www/html/time/libraries/Kimai/Database/Mysql.php on line 2322

is this a bug or is there an error in the call?

Cheers
Phil

**Comment by simonschaufi** [comment]
I never used the json api so far but I know it is used for the kimai app for example. My idea is that once you login, you get the api token for that user and can communicate with kimai as long as you want. If you want to logout and login with another user, you need to take care of this yourself and start another authentication and get the api token for the new user.

> is this a bug or is there an error in the call?

You can play around with the [jQueryUi version](https://github.com/kimai/kimai-mobile) of kimai and see, if the error happens there as well. If yes, it is a bug on our side.

**Comment by kevinpapst** [comment]
As @simonschaufi mentioned, API keys do not expire. You can only revoke them via database by now. The idea is that you let your customer authenticate once and then store that API key at a safe place - way better then storing the original credentials. 

Regarding the log entries. That is missing validation on the API part and missing data on your end. You have to supply all necessary values to add a correct timesheet entry. Just check the Mysql.php around the lines mentioned in your log to see which fields you have to add.
