### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by Viras-** [kimai/kimai#1076]
What are the chances of getting a new version released soon?

Our app would like to include support for expenses, but this can't be done without releasing a new version containing the bugfix for the expenses remote API.

Maybe we can be of any help for a new release?

**Comment by simonschaufi** [comment]
Hi,
the thing is, I'm the only maintainer of kimai right now and I'm focussing on other projects right now. There is so much to be done as kimai code is really old and hard to maintain but a new release should be possible asap. I would like to merge develop branch into master but there is a still a bug with https://github.com/kimai/kimai/pull/1047 which is the biggest blocker right now. If you could help me fix this bug, I would highly appreciate that! Any help is welcome!

**Comment by Viras-** [comment]
I will take a look and see if I can fix it.

In addition, if you wish you can add me as maintainer as well. I won't have too much time either but if desired I can help out.

**Comment by simonschaufi** [comment]
Thanx!
Even without being a maintainer you could help us a lot already. You can make pull requests and you can verify other pull requests. If you ping me when you verified a pull request, merging it is just a simple click ;) The pain is always to test the pull requests and that takes a lot of time...

**Comment by Viras-** [comment]
Sure - I will do my best to help the speeding up the development.

**Comment by simonschaufi** [comment]
@Viras- could you have a look into the issue? Today I release a new version but the issue 905 is excluded from it as it is just not running perfectly.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
