### ISSUE TITLE
QR Code login

### ISSUE THREAD

**Issue by gizmo2004** [kimai/kimai#1077]
hi , i have a question , can it be realize to login in with a qr code on my kimai site ? 

thanks
gizmo2004

**Comment by alexanderdd** [comment]
Same question here. 

I am looking for a solution where employees use a qr code to log their time at a tablet at the entrance. Any suggestions? Thank you!

**Comment by simonschaufi** [comment]
Well, the first request was about login, the second request is about time tracking (starting and stopping).
Everything can be implemented if you are willing to pay for it. Kimai is open source but not everything is for free.

**Comment by alexanderdd** [comment]
Thanks Simon for the quick reply and the clarification. Keep up the good work.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
