### ISSUE TITLE
Question about duration

### ISSUE THREAD

**Issue by mibsk** [kimai/kimai#1083]
Hello,

I just would like to ask, why it is possible record more than 24 hours per day.

#### Steps to reproduce
For example: (under admin account)
Start date: 1.1.2018, start time: 08:00
End date 1.1.2018, end time: 23:55
Total duration: 15:55
Repeat this (add the another record for same customer, project an activity with the same start and end date/time.)
[screen](https://ctrlv.cz/QFJa)
Total: 31:50 :(
#### Reproducable on demo.kimai.org? [yes|no]
yes
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
 v1.2.1.1393
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

Thank you.

**Comment by simonschaufi** [comment]
Simply because we don't want to limit people using kimai. Every user is responsible for his own time recordings. Kimai is used in so many different companies, it would be impossible to configure something that everyone will be happy with.

**Comment by mibsk** [comment]
OK. Thanks for explanation.
