### ISSUE TITLE
Excel exports size 0kB

### ISSUE THREAD

**Issue by TeunConfed** [kimai/kimai#1085]
#### Expected behaviour
With the use of the excel export button export selecting lines.
#### Actual behaviour
Exported files contain no data
#### Steps to reproduce
Select data from kimai and push Excel export.
#### Reproducable on demo.kimai.org? [yes|no]
No
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
When exporting using the CSV option, I receive data. Also PDF export works

**Comment by simonschaufi** [comment]
Sorry, this is too little information and as it is not reproducable on the demo installation, I also cannot reproduce it.

**Comment by TeunConfed** [comment]
Sorry for my short information. The logfile also indicated the following lines:
[09.01.2018 14:21:09] KSPI axAction (admin): export_xls
[09.01.2018 14:21:11] Uncaught exception: Class 'ZipArchive' not found

Maybe you can point me out in which direction I can search in the source?
I also have seen that another issue exists concerning export to XLS where no data is exported. # 982
But I don't know if it is exactly the same issue.

**Comment by kevinpapst** [comment]
Seems your server is missing the required PHP extension.
See docu: http://php.net/manual/en/class.ziparchive.php
Do you manage that server by yourself? If so, you could try to install the zip package.

**Comment by TeunConfed** [comment]
We manage the server and I will try to install the package.

We did an upgrade to a new version of Kimai and the functionality worked before. That was the reason I wasn't thinking of missing any package. 

I'm going to install the package and will let you know that it works.
Thanks for your response and help.

**Comment by TeunConfed** [comment]
Installation is done and functionality is up and running.
Thanks!

**Comment by simonschaufi** [comment]
What OS are you using? In Ubuntu this package is  installed by default.

**Comment by TeunConfed** [comment]
We are using Ubuntu, 16.04.

But the functionality only worked after the manual installation.
Do you need some more information?

**Comment by simonschaufi** [comment]
Ok, then we need to update the documentation

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
