### ISSUE TITLE
LDAP problem in auth.php

### ISSUE THREAD

**Issue by MathieuLeGuyader** [kimai/kimai#1087]
Hello, 

When i change the authentification LDAP to Advaced LDAP in autoconf.php, i have this log in apache

PHP Fatal error:  Uncaught Kimai_Auth_Exception: LDAP-Extension is not installed in /var/www/kimai/libraries/Kimai/Auth/Ldap.php:70\nStack trace:\n#0 /var/www/kimai/index.php(59): Kimai_Auth_Ldap->__construct(Object(Kimai_Database_Mysql), Array)\n#1 {main}\n  thrown in /var/www/kimai/libraries/Kimai/Auth/Ldap.php on line 70

Can you tell me where is my problem ?

thank you

**Comment by kevinpapst** [comment]
Sure, the error states that the LDAP extension is not installed:
http://php.net/manual/en/book.ldap.php

So try something like `apt install php-ldap` or `yum install php7-ldap` ... these commands were not tested, it depends on your server!
