### ISSUE TITLE
While deploying Kimai open Source Time Tracking in XAMPP, i am facing PHP version issues?

### ISSUE THREAD

**Issue by VinayGuruswamy-2018** [kimai/kimai#1089]
System Requirements
The following conditions must be met:
at least PHP version 5.4
The MySQLi extension for PHP has to be loaded
The iconv extension for PHP has to be loaded
The DOM extension for PHP has to be loaded

For PDF export the following requirement must be met:
Allowed memory usage should be at least 20MB
See memory_limit in php.ini file
![kim_diag](https://user-images.githubusercontent.com/35131214/34981751-79dae806-face-11e7-8f2b-b28b9fa982f8.png)

**Comment by kevinpapst** [comment]
So what? Which PHP version do you use?

**Comment by VinayGuruswamy-2018** [comment]
I am using 7.0.26 , but even i am getting the same issue. i am using kimia via xampp.

**Comment by kevinpapst** [comment]
That code checks the php version: https://github.com/kimai/kimai/blob/master/installer/processor.php#L81
I wonder why that should trigger. Just delete lines 81 to 84 from the linked file and retry

**Comment by VinayGuruswamy-2018** [comment]
![kim_cap](https://user-images.githubusercontent.com/35131214/34986125-6c58738e-fadc-11e7-8b58-3cb20cb9e8d8.PNG)
![kim_same_diag](https://user-images.githubusercontent.com/35131214/34986126-6c8a9ae4-fadc-11e7-91ad-6df9da5306be.png)

**Comment by VinayGuruswamy-2018** [comment]
Once again after commenting 81 to 84 line, i am facing the same issue.

**Comment by kevinpapst** [comment]
I haven't touched the installer for a long time, probably the error lies here:
https://github.com/kimai/kimai/blob/master/installer/steps/25_system_requirements.php#L40
Please try to remove the class "fail" - I don't know why this is active by default.

**Comment by VinayGuruswamy-2018** [comment]
Now i am facing DB error,  I have created DB named kimai. Not able to open DB.
![kimai_db](https://user-images.githubusercontent.com/35131214/34989951-593189ae-faea-11e7-8db9-f2d788928890.PNG)

**Comment by VinayGuruswamy-2018** [comment]
![db_error_extradb](https://user-images.githubusercontent.com/35131214/34991647-5bdedfde-faf0-11e7-8d5e-4e1a139f1f6e.PNG)
![db_error_mysql](https://user-images.githubusercontent.com/35131214/34991648-5c1195aa-faf0-11e7-8874-5d6f8693d4d0.PNG)
![db_error_postgresql](https://user-images.githubusercontent.com/35131214/34991649-5c4983fc-faf0-11e7-8228-798fcf00350e.PNG)
