### ISSUE TITLE
Should we delete Security folder,which is in htdocs/kimai/installer? 

### ISSUE THREAD

**Issue by VinayGuruswamy-2018** [kimai/kimai#1090]
I am facing this issuses, Should we delete Security folder,which is in htdocs/kimai/installer.
![security](https://user-images.githubusercontent.com/35131214/35029058-0e4dc886-fb7f-11e7-8ff3-4c38c6a26120.png)
![security1](https://user-images.githubusercontent.com/35131214/35029059-0e7ee632-fb7f-11e7-9489-af8c0ac1f313.png)

**Comment by kevinpapst** [comment]
Yes, you should delete it.

**Comment by VinayGuruswamy-2018** [comment]
![activity](https://user-images.githubusercontent.com/35131214/35040772-65e91928-fba8-11e7-836e-2f15c811f43d.PNG)
![project](https://user-images.githubusercontent.com/35131214/35040773-6618ce98-fba8-11e7-91ca-b07d901558ae.PNG)
