### ISSUE TITLE
Calendar API - eg iCalendar (ICS) export

### ISSUE THREAD

**Issue by wittich** [kimai/kimai#1092]
Is there any project/plugin which tries to export the Kimai data to an ICS calendar? 

I think that would be a useful feature for an overview what has been the work for the last days (at least on a user level). 

_That could be also an easier method for the [issue-976](https://github.com/kimai/kimai/issues/976)._

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
