### ISSUE TITLE
Is someone interested in changing open issue 967?

### ISSUE THREAD

**Issue by Marcel-Reis** [kimai/kimai#1098]
I'm interested in paying for it. But i need a recipe. We can pay via paypal or bank transfer.

https://github.com/kimai/kimai/issues/967

**Comment by kevinpapst** [comment]
Please consider placing a bounty: 
[![bountysource](https://api.bountysource.com/badge/issue?issue_id=1098)]

**Comment by Marcel-Reis** [comment]
Hallo Kevin,

Ich brauche leider wieder eine Rechnung und kann es daher nur via Paypal
oder Überweisung machen. Hab es nun auch rein geschrieben. Ich hatte dir
das Geld ja auch im Voraus geschickt. Das ist für mich generell kein
Problem solange dann die Arbeit auch erledigt wird. Ich kann es dir aber
auch bar geben wenn dir das nach der Erledigung lieber ist. Ich arbeite ja
in Zuffenhausen. Glaub du hast in Stuttgart gewohnt oder?

Gruß,
Marcel

2018-01-26 8:27 GMT+01:00 Kevin Papst <notifications@github.com>:

**Comment by kevinpapst** [comment]
Du bringst mich mit Simon durcheinander.

Am 26. Januar 2018 um 10:11 schrieb Marcel-Reis <notifications@github.com>:

**Comment by Marcel-Reis** [comment]
Ist mir dann auch aufgefallen ;-) Hab dir ne Mail direkt geschickt über
deine Website.

Gurß,
Marcel

Am 26. Januar 2018 um 10:28 schrieb Kevin Papst <notifications@github.com>:

**Comment by whitetuna1** [comment]
Hi Marcel-Reis.

I may be able to help with this, but from what I've read it's not something deemed necessary or practical so I'm not sure about how to go about it without contributing to the source code for everyone. I haven't really used GitHub and I'm not familiar with Bountysource.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
