### ISSUE TITLE
Default skin

### ISSUE THREAD

**Issue by eglyn** [kimai/kimai#1099]
Hi :)

I made a new skin for Kimai, and I want it to default to all accounts.
I found a file "autoconf.php" in which the skin is specified, but it does not work.
Is there a way to do it differently?

Thank you in advance.

**Comment by kevinpapst** [comment]
Every user has its own settings, so you have to update the database directly with an SQL script. There is no option to force the skin for a user.

**Comment by eglyn** [comment]
Ok thx :)
