### ISSUE TITLE
Resurrecting the password salt

### ISSUE THREAD

**Issue by demsley** [kimai/kimai#1100]
#### Expected behaviour
This is entirely my bad but I need some advice if possible.

#### Steps to reproduce
The drive hosting the kimai folder has fried.  Thus I do not have the old autoconf.php file.

I've reinstalled Kimai on a new drive and manually edited the autoconf.php to access the old database but, of course, the salt is different.  I cannot use the forgotten password option as the server does not send emails. 

#### Reproducable on demo.kimai.org? [yes|no]
No

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai 1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

Help and advice appreciate.

Dave

**Comment by simonschaufi** [comment]
You can create the pw hash yourself with this function: https://github.com/kimai/kimai/blob/master/includes/func.php#L595. Echo the hash and copy paste it in the db field for the user. then you can login again.

**Comment by demsley** [comment]
simonschaufi you are a star.  Many, many thanks.

**Comment by simonschaufi** [comment]
if you want to appreciate your thanx financially, on the kimai website is a paypal donation link ;)
