### ISSUE TITLE
Windows Domain Auth

### ISSUE THREAD

**Issue by acschristoph** [kimai/kimai#1102]
#### Expected behavior
Authenticate over windows domain users
#### Actual behaviour
In the docs are described that includes/autoconf.php should change to $authenticator = "activeDirectory";

But I don't have this file in my includes dir. I Have the same files that are in the GitHub repo.

basics.php	
func.php	
kspi.php
version.php

#### Steps to reproduce
Download the latest version
#### Kimai version
If I want to update over the web.ui kimai says I use the latest version

can anybody described me how can I used windows domain user auth with kimai =)

Br Christoph

**Comment by simonschaufi** [comment]
you first have to install kimai, then the autoconf.php file will be created.

**Comment by acschristoph** [comment]
ok, that makes sense ;) I don't know why is it lost but I had reinstall kimai and I have now this file.
So I change now the $authenticator = "activeDirectory";  value
Now I should create the auth.php file with this values right:
<?php
return array(
    'host' => 'ldap://localhost',
    'enhancedIdentityPrivacy' => 'false',
);
Thank you for helping

**Comment by simonschaufi** [comment]
Sorry, non of the developers can help you with that as we have never done it ourselves but please read the documentation. If you figured it out, we are glad if you could extend the documentation with a new chapter about this topic! 🎉

**Comment by timlegge** [comment]
Just seeing this.

 $authenticator = "activeDirectory"; simply extends $authenticator = "ldapadvanced";

I have used ldapadvanced in my install and the documentation is at https://github.com/kimai/www.kimai.org/blob/master/documentation/authenticator.md

Ldap is a bit of a pain to setup because you need to understand how your LDAP /AD installation is setup.   If you are still having issues let me know

**Comment by asaadhoussam** [comment]
hi 
External authentication systems such as LDAP are used only to verify a user's identity?
are not used to give access to any components within the application as the external system?

**Comment by asaadhoussam** [comment]
thank you simonshaufi
Can you help me understand the mechanism that the system uses to manage Role-Based Access Control on the KIMAI application?
thanks

**Comment by simonschaufi** [comment]
Sorry, I never really understood it myself.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
