### ISSUE TITLE
What's the use of this button?

### ISSUE THREAD

**Issue by Yw-melo** [kimai/kimai#1104]
As we know we click the big green button to start a timesheet,
but I don't know What's the use of this '+' button in this picture,
it is also to start a timesheet?,
![wechatimg28](https://user-images.githubusercontent.com/33000435/35724707-b10c36b8-0839-11e8-8a9c-f94e3670f4c4.jpeg)

**Comment by Yw-melo** [comment]
After click  button we can’t choose any time before today

**Comment by kevinpapst** [comment]
The button will start a new record with the project and activity of this record. 
And that button does not do anything else. There is a config somehwere that defines the earliest allowed start date, can't remember where it was, but thats likely your problem. Or try to choose a different time range in the upper middle part.

**Comment by simonschaufi** [comment]
not reproducable for me neither on demo nor on my own installation.
