### ISSUE TITLE
as user with admin permission I can not remove that user from a group

### ISSUE THREAD

**Issue by gramels** [kimai/kimai#1106]
#### Expected behaviour

User with admin permission shall be able to add and remove itself to a group.

#### Actual behaviour

User can add itself to a group but upon trying to remove it gets an error "Permission denied" red screen.

#### Steps to reproduce

add and remove yourself to group

#### Reproducable on demo.kimai.org? [yes|no]

yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
