### ISSUE TITLE
Can't change currency in Admin panel

### ISSUE THREAD

**Issue by lcgauthier** [kimai/kimai#1107]

**Comment by lcgauthier** [comment]
in the admin panel, the currency defaulted to EURO and (€).. i would like to change it to CAD, $,  i try to do the change, click save,  and it reverts back to EURO and (€).

**Comment by Tanami** [comment]
Please fill out the required fields, such as the Kimai version.

**Comment by kevinpapst** [comment]
@lcgauthier please edit the first posting and use the the

**Comment by kevinpapst** [comment]
reopen accidentally closed ticket 

@lcgauthier please edit the first posting and use our issue template fields to tell us more about your problem
