### ISSUE TITLE
Cannot add a timesheet record using API setTimesheetRecord

### ISSUE THREAD

**Issue by JonnyHonda** [kimai/kimai#1109]
I'm currently playing around with the API and have produced a basic start/stop application and I've come to the point where I wish to add/update a timesheet record.

I've been struggling to get the function **setTimesheetRecord** to work and it keeps returning **Invalid projectId**.

I've resorted to using SoapUI to poke directly at the api and I am unable to formulate an XML that successfully gets past this message.
example XML below as generated from the wsdl.

```xml
<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap="http://192.0.2.82/core/soap.php">
<soapenv:Header/>
<soapenv:Body>
<soap:setTimesheetRecord soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
         <apiKey xsi:type="xsd:string">redacted</apiKey>
         <record xsi:type="soapenc:Array" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
            <!--You may enter ANY elements at this point-->
			<projectId>1</projectId>
			<taskId>1</taskId>			
         </record>
         <doUpdate xsi:type="xsd:boolean">true</doUpdate>
      </soap:setTimesheetRecord>
   </soapenv:Body>
</soapenv:Envelope>
```

I have had a hack around the Api.php file and the above XML produces a $record in **setTimesheetRecord()** as 
`array(2) {
  [0]=>
  string(1) "1"
  [1]=>
  string(1) "1"
}
`
and I'm expecting 
`
array(2) {
  ["projectId"]=>
  int(1)
  ["taskId"]=>
  int(1)
}
`
or at least that is what I think kimai is expecting.

I may be just me, any idea what the XML soap array should look like?

**Comment by simonschaufi** [comment]
Hi,
if the API is not complete or brken, please fix it! It is quite possible, that it's broken or incomplete. If you can fix it yourself, we would really appreciate it! I'm just aware that the json api works quite well but never played with the soap one.

**Comment by JonnyHonda** [comment]
Mmmm, interesting, doesn't the json interface utilise Kimai_Remote_Api also?
So any changed there would likely break the json functions also.

**Comment by simonschaufi** [comment]
I mean if something is missing, you are free to add it. The existing code should of course still work ;)

**Comment by bastilimbach** [comment]
I'm currently experiencing the same behavior using the JSON API. The `projectId` definitely exists and all required parameters are sent. (apiKey, projectId, taskId, start, end)

**Comment by simonschaufi** [comment]
Could someone please make a pull request to fix this? It's so hard to make it myself If I don't have the environment for it available.

**Comment by bastilimbach** [comment]
@simonschaufi I'll look into this issue when I'm home from work.

**Comment by bastilimbach** [comment]
Well, that was an easy "fix". You need to send the record as an object not an array with one object. I changed my request body from:
```json
{
  "id": 1,
  "method": "setTimesheetRecord",
  "params": {
    "apiKey": "3173d5ce01908c635540d19b3",
    "doUpdate": false,
    "record": [
      {
        "projectId": 1,
        "taskId": 1,
        "start": "",
        "end": ""
      }
    ]
  }
}
```

to:

```json
{
  "id": 1,
  "method": "setTimesheetRecord",
  "params": {
    "apiKey": "3173d5ce01908c635540d19b3",
    "doUpdate": false,
    "record": {
      "projectId": 1,
      "taskId": 1,
      "start": "",
      "end": ""
    }
  }
}
```

and it worked perfectly!

@JonnyHonda You need to change your `xsi:type="soapenc:Array"` to whatever the equivalent of an object is in SOAP. 

@simonschaufi If you open `.../core/json.php` the method shows a wrong type. I'm not familiar with JSON-RPC and I don't know how to change the type to the equivalent of an object in JSON-RPC type.
```json
"setTimesheetRecord": {
      "envelope": "JSON-RPC-2.0",
      "returns": "array",
      "transport": "POST",
      "parameters": [
        {
          "type": "string",
          "name": "apiKey",
          "optional": false
        },
        {
          "type": "array", <--- This one
          "name": "record",
          "optional": false
        },
        {
          "type": "boolean",
          "name": "doUpdate",
          "optional": false
        }
      ]
    }
```

**Comment by JonnyHonda** [comment]
Ha ha. Thanks guys. Thing is I rewrote my application at the weekend to use json, but while I have your attention.

If I understand the API correctly setTimeSheetRecord either adds or updates a full complete Timesheet, and requires start and stop time.
Question. 
Is there no way to edit a running timer for say, changing project, activity, description and start time? Via the API

**Comment by simonschaufi** [comment]
The API existed long time before I jumped into the project and I know that some Apps use this API, so you are free to extend it like you want but just make sure the existing API doesn't break. I would be glad to get your pull requests!

**Comment by bastilimbach** [comment]
@JonnyHonda take a look at [https://demo.kimai.org/core/json.php](https://demo.kimai.org/core/json.php). There you can see every available method you can use. You could try to start the recording with `startRecord` , get the current running record with `getActiveRecording` and finally update the recording with the ID you get from `getActiveRecording`. It might work but I didn't test this.

To create/update a timesheet you need: 
```json
"record": {
      "projectId": 1,
      "taskId": 1,
      "start": "Tue, 27 Feb 18 22:00:00 +0000",
      "end": "Tue, 27 Feb 18 23:00:00 +0000",
      "commentType": 0,
      "statusId": 1
    }
```

The start and end can't be a Unix timestamp and commentType  0, as well as statusId 1, are the default values.

**Comment by simonschaufi** [comment]
the API basically just publishes all methods of this file: https://github.com/kimai/kimai/blob/master/libraries/Kimai/Remote/Api.php so you are free to extend it and send in your pull requests!

**Comment by JonnyHonda** [comment]
@simonschaufi and @bastilimbach , I've considered a PR and had a look through open ones and found this, which is basically similar to what is was going to submit https://github.com/kimai/kimai/pull/829/commits/c7d43c6aef3ccedbd897b36b416bca3328558349

I would probably not used have used a paramater for entryID and used the one in the data array, I wasn't considering being able  to update all the timesheetdata and would have called the function updateActiveRecording.

I'm not familiar with the PR process but I'll get something tested and go from there.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
