### ISSUE TITLE
No instructions as stated on kimai.org in the 'skins' directory

### ISSUE THREAD

**Issue by frederickjh** [kimai/kimai#1110]
#### Expected behaviour
I find instructions in the skins folder.
#### Actual behaviour
No instructions found in the skins folder.
#### Steps to reproduce
Go to skins folder as instructed on [kimai.org](http://kimai.org) and look for directions.

> You can also send us your own skin designs (**find instructions in the ‘skins’ directory**). We will also have some skins available in the future.

#### Reproducable on demo.kimai.org? [yes|no]
NA
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Current version on Github
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
NA

**Comment by simonschaufi** [comment]
thank you. we have a separate repository for the website.

**Comment by frederickjh** [comment]
Interesting fix, removing the evidence. This fix still leaves those of us interested in creating a new skin wondering about the large amount of files in each skin folder and where to start.

**Comment by kevinpapst** [comment]
LOL, you told us that the docu is wrong and that was right. So we fixed it. 
I can't remember that I ever saw docu about skins. If you have questions about skins, just open up a new issue

**Comment by simonschaufi** [comment]
The main entry point is the styles.css with a few exceptions like the login.css/error.css which is included directly in the html.
