### ISSUE TITLE
Dashboard view to allow drill downs - directly viewing the active users list etc

### ISSUE THREAD

**Issue by rarvin** [kimai/kimai#1113]
![Screenshot_20190916_182703](https://user-images.githubusercontent.com/50443902/64959932-de2edb80-d8af-11e9-96fb-7f59791f2e28.png)
The dashboard view provided the details of working hours today, working hours per week, working hours per month, the number of active user in the day, week and month too. What would be great is if these are made clickable links which could open a page and show the list of active users per day/week/month. Their contributions towards the working hours per day, week, month etc. Such statistics or drill down from the dashboard view would be helpful. 

To start with a clickable link to show the list of active users per day/week/month and their summed up daily/weekly/monthly work hours.

**Comment by rarvin** [comment]
@kevinpapst would it be possible to show just the names of the active users alone

**Comment by rarvin** [comment]
We would like to know who did some kind of work in the said day, week month. Even if you release this as a plugin it would be good. I understand that even a simple login results in an entry even if the names are shown alone it would be extremely helpful. We are doing work from home due to the COVID19 issues and now we have no way of knowing easily who were the active users for a said day or if they are currently active. An easy look from here would be good. Thanks

**Comment by kevinpapst** [comment]
At one point in the future it will be possible in Kimai directly.But thats nothing that will be there soon (from my side)...

You can always write some simple SQL queries to get the data directly from the database. Thats not beautiful and not usable from management, but the data is there - you just need to get it out of the database.

**Comment by kevinpapst** [comment]
Available through the reports nowadays.
