### ISSUE TITLE
Installer fails for php  7.1.11-0ubuntu0.17.10.1 

### ISSUE THREAD

**Issue by AaronFeldman** [kimai/kimai#1114]
#### Expected behavior

Installer allowing for installation using versions of php higher than 5.4

#### Actual behaviour

Installer does not allow php 7.1.11-0ubuntu0.17.10.1 presents the user with a red "X at least PHP version 5.4" and then refuses to further install

#### Steps to reproduce

Install php  7.1.11-0ubuntu0.17.10.1 and use the installer

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai 1.1.0       Installation v1.2.2.1394

**Comment by simonschaufi** [comment]
Sorry, not reproduceable. I also use php7.1 on ubuntu and it works fine.

**Comment by kevinpapst** [comment]
Try to remove or replace that check:
https://github.com/kimai/kimai/blob/master/installer/processor.php#L81
And let us know what you found out. 
Or at least send us the output of `echo PHP_VERSION;`.

**Comment by hh-ams** [comment]
+1
I have php 7.1 installed on debian 9.

**Comment by simonschaufi** [comment]
Please let us know the problem. That it doesn't work for you doesn't help us as it works for us.

**Comment by AaronFeldman** [comment]
I commented out the code as follows:

>   case "checkRequirements":
     /**   if (version_compare(PHP_VERSION, '5.4') < 0) {
            $errors++;
            $javascript .= "$('div.sp_phpversion').addClass('fail');";
        }
>   */ if (!extension_loaded('mysqli')) {

I stopped and started apache2 with systemctl

and the gui installer splash screen shows the following:

System Requirements
The following conditions must be met:
X at least PHP version 5.4 <------------------------------------- in red
The MySQLi extension for PHP has to be loaded
The iconv extension for PHP has to be loaded
The DOM extension for PHP has to be loaded

and it does not allow further installation at that point.

For PDF export the following requirement must be met:
Allowed memory usage should be at least 20MB
See memory_limit in php.ini file

Attached is a pdf of my 'phpinfo' output

[phpinfo.pdf](https://github.com/kimai/kimai/files/1731954/phpinfo.pdf)

**Comment by hh-ams** [comment]
commenting out line 27 in processor.php will work.
I guess, there is a problem with the reference in libraries/autoload.php.

**Comment by AaronFeldman** [comment]
commenting out line 27 in processor.php didn't work for me.

**Comment by simonschaufi** [comment]
Do you see any errors in kimai log file or php log file? Internal server error doesn't help either

**Comment by simonschaufi** [comment]
PHP_VERSION is not a system environment variable. It's only available in a php scrip

**Comment by AaronFeldman** [comment]
Looks like commenting out line 27 does work. Not sure why it did not at first.  Thanks all.

**Comment by simonschaufi** [comment]
Ok since 2 people have the problem, the third one will sooner or later also report that. What exactly is the problem?

**Comment by hh-ams** [comment]
The Bug is in your INSTALL.md - you did not mention, that it is necessary to install composer, e. g. by

apt install composer -y

and then running

composer install

in your working directory.

That's all. So the Installation will run witthout any problems.

**Comment by simonschaufi** [comment]
aha. For the zipped release files this isn't neccessary but for the git sources yes.
