### ISSUE TITLE
Payment data would be nice

### ISSUE THREAD

**Issue by AaronFeldman** [kimai/kimai#1115]
**Feature Request** 

It would be nice if we could take into account payments made to date by adding them to the timesheet and have them reflected in the invoices.  Otherwise, one has to do this by hand, which kind of defeats the purpose of automating the invoicing. If I am mistaken and this is a feature that is already available, perhaps by filling in a negative value, then please advise.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
