### ISSUE TITLE
Chats for the community

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#1116]
Is there any interest to setup a community chat somewhere in the net, to have a dedicate place for real time talk?

Possible places could be:
- https://gitter.im/ (already created a test room for kimai/kimai, see #1117)
- https://discordapp.com/
- https://slack.com/
- https://flock.com/
- https://keybase.any other suggestions?

What it should allow:
- free plan
- free integrations of third party services (like scrutinizer/travis ...)
- cloud based (there is no interest in a self-hosted product right now, as this puts additional work on us which we don't have right now)

**Comment by thedayse** [comment]
Yes - the gitter chat seems useful

**Comment by kevinpapst** [comment]
Archiving old issues. [Please switch to Kimai 2](https://github.com/kevinpapst/kimai2)...
