### ISSUE TITLE
Kimai does not detect correctly the PHP version (impossible to install)

### ISSUE THREAD

**Issue by ghost** [kimai/kimai#1122]
#### Expected behaviour
Kimai should detect correctly the PHP version:
```
[~]: php -v
PHP 5.5.14 (cli) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Coverager v3.2.0, Copyright (c) 2005-2014, by mOo
[~]: rpm -q php5
php5-5.5.14-91.2.x86_64
```

#### Actual behaviour
During install (actually upgrading from version 1.1.x) kimai shows: "at lest PHP version 5.4" (red with an 'x' in front of it, i.e. not fulfilled requirement)

#### Steps to reproduce
+ Download https://github.com/kimai/kimai/archive/1.2.2.tar.gz
+ Follow the instructions in https://www.kimai.org/documentation/updates/ and INSTALL.md
+ Open kimai in web browser, choose English and agree to license terms.

#### Reproducable on demo.kimai.org? [yes|no]
No.

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.2.2.1394 (as displayed in the web installer)

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
Not present.

So far everything worked without problems with version 1.1.x but now I can't upgrade due to this. Can you help?

**Comment by simonschaufi** [comment]
if you install the archive from github directly, you NEED to run `composer install --no-dev` also.

**Comment by anchev** [comment]
At which step of the installation procedure? Could you please include it in the proper place in docs so there is no confusion?

**Comment by simonschaufi** [comment]
Please have a look here: https://www.kimai.org/documentation/installation/#installation-1

**Comment by anchev** [comment]
Thanks.
I mean - the documentation about how to update. It doesn't have that info and for one who would guess to look at installation (as if starting for a first time) one would assume that for update it is not a require step.

**Comment by anchev** [comment]
BTW that composer command is listed only for `git clone`. It is not listed in case of downloading the tar.gz file (for which is the current issue).

**Comment by simonschaufi** [comment]
Kimai will itself detect if an update is neccessary of the database. The update process is also documented: https://www.kimai.org/documentation/updates/ !
Well the tar.gz file is basically just a zip file of the current branch. You will end up with exactly the same files as if you would clone the repo.

**Comment by anchev** [comment]
The issue is about detecting PHP version, not about database. The documentation about the update process does not mention the info which you shared in the previous comment (about `composer`). That's why I suggested that it is included in the doc about update.

**Comment by simonschaufi** [comment]
Please improve the documentation yourself so that it is better understandable: https://github.com/kimai/www.kimai.org/tree/master/documentation

**Comment by anchev** [comment]
This is what happened:
```
# composer install --no-dev
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Installing dependencies from lock file
  - Installing phpoffice/phpexcel (1.8.1)
    Downloading: 100%

  - Installing tecnickcom/tcpdf (6.2.13)
    Downloading: 100%

  - Installing zendframework/zendframework1 (1.12.20)
    Downloading: 100%

Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating autoload files
```
If phpexcel is abandoned why is composer installing it?

I continued and upgraded the DB successfully.

Result: now I can't login to kimai. It tells me my password is wrong but I am using the same password as before the update. Can you help?

**Comment by simonschaufi** [comment]
Oh this must have just happened recently as I was not aware of it. I have no idea what you did but resetting the pw is easy: Create yourself a php file, put in the salt and generate the new pw hash: https://github.com/kimai/kimai/blob/master/includes/func.php#L594-L595
then put the hash in the pw column for the user.

**Comment by anchev** [comment]
I tried the "forgot password" way. I clicked the link and simply entered my old password twice. I still can't login with it.

Why should I need to reset my passwords at all?

Also: would it be correct (or necessary) to copy includes/autoconf.php from the previous kimai version?

**Comment by simonschaufi** [comment]
Read the manual!!!!!!!
It is written that you HAVE to copy over this file!

**Comment by anchev** [comment]
> Read the manual!!!!!!!
Kindly don't shout at me.

> It is written that you HAVE to copy over this file!
No, it is not. The manual says:
> To install a new version just replace the entire directory with the new package and KEEP the file autoconf.php which can be found inside the /includes folder.
which does not immediately and explicitly mean "Copy the old autoconf.php to the new kimai directory.

You have to fix your docs, not shout at people when they are confused by them.

**Comment by anchev** [comment]
There are some tables in the db named kimai_bak_* - should those be deleted? No info in the update manual about it.

**Comment by kevinpapst** [comment]
Please calm down. 
People always raise the same questions, which is annoying... but it doesn't help to get frustrated.
So lets focus on helping out here. 

We will adapt the docu and a warning on the installation page, that it SHOULD NOT be executed while upgrading (with a link to the updates section).
The _bak_* tables are there for the people who execute the wrong action, so you can delete them if you have another backup on hand.

@anchev we are not english natives, so if you can provide a better explanation which is more clear, that would be very useful!

**Comment by anchev** [comment]
@kevinpapst Thank you for explaining. Although I am not a native English speaker myself I would be glad to help with anything I can. But of course first I had to clarify for myself the right procedure. I also don't know how exactly to update the doc (as recommended). Should I paste text here or what? (I have never used git to be honest, just svn)

Perhaps fixing phpoffice/phpexcel should come before updating the docs?

**Comment by kevinpapst** [comment]
You can just paste the text here and we will add it to the docu, if you don't want the hassle to learn git and/or github first ;-)

The warning about the library just means that it is not maintained any longer at that address.
We cannot simply change it to the new package, as then we would have to rewrite all the code using the old library. So this might be a task for the future, but it is in no way a warning that Kimai is broken.

**Comment by anchev** [comment]
Ok, here is a suggestion for the updates section of the docs based on the steps I performed successfully:
--
Step 1:
Add the following sentence:
> For 

Step 2:
Replace the first sentence with:

To install a new version, first rename/move the old one (e.g. `mv kimai kimail-old`) and then unpack the new version in a directory with the same name as the old one (e.g. `kimai`). Then copy your old `autoconf.php` into the new version, e.g:

`cp -a kimai-old/includes/autoconf.php kimai/includes/autoconf.php`

Step 3:

If you install the archive downloaded from GitHub you NEED to run `composer install --no-dev` too.

Step 4 = current Step 3

Step 5 = current Step 4

Add a sentence: If everything was completed successfully (no errors or warnings) you can also delete the database tables named `bak*` - they are there for the people who execute the wrong action.
--
Actually as I am thinking: you can make the auto updater to clean up the bak* tables automatically if the update is successful. Then the last sentence may not be necessary.

**Comment by anchev** [comment]
Sorry for the multiple edits. I messed up something with formatting initially.

**Comment by simonschaufi** [comment]
The normal update process is not to move the old files away but just to overwrite them. In that case you have to copy over the autoconf.php file as well as there is the db configuration and most importantly the hash included.

**Comment by anchev** [comment]
> The normal update process is not to move the old files away but just to overwrite them.

How would that resolve removing a file which is needed in the older version but is not present (and hence no longer needed) in the new one?

**Comment by kevinpapst** [comment]
@simonschaufi do you have a proposal that makes it clearer what has to be done?

**Comment by simonschaufi** [comment]
>  I don't get what you mean.

**Comment by anchev** [comment]
> I don't get what you mean.

Example (pseudo file structure):

version 1.3 has the following files:
```
kimai/aaa.php
kimai/bbb.php
kimai/ccc.php
```
Then later version 1.4 is released which uses:
```
kimai/aaa.php
kimai/ccc.php
kimai/ddd.php
```
i.e. `kimai/bbb.php` is removed and no longer necessary. If during an update the user merely copies the files of 1.4 on top of those of 1.3 `bbb.php` will remain (which will use disk space although it will never be used, not clean solution). But if you use the method I suggest, only the files which are used by the new version will be used.

**Comment by simonschaufi** [comment]
sure, you can of course also delete all files except the autoconf and then just unzip all files into the same folder. same result. anyway, in the end you have to use the "config" file again no matter what system you use. This also applies to all other systems like wordpress, joomla or whatever....

**Comment by anchev** [comment]
> Could you please help us with the documentation? That would be awesome!

I already pasted what I think should be included. Is there anything else?
