### ISSUE TITLE
Kimai version 1.2.2 , not working on PHP 5.4 

### ISSUE THREAD

**Issue by prbt2016** [kimai/kimai#1124]
Hi,
I tried manual installation of Kimai 1.2.2 (latest stable version) on PHP 5.4 and MYSQL 5.5(on Centos) .However when i start the installation and after 'System Requirements' check following error is thrown 
**Fatal error: Can't use method return value in write context in /{{path}}/{{to}}/{{kimaidir}}/includes/func.php on line 344**.
  However when i tested it on PHP 5.5 , it works fine .
What could be the possible issue ?.Can you please check and fix this.

**Comment by simonschaufi** [comment]
Sorry, we can't reproduce this as we don't use Centos but ubuntu. Is [this line](https://github.com/kimai/kimai/blob/master/includes/func.php#L344) the one that causes the error? 

Btw: why don't you use PHP 5.5 then? PHP 5.4 is totally outdated and shouldn't be used at all any more.

**Comment by prbt2016** [comment]
Hello  simonschaufi ,
Thanks for your reply.Yea the line mentioned is causing an issue. Was testing it on PHP 5.4 as the minimum requirement mentioned here [](https://www.kimai.org/download/ ) is PHP 5.4 .Have you upgraded the PHP  requirement ?.

**Comment by simonschaufi** [comment]
Well, to be honest, we don't test all PHP versions. I'm currently developing on PHP 7.1 since PHP 5.4 is way too old and not supported any more.

**Comment by kevinpapst** [comment]
From the PHP docs: https://secure.php.net/manual/en/function.empty.php
So we need either raise the PHP requirement or rewrite all these empty() conditions.

These are the officially supported ones: https://secure.php.net/supported-versions.php

Having a lower requirements is good for attracting a larger user base, but we are holding us back from using newer language features. I wouldn't go with PHP 7 (even though it is available more than 2 years now) but at least 5.6. 

So my vote goes for raising the requirement to PHP 5.6, as 5.4 & 5.5 has reached its end-of-life quite a while ago: https://secure.php.net/eol.php

**Comment by prbt2016** [comment]
Hi,

Thank you for the update. I completely understand that PHP 5.4 is obsolete and is not supported anymore. 

However some users still use PHP 5.4 because some other utility on their website might not work on PHP 5.5+ 

So rather than causing a FATAL error I would recommend to simply update the PHP version requirement for Kimai to PHP 5.5+ on the downloads page :
https://www.kimai.org/download/

This will make sure users know that they need to use PHP 5.5+ in order to use this script.
