### ISSUE TITLE
automatic calculation of values for start date and start time

### ISSUE THREAD

**Issue by ateliernz** [kimai/kimai#1128]
#### Expected behaviour
automatic calculation of values for start date and start time when end date and, end time and duration are entered

#### Actual behaviour
if end date and, end time and duration are entered, values of start date and start time are erased and input fields are blank

#### Steps to reproduce
1. Manually add an entry in the timesheet pressing the (+) button
2. Click on Input field End date
3. Select day before today
4. Values of start day and duration are erased
5. Enter a duration value and push tab (values for start date and time do not appear automaticaly)
6. Click on OK
7. pop-up error message: Time or date is not valid.

#### Reproducable on demo.kimai.org?
no

#### Kimai version
1.2.2.1394

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[22.02.2018 14:58:21] KSPI axAction (thomas): add_edit_timeSheetEntry
[22.02.2018 14:58:21] KSPI axAction (thomas): reload_activities_options
[22.02.2018 14:58:21] KSPI axAction (thomas): bestFittingRates

#### Reproducable on older installation on same host?
no
new values are shown and I get this extra log file line:
[22.02.2018 15:16:18] Global role 1 gave true for ki_timesheets-showRates.

**Comment by simonschaufi** [comment]
Please investiage further what exactly is the problem as you wrote yourself that you cannot reproduce it on the demo

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
