### ISSUE TITLE
add a new field entry to user_details

### ISSUE THREAD

**Issue by masterofdesaster300** [kimai/kimai#1129]
How can i add a new entry to the user_details "field" in the floater. 
I want to save an entry which i typed in the user edit floater in the admin panel.
I dont know where it is in the code.
Thank you for helping

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
