### ISSUE TITLE
Howto set Billable: 100% by default for all tasks

### ISSUE THREAD

**Issue by nafetsreuab** [kimai/kimai#1130]
Please create a default option per user to set Billable: to 100% for all tasks.

Currently on every task i have to manually set billable to 100%.

Reproducable on demo.kimai.org? YES

Kimai version Kimai dev 1.2.2.1394

**Comment by AlxBe** [comment]
Take a look here: https://github.com/AlxBe2/kimai/tree/default-billable

**Comment by nafetsreuab** [comment]
thank you. I'm not familiar with forks/github. Will this change be available in the official kimai release?

**Comment by nafetsreuab** [comment]
After some digging, i do not need any code change as i can just set 'includes/autoconf.php'

$billable = array (
  0 => 100,
  1 => 100,
  2 => 100,
);

which is what i want. Thank you.
