### ISSUE TITLE
Hide/suppress prices on PDF-exports

### ISSUE THREAD

**Issue by nafetsreuab** [kimai/kimai#1131]
There should be options to export to PDF without showing prices

Best would be to have options like:  
[ ] show total sum on exported pd file
[ ] show hourly rate on exported pdf file
[ ] show sum per task on exported pdf file

Currently the PDF export contains the total sum (over all tasks for a specific period) + the hourly rates + the sum per task (hourly rate x hours)

Reproducable on demo.kimai.org? YES

Kimai version dev 1.2.2.1394

**Comment by nafetsreuab** [comment]
problem not present. I was just too stupid.

**Comment by kevinpapst** [comment]
So you found the clickable table headers? And sorry for not answering earlier :)

**Comment by nafetsreuab** [comment]
Yes i did :p
