### ISSUE TITLE
Export extension - bug?

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#1136]
`
FastCGI sent in stderr: "PHP message: PHP Notice:  A non well formed numeric value encountered in .../extensions/ki_export/base_export_pdf.php on line 229
`

Happening on the master demo. I don't know how, it just pops up quite often in the error log

**Comment by philipp-doblhofer** [comment]
Are you using PHP 7.1?

Because there is this new feature: https://wiki.php.net/rfc/invalid_strings_in_arithmetic which warns you if you add a string which is not a valid number to a number.
So casting to a numeric value might fix the problem.

**Comment by kevinpapst** [comment]
Yes, the server which is running our demo was upgraded to 7.1 recently.

**Comment by kevinpapst** [comment]
Archiving old issues. [Please switch to Kimai 2](https://github.com/kevinpapst/kimai2)...
