### ISSUE TITLE
admin password

### ISSUE THREAD

**Issue by jameseck** [kimai/kimai#1137]
Hi,

I've lost the admin password for my Kimai install.  Is there a way to reset it?  I don't have an SMTP server configured so I can't use the forgotten password link.  Can someone please provide details on how to update it directly in the database?

Thanks

J

**Comment by timlegge** [comment]
you need to do two steps:

 generate the default password:
1. Get the password salt from the autoconf file (grep salt ../includes/autoconf.php)
2. open php in interactive (php  -a)
3. create a variable fo the salt ($password_salt = 'bsfskjfhskdwdwf';)
4. generate the password (print md5($password_salt . 'changeme' . $password_salt);)

update the database with the password
backup the database
connect to the database
run an update query that updates only the admin user with the new password

select password from kimai_users where name = 'admin';

should get you started

**Comment by timlegge** [comment]
don't ues the salt I used as it won't work it has to be the one from your installation

**Comment by kevinpapst** [comment]
This question comes up so often, we should have a documentation for it...
Next time you can simply refer to one of the old threads ;-)

**Comment by jameseck** [comment]
Thank you!

**Comment by moisei** [comment]
I've used another workaround, feels little bit simpler and safer for me. Given you know the password of any other kimai user and you have access to the database, you can change the role of this user to be SUPER_ADMIN in the db.  set ```kimai2_users.roles``` to ```a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";}```  and then just login as this user and change password of the superadmin user in the kimai2 user's page. After that you can reset the role of the current user to the original one.

**Comment by kevinpapst** [comment]
@moisei this is Kimai 1 and btw. you can use the commands available in `bin/console`, which are much safer than fiddling in the database:
<img width="547" alt="Bildschirmfoto 2020-03-21 um 17 44 12" src="https://user-images.githubusercontent.com/533162/77231490-94df8180-6b9b-11ea-9ed2-41e994ef7b95.png">
