### ISSUE TITLE
[privacy concern] Does Kimai connect to external hosts to check version?

### ISSUE THREAD

**Issue by anchev** [kimai/kimai#1141]
I notice that before login to Kimai there is this message:

"You are running the latest version :)"

Kimai is installed on a localhost but this message tells me that in some way the software connects to another external host to check the version (otherwise it could not possibly know if it is latest or not).

I do NOT want Kimai to connect to other hosts as I consider this a privacy issue. A privacy respecting software should never connect to any other host without the explicit permission of the user. So if that is the case: can you please explain how to prevent any external connections? (I am ok with manually checking the version for update when necessary)

**Comment by kevinpapst** [comment]
That performs the check:
https://github.com/kimai/kimai/blob/master/libraries/Kimai/Update/Check.php

Its called here:
https://github.com/kimai/kimai/blob/master/js/main.js#L209

Just delete that line and you are good to go.

Maybe its called somewhere else, just search the codebase now that you have the references.

**Comment by anchev** [comment]
Thanks. Can you please add it as an option/config setting so that one doesn't need to hack it this way?

**Comment by kevinpapst** [comment]
There is already a config for that in adminstration / extended. 
If checked, it suppresses the automatic check before login.
