### ISSUE TITLE
Calendar View instead of a list

### ISSUE THREAD

**Issue by gphill** [kimai/kimai#1143]
Hello!

Is there any posibility to change or add a view like a calendar instead the list?

i mean like a Outlook Calendar (month view).

Best!

**Comment by kevinpapst** [comment]
You can add such a feature via an extension, but afaik there is currently nothing existing that does it for you.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
