### ISSUE TITLE
Missing documentation of API/Remote

### ISSUE THREAD

**Issue by kakohari** [kimai/kimai#1145]
When trying to make use of some API (JSON, SOAP) or the Database.php one has to find out stuff via the code. It might be spectacular to have some starting point in the documentation :dancing_men: :dancing_women:  (<-- those are called dancing men and dancing women and are dancing here to make you happy!)

**Comment by simonschaufi** [comment]
Have you considered making a pull request and help us? Here is the repo for the documentation: https://github.com/kimai/www.kimai.org/tree/master/documentation
Looking at some issues you have a starting point already. https://github.com/kimai/kimai/issues/1109

**Comment by xakiru** [comment]
@kakohari you can check the new documentation if you still need it

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
