### ISSUE TITLE
Export Data to Excel XLSX 0 Byte

### ISSUE THREAD

**Issue by MarkusWz** [kimai/kimai#1151]
When exporting data as Excel File, we sometimes faced the problem that exported file is 0 Byte. It still woked with csv but not with xlsx.

After some investigations we found out that one person put a comment into one of the entries which started with: ==> 

This caused exporting the xlsx having 0 Bytes. After avoiding these characters the export again worked perfect again.

Used Kimai Version v1.2.2.1394

**Comment by simonschaufi** [comment]
Thanks for letting us know. Actually the equal sign starts a command in Excel. Probably that's the reason because of an internal error.
