### ISSUE TITLE
log time user edit his timesheet

### ISSUE THREAD

**Issue by Andrej553** [kimai/kimai#1152]
Hi,

i want my users to edit their timesheet if there is a mismatch (e.g. server was down and he could not start ...) but log when (and how often) they use the edit entry function.

Example:
Start recording at 10:00 stop it at 12:00.
Edit entry. Set starting time to 08:00. 
Timesheet says 08:00-12:00 last edited 15:25.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
