### ISSUE TITLE
How to change number of user visualizations in timesheet screen

### ISSUE THREAD

**Issue by andiguego** [kimai/kimai#1153]
Hi
We want to know how to change the number of displays on the time sheet screen, since when the user logs in for the first time he can see more records, but when he makes a first operation, the records that are displayed are limited to a few.

We observe in some of the answers that there are people who have changed it, but we have not managed to do so.

**Comment by simonschaufi** [comment]
The amount of time records depend on 2 things. The selected time frame at the top and the limit in the profile settings. hope that helps.
