### ISSUE TITLE
Fresh install won't work - 301 errors

### ISSUE THREAD

**Issue by kegster** [kimai/kimai#1154]
#### Expected behaviour
Normal kimai functionality

#### Actual behaviour
After I login for the first time (using admin/changme), it sucessfully logs me in, but the entire APP looks "somewhat okay" except when I try to go to settings I get a "floater" empty overlay. Also, the console log shows 301 errors for ALL assets (images, etc).

After this happens, the weird part is that if I refresh or attempt to go back to any kimai url, I get an actual 301 error on the site.

I am using a cPanel interface. I've tried PHP 5.6, 7.0, 7.1, 7.2 AND I've attempted with fpm on and off. I've done fresh installs with brand new accounts created as well. I have full root, whm, cpanel access.

This sounds like I may have a noob issue, but I have been working with web environments for a long time (with and without cpanel) and I've never had an issue like this.

#### Steps to reproduce
Install on cpanel machine. I use a VDS from ramnode.
#### Reproducable on demo.kimai.org? [yes|no]
no

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.2.2

**Comment by simonschaufi** [comment]
301 is a redirect status code. no glue where this could come from.

**Comment by kegster** [comment]
I meant 403 not 301. I had created a bunch of 301's  prior to writing this ticket. my apologies.

**Comment by simonschaufi** [comment]
Still, I can't really help in your case. This looks very strange. Did you download the release zip file?

**Comment by kevinpapst** [comment]
Sent in your nginx and phpfpm config and we can have a look.

**Comment by simonschaufi** [comment]
no feedback for more than 1 month.
