### ISSUE TITLE
Possibility to set a limit of hours to specific project/activities

### ISSUE THREAD

**Issue by vascojdb** [kimai/kimai#1155]
#### Expected behaviour
Be able to assign a maximum number of hours to a costumer or project or activity, say 160h for example, users will be able to assign time to what they are working on, but the user should see how many hours are left until it reaches the maximum, after the maximum is reached, the user should not be able to burn more hours to the activity without contacting the manager/admin, who will update or not the total hours for the activity/project/etc...

#### Actual behaviour
The user can can add as much time as he/she wants to any activity, no limits are set.

#### Steps to reproduce
Just keep n adding hours to some project, no limits are set.

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
any

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
no relevant logs

**Comment by simonschaufi** [comment]
we are aware of this missing feature. If you are interested, we could implement this feature as a paid feature for you as this requires a lot of work.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
