### ISSUE TITLE
Stored XSS

### ISSUE THREAD

**Issue by osmooth** [kimai/kimai#1156]
Devs, I'm a security penetration tester and wanted to highlight an issue. It's a fantastic product and I fully support this tool.

#### Expected behaviour
Sanitise encode user entered data. 

#### Steps to reproduce
add this payload into the new project name:
`
"><script>alert(document.cookie)</script>
`
Now add a new timesheet entry for that project.

#### Reproducable on demo.kimai.org? [yes|no]
yes

**Comment by simonschaufi** [comment]
I added `"><script>alert(document.cookie)</script>` as a new project name but there is no alert on current master. can't reproduce.
