### ISSUE TITLE
protected's in remote/api.php instead of privates

### ISSUE THREAD

**Issue by labor4** [kimai/kimai#1159]
would it make sense to you too if you'd change the private methods in api.php into protected's?
I'm working on a /mobile "enter stuff after it happened" expansion.
That way I could cleanly separate my code from the parent git repo until it's finished.

thanks
manu
[0001-api.php-prep.patch.txt](https://github.com/kimai/kimai/files/1885927/0001-api.php-prep.patch.txt)

**Comment by kevinpapst** [comment]
Sure, can you sent a pull request?

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
