### ISSUE TITLE
Dashboard shows numbers of project without having access to it

### ISSUE THREAD

**Issue by webkp** [kimai/kimai#1161]
**Describe the bug**
A team lead can see working hours and revenue of a team member in his team but with a project the team leader has no access to.

**To Reproduce**
1. Create two projects (Proj1 + Proj2)
2. Create two teams (Team1 + Team2)
3. Create two users (A + B)
4. Grant team Team1 access to project Proj1
5. Grant team Team2 access to project Proj1 and Proj2
6. Assign user A as team lead of team Team1
7. Assign user B as team lead of team Team2
8. Add user B to team Team1

Recap: User B is a part of team Team1 and team lead of Team2

If user B logs time for project Proj2 which only he/Team2 has access, user A can see the working hours and revenue on his dashboard (and only there). Timesheet and invoices are all ok since restricted to user A's project Proj1. This inconsistency is only visible on the dashboard, section "All users" (all box types like active user, revenue, working hours as well as all box times like today, this week etc.)

Sure, user B is part of Team1, too but since user A has no access to project Proj2 I would expect he is not able to see those working hours and revenue in his dashboard.

**Additional context**
 - Kimai version 1.4.1
 - PHP version 7.2

**Comment by kevinpapst** [comment]
Thanks for the info. Which boxes exactly are affected?
Maybe the statistic calls for the small "single value" widgets currently don't respect the team permissions.

**Comment by webkp** [comment]
On the dashboard, all boxes under section "All users":

![kimai_dashb](https://user-images.githubusercontent.com/11754639/66483646-c9f08f80-eaa5-11e9-95d7-fc4be9a96596.png)

**Comment by kevinpapst** [comment]
Hm, true... well maybe teamleads shouldn't see these boxes?

These lines define the visibility:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L192
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L197

At least the middle row makes no sense to be filtered by the team.

**Comment by webkp** [comment]
I would say these are interesting numbers for a teamlead, even probably the active users row (to see how many team members actually were working on projects of the team). But I think those numbers should be filtered so that he only sees the numbers for his teams projects.

**Comment by webkp** [comment]
@kevinpapst  is this something that will only be resolved in the long term?

I ask, because currently no hourly rate can be set, because otherwise, especially when using with freelancers, they would see these revenues from other teams, which they should not see at all.

**Comment by kevinpapst** [comment]
You can simply change the dashboard settings. Read the documentation how to do it:
https://www.kimai.org/documentation/dashboard.html

Here is an example for your local.yaml:
https://www.kimai.org/documentation/configurations.html#overwriting-local-configs-localyaml

```
kimai:
    dashboard:
        duration:
            permission: ROLE_ADMIN
        active_users:
            permission: ROLE_ADMIN
        rates:
            permission: ROLE_ADMIN
```

Then rebuild your cache:
https://www.kimai.org/documentation/configurations.html#reload-changed-configurations

And "gone" they are ... only visible to Admins.

**Comment by webkp** [comment]
Perfect, thank you very much! I greatly appreciate it.

I've already made some adjustments but didn't realize that I could hide them completely.

**Comment by kevinpapst** [comment]
The bug will be fixed sooner or later, but until then simply hide them from teamleads, so you can finally start working with rates!

**Comment by kevinpapst** [comment]
fixed for the next release
