### ISSUE TITLE
Fresh install of V2 fails with composer: Script cache:clear returned with error code 255

### ISSUE THREAD

**Issue by krabina** [kimai/kimai#1166]
I tried a new installation on a hosted webserver with ssh. I followed these [instructions](https://www.kimai.org/documentation/installation.html)

```
[~/zeit]# composer install --no-dev --optimize-autoloader
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "WebServerBundle" from namespace "Symfony\Bundle\WebServerBundle".
!!  Did you forget a "use" statement for another namespace? in .../zeit/src/Kernel.php:85
!!  Stack trace:
!!  #0 .../zeit/vendor/symfony/http-kernel/Kernel.php(424): App\Kernel->registerBundles()
!!  #1 .../zeit/vendor/symfony/http-kernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 .../zeit/vendor/symfony/framework-bundle/Console/Application.php(159): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 .../zeit/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 .../zeit/vendor/symfony/console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #5 .../zeit/bin/console(39): Symfony\Compo in /home/kdz/zeit/src/Kernel.php on line 85
!!
Script @auto-scripts was called via post-install-cmd
 Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
Script @auto-scripts was called via post-install-cmd
```

**Comment by kevinpapst** [comment]
If you want to use `APP_ENV=dev`, you have to run `composer install`.

If you want to use it in production mode (what your composer install command suggests from `--no-dev`), then you have to change your `.env` file to `APP_ENV=prod`.

**Comment by krabina** [comment]
the problem is, there is no .env file

**Comment by kevinpapst** [comment]
Hm, the `cp .env.dist .env`, change it to your needs and run `composer install --no-dev --optimize-autoloader` again. I'll have a look at the docs.

**Comment by krabina** [comment]
there is also no .env.dist in the directory. seems that install did not copy everything. 
This is what the directory looks like:
![grafik](https://user-images.githubusercontent.com/4318745/66740654-fcb6d100-ee73-11e9-9bed-85e6bfe95e0e.png)
The .env file I created manually...

**Comment by kevinpapst** [comment]
How did you get the sources? Did you use git clone?

**Comment by kevinpapst** [comment]
And if so, what was the exact command you used and what does `git status` report? 
The file must be there, I never saw the git clone cloned a repo with missing files...

**Comment by krabina** [comment]
sorry, my mistake. 
git pulled everything in a directory "kimai2", I copies everything to a different directory which did not work.
I left it to kimai2, did ever required step and renamed it at the end. 

Everything seems to be fine now. Thank you for your quick support!

**Comment by kevinpapst** [comment]
Thanks for your feedback! Happy time tracking
