### ISSUE TITLE
Mac App for Timetrack: Eon Timer

### ISSUE THREAD

**Issue by davidrei** [kimai/kimai#1168]
You may add 'Eon Timer' to the list of applications supporting to track time against Timetrack.

After setting up the Kimai account in Eon Timer you may select the project/task from the drop down list in Eon Timer and log work. 

Eon Timer website at: https://software.charliemonroe.net/eon.php
Download from Apple App Store at: https://itunes.apple.com/ch/app/eon-timer/id413744108?l=en&mt=12

**Comment by kevinpapst** [comment]
@davidrei Neither your website nor App Store show Kimai as compatible.
Also: Timetrack is not Kimai.
Can you share a license so we can test the app?

We don't mind advertising your app if its compatible with Kimai, please sent in a PR for that file: https://github.com/kimai/www.kimai.org/blob/master/apps.md

**Comment by kevinpapst** [comment]
I will reopen this issue if you reply with more information
