### ISSUE TITLE
Documentatin for HTML invoice templates

### ISSUE THREAD

**Issue by andjona** [kimai/kimai#1169]
I´m looking for a documentation for html invoice variables.
Particularly I´m looking for a way to ad the project name to the invoice - equivalent to var.projects in open office templates.

**Comment by kevinpapst** [comment]
Project name is part of each row (invoice entry), see:
https://github.com/kimai/kimai/blob/master/extensions/ki_invoice/invoices/freelancer/index.html#L96

**Comment by andjona** [comment]
Hi,
this works great for freelancer timetables, but is there a variable to get it as a single entry for putting it in the invoice header?

**Comment by kevinpapst** [comment]
What about `$entries[0]['projectName']`?

**Comment by andjona** [comment]
That does the trick - thanks
