### ISSUE TITLE
json.php addProject?

### ISSUE THREAD

**Issue by DragonBale** [kimai/kimai#1170]
Is there no way to add or set a project besides only getProjects in the json.php request system?

**Comment by simonschaufi** [comment]
Currently not but feel free to implement it! The file is this one: https://github.com/kimai/kimai/blob/develop/libraries/Kimai/Remote/Api.php

**Comment by DragonBale** [comment]
Oh ok, thanks for the fast answer!
Sadly I'm not that good in zend develop and don't have the time at the moment to create one by myself.

But I figured it out how to use the processor.php file to create a project.
