### ISSUE TITLE
Wrong language in the invoice

### ISSUE THREAD

**Issue by gerroon** [kimai/kimai#1173]
Hi

I installed Kimai on Debian. Everything works well except that the invoices are in German and the money stuff is in EU. I chose english and US time zone when installing it. 

it seems like the standards are wrong in all invoice templates.

Kimai v1.2.2.1394 - © 2006-18 by the Kimai-Team: 
Php 5.6
mysql  Ver 14.14 Distrib 5.6.19, for debian-linux-gnu (i686)

thanks

**Comment by simonschaufi** [comment]
Please modify the templates to your own needs. These are just examples. Create a copy and make adjustments to avoid being overwritten after an update.

**Comment by gerroon** [comment]
Ok thanks for the follow up. I assumed , it was auton generated.
