### ISSUE TITLE
Timesheet multiple entry editing

### ISSUE THREAD

**Issue by andjona** [kimai/kimai#1177]
Hi,
I´m looking for a way to set multiple timesheet entries (after an invoice was written) to "cleared" (abgerechnet).
Right now I have to edit every single entry, which is a lot of a work.
Greetings

**Comment by simonschaufi** [comment]
the current master has this feature already implemented. if you can't wait for the next release, update your kimai to the current master.

**Comment by andjona** [comment]
great, thanks!
