### ISSUE TITLE
Working-Time is realy wrong

### ISSUE THREAD

**Issue by tholler3012** [kimai/kimai#1185]
#### Expected behaviour
Normaly I can see the working time in the right corner, now I see 424141:39:49 - and the seconds are counting up.
#### Actual behaviour
In the right corner I see 424141:39:49 instead of 0:39:49 - the time is counting up.
#### Steps to reproduce
This happened since I updated mimai to 1.3.0 - and with to update to 1.3.1 it is the same.
#### Reproducable on demo.kimai.org? [yes|no]
NO
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.3.1.1394
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[21.05.2018 15:54:31] login: user as user
[21.05.2018 15:54:32] KSPI axAction (user): reload_activities
[21.05.2018 15:54:32] KSPI axAction (user): saveBuzzerPreselection
[21.05.2018 15:54:32] user_edit failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE `userID` = 132374563' at line 1 (#1064)
[21.05.2018 15:54:41] KSPI axAction (user): setTimeframe
[21.05.2018 15:54:41] KSPI axAction (user): startRecord
[21.05.2018 15:54:41] startRecorder: Column 'projectID' cannot be null (#1048)
[21.05.2018 15:54:41] KSPI axAction (user): reload_timeSheet
[21.05.2018 15:54:46] KSPI axAction (user): stopRecord
[21.05.2018 15:54:46] KSPI axAction (user): add_edit_timeSheetEntry
[21.05.2018 15:54:46] KSPI axAction (user): reload_timeSheet

**Comment by simonschaufi** [comment]
check your maria db version. You have an error in your sql.

**Comment by tholler3012** [comment]
At phpMyAdmin I can see, that it is

    Server: Localhost via UNIX socket
    Server-Typ: MariaDB
    Server-Version: 10.0.35-MariaDB - MariaDB Server
    Protokoll-Version: 10
    Benutzer: root@localhost
    Server-Zeichensatz: UTF-8 Unicode (utf8)

So, where is the problem?

Regards

TH

**Comment by simonschaufi** [comment]
Sorry, I can't help with your problem. I know from other people that kimai runs well on MySQL and MariaDB.

**Comment by kevinpapst** [comment]
There is also an error regarding `Column 'projectID' cannot be null`while starting a record.
What happens if you refresh the page?
Does it happen for every new record? Please switch project and activity in between.

**Comment by ivtavares** [comment]
I have got the same problem. I updated my kimai to the version 1.3.1 and it happened too

**Comment by tholler3012** [comment]
OK, I think I have found something: When I use Vivaldi as browser I get that issue, when I use FF or Chrome everything is fine.

**Comment by simonschaufi** [comment]
Then Vivaldi is broken ;)

**Comment by kevinpapst** [comment]
Could one of you share more information?
I've tried it with the latest Vivaldi version for Mac on the demo site and didn't have that problem.

If one of your is familiar with the console, it would be great if you could share some more insights.
Check the network request when starting a record. What is the sent data and what is returned. 

Probably also check the database of the running entry, what is in there?
Does it happen reproducible with Vivaldi? 
Which extensions do you use (probably some privacy/security plugin is intercepting the request)?

**Comment by simonschaufi** [comment]
If you are not ready to maintain your own system, then why not use a hosted time tracking system like plenty others? The Internet is full of them.
