### ISSUE TITLE
Login not possible - all passwords wrong - since updating to 1.3.1

### ISSUE THREAD

**Issue by Richigeht** [kimai/kimai#1186]
#### Expected behaviour
Being able to login within the need to reset passwords.
#### Actual behaviour
With the same passwords I am not able to login anymore but I require to reset them.
#### Steps to reproduce
I did upgrade to latest 1.3.1 coming from the 1.2.2.
#### Reproducable on demo.kimai.org? [yes|no]
no
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.3.1

**Comment by simonschaufi** [comment]
How did you upgrade? I guess you didn't copy over the password salt from the old installation. Please follow the official docs: https://www.kimai.org/documentation/updates/

**Comment by Richigeht** [comment]
Yes, you are correct, sorry for that! Thanks for quick answer.
