### ISSUE TITLE
The Tasks are not filtered for the selected customer or project

### ISSUE THREAD

**Issue by Tourvel** [kimai/kimai#1187]
Expected behaviour

When selecting (by the filter icon) a customer, only the projects and the tasks corresponding to this customer should be shown in the project and tasks columns respectively. Analogically, when selecting (by the filter icon) any project assigned to a customer, only the tasks assigned to the selected project should be shown in the tasks column.  

This is the behaviour of the "filter" feature that I find logical and that worked until I have installed the most up to date version (v1.3.1.1394).   

Actual behaviour

When selecting (by the filter icon) certain customer and/or certain project, no change at all occurs in the tasks column where all the tasks for all my customers continue to be shown. In other words, the filter icon in the customers column filters the projects (as it should) but has no effect on the tasks column. Moreover, the filter icon in the project column has no effect on the tasks column either. To filter the tasks, I have to use the select button - but its function should be different (i.e. the selection for recording).

Since certain tasks are identical for all my customers but are assigned individually to them (e.g. analyzing, drafting, attending meeting), unless I use the select button, I have dozens of the apparently "same" tasks listed in the tasks column.     

Reproducable on demo.kimai.org?
Yes

Kimai version 
v1.3.1.1394

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
