### ISSUE TITLE
Translation missing in fr.php

### ISSUE THREAD

**Issue by PascalLeBlanc** [kimai/kimai#1188]
#### Expected behaviour
add those line in the fr.php just after line 375
    'quicklink_today' => "Aujourd'hui",
    'quicklink_yesterday' => "Hier",
    'quicklink_lastWeek' => "Semaine dernière",
    'quicklink_lastMonth' => "Mois dernier",
    'quicklink_thisWeek' => "Cette semaine",
    'quicklink_thisMonth' => "Ce mois",

#### Actual behaviour
terms not translated

#### Steps to reproduce
set language to fr

#### Reproducable on demo.kimai.org? 
yes

#### Kimai version
 v1.3.1.1394 - © 2006-18 by the Kimai-Team:

**Comment by simonschaufi** [comment]
Hello,
could you please do it yourself?

Go to this link and edit the file:

https://github.com/kimai/kimai/blob/develop/language/fr.php

Then create a new pull request. Thank you!

**Comment by kevinpapst** [comment]
Can be closed due to #1189
