### ISSUE TITLE
Fr-fr Tranlation (French, Français)

### ISSUE THREAD

**Issue by Lagneaux** [kimai/kimai#1193]
Hi,

Quelques traductions sont manquantes. En voici quelques unes :

```
	"quicklink_today" => "Aujourd'hui",
	"quicklink_yesterday" => "Hier",
	"quicklink_lastWeek" => "Semaine -1",
	"quicklink_lastMonth" => "Mois -1",
	"quicklink_thisWeek" => "Cette semaine",
	"quicklink_thisMonth" => "Ce mois",
```
[fr.zip](https://github.com/kimai/kimai/files/2053106/fr.zip)

Regards
DOm

**Comment by simonschaufi** [comment]
We added them already: https://github.com/kimai/kimai/blob/master/language/fr.php#L376-L381. Are they correct?

**Comment by Lagneaux** [comment]
Hi,

I still improve French translations for the "Invoice" tab, attached file!
[fr.zip](https://github.com/kimai/kimai/files/2053512/fr.zip)

I also improve the file "Main.php" so that the translations of the invoice billing can match
At .../extensions/ki_invoice/templates/scripts/
[main.zip](https://github.com/kimai/kimai/files/2053576/main.zip)

regards
DOm

**Comment by Lagneaux** [comment]
Hi Simonschaufi,

> We added them already: https://github.com/kimai/kimai/blob/master/language/fr.php#L376-L381. Are they correct?

No, they are not correct! 

Cheers
DOm

**Comment by kevinpapst** [comment]
Hi @Lagneaux , 
thanks for your input and contribution.
Can you please add these changes into a new branch in your forked repository and sent them in as Pull request? 
There are fantastic tutorials out there if you are new to Git and GitHub.

**Comment by kevinpapst** [comment]
Thats the way how to contribute to an open source project, you can read more about it:
https://opensource.guide/how-to-contribute/#opening-a-pull-request
The first time is weird ;-) but its easier than it sounds!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
