### ISSUE TITLE
Kimai show 503 error in index.php.

### ISSUE THREAD

**Issue by anil815** [kimai/kimai#1195]
After login whole dashboard looks messy and nothing works fine. 
If I hit to go admin panel then it show me a black screen.  Please provide a solution

**Comment by kevinpapst** [comment]
How shall we help if you provide no information?
Kimai logs, Server logs, did you update, which version, which php version...

**Comment by kevinpapst** [comment]
Demo site works, must a system problem that we can't help with unless provided more information => closing
