### ISSUE TITLE
No hourly rate per task per project even though its in the docs

### ISSUE THREAD

**Issue by guysoft** [kimai/kimai#1196]
Hey, not sure if this is a feature, but it looks like there should be something like this because it is in the documentation at:
https://www.kimai.org/documentation/rates/
Says:
```
project 2 and task 5 have a rate of 50.00 € per hour
```

#### Expected behaviour
When editing an activity, under projects, there should be an option to include a custom hourly rate.
#### Actual behaviour
There is only a fixed rate, here is a screenshot
![screenshot_20180603_173330](https://user-images.githubusercontent.com/325670/40887648-7b71cc32-6754-11e8-95b7-f3a211668c2b.png)

#### Steps to reproduce
1. create a project
2. crate an activity
3. click on "edit entry" as shown below
![screenshot_20180603_173613](https://user-images.githubusercontent.com/325670/40887662-a4c5f7f2-6754-11e8-82ed-2423d5ee138e.png)

#### Reproducable on demo.kimai.org? 
yep

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.3.1.1394

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
None that I know of.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
