### ISSUE TITLE
adding user of a task to invoice 

### ISSUE THREAD

**Issue by andjona** [kimai/kimai#1197]
Is there a way of adding a user to the invoice html code e.g.
$row['_userID_'] 

Greetings.

**Comment by kevinpapst** [comment]
Which user?
For the row? 
The currently logged-in user?

**Comment by andjona** [comment]
Hi Kevin,
thanks for the fast reply and sorry for being so unprecise. 
Two people are working on a project and tracking their time. 
Now I want to print a timesheet via the invoice function. 
I‘m looking for the code to name the person who has been working on the topic. 
Greetings,
Andreas

**Comment by kevinpapst** [comment]
Hi Andreas,
could you please try with the debug template: https://github.com/kimai/invoice-templates
If you still can't find the value, let me know and I will have a deeper look into the code.

**Comment by andjona** [comment]
Hi Kevin,
thanks for the debug template. Code was:
$row['useralias']
Greetings
