### ISSUE TITLE
I try to develop a customized version after install kimai and get some confused.

### ISSUE THREAD

**Issue by Yw-melo** [kimai/kimai#1200]
#### Expected behaviour
After deploy it to the server, I get 500 error code with no message .Could someone tell me how to turn it to debug mode. Thanks a lot.

**Comment by Yw-melo** [comment]
I already turn the error_report on yet.

**Comment by simonschaufi** [comment]
Please don't waste our time. You should know how to read error logs...

**Comment by kevinpapst** [comment]
Sounds like a Webserver/PHP/permission problem. Please check your PHP and Webserver logs.
Its very likely no application problem.

@simonschaufi that sound is completely unnecessary
