### ISSUE TITLE
missing translation (hardcoded)

### ISSUE THREAD

**Issue by DJCrashdummy** [kimai/kimai#1203]
#### Expected behaviour
after switching to german [de] everything should be in german.

i would have contributed the translation myself, but i didn't find a corresponding string neither at [en.php](https://github.com/kimai/kimai/blob/master/language/en.php) nor at [de.php](https://github.com/kimai/kimai/blob/master/language/de.php) and this message is also untranslated in a bunch of other languages... so i'm afraid this message may be hardcoded? - or are the extension-translations stored somewhere else?

#### Actual behaviour
a picture is worth a 1000 words:
![export](https://user-images.githubusercontent.com/26110463/41204235-3e56768e-6ce2-11e8-86d6-77a9d46c91a0.png)

#### Steps to reproduce
go to export-tab, mark at least one entry as cleared and then toggle the button in the table-header to unclear at least one entry.

#### Reproducible on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.3.1.1394

**Comment by DJCrashdummy** [comment]
indeed it is hardcoded and also equipped with a comment:
https://github.com/kimai/kimai/blob/bff5531e6a1f41fc73e80117496b20c3806e705e/extensions/ki_export/js/xp_func.js#L342-L343

**Comment by DJCrashdummy** [comment]
btw: the message in this window does not distinguish between singular and plural (always uses the plural).

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
