### ISSUE TITLE
Database table timesheet. Date Format

### ISSUE THREAD

**Issue by MySepultura** [kimai/kimai#1208]
Where can I find the function which converts the Integer Value which is saved in the MySQL Database to Day-Month-Year and Hour and Minutes?

example: 1529388000 <-- This is the June 19th 2018 8:00 (8 am). Am I right it starts counting from 1970?

I want to code a C++ App which only accesses the Database to retrieve the informations.

Thanks

**Comment by kevinpapst** [comment]
Thats a simple timestamp, what exactly do you need?

**Comment by MySepultura** [comment]
I need it to transform this to a human readable string. Continental Europe Format 24h System (I think US Citizen call this system military time? ) Is there a general function to convert it?

for example "19.06.2018 08:00" or to two string classes d = "19.06.2018" t = "8:00".

**Comment by simonschaufi** [comment]
> I want to code a C++ App which only accesses the Database to retrieve the informations.

For internal use only or will you publish it at some point?

**Comment by MySepultura** [comment]
It was intended for internal use. But I can release it under GPL if someone is interested in. I will have to translate the GUI to english then. (Since I am in Germany)

**Comment by kevinpapst** [comment]
That would be nice! Sent us a link and we will feature it on the website.
