### ISSUE TITLE
Different modes for Agency and Freelancer

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#121]
|  | Agency with employees and freelancers | Freelancer |
|----------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------|
| Invoicing | Creates invoices for customers from all users working on a project with company branding.  Freelancers can create invoices to the agency with freelancer branding only for himself. Users are not allowed to create invoices. | Can create invoices to the customers with own branding only for himself (if multi user system). |
| Customer Admin | Agency is managing the customers. Freelancer is not allowed to C(R)UD. | Full access |
| Project Admin | Agency is managing the projects. Freelancer is not allowed to C(R)UD. | Full access |
| Task Admin | Agency is managing the tasks. Freelancer has limited rights to CRUD (can only CRUD in projects he is assigned to). | Full access |

**Comment by Kurgan-** [comment]
I am a freelancer, and I use Kimai v1. I have a single user (myself) who is an admin. I can do whatever I want, and that's simple as that. I don't see the need for a "freelance" mode if you can still simply have one "super admin" user that can both configure items and log his/her time.

**Comment by simonschaufi** [comment]
Freelancer mode is default. Agency mode will be restricted

**Comment by kevinpapst** [comment]
Permissions and roles are free configurable.

And the project/customer specific permissions are not yet existing. Closing this in favor of #366

**Comment by kevinpapst** [comment]
Everything from the feature request is now possible.
But the more complicated your setup is, the more time you need to put into configuration of roles, teams and permissions. So: not "two modes" but unlimited modes, only with necessary manual work.

**Comment by simonschaufi** [comment]
Thank you so much Kevin!
