### ISSUE TITLE
some issues at the hompages download-page

### ISSUE THREAD

**Issue by DJCrashdummy** [kimai/kimai#1212]
there are some things i noticed at the homepage, especially at https://www.kimai.org/download/:
first i have to say that the 2 buttons (**release** & **stable**) are pretty confusing! ...and this confusion gets even worse after checking out the **development** version, which links the same as the stable?!? :confused: 

so shouldn't there rather be just a **release** and **development** download?
if not, please explain somewhere at the homepage the differences:
- especially for the wording **release** & **stable**
- and why the **stable** and **development** download is the same...?

concerning the **_Installation_**-section:
according to [_Installation: further steps_](https://www.kimai.org/documentation/installation/) and [_Updates: Step 4_](https://www.kimai.org/documentation/updates/) shouldn't it be mentioned that not just the `installer` directory should be deleted after a successful installation but also the `updater` directory?

concerning the **_More Downloads_**-section:
mentioning and linking the github-project there beside the sourceforge-project may be reasonable, since it seems that github is the main-repo and sourceforge just a mirror... yes i know, the github-link is permanently on the top right, but at this size it can be easily overlooked.

---

apropos **_sourceforge_**-project:
when you download Kimai there via the one big _Download_ button, you get the 7 years old version 0.9.2.1306! please also link the latest stable download there, since it seems to be uploaded anyway and especially as long as sourceforge is mentioned at the official homepage.

**Comment by simonschaufi** [comment]
- Release: contains ALL files for a full release
- Stable: Does NOT contain all files (the whole composer stuff is missing) and is just a zip file from the master branch
- Develop: Same as stable but from the develop branch.

We develop on develop branch only (if you have noticed it already) and merge only when we have tested it and think it is ready for the next release. Therefor the develop branch _can be_ in a broken state.

## concerning the Installation-section
Doesn't need to be deleted

## apropos sourceforge-project
nop, we only publish new releases on github.

**Comment by kevinpapst** [comment]
Thanks for the notes, its always good to get some feedback.
As involved developers we are kind of blind on that eye.

I updated the page to make it a bit more clear: 
https://www.kimai.org/download/

And I incorporated some of your notes.

I guess the updater directory doesn't have to be deleted, as it checks the version and if there is anything todo. Yes you can remove it, but afair it shouldn't be a risk to have it.
