### ISSUE TITLE
Activities with fixed rate are set to 0 € in timesheet

### ISSUE THREAD

**Issue by JayAige** [kimai/kimai#1221]
System: 1 Admin, several Users (in the meaning of global roles)
This issue concerns activities with fixed rates. I made some activities with fixed rates (f.e. day rates) and assigned them to different projects. 

#### Expected behaviour
When an user (global role) enters an activity with fixed rate in the timesheet, the amount is set to 0.00 € despite there is a fixed rate set for the activity and for the project correlated activity.

#### Actual behaviour
The formerly set fixed rate should show up at the amount field instead of 0.00 €.

#### Steps to reproduce
Enter a fixed rate activity with an global role "user" account for any kind of project.

#### Reproducible on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai 1.3.1.1394

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
none

**Comment by JayAige** [comment]
I did some research about this problem and found some kind of a solution for this problem:

Go to 'Admin Panel' -> 'Global rules' -> Edit the 'User' global rule -> 'Timesheet'
Here a flag for 'edit rates' must be set.

After the user got the permission to edit rates, the formerly entered fixed value for the activity is correctly shown for future entries and stored for the amount value in the timesheet.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
