### ISSUE TITLE
"from last" button in time entry sheet

### ISSUE THREAD

**Issue by piflixe** [kimai/kimai#1223]
This is a feature request - please label accordingly if you think this makes sense and is feasible

#### Expected behaviour
have a "from last" button left of the start time in the time entry sheet, similar to the "now" button right of the end time field

![inkedfrom_last_button](https://user-images.githubusercontent.com/6273829/42310811-a305183e-803c-11e8-9495-00b09231f24a.jpg)

When creating an entry after you have done something, you could just hit "from last" and "now" and an entry is created after your last entry until now.

#### Actual behaviour
button not present in current demo

#### Steps to reproduce
click on "+" button to manually create a time entry

#### Reproducible on demo.kimai.org? [yes|no]
yes

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
