### ISSUE TITLE
Invoices export settings

### ISSUE THREAD

**Issue by Lagneaux** [kimai/kimai#1224]
#### Expected behaviour

**Comment by acmeraptor** [comment]
I've tried some changes and rejected them for automatic invoice numbering. Granted my business is new, but I can't rely on a counter keeping track of failed efforts to invoice things. It just messes with my record keeping.  Manual tracking is working better for now with a pre-formatted open document field to edit. Just a bit of advice, hope it helps.

⁣~acme​

**Comment by Lagneaux** [comment]
Hi,

I'm not a php programmer but I did some lines that allow me to have a counter!

I make my work available to everyone! The print file slightly m
[file_num.txt](https://github.com/kimai/kimai/files/2177473/file_num.txt)
odified and a «record of time» (list, time, time rate, VAT, totals with and without VAT).

How to recover for these documents invoices, **the variable of the name of the publisher** (connected or other)?
```
// billing counter,read
$fp = fopen("fnum.txt","r+");                          // 1.Open file r&w (chmod 777)
$fnum = fgets($fp);                                    // 2.Read last number in line 1
$fnumerotation = str_pad($fnum, 5, "0", STR_PAD_LEFT); // 3.Insert as many zero to have 5 digits, for example : 00009 or 00

$invoiceID = $customer['name'] . "." . date("Y", $out) . date("m", $out) . date("d", $out) . "." . $fnumerotation;
$today = time();
$dueDate = mktime(0, 0, 0, date("d"), date("m") + 1, date("Y"));

// billing counter, increment and save
$fnum++;                                              // 3.Increment the number (+1)
fseek($fp,0);                                         // 4.We go to the beginning of line 1 of the file
fputs($fp,$fnum);                                     // 5.Write in the file the new number
fclose($fp);                                          // 6.Close the file

```

Regards
Dom

output
[Relevé de Temps.docx](https://github.com/kimai/kimai/files/2177457/Releve.de.Temps.docx)
php file, print
[print.txt](https://github.com/kimai/kimai/files/2177458/print.txt)
Counter file
[file_num.txt](https://github.com/kimai/kimai/files/2177475/file_num.txt)

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
