### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by parthakarmick** [kimai/kimai#1225]
I am trying to install kimai into webserver without using SSH and composer. But received Uncaught Error: Class 'Kimai_Config' not found in /home/karmickdev/public_html/timesheet/installer/processor.php:166 while I hit Install button. Can you help on this?

**Comment by kevinpapst** [comment]
Not unless you tell us exactly what you did, which files you used for installation ...

**Comment by parthakarmick** [comment]
I have downloaded Kimai from github. I have use composer into my local machine. Then zip that package and upload into webserver. It took me to installation process, but give error when hit the Install button.

**Comment by kevinpapst** [comment]
Why not use the pre-packaged version: https://github.com/kimai/kimai/releases/download/1.3.1/kimai_1.3.1.zip

**Comment by parthakarmick** [comment]
Do I just upload that zip into server and start installation process?

**Comment by kevinpapst** [comment]
Did you follow the installation instructions? https://www.kimai.org/documentation/installation/
Download the linked zip, extract and upload (or the other way around if you have the option, as uploading a ZIP is much faster than the single files). The open Kimai and it will bring you to the installer. From there on everything will work. 
You must have missed somthing somewhere in between, I guess the composer autoloader is not correct in your installation, but thats just a guess.
