### ISSUE TITLE
I created a desktop widget and a command line client for kimai

### ISSUE THREAD

**Issue by infeeeee** [kimai/kimai#1226]
I needed a desktop widget for kimai, so I created one in Rainmeter: [Github page](https://github.com/infeeeee/kimai-widget). [Rainmeter](https://www.rainmeter.net/) is a desktop customization tool, only on windows.
It uses my command line client under the hood, written in node js: [Github page](https://github.com/infeeeee/kimai-cmd). It uses the json api. It runs on win, linux, mac, and it's packaged as an executable, so you don't have to install node js.
I just read about kimai v2, I hope the json api will be supported there as well. If it's not, I will update this for a new api.

**Comment by kevinpapst** [comment]
apps are already available on the website
