### ISSUE TITLE
Button "This week" and "last week" is not correct while using it on a Sunday

### ISSUE THREAD

**Issue by Richigeht** [kimai/kimai#1227]
#### Expected behaviour
If I use the button "this week" today, I do expect to see dates from 9. to 15. July. That works.
If I do press the button "last week", I do expect to see dates from 2. to 9. July. 
#### Actual behaviour
I only see dates for 9. to 15. July.
#### Steps to reproduce
Click on a Sunday (I guess that is the reason for it) on the last week/this week buttons and see the dates are off/wrong.
#### Reproducible on demo.kimai.org? [yes|no]
yes
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.3
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
nope

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
