### ISSUE TITLE
Duplicate Expense

### ISSUE THREAD

**Issue by piflixe** [kimai/kimai#1231]
#### Expected behaviour
When a certain expense reoccurs several times, user should be able to simply duplicate the corresponding expense entry by clicking on a button next to the edit button in the expense overview. This will copy the entry and insert the current date / time.

#### Actual behaviour
This functionality does not exist to my knowledge

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
