### ISSUE TITLE
from the 1.0.0 version the current task doesn't appear in timesheet except 'refresh'

### ISSUE THREAD

**Issue by tma000** [kimai/kimai#1236]

**Comment by kevinpapst** [comment]
Pleas respect our free time that we spent in developing Kimai.
Have a look at that issue and tell me: would you understand what is meant @tma000 ?
An answer is impossible and I will close this issue.

**Comment by tma000** [comment]
expected behaviour : like 0.9.2, the current task appear (actived by red button)  appeart in timesheet
actual behaviour : until 0.9.3 ok / from 1.0.0 ko
steps to reproduce : active a task by red button, you need to refresh systematically  the browser to see the current task in timesheet from v1.0.0
reproductible on demo.kimai.org : yes, same behaviour
log php in attached
