### ISSUE TITLE
Feature Request: Screen Capture & Web Cam Capture - Willing to Sponsor!

### ISSUE THREAD

**Issue by fiveways** [kimai/kimai#1240]
#### Expected behaviour
Ability to Capture Desktop and/or Web Cam from client app and send to server.  Must be able to see images from web interface. Delete after X months, setting per project.

#### Actual behaviour
store images on server or on amazon s3

very interested in this feature and we would seriously sponsor this request for priority completion. 

Please email notroger (at) gmail.com

**Comment by simonschaufi** [comment]
Hi,
Screen capture and webcam is not possible just with a web application.
Even if it would be possible, sponsoring such a feature would cost a couple of 1000€.
We only accept serious requests...
