### ISSUE TITLE
Invoice prints in German

### ISSUE THREAD

**Issue by wolftone1916** [kimai/kimai#1242]
#### Expected behaviour
Print Invoice in selected language

#### Actual behaviour
Prints in German

#### Steps to reproduce
Print Invoice

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

I looked and found an issue relating to this in the existing issues but the only response was to edit the template to your needs. I guess this is assuming where in the world I am to go to make this edit. I would like it to print in English and not German. I looked through a bunch of files but couldn't find where to go to edit the language it prints out to when I try to create an invoice.

**Comment by simonschaufi** [comment]
Copy and adjust the invoice template to your own needs. You can find it there in the folder: extensions/ki_invoice.

**Comment by wolftone1916** [comment]
I don't see anything in those files to change the language that the invoice prints in. I have en selected under the options but as far as printing invoice, I've looked at the coding and I see it has lang in there but not sure what that is calling to so maybe I could manually set it to English.

**Comment by acmeraptor** [comment]
Copy the template where you can edit it with open office. Save and upload your new template with a meaningful name to same file path.  If you can be a little patient I will share my English version I made.

⁣~acme​

**Comment by wolftone1916** [comment]
Yes of course, I would love that. I guess I'm just confused on what to do to edit it. Go mbeannaí Dia dhuit!

Joshua "Lee" Conley

 

    On Wednesday, August 8, 2018 12:43 PM, acmeraptor <notifications@github.com> wrote:
 

 Copy the template where you can edit it with open office. Save and upload your new template with a meaningful name to same file path.  If you can be a little patient I will share my English version I made.

⁣~acme​

**Comment by wolftone1916** [comment]
Just to leave this issue closed, I figured it out finally, took me a second to get it but I'm there now lol. However, I have one question, when I print to the freelancer one that uses html which I would prefer to use, even with customer selected, the name isn't listed where it says customer. Not sure if I should create another issue for that though...

**Comment by ashish-joshi-sr** [comment]
Hi can anyone share english template with me?

**Comment by acmeraptor** [comment]
⁣CasperBB Support​

**Comment by acmeraptor** [comment]
I'm still new to github on the forking and stuff. This is the way I found to share my template.  This is for version 1.1.x and needs to be updated with open office.  No other office programs seem to handle meta data correctly.
https://github.com/acmeraptor/kimai_templates
