### ISSUE TITLE
Invoices with hourly work and expenses separated out *Feature Request*

### ISSUE THREAD

**Issue by sollermun** [kimai/kimai#1243]
#### Expected behaviour
Invoices with separate tables for hourly work and expenses, a total for each, and a total for the entire invoice.
#### Actual behaviour
Creating two separate tables does not appear to work.
#### Steps to reproduce
Edit the long invoice ODT and create two tables, one for fees and one for costs. The second table is not shown when generating the invoice.
#### Reproducible on demo.kimai.org? [yes|no]
N/A
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.3

**Comment by JayAige** [comment]
Any advise on how to solve this problem? I'm facing the same issue and spent hours trying to get two tables in one invoice.

**Comment by simonschaufi** [comment]
Every entry has a `type` that you can work with. I know that the tinyDoc template is really difficult to understand but it should be possible.

**Comment by JayAige** [comment]
Anyone?

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
