### ISSUE TITLE
Date time  and project info are overlayered when window is resized

### ISSUE THREAD

**Issue by yardstudio** [kimai/kimai#1246]
Hello,

is possible better alligning informations panels when window is resized ?

#### Expected behaviour
Better positioning or alligning main page panels when window is resized

#### Actual behaviour
When window is resized then panels are "overlayed" 
http://www.yardstudio.eu/printscreens/2018-08-20_18-19-51.png

#### Steps to reproduce
simply resize window

#### Reproducible on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
newest

**Comment by simonschaufi** [comment]
Sorry, Kimai is not made for small screens. There is no responsive view available at the moment and won't be implemented soon since we want to focus on the upcoming kimai version which is responsive.
