### ISSUE TITLE
Enhancement: Change "now" link to appear over a stop button

### ISSUE THREAD

**Issue by frederickjh** [kimai/kimai#1247]
#### Expected behaviour
That it is clear to the user that setting the stop time to now will stop the event.
#### Actual behaviour
Until the "Edit Entry" dialog is close it is not apparent that this will happen
#### Steps to reproduce
Click the "now" link in an "Edit Entry" dialog and click OK.
#### Reproducible on demo.kimai.org? [yes|no]
Yes
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Current on demo.kimai.org
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
none

For more background see the thread that this [comment](https://github.com/kimai/kimai/issues/719#issuecomment-227793149) is in. I suggested this enhancement in that comment.

My idea for this would be to use the current graphic that is used for the stop button but superimpose the word "now" over the center of it. The stop graphic could be resize to fit the layout. Here is a quick mock-up of what it could possibly look like.

![image](https://user-images.githubusercontent.com/864159/44410362-831f9d80-a564-11e8-8a96-3478a1a78031.png)

I am sure that someone can make this look better with either a shadow or outlining on the word "Now".

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
