### ISSUE TITLE
expenses appear with duration -1:00 hour in PDF export when standard time is selected

### ISSUE THREAD

**Issue by piflixe** [kimai/kimai#1251]
#### Expected behaviour
expenses should not have a duration in the PDF export

#### Actual behaviour
when exporting entries (incl expenses) to PDF and "standard time" is selected as time format then -1:00 appears in the duration column on the PDF export

#### Steps to reproduce
* create expenses entry
* go to export tab
* click on "PDF"
* choose "standard time" as time format in drop down

#### Reproducible on demo.kimai.org? [yes|no]
yes

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
