### ISSUE TITLE
Start with preset time

### ISSUE THREAD

**Issue by wolftone1916** [kimai/kimai#1252]
Just curious if there is a way to do this or plans on doing it. So, basically set it so that a particular job someone is working on or project starts out with a minimum time first that can be adjusted. For instance, the company I work for pays 1 hour of drive time added to the time they clock in for. I would want it so that I could set it so that each person who is clocking in for the project that allots drive time would start out with that hour added already. If this isn't already a feature, is there any file I can edit to make it so when someone clocks in, they start with 1 hour already?

**Comment by simonschaufi** [comment]
Hi,
the thing is, what happens when you start the same task multiple times? I guess you only want that once per day but now it's getting complicated.
Could you specify a bit more what exactly you want? I could implement that as a special kimai modification for you (paid of course).

**Comment by wolftone1916** [comment]
Well for what we use it for, they wouldn't be using it more than once in a day. If they did, that would be in error and hence we would adjust that time. Basically I would want it so I could set a default start time so like say they clock in, it would set how much time they start with upon clocking in. So, we pay 1 hour drive time, they clock in and are already at 1 hour time and it's counting from there. Otherwise we have to manually add the hour into their time on each person.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
