### ISSUE TITLE
Demo + Installer broken !!!

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#1256]
As discussed in #1255 there is a good reason to always start any path assignment with a slash.

Using this:
```
defined('WEBROOT') || define('WEBROOT', dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR);
require_once WEBROOT . '/libraries/autoload.php';
```
works on every OS

And using this:
```
defined('WEBROOT') || define('WEBROOT', dirname(dirname(__FILE__)));
require_once WEBROOT . 'libraries/autoload.php';
```
fails on EVERY OS.

Please fix it (the installer and both demos are broken):
- https://github.com/kimai/kimai/blob/master/installer/processor.php#L24
- https://github.com/kimai/kimai/blob/master/error.php#L21

**Comment by simonschaufi** [comment]
should be working now again.

**Comment by kevinpapst** [comment]
demo reinstalled, works again. thx!
