### ISSUE TITLE
Batch update: append/replace to description field also

### ISSUE THREAD

**Issue by rarvin** [kimai/kimai#1256]
#1240 inrelease 1.6 bring with the fabulous feature of multi delete of entries as well as multi edit of customer, project, activity, tags as well as the user.

What would additionally be great would be the option to edit the description field for the same multi selected entries in one go. An append option or replace option would be good. If append is too difficult then a replace option would be enough. This would be greatly helpful.

If this can also be extended to later the custom columns for timesheet that would be a welcome addition too.

**Comment by kevinpapst** [comment]
Not a lot of interest, closing
