### ISSUE TITLE
Get via API the timesheets of all the users with admin

### ISSUE THREAD

**Issue by lrob** [kimai/kimai#1258]
I would like to retrieve the timesheets of all the users via API. I was expecting to achieve this result using the function getTimesheet with the admin user, but in this way I get an empty dictionary. Is there a way to achieve this result using another function?

**Comment by simonschaufi** [comment]
You could write your own API and extend from our class or you make a pull request and add this missing feature. For now it is only possible to fetch the records of one user.

**Comment by lrob** [comment]
OK, thanks for you reply. However I think that I will implement a solution that does not require to retrieve the timesheets of all the users.
