### ISSUE TITLE
The date of selection is displayed as NaN

### ISSUE THREAD

**Issue by 2686685661** [kimai/kimai#1259]
![_3](https://user-images.githubusercontent.com/28822332/46994569-8f307180-d147-11e8-9222-8440215559db.png)

**Comment by simonschaufi** [comment]
how to reproduce?

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
