### ISSUE TITLE
Need help with Active Directory Auth

### ISSUE THREAD

**Issue by marquesmatheus** [kimai/kimai#1264]
Hi, i need some help to connect kimai using Active directory.

I've changed the autoconf.php to activeDirectory and set up the auth.php like that:

<?php
return array(
	    'host' => `'ldap://dc.mydomain',`
	        'enhancedIdentityPrivacy' => 'false',
	);
?>

It's giving me the error "No user with that information `found".

On log: /var/log/apache2/ts.joaopauloii/error.log

Tue Nov 13 10:55:07.636355 2018] [:error] [pid 25708] [client 10.0.65.2:35874] PHP Warning:  ldap_search(): Search: Operations error in /var/www/kimai-ts/libraries/Kimai/Auth/Ldapadvanced.php on line 256, referer: http://ts.xxxx/index.php

I'm using my AD username from local network. What am i missing?

Thx again

**Comment by marquesmatheus** [comment]
Tested here setting:

	var_dump($usernameAttribute),
		var_dump($mailAttribute),
		var_dump($commonNameAttribute),
		var_dump($earchBase),
		var_dump($host),
		var_dump($bindDN),

All information came NULL...

**Comment by marquesmatheus** [comment]
Sure, i've checked the documentation, what configs do you need?

**Comment by marquesmatheus** [comment]
The server that i installed the kimai was on a debian 9.
It has a valid ip for the local network, on my AD server it has too a valid host AAA name.
I can ping and communicates with both of them.
The domain address is dc.somedomain
The doubt that i have is, this kind of auth from kimai using ActiveDirectory, is just pointing the kimai to the AD address and it will catch and validates the user and password from AD itself ?

Tried to config using ldapadvanced but with no sucess too...

**Comment by kevinpapst** [comment]
Please show us all Kimai configurations that you applied regarding the AD

**Comment by marquesmatheus** [comment]
With this example i can connect to AD
`<?php
if(isset($_POST['username']) && isset($_POST['password'])){

	   $adServer = "ldap://dc.somedomain";
	    	
	   $ldap = ldap_connect($adServer);
	   $username = $_POST['username'];
	   $password = $_POST['password'];

	   $ldaprdn = 'joaopauloii' . "\\" . $username;
           ldap_set_option($ldap, LDAP_OPT_PROTOCOL_VERSION, 3);
           ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);

	    $bind = @ldap_bind($ldap, $ldaprdn, $password);

	    if ($bind) {
            $filter="(sAMAccountName=$username)";
            $result = ldap_search($ldap,"dc=joaopauloii",$filter);
            ldap_sort($ldap,$result,"sn");
            $info = ldap_get_entries($ldap, $result);
           // for ($i=0; $i<$info["count"]; $i++)
		//		            {
          //  if($info['count'] > 1)
//break;

echo "<p>You are accessing <strong> ". $info[$i]["sn"][0] .", " . $info[$i]["givenname"][0] ."</strong><br /> (" . $info[$i]["samaccountname"][0] .")</p>\n";

echo '<pre>';
var_dump($info);
echo '</pre>';
$userDn = $info[$i]["distinguishedname"][0]; 
//}
@ldap_close($ldap);
} else {
$msg = "Invalid email address / password";
echo $msg;
}

}else{
?>
<form action="#" method="POST">
<label for="username">Username: </label><input id="username" type="text" name="username" /> 
<label for="password">Password: </label><input id="password" type="password" name="password" />        <input type="submit" name="submit" value="Submit" />
</form>
<?php 
} 
?> 
`

**Comment by marquesmatheus** [comment]
The only configurations that i made was:

Setting the $authenticator = "activeDirectory"; on the autoconf.php

And setting the auth.php:
<?php
return array(
	    'host' => 'ldap://dc.somedomain',
	        'enhancedIdentityPrivacy' => 'false',
	);
?>

**Comment by marquesmatheus** [comment]
Any sugestions?

**Comment by marquesmatheus** [comment]
As i said, i'm using the autoconf.php auth "activeDirectory", the auth.php file i wrote on my last post. Even using the activeDirectory auth on autoconf.php and setting the lines on auth.php is there needed to write on other file or more config to be inserted somewhere?.

I will try to use now LDAP the advanced option, just made it 2 days ago without success too :(.

**Comment by marquesmatheus** [comment]
LDAP Advanced configs files:

1 - autoconf.php
$authenticator = "ldapadvanced";

2 - auth.php
`<?php
return array(
    'host' => 'ldap://dc.testdomain',
    'bindDN' => 'CN=Matheus Ferreira Perrenoud Marques,OU=CPD,OU=TI,DC=testdomain',
    'bindPW' => 'mypassword',
    'searchBase' => 'dc=testdomain,dc=example,c=org',
    'userFilter' => 'uid=%s',
    'groupFilter' => 'memberUid=%1$s',
    'usernameAttribute' => 'uid',
    'commonNameAttribute' => 'cn',
    'groupidAttribute' => 'cn',
    'mailAttribute' => 'mail',
    'allowedGroupIds' => array('kimai-access'),
    'forceLowercase' => true,
    'nonLdapAcounts' => array('admin'),
    'autocreateUsers' => true,
    'defaultGlobalRoleName' => 'User',
    'defaultGroupMemberships' => array('Users' => 'User'),
);
?>
`

3 - Error
`[Wed Nov 14 13:50:27.319866 2018] [:error] [pid 29895] [client 10.0.65.2:48130] PHP Warning:  ldap_search(): Search: Operations error in /var/www/kimai-ts/libraries/Kimai/Auth/Ldapadvanced.php on line 262, referer: http://ts.joaopauloii/index.php
`

4 - My LDAP url with this user:
ldap://server:389/CN=Matheus%20Ferreira%20Perrenoud%20Marques,OU=CPD,OU=TI,DC=testdomain

**Comment by marquesmatheus** [comment]
Front end error:
No user with that information found

I'm using my local network login as an example testelogin and my password.
Do i need to set my domain before my user, like testdomain.testlogin on the login screen or just the network login is ok?

**Comment by kevinpapst** [comment]
Maybe someone else can jump in. 
I can just help you as far as setting up the authenticator and checking obvious setup problems. 
You can use the activeDirectoy authenticator. It extends the LDAPadvanced authenticator => so you can use all config parameters from the "ldap advanced" as well.

The config is somewhat wrong or the LDAP-advancerd authenticator uses an incompatible approach.
Please replace `ldap_search` it `var_dump` in https://github.com/kimai/kimai/blob/master/libraries/Kimai/Auth/Ldapadvanced.php#L245 and check if the values are the ones you expect to be used.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
