### ISSUE TITLE
Possible for Admin to assign users to the Manager Role.

### ISSUE THREAD

**Issue by Sangeetha1321** [kimai/kimai#1274]
Hi,
In the updated version/previous version of the Kimai whether it is possible to assign specific users to the Managers by the Admin.

And Manager needs to get the workflow of their corresponding users.

Thanks in Advance!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
