### ISSUE TITLE
Kimai Activitys 1.3.1

### ISSUE THREAD

**Issue by Gordon87** [kimai/kimai#1275]
Hi everyone,

i updated Kimai from 0.9.3 to 1.3.1...
The problem i have is after starting a new project i want to choose activitys.
In version 0.9.3 i had the possibilty to choose "all activitys"
Now in version 1.3.1 i have to select the activitys individually.

![1](https://user-images.githubusercontent.com/46001456/50228944-7479b380-03a9-11e9-9c9e-a715f2e41e47.PNG)

Is there a way to choose all of them?

Thanks

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
