### ISSUE TITLE
Project Name & Project Total only in invoice

### ISSUE THREAD

**Issue by sdo992** [kimai/kimai#1276]
#### Expected behaviour
Be able to invoice by project Name and total project hours, instead of by tasks within the project:

```
Description                                                       Total Hours Worked                 Total Billed
20181221-WebProject001                                          20                                     $1,000
20181222-WebProject002                                          15                                     $750
20181201-NetworkSupport001                                  50                                     $1,500
```
#### Actual behaviour
Unable to only list rows of projects, only one project name shows up with `[row.projectName]`
Unable to list total hours of all tasks in one project
Unable to list total billed based on hours of all tasks in a project
#### Steps to reproduce
Try to create an invoice
#### Reproducible on demo.kimai.org? [yes|no]
Unknown
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.3.1
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
No log entry

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
