### ISSUE TITLE
Report including hours and costs

### ISSUE THREAD

**Issue by Peterlundorf** [kimai/kimai#1279]
See below - thanks :-)

**Comment by Peterlundorf** [comment]
Hi
I have registered hours on different people for a specific project/activities.
For the documentation I need to include the hourly cost but I have not been able to make the hourly cost appear in the exported pdf-file.

Is it possible somehow to set a general hourly cost/person and to have the total sum of costs appear in the exported document?

Thanks many times for your help!

Regards - Peter - Denmark

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
