### ISSUE TITLE
Exported PDF as table / printed document shows all customers

### ISSUE THREAD

**Issue by blochwitz** [kimai/kimai#1280]
Hi,

when i export time entries into PDF with summary and formatted as table all customers and projects will be listed above the details list without a break.

And in the details table a # is printed instead of the project. Also the user name is not in the summary and in the details table.

A PDF formatted as list holds the user name and above the list the project name...

Screenshot of the PDF as table:
![bildschirmfoto 2019-01-22 um 13 24 05](https://user-images.githubusercontent.com/42935152/51535536-08c3b400-1e49-11e9-90d9-dda5ba76212b.png)

Screenshot of the PDF as list:
![bildschirmfoto 2019-01-22 um 13 23 06](https://user-images.githubusercontent.com/42935152/51535577-28f37300-1e49-11e9-922e-41b6fe3dae7e.png)

#### Kimai version is the latest stable

**Comment by jimlucas** [comment]
@blochwitz From your statements above, it isn't clear exactly what you are looking for.

> Hi,
> 
> when i export time entries into PDF with summary and formatted as table all customers and projects will be listed above the details list without a break.
> 
> And in the details table a # is printed instead of the project. Also the user name is not in the summary and in the details table.

The # isn't for a project name.  Looking at the code, the # should only be shown when a 'tracking number' is included on a timesheet entry.

> 
> A PDF formatted as list holds the user name and above the list the project name...

It appears that the layout for the List view does include a bit more useful information then the table view.  I am working on changes to the table view that will provide this lacking data.

[invoice_2020-04-17_07-35-45.pdf](https://github.com/kimai/kimai/files/4495595/invoice_2020-04-17_07-35-45.pdf)

What do you think of these changes?

> 
> Screenshot of the PDF as table:
> ![bildschirmfoto 2019-01-22 um 13 24 05](https://user-images.githubusercontent.com/42935152/51535536-08c3b400-1e49-11e9-90d9-dda5ba76212b.png)
> 
> Screenshot of the PDF as list:
> ![bildschirmfoto 2019-01-22 um 13 23 06](https://user-images.githubusercontent.com/42935152/51535577-28f37300-1e49-11e9-922e-41b6fe3dae7e.png)
> #### Kimai version is the latest stable

**Comment by simonschaufi** [comment]
The thing about this issue is that 100 people want to have 100 different PDFs. It's not the best option but the only one possible with Kimai 1: You need to adjust the PDF renderer yourself if you want a different output. Therfore I'm closing this issue.
