### ISSUE TITLE
installation without ssh

### ISSUE THREAD

**Issue by 9daccad9** [kimai/kimai#1284]
I am trying to install kimai without ssh-access. In the documentation is written:

No SSH possible (not recommended)
In case you only have FTP or SFTP access to your hosting environment, you can still install Kimai, but you won’t easily be able to upgrade your installation once a new release is out.

Please note that this is not a recommended setup!

Uncompress kimai.zip locally
Delete all files except:
includes/autoconf.php
any self made invoice templates under extensions/ki_invoice/invoices/
any self written extensions under extensions/

But when I unzip the file kimai_1.3.1.zip, the directory includes/ does not conain a file autoconf.php

**Comment by 9daccad9** [comment]
Only this files are in the folder includes/

![screenshot01](https://user-images.githubusercontent.com/47082574/51803576-02717580-2257-11e9-8408-065f9082b07d.jpg)

**Comment by kevinpapst** [comment]
The autoconf will be created when running the installer. The sentence you mention is only meant for updates. If updating via FTP you have to make sure, that the autoconf file is not replaced/deleted.

**Comment by 9daccad9** [comment]
Thanks for your answer!
But how do I make a new instal when having no ssh-access?

**Comment by kevinpapst** [comment]
The complete list point `Delete all files except` is only meant for updates.
Uncompres the ZIP, upload all files, open your browser and point it to index.php

**Comment by 9daccad9** [comment]
I have now transfered via ftp the whole unziped package to a new directory kimai, which looks something like this:
`https://www.example.xy/kimai/installer/`  (example.xy stands for my url)

When I take a browser now and go to the url
`https://www.example.xy/kimai/index.php` the browser jumps automatically to
`https://www.example.xy/kimai/installer/index.php` and the browser only shows a black content.
![image](https://user-images.githubusercontent.com/47082574/51847127-5180de80-231b-11e9-9fb0-8e059e81257f.png)

What did a made wrong?

**Comment by simonschaufi** [comment]
I have no idea but maybe your biggest mistake is using IE :)

**Comment by simonschaufi** [comment]
Can you please press F12 and check the console for errors?

**Comment by 9daccad9** [comment]
I got this errors:
![image](https://user-images.githubusercontent.com/47082574/51908092-1806ac80-23c9-11e9-9d85-ae2f9a08bde5.png)

**Comment by 9daccad9** [comment]
We could find one reason for the error at beginn of installing:
The file ../installer/index.php conains a "Q" instead of a "q" ... so the right path was not found ... see picture
![image](https://user-images.githubusercontent.com/47082574/52346096-1cf9da80-2a1f-11e9-8622-214a7a538e4f.png)

But I can not get much further:
After choosing Language and accapting General Public License the next error is coming:
![image](https://user-images.githubusercontent.com/47082574/52346302-9eea0380-2a1f-11e9-89a9-3ff3d4e286b3.png)

What is the problem here? Does anybody know?

**Comment by Dan88Man** [comment]
I had the same issue with PHP version not matching.

Go into your webspace providers settings and check which PHP version is activated for this domain. You should be able to change it to a higher version, just by a dropdown menu.

Please note that other scripts on the same domain will be affected by the PHP version change as well. Make sure to test them if you have anything else running on that domain.

If something doesn't work anymore, you can easily change the PHP version back to the current state. It is not a permanent change and it will not overwrite any of your files.

Which webspace and domain provider are you using?

**Comment by 9daccad9** [comment]
I am using this provider
https://chilly.domains/en/hosting/hosting.html
and from there products the one which is named "chillyHost Bronze"

**Comment by simonschaufi** [comment]
Please use at least php 7.0 if possible, otherwise php 5.6

**Comment by 9daccad9** [comment]
I have checked:
Server Antwort (Status Code): 200 OK
PHP Version: PHP/7.3.2
Webserver: Apache

Dont know, why kimai says php-version 5.5 ....

**Comment by simonschaufi** [comment]
About the "Q" see https://github.com/kimai/kimai/tree/master/libraries. The folder is correct with a capital Q.

**Comment by simonschaufi** [comment]
I haven't used php 7.3 yet. For now we can only say it works well with php 7.2

**Comment by 9daccad9** [comment]
Ok. I'have named manual now the folder with a capital Q (after my installation it was namend with a "q" and took the original ../installer/index.php.
But I can not get further until the error named with php-verion 5.5

**Comment by 9daccad9** [comment]
I could change now the php-version für the concering directory to 7.2
![image](https://user-images.githubusercontent.com/47082574/52350753-8aab0400-2a29-11e9-91ff-b705ce49a0b4.png)

but still the same error:
![image](https://user-images.githubusercontent.com/47082574/52350917-de1d5200-2a29-11e9-9112-698be502882c.png)

**Comment by kevinpapst** [comment]
Please switch to the network tab in your browsers dev-tools and copy&paste the reply that causes this error. Should be a POST to the URL "processor.php".
Maybe there is a PHP error, which then can't be evaluated in the frontend.

**Comment by 9daccad9** [comment]
Do you mean this (found unter processor.php):
![image](https://user-images.githubusercontent.com/47082574/52356489-99e37f00-2a34-11e9-901b-3cc3dd73ee86.png)

**Comment by kevinpapst** [comment]
Well yes, that explains the problems you are facing.
I just downloaded the 1.3.1 zip and the file `libraries/composer/ClassLoader.php` is in there, so you have to check why it can't be found in your installation.
As you already had problems with the capital Q, you maybe have a problem with the file transfer. Does your FTP lowercase all filenames? Whatever is going on there, it seems to be a server issue and not a Kimai bug.

**Comment by 9daccad9** [comment]
Finally done,
Kevin, you're right. All the problems arose because of the not proper upload. The ftp-client made uppercase letters to lowercase letters in serveral file-names.
Now I used "ncftp" for uploading and it works!
**THANKS** to all of you for the help!!
