### ISSUE TITLE
I cannot see admin dashboard

### ISSUE THREAD

**Issue by j3korn** [kimai/kimai#1287]
#### Expected behaviour
No problem on admin dashboard

#### Actual behaviour
Error when I try to see the admin dashboard

#### Steps to reproduce
see the admin dashboard

#### Reproducible on demo.kimai.org? [yes|no]
no

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
version 2
![error](https://user-images.githubusercontent.com/13186026/54165549-2a93ed00-442f-11e9-825d-54bfa07cffa3.PNG)

**Comment by kevinpapst** [comment]
Seems you are running out of memory. Nothing I can fix.
Is this a shared hosting or do you manage the server & database yourself?
As this is a SQLSTATE error, its coming from the database. But if you are using SQLite it might be PHP as well. Never saw this error before.

**Comment by kevinpapst** [comment]
And btw: Kimai 2 is here https://github.com/kevinpapst/kimai2
