### ISSUE TITLE
Where do I put Matomo / Google Analytics snippet?

### ISSUE THREAD

**Issue by davidtessier** [kimai/kimai#1288]
#### Expected behaviour
I'd like to be able to place my Matomo (formerly Piwik) site tracking javascript snippet in this system. I'm not sure where it should be placed. Could someone let me know? This is similar to a Google Analytics javascript snippet. Ideally, this would appear in the `<head>` section of any page I visit.

I'm using the Kimai 2 (0.8.1)

Thanks for the assistance!

**Comment by hmr-it-jr** [comment]
if you have question related to kimai2 you should post it to kimai2 repository and not to the kimai 1 repository.
