### ISSUE TITLE
Is it possible to make super_admins be able to connect from any IP adress, but users only from workplace's IP.

### ISSUE THREAD

**Issue by xpresas** [kimai/kimai#1289]
#### Expected behaviour
Super_Admins ROLE should be able to connect from any IP adress just like right now. 
But simple user could connect only from a certain IP. 
I was looking into security.yaml and some symfony documentation. I am junior level programmer so I can make some things myself. Altho I havent tried it yet. So my question: is it possible to do on a current stable kimai version?

**Comment by kevinpapst** [comment]
Wrong repo, this is Kimai1.
Go to http://github.com/kevinpapst/kimai2 for Kimai 2.

**Comment by simonschaufi** [comment]
@kevinpapst can you transfer the issue to kimai 2?

**Comment by kevinpapst** [comment]
Too late, already a new one was created. But I will  try it with the next one, totally forgot about that new option.
