### ISSUE TITLE
Undefined index: projectGroups in /var/www/timetracker/core/processor.php on line 330

### ISSUE THREAD

**Issue by ClintfromCanada** [kimai/kimai#1292]
It seems that all usage of the website is disabled until I restart apache once one of these errors shows up.  This error is from the apache error log.

I also get the same error from the above file on line 335

I'm trying to transition to v2 but for the time being I am trying to just keep up v1 with the current database until I can move to v2 and I cannot figure out where to attack this problem.  Has anyone seen such an animal before?

**Comment by simonschaufi** [comment]
This error is too generic, I can't say anything about it. My kimai works great for years.

**Comment by jimlucas** [comment]
@ClintfromCanada is this issue still of concern or have you transitioned to Kimai2 yet?

If it is an outstanding issue still causing you problems, I can take a look at it.  Initial investigation of those two lines of code I can see see a potential problem that could cause an error.

To investigate further, I would need a little more information.  What version of PHP and Kimai are you currently running?

**Comment by ClintfromCanada** [comment]
Thanks for getting back to me. We have since moved to another custom made
platform.

Best regards,

Clint
