### ISSUE TITLE
Update errors from v0.9.3 to v1.3 

### ISSUE THREAD

**Issue by ShortBuss** [kimai/kimai#1293]
Hello-

I installed Kimai development version 0.9.3.1380 way back when & it's been just great! I need to update because of depreciated php 5.6. I'm planning on updating to 1.3 for a stable version before I up the php to 7.1. At time of v2 update I'll up to php7.2 or 7.3.
Recently I had the same problems as in this thread:

https://github.com/kimai/kimai/issues/751

The 2 items (UPDATE kimai_membershipRoles SET core-user-view = 1 WHERE name = 'Admin'; UPDATE kimai_membershipRoles SET core-user-view = 1 WHERE name = 'Groupleader';) in red.

Would the resolution in that thread work in my situation? 

Thanks in Advance
Karl

**Comment by simonschaufi** [comment]
Maybe, you should definitely not "try" it on production. Make a backup of your database and reset it back if update failed and then try to fix the error by hand so that the migration will be green.

**Comment by ShortBuss** [comment]
Thanks for the prompt response. I always backup everything before changing anything. I will try the manual fixes found on that thread...

**Comment by ShortBuss** [comment]
I added the core-user-view column to the kimai_membershipRoles table, update to 1.3.1.1394 went smooth! Switched to php 7.1, gonna try 7.2 & 7.3 to see if 1.3 stands up.

**Comment by jimlucas** [comment]
I can confirm that v1.3.1.1394 runs fine on PHP 7.3.6
I am logging all errors and do not see any being generated by the system when browsing around the GUI.
