### ISSUE TITLE
Stored XSS 

### ISSUE THREAD

**Issue by osamaalaah** [kimai/kimai#1295]
There is stored XSS in the index.php/en/timesheet/ 

To reproduce this vulnerability :

1-Create time sheet 
![kimai1](https://user-images.githubusercontent.com/16985503/61182857-a8644100-a639-11e9-8057-6359f6494f9f.png)

2-use this payload "><svg/onload=alert('xss')> in the description field 
![kimai2](https://user-images.githubusercontent.com/16985503/61182858-a8fcd780-a639-11e9-916b-051301408731.png)

**Comment by kevinpapst** [comment]
Thanks for reporting. Nevertheless, I am deleting this issue.
This is not Kimai 1 and please use the Security reporting function.

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/kimai2/network/alerts
