### ISSUE TITLE
View problem after updating to 1.3.1

### ISSUE THREAD

**Issue by hypersonic64** [kimai/kimai#1296]
Hi,
we had to update our old 0.9 version to 1.3.1 due to PHP upgrade to 7.3.
Now we have the problem that some of the entries are no longer shown in the export view (and also missing in the Excel sheet exported) and the time sum on top is too low.
When I change to the export page all relevant entries are shown and the time sum on top has the correct value for half a second or so until the ajax request for processor.php with axparm parm reload_timeSheet is answered. After that some entries are missing (8 of 75 entries). They are assigned to four projects belonging to two customers.
I compared the projects and customers with others directly in a database viewer but they don't show any differences in the columns (only in ids and name of course).
The update process ran w/o problems.
The same problem often occurs in the normal timesheet view but there you can get around by pressing F5. After that the missing entries are shown until I enter the next activity.
But even after pressing F5 still both the customers are not shown in the lower filter box.

Any ideas?
Thanks 
Hyper

**Comment by hypersonic64** [comment]
ok, seems like I found the cause of the issue: The group I belong to doesn't have the customer assigned.
So, although I can create activities for this customer's projects these activities are not shown in the export.

Maybe this bug can be fixed?

Thanks
Hyper

**Comment by simonschaufi** [comment]
Hello Hyper,
thank you for reporting this issue. Since this is an edge case and kimai 1 is outdated, I don't want to spend more time in a bugfix. If it is really important for you, then we can talk about it but I will only offer this as a payed service.
