### ISSUE TITLE
Feature Request: Adding webcal/ical-Calendar next to Google Calendar

### ISSUE THREAD

**Issue by saschafoerster** [kimai/kimai#1297]
I would like to add our team-holiday-calender, but our opensource-tool for holiday-management "only" gives us a open ical-feed. Actually, people that love self hosting their time-app should also prefer to keep their calendars on their severs. ;)
https://github.com/timeoff-management/application

**Comment by kevinpapst** [comment]
Wrong repo?

**Comment by saschafoerster** [comment]
@kevinpapst No, I mean this feature here: https://www.kimai.org/documentation/calendar.html

**Comment by kevinpapst** [comment]
Right. Then you are talking about Kimai 2. This is the repo for Kimai 1.
