### ISSUE TITLE
Date selector expense item

### ISSUE THREAD

**Issue by jlpeifer** [kimai/kimai#1301]
#### Expected behaviour
Kimai v1 --> Expenses --> Add --> Day --> (a valid date entry accepted)

#### Actual behaviour
Kimai v1 --> Expenses --> Add --> Day --> (two things)
first... the pre-populated date that shows up in the field isn't formatted correctly. First instance, an entry made today the date shows up as "0808.1010.1919".
second... using the date picker will result in a property formatted date, but then submission of the entry isn't allowed until the date format is changed back to above. Have to accept the oddly formatted date, get into phpmyadmin, change the timestamp manually.

#### Reproducible on demo.kimai.org? [yes|no]
No... demo seems to be running v2

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.3.2.1394

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
![kimai](https://user-images.githubusercontent.com/5297832/66379951-70dd0a80-e984-11e9-8e2a-e6dab6f22867.png)

**Comment by jimlucas** [comment]
First off, official support for v1.X has stopped.  They are only working on v2.x going forward.

But...  with that said, make sure under the Admin Panel -> Advanced area that your required date formats look like the attached image.


![Allowed Date Formats](https://user-images.githubusercontent.com/1685780/66429673-5f6c2080-e9cd-11e9-92f8-4fcca35fd355.png)

**Comment by simonschaufi** [comment]
Yeah, sorry that we don't support other date formats than that in the datepicker. Won't fix as it is quite complex and official support for v1 has stopped.

**Comment by jlpeifer** [comment]
@simonschaufi, Simon... I appreciate, but am saddened, that v1 is being phased out. I took a stab at installing and using v2 on a subdomain in my shared environment and ended up having to pay @kevinpapst to help me get it running (never had an issue installing v1). The lack of a free expense tracking option a real detriment and the reporting options just weren't as helpful to my billing process as is v1. Yes, the UI was sleek but v1's UI is functional and still appealing. If you're not going to entertain supporting this perhaps it'd be best to remove the "Simon is still trying to keep it alive" reference at the bottom of [this](https://www.kimai.org/v1/) page?

@jimlucas, Jim... thank you for the helpful response regarding date formats. This helped resolve the problem.

**Comment by kevinpapst** [comment]
I doubt that you **had** to pay me. You asked me for paid help, as it turned out because nginx was misconfigured, not because of Kimai 2. 

This is open source, send PRs or fork Kimai 1 or v2 and make it better.
We spent our free time to give away the present of a free software. 

You are in the IT business yourself but don't want to pay for software. I hope your customers are different and value your time and work.

**Comment by simonschaufi** [comment]
@kevinpapst yes, you should actually remove that part on the website.
