### ISSUE TITLE
Rounding Issue since v1.3.3

### ISSUE THREAD

**Issue by hh-it-co** [kimai/kimai#1302]
Since v1.3.3 there is an issue with the rounding-function. If i add an entry manually like this
![kimai_rounding_before](https://user-images.githubusercontent.com/14543259/67319174-de547380-f50c-11e9-9194-97cfb2ee95b3.png)

it will actually be stored like that
![kimai_rounding_after](https://user-images.githubusercontent.com/14543259/67319329-10fe6c00-f50d-11e9-81d9-e16539b6e4a8.png)

If the end time had been 20:29:59, it would have been rounded correctly, like expected.
I expect, that times should be forced to be rounded to a full 15 minutes, no matter if the entry is added manually or "recorded".

If have activated these 2 options:
![kimai_rounding_option_1](https://user-images.githubusercontent.com/14543259/67320240-3d66b800-f50e-11e9-8862-e561502f4981.png)
![kimai_rounding_option_2](https://user-images.githubusercontent.com/14543259/67320250-3f307b80-f50e-11e9-805e-1edb78d73e9f.png)

**Comment by simonschaufi** [comment]
Thank you for the info. I actually fixed a but in this process but introduced another one as it seams. I will have a look into this.

**Comment by simonschaufi** [comment]
@hh-it-co that bug is more complex than I thought since the original rounding function has the same problem that when the time matches with the steps to round to, it shifts to the next step (+15 min in your case)

**Comment by simonschaufi** [comment]
Fixed in Release 1.3.4

**Comment by hh-it-co** [comment]
Thanks for your investigation. I've tested your fix, but it does not work as expected. Now, it seems like the rules for rounding will completely be ignored, except for recorded entries. The rounding is not forced as before during manual processing. Entries with less than the rounding-time will be rounded down, no matter if rounding down is allowed or not.
