### ISSUE TITLE
Different behaviour of actions button in kimai v2

### ISSUE THREAD

**Issue by codexdb** [kimai/kimai#1305]
#### Expected behaviour
Action button in all menus related to last column of tables with class
datatables should open the drop down selection box the same way.

#### Actual behaviour
Choosing menu Timesheets shows different behaviour.

#### Steps to reproduce
1. Open menu Timesheets.
2. If not already created, add some new timeshhets.
3. Click on the lowast Actions button.
4. The related drop down opens inside the datatable, so you has to use scroll buttton to see selections.

#### Reproducible on demo.kimai.org? [yes|no]
Not reproducible if logged in as anna_admin.

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.4.2 stable (Ayumi) (the same as in demo).

In my test environment I had only 4 timesheets, in the kimai demo are thousands to scroll down to last row. I tried to flatten my screen viewport, so I had to scroll too, but no improvement.

**Comment by kevinpapst** [comment]
Wrong repo, please re-post here: https://github.com/kevinpapst/kimai2

**Comment by kevinpapst** [comment]
Btw: you can create new users in the demo to test it
