### ISSUE TITLE
Add clocktime based surcharges

### ISSUE THREAD

**Issue by mr2017x** [kimai/kimai#1312]
Hello,

maybe another Idea for future processing are timebased surcharges like
Monday until Friday from 9 am to 17pm is 10€ / h but between 17pm and 22pm is +15% and Weekend at all 25%, Weekend-Nights +50%. All based on Standardtime + calculated additive.

i hope this would be possibile? if you have further questions regarding this idea, feel free to contact me.

thanks in advance!

**Comment by kevinpapst** [comment]
Closing in favor of https://github.com/kimai/kimai/issues/309
