### ISSUE TITLE
[Feature request] Support splitting totals for payment

### ISSUE THREAD

**Issue by vogelfreiheit** [kimai/kimai#1313]
I would like to suggest a feature that might be useful for some people including myself: supporting split totals in invoices. For example, specify that a certain amount off the total invoice amount will be paid to a different bank account, and the remainder to another one.

So far I have not been able to find a way to do this without resorting to somewhat convoluted use of dual invoicing, but I might have missed something.

**Comment by simonschaufi** [comment]
Kimai v1 won't get any new features. If you want to have this feature in the new version, then please open another issue at https://github.com/kevinpapst/kimai2 but since this is very unusual, you probably have to implement that yourself.
