### ISSUE TITLE
Problems Installing Kimai on XAMPP

### ISSUE THREAD

**Issue by PayShop** [kimai/kimai#1315]
#### Problem
Hello,
I'm trying to install the development version of Kimai on XAMPP since yesterday, but I'm missing something along the way. I downloaded the files, created a folder on htdocs named Kimai and extracted the files into the folder. When I go to localhost/kimai I only see the index page and nothing happens.
Can anyone help me?

I tried with docker too, but when I try to run the docker I receive the error saying that the command server:run is not defined.

Thanks in advance!

**Comment by kevinpapst** [comment]
This is Kimai 1, you are looking for Kimai 2: https://github.com/kevinpapst/kimai2
In the development version the command `server:run` was removed, use a proper webserver or something like the https://symfony.com/doc/current/setup/symfony_server.html
