### ISSUE TITLE
Mailer-Daemon: Kimai tried to send mail to reset password without recipient

### ISSUE THREAD

**Issue by KlausHB** [kimai/kimai#1316]
Hi,

today Kimai sent an email without recipient trying to reset a password.

Our mailer-daemon sent me the information You can read below.

Is this a hacking attack?
What happend?

Best regards

KlausHB

#### Actual behaviour

This message came from our mailer daemon:

------ This is a copy of the headers that were received before the error
      was detected.

To: 
Subject: =?utf-8?Q?Kimai=20-=20Passwort=20zur=C3=BCcksetzen?=
X-PHP-Script: <here was the domain of our server>/processor.php for <here was an ip number>
From: Kimai - Open Source Time Tracking <>
Date: Wed, 08 Jan 2020 00:28:49 +0100
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline
MIME-Version: 1.0

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai Version: v1.3.1.1394

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

**Comment by simonschaufi** [comment]
The admin email should be used as sender. Did you set that?

**Comment by KlausHB** [comment]
Because the mail was sent out, there ist a admin user. But here there was no recipient.
I just tried klicking the button for forgotten password in another browser without any data in the name field. The same message came from mailer daemon.

So I now think a stranger just clicked this button too. And my fears that this might be some kind of attack are less now.

**Comment by simonschaufi** [comment]
I close this issue as this feature works as expected. If there is something else I missed, please let me know.
