### ISSUE TITLE
Dashboard view request to move between weeks

### ISSUE THREAD

**Issue by lowrob** [kimai/kimai#1318]
#### Expected behaviour
On the Dashboard screen in the top section of My Working hours graph and totals uner it - it would helpful to users if they were left and right arrows that would allow you to go back a number of weeks (one week at a time) and show "WORK HOURS THIS WEEK" for the week you are on.  

This is really Feature Request - give me a price to do the work and I can try to get you some $$$

#### Actual behaviour
Shows only the current week

#### Steps to reproduce
Existing funtionality

#### Reproducible on demo.kimai.org? [yes|no]
Yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Was using the demo site - latest stable version.

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
NA

**Comment by kevinpapst** [comment]
This is Kimai 2, the feature you are asking for is Kimai 2: https://github.com/kevinpapst/kimai2
I am closing this issue here. 

Please find my email via my profile/website and send me a short message, so we can talk about sponsoring this feature.
