### ISSUE TITLE
Kimai v1 - Reset User Password - from PHP

### ISSUE THREAD

**Issue by demsley** [kimai/kimai#1319]
Apologies if this is the wrong place to post.  I seem to have lost all access to my Kimai v1.  All users are reporting: 

Access denied!
Wrong Username and/or Password 

How might I reset the password (via command line or phpmyadmin) please?

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.3.2

**Comment by simonschaufi** [comment]
Well, if they can use the password reset feature, you just need to set their email address if they didn't set it before. You could also generate a default password with your own secret. This is how you can generate it:

```php
md5($salt . $password . $salt)
```

so if your salt is `123abc` and the password `password` then generate the secret like so:

```php
md5('123abcpassword123abc')
```

**Comment by demsley** [comment]
The solution is also avialable on:   https://github.com/kimai/kimai/issues/1137
Thanks simonschaufi
