### ISSUE TITLE
Export: downloaded Excel file does not open and Csv file does not support utf-8 character set

### ISSUE THREAD

**Issue by furkantolu** [kimai/kimai#1323]
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[kimai-export (2).xlsx](https://github.com/kimai/kimai/files/4306514/kimai-export.2.xlsx)

**Comment by kevinpapst** [comment]
This is a wrong repository.
Can you please repost this issue at: https://github.com/kevinpapst/kimai2/
