### ISSUE TITLE
Deprecated: Function get_magic_quotes_gpc() in Ultimate MySQL Wrapper Class

### ISSUE THREAD

**Issue by renatoandradeweb** [kimai/kimai#1324]
In PHP 7.4.2 the extension is deprecated.

Deprecated: Function get_magic_quotes_gpc() is deprecated in mysql.class.php on line 1592

**Comment by simonschaufi** [comment]
Kimai 1 is not developed further on. Please switch to Kimai 2 or keep the PHP version at 7.2 or 7.3
