### ISSUE TITLE
Think about a cooler name

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#133]
## Description
Kimai 2 is boring. Ideas:
- Kimai X: Space X, owncloud X...
- Kimayeni (mix of kimai and yeni (new in Aserbaidschan))
- Kimainovo (Bosnien)
- Kimaibaru (Indonesien)
- Totally different name like piwik -> Matomo

**Comment by xakiru** [comment]
Yea, I prefer Kimai which is clear and small name. But it won't attract more audience who would think it's just an update.

Maybe adding a second name would be good. Here few names that I can think of :
Kimai Lemon (use citrus fruits names in the future if needed, that start button always reminds me of a half a citrus)
Kimai 2.0 (the obvious one)
Kimaii (kawaii cute in japanese)
Kimayo (sounds cool)

**Comment by simonschaufi** [comment]
`Kimai Lemon` +1

**Comment by kevinpapst** [comment]
Kimai will stay as base name, there is definitely no room for changes at that part.
Fruits are then one option as "theme" for the first phase. 
It would be nice to have some design resources, so we could visually show a "Kimai-Lemon/Lime" e.g. on the website or an about dialog ...

**Comment by kevinpapst** [comment]
If anyone wants to contribute an icon, please open a PR.

**Comment by simonschaufi** [comment]
It would be really cool to remove the 2 out of the version as this version is not just a new release but a totally new product, so it should have its own name as well.

**Comment by kevinpapst** [comment]
You want a new name but at the same time remove the 2 => then its "Kimai" again. I guess I can't follow.

**Comment by simonschaufi** [comment]
`Kimai Lemon`. -> Kimai Lemon 1.0; Kimai Lemon 2.0 and so on...
