### ISSUE TITLE
"Missing Time Period" when generating invoice

### ISSUE THREAD

**Issue by nwinesett** [kimai/kimai#1330]
#### Expected behaviour
Select Invoice Tab
Select Customer
Select Project
Use Datepicker to select from and to dates
Select any available invoice
Select round time 0.1
Select all for "include entries"
select oldest first
leave uncheck "mark entries as cleared"
click "create"

Should open the selected invoice with time entries.  Worked with v1.3.1

#### Actual behaviour

Now a browser window pops up from  https://**/extensions/ki_invoice/print.php stating:
"Missing time period"

#### Steps to reproduce
see above

#### Reproducible on demo.kimai.org? [yes|no]
n/a
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.3.5|github master
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
uncertain
However, this is similar to Issue #1210, but I didn't understand the resolution there.

**Comment by nwinesett** [comment]
In reviewing Issue #1210, I would note that I also upgraded from 1.3.1 to 1.3.5 so I have a newer installation.  However, I attempted an invoice dated today (similar to what  that user attempted), but I still go the "missing time period" result.  As such, I'm still trying to figure out the error so I can print invoices again.  Anyone have an idea for me to try?

**Comment by jimlucas** [comment]
I have not been able to replicate this issue.  It could be due to configuration options you have set in the Advanced Settings or possibly something to do with the timesheet entries.

I have setup a demo install on my development folder, please use this for comparing and testing to see if you can replicate this issue.

https://www.cmsws.com/development/kimai/
User: guest
Pass: guest

**Comment by nwinesett** [comment]
@jimlucas Thanks for looking at this.

Invoices pull up properly on your demo site.  There is no admin panel on the demo so I can't see the configuration

My settings:
![image](https://user-images.githubusercontent.com/60666725/79227397-729cf480-7e25-11ea-9f0a-157d4186f8e9.png)

I used to have datepicker as mm.dd.yy and datepicker for php m.d.y, but the datepicker didn't work that way as it still put in dates with the day first (i.e. you graphically pick April 1st in datepicker, but the timesheet entry ends up being generated for January 4th).

I will note that the "Missing Time Period" also happens on my backup 1.3.1 installation (using the same database).

I have tried this on many different projects with different dates and always the same result.

**Comment by nwinesett** [comment]
Additional troubleshooting notes:

1) tried switching datepicker to mm.dd.yy and datepicker in PHP to m.d.y:  Still received same error.

2) checked the kmxe_timeSheet table in my phpMyAdmin for any missing or errant entries in the start and end columns.  There were none and everything looked normal to me.  It's hard to read those unix dates but everything was between 1476806040 and 1597040340.

3) I made a brand new customer and project for the admin user and entered a timesheet entry for it today.  When I tried to make an invoice for this customer, project, and timesheet entry, I still got the same Missing Time Period error.

**Comment by simonschaufi** [comment]
@nwinesett I have no idea what is your problem but I offer payed support if you need help on your machine.

**Comment by jimlucas** [comment]
> @jimlucas Thanks for looking at this.
> 
> Invoices pull up properly on your demo site. There is no admin panel on the demo so I can't see the configuration
> 
> My settings:
> ![image](https://user-images.githubusercontent.com/60666725/79227397-729cf480-7e25-11ea-9f0a-157d4186f8e9.png)
> 
> I used to have datepicker as mm.dd.yy and datepicker for php m.d.y, but the datepicker didn't work that way as it still put in dates with the day first (i.e. you graphically pick April 1st in datepicker, but the timesheet entry ends up being generated for January 4th).
> 
> I will note that the "Missing Time Period" also happens on my backup 1.3.1 installation (using the same database).
> 
> I have tried this on many different projects with different dates and always the same result.

One of the Date format fields is wrong.  Here is a screen shot of the defaults.  Notice the middle field.  You have 'd.m.y' and it should be 'd.m.Y'.  Update that and lets see if it works now.

![Date Format defaults](https://user-images.githubusercontent.com/1685780/79272429-49e12300-7e56-11ea-8aaf-229e34180a78.png)

**Comment by nwinesett** [comment]
@simonschaufi  Thanks for your offer and I will keep that in mind.

@jimlucas  Voila!  That was it!  Thank you!

Here are my best settings for me in the US:

![image](https://user-images.githubusercontent.com/60666725/79355124-e660ff00-7f02-11ea-90f6-3e4e637a5e9f.png)

So, for everyone's reference, that means that you cannot use any format shown in the "notation for date" link (i.e. http://php.net/manual/en/function.date.php).  As far as I can tell, you must use dd.mm.yy for datepicker and d.m.Y for datepicker in PHP to have everything work properly.  You CAN however change the "Date format of the timespan" and the "Date format for tables" as I have done, and it mostly looks right.  For me, it is not a problem.  Buy my other users who are not familiar with a day/month/year format might be confused by the text showing in the datepicker for timesheet and invoice.  As long as they stick to the graphical date selection, they should be fine.  If a user wants to type in the date, they have to remember it's day first, month second.  Otherwise, the timesheet entry will be entered backwards.  However, with my settings, month/year still shows in the more important areas like the timesheet table and on invoices as long as they stick to the graphical datepicker or remember to enter text dd.mm.yy.

If they enter it backwards accidentally, it causes these problems:

1) April 1st would be entered as January 4th, so the timesheet entry would be out of order or disappear if it's not in your selected time period.
OR
2) Worse, April 14th would be entered as ???? (There is no month for 14, so in my system it just disappears altogether from the timesheets and is no longer accessible by Kimai.  I assume it is accessible in the database and would have to be corrected there.  That's hard because the dates are in Unix format.
 
I'm showing the datepicker here, where with my now working settings, and that it still shows Day/Month/Year in the date picker text entry, which is something you have to deal with unless it's reconfigured down the road:

![image](https://user-images.githubusercontent.com/60666725/79355553-7141f980-7f03-11ea-8fe6-4527af4986a0.png)

So that is another issue/feature which could be opened, but I'm going to close this one and just mention it for someone else who encounters this problem.

**Comment by kevinpapst** [comment]
All of these problems are not existing in Kimai 2 😁 

Thanks for sharing these infos for other users!

**Comment by nwinesett** [comment]
@jimlucas @kevinpapst 

Regarding:
> Worse, April 14th would be entered as ???? (There is no month for 14, so in my system it just disappears altogether from the timesheets and is no longer accessible by Kimai. I assume it is accessible in the database and would have to be corrected there. That's hard because the dates are in Unix format.

I checked my database and here is what happens.  The unix date entered for the time entry when I put April 14th in backwards as 04.14.2020 was 1612468680, which equals Feb. 4, 2021.  So it appears that the timeentry date adds 2 months (14 minus 12) past the year (2020).  So, 04.15.2020, would go in as March, 4, 2020 and so forth.  That might help someone out down the road.

To fix, I just changed the first 5 numbers (so as to change the date, but not the time... so **16124**68680 became **15868**68680.  Do the same for start and end columns.  This might not work perfectly, but I used [https://www.silisoftware.com/tools/date.php](url) to check my conversion.

LOL @kevinpapst ... Kimai2 may have less bugs and I understand there are reasons to switch, but the most important feature to me is usability.  It has to be fast and fluid, which I find in Kimai1 but not Kimai2.  See my more detailed comment: [https://github.com/kimai/kimai/issues/1327#issuecomment-612564138](url)

I'll keep an eye on it, but Kimai 1 works best for me right now :)

**Comment by nwinesett** [comment]
@jimlucas @kevinpapst 

> To fix, I just changed the first 5 numbers (so as to change the date, but not the time... so 1612468680 became 1586868680. Do the same for start and end columns. This might not work perfectly, but I used https://www.silisoftware.com/tools/date.php to check my conversion.

One more thing... I just realized that you don't have to edit the database.  Since it just adds those months onto the end of the year, just change your time period to way in the future and you can edit them from Kimai after all!
