### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by nwinesett** [kimai/kimai#1331]
#### Expected behaviour

User's Global roles are set as follows:

![image](https://user-images.githubusercontent.com/60666725/79093662-91629480-7d1a-11ea-8e94-f443fe0d43c1.png)

Activities are all in the admin group, not user group.

If the User is allowed to "add, assign, and view" "Activity, different group", then it seems that the activiites should appear in the user's lower list.  They do not.

In order to get the activities to appear, I have to add the admin group to the user, OR the user's group has to be added to the activity. 

In my scenario, I don't want the user to be able to make changes to these particular activities in the "admin" group, but i want the user to be able to use and assign them to their timesheet entries.

Am I misunderstanding "activity, different group"?

#### Actual behaviour
Activites of a different agreement do not appear in the lower list.
#### Steps to reproduce
see above
#### Reproducible on demo.kimai.org? [yes|no]
n/a
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.3.5 master
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
none

**Comment by simonschaufi** [comment]
That whole permission thing is so complicated, even I as a maintainer of the core don't understand it. I would highly recommend to try out Kimai2 as Kimai 1 is not developed further.

**Comment by nwinesett** [comment]
LOL, that makes me feel better.  I'm going to play with it and report what I find, but it would be nice to know what the intent of the settings is.  I'm unclear what assign/unassign is supposed to do, but I assume it means add them to a time entry.  The goal would be as follows:

1.  Admin user can see and edit everything.
2.  Staff user account can see everything, edit customer and projects only
3.  Associate 1 user/group can see all customers and projects in his group, and assign to his time entries (but can't see Associate 2 user/group customers/projects/time entries)
4.  Associate 2 user/group can see all customers and projects in his group, and assign to his time entries (but can't see Associate 1 user/group customers/projects/time entries)
5.  Make standard Activities that can be seen and used by all, but not deleted or edited.
6.  Allow Associate 1 and 2 to each make their own custom activities as well.

**Comment by nwinesett** [comment]
@simonschaufi @jimlucas @kevinpapst 

My Permissions Findings:

_From the Admin Panel:_

![image](https://user-images.githubusercontent.com/60666725/79528757-781a5a80-8030-11ea-8bad-b810d283be21.png)

![image](https://user-images.githubusercontent.com/60666725/79623927-4ebb0680-80e4-11ea-9512-d557f707deaf.png)

1.  BUG-"Add" permission:  If a user has the Admin Panel enabled in their assigned global role, then they can add **customers**, **projects**, **users**, and **activities** to any group and can also add "**status**" even if their global role has "add" unchecked.  However, the add button **"+"** is properly missing from the Timesheet extension if "add" is unchecked (as long as none of the user's roles have and "add" permission).  Also, the user properly cannot add **groups** or **users** from the Admin Panel or Timesheet extension if "add" is unchecked.

![image](https://user-images.githubusercontent.com/60666725/79624009-a2c5eb00-80e4-11ea-94c6-000724c43ceb.png)

2.  BUG-"Global Roles" and "Membership Roles" fully editable by all if user has access to Admin Panel:   Even if "edit advanced settings" is unchecked in the user's global role, they can still see, add, delete, and edit the global roles and membership roles if they have access to the Admin Panel.  This effectively means that any user with access to the Admin Panel has complete system access, since they can change their role to provide access.  As you will see below, a user cannot see any customers, projects or activities from another group from the Timesheet extension, regardless of the permission settings.  Giving them access to the Admin Panel is not a suitable substitute since they have access to these roles.  _Note:  I haven't tried it, but I'm thinking that you might block yourself entirely from the Admin Panel if you were to uncheck the Admin Panel for the admin user and all other users._

Ideas to fix:

- [ ] Move Global and Membership Roles to "advanced settings"

- [ ] Change/fix Timesheet extension to show customers, projects, and activities in other groups if the user's global role allows it.  Even if a user needs access to these things, it may be undesirable for this access to be in the Timesheet as a user may not want to see these things from other groups as it would clutter up the things they actually work on.  In this case, you might want to have another filter button to filter out things from other groups.

- [ ] Or, my favorite, create a new Extension(s) (e.g. tab) for Customers, Projects, and Activities to be seen in other groups (if allowed).

3.  **Edit**, **Delete**, and **View** global permissions do work in the Admin Panel, but can't see anything not in your group in the Timesheet extension.

4.  **Assign** and **Unassign** means _Assigning to a Group_:  Assign and unassign global permissions refer to the ability to add a customer, project, or activity to a group.  These permissions do work in the Admin Panel.  I had intuitively thought assign/unassign would mean to assign/unassign to a timesheet entry, but that is incorrect.  

- [ ] I suggest clarifying the description to "assign group" and "unassign group."

_Results from the Timesheet extension:_
5.  **Users**, **Customers**, **Projects**, and **Activities** MUST be in your group(s) to use:   Each can be in one or more groups.  A user can also be in one or more groups.  If the other user, customer, project, or activity is NOT in any of the user's groups, then the they will NOT appear in the user's Timesheet tab and will NOT appear in the "add timesheet entry" floater no matter what the user's global role is, no matter what permissions are set in that global role, and no matter what permissions are set in the membership roles.  THEREFORE, you cannot add a Timesheet entry except to items in your group(s).  

I hope the above is helpful to folks.  A lot of trial and error to figure that out.

**Here are my suggested settings to accomplish my goal in the previous post**
_Note:  You need to separate "groups" and "global" and "membership" roles in your mind and name them differently so you don't mix them up.  I kept mixing them up or overlapping them in various ways._ 

**Suggestion:**  Give Customers, Projects, and Activities their own groups with descriptive names.

1.  **Groups:**  customersALL, projectsALL, activitiesLOCKED, associateONE, associateTWO
2.  Assign all customers to customersALL AND either associateONE OR associateTWO
3.  Assign all projects to projectsALL AND either associateONE OR associateTWO
4.  Assign standard activities that you want users to use but NOT edit or delete to activitesLOCKED
5.  **Global Roles:**  adminDOALL, SEEALL, SEEGROUPONLY

**SEEALL.**  
![image](https://user-images.githubusercontent.com/60666725/79628970-1b3fa280-810b-11ea-9b9b-bd848d009e3d.png)

**SEEGROUPONLY**
![image](https://user-images.githubusercontent.com/60666725/79629003-796c8580-810b-11ea-93fd-bed367bc9e25.png)

6.  **Membership Roles:**  adminDOALL, staffEDITCUSTOMERSPROJECTSONLY, associatesADDACTIVITYONLY, SEEONLY

**staffEDITCUSTOMERSPROJECTSONLY**
![image](https://user-images.githubusercontent.com/60666725/79629044-c0f31180-810b-11ea-8079-5398ddad4d85.png)

**associatesADDACTIVITYONLY**
![image](https://user-images.githubusercontent.com/60666725/79629078-fd267200-810b-11ea-824c-37e72b13585c.png)

**SEE ONLY**
![image](https://user-images.githubusercontent.com/60666725/79629252-a28e1580-810d-11ea-8dd5-70f0c05f8a96.png)

7.  admin user = adminDOALL (global role), adminDOALL for all groups, all groups assigned
8.  staff user = SEEALL (global role), staffEDITCUSOMERPROJECTSONLY for customersALL and projectsALL
9.  associateONE user = SEEGROUPONLY (global role), associatesADDACTIVITYONLY for associateONE, and SEEONLY for activitiesLOCKED

10.  associateTWO user = SEEGROUPONLY (global role), associatesADDACTIVITYONLY for activitiesLOCKED and associateTWO

Voila.... I've accomplished my goal.  The only thing I can't seem to do with the current setup is allow associates to be able to see all customers and projects, without having access to the Admin Panel, but only have the customers assigned to them in the Timesheet extension.  For that, we would need one of the new feature solutions suggested above.

**Comment by simonschaufi** [comment]
Thank you very much for your research. Since this version of Kimai is not developed further, I'm only doing payed modifications. If you want something to be changed, let me know and we will find a way for the payment.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
