### ISSUE TITLE
One solution when installer won't run and states:  run composer install --no-dev

### ISSUE THREAD

**Issue by nwinesett** [kimai/kimai#1333]
#### Expected behaviour
1.  Copy Kimai v1 files to hosted website
2.  Navigate to new installation
3.  Installer runs successfully

#### Actual behaviour
On my webhost, I navigate to the new installation and it fails and reports something to the effect of: 
**run  composer install --no-dev**

So, I opened an SSH terminal to run this command.  However, the command failed on my server and complained that allow_url_fopen and proc_open must be enabled.
#### Steps to reproduce
See above
#### Reproducible on demo.kimai.org? [yes|no]
N/A
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.3.5
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
None

My solution:
I was able to get this working but wanted to report it here in case it helped someone else.
1.  Open SSH terminal
2.  cd to the directory on your host where you copied the kimai v1 files
3.  run the following command:
php -d allow_url_fopen=on /opt/cpanel/composer/bin/composer install
4. (Apparently Optional)  I say optional because the following didn't seem to work because composer install still complained about proc_open not being enabled afterwards, but I made a custom php.ini file and made the following edit to php.ini in my public_html directory:
;trying to get kimai v1 installer to work
enable_functions = proc_open 
5.  In your browser, navigate to your new installation
6.  The installer now runs properly (at least for me)

Hope this saves someone some time down the road.

**Comment by simonschaufi** [comment]
Thanx for sharing. You could have done that also locally and upload all the files.

**Comment by nwinesett** [comment]
@simonschaufi I don't understand what you mean.  I was thinking the problem was php dependencies on my webhost installation.

**Comment by simonschaufi** [comment]
If you're having problem with composer, you can execute the same command on your machine and then just upload the whole project. That will give you the same result.
