### ISSUE TITLE
Kimai V1.9 Reset Super Admin Password

### ISSUE THREAD

**Issue by yoadee** [kimai/kimai#1334]
I can't access my super admin account, I have tried to google my way forward but to no avail.
I downloaded the DB and used an argon2id encoder with the right settings to try and change the password that way manually but when I exported the DB it came out way smaller than the original and I got a 500 error when trying to access Kimai.

I have no autoconf.php file or /includes folder either since I uploaded through FTP and have no SSH access.

Is there any other way to change the DB that I am not aware of? I used DB Browser for SQLite on Mac OS

#### Reproducible on demo.kimai.org? [yes|no]
No
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v 1.9

**Comment by jimlucas** [comment]
I believe you are looking for Kimai 2.  Go here: https://github.com/kevinpapst/kimai2

**Comment by simonschaufi** [comment]
sorry but version 1.9 does not exist

**Comment by kevinpapst** [comment]
@jimlucas https://www.kimai.org/documentation/users.html#admin-password-forgotten
