### ISSUE TITLE
Email when reaching 25%, 50% and 75% of budget

### ISSUE THREAD

**Issue by yweidmann** [kimai/kimai#1335]
Dear kimai

I have a basic question about the functionalities of _kimai_ (I wasn't able to find some hints about it in the documentation):
Is it possible, that _kimai_ sends out automatically an email-notification if the sum of the time spent in a project reaches a certain limit (e.g. 25%, 50% and 75% of budget)?

Would be great.

Looking forward to any hints.

Best regards,
Yvo

**Comment by kevinpapst** [comment]
Kimai 2 is here: https://github.com/kevinpapst/kimai2
