### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by imadmoussa1** [kimai/kimai#1336]
Hello,
I had been testing kimai with different languages,
I add new translations in translations/*.en.xlf but not reloaded in webpage.
Do I need to send PR for the changes ? or these changes can take effects locally while translating the text and how?

Thank you

**Comment by simonschaufi** [comment]
@imadmoussa1 Could you tell me how you ended up in this repository?

**Comment by imadmoussa1** [comment]
@simonschaufi I was following this tutorial https://www.kimai.org/documentation/translations.html

**Comment by simonschaufi** [comment]
no I mean here in github?

**Comment by kevinpapst** [comment]
Hi @imadmoussa1 - please repost your question here: https://github.com/kevinpapst/kimai2/issues

**Comment by imadmoussa1** [comment]
Hi @kevinpapst I will thank you.
I asked the question in the wrong folder.

**Comment by simonschaufi** [comment]
yes that was my question. many users end up here and I wanted to know how you did end up here. is there somewhere wrong link?

**Comment by imadmoussa1** [comment]
@simonschaufi
while reading the documentation https://www.kimai.org/documentation/translations.html. I click on this link https://github.com/kimai/www.kimai.org/blob/master/_features/multi-language.md in 
the second point in the Finalization step, I ended under https://github.com/kimai/www.kimai.org and I moved to the project folder https://github.com/kimai/kimai

**Comment by simonschaufi** [comment]
ok. thank you. this path we can't change of course.

**Comment by simonschaufi** [comment]
@kevinpapst maybe put a github link somewhere on the website?
