### ISSUE TITLE
500 internal Server Error CentOS8

### ISSUE THREAD

**Issue by sahara101** [kimai/kimai#1337]
#### Expected behaviour
Working kimai
#### Actual behaviour
500 internal Server Error CentOS8
#### Steps to reproduce
Installed using the Ubuntu 18.04 wiki with a few changes. 
1. installed php-mysqld
2. installed mariadb
3. chown using the user nginx
4. had to modify /etc/nginx/nginx.conf to include /etc/nginx/sites-enabled/kimai2
5. had to modify /etc/nginx/default.d/php.conf to add the fastcgi_pass
6. created host entry for www.kimai.local
7. skiped SSL config

If I try www.kimai.local I am directly greeted with 500 internal server error....

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.9
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
Cannot find any logs at all
Thank you!

**Comment by kevinpapst** [comment]
This is Kimai 1, you want Kimai 2: https://github.com/kevinpapst/kimai2

I bet you have wrong file permissions, check var/log/prod.log (in the Kimai directory).
