### ISSUE TITLE
Sessions are timing out, leading to data loss and requiring repeated logins

### ISSUE THREAD

**Issue by RayCulp** [kimai/kimai#1339]
#### Expected behaviour
In previous versions, the session did not timeout after a period of inactivity
1. Log in
2. Start a new entry, enter some text in the desciption
3. Wait a while
4. Try to save the entry
5. The entry is saved

#### Actual behaviour
A recent update seems to have added a session timeout time
1. Log in
2. Start a new entry, enter some text in the desciption
3. Wait a while
4. Try to save the entry
5. The entry cannot be saved because the session has timed out
6. You are redirected to the login page

#### Steps to reproduce
1. Log in
2. Start a new entry, enter some text in the desciption
3. Wait a while
4. Try to save the entry

#### Reproducible on demo.kimai.org? [yes|no]
Yes (see video here https://mixdrop.co/f/pkkw8n8nh8dwqe)

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.10.2 stable (Ayumi)

**Comment by jimlucas** [comment]
Wrong version.  You need this: https://github.com/kevinpapst/kimai2

**Comment by RayCulp** [comment]
Thanks for the response, but I think you may be mistaken. I'm on Kimai 2, but the version number it reports is 1.10.2 stable (Ayumi).

**Comment by kevinpapst** [comment]
@jimlucas is right, please head over to https://github.com/kevinpapst/kimai2
