### ISSUE TITLE
DELETE ENTRY TIMESHEETS - Entry could not be deleted

### ISSUE THREAD

**Issue by EdoardoMDP** [kimai/kimai#1340]
Hi,

I got this error message when i try to delete items on timesheets:

![image](https://user-images.githubusercontent.com/31856288/94782379-6c96d200-03cb-11eb-9be1-43c506620c24.png)
Entry could not be deleted:
parsererror

There is nothing in the log file.
Could you help me?
Thanks

Kimai version: 1.10.2 stable

**Comment by kevinpapst** [comment]
Please go here: https://github.com/kevinpapst/kimai2
And check your browser console and network tab, there might be a related error

**Comment by EdoardoMDP** [comment]
I'm not getting any errors.
if I delete the item from the dropdown menu on the right, I get the error.
![image](https://user-images.githubusercontent.com/31856288/94785161-7a4e5680-03cf-11eb-9c02-09362e7007bc.png)

but if I select the item and delete it from the menu that appears at the bottom of the page, it works

**Comment by kevinpapst** [comment]
You are in the repository of Kimai 1, please open a new issue for Kimai 2 in https://github.com/kevinpapst/kimai2

**Comment by simonschaufi** [comment]
@kevinpapst why don't you just move the issue over to your repo?

**Comment by kevinpapst** [comment]
Unfortunately I can't, moving issues works only in the same organization
