### ISSUE TITLE
[Custom Fields Paid] Custom fields not returning with API metaFields property

### ISSUE THREAD

**Issue by AddoSolutions** [kimai/kimai#1341]
#### Expected behaviour

Including the provided meta fields in API results

#### Actual behaviour

![image](https://user-images.githubusercontent.com/3859209/96035117-94a51d00-0e30-11eb-9392-d3ce0bf97f6f.png)

#### Steps to reproduce

Vanilla install

#### Reproducible on demo.kimai.org? [yes|no]

![image](https://user-images.githubusercontent.com/3859209/96035376-f2396980-0e30-11eb-8918-8cc17d2c0d53.png)

**Comment by kevinpapst** [comment]
I invited you to the repository of the plugin (you should have received an email from Github), please reopen the issue there.
Closing here as this is the wrong repository and I cannot transfer the issue.
Kimai 2 core is here: https://github.com/kevinpapst/kimai2

**Comment by kevinpapst** [comment]
BTW: I checked the demo and you forgot to activate "Visible" for the new "Test" field.
<img width="1052" alt="Bildschirmfoto 2020-10-14 um 21 42 08" src="https://user-images.githubusercontent.com/533162/96037427-1e231200-0e66-11eb-9003-9b2f97424db8.png">
