### ISSUE TITLE
Floaters not oppening

### ISSUE THREAD

**Issue by sofiendamiP** [kimai/kimai#1343]
Hello everyone,

I tried to add a new checkbox in the window, when adding a new project.
I added the ckeckbox in the file templates/floaters/add_edit_pct.tpl.
Now, when I try to add a new project, the window doesn't open and I get only a small window with the writing floaters on it.
Can anyone help me ?

Thank you !

**Comment by simonschaufi** [comment]
sorry, no support here any more. Check the browser console for javascript errors.
