### ISSUE TITLE
Small question about custom fields

### ISSUE THREAD

**Issue by Solidus-Prime** [kimai/kimai#1344]
I am trying to follow the guide on custom fields located here:

https://www.kimai.org/documentation/meta-fields.html

and have read it over a few times, and can't figure out which document to paste the text into. Forgive me if this is obvious. I am really inexperienced with PHP in general, but got our server up and running on Windows Server with your guide. Everything is going great, we are just trying to get these custom fields in.

Thanks a lot for your efforts, btw. It is really appreciated.

**Comment by kevinpapst** [comment]
Wrong repository, Kimai 2 lives here: https://github.com/kevinpapst/kimai2

You can buy the plugin, it handles everything for you:
https://www.kimai.org/store/custom-fields-bundle.html
