### ISSUE TITLE
Kimai2 url access from hosting windows machine

### ISSUE THREAD

**Issue by rjayaser** [kimai/kimai#1346]
#### Expected behaviour
we should get access to kimai2 url which is running inside oracle vm 6.1, from the hosting windows server machine e.g http://192.168.56.101/kimai2/public/en/login, where 192.168.56.101 is the vm m/c ip which is Ubuntu 18 version. 
#### Actual behaviour
we are not able to access the kimai2 login page, but we are able to access the kimai2 install root folder i.e document root. 
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop] 
![oraclevm_setting_details](https://user-images.githubusercontent.com/67286004/108168789-debf4780-711d-11eb-9e9f-b52fa9d961cc.png)
Kimai2

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
![kimai2_login_page_access_error](https://user-images.githubusercontent.com/67286004/108168548-7ff9ce00-711d-11eb-88fc-c756d1802cd0.png)
![apache2_homepage_kimai2_docroot](https://user-images.githubusercontent.com/67286004/108168551-812afb00-711d-11eb-96a9-34a66bbac3dd.png)

**Comment by kevinpapst** [comment]
Kimai 2 is here: https://github.com/kevinpapst/kimai2
Obviously your Apache config is wrong. Document Root should point to public/
https://www.kimai.org/documentation/webserver-configuration.html
