### ISSUE TITLE
Report page's week/month switcher doesn't work

### ISSUE THREAD

**Issue by TeNNoX** [kimai/kimai#1347]
#### Expected behaviour
Navigating to next/previous month shows different results

#### Actual behaviour
The button correctly adds a "&date=2021-02-01" to the URL, but the page still shows the month **march**.

#### Steps to reproduce
1. go to reporting page
2. click next/previous week
3. See the same week

#### Kimai version 1.11.1 stable (Ayumi)
from latest docker `kimai/kimai2:fpm-alpine-master-prod`

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
```
kimai_1  | 192.168.208.2 -  31/Mar/2021:12:35:12 +0000 "GET /index.php" 200
nginx_1  | 172.18.0.2 - - [31/Mar/2021:12:35:12 +0000] "GET /en/reporting/month_by_user?user=2&date=2021-02-01 HTTP/1.1" 200 52795 "https://kimai.txlab.io/en/reporting/month_by_user?user=2&date=2021-02-01" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1  | 192.168.208.2 - - [31/Mar/2021:12:35:12 +0000] "GET /health HTTP/1.1" 200 5 "-" "Wget"
nginx_1  | 172.18.0.2 - - [31/Mar/2021:12:35:13 +0000] "GET /api/timesheets/recent?size=10 HTTP/1.1" 200 4327 "https://kimai.txlab.io/en/reporting/month_by_user?user=2&date=2021-02-01" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
kimai_1  | 192.168.208.2 -  31/Mar/2021:12:35:13 +0000 "GET /index.php" 200
```
`var/logprod.log` is empty

**Comment by simonschaufi** [comment]
Thus repo is for v1 only.
