### ISSUE TITLE
Time-clock mode, but still editable by user afterward

### ISSUE THREAD

**Issue by serotonie** [kimai/kimai#1349]
Hi there,

Is there a way to use Time-clock as Timetracking mode but that the users are still able to edit the begin and end times afterward ?
I'd like to propose a ''one-click only'' solution to be abble to record the woking taks when in a rush, but at the end of the week, the users should be able to complete/edit everything they did.

Thanks a lot

**Comment by kevinpapst** [comment]
There are so many ways to quickly add a new record (calendar, restart, copy, last activities) - what is wrong about them?

**Comment by kevinpapst** [comment]
BTW. Kimai 2 is here: https://github.com/kevinpapst/kimai2
