### ISSUE TITLE
Lexoffice API connection #feature-request

### ISSUE THREAD

**Issue by Tzunamik** [kimai/kimai#1350]
Hi,

is it possible that the kimai cloud provides a api connection to lexoffice.
So that customers could by synced and time entries would be automatically sent to lexoffice for invoices.

**Comment by kevinpapst** [comment]
Thanks for posting! Unfortunately you are in the wrong place. 
Could you please go here and post again: https://github.com/kevinpapst/kimai2/issues

Lexoffice sounds very interesting. I will try to find out more.
