### ISSUE TITLE
Change the Week Starting Day?

### ISSUE THREAD

**Issue by warwagon86** [kimai/kimai#1351]
Hi is it at all possible to change the starting day of the week?

For example we want to run our timesheets from Thursday to Thursday.

Many thanks in advance.

**Comment by kevinpapst** [comment]
Interesting concept of a week 😁 
About which screens are you talking exactly?
Dashboard and calendar?

**Comment by warwagon86** [comment]
Haha I know. Just the Timesheet and calender screens. We only have 10
employees but it's just trying to make it easy for them to log hours.

Thanks

Ryan

**Comment by kevinpapst** [comment]
Not possible right now and I don't see this feature anytime soon. 
Would mean a lot of coding work for ... well a very small feature.
