### ISSUE TITLE
after update 1.15.2 to 1.16.9 ; server error 500 for some time records only

### ISSUE THREAD

**Issue by yroberttissot** [kimai/kimai#1352]
### #### Expected behaviour
To be able to open all time records and edit them
#### Actual behaviour
If I open any time records from one specific customer, I get the Error 500
Before the update, I had no issues with that customer

After a while, I can't open the timesheet at all. If I reload through the console, I can access again the timesheet, even open the record of the specific client, but if I try to edit and save -> 
![image](https://user-images.githubusercontent.com/70005531/148045611-30e747bb-3f8e-4b94-9718-25d7ac5340d2.png)
And after that, I get the Server Error when I try to open the record

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.16.9 prod
PHP 7.4.26
server  Linux h2web234 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1+deb9u1~deb8u1 (2020-06-09) x86_64

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
log file is weirdly empty and all permissions look fine:
![image](https://user-images.githubusercontent.com/70005531/148044680-73ace644-f647-41cb-b69d-a5371188bf46.png)

from the server, I only have these logs
kimai.XXX.com [Tue Jan 04 09:19:33.297743 2022] [fastcgi:error] [pid 22760:tid 140075375515392] (104)Connection reset by peer: [client 194.XXX:0] FastCGI: comm with server "/home/clients/d3ba84e1add40dfe16a751e5ab76e7c7/.config/apache/kimai.XXX.com/.fpm/php5.external" aborted: read failed: "Connection reset by peer", referer https://kimai.XXX.com/public/en/timesheet/
kimai.XXX.com [Tue Jan 04 09:19:33.297814 2022] [fastcgi:error] [pid 22760:tid 140075375515392] [client 194.XXX:0] FastCGI: incomplete headers (0 bytes) received from server "/home/clients/d3ba84e1add40dfe16a751e5ab76e7c7/.config/apache/kimai.XXX.com/.fpm/php5.external", referer https://kimai.XXX.com/public/en/timesheet/

**Comment by kevinpapst** [comment]
Wrong repository, go here: https://github.com/kevinpapst/kimai2. 
Anyways, this is definitely not a Kimai bug. Maybe a wrong update process. Composer?
