### ISSUE TITLE
Zugriff auf die Variablen aus Projektfortschritt (Dashboard)

### ISSUE THREAD

**Issue by HeinzWuert** [kimai/kimai#1362]
**Is your feature request related to a problem? Please describe.**
Die Variablen aus Dashboard > Auftragsfortschritt für Excel verfügbar machen

**Describe the solution you'd like**
Es geht insbesondere um die Variable: "bereits verbrauchte Zeit" aus dem Stundenkontingent

**Comment by kevinpapst** [comment]
Available for PDF exports. Also available in the report section.
I think best is to be able to export reports.
