### ISSUE TITLE
Add help text to form elements

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#138]
## Description
Add help text to form elements (placeholder / static text below).

The help text below should be rendered like this:

```html
<div class="form-group">
    <label class="control-label" for="inputSuccess">Label</label>
    <input class="form-control" id="inputSuccess" placeholder="Enter ..." type="text">
    <span class="help-block">Help block</span>
</div>
```

**Comment by kevinpapst** [comment]
See https://symfony.com/blog/new-in-symfony-4-1-form-field-help
We need to fix #149 first and the use it instead of the custom implementation in the linked branch
