### ISSUE TITLE
User defined format of date edit field

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#139]
> The date fields in the Edit Entry Dialog don't follow the formatting specified on the Admin Panel's Advanced settings. Now that I look at it more closely, perhaps the date-formatting rules don't apply to the Edit Entry dialog. It would be nice if either they did apply, or there was a place to set the format.

see forum post: http://forum.kimai.org/index.php?topic=1738.0
Another comment at http://forum.kimai.org/index.php?topic=3781.msg9285#msg9285

**Comment by kevinpapst** [comment]
Another comment at http://forum.kimai.org/index.php?topic=3781.msg9285#msg9285

**Comment by packzap** [comment]
Forgive my ignorance, but how do you vote for this?

**Comment by kevinpapst** [comment]
Hey, you did already just by commenting ;-) Otherwise people tend to add a comment with "+1"

**Comment by packzap** [comment]
Ah, thanks!  +1

**Comment by MAndrecPhD** [comment]
+1

**Comment by Gregyski** [comment]
+1 I hope the [international standard ISO 8601 datetime format](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations) will be made viable as well.  Thank you.

**Comment by coldchain** [comment]
+1

**Comment by fganong** [comment]
+1

**Comment by dbrisser** [comment]
+1

**Comment by mdavi62** [comment]
+1

**Comment by kevinpapst** [comment]
Archiving old issues. [Please switch to Kimai 2](https://github.com/kevinpapst/kimai2)...
