### ISSUE TITLE
Show total working hours on dashboard

### ISSUE THREAD

**Issue by davidus05** [kimai/kimai#1403]
**Is your feature request related to a problem? Please describe.**
We have a project which started in 2019 and is going until summer 2020. My users want to see their total working hours on this project. Now in the dashboard you can only see today, this week, this month and this year.

**Describe the solution you'd like**
I would like to change out the "this year" on the dashboard with "total" or add this point to the dashboard.

**Describe alternatives you've considered**
As an admin I have to export the timesheet for the user, set the date range to from 2019 and then see the total hours for the user and can tell him.

Is there any way to do this currently? Thanks!

**Comment by kevinpapst** [comment]
Check the demo. If you configure teams, their projects will show up on the dashboard with a progress bar.

**Comment by davidus05** [comment]
Yes, we have teams enabled and configured. But the users want to see their time only in total. Not the total project-work of all team members together.

**Comment by kevinpapst** [comment]
Well, not possible with a pre-made widget right now. You can build your own (see docs). 
Other solution: they need to filter their timesheet by the project and then use the PDF print.
