### ISSUE TITLE
Reporting / Controlling extension

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#142]
Forum post:
http://forum.kimai.org/index.php?topic=481.0
http://forum.kimai.org/index.php?topic=907.0

Kimai tracks a lot of data but currently provides almost no way of creating statistics and reports. A new extension could provide that. It could display diagrams and tables which aggregate existing data.

Giving the user the ability to build the graphs by himself would be really amazing. For example, he could select to create a chart which shows the total worked hours over the past year. But if this too complex, we could just provide some standard diagrams.

[![bountysource](https://api.bountysource.com/badge/issue?issue_id=1909178)](https://www.bountysource.com/issues/1909178)

**Comment by 3screens2eyes** [comment]
Hi,

any word on the status of this? Would really like to use it. Also, did you see my post of May 4 or know what happened to it?
.
-- 
Regards,
-- 3screens2eyes

**Comment by claudegel** [comment]
Hi,
working on it should be ready this weekend

Claude Gelinas agr.
Phyto Ressources Inc.

**Comment by simonschaufi** [comment]
If you want to support that feature financially, please head over to https://www.bountysource.com/issues/1909178-reporting-controlling-extension and post a bounty. Thanx!

**Comment by davidrothschild** [comment]
Hi guys, I tried testing @ServiusHack 's reporting branch, but I don't see any difference.  I was expecting to see a new "reporting" tab added or something like that, but I'm not seeing anything.  Am I missing something?

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
