### ISSUE TITLE
Daily working time

### ISSUE THREAD

**Issue by AchMol** [kimai/kimai#1483]
Hi all,
we use Kimai v1 for a long time und think about renovation... ;-)

Is there any possibility to configure or add a add-on for target time/is time (8h/day) in Kimai v2?

Thanks,
AchMol

**Comment by kevinpapst** [comment]
Not yet

**Comment by AchMol** [comment]
Are there any plans to add this feature?

**Comment by kevinpapst** [comment]
Entering the target time is just the first and most simple part of the feature...
Yes, it is planned, bas it is a very complex feature I am waiting for financial supporters.

**Comment by AchMol** [comment]
Ah ok, I understand...

**Comment by x-jokay** [comment]
> Entering the target time is just the first and most simple part of the feature...
> Yes, it is planned, bas it is a very complex feature I am waiting for financial supporters.

And how much will it cost to get this feature implemented? :wink:

**Comment by kevinpapst** [comment]
In latest version available. Also this plugin adds many more features: 
https://www.kimai.org/store/controlling.html
