### ISSUE TITLE
PWA Support to allow Desktop installation

### ISSUE THREAD

**Issue by leopf** [kimai/kimai#1560]
Add a service worker and manifest.json to the project, allowing desktop installation and asset caching.

I suggest to add the "workbox-webpack-plugin" to the webpack.config. It automatically generates all caching rules required for the application.

For the manifest.json generation (including icon scaling etc.) I suggest the webpack plugin "webpack-pwa-manifest". 

I have workes with both plugins before. They are very easy to use and don't obstruct the deployment process. I would be happy to contribute, solving this request!

**Comment by kevinpapst** [comment]
That would be awesome! I would love to see that. Can you share some infos what we can do with it? I have only theoretical knowledge about PWAs from a few years ago.

If you start working on it, I can contribute my knowledge about Kimai and its "frontend stack" ... but I guess it is easy to understand for real frontend/JS developers. Mainly basic compilation tasks and a self-baked plugin system.

**Comment by leopf** [comment]
Great to hear!

There are a lot of things you could do!

1. Web-Notifications without having the Website opened.
2. Use the share API of mobile phones. That way you could start Time-Tracking by sharing a text to Kimai (there are probably better use cases).
3. Theoratically allow complete offline use. That would require the frontend to be decoupled from the backend. With local storage or IndexedDB you could f.a. store not yet saved time entries and commit them once the client is online again.
4. Obv. desktop/homescreen installation.

There are a lot more things beeing added and things that I don't know about, but it seems like a great fit for Kimai. 

For now I would start with caching css, woff2, js and ico files. The service worker can then be extended to allow for notifications, complete offline use etc.

**Comment by kevinpapst** [comment]
Might be a lot of necessary changes, but they are worth the effort. 
I wanted to decouple front-end / backend for a longer time, so this could be a very good reason to start it.

**Comment by adrianrudnik** [comment]
PWA support is nice, but it has hard limits and a very high technical debt once you come to topics like offline or disconnected usage scenarios. It mostly works on Google products and only makes sense if you want to offer a shortcut to install a website as a website-app. I dont think that Safari and Firefox are feature complete as Chrome is in this regard.

That limits the feature set that makes sense for PWA to propose an app install. As the app itself is always-online, it is also always-cached if the headers are set correctly and there is no scenario where it should be unusable on desktop or mobile right now.

As for the push feature, this relies heavily on a push service via websockets (or god forbid gsm) which can be done via PWA but thats not a requirement and would work better for all platforms without PWA. It could be done right now with mercure / centrifugo or any other service that allows the backend to push via REST and publish into secured channels that require authentication by clients.

Most of the stuff seems to be almost there for installs.

**Comment by kevinpapst** [comment]
If somebody wants to contribute code, please go ahead!
Right now, you can already install Kimai as chrome app and on mobile phones as "start screen link".
