### ISSUE TITLE
Add register user function

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#164]
Add functionality for self-registration

**Comment by sideeffect42** [comment]
While I agree that a registration function is nice to have I disagree about it being enabled by default.  
I would argue that in most situations where Kimai is used the users are managed by some person in the company or there is only one user at all.

I consider registration being enabled by default an *unnecessary security hole* that might give people access to Kimai that shouldn't.
In addition self-registration should be easy to enable or disable.

The procedure to disable self-registration described in [the docs](https://github.com/kevinpapst/kimai2/blob/master/var/docs/users.md#user-registration) didn't work for me.
Are there any additional steps required after adjusting the configuration?

I had to patch the .htaccess to ensure no new users could register:
```
RewriteRule ^\w+/register - [F]  # forbid self-registration
RewriteRule ^\w+/resetting - [F]  # forbid password reset
```

**Comment by kevinpapst** [comment]
@sideeffect42 I checked the documentation and you were right, it was not complete / outdated. I improved it, see the above commit. Hope that works better.

I also added two config settings that you can have in the file `config/packages/local.yaml` to be safe for upgrades, which can be used to disable password-reset and user-registration.

For now I will keep these features active by default, as disabling it is only a minimal change in one config file.

**Comment by sideeffect42** [comment]
@kevinpapst Thank you very much for your rapid response.
After clearing the cache it now works.

With the latest version I could successfully disable both registration and password resets by adding these lines to `config/packages/local.yaml`:
```yaml
kimai:
    user:
        registration: false
        password_reset: false
```

**Comment by kevinpapst** [comment]
Thanks for your quick feedback!
Please post any idea as new issue, I want to develop Kimai 2 together with the community and every feedback is highly appreciated.
