### ISSUE TITLE
Feature request: tasks tab to add task management

### ISSUE THREAD

**Issue by stephenreda** [kimai/kimai#165]
Okay imagine this: in the main tabs we put a new tab 'Tasks'.
I know this name could cause some confusion with the already existing 'tasks'.
My idea is that you can create a task, and assign it to somebody from your team.
this task has a status (uninitiated, open or closed).
In the task is a link to start a new time entry.
This would allow for some kind of task-management.
The main functionality is that you can add a todo for another use. We already work with budget and reports so why not start working more towards a project-management application. 

![screen](https://f.cloud.github.com/assets/2557554/453346/09fd045a-b312-11e2-8650-7e9d9ac01a73.jpg)

In addition to this we could use a color scheme to indicate the status of a task in relation to the timesheets:
in progress: when time entry('s) for the task is present and due date is not yet passed.
overdue: when the task is not closed before due date.
finished in time: when time entry('s) for the task is added, and the task is closed before due date.
![screen](https://f.cloud.github.com/assets/2557554/453397/958e1822-b314-11e2-8bdc-c9c6523a336a.jpg)

If we add a field for estimated time of work, then we could work towards a function which checks for overtime on a project and also a specific task ( overtime ideao Issue #144 )

**Comment by WebBen** [comment]
Sounds great! Somebody wants to make that?

**Comment by wagonpusher** [comment]
This is the one feature that im missing in Kimai.

**Comment by piflixe** [comment]
I like the idea but would recommend serious thinking on the subject since task management is a huge subject on its own and will always be incomplete if only realised briefly. I would rather suggest working together with task management project like redmine, openproject, trac or alike.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
