### ISSUE TITLE
 Time multiplier for nightshift

### ISSUE THREAD

**Issue by JujanS** [kimai/kimai#1695]
how can I adjust that the wages / salaries in the time from 21: 00-06: 00 is 25% higher. Sorry for my bad englisch skills iam from Germany

**Comment by Kantime** [comment]
Not possible for know. In the futur maybe. The are working on it.

**Comment by JujanS** [comment]
but when is the future. because of corona we all have twice as much to do and often work 13 hours at a time. we are a care company and cannot use kimai if there is no shift percentage. I wanted to simplify the timesheets for Mlt Kimai

**Comment by kevinpapst** [comment]
Hallo @JujanS - ihr könnt gerne die Entwicklung finanzieren und dann wird es eingebaut.

**Comment by Kantime** [comment]
C'est sympa de changer de langue en cours de fil de discussion !

**Comment by kevinpapst** [comment]
Pff, my software, my issue tracker, my rules 😁 
Hint: use deepl or google translate

**Comment by JujanS** [comment]
Oh du sprichst Deutsch :) Wir sind ein Pflegeunternehmen und könnten uns so eine Unterstützung vermutlich einfach nicht leisten. Wir würden natürlich eine solche Erweiterung kaufen wie zum Beispiel die Plugin Preise auf der Website von kimai aussehen wäre es absolut annehmbar. Kimai ist eine sehr gut strukturierte Arbeitsoberfläche allerdings wirklich nicht einsetzbar ohne Stunden Prozente. Es würde unser haus wesentlich smarter machen.

**Comment by kevinpapst** [comment]
Ja, das finanzielle verstehe ich. Dummerweise lebt es sich von einer kostenlosen Software auch nicht so richtig gut ^^
Da ich mit Schichtarbeit keinerlei Erfahrung habe und auch keinen Überblick wie da angerechnet wird, müsstest Du als erstes mal die Rechenregeln erläutern.
Ich bin vor allem am Regelungswerk interessiert, das genutzt wird wenn zwischen den Schichten gebucht wird. Also z.b. von 20:00 bis 03:00 oder ganz fies von 19:00 bis 08:00.
einen Eintrag (kommen bis gehen) pro Mitarbeiter und Tag haben, oder?

**Comment by JujanS** [comment]
Ja also im Büro rechnen wir das so (unsere Firma) ist bei allen so allerdings die Prozente sind anders. 20:00 - 06:00 25 Prozent mehr Gehalt -> Arbeitest du von 18:00 - 05:00 hast du zwei Stunden normalen Stundenlohn und neun Stunden 25 Prozent Zuschlag 

Wichtig zu wissen ist ein höhererzuschlag wie zum Beispiel Sonntags(50%) überschreibt den kleineren Zuschlag sie addieren sich nicht Beispiel: eine personal arbeitet am Sonntag von 22:00 - 05:00 dann erhält sie 2 Stunden 50 Prozent Zuschlag und 5 Stunden 25 Prozent 

Natürlich wäre es vom Vorteil ein kontrollkästchen für Feiertage zu haben welche mit einem Klick aus einem Tag 50% machen - aber das wäre auch erstmal per Hand manuell möglich zu rechnen

**Comment by sdillenburg** [comment]
Factors for weekends and/or sundays as well as public holidays could be added also.

**Comment by kevinpapst** [comment]
duplicate of #309
