### ISSUE TITLE
Log without Activity

### ISSUE THREAD

**Issue by schwantuschke** [kimai/kimai#1715]
My question is like this Issue: https://github.com/kevinpapst/kimai2/issues/1643
It's possible to log time without activity?

**Comment by kevinpapst** [comment]
No.

**Comment by schwantuschke** [comment]
Thanks for this short answer ;)
It's possible to do this in future?

**Comment by kevinpapst** [comment]
You are welcome 😁 
I was thinking of it as well and it might come in the future.

**Comment by schwantuschke** [comment]
Great. Thank you :)

**Comment by HeinzWuert** [comment]
Arrrgh! 
This might be helpful for timerecording "coming" and "going".
Bookings without activity are not wanted (for us).
If so please realize it in a way, that f.e. a defined activity is automatically bound to this function.

**Comment by jonsnow1357** [comment]
yes please :) we don't use activity either, just project.
or maybe something simple to start ... if there's only one activity defined auto-fill it

**Comment by spanstrong** [comment]
I don´t need / want to use activities so I always create project and activity with identical name. I would love the option to log time to project directly.

**Comment by kevinpapst** [comment]
You can achieve that with the [custom content plugin](https://www.kimai.org/store/custom-content-bundle.html). Then:

Create one global activity and grab the ID from the URL, replace `5095` in the code with your new ID:

```javascript
document.addEventListener('show.bs.modal', (e) => {
    const activity = e.srcElement.querySelector('#timesheet_edit_form_activity');
    if (activity !== null) {
        activity.value = '5095'; 
        activity.dispatchEvent(new Event('change'));
        const activityRow = e.srcElement.querySelector('.timesheet_edit_form_row_activity');
        if (activityRow !== null && !activityRow.classList.contains('d-none')) {
            activityRow.classList.add('d-none');
        }
    }
});
```
