### ISSUE TITLE
Wekan activity integration

### ISSUE THREAD

**Issue by haydenseitz** [kimai/kimai#1725]
**Is your feature request related to a problem? Please describe.**
No :)

**Describe the solution you'd like**
[titra](https://github.com/kromitgmbh/titra/), a similar time tracking app, has an [integration with Wekan](https://github.com/kromitgmbh/titra/wiki/Wekan-integration), so that you can select activities from your wekan project board when creating a time entry. A feature like that, or any type of integration with wekan, [would be very much appreciated around the community](https://github.com/wekan/wekan/issues/812). 

**Describe alternatives you've considered**
There are 2 versions of this integration I have imagined:

1. _Project_ is linked to Wekan board, and _Activity_ is linked to cards on the board
2. If using [swimlanes ](https://github.com/wekan/wekan/wiki/Swimlanes) in wekan, allow for an option where: _Customer_ is linked to board, _Project_ is linked to swimlane, and _Activity_ is linked to card on board.

**Additional context**
As described in the wekan integration link above, a board has a full JSON metadata export that should allow API access to the wekan boards to read board/swimlanes/activities.

**Comment by kevinpapst** [comment]
Thanks for posting the idea. 
Lets see if the Wekan team reaches out, or anyone else comments/votes here.

**Comment by kevinpapst** [comment]
not a lot of interest here, closing
