### ISSUE TITLE
Upgrade to FontAwesome 5

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#179]
- [x] Upgrade to FA5, see https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- [x] Change the "invoice" icon from "print" to "invoice", which was added recently: https://fontawesome.com/icons?d=gallery&q=invoice

**Comment by simonschaufi** [comment]
Do you want to use the svg approach or the font file?

**Comment by kevinpapst** [comment]
Haven't read enough about the options. I'd prefer the "easier" and more compatible way.
Any recommendation? Pros and Cons?

**Comment by simonschaufi** [comment]
Looks like they have changed lots of things on their website. I use [this way](https://fontawesome.com/how-to-use/on-the-web/advanced/svg-javascript-core) on one project and you have to specify all icons individually that you want to use. 

Concerning performance: https://fontawesome.com/how-to-use/on-the-web/other-topics/performance

**Comment by kevinpapst** [comment]
Using the "classical" webfoot approach for now
