### ISSUE TITLE
Order tasks alphabetically on invoice

### ISSUE THREAD

**Issue by vissersj** [kimai/kimai#187]
There is a certain order in my project tasks, for instance:

01 Design
02 Build
03 Test
04 Deliver

I would like to have that exact order on my invoice (with sum hours), but at the moment the order is different. My request for change is to order the project tasks on the invoice alphabetically.
  
--
Hi vissersj,

I see that this can be of use. Please go to vissersj https://github.com/kimai/kimai/issues and file a feature request there.

Best Regards,
Severin

**Comment by Devoteq** [comment]
Has there been made any progress on this request, i have the latest kimai version running but the print.php is modified heavily. and i dont have the coding skills to change the order of my invoice's 
I would like them ordered by date (they currently are ordered by date but the wrong way around for me) starting with the highest date and ending with the lowest date

**Comment by kevinpapst** [comment]
The linked pull request will finally fix this issue by adding an select box to choose between:
- order by date - oldest first
- order by date - newest first
- order by name
Once it is merged, you can check it out at our demo page.
