### ISSUE TITLE
Monthly time budgets per project

### ISSUE THREAD

**Issue by saschafoerster** [kimai/kimai#190]
With version 1 it was not possible to define a monthly time budget for a customer, only a general budget for the whole project. For continuous projects like community management, this would be a great feature.

With every project I would like to define a general monthly/weekly/daily or yearly time budget. When the budget is used, a notification via e-mail would be great. 

Alternative till now is to check every project manually at the end of the month.

**Comment by kevinpapst** [comment]
Yes, good idea. A report extension is already planned. But we need cronjobs first and then do some proper planning on the basic code for that. 
Setting up a report like the one you mentioned should be only a config then.
Also dynamic/configurable widgets on the dashboard could be helpful.

**Comment by kevinpapst** [comment]
Time budget was added in master (see #843), but only for customers/projects/activities => not for a certain time range.  You could use a new project or activity each month.

**Comment by saschafoerster** [comment]
Maybe some advanced reporting is a nice paid add-on, which we would most likely pay for because it helps us to keep on overview on the monthly time-budget sizes, which is company-wise really relevant.

**Comment by kevinpapst** [comment]
Closing here, reporting is on the roadmap and mentioned in several tickets
