### ISSUE TITLE
Manual upgrade

### ISSUE THREAD

**Issue by anmol26s** [kimai/kimai#192]
Hi
YunoHost uses a source upgrade instead of the git pull to update. It would be nice if you can explain the manual  steps to upgrade the Kimai2.

**Comment by kevinpapst** [comment]
Hey @anmol26s - is that still an issue?

**Comment by anmol26s** [comment]
In yunohost when we upgrade we unpack the new sources over the previous sources. So the changes to the files are updated, but the files which are no longer required and are deleted in the git are not deleted while updating through Yunohost because there is no way to know that the file is no longer required.

The solution is that we backup the configuration files and user data to some place else, delete the kimai 2 source folder and unpack the new sources, restore the config files and user data and run the commands to update.

So for this it would be nice if you can tell what needs to be backed up before the new sources can be unpacked. I know to backup .env file for the settings of the Kimai 2. Is there any other user data or custom files which Kimai 2 store apart then this?

**Comment by kevinpapst** [comment]
Aha, good to know.
I guess you apply the following order?!
- backup files
- delete old directory
- install new directory
- overwrite everything in new directory with the files from the backup
?!

Then please backup [config/packages/local.yaml](https://github.com/kevinpapst/kimai2/blob/master/var/docs/configurations.md#overwriting-local-configs-localyaml). It may not exist, but users can create it to overwrite application settings.

Your installation uses MySQL by default, right? Otherwise the default SQLite database is located at `var/data/kimai.sqlite`. 
Please note, that in this directory also the test database `kimai_test.sqlite` lives => that one needs to be updated with a new version - so don't backup the complete directory.

In the next milestone I will add an (upload) directory at 'var/invoices/` you can already backup the complete directory if it exists.

**Comment by anmol26s** [comment]
Great, thank for explaining the correct procedure to backup. I am really interested to install the mysql. Con you please explain me how to configure the mysql? Currently the package uses SQLite because of this https://github.com/kevinpapst/kimai2/issues/191#issuecomment-401564733

**Comment by kevinpapst** [comment]
As far as I remember there was one column that used JSON and I replaced it in the meantime with a native text column. 

Can you try to install it manually? Simply edit `.env` and use the setting: 
```
DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name
```
and then call 
```
bin/console doctrine:database:create
bin/console doctrine:schema:create
```

**Comment by kevinpapst** [comment]
Yes, I meant for using MySQL.
I really need to install YunoHost in a VM, so I can support you. Will do that the next days.

**Comment by anmol26s** [comment]
It would be really nice. Once the package gets properly built it would be easy to maintain. 
I am using using sqlight. And I would like to migrate to mysql.
Further while trying update for yunohost I saw there is no folder name /var/data.

**Comment by kevinpapst** [comment]
But the folder is in git: https://github.com/kevinpapst/kimai2/tree/master/var/data
Sorry for the delay, I have a lot of personal stuff going on right now.

Regarding the MySQL switch: that should be fairly for new installations. You just need to change the `DATABASE_URL` in the `.env` file (like so: https://github.com/kevinpapst/kimai2/blob/master/.env.dist#L20).

Do you have default values in YunoHost for database server, user and password? If not, we could create them on the fly. 

But for upgrades that might be more troublesome, as we have to export and import the data - unfortunately I have no time right now to work on that.

Could you try it for new installations and we work on upgrades at a later time?

**Comment by anmol26s** [comment]
I am getting this error now:

 Generating optimized autoload files
43471 DEBUG ocramius/package-versions:  Generating version class...
43472 DEBUG ocramius/package-versions: ...done generating version class
43773 WARNING Executing script cache:clear [KO]
43773 WARNING  [KO]
43773 WARNING Script cache:clear returned with error code 255
43773 WARNING !!
43773 WARNING !!   // Clearing the cache for the prod environment with debug
43774 WARNING !!   // false
43774 WARNING !!
43774 WARNING !!  PHP Fatal error:  Class App\Invoice\DateNumberGenerator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (App\Invoice\NumberGeneratorInterface::getId) in /var/www/kimai2/src/Invoice/DateNumberGenerator.php on line 18
43774 WARNING !!  22:45:42 CRITICAL  [php] Fatal Error: Class App\Invoice\DateNumberGenerator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (App\Invoice\NumberGeneratorInterface::getId) ["exception" => Symfony\Component\Debug\Exception\FatalErrorException { …}] []
43774 WARNING !!
43774 WARNING !!  In DateNumberGenerator.php line 18:
43775 WARNING !!
43775 WARNING !!    Error: Class App\Invoice\DateNumberGenerator contains 1 abstract method and
43775 WARNING !!     must therefore be declared abstract or implement the remaining methods (Ap
43775 WARNING !!    p\Invoice\NumberGeneratorInterface::getId)
43775 WARNING !!
43776 WARNING !!
43776 WARNING !!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
43776 WARNING !!
43776 WARNING !!
43776 WARNING Script @auto-scripts was called via post-install-cmd

**Comment by anmol26s** [comment]
> Do you have default values in YunoHost for database server, user and password? If not, we could create them on the fly.

Yes we have default values created for mysql.



> But for upgrades that might be more troublesome, as we have to export and import the data - unfortunately I have no time right now to work on that.

So for this I will have to make upgrade script in such a way that users who have installed Kimai2 with sqlite do not break there instance and keep them on sqlite. Is import and export implemented for Kimai2  in the web interface?

> Could you try it for new installations and we work on upgrades at a later time?

Installation is working fine with the latest version. But upgrade is failing with above error.

**Comment by kevinpapst** [comment]
The update script should probably not touch the .env file, does it do that by now?
If not, you don't have to care about the database switch, as the user will stay on the currently configured database.

There is no export-import functionality implemented, but something like this could work.
Export the data from sqlite with https://stackoverflow.com/posts/20014210/revisions and then
```
bin/console doctrine:schema:create
bin/console doctrine:database:import exportfile.sql
```

How do you do the update? The file mentioned was removed in git and does not exist any longer. 
I guess I have to setup YunoHost locally (or VM?) to help you with the scripts and to better understand how the process is handled.
I think you mentioned that in the past, but I forgot: do you use git for installation/update?

**Comment by anmol26s** [comment]
Ok I did not removed the  folder while update. So it changed the files and kept the files which were not there in the latest builds.
I will remove the folder then remove the folder and backup all the required files.
Yes you can do yunohost on VM.

**Comment by anmol26s** [comment]
Ok now update is working. There was no /var/invoices folder and  config/packages/local.yaml files while backup.
Moreover when I go to password reset button `https://domain.tld/en/resetting/request ` , I get error.

```
Oops! An error occured.
500: Internal Server Error
An unexpected error occured, please try again. You may have found a bug, so please contact your administrator if the problem doesn't go away after you tried it again. 
```

**Comment by kevinpapst** [comment]
Can you show me the contents of `var/log/prod.log`.
The files you mentioned are optional, but you should check for them during backup. The local.yaml is more for experienced users, but there will be for sure some users who add their own invoice templates.

**Comment by anmol26s** [comment]
Ok I will check if the there are these files before backup I will back it and then restore after the update.

Here is the logs:

```
[2018-10-07 00:47:05] request.INFO: Matched route "fos_user_resetting_request". {"route":"fos_user_resetting_request","route_parameters":{"_route":"fos_user_resetting_request","_controller":"fos_user.resetting.controller:requestAction","_locale":"en"},"request_uri":"https://domain.tld/en/resetting/request?%2Fen%2Fresetting%2Frequest=","method":"GET"} []
[2018-10-07 00:47:05] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"secured_area","authenticators":1} []
[2018-10-07 00:47:05] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2018-10-07 00:47:05] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-10-07 00:47:05] php.INFO: User Deprecated: Referencing controllers with a single colon is deprecated since Symfony 4.1. Use fos_user.resetting.controller::requestAction instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Referencing controllers with a single colon is deprecated since Symfony 4.1. Use fos_user.resetting.controller::requestAction instead. at /var/www/kimai2/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:39)"} []
[2018-10-07 00:47:05] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\EnvNotFoundException: "Environment variable not found: "MAILER_FROM"." at /var/www/kimai2/vendor/symfony/dependency-injection/EnvVarProcessor.php line 77 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\EnvNotFoundException(code: 0): Environment variable not found: \"MAILER_FROM\". at /var/www/kimai2/vendor/symfony/dependency-injection/EnvVarProcessor.php:77)"} []
```

**Comment by kevinpapst** [comment]
See https://github.com/kevinpapst/kimai2/blob/master/UPGRADING.md
You know Kimai2 is not yet stable and things change ;-) so you should check if `.env` contains the string `MAILER_FROM` and if not pipe it into the file with something like `MAILER_FROM=kimai@example.com` (if you have a domain name available during installation use this one instead of example.com).

**Comment by anmol26s** [comment]
Ok thanks now it work. But I can't receive the emails from smtp. We need no authentication and encryption, so what should be `MAILER_URL=` ?

Further what do `DATABASE_PREFIX=kimai2_ `do? It prefix kimai2 before tables or the database?

**Comment by anmol26s** [comment]
And how can registration be closed after fresh install.

**Comment by kevinpapst** [comment]
The prefix is for the tables.

I added some notes at troubleshooting about the MAILER_URL: 
https://github.com/kevinpapst/kimai2/blob/master/var/docs/emails.md#troubleshooting

This could be something more complex like: 
```
MAILER_URL=smtp://username:password@mx.example.com:587?encryption=tls&auth_mode=plain
```
or GMAIL:
```
MAILER_URL=gmail://me@gmail.com:app-password@localhost
```

Good idea, you could offer several options during the installation and then generate the local.yaml file from the selected options.

**Comment by anmol26s** [comment]
@kevinpapst 
Thanks for your help. I have created a branch mysql, which have option to chose database as mysql or sqlite and user registration option to be true or false.

**Comment by anmol26s** [comment]
It would be if you can tell any new options which should be included in while installation.
Currently the upgrade will check about the database, invoices,.env.

**Comment by kevinpapst** [comment]
I will let you know when changes come up.
For now I think the database file, the .env file and the invoices directory are enough as backup.
Lets make it that way: I will create a ticket about every new release in your project with all the required information, as already documented here: https://github.com/kevinpapst/kimai2/blob/master/var/docs/internal.md

Or do you want the information upfront, so the update is ready once I release a new version?

**Comment by anmol26s** [comment]
> Lets make it that way: I will create a ticket about every new release in your project with all the required information, as already documented here: https://github.com/kevinpapst/kimai2/blob/master/var/docs/internal.md

This would be good idea and very helpful.
We can close this for now then.
Thanks
