### ISSUE TITLE
added Modified_Date for TimeSheet

### ISSUE THREAD

**Issue by dodophoenix** [kimai/kimai#194]
Hi there, 

it would be nice if there would be a 'modified date' column on each time-sheet entry. 
The column should be visible for qualified members only. 

So I did some changes that can be found here. 
https://github.com/dodophoenix/kimai/tree/modified_date

Currently the modified column is visible to anyone who is allowed to edit the wage on time-sheet entry

It would be nice if a feature like this could be part of upcoming releases. 
So don't hesitate to contact me if I can help.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
