### ISSUE TITLE
easier creation of tasks

### ISSUE THREAD

**Issue by AyamAsayam** [kimai/kimai#195]
## Description
when you are creating a list of tasks within a Project,  it would be desirable to keep creating tasks for the same project and customer until you are finished with your task list.

## Expected Behavior
 at the end of creation of a single task, add the option of a new (blank) task in the same project/customer 

## Actual Behavior
once finished, the task creation returns you to a whole list of all projects tasks, so you need to define project and customer again. This could be necessary many times, depending on how long is the project's task list. This could be something like a "keep creating same project's tasks" button

**Comment by kevinpapst** [comment]
Good idea, will be included in the current milestone!

**Comment by kevinpapst** [comment]
@AyamAsayam thanks for the suggestion.

I just added  a checkbox "create more" to the forms:
- create user
- create project
- create task

When checked, the creation form is shown again after successful creation and it has pre-selected the "customer" or "project" and the "create more" checkbox
