### ISSUE TITLE
More simple deployment needed - one package

### ISSUE THREAD

**Issue by climb4fun** [kimai/kimai#199]
Hi all,

what was a success factor of Kimai V1?
It's simplicity of deployment. Only PHP and MySQL. This was a reason for me to choose Kimai. I'm really a big fan of Kimai.

Due to constraints on my server, I cannot deploy Symfony; unless the fact I didn't have knowledge to do so.
I'd like to be an early adopter to V2, but due to the new deployment process, I will stay on V1 and hope it will survive as long as possible. It works fine on PHP 7.2.x.

If you have a more simple deployment - just dropping on the server and unzip - then I'll be able to migrated to V2.

Sorry to say that.

But thanks for Kimai V1 - it's a great piece of software.

Best regards
climb4fun

**Comment by kevinpapst** [comment]
Hey @climb4fun!
Thanks for your feedback, I wasn't considering that it might be a problem for someone to install it like its mentioned in the documentation.
I can write some documentation on how to install Kimai if only FTP is available. But thats nothing I would recommend, unless you have no other choice. Its much much faster to install it with Git and composer.
Symfony is only a PHP Framework like Zend which is used is in Kimai 1.
Do you have bash access or only FTP available?

**Comment by climb4fun** [comment]
Hi Kevin,

I only have FTP and it's behind a firewall. In my daily work it means, I can upload a file, unzip and then start a php installer. For sure I can run phpMyAdmin.

Best regards
Klaus (climb4fun)

**Comment by NicklasAndersson** [comment]
It is really common for cheap web hosts to only provide ftp and some preinstalled tools.

**Comment by kevinpapst** [comment]
Basically all you have to do in that case: executing the already documented installation steps on your local machine, then zipping the folder, uploading it and unzipping it on your server (or even uploading all files unpacked). 
That might not be obvious for unexperienced users, so I will write some documentation to make it clearer

**Comment by climb4fun** [comment]
Hi Kevin,

much appreciated.

Regards
Klaus

**Comment by kevinpapst** [comment]
I added instructions for "FTP only" installations: 
https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md

I'd appreciate if one of you could try it out and give me some feedback, as I can't try it out myself. 
There is also a new ticket for a web-based installer, which will simplify this process in the future: #209

**Comment by climb4fun** [comment]
Hi Kevin,
first of all thanks for your accommodation and support.
	* I tried to deploy, but my first obstacle is SQLite. I have only MSQL or MariaDB available.
	* I can't run composer - no exec enabled on my server.
Best
Klaus
Am Do., Jul. 12, 2018 22:39 schrieb Kevin Papst : I added instructions for "FTP only" installations:
https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md (https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md)
 I'd appreciate if one of you could try it out and give me some feedback, as I can't try it out myself.
 There is also a new ticket for a web-based installer, which will simplify this process in the future: #209 (https://github.com/kevinpapst/kimai2/issues/209)

**Comment by goddib** [comment]
Hi all, just to let you know - I've also tried to install locally then upload with no success so I'm no reverting to Kimai v1. The limitation on my end is that I do not have shell access to the server. A web-based installer would thus be necessary to enable me to use Kimai v2.

Thanks for all the hard work!

**Comment by kevinpapst** [comment]
Please see this issue #642 which adds a FTP package. 
There is a package for the upcoming version 0.9 linked which can be used for FTP installation.
I need feedback from FTP users, as I cannot test it properly.

**Comment by DerDanilo** [comment]
The FTP Package is fine as long it would contain a default DB file that could be imported. A web-based installer would be best of course. Setting Kimai up on a dedicated VM is overkill, so having a web based installer to do the basics would be best. Then users could just use whatever backend they need.

Thanks!

**Comment by ateliernz** [comment]
A managed to install it on my synology nas, however i wouldn't recommend it. I am not experienced to do so. I don't fully understand Symphony or GIT etc. and just follow the installation instructions. learning by doing :P 

I would be happy to test a webbased installer :)

**Comment by limitedAtonement** [comment]
I think this can be closed. FTP installation instructions are here: https://www.kimai.org/documentation/ftp.html and there are docker images available for very quick installation.

**Comment by kevinpapst** [comment]
Closing, as an FTP / Web installer was never in the scope of Kimai and no one ever wanted to contribute or sponsor one.
