### ISSUE TITLE
Tasks for different projects/customers (global activities)

### ISSUE THREAD

**Issue by plauzenbaer** [kimai/kimai#200]
**Tasks are only for one project and one customer**

excuse if i`m wrong with my perception of tasks in general.

i`ve just finished installing my own demo of v2 
i preparded some customers, some projects and some tasks

what i found out was that it`s not possible (or i didn`t saw it ) that
one task couldn`t be used for different projects of different customers...

why ?
for example: usually you drive to and from a customer. if this time
is important than you have "Anfahrt" and "Abfahrt" as separate tasks.
this could be used for different projects, right ?

so actually i can`t assign tasks to more than one project .

help for my understanding is greatly appreciated.

**Comment by kevinpapst** [comment]
Yes, you are right. There is currently no concept for "global tasks" as I consider it a "broken" feature.
What if you have tasks that have the same name, but different rates for different customers (which is fairly normal)? Yes it was possible in Kimai v1, but it led to several problems, so I decided to go a different way with v2.

But I see the hassle in managing the same tasks for every project, so I would propose improvements in the Admin UI:
- Batch creation for new tasks: you can select the projects which will get the new tasks
- When creating a new project, you can select tasks which will be created automatically

I'd like to start a discussion and hear all positions, as everyone uses Kimai in a different way.

**Comment by plauzenbaer** [comment]
sounds good to me. Usually you have a lot of tasks which could be part of a "standard set" of tasks like
"Anfahrt" and "Abfahrt" and "Telefonieren" and "Programmieren" etc. pp
then the admin user chooses from the standard set and has it availably. so effective and timesaving
at least 30 - 60 Minutes ;-)

**Comment by globaljetservices** [comment]
We are a small business and have been using Kimai for years and wanted to say thank you to everyone who has worked so hard on this software.  The new version is radically different, and we see a lot of great benefits.   I would agree with your thoughts on batch creation.  In our environment we have around 200 projects and most of the projects have around 20 tasks/activities.  Those tasks/activities are the same for the 200 projects we have.  Sometimes we need to add a new task/activity and add it to each project in our company.  How would that work in V2?

**Comment by kevinpapst** [comment]
Don't know yet @globaljetservices , but I will take this into account, thanks for the info!

**Comment by DanSman** [comment]
I just installed it on arch arm. It's really great to see this big change. Especially for the mobile devices. 

It would be great to get this feature back. I'm using it for a painting job and every "first coat" , "sec coat" etc needs to be added on every project again. 

I didn't use "selecting activities" in kimai1 for any of my projects. I only "tick" the activity what I'm actually wanna do and pushed the time/play button.  

Just for my needs it would be to much work to do this on every project .

But so far ... it's looking really good and very user friendly.

**Comment by kwade00** [comment]
Other software I've used works similarly to @plauzenbaer's experience. A master list of tasks which can be selected for each project. Some can even be selected to automatically add to every new project. I haven't looked at Kimai's structure, but these seem to have a Task table and a LinkedTask table, for example. The LinkedTask table would just be a many-to-many with taskid, projectid, and rate columns. The rate column is to override the standard rate in the master Task table. If that's to drastic a change then copying from a master task table to the project on project creation would certainly be better than creating all tasks for each project one at a time.

**Comment by Kurgan-** [comment]
I strongly back the request for global tasks. I use only 4 tasks (globally) in my current Kimai installation, and having to enter tasks again and again for every customer and for every activity would be painful.

**Comment by kevinpapst** [comment]
Already working on it, so: Feature request accepted.
But that will take some time, its rather complicated to manage project specific and global activities.

**Comment by srdco** [comment]
+1 for this feature. It is (almost) critical for our use case. We have a set of tasks that are almost identical for every project (patent application). Creating new ones for each project (about a dozen or so tasks), while not impossible, does complicate the UI, and especially introduces a lot of problems with consistency for reporting, etc.

Maybe a global "activity template" type of idea would work? That way the individual activities could be linked back to the master activity template for reporting, creation, etc, but still could retain individual properties (like billing rate, etc).
So, for example, you would have a Master Activity Template for "Application Drafting," and then everytime you create a new project ("John Smith's Application No. 2"), you could create an activity for that project, by simply selecting a checkbox or dropdown or something that uses the Application Drafting master activity template.
