### ISSUE TITLE
Provide different ways of rounding

### ISSUE THREAD

**Issue by ServiusHack** [kimai/kimai#202]
This is a result of #89.

We need to offer several extendable ways to perform rounding of timesheet entries in Kimai. This can be solved by having several classes implementing rounding from which admins can choose one.

It could also be considered that there are several stages of rounding:
* Round when tracking via buzzer
* Round when adding manually
* Round when exporting
* Round when invoicing
* maybe more?

**Comment by kevinpapst** [comment]
We already have issues with the rounding option, those should be fixed first.
No votes, closing for now.
