### ISSUE TITLE
Make extensions more independent from the core

### ISSUE THREAD

**Issue by ServiusHack** [kimai/kimai#203]
At the moment we have a tight coupling between the core functionality and extensions. There are even intersections between extensions (export and expenses extension).

We should achieve the following:
- Each extension (maybe with the extension of admin and timesheet) can be completely removed from the installation.
- Each extension can later be installed and uninstalled as well as enabled/disabled for several groups.
- Each extension can detect and interact with other extensions or gracefully fall back if they don't exist.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
