### ISSUE TITLE
Feature request - Monthly overview / report

### ISSUE THREAD

**Issue by eporsche** [kimai/kimai#207]
## Description 
Instead of a list of all time records, it would be nice to see the full month. And for which days a time recording has been created. That way an employee could easily see for which days a time record might be missing. Also national holidays and weekends could be added to this view. 
With this information added to the monthly overview an employee can see how much hours he has worked this month and how much hours he has still to work. Holidays and weekends would then be taken into consideration.

## Expected Behavior
* Monthly overview (calendar view)
* Ability to enter planned working time per employee (not per project)
   * time calculation model: monthly, yearly, accumulated
   * support for full time (planned working time 100% per week) / half time employees (planned working time 50% per week)  or pay per hour workers (0% planned per week)
* Ability to enter holiday budget per employee
* Ability to calculate overtime
* Ability to enter times absent due to overtime
* Ability to enter absence due to illness
* Ability to enter absence due to holiday
* Holidays and weekends highlighted 
* PDF Download for monthly report
* Disable past month time recording for accounting

## Actual Behavior
* list of all time records per employee

**Comment by kevinpapst** [comment]
these are a lot if ideas on one topic, but i like them! its already planned to work in the reporting features, so i move this ticket to the next milestone. i'll come back for discussion in a few weeks.

**Comment by hmr-it-jr** [comment]
+1 for these:
- Ability to enter holiday budget per employee
- Ability to calculate overtime
- Ability to enter times absent due to overtime
- Ability to enter absence due to illness
- Ability to enter absence due to holiday

We "solved" this in Kaimai 1 with creating a customer "loss of working hours" and different projects like "illnes", "holidays", ... and an activity "not in office".

**Comment by kevinpapst** [comment]
Guys, I started to work on the calendar view, please see #236 (there is a screenshot attached).
Please note that this Feature request is basically 10 in one, so this is impossible to add in "one session".

I will treat this PR as the basic calendar functionality including display of public holidays. If that is done, I will close this PR. All your other ideas (which are great 👍 and shouldn't get lost!) need to be rewritten in single feature requests (so people can vote). 

Please take some time and write them one by one and then we can prioritize these features and plan them for the next milestones.

**Comment by mr-jingles** [comment]
The calendar view looks great. I installed you pull request locally.

On my wish-list would be the following  
- a click in a free area on the calendar opens the "add new time page" in  a modal window - I don't think that more fields are required here
- click on a existing entry opens the modal window to edit the time
- I also like the list option of the fullcalendar.io module - compared to the current implementation it highlights days as subheadings in new rows. If this gets merged to the current list view it can help the user who prefers the list view to spot missing time entries and it would group multiple entries of one day nicely. 

Regarding the display of national holidays - I like: http://jollyday.sourceforge.net/ 
The package is used for Java but maybe the implementation on how they structure holidays in simple xml files can also be used here.
 
I will add the other requests subsequently as you suggested as new and separate user stories.

Thanks for your effort!

**Comment by kevinpapst** [comment]
@mr-jingles I just pushed further changes, you could update and give it a try (I am not sure about the hover effect, especially as hover effects are not supported on mobile)

I tried using a modal, but it doesn't work properly and its too much effort for the first implementation. Maybe later, for now create feature requests and let people vote for it.

Regarding the calendar: I will definitely use GCal, as this enables the user to embed a feed which could be enhanced with further entries e.g. like company holidays and events (think bbq and xmas party).

**Comment by mr-jingles** [comment]
@kevinpapst  - maybe one litte obstacle here regarding the holidays:

If lets say - I have multiple employees working in different parts of the country they might have different national holidays. It should be possible to assign the country but also the state to an employee. To the state a gcal feed with national holidays can be assigned. As for bbq or xmas events I would rather assign a second gcal for the company.

**Comment by sideeffect42** [comment]
Oftentimes contracts are written with a specific amount of hours/week or hours/year that an employee needs to work.

From an employees point of view it would be great if the dashboard could be extended to now only show "working hours this month" and "working hours total", but more importantly also "working hours today", "working hours this week", and potentially "working hours this year".

**Comment by kevinpapst** [comment]
@sideeffect42 Do not comment on closed PRs, simply open new ones.
I cannot handle these mixed feature requests with dozens of ideas in one thread.

**Comment by kevinpapst** [comment]
Widgets and their time ranges are now configurable: see #269
Also some more widgets were added and pre-defined.
