### ISSUE TITLE
kimai-mobile - Beschreibung hinzufügen

### ISSUE THREAD

**Issue by stahredv** [kimai/kimai#208]
In der Mobile Version fehlt noch die Möglichkeit eine Beschreibung hinzuzufügen. Ich denke diese Funktion ist für den praktischen Einsatz sehr wichtig (um z.B. zu notieren was man gemacht hat).

**Comment by simonschaufi** [comment]
moved over to https://github.com/kimai/kimai-mobile/issues/12
