### ISSUE TITLE
Add installable package

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#209]
As Kimai will be used by many non-technical people the installation process should be simplified.

See #199 

## Idea 1
We could add a web-installer bundle that allows to perform the required steps via browser:
- create `.env` file and configure env and database 
- create first user(s)

## Idea 2
This way Kimai 2 would work out-of-the-box without any adjustments required.:
- create a script to build a pre-packaged Kimai 2 (composer, .env for prod & sqlite, create empty sqlite db)
- adding the "register user" functionality (first user should get role SUPER_ADMIN)

**Comment by hmr-it-jr** [comment]
I vote for Idea 1. I thinks it's very common to have a wizard where you set-up everything like database, email, etc. and then after sucessfully finishing the wizard you can use the software.

**Comment by JBSwin** [comment]
I, too, vote for Idea 1.  The install scripts and web front-end would make implementation more accessible to users who aren't as familiar with some of the backend setup.  I consider myself relatively experienced with linux, but the setup instructions leave a few unknowns that cause the system to not function.  I'm on my third attempt now, following the instructions given, and still have not been able to see the application load.

At least the web-installer would ensure your server, PHP, and DB are all functioning and CAN open the app.  Right now, I have no idea where I'm failing or what I've possibly misconfigured.

**Comment by kevinpapst** [comment]
Please open a new issue for that cause @JBSwin

**Comment by kevinpapst** [comment]
Closing in favor of #199

**Comment by SchreinerK** [comment]
Without an easy to use web installer like in v1, the current v2 is not useable :(

**Comment by kevinpapst** [comment]
@SchreinerK not completely true ;-) but I get your point. 
Please vote on #199, as this is one of the duplicate issues.
BTW - nice to hear from you after some years ... it was SolarWorld, right?
