### ISSUE TITLE
Add "Split" option to DropDownMenu in "My times" window

### ISSUE THREAD

**Issue by mweissdigchg** [kimai/kimai#2122]
**Is your feature request related to a problem? Please describe.**
When people "clock in" in the morning, and "clock out" in the afternoon, there should be a possibillity to split up the single entry into multiple entries and assign them to different customers/projects/tasks afterwards

**Describe the solution you'd like**
1. In "My times" window, go to the entry you'd like to split
2. Press the corresponding DropDown button on the right
3. Select "Split"
4. Dialog pops up to select:
    Time to split at
    or
   Percentage to split (e.g. when applying 50% on a block with 1:00h, two blocks with 0:30h are created)
5. Press Button Apply
6. Instead of one entry you now have two entries where the first starts at and the following ends at the specified time

**Describe alternatives you've considered**
If Timetracking mode [Default] is set:
Add additional entries manually and modifiy the exisiting one

If Timetracking mode [Time-clock] is set:
not possible

**Screenshot**
![Screenshot 2020-11-12 132145](https://user-images.githubusercontent.com/74358275/98942623-95dc6f00-24ee-11eb-87bf-f8cdb3340c34.png)

**Comment by kevinpapst** [comment]
Two upvotes 👍  in 2.5 years is not enough interest, closing.
