### ISSUE TITLE
Automatic time addon on clock in

### ISSUE THREAD

**Issue by wolftone1916** [kimai/kimai#215]
**Is your feature request related to a problem? Please describe.**
No problem at all

**Describe the solution you'd like**
We use this right now so our Brand Ambassadors in the field can clock in via their mobile device. We pay them an hour of drive time on top of the time that they are clocked in and it would be awesome to have it so that an admin could set it to automatically add on a particular amount of time to a users clock in. So say user1 clocks in, they clock out after 3 hours, the system (per the admin setting of add on extra time on clock in) would add an hour to that time or even show in another column of the time that's set to be added and have that sitting before the total time sum. 

**Describe alternatives you've considered**
I looked through the program and didn't see anything to do this already outside of toying with the coding myself

**Additional context**
I feel this could be useful for more than this case as some companies or users could set it for contract style work so the user clocks in and require a minimum of {X} amount of time and then hours worked or say a particular project is difficult, an admin could use an auto addon of time as a bonus for working on that particular project.

**Comment by kevinpapst** [comment]
Have look at that configuration, sounds as if that could be of help:
https://github.com/kevinpapst/kimai2/blob/master/var/docs/configurations.md#rounding-of-begin-end-and-duration-for-timesheet-records

**Comment by kevinpapst** [comment]
No feedback from any other user. No plans to add something like this in the core. Closing
