### ISSUE TITLE
Feature request - Make "Rate" hideable

### ISSUE THREAD

**Issue by j0hannesr0th** [kimai/kimai#217]
**Is your feature request related to a problem? Please describe.**
At the moment it is not possible to hide the rate for specific groups and users.

**Describe the solution you'd like**
Make the rate hideable for specific groups and users. (see attached screenshot)

**Describe alternatives you've considered**
If it's too much effort to hide the whole column I'm fine with replacing the actual rate with "-" for specified groups and users.

**Additional context**
If you are the owner of a company with a few employees you might want that employees don't see the amount of money you get for their work. A solution for this is just to hide the rate in the dashboard for defined groups and users. A checkbox "show rate in dashboard" would be the simpliest solution.

<a href="https://ibb.co/nw24j8"><img src="https://preview.ibb.co/iLz6xT/rate.png" alt="rate" border="0"></a>

**Comment by kevinpapst** [comment]
That will require ACL support, which is not yet in Kimai v2 but it will be added in the future.
I have already some ideas in my head, I need to write them down for the Milestone where this will be included.
Thanks for the idea! I know that this column is difficult for companies, so I will check if I get a hack inside for the meantime until the correct solution is implemented.

**Comment by kevinpapst** [comment]
I am currently working on the configurable permission system and could need some help with testing and feedback to see if the solution fits your needs.

You can configure to:
- de-/activate to view rates for own user
- de-/activate to edit rates for own user
- de-/activate to view rates for other user
- de-/activate to edit rates for other user

The most important part is here:
https://github.com/kevinpapst/kimai2/pull/424/files#diff-a4c4c3e459663533af7607848e15e457R56
and here is the docu:
https://github.com/kevinpapst/kimai2/pull/424/files#diff-627f9e7618137a3b4d52c91d3d8b4970

**Comment by kevinpapst** [comment]
I would appreciate your feedback on this one. If you don't have the time, could you let me know?
I will merge it by the end of the week and cannot promise further work on this topic in the next months.

**Comment by hmr-it-jr** [comment]
Sorry for the late response. I'll test it tomorrow morning and will write you!

**Comment by kevinpapst** [comment]
Thanks!

**Comment by hmr-it-jr** [comment]
Works like a charm! - Normal users don't see the rate, but I've discovered that normal users can switch their role from normal user to system-admin.

I couldn't find an open issue for this so I've opened issue #440

**Comment by kevinpapst** [comment]
After fixing the wrong permission assignment for regular user #440, do you think this is ready for a first version?

**Comment by hmr-it-jr** [comment]
I've tested it again and now it looks ready to be released!

**Comment by kevinpapst** [comment]
Cool, will do so soon. Thanks for testing 👍
