### ISSUE TITLE
Feature request - show user how long he still has to work

### ISSUE THREAD

**Issue by j0hannesr0th** [kimai/kimai#218]
**Is your feature request related to a problem? Please describe.**
At the moment it's not possible for the user to see with a look how long he still has to work today.

**Describe the solution you'd like**
Make a default system wide working time - for exmaple 8 hours - and a per user setting for this. If a time is set at the user use this - otherwise use the default system wide time.
If a user is recording a project make a live counter which counts down the defined hours. If he stops recording a project stop the "hours to go home counter", too. If he later starts again recording for a different or same project count down the "hours to go home counter" at the last point you stopped it.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
The icon I used is fa-home (https://fontawesome.com/icons/home?style=solid).
<a href="https://ibb.co/k74j1o"><img src="https://preview.ibb.co/gc02nT/Unbenannt.png" alt="Unbenannt" border="0"></a>

**Comment by kevinpapst** [comment]
Kimai is primarily a project time tracking solution. It might be extended to care about employee work time tracking in the future, but for now it isn't. Therefor all ideas in this topic area will be closed.
