### ISSUE TITLE
Feature Request - Excel Output of times

### ISSUE THREAD

**Issue by Richigeht** [kimai/kimai#221]
Hello!
It would be great if - like in Kimai V1 - there would be a easy way of doing an Excel export!

The reason for this is that using those Excels it is then possible to import them into other systems - like I am doing it with an Access DB - which then allows me to easily build reports from the times.

Thanks.

**Comment by kevinpapst** [comment]
Thanks for your feedback @Richigeht !
This is a must-have for me as well and it will definitely be added.
I added the ticket to the milestone 0.5 when I work on invoices and export.

**Comment by kevinpapst** [comment]
Hi @Richigeht ,
I am currently working on a major invoice refactoring, including a CSV export.
I would appreciate if you could test it and give me some feedback.
Here is the pull request: #306

**Comment by Richigeht** [comment]
Hi @kevinpapst 
Thanks for the update. Is this also live on the demo website you have? 
That would make it most likely easier for me to test, if not I will just setup a second kimai instance somewhere and try to find some times for testing.

**Comment by kevinpapst** [comment]
Unfortunately not, the demo website takes master, so this is not available.
But a second installation, using SQLite takes ~ 3 minutes ;-) see
https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md#development-installation

**Comment by Richigeht** [comment]
I will try to find some time for testing. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by Richigeht** [comment]
Well seems like it takes longer - half through the setup since the server didn’t have the proper php versions and dependencies. 
I hope the next days I can wrap it up and start testing. 

BTW you are really sky diving as a hobby? That’s quite cool! 


Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by kevinpapst** [comment]
Ok, in that case my 3 min. estimation might have been wrong ;-)

Yep, I sometimes need a break from the computer, so this is another hobby besides the software development: https://www.sky-junkies.de 

I'd appreciate some feedback, as I don't have Microsoft Office for proper testing. Seems to work with Open Office, but the original Excel is still something different.
