### ISSUE TITLE
Add the possibility to add which user has done the job on invoices

### ISSUE THREAD

**Issue by bdrayer** [kimai/kimai#222]
There is actually no way to get the username on the invoice system for Kimai 1 and has I have seen, there is also no way to get it on Kimai 2.

Such information can be useful when you send the invoice to the client with 2 different people working at the same time.

And just for my understanding, you stop to use the possibility to use OpenOffice templates like before ? I find this possibility really amazing.

**Comment by kevinpapst** [comment]
Hey @bdrayer ,
thanks for the feedback!

Regarding OpenOffice: I didn't drop the support, it was not yet added ... but its on the roadmap. Thats an important feature. Please create a new ticket for it and I add it to the milestone as reference.

The username is available both in Kimai 1 and 2, here is a link for v2 that works for right now (it won't after the demo is reinstalled):
https://demo-v2.kimai.org/en/invoice/?template=2&user=6&begin=2018-07-01&end=2018-07-31&customer=1&project=
This example displays the username only in the top (so one invoice per user). Your use case is different, so you should either create your own invoice template or describe the use-case in more detail.

**Comment by bdrayer** [comment]
HI @kevinpapst ,

Great for OpenOffice, I will create a feature request.

Regarding the username, how to get it in a row on Kimai 1 (and 2) ? I didn't find this information in existing templates and on documentation.

**Comment by kevinpapst** [comment]
For Kimai 1 please ask in the issue tracker there, for Kimai v1, it would be something like:
```
{% import "macros/widgets.html.twig" as widgets %}
```
at the beginning of the template and then for each row (somewhere near https://github.com/kevinpapst/kimai2/blob/master/templates/invoice/renderer/print.html.twig#L64):
```
{{ widgets.username(entry.user) }}
```
