### ISSUE TITLE
Add support for OpenOffice templates

### ISSUE THREAD

**Issue by bdrayer** [kimai/kimai#223]
As asked on Issue #222 I create an Issue regarding the possibility to use OpenOffice templates for Invoices as on Kemai 1.

**Comment by kevinpapst** [comment]
Hi @bdrayer  !
I am currently working on a major invoice refactoring, including a Docx export (which OpenOffice also supports).
I would appreciate if you could test it and give me some feedback.
Here is the pull request: #306
