### ISSUE TITLE
API doenst let me specify a duration at Timesheet creation

### ISSUE THREAD

**Issue by sinister-labs** [kimai/kimai#2241]
**Describe the bug**
I try to create a timesheet through post request. The documentations say i can put a "duration" field in JSON Body but everything i get back is. 

```
{
    "code": 400,
    "message": "Validation Failed",
    "errors": {
        "errors": [
            "This form should not contain extra fields."
        ],
        "children": {
            "project": {},
            "activity": {},
            "description": {},
            "tags": {},
            "user": {},
            "exported": {}
        }
    }
}
```

**To Reproduce**
1. Send POST Request to /api/timesheets
2. Set body to: ```{
    "duration": 1800,
    "project": 30,
    "activity": 2,
    "description": "Test"
}  ```

**Additional context**
 - Kimai version: 1.12 stable (Ayumi)
 - Device: Macbook Pro 16"
 - Browser Postman

**Comment by kevinpapst** [comment]
Thats a bug in the API documentation. Please use `begin` and `end` field.

**Comment by Sinister-lab** [comment]
I found out that it's related to the time-tracking mode. 
I changed it to default, now the begin and end field works.

Thanks for your reply

**Comment by kevinpapst** [comment]
Yes, but still [a bug here](https://github.com/kevinpapst/kimai2/blob/master/src/Form/TimesheetEditForm.php#L120) ^^ so I'll reopen to keep track of it.

**Comment by jerosa** [comment]
Hi, I have encountered the same problem when changing the Kimai mode to [Time Clock]. 

The idea is to restrict users so that they can only start and stop timesheets and in the creation they cannot add an end date. However via API admins will be able to create those timesheets with start and end date as in default mode.

Is this possible?

**Comment by kevinpapst** [comment]
@jerosa unrelated to the original issue. Therefor just a very quick answer: no. Either you allow to set start and end or you don't. Users can use the API the same way an admin can. Therefor the is no such mix mode available. Could be create though rather easily: https://github.com/kevinpapst/kimai2/blob/master/src/Timesheet/TrackingMode/PunchInOutMode.php#L37

You could even change the file in your installation, which I wouldn't recommend, just for the sake of testing...

**Comment by jerosa** [comment]
Thought it was an API bug when changing the mode or I would have created a separate issue, sorry about that. 

I have tried to modify the code you suggested (in development) and it works.  Would it be possible to modify these options by configuration or create a new mode of operation allowing the change via API only for administrators? 
Thanks for the quick answer.

**Comment by kevinpapst** [comment]
> Would it be possible to modify these options by configuration 

No

> or create a new mode of operation allowing the change via API only for administrators?

With a larger effort: yes. You would have to change all places where this methods is implemented/used.

**Comment by Maiiwen** [comment]
> Thought it was an API bug when changing the mode or I would have created a separate issue, sorry about that.
> 
> I have tried to modify the code you suggested (in development) and it works. Would it be possible to modify these options by configuration or create a new mode of operation allowing the change via API only for administrators? Thanks for the quick answer.

Hello !

I am currently facing this issue, modifying the return value of canUpdateTimesWithAPI function to true made it work perfectly (at least it seams)

It would be very useful to add the canUpdateTimesWithAPI parameter to the time tracking configuration options instead of forcing the modification of this parameter in the code

**Comment by kevinpapst** [comment]
The code would have to check for the current user and verify if that user is an admin or has a permission like edit_other_timesheet.

**Comment by Pax-0** [comment]
I'm running into the same issues, where I need to allow "super-admins" to be able to specify fields like `begin` and `end` independent of the global setting for regular users.

if anyone has any pointers on how to achieve that I would appreciate it

**Comment by kevinpapst** [comment]
Next release will ship a change, see #5134.  
Users with `view_other_timesheet` can use the team UI where end-time and begin-time fields are available always.
So we can make the fields available via API as well.

**Comment by Pax-0** [comment]
Thank you so much for the quick response, cant wait test this out.
