### ISSUE TITLE
Verifying email configuration

### ISSUE THREAD

**Issue by isolin** [kimai/kimai#226]
I managed to create an LXD image for Ubuntu Minimal Server for kimai2. Everythink seems to be running well, except for sending emails.

I installed and configured the basic `mailservices` package and set up `postfix` with default values (following [How to Install and Configure Postfix as a Send-Only SMTP Server](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-16-04)). I set the recommended value for SMTP in `.env`.

Would please be possible to:
* Include a verification script that sends a dummy email, to find out whether the settings are fine?
* Explain in the installation instruction when to expect emails being sent? E.g. when I create a user, does she/he get an email notification?

**Comment by kevinpapst** [comment]
Hi @isolin ,
Kimai2 is not yet sending out any emails.
If you want to test emails, check the branch in this PR: https://github.com/kevinpapst/kimai2/pull/216

It includes user registration and password reset. Later one does sent emails by default, the first one can be reconfigured to sent emails as well.

**Comment by isolin** [comment]
Thanks for the tip, so there is nothing is should worry about and I will check once the functionality is in the master :)

**Comment by kevinpapst** [comment]
I merged it today, so it is in master (next release will follow in around a week).

You have to adjust two things:

- there is a new `MAILER_FORM` env setting in https://github.com/kevinpapst/kimai2/blob/master/.env.dist#L7
- you need to configure the `MAILER_URL`env setting to work at https://github.com/kevinpapst/kimai2/blob/master/.env.dist#L28

Currently you should receive an email for the "password forgotten" feature that is accessible from the login form.

You can also activate the "user approval" by setting this value to true: https://github.com/kevinpapst/kimai2/blob/master/config/packages/fos_user.yaml#L10
Then you should receive an email when registering a new user from the login form.

**Comment by kevinpapst** [comment]
I added some docs about email at https://github.com/kevinpapst/kimai2/blob/master/var/docs/emails.md

If you have further questions, you can re-open the issue.
