### ISSUE TITLE
Issue related to Kimai1 you must avoid for Kimai2

### ISSUE THREAD

**Issue by xaro1** [kimai/kimai#232]
I using Kimai1 since approx. 2012. Actually, Kimai1 became simply unusable because of slow SQL queries. We need to wait 20 to 40 sec. for UI get updated after starting/stopping a task or changing view (by example, when changing date range) It's unmanageable...

Our MariaDB server consume almost 100% CPU time (on 8 cores Xeon) for executing queries from get_timeSheet, get_time_users, get_time_customers, get_time_projects, get_time_activities... All queries with lot of calculation (minus, division, etc.)

FYI, timeSheet table is around 62000 records and projects around 2500.

I would like to migrate to Kimai2. Is lot of optimization are already done on that point ?

**Comment by kevinpapst** [comment]
Why not simply giving it a try?

Install it for [development usage](https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md#development-installation) and then change these lines: 
- https://github.com/kevinpapst/kimai2/blob/master/src/DataFixtures/TimesheetFixtures.php#L31
- https://github.com/kevinpapst/kimai2/blob/master/src/DataFixtures/TimesheetFixtures.php#L211
With these lines you can change the amount of generated test data that will be loaded when you execute 
```
bin/console kimai:reset-dev
```
Then you can quickly find out what happens.

Or you simply try to [import the data](https://github.com/kevinpapst/kimai2/blob/master/var/docs/migration_v1.md) and see what happens.

I didn't test it with such an amount of data and there might/will be places where its gets unusable. For example there are select boxes which hold the projects - those need to be adapted for sure.

But I'd be glad if you could test it and sent in Feature requests to optimize the UI and if necessary the DB queries as well.

**Comment by xaro1** [comment]
Ok, I will try and give you a feedback soon.

You're right for select boxes. Also, I see that quick search fields for customer/projects/activities are gone. damn...

**Comment by kevinpapst** [comment]
There is nothing "gone"!
Kimai 2 is a complete new software and there is room for improvements. Simply post your ideas and feature requests as new issues.

**Comment by kevinpapst** [comment]
I created a test database with:
- 56 users
- 264 customers
- 7911 projects
- 59365 activities
- and roughly 127k timesheet entries

So far it performs quite well (at least much better than what you said about v1).
Yes there are flaws: for example the select box with all projects/activities inside could likely kill mobile browsers - but it doesn't feel "painfully" slow on my machine (which is quite powerful to be honest).
I think that can be improved by using a different lazy-loading approach and remove hidden (expired) projects/activities from these drop-downs. I will work on that in the next month.

I also added some improvements to the fixture loading, as it couldn't handle that amount of data until now. Inserting this amount of data took ~2h.

**Comment by kevinpapst** [comment]
FYI, 20 database calls on the dashboard including calculations + page rendering => around 700ms
<img width="1022" alt="bildschirmfoto 2018-07-24 um 18 32 35" src="https://user-images.githubusercontent.com/533162/43152869-02c72fae-8f70-11e8-83bc-96ce67b6d611.png">

**Comment by xaro1** [comment]
You don't mention if you're using sqlite, mysql or mariadb (local/remote) for this test ?

**Comment by kevinpapst** [comment]
Definitely a local installation, but I can't remember which database engine I used.
But when using MySQL, switching between local or remote shouldn't make any remarkable difference. If so, your network is a problem and not the database/application.
