### ISSUE TITLE
Web Installer Package for near-automated installs from browser

### ISSUE THREAD

**Issue by JBSwin** [kimai/kimai#235]
Consider a web-installer package to automate the deployment of the time-tracking system.

The install scripts and web front-end would make implementation more accessible to users who aren't as familiar with some of the backend setup. I consider myself relatively experienced with linux, but the setup instructions leave a few unknowns and clarity that cause the system to not function. I'm on my third attempt now, following the instructions given, and still have not been able to see the application load.

At least the web-installer would ensure your server, PHP, and DB are all functioning and CAN open the app. Right now, I have no idea where I'm failing or what I've possibly misconfigured.

**Comment by kevinpapst** [comment]
If there is a question, I can't see it. Otherwise this is a duplicate of #209 and #199

**Comment by JBSwin** [comment]
Agreed.  I must have misunderstood when you asked me to open a new issue in #209.  My bad.

**Comment by kevinpapst** [comment]
And I thought the intention of your posting was that you need help with the installation ;-) Double misunderstanding
