### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by infrabyte** [kimai/kimai#237]
## Description
The requested URL /time/public/en was not found on this server.
Apache/2.4.29 (Ubuntu) Server at localhost Port 80

## Actual Behaviour
All installation steps were followed as per https://github.com/kevinpapst/kimai2#installation
If I go to http://localhost/time/public/index.php then I get a login form but all css is broken

## Your Environment
* Version: 2
* Browser Name and version: firefox / opera / chrome
* Operating System and version (desktop or mobile): Linux Mint 19

**Comment by infrabyte** [comment]
It works only if I add in index.php

**Comment by kevinpapst** [comment]
Using in a sub-directory is not a supported setup.

From the docs:

> Kimai needs to be installed in the root directory of a domain or you need to [recompile the frontend assets](
https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md#frontend-dependencies)

> If you want to use a fully-featured web server (like Nginx or Apache) to run Kimai, configure it to point at the public/ directory of the project. For more details, see: http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html

Use the built-in webserver if you run in dev mode: https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md#development-installation

**Comment by fedibelkacem** [comment]
It can be a Duplicate of #255 and I gave an answer there.
