### ISSUE TITLE
Menu buttons not shown on IE 11

### ISSUE THREAD

**Issue by mawa85** [kimai/kimai#238]
On IE 11, the menu Buttons in the upper green bar as well as the filter Buttons and all other Buttons are not visible.

I can't see any Errors in the Debugger.

![26-07-_2018_15-58-14](https://user-images.githubusercontent.com/4971588/43266910-0a69167e-90dc-11e8-8105-662e241663f4.jpg)

**System**:
Windows 7
IE 11

**Comment by kevinpapst** [comment]
Do they work on the demo? https://v2.kimai.org/demo/
Do they work on https://fontawesome.com ?

**Comment by mawa85** [comment]
nope, tested on the demo

They work on https://fontawesome.com

**Comment by kevinpapst** [comment]
I have no Windows and therefor I am not able to test IE 11 myself unfortunately.

And chance that you could help debugging? Does your javascript console complain about anything?
It works on all browsers including mobil devices I tested, so its likely again some IE specific problem. I thought that would be over by 2018...

There are a lot of hints, maybe one of them helps?
https://github.com/FortAwesome/Font-Awesome/issues/8825
https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up
https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#internet-explorer-11-doesnt-show-icons

I will accept PRs to fix this issue, but I can't provide support myself. I know that sounds harsh, but I have no other solution for now: please switch to another browser.

**Comment by mawa85** [comment]
There a no issues in the console.

Related to this :https://github.com/FortAwesome/Font-Awesome/issues/8825#issuecomment-201043264
I found, that my company restricts font download in the policies. It is set as disabled for me.
Strangely fontawesome.com works for me. 

I will try at home over the weekend.

**Comment by cobaltos** [comment]
Hello There,

I will jump in on this, sorry to interrupt by the way.

I tried the mentioned issue but found no error on IE11 as you can see on the screenshot provided, I am thinking about a missing update for IE or some kind of ad blocker blocking remote fonts.

Please provide more information or let us know if you already resolved it so we can find a solution.

Kind regards.

![working_on_ie](https://user-images.githubusercontent.com/41913251/43408907-b2652ede-93df-11e8-909f-f988f5b06d27.PNG)

**Comment by kevinpapst** [comment]
Thanks for the infos @cobaltos ! Good to know that it works in general.
I guess its either related to some plugin or some obscure security setting in IE. The problem here is, that some companies cannot simply update their systems or security guidelines.
@mawa85 was your test from a private or company computer?
I'd still be interested in debugging information to see if we can prevent that somehow.

**Comment by cobaltos** [comment]
I would love to get some debugging info as well. I think a network debug would be also interesting and can be also obtained from IE debugger so if that could be provided it will be very helpful to see if maybe there is any missing or forbidden request. Let's see how this goes.

**Comment by mawa85** [comment]
Hi,
sorry I could not find time to test on my private computer, will do that tonight.
Here are my logs from IE network debugger (Company where font dowload is disabled in policies)
[https___demo-v2.kimai.org_de_timesheet_.txt](https://github.com/kevinpapst/kimai2/files/2249389/https___demo-v2.kimai.org_de_timesheet_.txt)

![01-08-_2018_14-30-26](https://user-images.githubusercontent.com/4971588/43521837-ed613e4e-9586-11e8-91b6-8ad08407a31c.jpg)


regarding fontawesome.com:
sorry I made a mistake last week. Icons on the start page work but these from the font list are also not shown.
https://fontawesome.com/icons?d=gallery&m=free

**Comment by kevinpapst** [comment]
Thanks for the feedback!
Sounds as if that is really not a Kimai bug then. If you would install it internally and add the domain to the allowed hosts policy, these icons should show up. 
I hope you don't suffer to much from these paranoid network-security-restrictions ;-)

I will close this ticket, as it not unsolvable from our side here.
