### ISSUE TITLE
Default rate for new customers

### ISSUE THREAD

**Issue by vic-t** [kimai/kimai#2380]
**Is your feature request related to a problem? Please describe.**
I usually assign a rate at the customer level, I think that's just cleaner and closer to the legal situation where there is a contract with each client that specifies the conditions. The contract usually doesn't allow to just change these conditions unilaterally, so even if my base rate should change, I may not want this to have an immediate effect on all customers. 

Entering a customer specific rate is just a bit tedious in Kimai. You have to create the customer, then open it, then scroll down to the fee section, create a new rate and save it. 

**Describe the solution you'd like**

I would like to be able to set a default rate that will be applied on a customer level each time a new customer is created, without me having to do this manually. For the few times when this default rate doesn't apply, it's not a problem for me to go to the fee section and change it manually. 

Setting a default rate should stay optional, then it won't break the current behavior but offer this added benefit for users who need it. 

**Describe alternatives you've considered**
The way it currently works is generally fine, this feature would just make it a tiny bit easier, and hopefully would be easy enough to implement. 

**Screenshot**
I'd be find with a simple setting in local.yaml but yes, it would be nice to have this somewhere in the super admin settings.

**Comment by mallorymay13** [comment]
When you assign a rate at the customer level, is there a way to add different hourly rate for each customer? I'm only seeing that it has to be done manually each time you log something you've done for the timesheet or it goes to the default rate for the user.

**Comment by kevinpapst** [comment]
Not a lot of interest here, closing
