### ISSUE TITLE
Feature Request - vacation budget per employee

### ISSUE THREAD

**Issue by eporsche** [kimai/kimai#242]
**Is your feature request related to a problem? Please describe.**
If absent times due to holidays are tracked. We also need a yearly budget of vacation per employee.

**Describe the solution you'd like**
Book absent times against yearly vacation budget of employee
Employees are able to download reports of their vacation budget status

**Comment by hmr-it-jr** [comment]
I've released a plugin which does this job: https://www.kimai.org/store/hmr-it-vacation-bundle.html

**Comment by kevinpapst** [comment]
Kimai is primarily a project time tracking solution. It might be extended to care about employee work time tracking in the future, but for now it isn't. Therefor all ideas in this topic area will be closed.

**Comment by kevinpapst** [comment]
There is a new **Working hours, vacation, illness (controlling)** plugin available at: 
https://www.kimai.org/store/controlling.html
