### ISSUE TITLE
Feature request - PDF Download for monthly report

### ISSUE THREAD

**Issue by eporsche** [kimai/kimai#244]
**Is your feature request related to a problem? Please describe.**
It should be possible to download working hour reports based on a given time frame.
In some companies it is quite common to sign off working time sheets on a monthly basis. That way employers get a sense of how much overtime hours employees already accumulated and employees have a document which has legal significance.

**Describe the solution you'd like**
* simple possibility to enter a from and a to date to download a monthly time sheet

**Comment by mr-jingles** [comment]
Hi Kevin,
your PR does fulfill the requirement of a monthly report :). However I would like to reference [Feature Request 240](https://github.com/kevinpapst/kimai2/issues/240) here as the monthly overview becomes really valuable if the monthly hours can be compared to the hours the worker should have spend within the company based on his contract.

**Comment by kevinpapst** [comment]
Thanks for your feedback!

**Comment by mr-jingles** [comment]
Thank you for all the effort you put into this project! :+1:
