### ISSUE TITLE
Adding country to customer properties

### ISSUE THREAD

**Issue by koryba** [kimai/kimai#246]
Currently it is not possible to enter a specific country for a customer.
This is required, when you have customers in different countries

**Comment by kevinpapst** [comment]
Okay, lets assume you have a country attached to a customer. 
What now? Do you want it to appear on invoices? On expenses? 
What is the further usecase?

**Comment by koryba** [comment]
Reason is to have the country on the invoice as well as take different VAT values into account. For this also the so-called VAT-taxnumber (UID) would be great...

**Comment by simonschaufi** [comment]
You should already be able to access the VAT UID: http://www.kimai.org/documentation/developer/invoice-templates.html#open-office-templates

If that doesn't work, the documentation is outdated but I'm sure you can get the information (somehow).

**Comment by simonschaufi** [comment]
done with #734
