### ISSUE TITLE
Spanish Translation Contrib

### ISSUE THREAD

**Issue by cobaltos** [kimai/kimai#248]
**Spanish Translation**

I would like to contrib offering Spanish Neutral translation for the Kimai 2 System. I thought about copying the translations files and translating all files in there under the "target" tags and follow the "filename.locale.xliff" format but I am not sure if that's the right procedure.

Please let me know if you approve the contribution offered and if the process mentioned before is the right one.

**By the way great job!**

**Comment by kevinpapst** [comment]
Hi @cobaltos, 
very nice offer. I'd love to add your contributions!

Yes, please copy each *.en.xliff file and rename it to *.es.xliff.

Then translate ONLY the strings between the target tags, like:
` <target>Oops! Page not found.</target>`

So basically you had everything right in your posting :-)

**Comment by cobaltos** [comment]
Great!
Thanks for the prompt answer; I will work on this to have it ready as soon as possible I will keep you posted once it is done.

Kind regards.

**Comment by kevinpapst** [comment]
You can see a translation PR at #253
When testing your new language files it might be necessary to run `rm -rf var/cache/*`. At least for me the new italian language files were still not loaded after executing `bin/console cache:clear`.

**Comment by kevinpapst** [comment]
There is a lot of documentation available:
https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/

Probably start reading here:
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
