### ISSUE TITLE
Separate Customer / Project / Activity input when logging time

### ISSUE THREAD

**Issue by Kurgan-** [kimai/kimai#250]
As an active user of old Kimai v1, I find it really annoying to log time in  Kimai v2. 

I am used to two different selection boxes, one for customer and for project, and one for activity.

Entering data in steps, where the previous selection populates the next box with only relevant entries,  allows for much shorter lists to select from. If I get a single selection box, the length of the list can become enormous (one entry for every combination of customer/project/activity) and definitely not easy to work with.

I am surely more willing to to click on two (or three) drop-down menus (instead of a single one) to have the benefit of shorter lists to choose from.

Also, I quite always use the keyboard to "jump" to a specific entry, which still works in kimai v2, but since entries are shown all together, there is no proper way to jump to the right entry. You always end up selecting a similar entry for a different customer.

**Comment by kevinpapst** [comment]
👍 directly related to #200 - I will change that when working on global activities

**Comment by Kurgan-** [comment]
Thanks  a lot.

**Comment by kevinpapst** [comment]
Work on global activities is almost finished: now you can either assign an activity to one project (so its only selectable in combination with that customer and project) or you can leave the project empty - in this case the activity can be used in combination with every project.

As this was a major rewrite of some of the core functions, I could use some help. If you are willing to participate: checkout the branch from the PR #259 and give it a try.

This includes a two-step form to select project and activity for timesheet records. You can even narrow it further down by starting with a customer selection for pre-populating the project and activity select.

You could even test the update by creating a copy of your production database and use that for the migration. DON'T test with your production database yet! My tests were successful, but I want to gather some more feedback before I publish it for everyone.
