### ISSUE TITLE
Feature request - API

### ISSUE THREAD

**Issue by bastilimbach** [kimai/kimai#251]
Kimai v2 looks awesome! Congratulation! Really looking forward to the future of v2.

Are there any plans to implement an API to create timesheet entries, manage users etc...?

**Proposed API v1:**
`GET timesheet`: Get timesheet (all records) of user xyz
`POST timesheet`: Create a new record in the timesheet for user xyz
`GET timesheet/recordID`: Get record xyz of user xyz
`PUT timesheet/recordID`: Update record in the timesheet for user xyz
`DELETE timesheet/recordID`: Delete record in the timesheet for user xyz

**API v2:**
`GET users`: Get all users
`POST users`: Create a new users
`GET users/userID`: Get user with id xyz
`PUT users/userID`: Update user with id xyz
`DELETE users/userID`: Delete user with id xyz

`CRUD` operations for projects
`CRUD` operations for customers
`CRUD` operations for activities

**API v3:**
Invoice management: API to create invoices.

**Comment by kevinpapst** [comment]
Yes, plans are there but so much other stuff to do as well first ;-)
But its good that we now have it as official Feature request.

**Comment by kevinpapst** [comment]
Actually I had to start on working on a basic API while working on global activities. 
This API will be read-only for now, but you are welcome to have a look and add your ideas!

**Comment by bastilimbach** [comment]
Would love to contribute! I just need to read myself into Symphony 4.

**Comment by kevinpapst** [comment]
Great! I try to push all the changes required for the basic setup today/tomorrow.

**Comment by kevinpapst** [comment]
You know that the first basic API is in place? It supports reading only, but its there.

**Comment by kevinpapst** [comment]
Could you please open new PRs for every endpoint you need.
Probably really when you need it and not in advance.
Otherwise this one issue is a bulk for ten new features and will never be closed.
I will close this ticket as a basic read API + [documentation](https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers_api.md) is in place now.

Thanks for supporting Kimai @bastilimbach 👍

**Comment by bastilimbach** [comment]
@kevinpapst I'm already testing the current read-only API. To be honest with you, I didn't think that you would be so fast at implementing this. 👍

As soon as I implement the read-only API inside [Timeu](https://github.com/bastilimbach/timeu), I try to add the basic "Create Entry" API as a PR.

**Comment by kevinpapst** [comment]
I think an App would really push Kimai 2 forward - so I will help you as good and fast as I can:
Don't be shy, open as many new PRs as you like! 

Just let me know if you need any filter/search/endpoint ... in the API, its a bit hard to build it without a real-usecase ;-)
