### ISSUE TITLE
Preselect Activity - configurable default activity for projects

### ISSUE THREAD

**Issue by christian-lo** [kimai/kimai#2538]
**Is your feature request related to a problem? Please describe.**
I've got some (simple) projects where I always track one single activity. The reason is sometimes just the detailed way I split up my projects as well as some projects (e.g. documentation) nearly all recordings make use of activity documentation. 

**Describe the solution you'd like**
Add an additional select field "Activity" underneath "Customer *" in the "Create Project" as well as in the "Edit Project" screen. This field should not be mandatory.

**Describe alternatives you've considered**
So far I always have to fill in activity even when there's just one available.

**Screenshot**
![Bildschirmfoto 2021-04-26 um 20 28 00](https://user-images.githubusercontent.com/81588467/116132495-eaa32900-a6cd-11eb-8038-086b01de68d9.png)

**Comment by kevinpapst** [comment]
Why don't you use another option to (re-)start previous timesheets?

**Comment by christian-lo** [comment]
Thanks for the fast reply – just restarting a previous timesheet doesn't save clicks (neither time) because then I need to reopen the task anyway to edit Description. Thus starting a new record will let me fill in all information at once with a click / selection less ;)

**Comment by kevinpapst** [comment]
From a simple click count I think is wrong.
Click start, click project
Click restart, click open, click description ... save

**Comment by kevinpapst** [comment]
There is an existing issue to pre-select entries if a dropdown has only one option. Please vote for it.
Sounds as if yours is partially a duplicate.

I know it probably won't work for the Activity select, if you have additional global activities - but anyways, it's a good start.
And in the future, the activity should become optional (configurable) which might solve the other issue you have right now.

**Comment by kevinpapst** [comment]
If a project has only one activity, it will be preselected.
