### ISSUE TITLE
Technology switch?

### ISSUE THREAD

**Issue by toaotc** [kimai/kimai#259]
I met Torsten (the kimai founder) 5 years ago and we talked about ExtJS to use for frontend. We did decide to decide it later.
Now it's 2013 and Kimai is based on technologies 10 years old.

My suggest for `Kimai2`:
- backend based on [Symfony2](https://github.com/symfony/symfony)
- frontend based on [Bootstrap](https://github.com/twbs/bootstrap) or Sencha [ExtJS](http://www.sencha.com/products/extjs/)/[Touch](http://www.sencha.com/products/touch/)

**Comment by kevinpapst** [comment]
This was long overdue: https://v2.kimai.org

This is just the start and we still have a long way to go.
Kimai v2 is based on Symfony 4.1, Doctrine ... the official announcement will follow soon.
