### ISSUE TITLE
Additional columns in teams overview

### ISSUE THREAD

**Issue by holzi1005** [kimai/kimai#2601]
**Does your feature request relate to a problem? Please describe it.**
I, as an administrator of many teams, would benefit from an additional listing of the "Projects" and "Customers" columns in the teams table so that I can quickly see which teams are old, historical, and no longer needed.

**Describe the solution you would like to see**.
Additionally, two columns, one with all customers and one with all assigned projects.

We can implement this feature as PR. Are there certain additional use cases, e.g. hide for view on xs (Like users) or other. As I can see, this table does not have any filter or selection options.

**Comment by kevinpapst** [comment]
HI! I'd accept a PR, sure. 

Customer column can be shown by default, Projects should be hidden by default.
But I can't tell you about responsive classes, you need to test it during development. If it doesn't fit, eg. hide it on XS.
I assume the objects are fully populated, but please make sure that you do not trigger `n` new database calls.
And if you want to add new features like more search options, you can do that as well.

**Comment by HeinzWuert** [comment]
I also have the problem with real teams that no longer exist. If a project is ended, the team of the same name is no longer required. Unfortunately there is no option in Kimai to delete the team that is no longer required when a project is ended.
It would be helpful to get an overview of these "orphans"!

**Comment by kevinpapst** [comment]
@holzi1005 still waiting for the PR

**Comment by kevinpapst** [comment]
Small interest, closing
