### ISSUE TITLE
Include ROLE_USER in SAML mappings to reject accesses of users without required roles

### ISSUE THREAD

**Issue by rmartinez-dasnano** [kimai/kimai#2614]
**Is your feature request related to a problem? Please describe.**
We are building a platform with several modules. One of them is Kimai. Modules are connected via SSO using as IAM Keycloak.
To integrate Kimai we used SAML.

In Keycloak realm configured for customers we have several roles for several user profiles. One of them is employee. Whithout this role user should not be able to access Kimai. But It seems with SAML user federation in Kimai, any authenticated user has ROLE_USER role by default

  >Every user automatically owns the ROLE_USER role, you don't have to create a mapping for it.

**Describe the solution you'd like**
It would be really helpfull to include also this role in SAML mappings, so if the user does not have the mapped role (EMPLOYEE in our case), then access to Kimai is not granted.

**Describe alternatives you've considered**

**Screenshot**

**Comment by kevinpapst** [comment]
You can sponsor a feature to reject login of special SAML users. Either financially or code wise.

**Comment by kevinpapst** [comment]
A new Boolean config should be added, that will (if activated) prevent Kimai from creating the user role.

**Comment by kevinpapst** [comment]
Closing, as this has no upvotes in 2 years.
Additionally there is no company that seems to be interested enough, to sponsor development.
