### ISSUE TITLE
Sum of hours in timesheet invoice

### ISSUE THREAD

**Issue by sideeffect42** [kimai/kimai#262]
**Is your feature request related to a problem? Please describe.**
When only hours are required the timesheet invoice template is great, except that it only prints a list of spent hours but no sum, so I have to go and sum up all entries by hand.

**Describe the solution you'd like**
I would want Kimai to calculate the sum and print it beneath the table.

**Comment by kevinpapst** [comment]
I need that as well: will be added soon!

**Comment by kevinpapst** [comment]
Implemented with #254 and already merged to master
