### ISSUE TITLE
Handle wrong server times better

### ISSUE THREAD

**Issue by ServiusHack** [kimai/kimai#266]
Forum post: http://forum.kimai.org/index.php?topic=2310.0

It could be that the server time is off. In that case some problems can arise. For instance, when starting a recording the client time is used, when stopping it the (wrong) server time is used. Maybe there are even more cases.

Since Kimai's most important part is to record time we should do our best to handle cases when the server time and client time differ.

**Comment by simonschaufi** [comment]
closed as duplicate to #507

**Comment by HenryNe** [comment]
Oh oh, that is not good. I have simple tested:
1. Local time 14:00 UTC, Server time 13:00 UTC
2. Press start and stop
3. Recorded: In=14:00 Out=13:00 h'm=-1:00 rate=-1,00

**Comment by kevinpapst** [comment]
@andreykl - if you want be able to choose whether client or server time is used, please raise a new issue. For the next release, we changed to using server time completely, as this is the easiest way to prevent a couple of possible errors.
