### ISSUE TITLE
Description in timesheet invoice

### ISSUE THREAD

**Issue by sideeffect42** [kimai/kimai#268]
I created a timesheet invoice that I use to export my hours to send to the client. The PDF that's generated is really nice.  
There is one little thing that bugs me, though.
It would be great if in addition to the "Activity" also the description of the entry as set in "My times" could be printed.

**Comment by sideeffect42** [comment]
Small update: The new freelancer invoice type shows the description just as I would need it but sums up the currency instead of the spent hours.

**Comment by kevinpapst** [comment]
Yeah, just wait a bit longer. Doing invoices properly and extendable is not easy. I have the plan in my head, but putting these ideas into code needs time unfortunately ;-)
In the meantime, its very easy to apply the change for yourself. Compare these two lines:
https://github.com/kevinpapst/kimai2/blob/master/templates/invoice/renderer/freelancer.html.twig#L76
https://github.com/kevinpapst/kimai2/blob/master/templates/invoice/renderer/timesheet.html.twig#L61

**Comment by sideeffect42** [comment]
No problem. Tbh I think the progress you're making is excellent.
I just wanted to note this here as for someone else looking for the same the new freelancer template could be just the right thing.

Thanks for the pointer to the invoice templates. I'll patch them locally in the meantime :-)

**Comment by kevinpapst** [comment]
Hey @sideeffect42 ! 
After a longer time working on improving the invoice system, I decided not to add your request.
Instead (and I think this is much better) I added a feature in the meantime, that allows you to add your customer templates to Kimai. Please see the documentation on this topic:
https://github.com/kevinpapst/kimai2/blob/master/var/docs/invoices.md

Also the default templates changed a bit, so what you have to do after updating to the latest version:

- create the directory `var/invoices/`
- copy the file [freelancer.html.twig](https://github.com/kevinpapst/kimai2/blob/master/templates/invoice/renderer/freelancer.html.twig) to `var/invoices/your-invoice-name.html.twig`
- adapt the new file `your-invoice-name.html.twig` to your needs
- configure this new file as invoice document in your invoice template

Can you live with that solution? 
Do you need help in adapting the template to your needs?

**Comment by sideeffect42** [comment]
Hey @kevinpapst,
just had a bit of time to play around with your new solution. That works for me. Thanks :-)
