### ISSUE TITLE
Rounding per customer, project or activity

### ISSUE THREAD

**Issue by VOOM108** [kimai/kimai#2680]
**Is your feature request related to a problem? Please describe.**
I have been generating timesheets with 1-minute-steps for all my customers for years and don't want to change that. One big customer needs the times rounded to 15-minute-steps. At the moment it is all or none, as rounding is a global setting. 

**Describe the solution you'd like**
Be able to configure rounding per either customer, project or activity 

**Describe alternatives you've considered**
Have no idea at the moment other than having to generate the timesheet and invoice for this one manually. Or maybe edit the entries every time to round to the needed step.

**Comment by glorpen** [comment]
@VOOM108 I've had same problem - single customer wants times rounded differently.
Since this feature still did not suddenly appeared in Kimai, you can check if my plugin resolves your problem: https://github.com/glorpen/kimai-duration-plugin

**Comment by VOOM108** [comment]
Thanks, works nicely. :) I have to export not only the result but also the start- and end times to a timesheet, though. I think the times will be calculated by the software the client uses, and it might not tolerate a discrepancy between the rounded result and the time logged. But I have to check that with them. In that case, I would still have to change the start- and end time for an entry.

**Comment by kevinpapst** [comment]
Super cool solution @glorpen 👍 

I'd like to invite you to add a page to the website/marketplace, so other users can find your plugin as well:
https://www.kimai.org/documentation/store.html

**Comment by VOOM108** [comment]
Please, if possible, add an option to round the times logged as well, not only the result, for the reasons mentioned above.... :) In my case, if I still have to change the times anyway, I need no rounded results in the first place...

**Comment by kevinpapst** [comment]
Closing here due to @glorpen plugins: https://www.kimai.org/store/glorpen-duration-bundle.html 

I have no plans to add this to Kimai core.
