### ISSUE TITLE
Adding rates to customers, projects and tasks

### ISSUE THREAD

**Issue by oskarhotel** [kimai/kimai#271]
Hi,
in Kimai V2 I cannot locate where to add hourly/daily rates to users, projects and tasks. Is this a feature that is still not implemented? When will the feature be accessible?

**Comment by kevinpapst** [comment]
Yes, you are right. It is "still" not implemented.
I think its important, but other stuff has more priority right now.
 Lets see how many user vote for the feature.

**Comment by kevinpapst** [comment]
BTW. You can apply a fixed rate for a user in his profile section. I'll rename the issue.

**Comment by oskarhotel** [comment]
Sorry, but I can't find the the field to apply a fixed rate in the profile section of the https://demo-v2.kimai.org/de/admin/user/ environment.


________________________________
Von: Kevin Papst <notifications@github.com>
Gesendet: Freitag, 17. August 2018 23:14:13
An: kevinpapst/kimai2
Cc: Hader, Joachim; Author
Betreff: Re: [kevinpapst/kimai2] Adding rates to projects, users and tasks (#271)


BTW. You can apply a fixed rate for a user in his profile section. I'll rename the issue.

**Comment by kevinpapst** [comment]
Right now, you can only set your own rate => you cannot apply it to profiles of other users.
Check the first field in the preferences section - called "Hourly rate"

**Comment by oskarhotel** [comment]
Ok, found it. Thank you.

Looking Forward to get these Features as well as both "billabel tasks" and "not billable Tasks"

Regards

Joachim


________________________________
Von: Kevin Papst <notifications@github.com>
Gesendet: Montag, 20. August 2018 13:25:54
An: kevinpapst/kimai2
Cc: Hader, Joachim; Author
Betreff: Re: [kevinpapst/kimai2] Adding rates to customers, projects and tasks (#271)


Right now, you can only set your own rate => you cannot apply it to profiles of other users.
Check the first field in the preferences section - called "Hourly rate"

**Comment by tommyms** [comment]
This is an important feature for anyone doing consultancy work. I am considering making a time tracking system myself that handles these things, but would be nice to be able to use Kimai 2 instead if it gets the necessary features over time :)

**Comment by tommyms** [comment]
@kevinpapst good point :)

**Comment by kevinpapst** [comment]
@oskarhotel I created a new issue for "setting other users hourly rate", please vote on #303 to increase its importance.

Please create a new feature request for the billable / non billable tasks. Its not possible to work on multiple features in one GitHub issue.

Fixed and hourly for single timesheet entries is available in master. Please see the Pull request #304 - fixed and hourly rates can then be set on activities, projects and customers.
I'd appreciate help in testing.

**Comment by oskarhotel** [comment]
@kevin Thank you very much.

I’ll open a new feature request.

 

Von: Kevin Papst <notifications@github.com> 
Gesendet: Donnerstag, 6. September 2018 09:54
An: kevinpapst/kimai2 <kimai2@noreply.github.com>
Cc: Hader, Joachim <Joachim.Hader@secudor.de>; Mention <mention@noreply.github.com>
Betreff: Re: [kevinpapst/kimai2] Adding rates to customers, projects and tasks (#271)

 

@oskarhotel <https://github.com/oskarhotel>  I created a new issue for "setting other users hourly rate", please vote on #303 <https://github.com/kevinpapst/kimai2/issues/303>  to increase its importance.

Please create a new feature request for the billable / non billable tasks. Its not possible to work on multiple features in one GitHub issue.

Fixed and hourly for single timesheet entries is available in master. Please see the Pull request #304 <https://github.com/kevinpapst/kimai2/pull/304>  - fixed and hourly rates can then be set on activities, projects and customers.
I'd appreciate help in testing.

**Comment by kevinpapst** [comment]
Available in master now, please [read the documentation](https://github.com/kevinpapst/kimai2/blob/master/var/docs/timesheet.md#rate-calculation) and the PR #304 for more information:
