### ISSUE TITLE
Memory size always exhausted

### ISSUE THREAD

**Issue by obnys** [kimai/kimai#273]
**Describe the bug**
My apologies in advance for posting here. I'm pretty sure, this is not a bug, but I could only choose between bug and feature request. After installation I can't open the website. It stays blank. Apache error-log says:

PHP Fatal error:  Allowed memory size of xxxx bytes exhausted (tried to allocate 4096 bytes) in /var/www/htdocs/kimai2/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

PHP Fatal error:  Allowed memory size of xxxx bytes exhausted (tried to allocate 57344 bytes) in /var/www/htdocs/kimai2/vendor/composer/ClassLoader.php on line 412

It always tries to allocate the same amount of bytes as mentioned above, no matter how high I set max memory (tried 128M, 256M, 512M, 1024M)

**To Reproduce**
I did edit memory_limit in /etc/php/7.2/apache2/php.ini to any size and restartet apache2. The error message stays the same.

**Expected behavior**
Login Screen being displayed

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Win7 Ultimate
 - Browser: Firefox
 - Version: 61

**Additional context**
Server: Ubuntu 16.04.5 LTS (on Odroid XU3, armhf) with Apache/2.4.18 and PHP7.2

**Comment by kevinpapst** [comment]
Please check if there is anything in `var/log/`. I suspect not and I suspect that you forgot to set the filepermissions. 

What happens is: 
- a logfile should be written, but that fails due to filepermissions
- that problem is catched by the logger, which tries to write it to its logfile
- and that repeates until all memory is full

Fix it by following the installation docu ;-) or by applying the permissions your system needs (for the webserver user) to be able to write to `var/` inside the Kimai directory.

**Comment by kevinpapst** [comment]
@obnys does it work now?

**Comment by obnys** [comment]
My apologies for the late response. During the past days I had trouble finding time for this project. It does work indeed. It seems I forgot to set both ownership and file permission (although I could swear I did it). Many thanks for your fast help. Currently the login page is beeing displayed and I can log in with my superuser, but the pages are all white and not formatted. I think this has something to do with symfony. But this is another issue which has nothing to do with this thread ;-).

Again, thanks a lot! :+1:

**Comment by kevinpapst** [comment]
No problem, I can help with this as well. How are you using Kimai? Currently it doesn't support to be used in a subdirectory out-of-the-box.
Everything is good if you installed it at https://kimai2.example.com/
But if you installed it at https://example.com/kimai2/ then the assets (like CSS and JS files) can't be loaded => see https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md#rebuilding-assets-for-use-in-a-subdirectory

**Comment by kevinpapst** [comment]
I will close this issue, if you still have troubles with the assets, please open a new issue.
