### ISSUE TITLE
Improve dashboard display

### ISSUE THREAD

**Issue by jeau** [kimai/kimai#280]
While working on the French translation of Kimai, I noticed that the display of statistics in the dashboard boxes is not very readable for this language. Indeed, sentences are often longer than in English. I suggest a two-line display.

I also think we should specify the format for displaying times with language translation. The same way as for the dates. For example, in French `12:18 h` should appear `12 h 18 min`

Finally, amha for the revenues display two decimals are enough ;)

![capture d ecran 2018-08-21 a 14 49 25](https://user-images.githubusercontent.com/3129299/44403268-4b105e80-a554-11e8-9393-7da802dd9779.png)

**Comment by kevinpapst** [comment]
The decimals are a bug, which I don't yet understand. 
There is already a rounding applied, don't know by now why that happens on some systems and not on others. I will investigate on this.

Time format is a good info 👍will add a setting for it.

Regarding the two lines, this is a CSS setting, I'll also check out this one.

**Comment by kevinpapst** [comment]
@jeau Could you fetch the latest master and propose another format for french:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L45
Its now possible to configure the short (in all data-tables) and long duration (currently only used for the dashboard widgets) format for every language separately.

**Comment by kevinpapst** [comment]
Used the format you mentioned above `12 h 18 min`.

**Comment by jeau** [comment]
Hi @kevinpapst 
great thanks
for french format, could you set `duration_short` to '%%h:%%m' ?
without the h at the end 
thierry

**Comment by jeau** [comment]
Oups @kevinpapst 
the correct format in this context for french translation is `duration_short: '%%h h %%m'`

sorry
th

**Comment by kevinpapst** [comment]
@jeau can you please create a new pull request if you think it should be changed?!
