### ISSUE TITLE
Add inline editing of "Tracking number" on timesheet

### ISSUE THREAD

**Issue by hzqmrk** [kimai/kimai#281]
## Description

Please consider adding inline editing of "Tracking number" on timesheet.  This is a convenience only feature.

## Your Environment
* Version: v1.3.1.1394
* Browser Name and version: Firefox 61.0.2
* Operating System and version (desktop or mobile): Windows 7

**Comment by kevinpapst** [comment]
@hzqmrk are you talking about the "timesheet" invoice template? I just checked it, inline editing is there since the first commit.

**Comment by hzqmrk** [comment]
Maybe I missed it, but there is a checkbox in the user prefs to make the
description editable in the timeline view.  Just click or tab to the field
and type.  No need to open the entry dialogue.

I want same for tracking ID.  Perhaps I missed a setting, but right now if
I want to set or change the tracking ID I have to open the time entry,
click on advanced tab, change ID, then click OK.
