### ISSUE TITLE
Dollar Budget Remaining is incorrect for Activity and Project

### ISSUE THREAD

**Issue by diamondq** [kimai/kimai#2820]
**Describe the bug**
I created a project and sub-activity, both with a Monetary (Canadian Dollar) and Time Budget defined. When adding a timesheet entry to the activity, the "are still open" is quite incorrect:

Sample data:
Budget | CA$30,000.00 | 100%
Total revenue | CA$156.25 | 0.52%
Billable | CA$156.25 | 100.00%
Internal rate | CA$156.25 | 100.00%
0.52% used (CA$863,843.75 are still open)

**Additional context**
 - Kimai version: 1.15.2 stable
 - PHP version: 8.0.10
 - Device: Ubuntu via tobybatch Docker image
 - Browser: Brave (Chrome variant) v1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit)

**Comment by kevinpapst** [comment]
Thanks, confirmed.
Calculation used "time budget" - "money budget" which will be fixed with #2821
