### ISSUE TITLE
Add support for MS Office templates

### ISSUE THREAD

**Issue by AlxBe** [kimai/kimai#283]
Include the possibility to use MS Office templates for invoices.

**Comment by kevinpapst** [comment]
Yep, that will definitely be added in the invoice milestone

**Comment by kevinpapst** [comment]
Hi @AlxBe !
I am currently working on a major invoice refactoring, including a Docx export.
I would appreciate if you could test it and give me some feedback.
Here is the pull request: #306

**Comment by AlxBe** [comment]
Hallo Kevin Pabst,

mach ich, ist Anne erst ab nächste Woche..

Grüße Alex

Am 14. September 2018 00:07:41 MESZ schrieb Kevin Papst <notifications@github.com>:
