### ISSUE TITLE
Small typo leads to broken update

### ISSUE THREAD

**Issue by alqu** [kimai/kimai#2839]
This trailing comma:
https://github.com/kevinpapst/kimai2/blob/b2d3272151523106027da1d31311bf6fbaf4c7d4/src/Repository/TeamRepository.php#L214

Leads to a broken upgrade process.
Fix: remove trailing comma.

I am running an old PHP 7.2.24 on a CentOS 8.4.2105 machine with Kimai 1.15.4

**Comment by kevinpapst** [comment]
I can remove that, but you have to update your PHP. 
PHP 7.3 is a requirement for Kimai >= 1.15, see https://github.com/kevinpapst/kimai2/blob/master/UPGRADING.md#115

Not only is 7.2 long outdated and doesn't receive security updates, but also all dependencies of Kimai are bumped and use 7.3 features. So you will likely run into more bugs sooner than later.

And not to forget: I am going to use more and more 7.3 language features.
