### ISSUE TITLE
incorrectly calculated length of activity, if it spans across calendar month/s

### ISSUE THREAD

**Issue by litinoveweedle** [kimai/kimai#2844]
**Describe the bug**
When activity spans (from start to end) across a calendar month, then activity length-duration is incorrectly calculated - it is one hour longer than it should be.

**To Reproduce**
1. Go to calendar
2. Create activity starting 30.10.2021 00:00 and ending 31.10.2021 00:00
3. See correct activity duration 24hrs
2. Create activity starting 31.10.2021 00:00 and ending 1.11.2021 00:00
3. See error - activity duration is incorrectly calculated as 25hrs

**Logfile**
```
no message/error logged
```

**Additional context**
 - Kimai version: 1.15.4
 - PHP version: 7.3

**Comment by kevinpapst** [comment]
https://en.wikipedia.org/wiki/Daylight_saving_time

**Comment by kevinpapst** [comment]
So you got only extremely "lucky" to choose the correct day. That can happen 😁 and it proves that Kimai works correctly in edge cases.

**Comment by litinoveweedle** [comment]
Yep, that is me - being extremely 'lucky' time to time.😆 Anyway thank you for kimai, I did at least bought few of yours plugins meanwhile, to support this great project.

**Comment by kevinpapst** [comment]
Thanks for the support, I hope Kimai is useful for you!
