### ISSUE TITLE
Support for time tracking hardware like timeflip

### ISSUE THREAD

**Issue by nikolauskrismer** [kimai/kimai#285]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Recently I discovered tools that I would call "hardware supported time tracking". The most well-known devices seem to be (TimeFlip)[https://timeflip.io/] and/or (ZEI° by Timeular)[https://timeular.com/]. What would be great now is to integrate these devices to kimai. I haven't looked into the details yet, but a quick read shows that there is an API at least for timeflip (for ZEI there seems to be a CSV export functionality but only when paying a monthly fee).
I really think that such an integration could improve tracking the time spent for phone calls, e-mails on the web or on working on a certain project and that tracking detail would reach more precise levels (turning a dice is much easier than adding a new record on a web application).

**Describe alternatives you've considered**
I did not consider any other or existing solutions, since they are either cloud-based (which I do not want my time tracking to be) or not very intuitive (like smarphone apps....). However, I will describe two alternatives I can think of :-)
If already existing devices can not be integrated (or should not be used because they produce heavy costs) I can think of two things:
1) Build your own tracking device. Arduinos and/or RaspberryPis (or other single-board systems) could certainly be used for that...
2) Use USB devices for tracking time (I am wondering a bit why I did not find other solutions that are already doing that). Connecting a small memory stick via USB could mean something like "I am on the phone now" while using another stick could indicate "working on project X". I now that this needs a desktop sync client that queries the operating system for a log about connected devices (and the history of connections), but I could imagine that at least for Unix based systems (like Mac, Linux) this is not that hard to implement...

**Additional context**
Right now there is no additional context :-)

What do you think about that request? Let me know so we can discuss a bit more about it...

**Comment by kevinpapst** [comment]
I don't really know what to write here, I never saw these solutions before. On a first glance they look like gadgets that can't decide whether they are time-management or time-tracking apps.
I can't see myself using them, but playing with them when they lay on my desktop and then accidentally recording dozends of tasks ;-) 
Plugging in and out USB sticks to manage time-tracking sounds even stranger to me.

Kimai has an API which could be used to write any add-on you want. You could build a plugin with some simple functions for your taskbar (which might be more intuitive to use than a web-app) or you build a hardware device which trigger some HTTP calls to the Kimai API.

Yes, your request is very interesting. For example having a programmable keyboard like these:
www.amazon.com/XK-24-USB-Programmable-Keypad-Windows/dp/B003MB780E/
and then connected to Kimai with buttons for single Activities, pause and stop sounds very neat.

I would totally support everyone who wants to work on that with API adjustments etc.

**Comment by nikolauskrismer** [comment]
Your idea with a keyboard is nice too.
The WAF might be a bit lower, but cost are also low.
My idea right now is to use a command-line tool that starts/stops recording and allows to pass the activity to track while also handling authorization. One could then call this tool from a programmable keyboard.

I really hope that a programmable keyboard is not necessary.
However, I think that adding a second numblock to the system should at least help when using linux (there should be some way to add a numblock as separate device and then matching the keys in gnome/kde to the command line tool).

**Comment by nikolauskrismer** [comment]
I just bought a small numblock today (~10 dollars). A lot cheaper than the "programmable" keyboards and thanks to some linux tools (see https://unix.stackexchange.com/questions/35649/second-keyboard-to-run-commands) does something very similar.

Now I need to bind the keys to kimai2. Is there something like a bash script that one can call to start/stop activities? Maybe this can be implemented using the API :-) Is there some documentation about the API?

I will write a blog entry on how to configure things after everything works as it should, so you can copy/link it afterwards

**Comment by nikolauskrismer** [comment]
After some problems I finally managed to install kimai2 onto my server...
I had to add variable assignments to my mysql my.cnf file:
```
innodb_file_format=Barracuda
innodb_file_per_table=1
innodb_large_prefix=1
innodb_default_row_format=dynamic
```
Maybe one should document that.... without these changes the database schema could not be created due to too large keys (Error "Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")

However... back to the topic... I also managed to access the API.
As far as I can see there are only GET methods... so right now the API is read-only, isn't it?
To add time tracks using hardware devices (and the API) I would net a POST method. I can think of two different approaches:
1) Track everything in kimai. By that I mean that i send something like "start activity X" to the API and after a while end the activity by sending a "stop activity X". All error handlings would need to be implemented in Kimai. The advantage would be that this in general would work with multiple devices. So one could start an activity in the office and ending the same activity (using a mobile device) at home, in the subway (if I forgot to stop it in the office) or even after a meeting at the client's facility.
2) Track everything offline. The API is only used for entering results. I would track start- and stop-time on the client and only sent something like "Activity X lasted from 08:00 a.m. to 11:21 a.m.". The advantage would be that kimai does not need to handle complex error cases. However, cross-client functionality would be hard to implement (or needs something like cloud storage).
What do you think would be better here? I am willing to write my client(s) for either approach...

**Comment by nikolauskrismer** [comment]
The problem occurred in combinration with MariaDB 10.1 (under centos 7).
From what I've read I suppose this is not a problem with MariaDB 10.3 anymore (so I upgraded in the meantime)...

I will open FRs for the APIs changes as soon as I have a prototype.

**Comment by kevinpapst** [comment]
Sounds great 👍 please keep me updated. And let me know if I can be of any help/support you!
Kimai will be even betterwith a healthy developer environment and different endpoints. I really like your idea and would like to document or blog about it once we have something that works.

**Comment by nikolauskrismer** [comment]
Added FR #315 for first API changes

**Comment by kevinpapst** [comment]
Closing this as the API is in place and I added #829 (explicit issue about hardward support)
