### ISSUE TITLE
"Come" and "Go" Function

### ISSUE THREAD

**Issue by waldi** [kimai/kimai#288]
Hi,
i'm having a feature request. Following situation:
We use Kimai in our small company to track the times we work for our customers. But we also track the time we are at work itself (the time we are in the office).
But unfortunately you can only start one project at a time so we modified kimai so we had this little button up there to "Come" and "Go"
Wouldn't this also be an idea for the official kimai?

Best regards,
W4ldi
![03-12-2013 10-18-33](https://f.cloud.github.com/assets/11230/1662324/e4f2f4a0-5bfc-11e3-8e32-977595c769b2.png)

[![bountysource](https://api.bountysource.com/badge/issue?issue_id=1900893)](https://www.bountysource.com/issues/1900893)

**Comment by simonschaufi** [comment]
@waldi any response would be great! We would love to integrate it into the core then ;)

**Comment by kevinpapst** [comment]
Yeah, kind of ... we have to speak about the UI and configuration settings first. But its a great feature!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
