### ISSUE TITLE
User Groups and team permissions

### ISSUE THREAD

**Issue by nashbrydges** [kimai/kimai#298]
Need to be able to assign users to groups.

Need to allow groups to have assigned a team lead who can manage/add/edit all associated Activities and Projects for this group.

Also need the ability to create Global Activities that do not necessarily need to be assigned to Projects. There could be activities that exist for all or many Projects and having a Global activity that's available for Group Users to select would be useful instead of having to duplicate Activity for each Project.

**Comment by kevinpapst** [comment]
Global activities is a quite complex theme, but I am already working on it: see #259 

The other topic is something that is definitely on the roadmap.

**Comment by kevinpapst** [comment]
Global activities are implemented and the team and permission approach will be discussed in #366
