### ISSUE TITLE
Activity Re-Use

### ISSUE THREAD

**Issue by jamesorose** [kimai/kimai#301]
Hi,

First, V2 looks absolutely fantastic! Great work!

Something I saw that is useful in previous versions (and either missing in v2, or I did not see it) is the ability to add pre-set activities when you create a new project. In our case, we basically only have 4 activities for all customers/projects. It's easier and less error prone to select from pre-populated activites when the project is created.

Regards,

James

**Comment by jamesorose** [comment]
This was already raised in other issues. Apologies for the duplicate.

**Comment by kevinpapst** [comment]
Thanks for the feedback!
I know many people need it, so I am already working on it, but it will take some more time.
