### ISSUE TITLE
Change favicon while tracking

### ISSUE THREAD

**Issue by jorunkel** [kimai/kimai#3057]
**Is your feature request related to a problem? Please describe.**
Currently the favicon is the same all the time. Kimai changes the page title to the duration when tracking is active. But since I'm using Kimai in a pinned tab in Firefox there is no way to see that. Working in other tabs I'd like to have a visual indicator whether tracking is active or not.

**Describe the solution you'd like**
Kimai should change its favicon while tracking time. I.e. it could change color (red) or the symbol on it to a stop sign or even both. That would give some visual indicator that tracking is active even when the tab is not active.

**Comment by kevinpapst** [comment]
You seem to be a developer, would you like to suggest a solution / work out a PR?

**Comment by jorunkel** [comment]
To be honest I'm not familiar with the source code of Kimai. The actual changeset should be quiet small, though. For the clientside part here ist some example code:
https://stackoverflow.com/a/260877

**Comment by BKapelari** [comment]
Maybe the easiest way would be something like this
Website: http://lab.ejci.net/favico.js/
Github: https://github.com/ejci/favico.js

**Comment by kevinpapst** [comment]
Looks like a nice library, even though it does not work in Safari. Thanks for sharing @BKapelari 

But: it is not maintained since 7 years and has too many features (10kb). If you know a more recent version, supporting ES6 builds I'd be happy to have a look.

**Comment by BKapelari** [comment]
Yes I see the same problems. Maybe we ca find something similar

**Comment by BKapelari** [comment]
Okay, I did a little recharge:
it is really simple to change the Favicon via JS:
` fdocument.querySelector("link[rel$=icon]").setAttribute('href', 'new-favicon.ico');`
This should work in all mayor browsers except IE and Safari.

**Comment by BKapelari** [comment]
Do you like this one?
![kimai_logo_stop_transparent](https://user-images.githubusercontent.com/4718590/179183482-cd9e548b-dfcb-4aa0-9ee0-45c2a5c8c41a.svg)

**Comment by buzter** [comment]
Just an idea: What about an icon that better indicates what's going on? Just arranged this in only seconds to illustrate what I mean:
![kimai_logo_running_transparent](https://user-images.githubusercontent.com/19949143/179188683-25426c71-117e-4823-bdc9-6db2c4f442a3.svg)

**Comment by buzter** [comment]
Okay, understand Your point. These could be simpler versions of the icon. I also simplified the one developed by @BKapelari 

![standard_simple](https://user-images.githubusercontent.com/19949143/179207952-19bf6a69-c1cd-43ed-a836-b135013d08f9.svg) 
![stop](https://user-images.githubusercontent.com/19949143/179207989-fa96fa71-3d6c-479a-9f8f-288bb30d67a7.svg)
![running](https://user-images.githubusercontent.com/19949143/179208007-f0e87ea1-a12d-469b-a902-6d22a58ad68c.svg)

**Comment by kevinpapst** [comment]
@BKapelari if you want to give it a try, send in a PR. We can still optimize the icons later on.

**Comment by BKapelari** [comment]
> We need an icon first. I have zero software/knowledge about image manipulation. Can someone make a stop icon from this: https://github.com/kimai/images/blob/master/kimai_logo_transparent.svg ?
> 
> The code would go here (if entries.lenglth > 0: toggle icon) https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiActiveRecords.js#L67

this works as it should. But if I reload the page, the icon is gone. I think there is a interval function for checking if the tracker is running. Where can I find it?

**Comment by kevinpapst** [comment]
See here: https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiActiveRecordsDuration.js#L34

**Comment by BKapelari** [comment]
okay, seems to work. Here is my code: https://github.com/BKapelari/kimai2
Maybe we should define de "stop_favicon" in the config file?
Also the naming could be better.
I'm looking forward to your feedback!

**Comment by kevinpapst** [comment]
Thanks for testing! I will have a look and add it, if it works properly.

**Comment by kevinpapst** [comment]
See https://github.com/kimai/kimai/pull/4038

Once I get a package of better icons, I will change it to flip the image instead of adding the red rectangle.
