### ISSUE TITLE
Date range inclusiveness inconsistency 

### ISSUE THREAD

**Issue by strangecode** [kimai/kimai#306]
The date range filter does not include entries that have a date that matches the end date, while they do include entires that have a date that matches in the begin date. This issue exists for both the one at the top of the GUI and when making queries via the API (`getTimesheet` method, with `from` and `to` dates). 

E.g.: If I set a filter of `Jan 1` - `Jan 31` it will only include entries from Jan 1 to Jan 30. 

I'm working around this by issuing queries via the API for `Jan 1` to `Feb 1` to ‘get all entries from last month.’ If you guys change this behaviour, which I think you should,  please let us know so we can adjust our use of the API so we don't process duplicate days (entries on `Feb 1` would be duplicated for us if the behaviour were to be fixed). You might even consider adding a new API method with the corrected behaviour, `getTimesheetInclusive` so as not to catch anybody off guard. Thanks.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
