### ISSUE TITLE
Feature request: Quick search box for activities when creating new timesheet

### ISSUE THREAD

**Issue by xaro1** [kimai/kimai#307]
We have 200 customers, 10 projects for each customers and 20 activities for each projects. In this scenario, an activities list box is simply unthinkable. Quick search box (as on kimai v1) is more suitable.

A list of shortcuts of activities for each user will be great. #idea

**Comment by kevinpapst** [comment]
Already in work, unfortunately mixed in in the PR for the global activities. See #259

**Comment by kevinpapst** [comment]
While working on global activities, I added a three step form when starting a new record.
You now have to select a project and then the list of its activities is fetched for the select box. You can even narrow that down by first selecting the customer, then the project and the activity as last step.
If you want to test that, checkout the branch PR #259
