### ISSUE TITLE
Choosing CUSTOMER and adding a project directly 

### ISSUE THREAD

**Issue by jabertolin** [kimai/kimai#309]
Hi,

Probably is a bug or missing feature.

When filtering customers to get only their projects, if you add a new project once you inform the name of the project you need to choose again the customer. As you are filtering the projects for a customer I consider that adding a project should inform the field "Customer" with the name of the customer filtered.

Thanks
JAB

**Comment by simonschaufi** [comment]
Is this issue about the lists in the footer or the Administration?

**Comment by kevinpapst** [comment]
Cleaning up very old issues that nobody voted on.
