### ISSUE TITLE
Installation of kimai2 does try to access "/de" website which is not present

### ISSUE THREAD

**Issue by Richigeht** [kimai/kimai#310]
**Describe the bug**
Hi
just setting up the test environment, and though I got some errors while creating the database it seems to have created it now? I could add a user but by access the website it tries to go to /de and that does not exist, so I get an 404 error.
**To Reproduce**
1. Follow the installation guide using php, mysql.
2. Try to access the website.

**Expected behavior**
Well that the website loads up :) 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kevinpapst** [comment]
I can't help with that description. 
You got errors during installation, then show them. How shall I otherwise know what happened?
Also, please give all information you can: PHP version, database version ....
What in the log file? Check var/log/

**Comment by Richigeht** [comment]
Hi
Well then I wanted to log them, couldn’t reproduce them. 
Using php 7.2 and MySQL 10.1.26 but shouldn’t matter though since I just get a 404 error for trying to access /de folder. 
There is nothing in Apache logs. 



Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by kevinpapst** [comment]
How did you configure your VirtualHost? 
I do not recommend apache and haven't used it in a while ... but it should still work if you point your document root to the `public/` directory. There is an .htaccess file that should be picked up if you configured AllowOverwrite. If not, then you have to add the stuff from the .htaccess file to your server configuration:
https://github.com/kevinpapst/kimai2/blob/master/public/.htaccess

**Comment by Richigeht** [comment]
Hi
Well that could be the reason for it I guess. I have just worked with an Alias here. I will give it another try. 

For the Database stuff - is there some logging done and stored automatically? If not I will recreate the Database. 

Also sorry for the lack of input - I am traveling and the hotel WiFi just kicked me out all the time so was a bit limited being able to work :-/ 


Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by kevinpapst** [comment]
There is no log created, if you want a log please pipe the database and schema creation calls into a file. 
Probably try the `kimai:reset-dev` command (see the docu), that will erase all tables and data from the Kimai database and re-create everything + insert demo data. Just for testing, while you update your webserver config.

Enjoy your trip!
