### ISSUE TITLE
Out of memory exception while trying to access the website

### ISSUE THREAD

**Issue by Richigeht** [kimai/kimai#313]
**Describe the bug**
Out of memory exception after the initial setup while trying to access the website. 
**To Reproduce**
1. Setup php.ini limit to 512M (though the error message clearly states it cannot allocate x amount of bytes which is smaller than the allowed RAM usage)
2. Try to launch the website.

**Expected behavior**
trying to access the website for testing.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
/src/Monolog/Handler/StreamHandler.php on line 107
[Thu Sep 20 22:22:10.428741 2018] [php7:error] [pid 4039] [client 80.255.7.98:53510] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in /var/www/limesurvey_new/kimai2/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1
From the log files. 

Using php7.2 and apache 2.4.25.

Found, if you Google it, hints that you might want to use
"ini_set('memory_limit', '-1');" in the PHP file. 
https://www.drupal.org/forum/support/post-installation/2013-02-12/solved-fatal-error-allowed-memory-size-of-33554432-bytes#comment-10140834

**Comment by kevinpapst** [comment]
The logger fails writing to the log file and tries to log that error => infinite loop. 
Please follow the installation documentation step by step ;-)
```
chown -R www-data var/
chmod -R 777 var/
```

**Comment by Richigeht** [comment]
Well, I gave now all files in kimai2 the 777 permission. I do see the website without design loading now. 
However just giving everything under /var the 777 permission does not sound like a good idea to me - or to have all that assigned to www-data though.

**Comment by Richigeht** [comment]
ok the issue is that this is running under a sub folder but tries to access back to the root folder for like the CSS stylesheet.

I.e. website runs under /kimai2/public
CSS is trying to be grabbed from /build/app.css

I will try to add a sub domain/different vhost then I am back and can work locally in the network to see if everything works then.

**Comment by kevinpapst** [comment]
This is a documented limitation (for now). 
But you can get it working in a sub-directory easily, if you have the tools installed: 
https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md#rebuilding-assets-for-use-in-a-subdirectory

**Comment by kevinpapst** [comment]
And btw. if you have a better idea on how to explain the "permission mystery" in a way that I do not spend my complete free-time explaining it to the non-experienced folks, I am happy to put that into the documentation. Yes "777 for var" is maybe not the best idea, but I am only explaining how you can get Kimai up and running quickly. Whoever fiddles around with servers should know what he is doing.
You seem to know a bit about servers and still have troubles ... probably experienced people tend to skip the documentation, you know ... they think reading it is only for beginners 'cause know their stuff ;-)

Ok, back to topic ... you can give `var/cache/` and `var/log/` the "right permission" if you feel safer this way.

**Comment by Richigeht** [comment]
Yep sounds like me - normally not reading manuals that closely :D

I will see that I get it working and the 777 thing, I will work on that if I have a moment. I just gave the Kimai folder for now this permission and it seemed to have worked besides the issue with the folder locations. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by kevinpapst** [comment]
What do you think of this:
```
chown -R :www-data .
chmod -R g+r .
chmod -R g+rw var/
```
?

**Comment by Richigeht** [comment]
Well I would just tell them to make the Kimai folder and not total /var folder indeed. :)

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by kevinpapst** [comment]
Can I close the ticket or do you still need assistance with the setup?

**Comment by Richigeht** [comment]
Should be fine to close it - will probably be able to figure out the rest thanks. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet
