### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by wolftone1916** [kimai/kimai#314]
**Describe the bug**
I installed the app locally and then uploaded all the files. Tried to navigate to the public folder and got a page 500 error and checked to see what error was causing it and was given the following:

> Uncaught Twig_Error_Loader: The "/home/south287/public_html/timeclock2.0/kimai2\vendor\symfony\framework-bundle/Resources/views" directory does not exist ("/home/south287/public_html/timeclock2.0/kimai2\vendor\symfony\framework-bundle/Resources/views"). in /home/south287/public_html/timeclock2.0/kimai2/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:101 Stack trace: #0 /home/south287/public_html/timeclock2.0/kimai2/var/cache/prod/ContainerJSVbq8m/srcProdProjectContainer.php(711): Twig_Loader_Filesystem->addPath('/home/south287/...', 'Framework') #1 /home/south287/public_html/timeclock2.0/kimai2/var/cache/prod/ContainerJSVbq8m/srcProdProjectContainer.php(1182): ContainerJSVbq8m\srcProdProjectContainer->getTwigService() #2 /home/south287/public_html/timeclock2.0/kimai2/var/cache/prod/ContainerJSVbq8m/srcProdProjectContainer.php(490): ContainerJSVbq8m\srcProdProjectContainer->getSensioFrameworkExtra_View_ListenerService() #3 /home/south287/public_html/timeclock2.0/kimai2/vendor/symfony/event-dispatcher/EventDisp in /home/south287/public_html/timeclock2.0/kimai2/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 101

**To Reproduce**
1. Installed locally
2. Uploaded all the files
3. Navigated to the public folder

**Expected behavior**
App would be installed and running.

**Screenshots**
None at the moment. I just see a white screen

**Desktop (please complete the following information):**
 - Chrome
 - whatever the installed pulled from github

**Smartphone (please complete the following information):**
NA

**Additional context**
I installed locally as I have a shared server access to my website. I cannot install composer as I don't have root access.

**Comment by kevinpapst** [comment]
Did you follow this documentation?
https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md#ftp-installation
Does the directory which is mentioned exist?

**Comment by wolftone1916** [comment]
> Did you follow this documentation?
> https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md#ftp-installation
> Does the directory which is mentioned exist?

Yes, I checked that the directory exists and it does. I as well followed the instructions on that page step by step. I'm not sure why it's not seeing the directory. 

The only thing I even noticed that looked off is that the directory has a **/** and after kimai2 it becomes a **\** 

would that cause it?

**Comment by wolftone1916** [comment]
![directory](https://user-images.githubusercontent.com/2268529/45898856-dc1b6500-bda0-11e8-856d-828f7b9d9dfa.jpg)
This is the folder list I have on the server.

**Comment by kevinpapst** [comment]
Actually I have no real idea what might be wrong.
Could you please delete everything inside the Kimai directory `var/cache/`, then give the directories:
- `var/cache/`
- `var/logs/`
write permissions.
Now try to reload the page. If it still doesn't work, have a look if there is a log file inside `var/log/` that might have more information.

**Comment by wolftone1916** [comment]
Okay so, I did what you said and did the write permissions. Got a login screen finally BUT:

![login](https://user-images.githubusercontent.com/2268529/45914348-87600480-be09-11e8-84ee-11819bb415ee.jpg)

There isn't any formatting on it and it gives that authentication error. Feel like it's a huge stride to get to this point though lol. So any clue about this?

**Comment by wolftone1916** [comment]
This is in the log you mentioned:

> [2018-09-22 01:49:21] request.INFO: Matched route "fos_user_registration_register". {"route":"fos_user_registration_register","route_parameters":{"_route":"fos_user_registration_register","_controller":"fos_user.registration.controller:registerAction","_locale":"en"},"request_uri":"http://southernstarbrewing.com/timeclock2.0/kimai2/public/en/register/","method":"POST"} []
[2018-09-22 01:49:21] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"secured_area","authenticators":1} []
[2018-09-22 01:49:21] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2018-09-22 01:49:21] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-09-22 01:49:21] php.INFO: User Deprecated: Referencing controllers with a single colon is deprecated since Symfony 4.1. Use fos_user.registration.controller::registerAction instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Referencing controllers with a single colon is deprecated since Symfony 4.1. Use fos_user.registration.controller::registerAction instead. at /home/south287/public_html/timeclock2.0/kimai2/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:39)"} []
[2018-09-22 01:49:21] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at /home/south287/public_html/timeclock2.0/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /home/south287/public_html/timeclock2.0/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /home/south287/public_html/timeclock2.0/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:50, PDOException(code: 0): could not find driver at /home/south287/public_html/timeclock2.0/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:46)"} []

**Comment by kevinpapst** [comment]
The styles are explained multiple times in the docu, Kimai frontend assets need to be recompiled if you want to use it in a subdirectory.
What is much worse: `An exception occurred in driver: could not find driver`
Your hoster seems not to support SQLite, which is a critical problem. I would try to contact them.

**Comment by wolftone1916** [comment]
Couldn't I just adjust the .env file to use MySQL?

**Comment by wolftone1916** [comment]
> The styles are explained multiple times in the docu, Kimai frontend assets need to be recompiled if you want to use it in a subdirectory.
> What is much worse: `An exception occurred in driver: could not find driver`
> Your hoster seems not to support SQLite, which is a critical problem. I would try to contact them.

I apologize for not understanding what was meant by front end assets.

**Comment by kevinpapst** [comment]
You could change the `.env` file to use MySQL, but you need the database tables and structure.
This can currently only be installed with the command line.
Try to execute this in your database:
```
     CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', alias VARCHAR(60) DEFAULT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, api_token VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_B9AC5BCE92FC23A8 (username_canonical), UNIQUE INDEX UNIQ_B9AC5BCEA0D96FBF (email_canonical), UNIQUE INDEX UNIQ_B9AC5BCEC05FB297 (confirmation_token), UNIQUE INDEX UNIQ_B9AC5BCEF85E0677 (username), UNIQUE INDEX UNIQ_B9AC5BCEE7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE kimai2_user_preferences (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, value VARCHAR(255) DEFAULT NULL, INDEX IDX_8D08F631A76ED395 (user_id), UNIQUE INDEX UNIQ_8D08F631A76ED3955E237E06 (user_id, name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE kimai2_customers (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, number VARCHAR(50) DEFAULT NULL, comment TEXT DEFAULT NULL, visible TINYINT(1) NOT NULL, company VARCHAR(255) DEFAULT NULL, contact VARCHAR(255) DEFAULT NULL, address TEXT DEFAULT NULL, country VARCHAR(2) NOT NULL, currency VARCHAR(3) NOT NULL, phone VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, mobile VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, homepage VARCHAR(255) DEFAULT NULL, timezone VARCHAR(255) NOT NULL, fixed_rate NUMERIC(10, 2) DEFAULT NULL, hourly_rate NUMERIC(10, 2) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE kimai2_projects (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, order_number TINYTEXT DEFAULT NULL, comment TEXT DEFAULT NULL, visible TINYINT(1) NOT NULL, budget NUMERIC(10, 2) NOT NULL, fixed_rate NUMERIC(10, 2) DEFAULT NULL, hourly_rate NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_407F12069395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE kimai2_activities (id INT AUTO_INCREMENT NOT NULL, project_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, visible TINYINT(1) NOT NULL, fixed_rate NUMERIC(10, 2) DEFAULT NULL, hourly_rate NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_8811FE1C166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE kimai2_timesheet (id INT AUTO_INCREMENT NOT NULL, user INT DEFAULT NULL, activity_id INT DEFAULT NULL, start_time DATETIME NOT NULL, end_time DATETIME DEFAULT NULL, duration INT DEFAULT NULL, description TEXT DEFAULT NULL, rate NUMERIC(10, 2) NOT NULL, fixed_rate NUMERIC(10, 2) DEFAULT NULL, hourly_rate NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_4F60C6B18D93D649 (user), INDEX IDX_4F60C6B181C06096 (activity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE kimai2_invoice_templates (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, address TEXT DEFAULT NULL, due_days INT NOT NULL, vat INT DEFAULT NULL, calculator VARCHAR(20) NOT NULL, number_generator VARCHAR(20) NOT NULL, renderer VARCHAR(20) NOT NULL, payment_terms TEXT DEFAULT NULL, UNIQUE INDEX UNIQ_1626CFE95E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     ALTER TABLE kimai2_user_preferences ADD CONSTRAINT FK_8D08F631A76ED395 FOREIGN KEY (user_id) REFERENCES kimai2_users (id) ON DELETE CASCADE;
     ALTER TABLE kimai2_projects ADD CONSTRAINT FK_407F12069395C3F3 FOREIGN KEY (customer_id) REFERENCES kimai2_customers (id) ON DELETE CASCADE;
     ALTER TABLE kimai2_activities ADD CONSTRAINT FK_8811FE1C166D1F9C FOREIGN KEY (project_id) REFERENCES kimai2_projects (id) ON DELETE CASCADE;
     ALTER TABLE kimai2_timesheet ADD CONSTRAINT FK_4F60C6B18D93D649 FOREIGN KEY (user) REFERENCES kimai2_users (id) ON DELETE CASCADE;
     ALTER TABLE kimai2_timesheet ADD CONSTRAINT FK_4F60C6B181C06096 FOREIGN KEY (activity_id) REFERENCES kimai2_activities (id) ON DELETE CASCADE;
```

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md

**Comment by wolftone1916** [comment]
I'm speaking the my hosting and they have said that it is supported. It shows here:

http://southernstarbrewing.com/phpinfo.php

**Comment by kevinpapst** [comment]
Show me your .env file please

**Comment by wolftone1916** [comment]
Here it is:

`# This file is a "template" of which env vars need to be defined for your application
# Copy this file to .env file for development, create environment variables when deploying to production
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

# KIMAI DEFAULT ENV VARS
DATABASE_PREFIX=kimai2_
MAILER_FROM=kimai@example.com

###> symfony/framework-bundle ###
APP_ENV=prod
APP_SECRET=change_this_to_something_unique
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS=localhost,example.com
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
# Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data/kimai.sqlite"
# Configure your db driver and server_version in config/packages/doctrine.yaml
# DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name
DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/kimai.sqlite
###< doctrine/doctrine-bundle ###

###> symfony/swiftmailer-bundle ###
# For Gmail as a transport, use: "gmail://username:password@localhost"
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
# Delivery is disabled by default via "null://localhost"
MAILER_URL=null://localhost
###< symfony/swiftmailer-bundle ###
`

**Comment by wolftone1916** [comment]
here:

> # This file is a "template" of which env vars need to be defined for your application
# Copy this file to .env file for development, create environment variables when deploying to production
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

# KIMAI DEFAULT ENV VARS
DATABASE_PREFIX=kimai2_
MAILER_FROM=kimai@example.com

###> symfony/framework-bundle ###
APP_ENV=prod
APP_SECRET=change_this_to_something_unique
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS=localhost,example.com
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
# Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data/kimai.sqlite"
# Configure your db driver and server_version in config/packages/doctrine.yaml
# DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name
DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/kimai.sqlite
###< doctrine/doctrine-bundle ###

###> symfony/swiftmailer-bundle ###
# For Gmail as a transport, use: "gmail://username:password@localhost"
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
# Delivery is disabled by default via "null://localhost"
MAILER_URL=null://localhost
###< symfony/swiftmailer-bundle ###

**Comment by wolftone1916** [comment]
Here:

# This file is a "template" of which env vars need to be defined for your application
# Copy this file to .env file for development, create environment variables when deploying to production
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

# KIMAI DEFAULT ENV VARS
DATABASE_PREFIX=kimai2_
MAILER_FROM=kimai@example.com

###> symfony/framework-bundle ###
APP_ENV=prod
APP_SECRET=change_this_to_something_unique
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS=localhost,example.com
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
# Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data/kimai.sqlite"
# Configure your db driver and server_version in config/packages/doctrine.yaml
# DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name
DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/kimai.sqlite
###< doctrine/doctrine-bundle ###

###> symfony/swiftmailer-bundle ###
# For Gmail as a transport, use: "gmail://username:password@localhost"
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
# Delivery is disabled by default via "null://localhost"
MAILER_URL=null://localhost
###< symfony/swiftmailer-bundle ###

**Comment by kevinpapst** [comment]
Sorry, I can't help here. The error is clear, it's trying to use SQLite but that doesn't work for some reason:
vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/**AbstractSQLiteDriver.php** line 90 {"exception":"[object] (Doctrine\DBAL\Exception\DriverException(code: 0): **An exception occurred in driver: could not find driver**
Try MySQL as suggested

**Comment by wolftone1916** [comment]
So maybe this is a dumb question but when you say to run those commands on that database, how does one do that?

**Comment by kevinpapst** [comment]
You have SSH access? Why didn't you follow the default installation? 
No, simply register, the first user will have Super Admin permissions

**Comment by wolftone1916** [comment]
I do but I haven't been able to get the install to work via ssh. Composer is installed already so I have to skip that step. I go to the next step and again get hit with an error regarding symfony. I just tried to create a new user and am met with:

![error](https://user-images.githubusercontent.com/2268529/45921298-903bef00-be78-11e8-8057-f8be4955937a.jpg)

**Comment by kevinpapst** [comment]
The installation does 100% work via SSH. Its being reinstalled every couple of hours automatically on my server, using the exact same commands which are documented in the README.

**Comment by wolftone1916** [comment]
I get that, however, my server already has composer installed and I don't have root access to install dependencies and composer. What I do instead is I upload the vendors folder to the kimai2 directory that I have from doing the install locally.

**Comment by wolftone1916** [comment]
So, I'm not sure if the 500 error page is coming back maybe due to the commands I ran that you sent me? They all seemed to be successful. I'll attach a screenshot of what the database looks like:

![error2](https://user-images.githubusercontent.com/2268529/45921596-5a016e00-be7e-11e8-9f96-5f3017bf4726.jpg)
and

![error3](https://user-images.githubusercontent.com/2268529/45921613-743b4c00-be7e-11e8-84a9-1aa6d857cc1d.jpg)

**Comment by wolftone1916** [comment]
Okay so, oddly enough. I am on the horn with my hosting, I had them check the error and they didn't get met with an error and were able to create the first user. I just logged in successfully so the install and setup must have worked and maybe my cache might have been the issue? I'm logged in now and just need to switch over the front end assets. Sorry for the headache I've caused trying to figure this out mate :/

**Comment by kevinpapst** [comment]
LOL, good to know that it works now. Let me know if you need help with the frontend assets.
Its unfortunate that you have to recompile them, but there is a bug in webpack-encore (the frontend build tool that is used) which prevents me currently from generating assets that works on (sub)domain level and subdirectories at the same time.

And while you work on it, you MUST change your document root. Its a **huge** security risk if you use Kimai the way you do it right now.

If possible map a subdomain to the path `/home/south287/public_html/timeclock2.0/kimai2/public/` - then you also don't need to recompile the assets.

If you can't use subdomains, then at least change the path mapping and use something like `http://southernstarbrewing.com/timeclock/` to point to `/home/south287/public_html/timeclock2.0/kimai2/public/`

**Comment by wolftone1916** [comment]
So, I guess my only question now would be about adjusting the public assets. So would I use the:

> /home/south287/public_html/timeclock2.0/kimai2/public/

in the webpack.config.js path and put it at .setPublicPath('/build/')?

and change the document root? Sorry for all the questions here.

**Comment by wolftone1916** [comment]
I can use subdomains. I have a mobile one that sits at m.mydomain. So create a subdomain and maybe call it something like time.mydomain.com and then map that subdomain to the public folder in kimai2?

**Comment by kevinpapst** [comment]
Yes, that would be perfect! In that case you also don't need to fiddle around with the frontend assets.

**Comment by wolftone1916** [comment]
So, again a stupid question lol. When you say point it to that directory. Do you mean do a redirect on the sub domain to point to it so time.mydomain would point to http://www.mydomain.com/timeclock2.0/kimai2/public/ ?

**Comment by kevinpapst** [comment]
No, `time.example.com` should point to the document root `/home/south287/public_html/timeclock2.0/kimai2/public/`. No redirect.

**Comment by wolftone1916** [comment]
So once that is done if someone say myself goes to time.example.com all the frontend assets should work?

**Comment by kevinpapst** [comment]
Yes

**Comment by wolftone1916** [comment]
The domain is up finally and it all is working amazingly! Can't  thank you enough for your time, help, and patience. Cheers mate!

**Comment by kevinpapst** [comment]
Glad to hear that! And thanks for your feedback 👍 
I'll release a new version in the next days, just in case you need adjustable invoice templates.
