### ISSUE TITLE
Add option for rendering PDF with wkhtmltopdf instead of tcpdf

### ISSUE THREAD

**Issue by igitur** [kimai/kimai#315]
TCPDF is great, but is limited in its CSS support. How about adding an option to rather use wkhtmltopdf when it is available on the system.

**Comment by MisterChoc** [comment]
any news about this topic? 
we need to export the invoices from html to pdf?

**Comment by kevinpapst** [comment]
This topic is for export, not invoice.

**Comment by kevinpapst** [comment]
There is no plan on our side to integrate that. Everyone who wants to have customized PDFs should think about rendering ODT and then printing this to PDF. This could even be done in your own renderer using the openoffice command line tools (I guess, never tried it).
If someone adds a Pull Request with wkhtmltopdf support, we would be glad to add it to Kimais core. Until then I close this issue as it is not on our roadmap.
