### ISSUE TITLE
API: Kimai metadata endpoint

### ISSUE THREAD

**Issue by bastilimbach** [kimai/kimai#320]
**Describe the solution you'd like**
Currently, there aren't any endpoints to determine some metadata about the running Kimai instance. It would be very beneficial to get some data about the currently running Kimai version and other information. Examples:

- Used Database
- Kimai version
- PHP version

**Additional context**
As you know, I'm currently converting [Timeu](https://github.com/bastilimbach/timeu) to support Kimai2 instead of Kimai v1. It would be really helpful to get the version of the running Kimai instance. With the version number, I could verify, that certain API endpoints and functionalities are available . Currently, I use the version number of the swagger API documentation for that use case, which isn't really optimal. I'm not even sure if the version number gets updated on an API change:

```json
  "swagger": "2.0",
  "info": {
    "title": "Kimai 2 - API Docs",
    "description": "REST API description for the Kimai 2 time-tracking software",
    "version": 0.1
  },
```

**Related issues**
#319

**Comment by bastilimbach** [comment]
I'm totally fine with only the version number! I thought this could be useful to other API clients, like a data-migration script. But that's not a common use case and the exposed PHP or database version could lead to a security breach.

If you could add the version number to the `ping` endpoint, that would be perfect! With this I could validate the Kimai instance URL and the version.

How do you plan on updating the version number? Do you get the version from the database or a static config file?

**Comment by kevinpapst** [comment]
I would keep it as constant in one file. Other third party provider already asked for it, as they need it for their automated installer. I'll add the changes later and send you an update here.

**Comment by bastilimbach** [comment]
I'm having some issues with creating a local dev environment for Kimai2. If I execute `bin/console kimai:reset-dev` I get the following error message:

```
[ERROR] Failed to import fixtures: There are no commands defined in the "doctrine:fixtures" namespace.

         Did you mean one of these?
             doctrine
             doctrine:cache
             doctrine:database
             doctrine:generate
             doctrine:mapping
             doctrine:migrations
             doctrine:query
             doctrine:schema
```
Also if I try to run the server using `bin/console server:run` it gave me this error:

```
There are no commands defined in the "server" namespace.
```

PHP and Composer are up to date and the PHP extension intl is installed.
