### ISSUE TITLE
Can't create invoice (on Yunohost)

### ISSUE THREAD

**Issue by tommyms** [kimai/kimai#324]
**Describe the bug**
When trying to create an invoice, it is not possible to proceed.

**To Reproduce**
1. Before doing anything, it says "Before you can create an invoice, you have to select at least a customer filter."
2. After selecting customer in the filter, it does not allow me to proceed, instead a red text error message shows above the filters: "This form should not contain extra fields."

**Expected behavior**
Expect to be able to continue and create and invoice.

**Screenshots**
![kimai2invoiceerror](https://user-images.githubusercontent.com/4073642/45975569-da71cb80-c044-11e8-82b6-191732858fd7.PNG)

**Additional context**
I am running on the latest release on Yunohost (0.4)

**Comment by kevinpapst** [comment]
Which URL is generated? Looks as if there is something wrong with the submitted data, which in this case is done via GET parameter.

**Comment by tommyms** [comment]
Yes, what should I look for?

**Comment by kevinpapst** [comment]
Simply produce the error and then paste the last ~ 10 lines here

**Comment by tommyms** [comment]
Hmm, I can't find anything relevant in the log file...

**Comment by kevinpapst** [comment]
You can simply force this error by adding any GET parameter, like so:
https://demo-v2.kimai.org/de/invoice/?template=1&user=6&begin=2018-09-01&end=2018-09-30&customer=1&dsfg

So maybe if the webserver is somehow configured to pass additional parameters to Kimai (which you wouldn't see in your browser address bar), this could happen as well.

Really no clue whats wrong there. What you could do to debug this problem: 
- switch to `dev mode by editing the `.env` file 
- doing a `composer install` to get all the additional packages that are required for development

Then, after reloading the page, you should see the Symphony debug bar at the end of the screen. When you click on the red-highlighted error you will be able to see the error that is actually happening in the form. 

I will check in the meantime if I can easily change from GET to POST, to circumvent possible environment issues.

**Comment by kevinpapst** [comment]
Or, probably an easier test:
Edit https://github.com/kevinpapst/kimai2/blob/0.4/src/Controller/InvoiceController.php#L247 and change from `GET` to `POST`.
You might have to call `bin/console cache:clear` afterwards, so the changes will be used.
Then test the form again.

**Comment by kevinpapst** [comment]
That is weird, but okay. I changed it for the latest release, so I guess we can close the issue?

**Comment by tommyms** [comment]
Yes, sounds good!
