### ISSUE TITLE
add the same activity for multiple projects

### ISSUE THREAD

**Issue by eglyn** [kimai/kimai#325]
Hi everybody :), 

For now, if we want to add a single activity to multiple projects, the same activity must be created several times for each project.
It would be nice if we could for example when creating an activity, check in the list of projects those who will have this activity attributed, like this: 

![kimai_1](https://user-images.githubusercontent.com/24936778/46016221-81517880-c0d4-11e8-9877-524892fd7d1f.jpg)

**Comment by adis1987** [comment]
Or by default all projects will have all activitys, like in v1. I would be grate to select project first in dropbox and after that select pre-defined activity.

**Comment by AlxBe** [comment]
I think this feature would be essential, as we start an new project with a standard-activity (e.g. "project work"). What happens during upgrade if you used shared activities in kimai 1?

**Comment by kevinpapst** [comment]
@AlxBe check the documentation for this info. 
@all Follow the PR #259 for global activities

**Comment by kevinpapst** [comment]
Work on global activities is almost finished: now you can either assign an activity to one project (so its only selectable in combination with that customer and project) or you can leave the project empty - in this case the activity can be used in combination with every project.
As this was a major rewrite of some of the core functions, I could use some help. If you are willing to participate: check the branch from the PR #259 and give it a try. 
You could even test the update by creating a copy of your production database and use that for the migration. DON'T test with your production database yet! My tests were successful, but I want to gather some more feedback before I publish it for everyone.
