### ISSUE TITLE
Excel Output not containing data

### ISSUE THREAD

**Issue by Richigeht** [kimai/kimai#327]
**Describe the bug**
Excel is not containing data time entries. 

**To Reproduce**
1. I added a new entry.
2. Configured Excel output.
3. Printed the invoice. 

**Expected behavior**
Having my data in for the customer but the excel is not containing entries. 

**Screenshots**
![2018-09-25_15-48-54](https://user-images.githubusercontent.com/21252095/46018734-d85a4c00-c0da-11e8-9bbf-7faa7997b5b3.png)

[spreadsheet.xlsx](https://github.com/kevinpapst/kimai2/files/2415492/spreadsheet.xlsx)

**Comment by kevinpapst** [comment]
Works on the Demo:
https://demo-v2.kimai.org/de/invoice/?template=7&user=&begin=2017-09-01&end=2018-09-30&customer=1&project=

And here:
https://demo-v2.kimai.org/de/invoice/?template=8&user=6&begin=2018-09-01&end=2018-09-30&customer=6&project=179&activity=1385

But not here:
https://demo-v2.kimai.org/de/invoice/?template=8&user=6&begin=2018-09-01&end=2018-09-30&customer=6&project=179&activity=1384

There is definitely a bug in spreadsheet invoices that contain only ONE entry.  HTML/ODT works with one entry and Spreadsheets work when you have two or more entries.

I'll look into it, thanks for testing and reporting!

**Comment by kevinpapst** [comment]
Fixed bug in PR #328 - will merge it to master later this day

**Comment by kevinpapst** [comment]
Oh, thats the problem, let me quote from the git docu:

> What are the differences between git pull and git fetch?
> Answer:
> In the simplest terms, git pull does a git fetch followed by a git merge.

If you don't change anything locally, simply use `git pull` the next time.
But for now, I haven't merged the changes, so neither `git fetch` nor `git pull` will do anything.

**Comment by Richigeht** [comment]
Hi
Well I tried git pull as well and it said it would have been updated to master but still the sql script wasn’t updated though! 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by kevinpapst** [comment]
You cloned directly instead of using a fork, right?
Probably try a `git pull origin master`.

**Comment by Richigeht** [comment]
Aye and thought I tried that. Using gitlab for another environment and also using remote pull etc. 
well anyway will have a look later if it works or not. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet
