### ISSUE TITLE
Total Invoice Rounding Issue 

### ISSUE THREAD

**Issue by Elte156** [kimai/kimai#329]
I have changed the display settings to conform to USA standards
Dates using 'MM/DD/YYYY'
Currency Symbol '$'
Decimal Separator '.'

I have one entry in my timesheet for a project
General Tab
Day: 01.03.2014 - 01.03.2014
Time: 14:10:01 - 14:21:40
Duration: 00:11:39

Budget Tab
Rate by hour: 30.00
Everything else is default and I don't touch.

Now when I go to the main Invoice Tab:
I "Create" an invoice with:
Short Inv: enabled
Round time: 0.1h

The ODT file that it creates shows "0.20 h   $5.99"
20% of $30.00 is supposed to be $6.00

**Comment by kevinpapst** [comment]
If this is still a problem, please open a PR with what you think is the right way of calculating the rates and times.
