### ISSUE TITLE
Admin Setting Date_Format_0 not being used

### ISSUE THREAD

**Issue by Elte156** [kimai/kimai#330]
The admin setting date format 0 is not being used at all.
"Date format for the field below the timespan (notation for strftime())"

This corresponds to the db field `date_format_0` in the `configuration` table.
$kga['date_format'][0] is never referenced.

The field below the timespan; is this the date that is on the header of each page?
Sat 03.01.2014   Display Smallclock 17:47   Display Eye 0:28

**Comment by kevinpapst** [comment]
It is used now again for jquery datepicker in extensions (currently only invoices)
