### ISSUE TITLE
API: Add filtering/sorting/limits

### ISSUE THREAD

**Issue by nikolauskrismer** [kimai/kimai#333]
**Is your feature request related to a problem? Please describe.**
If I want to find the latest id of an entity used by kimai2, I need to retrieve all the entities, sort them by a date/id and then filter. If this would be done within the API, responses could be much smaller.

**Describe the solution you'd like**
GET Parameters in the API calls. Something like: "api/activities?sortBy=date&sortOrder=DESC&limit=2"
In this case only the two newest activities would be returned.

**Describe alternatives you've considered**
Another way of filtering would less SQL inspired, but more related to query by example. Something like "api/activities?date=>2018-08-08&limit=2" could also achieve something similar (however, i prefer the sql inspired solution :-)).

**Additional context**
Personally this is not mandatory to work with the API, but for larger systems I think that responses will be quite big without this feature (and so the API might become unusable).

**Comment by kevinpapst** [comment]
What is the use-case behind "the latest item"? 
Regarding the implementation: I will re-use the filter actions that are available as toolbars. If its required, I would add more filters (like sorting) there.

**Comment by nikolauskrismer** [comment]
The use case behind it is that I want to implement a "pause" or "end" activity button.
For that I would retrieve the last item that is still open and then close it (by adding an end_date)

**Comment by kevinpapst** [comment]
I will add filters nevertheless, but for convenience I would propose a `/timesheet/active/` endpoint, which will give you all running records for the current user.
