### ISSUE TITLE
Activities just Duration

### ISSUE THREAD

**Issue by jmucks** [kimai/kimai#334]
A great Feature would be to have certain activities showing jsut the duration on the Invoice.

**Comment by kevinpapst** [comment]
Thanks for registering and posting ideas 👍 

It would be good, if you could collaborate a bit more detailed on this request, as I have problems understanding your request. Can you try to put the idea from your head into a couple of sentences, so everyone - including me -  knows what you actually want ;-)

**Comment by jmucks** [comment]
Hi 

My idea is to have the posibility to create a activity that only shows the total duration in the  definied Time period on the invoice. 
The other Tasks shown normal with Date and Time. 

Idea is to create a summary of Short aktivites. 

For example you have 10 Times logged an certain activity each 5 minutes. These are shown in the invoice as one 50 minutes "article" without start ans end Time or Date



Sorry for the english. Hope it clears it up

**Comment by kevinpapst** [comment]
I created a pull request, that will add an invoice calculator which groups entries by their activity.
If you want to test it: #380 - checkout the branch, clear the cache and create an invoice with it.
