### ISSUE TITLE
Error thrown while running command "kimai:user:create 

### ISSUE THREAD

**Issue by tarekfellah** [kimai/kimai#3360]
**Describe the bug**
I followed your documentation to install Kimai 2 on a Cpanel hosting (WHM/Centos 7) 
For the command 
bin/console kimai:install -n

Kimai installation running ...
==============================
I got:
Database `dev8_kimai2` for connection named default already exists. Skipped.
[notice] Migrating up to DoctrineMigrations\Version20220531145920
After:
bin/console kimai:user:create username xxxxx@xxxxxx.com ROLE_SUPER_ADMIN
Please enter the password:
11:46:24 CRITICAL  [console] Error thrown while running command "kimai:user:create xxxxxx 'xxxxx@xxxxxx.com' ROLE_SUPER_ADMIN". Message: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.alias AS alias_2, t0.registration_date AS registration_date_3, t0.title AS title_4, t0.avatar AS avatar_5, t0.api_token AS api_token_6, t0.auth AS auth_7, t0.username AS username_8, t0.emailAS email_9, t0.account AS account_10, t0.enabled AS enabled_11, t0.password AS password_12, t0.last_login AS last_login_13, t0.confirmation_token AS confirmation_token_14, t0.password_requested_at AS password_requested_at_15, t0.roles AS roles_16, t0.color AS color_17 FROM kimai2_users t0 WHERE t0.email = ? LIMIT 1' with params ["xxxxx@xxxxxx.com"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.account' in 'field list'" ["exception" => Doctrine\DBAL\Exception\InvalidFieldNameException^ { …},"command" =>"kimai:user:create xxxxxx 'xxxxx@xxxxxx.com' ROLE_SUPER_ADMIN","message" => """  An exception occurred while executing 'SELECTt0.id AS id_1, t0.alias AS alias_2, t0.registration_date AS registration_date_3, t0.title AS title_4, t0.avatar AS avatar_5, t0.api_token AS api_token_6, t0.auth AS auth_7, t0.username AS username_8, t0.email AS email_9, t0.account AS account_10, t0.enabled AS enabled_11, t0.password AS password_12, t0.last_login AS last_login_13, t0.confirmation_token AS confirmation_token_14, t0.password_requested_at AS password_requested_at_15, t0.roles AS roles_16, t0.color AS color_17 FROM kimai2_users t0 WHERE t0.email = ? LIMIT 1' withparams ["xxxxx@xxxxxx.com"]:\n  \n  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.account' in 'field list'  """]

**To Reproduce**
1. run command bin/console kimai:install -n
2. Database `dev8_kimai2` for connection named default already exists. Skipped.
[notice] Migrating up to DoctrineMigrations\Version20220531145920
4. bin/console kimai:user:create username xxxxx@xxxxxx.com ROLE_SUPER_ADMIN
5. CRITICAL  [console] Error thrown while running command "kimai:user:create xxxxxx 'xxxxx@xxxxxx.com' ROLE_SUPER_ADMIN". Message: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.alias AS alias_2, t0.registration_date AS registration_date_3, t0.title AS title_4, t0.avatar AS avatar_5, t0.api_token AS api_token_6, t0.auth AS auth_7, t0.username AS username_8, t0.emailAS email_9, t0.account AS account_10, t0.enabled AS enabled_11, t0.password AS password_12, t0.last_login AS last_login_13, t0.confirmation_token AS confirmation_token_14, t0.password_requested_at AS password_requested_at_15, t0.roles AS roles_16, t0.color AS color_17 FROM kimai2_users t0 WHERE t0.email = ? LIMIT 1' with params ["xxxxx@xxxxxx.com"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.account' in 'field list'" ["exception" => Doctrine\DBAL\Exception\InvalidFieldNameException^ { …},"command" =>"kimai:user:create xxxxxx 'xxxxx@xxxxxx.com' ROLE_SUPER_ADMIN","message" => """  An exception occurred while executing 'SELECTt0.id AS id_1, t0.alias AS alias_2, t0.registration_date AS registration_date_3, t0.title AS title_4, t0.avatar AS avatar_5, t0.api_token AS api_token_6, t0.auth AS auth_7, t0.username AS username_8, t0.email AS email_9, t0.account AS account_10, t0.enabled AS enabled_11, t0.password AS password_12, t0.last_login AS last_login_13, t0.confirmation_token AS confirmation_token_14, t0.password_requested_at AS password_requested_at_15, t0.roles AS roles_16, t0.color AS color_17 FROM kimai2_users t0 WHERE t0.email = ? LIMIT 1' withparams ["xxxxx@xxxxxx.com"]:\n  \n  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.account' in 'field list'  """]

**Additional context**
 - Kimai version: 1.20.4
 - PHP version: 7.4.29
 - Device: Centos 7
 - Browser Firefox 101.0.1
 - Composer : 2.3.7

**Comment by kevinpapst** [comment]
Drop the database before running the command or make sure that there is no old data included. This error can only happen with invalid updates/installations and or when someone tried to be smarter then the system.

**Comment by tarekfellah** [comment]
I droped the database 
php bin/console kimai:install -n

Kimai installation running ...
==============================

Could not create database `dev8_kimai2` for connection named default
An exception occurred while executing 'CREATE DATABASE `dev8_kimai2`':

SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'dev8_user_db'@'localhost' to database 'dev8_kimai2'

 [ERROR] Failed to create database: Failed creating database. Check your credentials in DATABASE_URL

**Comment by kevinpapst** [comment]
The error is in front of you: Access denied for user dev8_user_db

Please ask in Stackoverflow or anywhere else for errors that are not Kimai related.
