### ISSUE TITLE
Questions about Kimia2

### ISSUE THREAD

**Issue by wolftone1916** [kimai/kimai#338]
I just have  a few questions about the system now that I've been able to explore it a bit. I know it's still early in development so these may have been covered or already in documentation so I apologize in advance if they are. I unfortunately couldn't find anything about it. I also cannot seem to find the documentation page that I had at one point that covered various things in kimai 2.

So, first question. In Kimai the original, you could simply click a button to start, and then click it to stop (especially on the mobile version). On this one, you have to select the date, and time the job is finished. Is there either a setting that can be changed or possibly a plan to add the option in the future to use just a one click button to start and stop the clock in or time recording? I ask this because we have a position at our company called Brand Ambassadors. They go out in the field and demo product. This is a decently high turnover position and requires things to be simple as possible. This is the reason the one click record and stop is more of a reasonable option for what we need. As well, sometimes they go over a half hour or so and it would be better for them to not have to go back in and edit the times.

So, second question. When the user does start the time, it gives the option for the user to pick their rate of pay. For us, this is an issue and I was wondering if there's any way to either remove that field or set it so that's not an option.

Thirdly, in Kimai original, an admin could set specific privileges for each user to do things like export times, to see other tabs like the admin panel, and things like what time sheets they can see. I am sure this might be a plan to add in later but I'm just curious for myself to have a plan of action as well. We have different level of admins that we would like to have access to different things. Cheers and thank you for the help and info!

**Comment by wolftone1916** [comment]
Here's what it looks like via my mobile device:

![thumbnail](https://user-images.githubusercontent.com/2268529/46550627-3df8c600-c89b-11e8-8cb8-0a079628e865.jpg)

**Comment by wolftone1916** [comment]
> This worked before because you could globally selected activity, project and customer. This concept is not migrated to Kimai 2 and I am not sure if I will come.
> I do understand the convenience behind that one-click though, thats why there are several one-click ways of starting and stopping one of your last activities.
> 
> If you had to work on many different projects and activities in Kimai 1, you had to select them as well before hitting "Start". You could only hit Start when you were still working on the "same job".
> 
> In Kimai 2 you hit "replay" on one of your last activities: either from the "last activities" dropdown in the upper right toolbar or directly from the timesheet. It's the same one-click behaviour, you just have to get used to other buttons.
> If you want to start a completely new activity, then you click the global arrow. If you have a good idea how that could be further improved (e.g. a modal selection) then I am happy to hear add it!
> 
> The same goes for running time-records: top them with one-click from the timesheet or from the "running entries" dropdown.

Ahh, I see now so basically they would only need to start or rather setup the job they are doing once and can just keep restarting that job via click to start and then click to stop it as they need later on. I like that actually. I could honestly start and stop the preliminary times for them to make it easier for them to handle later on. Loving it now that I'm figuring it all out. Thank you so much for all the prompt replies and help.

**Comment by kevinpapst** [comment]
I'll keep this ticket open for improving the documentation

**Comment by kevinpapst** [comment]
Just for documentation, this is now also explained at:
https://github.com/kevinpapst/kimai2/blob/master/var/docs/timesheet.md
