### ISSUE TITLE
Time Ranges for rates

### ISSUE THREAD

**Issue by mr2017x** [kimai/kimai#3396]
Good Morning,

i think we all have to face slowly the troubles of today. Price increases at all points. So i thought about that and it came up, that this needs also be done on my side. So i know that there is a recalculation tool for rates in kimai i think there is a need of prticular hourly rates like from 1.1.2021 to 1.1.2022 and then since 2.1.2022 active (which newer times are calculated with). 

I assume this is a bigger move, but i want to request it as a feature for tommorow as i think it could be relevant for calculated hours money amount and put it into discussion.

Thanks

**Comment by kevinpapst** [comment]
i have no plans to add such a feature
