### ISSUE TITLE
Upgrading kimai2

### ISSUE THREAD

**Issue by wolftone1916** [kimai/kimai#340]
Running into issues trying to update. So, I'm using Git Bash to do the update locally and then upload the files like I did with the install. Unfortunately, I keep getting errors trying that. When I try to run:

git pull origin master
 It gives me the error: fatal: Unknown index entry format 65720000
 I'm in the directory kimai2. I tried just to see on the next command:

sudo -u www-data composer install --no-dev --optimize-autoloader
And it gave the error bash: sudo: command not found.

So, question on handling this instead of trying to figure out why these errors are happening, would it be possible to just do another local install and upload those files like I did at the start and just make sure my .env file calls to the same database or will that cause me issues?

**Comment by kevinpapst** [comment]
Just try the command `composer install --no-dev --optimize-autoloader`.
The other stuff in front of the command is only required on a server.
**BUT:** you need to update your database, which is currently only possible via the command line.
So the only chance to do this is to copy the database from your server to your local machine, execute the update and then import this database back on your server.

I think its better to wait a couple of days, I will try to create an upgrade script to handle this in the next days.

**Comment by wolftone1916** [comment]
> Just try the command `composer install --no-dev --optimize-autoloader`.
> The other stuff in front of the command is only required on a server.
> **BUT:** you need to update your database, which is currently only possible via the command line.
> So the only chance to do this is to copy the database from your server to your local machine, execute the update and then import this database back on your server.
> 
> I think its better to wait a couple of days, I will try to create an upgrade script to handle this in the next days.

Sounds good mate, cheers and thank you :)

**Comment by kevinpapst** [comment]
Sorry, there is currently no time for any support scripts. I will concentrate on Kimai first.
