### ISSUE TITLE
failed to send testmail

### ISSUE THREAD

**Issue by trueshanti** [kimai/kimai#343]
**Describe the bug**
testing MAILER via `bin/console -vv swiftmailer:email:send`
results in error :
`[2018-10-06 15:48:20] app.ERROR: Exception occurred while flushing email queue: Expected response code 354 but got code "503", with message "503-All RCPT commands were rejected with this error: 503-R1: HELO should be a FQDN or address literal (See RFC 2821 4.1.1.1) 503 Valid RCPT command must precede DATA " [] []`

**To Reproduce**
1. use bin/console -vv swiftmailer:email:send
2. See error

**Expected behavior**
test email sent 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 62.0.3

**Additional context**
straight after install
MAILER_URL=smtp://localhost:25?encryption=&auth_mode=

**Comment by kevinpapst** [comment]
I don't think this is a Kimai issue. A test for me reveals:
```
# bin/console -vv swiftmailer:email:send
SwiftMailer's Interactive Email Sender
======================================
 From:
 > xxx
 To:
 > yyy
 Subject:
 > Test 123
 Body:
 > foo bar
 [OK] 1 emails were successfully sent.
```
Please read https://github.com/kevinpapst/kimai2/blob/master/var/docs/emails.md and all links.
I guess either your SMTP is mis-configured or your mail configuration is wrong.

**Comment by trueshanti** [comment]
our MTA is generally well configured 

in the kimai-config i defined `MAILER_URL=smtp://localhost:25?encryption=&auth_mode=` according to docu , but I might miss a detail around the variables `encryption=` and `auth_mode=` .. i cannot find hints on a correct syntax here - that might be my "BUG" maybe .. 
can you provide an example here maybe .. tnx

**Comment by trueshanti** [comment]
the according exim-log complains about the swiftmailer's syntax is seems:
```
2018-10-06 14:10:50 H=localhost [127.0.0.1] F=<projects@xxxx.tld> rejected RCPT <cr@xxxx.tld>: R1: HELO should be a FQDN or address
 literal (See RFC 2821 4.1.1.1)
2018-10-06 14:10:50 H=localhost [127.0.0.1] F=<projects@xxxx.tld> rejected RCPT <cr@xxxx.tld>: R1: HELO should be a FQDN or address
 literal (See RFC 2821 4.1.1.1)
2018-10-06 14:10:51 H=localhost [127.0.0.1] F=<projects@xxxx.tld> rejected RCPT <cr@xxxx.tld>: R1: HELO should be a FQDN or address
 literal (See RFC 2821 4.1.1.1)
2018-10-06 14:10:51 H=localhost [127.0.0.1] incomplete transaction (QUIT) from <projects@xxxx.tld>
```

**Comment by kevinpapst** [comment]
I'd like to, but I can't, as I haven't used it with a local SMTP by now.
All I can help with is to point you to the documentation:
https://symfony.com/doc/current/reference/configuration/swiftmailer.html

This is talking about the exact same cause I guess:
http://forum.directadmin.com/showthread.php?t=56287

Probably we need to set the `local-domain`: 
https://symfony.com/doc/current/reference/configuration/swiftmailer.html#local-domain

Try to put something like this:
```yaml
swiftmailer:
    local_domain: 'kimai.local'
```
into the file `config/packages/local.yaml`and execute `bin/console cache:clear` afterwards.

**Comment by trueshanti** [comment]
FYI .. i tried `sendmail://localhost` without success .. but full featured `smtp:// `with a dedicated user for outgoing mails worked so far: 

`MAILER_URL=smtp://projects-mx@xxxx.tld:***********@mx.xxxx.tld:587?encryption=tls&auth_mode=plain`

thank youmuch for the hints .. now i am back to #344

**Comment by kevinpapst** [comment]
Just for reference, this is now also explained at:
https://github.com/kevinpapst/kimai2/blob/master/var/docs/emails.md#troubleshooting

**Comment by trueshanti** [comment]
sidenote:  

need a ":" between $user + $password in URI 

password should not contain 'breaking characters' like "&@:" 

best regards 

-c- 

Am 2018-10-07 18:35, schrieb Kevin Papst:

> Just for reference, this is now also explained at:
> https://github.com/kevinpapst/kimai2/blob/master/var/docs/emails.md#troubleshooting

**Comment by kevinpapst** [comment]
Thanks, I'll fix that typo!
