### ISSUE TITLE
invalid CSRF-Token

### ISSUE THREAD

**Issue by trueshanti** [kimai/kimai#344]
**Describe the bug**
having recieved a passwort-reset-URI , follwing it results in a CSRF-Error

**To Reproduce**
1. Go to 'forgot password'
2. recieve mail and click on the confirmation-URI
3. kimai-installation complains about invalid CSRF-Token

**Expected behavior**
beeing able to set new password

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 62.0.3

**Comment by kevinpapst** [comment]
Thanks for the report @trueshanti 

I cannot reproduce the bug you mentioned. How long did you wait wit clicking the link? 
AFAIK there is a time-limit, but I am not sure.
 I could click the link and submit the form, but then I ran into another bug:
```
[2018-10-06 21:27:53] request.CRITICAL: Uncaught PHP Exception 
Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "fos_user_profile_show" as such route does not exist." at /kimai2/var/cache/prod/srcProdProjectContainerUrlGenerator.php line 114 
{"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_profile_show\" as such route does not exist. at /kimai2/var/cache/prod/srcProdProjectContainerUrlGenerator.php:114)"} []
```
I'll look into it.

**Comment by kevinpapst** [comment]
Fixed in the PR #345. Could you test if that works for you as well?

**Comment by kevinpapst** [comment]
Another idea: did you click the link in the email on the same device where you requested the reset?
I just read on Stackoverflow that this could be a problem.

**Comment by trueshanti** [comment]
i applied 6426e18fa89cdeea055a6081e913b6d89ab3c279 , i also changed 
`TRUSTED_HOSTS=localhost,projects.xxxx.tld` in `.env` , but no change.

**Comment by kevinpapst** [comment]
Can you login and use any other form?

**Comment by trueshanti** [comment]
i sadly cannot .. thats how it all began for me .. fresh install > adminlogin failled > then i ran into this issue . sorry for beingso  lame with symfony (rookie) :-p .. if only i could imagine howto make logging globally more verbose (atm its just quiet) i could tell more details

**Comment by kevinpapst** [comment]
Please try to create a user from the command line instead of using the forms:
```
bin/console kimai:create-user username admin@example.com ROLE_SUPER_ADMIN
```
If that doesn't help, enable the `dev` mode by changing it in `.env` file and clear the cache afterwards. You will see a debug toolbar after reloading the page that might help you finding the cause for the error.
Did you already try to `chmod -R 777 var/`? Probably the cache and session folders are not writeable, then the CSRF token cannot be stored and will always be wrong.

**Comment by trueshanti** [comment]
`[OK] Success! Created user: pradmin` .. but fails to login .. i am gonna start a fresh dev-instance and rework this .. i will update you on my findings .. Thank you

**Comment by trueshanti** [comment]
i wish i hade something better to say, but i reinstalled from scratch and no CSRF issues at all .. thats embarassing , ok . sorry for wasting your time :-(

but since i ran into another issue in the passwordreset we hear again.
