### ISSUE TITLE
Missing translation strings in Kimai 0.9.2

### ISSUE THREAD

**Issue by andres99** [kimai/kimai#346]
The following English strings exist in Kimai 0.9.2 stable but are missing from the respective translation file en.php:

(1) (under "Admin Panel - Database"): You don't have permission to see this information ...
(2) (in the Invoice tab): Invoice Form
(3) (linked from "Admin Panel"): Database backup utility
(4) (after an update check from "Admin Panel"): You are running the latest version
(5) (in the Budget tab): items in budget.

**Comment by laplix** [comment]
Personal opinion here. You should « at least » support the version before the current one.

Suggestion : Provide a LTS (Long Lasting Support) version every 2 or 3 years for, let's say, 5 years.

You provide enhancements for the 2 or 3 years (you choose) and bug fixes for the full 5 years . See the Ubuntu / Linus  Mint strategy for more details.

Businesses depend on you (me too). The need stability. This would go a « very » long way into adopting your beautiful software.

**Comment by simonschaufi** [comment]
we are currently working on a 1.0 release which will be some kind of LTS but we don't have the time to make sure older versions get bugfixes. This is open source software and anyone can contribute!

**Comment by kevinpapst** [comment]
Hey @laplix, thanks for your feedback! You are right with your opinion, but a missing (or hard coded) translation string does not truelly match my understanding of an urgent usecase for patching older version ;-)
Indeed, if this would be a security implication, we would need to talk about a solution.

@simonschaufi Did you check that all the named points from @andres99 list are translated in master? If not I would still consider this a Feature Request and re-open this issue.

**Comment by simonschaufi** [comment]
indeed, labels are missing in master. wonder where they got lost....
