### ISSUE TITLE
Tracking Expenses

### ISSUE THREAD

**Issue by amplicade** [kimai/kimai#351]
Hi,

will version 2 also support tracking expenses? Not sure if I missed this information somewhere.

BR
Tac

**Comment by kevinpapst** [comment]
Hi @TAC911 ! Now that we have a feature request, people can vote for it.

**Comment by dude1756** [comment]
Expenses would be great with two more features compared to v1:
1.) they should be editable by superuser incl. changing user (like for time tracking)
2.) it should be possible to distinguish between two types of expenses: a) fixed costs and b) travelling costs per km (it is possible in v1 by changing field label and using factor field)

**Comment by TAC911** [comment]
It would also be good to have the chance to upload attachments, e.g. invoices. A preferred option would be to allow to provide the options connect a cloud storage service (Dropbox, Drive or OneDrive) or a fileserver (AWS Bucket, Fileserver, ...).

**Comment by kevinpapst** [comment]
I thought about extending expenses with some kind of article/product database.
You first create articles like "logo design" or "traveling". When you create an expense, you choose not only date/time .. but also a previously created product and the amount. 
That would allow for more use-cases, as many businesses sell hardware in combination with their work. But they can't add each article every time they sell it.
@TAC911 that would be a new feature request, but I'll come back to that once I start working on expenses.

**Comment by dude1756** [comment]
Would be nice if users could track traveling costs. I.e. by just allowing multiple "currencies" within one project of which one could be "km" would be sufficient. Or how should travel costs be written to invoice?

**Comment by labor4** [comment]
heart vote counts tripple

**Comment by kevinpapst** [comment]
> heart vote counts tripple

Hahaha, you should still vote with 👍 otherwise the sort in the issue list doesn't count it

**Comment by sollermun** [comment]
I think it is critical that expenses be tracked. Until this feature is added, I cannot migrate from Kimai v.1

**Comment by labor4** [comment]
Just checking back to tell you how good it feels that this thing is sorted at the top (by likes). 
Further, I'd like to point out, that it is ALSO sorted top when ordered by heart...!

cheers
m

**Comment by kevinpapst** [comment]
So I have some good and bad news for you:
- Expense tracking is now available for Kimai 1.3
- It is _only_ available as paid plugin (considering that expense tracking is only used for commercial purposes and that I do have to live from my work)

You can test expense tracking in the [Plugin demo](https://www.kimai.org/demo/).
And here is the shop page: [Expense plugin](https://www.kimai.org/store/expenses-bundle.html)

What does it include:
- Expenses are sorted into free configurable categories, which consist of a `name` and a `visibility` flag (for groups like "Traveling", "Hardware", "Supplies","Training")
- Each expense is linked to a `category`, `user`, `project`, `customer`, `activity` and has the fields: `begin date`, `end date`, `description`, `sum`, `multiplier`, `refundable`, `exported`

Expenses which are marked as `refundable` are included in invoices. Thanks to the `exported` flag and the new features in invoices, you can be sure that expenses are included in one invoice only.

As you have a `sum` and `multiplier` field you can track:
- fixed prices, eg 130$ = sum 130$ and multiplier 1 
- unit prices, eg 550€ for 15 items 50€ each = sum 50€ and multiplier 15
- traveling costs, eg 41,85€ for 139,5km = sum 0.3 € and multiplier 139,5

This is just the first release and I plan to extend it further with your input!

To make your decision simpler, I created a coupon that can be used until the end of the month, which gives you 10€ off the price. You can enter it in the payment form: `0rsmb2c`.

I am closing this issue, as expense tracking is now available. But we can still discuss here, if you have any question regarding the plugin features.
