### ISSUE TITLE
Export Timesheet using filters based on customer, project and users

### ISSUE THREAD

**Issue by abhishio** [kimai/kimai#353]
**Is your feature request related to a problem? Please describe.**
In Old Kimai, we can export timesheet using filters like customers, Projects, Project Activities and users or using many combinations. This feature is very useful when more than one resource is working on the same project and the same activity or to send the timesheet of a single Project which contains every user's work.  

**Describe the solution you'd like**
Above features is available in the Old Kimai, where we can filter out a task based on the projects, users, customer or activities or using multiple options in multiple features. This feature is very useful to us and many other teams.

**Comment by kevinpapst** [comment]
The invoice functionality has most of the functions that you mentioned.
Can you collaborate on the exact functionality that is missing?

**Comment by kevinpapst** [comment]
Closing this in favor of #355 
I think both are about the same feature request: selected an arbitrary amount of users/projects/activities
