### ISSUE TITLE
Better storage of passwords in DB - correct usage of salt/one-way-function

### ISSUE THREAD

**Issue by scolytus** [kimai/kimai#355]
Currently _kimai_ stores passwords in the DB in the following way:
`data = md5($kga['password_salt'].$password.$kga['password_salt'])`

Since `$kga['password_salt']` is a site-static value, this is not a _salt_ in a cryptographic way, it's closest to the concept of _pepper_ instead.

While also a _pepper_ may have some security enhancing effects, it's not a suitable replacement for a _salt_. _Salts_ need to be assigned per user and unique in the "salt-space" of a site.

It is also bad practice to use hash-functions as _md5_ and the _SHA_-families for storing passwords. Those are designed to be fast, which ultimately aids an attacker, but isn't really needed when authenticating an user. It is better to use password encryption schemes which are designed for this special purpose.

The PHP FAQ contains a nice article[1] about this issue.
Furthermore, PHP 5.5 contains a high-level password handling API, addressing this issues.[2]

What I propose:
- Create 2 password handling functions for encoding and verifying passwords. This leads to a single point in the code where password handling is done. Currently there are 11 lines of code all over the place.
- Use a per user salt. The `password` field in the DB is already wide enough to hold all necessary data.
- Use a secure password storage scheme instead of `md5()`. This needs a bit of investigation of compatible PHP versions. There is a backport[3] of the new password API to PHP 5.3.7. Debian Squeeze for example just has 5.3.3, thus breaking compatibility.

Overall, this is not an immediate security threat. However, in my opinion such things should be done properly, especially when personal data of users are involved.

[1] http://php.net/manual/en/faq.passwords.php
[2] http://php.net/manual/en/ref.password.php
[3] https://github.com/ircmaxell/password_compat

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
