### ISSUE TITLE
Add introduction text for invoices

### ISSUE THREAD

**Issue by LiaraAlis** [kimai/kimai#3555]
I would like it if it were possible to define an introduction text in an invoice template that is output before the items are listed.
I imagine this is how it is done with payment terms as well.

@kevinpapst What do you think? I like to make a PR for it, but I would save my time if you don't want it. 😅

**Comment by kevinpapst** [comment]
No, I am against adding more fields. We need to find a way to add custom fields for templates as meta fields to the invoice. I have a couple of ideas, but all of them are a bit ugly. Actually I am thinking about this problem for a very very long time...

1. Templates should be able to define the additional fields that they support, so they are self-contained in one file only
2. Kimai should be able to understand which field can be configured, to render them in the invoice template form
3. I'd say we concentrate on Twig templates only.  
  -  DOCX templates can be customized directly in Word. But passing the variables down to the DOCX parser is no problem as well.

How?

We could either add a simple parser to strip out comments like
```
{# VARIABLE "introductionText" "text" #}
```
or we utilize Twig, check if a dedicated block named `setup_template_variables` exist and then render that special block to find out which variables are supported by passing in some simple DTO, which works like the pdfContext:
```
{% block setup_template_variables %}
  {%- set introductionText = variables.add('introductionText', 'text') -%}
{% endblock %}
```
Now these variables could be added dynamically to the invoice template form.

**Comment by LiaraAlis** [comment]
I like the idea to add additional fields, it guarantees the best flexibility.
But where do you want to define the content of this fields? In the template?
In my eyes it is very annoying if you want to make this texts translatable. You need to modify the core files and you're running into problems with the next update.

**Comment by kevinpapst** [comment]
Translations are completely optional and the translation plugin could be used for that.
Or you ship an additional translation file that users have to coy into their installation?

**Comment by kevinpapst** [comment]
Plugin authors can manipulate the invoice model before printing.
You could simply add some (translated) text to the payment terms.
If that is not enough, I need more infos what is needed.
