### ISSUE TITLE
Discourse forum

### ISSUE THREAD

**Issue by Ark74** [kimai/kimai#356]
Hi!
I just found about kimai2, looks great.

**Is your feature request related to a problem? Please describe.**
I've found that discussions aren't pretty fluid on github, also looking for support at an operational level not coding or bugs.

**Describe the solution you'd like**
My request would be in concern of the website, adding a discourse instance to ease and boost participation for forum like participation.

**Describe alternatives you've considered**
Discourse, it's fairly easy to setup, maintain and comes with valuable features like an app already.

**Additional context**
https://www.discourse.org/
I would suggest the docker setup.

**Comment by kevinpapst** [comment]
Thanks for the inspiration @Ark74. There is also a Slack channel, which I never announced anywhere, as I am not yet sure whether this brings any benefit by now. As long as the community is not large enough, you will probably have a much higher chance to get an answer here than in any chat/forum.
I'll leave this open so we can discuss different options.

**Comment by Ark74** [comment]
I've seen on many projects this combination (github+discourse) and it helps a lot to have a better approach to users on a expertise level.

If they are more technical and code skilled, then github would become the best choise for bugs and development.
Then discourse for more of a general consultation and non-code related stuff also for new users and people that are more forum related.
But it is also true, if the user base is small then splitting the areas may not being the best idea.

Cheers!

**Comment by kevinpapst** [comment]
Thanks for the suggestion, but I don't have plans to integrate discourse.
Maybe Slack later on, but for now GitHub is more than enough work...

**Comment by Hacking-Fortnite** [comment]
Hey can somebody help me out.

**Comment by Hacking-Fortnite** [comment]
I am not super familiar with this website because i have only been using it for a couple of days.  I was wondering if any of you knew how to connect your github account to epic games so i can gain acces to the source codes of ureal engine 4.
