### ISSUE TITLE
Option for setting default calendar view

### ISSUE THREAD

**Issue by robinrosenstock** [kimai/kimai#359]
**Is your feature request related to a problem? Please describe.**
When clicking on the calendar button (in my times) you see the month view, but I would like to see the week view as default.

**Describe the solution you'd like**
I would like an option for setting the default calendar view (month, week or day)

**Describe alternatives you've considered**
alternative: remember the last view, when clicking on the calendar button.

**Comment by kevinpapst** [comment]
Thanks for the feature request, will do.

**Comment by kevinpapst** [comment]
@geniusupgrader if possible: please check/test the PR #363 and let me know if thats what you wanted

**Comment by geniusupgrader** [comment]
I've tested it, though I haven't looked at the code..
So far really nice! All works as expected. But I do want to give some feedback.

There are 5 options:

- month
- agendaWeek
- agendaDay
- basicWeek
- basicDay

I really don't know what basicWeek and basicDay are for? And I can not set them in the calendar view (there are only month, week and day), which is not best for a user perspective and UI.
The second annoyance (for me) is the naming of the terms: „month, agendaWeek, agendaDay“. Why not just „Month, Week, Day“?
One other thing I've noticed, while testing, is that the options page is a bit hidden. I understand that the options are for the user, but its not very intuitive to click/edit the user to access the options. Maybe I should open a new feature request to add a new menu entry for the options?

**Comment by kevinpapst** [comment]
Thanks for the first feedback!
I removed the two view types for now, as they don't seem to add much benefit and also don't have buttons in the calendar itself. And I also translated the option keys.

Yes, please create a new Feature request for the preferences screen. 
Indeed its not intuitive for a user how to reach the own profile and the settings. That needs some improvement.

**Comment by geniusupgrader** [comment]
Thanks for updating and merging!
