### ISSUE TITLE
Data validation for register page username field.

### ISSUE THREAD

**Issue by Yw-melo** [kimai/kimai#360]
**Describe the bug**
The length of username field must longer than 4，but in our company there are many employees name is less than 4 eg Jay/Bree/Melo.
Could tell me how change the length of username filed more than 4?

**Comment by kevinpapst** [comment]
Edit `config/validator/validation.yaml` and execute `bin/console clear:cache` afterwards.
And I'll lower it to 3 for the next version.

**Comment by kevinpapst** [comment]
Fixed in master
