### ISSUE TITLE
Migrate to mysqli_ function

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#363]
As mysql function are deprecated, we need to switch to mysqli functions.

Point one: Update the used MySQL class if provided by its developer, otherwise patch it ourselves. See my question at: https://github.com/GerHobbelt/ultimatemysql/issues/1

We use some mysql functions directly in the installer. That needs to be adjusted as well. See #341

**Comment by simonschaufi** [comment]
integrated latest version from http://www.phpclasses.org/package/3698-PHP-MySQL-database-access-wrapper.html

**Comment by MetalMatze** [comment]
I just ran into the issue that kimai is not working anymore:
```
Uncaught Error: Call to undefined function mysql_connect()
```

I've updated my system to PHP7 and won't downgrade. Are there any updates for this issue?

**Comment by simonschaufi** [comment]
we don't use mysql any more so I'm sure you don't use the latest master. Please use git master to switch to mysqli
