### ISSUE TITLE
Kimai for tracking non-work-related activities (other types of activities)

### ISSUE THREAD

**Issue by robinrosenstock** [kimai/kimai#364]
**Is your feature request related to a problem? Please describe.**
I often track my non-working related things, like hobbies, my own personal projects or my sleep. When I look at the Dashboard, everything gets counted as Working Hours, which is misleading, because these types of activities are for my leisure time (especially sleep is not considered as "Working Hours").

**Describe the solution you'd like**
I would like to see, a flag for activities, which describes their type (working/leisure/sleeping). The situation now is that, every activity is regarded as some type of working activity, which can be seen by the fixed rate and hourly rate text boxes. I don't want to set a rate at all on these kind of activities! So there must be different types of activities.

**Describe alternatives you've considered**
no alternatives so far

**Additional context**
In accordance the Dashboard may need some more settings (show the statistics for my personal projects). Maybe connatural to #353. Maybe fits together with #298.
Please give me feedback and what you think about this feature request.

**Comment by jmucks** [comment]
Thinking it futher it would be great to assign team members to different activities. 

As some sort of human resource management or project management.

For example 
User A designated to work x hours on project A on Monday going to vacations the rest of the week and after this working on project b.

**Comment by geniusupgrader** [comment]
@jmucks, your suggestion is a slightly different topic, so please open a new issue on that.

**Comment by toxiclung** [comment]
> parent

This would be very useful to implement in our case. If you're still planning to do this i would suggest an approval process for sick leave or parental leave by a supervisor or other user with role for approval.

Right now we use googles form for employees to submit leave request. I think it would be great to have it integrated in Kimai.

**Comment by limitedAtonement** [comment]
I track personal time spent doing business-related things (taxes, bookkeeping, etc.) using myself as the customer and an appropriate project and activity.

**Comment by jruizaranguren** [comment]
Hi, @kevinpapst. We are interested in **sponsoring** this development. In addition to tracking holidays, sickness and other regulated scenarios typical in corporate settings, we are interested in reports where managers can review whether employees have tracked the worked time according to expected calendar. That is: work hours + sickness + paid leaves are more or less the hours expected by calendar for a team.

Could we talk about this?

**Comment by kevinpapst** [comment]
Hey @jruizaranguren please sent me an email at kevin/...\kevinpapst.de 
Nice avatar btw, it is the Explorer-Fraggle, right?

**Comment by jruizaranguren** [comment]
[Uncle Traveling Matt](https://muppet.fandom.com/wiki/Uncle_Traveling_Matt)

**Comment by marcus905** [comment]
> Hi, @kevinpapst. We are interested in **sponsoring** this development. In addition to tracking holidays, sickness and other regulated scenarios typical in corporate settings, we are interested in reports where managers can review whether employees have tracked the worked time according to expected calendar. That is: work hours + sickness + paid leaves are more or less the hours expected by calendar for a team.
> 
> Could we talk about this?

Hi, jumping here as if that sponsoring deal did not work out, also we're interested in sponsoring this development along with another one. Can we have your permission to email you at that address?

**Comment by kevinpapst** [comment]
@marcus905 sure

**Comment by jruizaranguren** [comment]
@marcus905, yes we had interest and @kevinpapst was kind enough to make us a proposal. The status from our side is that we are prioritizing other business lines and we don't expect invest on this in the very short term (althought that could change in weeks :smile:).

**Comment by kevinpapst** [comment]
I was terrible slow with answering requests, due to priority collisions. We'll see how it goes this & next time 😄

**Comment by kevinpapst** [comment]
Closing here, as this issue is a mess and points to nowhere.
