### ISSUE TITLE
Role and access management on customers and projects

### ISSUE THREAD

**Issue by jmucks** [kimai/kimai#366]
An in my  Opinion essential Feature would be to Assign different Role or Access Right per Project or Customer.

Letting ever Employe see all Customers und Projects could cause some serrios securut Issues

**Comment by kevinpapst** [comment]
True. I have plans for "teams", which will be used to handle access to projects.

**Comment by jmucks** [comment]
One not usual but possible combination to think on: 
User A is team leader in project A and have to print invoice or timesheets. 
The same User A is normal worker on project B and should not have improved access to invoice or customer data.

Just happend sometimes.

**Comment by kevinpapst** [comment]
Well, that would add a new level of complexity. I'll think about it. Yes: your use-case is totally valid... but (from my working experience) most companies tend to be not that strict and choose a "simple" approach. If someone is project lead, he must be able to step in for a sick colleague who is leading a different team. So they have a global role "teamlead". And large industries which would need such complex rulesets normally don't choose to use open source projects ;-)

But if more people need something like that, it could be a later improvement.

**Comment by jmucks** [comment]
In my opinion the easiest way would be to have a right matrix for every project. 

By default get the rights inherit from the global role set in the user management. 

Would do for normal thinking but give the possibility to specify each project different.

**Comment by kevinpapst** [comment]
What kind of permissions do you think are needed?
A user can be part of multiple teams and every team can be assigned to different projects or customers or both?
What kind of deeper permissions are required? Is a simple "visibility" check enough, so that a user can book times on it and all the rest is done via the global permissions (and if you were using v1 before, please try to forget how it worked there before you post your answer)?
What if an administrator/teamlead wants to edit the timesheet record of a user, which projects/customers can he choose? Only the ones that the user is able to see?

**Comment by JayAige** [comment]
hey kevin, is there an approximate timeline for this feature? We are currently heading to a new project where we'll assign some of the tasks to an external. He shall use Kimai for time-tracking without having access to our other projects. Currently i only see setting up a second kimai environment with seperated database as a reasonable solution.

**Comment by kevinpapst** [comment]
Sorry, but no. A first version will enter the stage soon'ish, but you know: features come when they are ready. I wouldn't recommend to make business decisions based on unpaied work.
But you can always sponsor such a feature if you want to speed things up.

**Comment by kevinpapst** [comment]
I started to work on the teams and permissions. Could you help testing?
See #996 and please leave your feedback in there, so we have everything in one place.
This does not cover all discussed points from here, but rather limits access to customers and projects right now: "one step after another" ...

**Comment by mr-jingles** [comment]
@kevinpapst Nice to see that you are picking up permissions. I have a quick general question though - I see the main use case for kimai for freelancers or consultancy companies to quickly invoice their current running projects. However my use case is more directed to the upcoming EuGH regulation:
https://curia.europa.eu/jcms/upload/docs/application/pdf/2019-05/cp190061de.pdf
So I would use kimai2 to quickly see the overtime of employees.. do you also see this as part of a future version of kimai2? Regards

**Comment by kevinpapst** [comment]
@mr-jingles please open a new issue to discuss that

**Comment by mr-jingles** [comment]
sure, #1021

**Comment by kevinpapst** [comment]
Teams are now available in master. Most certainly not all of the features discussed here were added, so please test it in the demo in the next days and write new feature requests for missing features (or bugs). 
Thanks for input!
