### ISSUE TITLE
Calendar Date Format at full hour (want 10:00 instead of 10)

### ISSUE THREAD

**Issue by simarilius** [kimai/kimai#3692]
### Describe the issue

The calendar formats the date incorrectly if the time entry does not contain a minute. e.g.: 10:00 (German Language Setting)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.29.1 

### Which PHP version are you using?

7.4

### How do you run Kimai?

Self-Hosted

### Steps to reproduce the behavior

1. Add an Timeentry starting at 10:00
2. Go to Calendar

### Screenshots

![image](https://user-images.githubusercontent.com/7790769/208475945-7cd22aff-b0b9-41dc-87ad-19d53a370ce8.png)

### Additional context

Device: [MacBook Pro 16]
Browser [ Safari 16.2]

**Comment by kevinpapst** [comment]
Fixed with new version

<img width="1704" alt="Bildschirm­foto 2023-02-23 um 11 26 01" src="https://user-images.githubusercontent.com/533162/220881140-e231128b-bcd3-4e99-ada8-288a302d5bbf.png">
