### ISSUE TITLE
Team restrictions ignored at quick start activities

### ISSUE THREAD

**Issue by simarilius** [kimai/kimai#3693]
### Describe the issue

- In the quick start dropdown / or restart activities dropdowns, it is possible to restart activities in which the User is not (or no longer) part of the team, but has entries for this activity
 
 In our case, the "Abwesenheit" customer is managed by me and the plugin and the user should only be able to see their entries (that works) but not be allowed to create any. 

In the normal dropdown, the constraint works :)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.29.1 

### Which PHP version are you using?

7.4

### How do you run Kimai?

Self-Hosted

### Screenshots

![image](https://user-images.githubusercontent.com/7790769/208477176-0ef2e5c0-608b-45de-866a-9bcb6cc74791.png)
![image](https://user-images.githubusercontent.com/7790769/208477207-d21d09a5-230b-4288-8378-127cd6e77b3d.png)

**Comment by kevinpapst** [comment]
Thanks for sharing 👍 

Will be fixed with 2.0.8
