### ISSUE TITLE
Retrieve Customer/Project/Activity internal cost by user profile

### ISSUE THREAD

**Issue by aramilialon** [kimai/kimai#3697]
### Describe the problem

Howdy!
We are configuring for some customers the cost of some resources using the "Hourly rate" feature and it works perfectly, the only "problem" we are facing is the fact that the internal cost, unless explicited, is equal to the hourly rate insered in the form.

### Describe the solution you'd like

Might it be possible to have a flag (possibly already checked) that allows the system to retrieve the internal cost from the user profile?

**Comment by kevinpapst** [comment]
Interesting approach and sounds logical to me. 
More options means more friction => maybe even make that a global configuration instead, which is turned on by default.
Yes, I like the idea!

**Comment by TGG-RPA** [comment]
How soon could this feature be worked on?  By pulling internal rate from the User Profile means:

a. Better governance to ensure rate consistency by user while still allowing override at the project level where required
b. Less input / maintenance

Good idea to have this as a global setting that is enabled by default.  Perhaps consider coding it in a manner that takes into account a rate table at the user profile level.

**Comment by kevinpapst** [comment]
This has been implemented weeks or months ago in 2.0.x
