### ISSUE TITLE
Azure SALM MultiFactor does not work

### ISSUE THREAD

**Issue by theRealBithive** [kimai/kimai#3698]
### Describe the issue

AADSTS75011: Authentication method 'X509, MultiFactor' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'. Contact the KIMAI application owner.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.30.0

### Which PHP version are you using?

8.1

### How do you run Kimai?

Self-Hosted

### Steps to reproduce the behavior

I followed the guide in the documentation; Everything seems to work until the the Microsoft Part is finished; then I get the Error Message above.

I did some investigation an it seems like the  **RequestedAuthnContext** has to be removed.
https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts75011-auth-method-mismatch

> 
> Root cause: The application is requesting the user to sign in using a specific method but the user has already authenticated with a different method prior to access the application. For example, in the SAML request the application has a RequestedAuthnContext with the specific AuthnContextClassRef value urn:oasis:names:tc:SAML:2.0:ac:classes:Password but the user has used multifactor authentication to sign in.
> Resolution:
> 
> Request to the developer of the application to remove the RequestedAuthnContext from the SAML request.
> Another option is to request the application owner to always prompt the user for a fresh authentication. To accomplish this, the application needs to add the value forceAuthn="true" as a parameter in the request to Azure AD.

I am not sure if this is something that can be done on my side or in the local.yaml config.

Thanks for your time!
Regards Bithive

**Comment by kevinpapst** [comment]
Interesting, always something new comes up 😁 


I am not an Azure user, besides testing the Kimai login, so I need some support:
Can you please share where you activate the additional methods in Azure, so I can try to test that with my YubiKey.
Hoping that this is "MultiFactor" in the eyes of Azure AD... or which methods do you use?

**Comment by theRealBithive** [comment]
Hi, thanks for your swift reply. I used the Microsoft Authenticator App on my Phone.
You can configure MFA via: https://mysignins.microsoft.com/security-info
There you can also add Security Keys.

**Comment by kevinpapst** [comment]
I hate that company. There is not one product that works as expected. And all the links that lead from one screen to another which looks completely different. There web is such a fucking mess, it is unbelievable impressive for the largest software company in the world.

I can't add YubiKey, there is no option for that:
<img width="518" alt="Bildschirm­foto 2022-12-23 um 08 29 12" src="https://user-images.githubusercontent.com/533162/209294510-190b44f1-43bc-4aae-859a-7e0d7c46893b.png">

I am using my account my 2FA TOTP and there is no issue signing in to Kimai. 
So please provide more infos how to reproduce the problem.

**Comment by kevinpapst** [comment]
According to this page:
https://learn.microsoft.com/en-us/azure/active-directory/authentication/tutorial-enable-azure-mfa

And other documentation I can only activate 2FA for my Azure AD SAML app if I have a premium account, which I don't have. 
So I can't test your issue and can't help ... unless you create a test app, send me the details via email to kevin at kevinpapst dot de , add my account (same email) and let me test with that.

**Comment by theRealBithive** [comment]
Firstly: Thank you, Kevin. I didn't expect this to be so much work on your side. It is much appreciated.

> I hate that company. There is not one product that works as expected.

Yes. Everything they touch turns into rot.

> unless you create a test app, send me the details via email to kevin at kevinpapst dot de , add my account (same email) and let me test with that.

Thanks for your offer, I will E-Mail you!

**Comment by kevinpapst** [comment]
> I didn't expect this to be so much work on your side. 

Well, I can only fix what I can see. And after testing and reading for more than an hour I had to give up.

I understand that they want to lure people into a subscription, but purposely deactivating 2FA on SAML apps is a security nightmare. 

Anyway: I think you should be able to create a SAML app, configure it to force 2FA and then invite me to that app. It needs to have these values:

<img width="601" alt="Bildschirm­foto 2022-12-23 um 12 59 25" src="https://user-images.githubusercontent.com/533162/209332784-3e012d6f-5bec-4aac-a405-66d591333e1a.png">

**Comment by kevinpapst** [comment]
See this discussion: https://github.com/kimai/www.kimai.org/pull/188

**Comment by kevinpapst** [comment]
The docs are now updated: https://www.kimai.org/documentation/saml-azure.html
Basically it is this line which needs to be added:

```
            security:
                requestedAuthnContext: false
```
