### ISSUE TITLE
Regenerate invoice after address change

### ISSUE THREAD

**Issue by LiaraAlis** [kimai/kimai#3701]
### Describe the problem

Currently it is not possible to regenerate the invoice document after changing relevant information for the invoice.
For example, it is not necessary to generate a new number after changing the billing address because you had an old billing address in the system. So it is enough to regenerate the invoice with the same number.
Also, the cancellation does not generate a credit note, so it is problematic in accounting if you cancel an invoice that you have already sent to the customer. So at the moment it's also not so easy to just create a new invoice, because then you would have two almost identical invoices.

### Describe the solution you'd like

I would like an option to regenerate the invoice document to enable the possibility to change customer data like the invoice address.

**Comment by kevinpapst** [comment]
delete the invoice (there is a permission that enables the feature) and recreate it.

careful: do not delete an arbitrary invoice from the list, but only the last one! might cause strange bugs otherwise.

**Comment by LiaraAlis** [comment]
In my case the invoice that I have to correct is not the last invoice. So this is not a solution. :(

**Comment by LiaraAlis** [comment]
I was able to change the invoice manually with Acrobat PDF and direct database changes. Very bad I was forced to do this. :(
Meanwhile, I got a few thoughts:
1. 1st option is to link invoices as described in #3080 and add a feature to regenerate the pdf with the information from database. I think this should be a very elegant way to do this. With this it could be also generate cancellation invoices.
2. 2nd option is to add a feature to "replace" an existing invoice when generating a new one. This could be a solution because you can search for already billed timesheets on the "invoice" page and re-invoice them. But I think it is not the best way to do this when there is no versioning for invoices.
3. PDFs should be generated as PDF/A to ensure that PDFs can not be modified afterwards. I suggest to add a config option for this. I think this should be very easy to add this feature because MPDF already supports this feature. It is only needed to set the `PDFA` option to true to generate a PDF/A document.

@kevinpapst What are your thoughts about this? For 3 I can create a PR after I got v2 up and running.

**Comment by kevinpapst** [comment]
1. Nice, but nowhere on my prio list. If someone contributes a PR, I will review. But it needs to be well tested. And it should be discussed upfront. Can an item be in multiple invoices? How do you handle that?
2. Keep in mind that Kimai is not a bookkeeping software. The invoicing module simplifies live of many freelancers and small companies and once you understand how it works, these cases you mention are very rare. I understand that you, as user, want such a feature. But I, as developer, am not willing to spent days with a feature that is rarely ever asked for. It might feel as if there is the need for it, but in reality there is not. For hundreds of generated invoices there is one that could benefit from such a feature. So many other features are waiting...
3. Never heard of that one, is it probably already possible to set via the Context? Then the template can directly choose to enable the feature - we could probably add it to the default templates then.

**Comment by kevinpapst** [comment]
When I use it according to the docs https://www.kimai.org/documentation/invoices.html#pdf-templates and https://mpdf.github.io/reference/mpdf-variables/pdfa.html then it seems to make a difference:
```
{%- set option = pdfContext.setOption('PDFA', true) -%}
{%- set option = pdfContext.setOption('PDFAauto', true) -%}
```
The file size increases from 32kB to 722kB. I was unaware of PDF/A, so I cannot say it the correct thing happened.
I guess the increased size comes from the embedded font.

The mac preview does not show any difference, but I guess that this is a good thing.
Can you try and share your findings?

**Comment by LiaraAlis** [comment]
@kevinpapst Sorry for late reply. I just tested the options above and can confirm that this is working.
I used my template and the file size is 246 KB. Original file size without PDF/A is 112 KB. Saving the file with Adobe Acrobat as PDF/A results in a file size of 122 KB.
According to the issue https://github.com/mpdf/mpdf/issues/1225 this is caused by the PDF version that mPDF is able to generate. But what I don't understand is that saving the kimai-generated PDF as PDF/A with Adobe Acrobat, the PDF version stays on 1.4 but the file size is smaller than with mPDF. The only explanation for this I have is that the compression technique is different, besides the PDF version.

**Comment by kevinpapst** [comment]
Hm, maybe. The default templates use fonts which are available on every computer since at least ten years and I strongly doubt that they vanish in the next ten years (which is the amount of time that might be tax relevant). So I stick with the smaller filesize - but it is nice to have the option now. So at least one point fixed 👍 

I am closing here, as I don't see the invoice regeneration on my roadmap. Sorry. But again: if anyone reads that and wants to add a PR: I'll happily review!
