### ISSUE TITLE
Set the order of columns (in my times page)

### ISSUE THREAD

**Issue by robinrosenstock** [kimai/kimai#371]
**Is your feature request related to a problem? Please describe.**
I want to reorder the columns (in my times page and elsewhere).

**Describe the solution you'd like**
Maybe make a setting which column is shown first and which second and so on.

**Describe alternatives you've considered**
Order the columns by mouse, with drag and drop.

**Additional context**
Coming from #370

**Comment by geniusupgrader** [comment]
Closed, because solution #404 is, for now, sufficient.
