### ISSUE TITLE
V2: Expenses in Reports

### ISSUE THREAD

**Issue by HeinzWuert** [kimai/kimai#3714]
### Describe the problem

Filtering in Expenses works good, but there are no totals: weekly, monthly and yearly like in the dashboard.

### Describe the solution you'd like

Add in the Symbol Menu with the stacked three sheets Expenses totals

### Screenshots

![image](https://user-images.githubusercontent.com/45666972/209817194-fbb97681-897b-4361-bd10-915a221d75a2.png)

**Comment by kevinpapst** [comment]
I cannot add a new entry to the list there, but have to create a report. 
But yes, I can do that.

Anyway: That is actually a feature request for the expense plugin repository. 
I cannot move it unfortunately. Can you re-open there please.

**Comment by HeinzWuert** [comment]
Done :-)

**Comment by kevinpapst** [comment]
Mercy
