### ISSUE TITLE
Proposal: added new users should default to user, not admin rights at all levels

### ISSUE THREAD

**Issue by andres99** [kimai/kimai#372]
At this time, 0.9.3 RC1 defaults new users to admin rights. This complicates the situation for Kimai users who are not IT professionals but who nonetheless add/configure new users to Kimai. In order to make a new non-admin user, they now have to create a user and change at least 2 (possibly more) settings: (1) the user's global role, (2) the user's role in the default admin group, (3) the user's role in possibly other groups that may exist. This is an effort for such non-IT users (or, in fact, even for IT-savvy users).

If all new users added to the Kimai database defaulted to ordinary users without any admin rights, such non-IT users could feel more confident and the system would be easier to administrate. Rationale: it would be easier for an IT-experienced user to elevate an ordinary user to admin rights (at the desired level - global or group) than for an unexperienced user to deprive any new users of the admin rights that have been given to them by default.

Therefore, all new users added should default to non-admin users both globally and in any existing/new groups.

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/issues/1291
