### ISSUE TITLE
API v0.6 swagger Go client generation reports type mismatch

### ISSUE THREAD

**Issue by decentral1se** [kimai/kimai#3720]
### Describe the issue

Using https://github.com/go-swagger/go-swagger:

```
./swagger_linux_amd64 generate client --spec doc.json
json: cannot unmarshal string into Go struct field SwaggerProps.definitions of type int64
```

`doc.json` is https://demo.kimai.org/api/doc.json

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.1

### Which PHP version are you using?

7.3

### How do you run Kimai?

kimai.cloud service

### Steps to reproduce the behavior

1. Download `go-swagger` binary on https://github.com/go-swagger/go-swagger/releases
2. Run `chmod +x` on the binary
3. Download the 0.6 `.json` swagger spec from https://demo.kimai.org/api/doc.json
4. Run `./swagger_linux_amd64 generate client --spec doc.json`

### Additional context

N/A

**Comment by kevinpapst** [comment]
Last time I tried (with official SwaggerGen project) to generate an API client (target PHP) it worked: 
https://github.com/kimai/api-php

Any more infos? 
The error message is a bit vague... any chance you can find out which entity/collection or attribute is complained?

**Comment by kevinpapst** [comment]
@decentral1se did you have a chance to look into it?

**Comment by decentral1se** [comment]
Hey, I did. I couldn't get much more out of it, I'm afraid. Maybe I'm doing it wrong... 

Are there any docs on how I can generate bindings for Go or has anyone managed it? Would love to hear.

I guess this ticket is hard to act on as-is, so will close for now.

**Comment by decentral1se** [comment]
@kevinpapst 

Had some time to look into this finally. I've tracked it down, this diff in the swagger JSON fixed it:

```diff
diff --git a/swagger.json b/swagger.json
index 5b47f3d..b9e8631 100644
--- a/swagger.json
+++ b/swagger.json
@@ -3533,7 +3533,7 @@
             "$ref": "#/definitions/TeamMember"
           },
           "type": "array",
-          "minItems": "1"
+          "minItems": 1
         },
         "customers": {
           "title": "Customers assigned to the team",
@@ -3613,12 +3613,12 @@
         },
         "username": {
           "type": "string",
-          "maxLength": "60",
-          "minLength": "2"
+          "maxLength": 60,
+          "minLength": 2
         },
         "accountNumber": {
           "type": "string",
-          "maxLength": "30"
+          "maxLength": 30
         },
         "enabled": {
           "type": "boolean"
@@ -3680,12 +3680,12 @@
         },
         "username": {
           "type": "string",
-          "maxLength": "60",
-          "minLength": "2"
+          "maxLength": 60,
+          "minLength": 2
         },
         "accountNumber": {
           "type": "string",
-          "maxLength": "30"
+          "maxLength": 30
         },
         "enabled": {
           "type": "boolean"
@@ -3736,12 +3736,12 @@
         },
         "username": {
           "type": "string",
-          "maxLength": "60",
-          "minLength": "2"
+          "maxLength": 60,
+          "minLength": 2
         },
         "accountNumber": {
           "type": "string",
-          "maxLength": "30"
+          "maxLength": 30
         },
         "enabled": {
           "type": "boolean"
```

It seems like these are integers that shouldn't get getting quoted? They aren't quoted elsewhere in the doc.

Have raised https://github.com/go-swagger/go-swagger/issues/2880 with the swagger client generation CLI I was using.

Furthermore, I'm seeing this reported in the validation:

> swagger validate swagger.json
> 2023/01/14 14:50:23
> The swagger spec at "swagger.json" showed up some valid but possibly unwanted constructs.
> 2023/01/14 14:50:23 See warnings below:
> 2023/01/14 14:50:23 - WARNING: example value for body in body does not validate its schema
> 2023/01/14 14:50:23 - WARNING: body.end.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: body.start.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: body.orderDate.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: body.begin.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: in operation "", example value in response 200 does not validate its schema
> 2023/01/14 14:50:23 - WARNING: definitions.ProjectEditForm.orderDate.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: definitions.ProjectEditForm.end.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: definitions.ProjectEditForm.start.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: definitions.TaskLogWorkForm.begin.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: definitions.TaskLogWorkForm.end.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: definitions.TimesheetEditForm.end.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: definitions.TimesheetEditForm.begin.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: definitions.ExpenseEditForm.begin.example in body must be of type date-time: "2023-01-14T05:12:43"
> 2023/01/14 14:50:23 - WARNING: definitions.TaskEditForm.end.example in body must be of type date-time: "2023-01-14T05:12:43"
> 
> The swagger spec at "swagger.json" is invalid against swagger specification 2.0.
> See errors below:
> - "paths./api/ping.get.responses.200" must validate one and only one schema (oneOf). Found none valid
> - paths./api/ping.get.responses.200.examples in body must be of type object: "array"
> - "paths./api/tasks.get.parameters" must validate one and only one schema (oneOf). Found none valid
> - paths./api/tasks.get.parameters.type in body is a forbidden property
> - invalid definition for parameter query in body in operation ""
> - in operation "", default value in response 200 does not validate its schema
> - 200.name in response has invalid pattern: "((?!,).)*"
> - definitions.TagEntity.name in body has invalid pattern: "((?!,).)*"

**Comment by decentral1se** [comment]
Generation is blocked atm with these errors:

> swagger generate client -f swagger.json                                                                              autonomic/kimai-swagger main
> 2023/01/14 14:55:44 validating spec swagger.json
> The swagger spec at "swagger.json" is invalid against swagger specification 2.0. see errors :
> - "paths./api/ping.get.responses.200" must validate one and only one schema (oneOf). Found none valid
> - paths./api/ping.get.responses.200.examples in body must be of type object: "array"
> - "paths./api/tasks.get.parameters" must validate one and only one schema (oneOf). Found none valid
> - paths./api/tasks.get.parameters.type in body is a forbidden property

I can open a separate ticket for that if you like?

(`swagger generate client --skip-validation -f swagger.json` does work tho :clap:  )

**Comment by decentral1se** [comment]
Attempting to get a working generated client in https://github.com/decentral1se/go-kimai :+1:

**Comment by kevinpapst** [comment]
Wow, thanks for the details and your investigation and cross posting this issue - great work 👍 

Okay, lets do it step by step.

The minLength & maxLength is a problem that comes from several places. First are places [like this](https://github.com/kimai/kimai/blob/1.x/src/Entity/User.php#L233) in Kimai where you find `max="30"` instead of `max=30`. This is one of these places where developers from other languages shake their head... php just does its autoboxing into integer. It's wrong here in Kimai and the new version has [fixed that issue](https://github.com/kimai/kimai/blob/main/src/Entity/User.php#L171) already.
Then there is the library that generates the swagger code from Kimai annotations. They do not cast the value to int before passing it to the OpenAPI ModelDescribor.  But they do in the next major release, which again is used in the next major release of Kimai.
So all in all => this is a wontfix for me, because it is fixed for 2.0 ([which will be released soon](https://www.kimai.org/blog/2022/next-major-release-preview/)).

Maybe you could to test the next release https://demo-branch.kimai.org/api/doc.json (user: `susan_super` and pw `kitten`).

What about the other errors, could you fix them by manipulating the JSON or did you use the `skip-validation` flag? 
No need for a new ticket, we will get there somehow 😁

**Comment by kevinpapst** [comment]
Using this online validator: https://apitools.dev/swagger-parser/online/
I see a lot of weird errors in the 1.x version, but none in 2.x - can you confirm that?

**Comment by decentral1se** [comment]
> What about the other errors, could you fix them by manipulating the JSON or did you use the skip-validation flag?

I was able to get generation working using `--skip-validation` and have a working example in https://github.com/decentral1se/go-kimai/blob/main/example.go. Seems fine! Idk what issues I'll run into...

> I see a lot of weird errors in the 1.x version, but none in 2.x - can you confirm that?

@kevinpapst I see a whole slew of new errors when I use `go-swagger`, I'd recommend just downloading the binary from https://github.com/go-swagger/go-swagger/releases/tag/v0.30.3 and running `swagger validate doc.json`, it's kind of a lot... Not sure what to do with that?

---

Feel free to close this if you like! Kind of "solved, I guess :upside_down_face: It's unclear what is "broken" for both versions of kimai in relation to the generation tool and the spec. I guess if I can get running code for now, that is enough! Once the new version comes out, I'll try to do the same and see how it goes.

Good luck with the new version!

**Comment by kevinpapst** [comment]
Ah, I see. The go-swagger project uses OpenAPI 2.0.

The next major release of Kimai uses OpenAPI 3.0.
Also the underlying libraries improved quite a lot between the two major releases of Kimai, so I think they fixed a lot as well.
I trust the online validation, which supports OpenAPI 3 and will do as advised: closing the ticket for now.
And then we talk again after the release, when you had the time to give it a try (hopefully go-swagger will support OpenAPI 3 soon).

**Comment by decentral1se** [comment]
:+1: 

FYI `go-swagger` folks are saying that Open API 3.0 is hard to migrate to, so idk if I'll be able to continue with that tool choice. See https://github.com/go-swagger/go-swagger/issues/1122 for the deets. Idk if others will struggle with this also. Anyway, will look into this again when the new version drops.

**Comment by kevinpapst** [comment]
That indeed sounds as if you need to switch the tooling. 
Maybe https://github.com/google/gnostic which was mentioned in one of the comments in this thread.

**Comment by decentral1se** [comment]
Sorry for resurrecting this issue but in case anyone else follows, I also had to make the following diff:

```diff
diff --git a/doc.json b/doc.json
index b9e8631..e3fc162 100644
--- a/doc.json
+++ b/doc.json
@@ -4231,7 +4231,8 @@
         "end": {
           "example": "2023-01-14T05:12:43",
           "type": "string",
-          "format": "date-time"
+          "format": "date-time",
+          "x-nullable": true
         },
         "project": {
           "description": "Project ID",
diff --git a/models/timesheet_edit_form.go b/models/timesheet_edit_form.go
index ce80351..8ed4ce8 100644
--- a/models/timesheet_edit_form.go
+++ b/models/timesheet_edit_form.go
@@ -38,7 +38,7 @@ type TimesheetEditForm struct {
        // end
        // Example: 2023-01-14T05:12:43
        // Format: date-time
-       End strfmt.DateTime `json:"end,omitempty"`
+       End *strfmt.DateTime `json:"end,omitempty"`

        // exported
        Exported bool `json:"exported,omitempty"`
```

According to https://github.com/go-swagger/go-swagger/issues/1491 in order to create a timesheet without an `end` value.

Otherwise, the generated code will always produce an `end` value.
