### ISSUE TITLE
Mark time entries as invoiced

### ISSUE THREAD

**Issue by npostnik** [kimai/kimai#373]
Every time-entry needs an "invoiced" flag, which can be set manually or while generating an invoice.

**Comment by stoberblog** [comment]
It would also be nice if this flag could be set in bulk (I use InvoicePlane for invoicing currently). One method I thought of doing this, would be to allow all events that are shown currently (you'd want to use in conjunction with filtering) and have a button (similar to the visible button). The button changes the invoice state on all entries shown/filtered. This may need three states annoyingly however, as there would be times when not all entries are in the same state to begin with.

**Comment by juup** [comment]
As posted in #992 it would be good to have different "invoice flags".
E.g.: open, printed, send out, paid, cancelled.

**Comment by kevinpapst** [comment]
Everyone who voted for this feature: please have a look at #1046 and help testing.
