### ISSUE TITLE
Calendar uses US date and time formatting by default

### ISSUE THREAD

**Issue by wmevius** [kimai/kimai#3733]
### Describe the problem

The Calendar control in Kimai always uses AM/PM for its time formats. It should use 24h by default. It also seems to use US date formatting by default.

### Describe the solution you'd like

Ideally, the calendar should follow the rest of Kimai for its date and time formats. At the very least it should be configurable.

### Screenshots

![BRyJ6pv](https://user-images.githubusercontent.com/19187133/210775724-64aa4ce6-80ee-498e-8be5-973b202804b6.png)

![TZJ85OR](https://user-images.githubusercontent.com/19187133/210775969-10198182-a39b-4a3f-8682-7cd37c9522c0.png)

**Comment by kevinpapst** [comment]
Kimai does not use US settings by default.
You have activated that in your user profile.
Change it back... in the upper right on your avatar => choose Preferences and then:
<img width="273" alt="Bildschirm­foto 2023-01-05 um 13 05 09" src="https://user-images.githubusercontent.com/533162/210776495-b9798646-4156-4387-a760-5346413c32b2.png">

**Comment by wmevius** [comment]
This is just the Calendar. The rest of Kimai is fine and using the correct settings.

I did not modify the Timezone/Language settings. However, it looks like we need to update our Kimai instance, as I don't have a 24 hours tickbox in preferences, so I will try that first.

**Comment by wmevius** [comment]
It's also only when you select 'English', for other languages it is fine - there is no option to select 'English - UK' or 'English - Ireland'

**Comment by kevinpapst** [comment]
Aha, yeah please do the update first. I cannot support old versions. Maybe it was different (wrong) back then...

The new version (not yet released) will ship with region support, so you can/have to choose the language and country, as you suggested as well.

**Comment by wmevius** [comment]
Hi Kevin,

We updated to the latest version and all is good. We will make sure to update a little more frequently from now on.

Just to let you know that we're extremely impressed by Kimai, and your hard work going into it.

Cheers,
Willem
