### ISSUE TITLE
Remove the mandatory project field and link activities to clients

### ISSUE THREAD

**Issue by NHendriks01** [kimai/kimai#3739]
### Describe the problem

I started working with Kimai this week and I really like it, what I don't like however is the fact that 'projects' is always a mandatory thing when adding new worked hours into Kimai. The work I do does not consist of work on a project-base, or well it does but for my timekeeping this isn't interesting, I only need to know what activity I had and what customer I was working for. I do work projects but I'm invoicing from a separate system and that will probably be the case for the years to come. My request is to remove the 'mandatory'-part of the whole projects-system.

Another feature request of mine of the linking of activities to certain customers. On a customer-page I can select three activities I do for them for example and when adding new hours only these activities show up. I have multiple internal activities (things like admin-work or travel time) that don't need to be added to a customer.

### Describe the solution you'd like

Keep the projects-module but remove it being mandatory.

 On a customer-page I can select a couple of activities I do for them for example and when adding new hours only these activities show up when the customer is selected. I have multiple internal activities (things like admin-work or travel time) that don't need to be added to a customer.

### Describe alternatives you've considered

Not really any other. Quite new to Kimai.

**Comment by kevinpapst** [comment]
Not possible. The entire data structure is build around the customer > project > activity structure.

But you could create one single customer for yourself (if there is only one existing, the field will be hidden) and then use projects as customers. Some users do that to get rid of the first information level.

**Comment by NHendriks01** [comment]
Ah, good one! That'll work fine!
