### ISSUE TITLE
REST Api HttpPost/HttpGet does not support umlauts

### ISSUE THREAD

**Issue by paul-franitza** [kimai/kimai#3751]
### Describe the problem

I'd like to be able to post customers, projects, activities, time sheets, ... containing german umlauts.
If i post such requests via HttpPost (libary: org.apache.http.client.methods.HttpPost) Kimai returns Code: 400; Message: Bad Request. 

There is a similar issue with get requests. If you try to get (for example) a project via REST Api with org.apache.http.client.methods.HttpGet and it contains umlauts the response from the server will replace every umlaut with its unicode counter part (e.g "\u00C4" for Ä).

### Describe the solution you'd like

The feature should fix both of this issues, so umlauts are no major problem when working with the REST Api and HttpPost and HttpGet.

**Comment by kevinpapst** [comment]
We are not in 2003 anymore ... you think umlauts cause problems? I wonder why I can even mix LTR and RTL with Vietnamese, Chinese, Farsi, Hebrew, Russian and Emojis and Umlauts?
<img width="946" alt="Bildschirm­foto 2023-01-12 um 16 35 57" src="https://user-images.githubusercontent.com/533162/212111050-38a2e46e-9b4f-47df-a50e-26c6a65da5ff.png">
<img width="1436" alt="Bildschirm­foto 2023-01-12 um 16 36 22" src="https://user-images.githubusercontent.com/533162/212111065-be02953d-dedc-4731-adeb-645c79d45cbe.png">

**Comment by kevinpapst** [comment]
Thank you for your free application and quick feedback, much appreciated :sarcasm:

**Comment by paul-franitza** [comment]
Well in this case
 this is totally my fault or my company is using outdated software. Could you be so kind and show me, how you are solving this problem? With the documentation online and all stackoverflow threads its not possible for me to figure out how to send those post messages properly. What kind of Headers do you use?
![httppost](https://user-images.githubusercontent.com/96250025/214291616-876d5135-dda9-408f-97d8-564ad1b8a299.png)

**Comment by kevinpapst** [comment]
Just to clarify: I believe that you see the issue!
I am just saying this is very likely happening somewhere outside of Kimai. 

Probably webserver config? 
Probably the used client?

I use default Postman settings:
<img width="282" alt="Bildschirm­foto 2023-01-24 um 13 31 51" src="https://user-images.githubusercontent.com/533162/214292378-7ae2e9ed-6ea9-4ac4-b2ed-2c51cec1d2f7.png">
<img width="958" alt="Bildschirm­foto 2023-01-24 um 13 34 13" src="https://user-images.githubusercontent.com/533162/214292838-3700f906-fe00-4b3c-87b5-2ac2e3600484.png">
