### ISSUE TITLE
Profile’s “Working since” showing &ndash;

### ISSUE THREAD

**Issue by itkfm** [kimai/kimai#3754]
### Describe the problem

The “working since” display is probably supposed to show a narrow-dash `-` when no data available, but it doesn’t.
Shows `&ndash;` instead.

Version: Kimai v2.0.0-beta

### Describe the solution you'd like

Don’t run the HTML entity `&ndash;` another time through an escape function.

### Screenshots

![image](https://user-images.githubusercontent.com/53079668/212152920-8370c18c-3f46-4642-abf5-825d159fd544.png)

**Comment by kevinpapst** [comment]
Thanks for testing and sharing 👍 

Will be fixed with https://github.com/kimai/kimai/pull/3757

**Comment by itkfm** [comment]
You’re welcome :)
Thank you for your great time tracker
