### ISSUE TITLE
Broken bug_report issue template

### ISSUE THREAD

**Issue by itkfm** [kimai/kimai#3755]
### Describe the problem

There’s no “bug report” template available.

GitHub’s UI says the following about [the file](https://github.com/kimai/kimai/blob/2.0.0-beta/.github/ISSUE_TEMPLATE/bug_report.yml):
> body[6]: render is not a permitted key. [Learn more](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-x-is-not-a-permitted-key).

### Describe the solution you'd like

Have a working *bug report* template, so I don’t have to file such as *feature requests*.

### Describe alternatives you've considered

Creating issues as “feature requests” serves as a work-around meanwhile.

### Screenshots

![image](https://user-images.githubusercontent.com/53079668/212154352-fc0fff59-fd85-4417-9d94-140f9bcd44dd.png)

**Comment by kevinpapst** [comment]
Interesting. Thanks for noticing and sharing 👍 

Fixed right away, so you can start reporting more found 🐛

**Comment by itkfm** [comment]
Thanks :)
Luckily, #3754 was the only thing I’ve encountered in the current beta so far.

**Comment by kevinpapst** [comment]
Keep on looking, there must be more 😁
