### ISSUE TITLE
Browser back button restores previously set language

### ISSUE THREAD

**Issue by itkfm** [kimai/kimai#3759]
### Describe the issue

Previous language is “kinda” restored when using the browser’s back button after changing it.

1. Set Kimai to English
2. Save
4. Set Kimai to German
5. Save again
6. Hit the back button in your browser
7. The page is English again (probably as expected)
8. Start to navigate around → it stays English
9. Go to *preferences* → Language field says German, although everything is English

Workaround:
You have to re-apply the new one on the user preferences page.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.0-beta

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

*empty*

### Screenshots

![image](https://user-images.githubusercontent.com/53079668/212340017-c0ae803d-143c-4c1f-942c-56cba6ae3700.png)

<details>
<summary>It gets fancier when triggering it from multiple browsers</summary>

![image](https://user-images.githubusercontent.com/53079668/212340815-f2b6f370-07bc-4693-99f8-88d3591d66ba.png)

</details>

**Comment by itkfm** [comment]
How would one find out about this behavior?
Well, I had set Kimai to English for my bug report yesterday. So I switched it back to German again, but navigated back via the browser’s controls and got this surprise.

**Comment by kevinpapst** [comment]
That's because Kimai keeps the user locale in the URL. Allows for testing different scenarios quickly.

**Comment by itkfm** [comment]
I see, thanks for the explanation.

**Comment by itkfm** [comment]
It might make sense to rename the “Language” preference to “Default Language” or something.

**Comment by kevinpapst** [comment]
Not sure if there is anything I can do about it. 
At least I will not force the language upon the user, because this switch via URL has some great benefits for testing.

Thanks for posting 👍  but I think I am going to close this as "wontfix". 

If you have a great idea how to apply a possible fix, please let me know!
