### ISSUE TITLE
Browser title bar color for PWA in dark mode

### ISSUE THREAD

**Issue by VOOM108** [kimai/kimai#3761]
### Describe the problem

Browser title bar for PWA is white, even when dark mode is activated on Windows and kimai

### Describe the solution you'd like

Custom colors could be added for light mode as well as dark mode to the header: 

e.g.

```
Dark Mode: 
<meta name="theme-color" content="#1c2233">

Light Mode:
<meta name="theme-color" content="#1f273a">
```

### Describe alternatives you've considered

If the head cannot be changed with the theme, the proposed color for the light theme (menu background) would work well in both cases: 

`<meta name="theme-color" content="#1f273a">`

**Comment by kevinpapst** [comment]
There is no PWA, so I assume you are talking about https://github.com/kimai/kimai/blob/main/public/manifest.json

How did you install that on your device exactly?

**Comment by VOOM108** [comment]
What I mean is "installing" the web-ui like a native app, that has its own icon and shows without browser controls, like all Chromium-based browsers can. Some Chromium-browsers actually call it "installing", sometimes it is referred to as "create link" or so. Often the term "PWA" is used, even when the actual website is not a web-app per se (e.g. in a Firefox-extension that adds that feature to the browser). 

So, however the meta-tags are added to the HTML head, would do what I propose.

**Comment by kevinpapst** [comment]
When I "add it to homescreen" from Chrome on my Samsung mobile (switched to dark mode), I do not see browser controls.
And I am sitting on a Mac, so it might behave different. 
I have never installed Kimai on a computer, only as homescreen link on mobile.

That's why I asked:

> How did you install that on your device exactly?

What I am asking for is a step-by-step guide (browser, plugin, where did you click...), so I can test it here.

**Comment by VOOM108** [comment]
Ok, I see... Using Chrome, it would be: 

... Menu on the right > More Tools > Create Shortcut > Open in a new window
The resulting window can be pinned to the taskbar etc. 

(If it actually is a PWA, the wording is different, then it offers to install the site. The result looks the same, though.)

**Comment by kevinpapst** [comment]
Wow, what a cool feature, thanks for pointing me into the right direction 👍 

Never saw that feature, I'll look into it.

**Comment by kevinpapst** [comment]
So it seems the "web" is not sure how to handle this, see e.g. https://github.com/w3c/manifest/issues/1045

I could switch the manifest.json from a static file to a controller response, as already [proposed in the past](https://github.com/kimai/kimai/pull/1571/files). 

Then the color could be dynamically switched when the user toggles between dark and light mode.
This would not react on the system preference, but the Kimai theme/color setting.

**Comment by VOOM108** [comment]
At the moment I do this with a simple userscript-extension, and it works. Whatever would lead to the same result in the head, should work. Only the third part has to to do with the title bar. The other ones may be useful as well, though.  

```
// Create the link element
var link = document.createElement("link");
link.rel = "mask-icon";
link.href = "/safari-pinned-tab.svg";
link.color = "#1b1e20";

// Create the first meta element
var meta1 = document.createElement("meta");
meta1.name = "msapplication-TileColor";
meta1.content = "#1b1e20";

// Create the second meta element
var meta2 = document.createElement("meta");
meta2.name = "theme-color";
meta2.content = "#1b1e20";

// Get the head element
var head = document.getElementsByTagName("head")[0];

// Add the link and meta elements to the head
head.appendChild(link);
head.appendChild(meta1);
head.appendChild(meta2);
```

**Comment by kevinpapst** [comment]
According to https://gist.github.com/kevinSuttle/1997924#windows-8-meta-tags the first two ones are rather "useless"? 
DO you have a specific use-case or is that just copy & paste from an old template?

**Comment by VOOM108** [comment]
I asked ChatGPT to write me that script ;) The second one I presumed would color a tile in the Windows 10 startmenu (which I don't use) in the given color. Safari I don't use at all.  

```
// Create the meta element
var meta = document.createElement("meta");
meta.name = "theme-color";
meta.content = "#1b1e20";

// Get the head element
var head = document.getElementsByTagName("head")[0];

// Add the link and meta elements to the head
head.appendChild(meta);
```

**Comment by kevinpapst** [comment]
I have chosen to use `#1d273b` both in light and dark mode. Looks good to me.

Will ship with the new beta.
