### ISSUE TITLE
Kimai 2.0.0: Make unique customer numbers optional again

### ISSUE THREAD

**Issue by Sarmingsteiner** [kimai/kimai#3762]
### Describe the problem

We were terrified when we read that Kimai 2.0.0 requires unique customer numbers.
Our situation: We do quite a lot of one-time-consulting. For these customers, we do not create a new client in our ERP (accounting) system. We just write an invoice in Kimai using the same customer number (299999 Various Customers) for importing them in our ERP (accounting) system.
So far, we have quite a lot of customers in Kimai using number 299999. Does this mean that an upgrade to Kimai 2.0.0 is impossible?

### Describe the solution you'd like

We would highly appreciate an option to make unique customer numbers optional again.

### Describe alternatives you've considered

If not, could you tell us where to find the code for this check?

**Comment by kevinpapst** [comment]
This is a code validation right now and no restriction on the database side, because it was obvious that this case (like yours) exists.

What about using `299999-0001`, `299999-0002` ... in these cases ?

**Comment by Sarmingsteiner** [comment]
Not quite, since the import of the CSV file in our ERP system would fail anyway. So we would have to change the customer numbers in the CSV file before.

**Comment by kevinpapst** [comment]
Then leave the field empty, that still works for as many customers as you want.

**Comment by Sarmingsteiner** [comment]
Also less than perfect, since we cannot import it without customer numbers.

**Could you be so kind and tell us where to find this validation in the code?**

**Comment by kevinpapst** [comment]
If there is one customer with an issue, there are more. So I am trying to find a proper solution first.

**Comment by kevinpapst** [comment]
BTW: printing stuff bold doesn't make it more likely to happen. I am here to make Kimai better for everyone. If you want personal consulting, you can send me an email.

**Comment by empx92** [comment]
Would be also a restriction of our ERP, so your are right, that this could be a issue for some customers.
On the other site the next problem with other customer numbers in kimai than in the ERP could be confusing for the backoffice or employee (=users of the kimai system)

**Comment by itkfm** [comment]
How about an option to specify a “replacement” customer number for those with an empty one? Such a replacement would be filled in for exports.

That would cover the OP’s use case while still keeping the otherwise useful constraint in place. (If I were using Kimai as my primary customer database (resp. CRM), I’d probably like it to validate the unique constraint for customer numbers, I guess.)

**Comment by kevinpapst** [comment]
Thanks for all your feedback. Next beta will contain a new system setting to "allow duplicate customer number":

<img width="377" alt="Bildschirm­foto 2023-01-20 um 21 40 13" src="https://user-images.githubusercontent.com/533162/213801294-a58e4b49-9052-469d-a101-1b16c792c6dc.png">
