### ISSUE TITLE
Confusing error message for exported entries in calendar view

### ISSUE THREAD

**Issue by itkfm** [kimai/kimai#3766]
### Describe the issue

Clicking on exported (and therefore “locked”) timesheet entries in the *Calendar* view asks users whether they’d like to be redirected to login but doesn’t tell them what’s actually wrong (specifically, that the entry is locked/read-only).

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.0-beta2 @ d0e6fee

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

*\*empty\**

### Screenshots

![image](https://user-images.githubusercontent.com/53079668/212972288-749b4cbb-87c1-414f-8b43-6d2a31689fa3.png)

**Comment by itkfm** [comment]
What might lead to further confusion:
The “login” mentioned in the message isn’t a thing either, because the user is already logged in at this point.
So they end up in the dashboard (obviously).

**Comment by kevinpapst** [comment]
will be fixed with the next beta
