### ISSUE TITLE
Internal Server Error on call to API endpoint "/api/timesheets/recent" when parameter "user" is set

### ISSUE THREAD

**Issue by fgschaefer** [kimai/kimai#3771]
### Describe the issue

On [api page of official demo instance](https://demo-stable.kimai.org/api/doc), calling the API endpoint "/api/timesheets/recent" with parameter "user" set to a user id (or "Send empty value" checkbox checked) results in Error Code 500 "Internal Server Error".

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.3

### How do you run Kimai?

Demo version at https://demo-stable.kimai.org

### Which PHP version are you using?

Unknown

**Comment by kevinpapst** [comment]
Thanks for the report, will be fixed with the next patch release
