### ISSUE TITLE
Fixed Times for Holiday and time compensation

### ISSUE THREAD

**Issue by empx92** [kimai/kimai#3772]
### Describe the problem

Most normal worktimes are 38.5h a week, so there is a fixed time for holidays of employees.

Wouldn‘t it be nice to keep track of holidays?

In Austria for example you‘ll have 25 days of paid holiday per year.

With a 38.5h/week work-time one holiday would count 07:42h for example (if you calculate with a benefit for your employee, otherwise a day has to be counted with 8.5h)

### Describe the solution you'd like

Activation in the settings site with possible consumption value for monday to friday.

There maybe should be a difference between holiday and time compensation (as holiday is a fixed time)

### Describe alternatives you've considered

I hardcoded this part in my pdf-export because this export is delivered to our payroll office.

But to see the time account of our employee we have to keep track in an excel or copy it from the payslip.

**Comment by tstrohmeier** [comment]
In Austria and Germany the period for the calculation of the holiday is different:

**Germany**
§ 1 Urlaubsanspruch
Jeder Arbeitnehmer hat in **jedem Kalenderjahr** Anspruch auf bezahlten Erholungsurlaub.
Source: https://www.gesetze-im-internet.de/burlg/BUrlG.pdf

**Austria**
§ 2. (1) Dem Arbeitnehmer gebührt für **jedes Arbeitsjahr** ein ununterbrochener bezahlter Urlaub. Das Urlaubsausmaß beträgt bei einer Dienstzeit von weniger als 25 Jahren 30 Werktage und erhöht sich nach Vollendung des 25. Jahres auf 36 Werktage.
Source: https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=10008376

The Work Year ("Arbeitsjahr") in Austria always starts with the first day of the employment. 


So it would be nice if the period for the holiday time calculation is configurable.

**Comment by kevinpapst** [comment]
Closing here, as the initial request is fulfilled with https://www.kimai.org/store/controlling.html
