### ISSUE TITLE
Timesheet creation form - problem with Timesheet Mandatory custom field, which is restricted

### ISSUE THREAD

**Issue by cloggg** [kimai/kimai#3773]
### Describe the issue

Timesheet entry form does not respect settings of CustomFields plugin (In my example: Mandatory field for Timesheet, restricted to certain project)
The form is not visible while creating the entry. it appears only when editing already existing entry

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

Kimai 1.22, CustomFields: 1.15, but issue is reproducable in Online demo (newest version)

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

**Comment by cloggg** [comment]
### ******  Configuration

![image](https://user-images.githubusercontent.com/44738323/213340796-e9b32e25-c8f3-4811-becb-5d04d0b780ed.png)

![image](https://user-images.githubusercontent.com/44738323/213340902-268a712c-3aad-4f28-b5fc-14e7e1e59c86.png)

### ******** New timesheet entry:
![image](https://user-images.githubusercontent.com/44738323/213341082-d6dd9f28-d2e6-4c24-8d20-0ed20360b650.png)

### ******** Saved without problems:
![image](https://user-images.githubusercontent.com/44738323/213341252-f8817138-a71e-4514-9bb5-1096bca951e7.png)


### ********* Editing the same entry:
![image](https://user-images.githubusercontent.com/44738323/213341349-6faf6216-7ffd-4968-a5eb-ce4b2675b457.png)

### ********* Now validation works - I cannot save:
![image](https://user-images.githubusercontent.com/44738323/213341492-0b339f6f-210e-41c0-95a5-219fd0f17495.png)

**Comment by kevinpapst** [comment]
A quote from https://www.kimai.org/store/custom-fields-bundle.html

> Be aware:
>
> Restricted fields won’t be visible on the create forms, as Kimai initially can’t know if the rule will apply: in these cases the fields will only be shown in the edit forms

Sorry for not having better news 😢 
But that is clearly communicated as a limitation before purchasing, so I am closing here.
