### ISSUE TITLE
Cannot assign permissions to a role right after creation

### ISSUE THREAD

**Issue by itkfm** [kimai/kimai#3777]
### Describe the issue

Right after creating a new role, one cannot grant permissions to it.
Instead the page will just scroll up to top; no error message though.

After reloading the page in the browser, permission management for the newly created role works fine.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.0-beta2 (0e91dd886e9f637b3790d70b4dd677c6e71433a1)

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Logfile

*\*empty\**

**Comment by kevinpapst** [comment]
Works in the demo: https://demo-branch.kimai.org/en/admin/permissions

Please check your environment, there seems to be something wrong with it.

**Comment by itkfm** [comment]
Can reproduce it with [the demo](https://demo-branch.kimai.org/en/admin/permissions), too.
Tested in two browsers (my regular Firefox profile + Chromium 109.0.5414.74 with no extensions installed).

My coworker tested it on their machine as well, and the same issue occurs.

**Comment by itkfm** [comment]
I’ve now even booted my Windows machine

1. went to demo-branch.kimai.org
2. logged in with `admin`:`password`
3. clicked on “System” > “Rollen”
4. pressed the “Erstellen” button
5. entered “DINGS_A” as name and clicked “Speichern”
6. clicked on “nein” in the “budget_activity” row for the new role
7. nothing happened, (well, URL got a trailing `#`)
8. clicked on “nein” in a few other rows for the new role → still nothing
9. hit F5, now it works

OS: Windows 11 Pro, 21H2
Browser: Firefox 109.0 (64 bit)

**Comment by kevinpapst** [comment]
Thanks for clarification.

I completely misunderstood the ticket.
There was a bug in the past, that the page was not reloaded after a role was created, so the new Role didn't show up.

I was mislead that this is the same issue. 
Found the reason, will be fixed with the next beta.

Thank you for continues testing ... and the great testing feedback 👍
