### ISSUE TITLE
Filter projects links to a missing page

### ISSUE THREAD

**Issue by itkfm** [kimai/kimai#3778]
### Describe the issue

The *project details* page (e.g. `/en/admin/project/1359/details`) links a “Filter projects” option.
Clicking it results in navigating to an URL like `/en/admin/project/?customers%5B%5D=279` which is not found (error 404).

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.0-beta2 (0e91dd886e9f637b3790d70b4dd677c6e71433a1)

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

*\*empty\**

### Screenshots

![image](https://user-images.githubusercontent.com/53079668/213523416-411294d4-d831-433f-a9a8-8ca8a4173371.png)

<details>

<summary>Error 404 page + URL</summary>

![image](https://user-images.githubusercontent.com/53079668/213523844-9609a092-91e1-40cd-be21-1f406c3e6615.png)

</details>

**Comment by itkfm** [comment]
Occurs for users with super admin permissions, too.

**Comment by kevinpapst** [comment]
1. Only customer detail pages have a link to "filter projects", I guess that is a typo in your description, right?

2. This "Filter projects" action correctly links to the project listing page, with the customer being pre-selected in the search filter. This might result in a "Not found" listing, in case the customer has no projects, but not in a 404.
Even if the customer does not exist, the form only shows an error message, not a 404.

With wrong permissions, you should see another error.
So something must be wrong in your env I'd say.

See, this works as expected: https://demo-branch.kimai.org/en/admin/project/?customers%5B%5D=279

It's always good to try reproducing in the demo first.

**Comment by itkfm** [comment]
1. No, I’m talking about a project details page (e.g. https://demo-branch.kimai.org/en/admin/project/113/details), the link is in the customer row there, though.
2. Yeah, I cannot reproduce it in the public demo either.

**Comment by itkfm** [comment]
That said… I haven’t changed a thing, but it suddenly works as expected here today. Oh dear… Sorry for the noise.

**Comment by kevinpapst** [comment]
Ah, you are right about the link in the customer dropdown.

One issue too much is better than missing a bug 😄 please keep on testing and posting feedback!
