### ISSUE TITLE
Kimai 2.0.0: Create new timesheet modal - show extended settings immediately

### ISSUE THREAD

**Issue by Sarmingsteiner** [kimai/kimai#3785]
### Describe the problem

For almost every new timesheet entry, we need to adjust / verify the billing settings such as hourly / fixed price, billable yes / no.

### Describe the solution you'd like

An option to show all settings without having to click the dropdown button "Extended Settings" would be time-saving and can prevent errors (so as in Kimai 1.30.x).

**Comment by kevinpapst** [comment]
Do-able with the CustomContentBundle and some lines of Javascript (but you have to wait for beta 3):
```javascript
document.addEventListener('show.bs.modal', (e) => { 
    e.srcElement.querySelector('#timesheet_extended_settings a[data-bs-toggle]')?.click(); 
});
```
Documented at https://www.kimai.org/documentation/plugin-custom-content.html
