### ISSUE TITLE
Docker image apache-1.30.5-prod throws 500 internal server error

### ISSUE THREAD

**Issue by klangborste** [kimai/kimai#3788]
### Describe the issue

Hello together,

today I did an update from my docker-compose stack and run into an problem with Kimai docker "apache-1.30.5-prod".
After the new image was pulled and the service was running again I got a 500 internal server error message. Couldn't find any errors in the Apache log that could be useful here.

After run the older docker image "apache-1.30.2-prod" it runs successful again.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.5

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by marcus905** [comment]
Not OP, but I have the same issue and this is what happens. Basically somewhere the timesheet controller might have been called with an incorrect parameter number. Will try checking and creating a pullrequest.


`[2023-01-22 11:55:52] php.CRITICAL: Uncaught Error: Too few arguments to function App\API\TimesheetController::__construct(), 5 passed in /opt/kimai/var/cache/prod/ContainerVcxn7G6/getTimesheetControllerService.php on line 14 and exactly 6 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\API\\TimesheetController::__construct(), 5 passed in /opt/kimai/var/cache/prod/ContainerVcxn7G6/getTimesheetControllerService.php on line 14 and exactly 6 expected at /opt/kimai/src/API/TimesheetController.php:81)"} []`

**Comment by kevinpapst** [comment]
<img width="1283" alt="Bildschirm­foto 2023-01-24 um 13 02 10" src="https://user-images.githubusercontent.com/533162/214286680-5030f250-bb09-4949-a81f-edf7c4b48cd1.png">

@marcus905 completely unrelated caching issue. delete xxx/kimai/var/cache/*
