### ISSUE TITLE
Ability to export all time by custom time range

### ISSUE THREAD

**Issue by TGG-RPA** [kimai/kimai#3792]
### Describe the problem

Only options are by week, by month, by year.

For organizations that process payroll every two weeks, this becomes a nuisance to over export and trim to validate.

### Describe the solution you'd like

Can we have the option to specify custom date range?

### Describe alternatives you've considered

Over export into Excel then trim - prone to manual key error and non value add time spent

**Comment by kevinpapst** [comment]
You can filter and export every time range. 
But actually it sounds as if you are talking about reports. 
Why do you use reports for exporting data? What is the use-case?

**Comment by TGG-RPA** [comment]
My bad - just getting used to the system.  Yes, I can verify that Export provides the range - which is exactly what I was looking for.  Thanks for the prompt response Kevin.
