### ISSUE TITLE
mysqldump fails

### ISSUE THREAD

**Issue by Sim0nW0lf** [kimai/kimai#3805]
### Describe the issue

I wrote a script to backup my database and it has been running nicely for half a year. But suddenly after my update to the newest version it fails.

`docker exec --user root -i kimai_mysql /usr/bin/mysqldump --defaults-extra-file=/scripts/backup-db-config.cnf  --single-transaction --force kimai --no-tablespaces > ./backup/${filename}`
is failing with this error:
```
-- MySQL dump 10.13  Distrib 5.7.41, for Linux (x86_64)
--
-- Host: localhost    Database: kimai
-- ------------------------------------------------------
-- Server version       5.7.41
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
mysqldump: Couldn't execute 'FLUSH TABLES': Access denied; you need (at least one of) the RELOAD privilege(s) for this operation (1227)
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
```

I also can't grant those privileges to the kimai user.

`GRANT RELOAD ON *.* TO 'kimai'@'localhost';`
```
ERROR 1045 (28000): Access denied for user 'kimai'@'%' (using password: YES)
```

Am I doing something wrong or has something about kimai changed?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.5 stable (prod)

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by Sim0nW0lf** [comment]
Oh, I forgot to login as root when granting those privileges 🤦🏻‍♂️😅
This issue was a change of the MySQL version actually...

As root user this command worked:
`GRANT RELOAD ON *.* TO 'kimai'@'%';`

**Comment by kevinpapst** [comment]
Info might be better off in the docker repository: https://github.com/tobybatch/kimai2/
Just in case someone else trips into that problem.
