### ISSUE TITLE
Kimai 2.0.0 beta 2 - UI Exception KimaiWebLoader is not defined

### ISSUE THREAD

**Issue by testload2011** [kimai/kimai#3806]
### Describe the issue

**Defect:** When you try to click on the navigation UI, none of the buttons are working. Have tried both update from 1.35.0 to 2.0.0 beta2 and fresh installation of 2.0.0 beta2. In both case, the same exception was appearing.

**Exception details:**

![image](https://user-images.githubusercontent.com/11069905/215965608-7bb8b73d-bd7e-4bed-abba-2f2b679c8a6c.png)

Steps to reproduce:
1. Install Kimai 2.0.0 beta2 as per the installation instructions provided
2. Create first user from the command line
3. Login with the 1st user (Super Admin user here)
4. Open Browser Dev tools
5. Click on left top corner burger icon to display the menu
6. The same exception occurs when you click any of the links from the left side menu

System: Windows 10 Enterprise
Web Browser: Edge Version 109.0.1518.70 (Official build) (64-bit)

Expected Result: The exception should not occur and the UI elements should be functional.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.0. beta 2

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![image](https://user-images.githubusercontent.com/11069905/215967344-ec288549-8927-4eb8-a625-e664dbbce9fa.png)

**Comment by kevinpapst** [comment]
Does it work in the demo for you: https://www.kimai.org/en/demo.html ?

**Comment by testload2011** [comment]
yes, the demo works fine. However, both in fresh installation and update (from 1.35.0 to 2.0.0) it throws the exception shown above.

**Comment by kevinpapst** [comment]
Then try to use 127.0.0.1 instead of localhost

**Comment by testload2011** [comment]
Tried, and still result is same. Please refer the attached screen capture. Tried on Google Chrome as well and same result. 

Is the JS getting blocked because origin policy is not set correctly ? When the request doesn't match Same Origin Policy the crossorigin attribute MUST be present for the integrity of the file to be checked. With an integrity set on an external origin and a missing crossorigin the browser will choose to 'fail-open' which means it will load the resource as if the integrity attribute was not set. Ref URL: https://stackoverflow.com/questions/35323268/how-to-solve-resource-requires-the-request-to-be-cors-enabled-resource-has-bee

https://user-images.githubusercontent.com/11069905/216083064-92615340-e0ef-431f-b0db-e5587ac4f700.mp4

**Comment by kevinpapst** [comment]
Kimai needs to run on domain / webroot level. 
Your path is `/kimai2/kimai/public/en/dashboard/` but it needs to be `/en/dashboard/`
