### ISSUE TITLE
exports with cronjobs - user option doesn't work

### ISSUE THREAD

**Issue by Flo-MF** [kimai/kimai#3815]
### Describe the issue

I want to export the timesheet via the export via cronjob für just one user and used the option "--user", but that seems, that it's not working.

When I change the option to "--team", I get an export. The user hast time entrys at the selected time-range.

Here my command for, which is not working:

`kimai:export:create --start=$(date --date "$(date +%Y-01-01) -30 day" +"%Y-01-01") --end=$(date --date "$(date +%Y-%m-01) -1 day" +"%Y-%m-%d") --user=63 --template="xlsx" --locale=de --exported=all --username=export-user --email=mail@domain.tld --subject="Erfasste Zeiten in Kimai" --body="Hallo, anbei findest du einen Export der Zeiten vom 1. Januar vergangenen Jahres bis zum ende letzten Monats. Viele Grüße, Das Kimai Zeiterfassungssystem"`

Here I get this result:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/66617442/216583962-a8827bd5-1c18-4703-b6e0-8a0ba4ce0593.png">

With this command it will be exported successfully:
`kimai:export:create --start=$(date --date "$(date +%Y-01-01) -30 day" +"%Y-01-01") --end=$(date --date "$(date +%Y-%m-01) -1 day" +"%Y-%m-%d") --team=4 --template="xlsx" --locale=de --exported=all --username=export-user --email=mail@domain.tld --subject="Erfasste Zeiten in Kimai" --body="Hallo, anbei findest du einen Export der Zeiten vom 1. Januar vergangenen Jahres bis zum ende letzten Monats. Viele Grüße, Das Kimai Zeiterfassungssystem"`

<img width="861" alt="Bildschirmfoto 2023-02-03 um 11 55 24" src="https://user-images.githubusercontent.com/66617442/216586736-05e11e56-152a-408d-a1ec-a69f0a288f2b.png">

I use Kimai 1.30.5 on a Linux.

Thank you very much!

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.5

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Solution: the export user `--username=export-user` needs to be in the same team like the `--user=63` or needs to a user with `view_all_data` permission (like the regular and system admin).
