### ISSUE TITLE
Currency prefix text on Invoice showing country as opposed to currency ISO

### ISSUE THREAD

**Issue by TGG-RPA** [kimai/kimai#3827]
### Describe the issue

Currency pre-fix showing on invoice appears to be country abbreviation as opposed to currency per ISO standards.  For instance, Canadian shows as "CA" as opposed to "CAD".

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.5 (self hosted)

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
This is not something Kimai decides upon.
The formatting of times/date/currency formatting is done by a library that uses ICU data.
Probably you rendered the invoice in the wrong language.

**Comment by TGG-RPA** [comment]
Could you please advise where this setting is found?
