### ISSUE TITLE
Export PDF Dropdown is missing when done via All Times -> Export

### ISSUE THREAD

**Issue by SkyBladeMP** [kimai/kimai#3836]
### Describe the issue

In Kimai 1 and 2 it is possible to create a PDF export with different templates under the Export menu (there is a dropdown menu for PDF). However, if you want to do an export via "All times" -> Export, the dropdown menu for PDF is missing and you are resticted to the default PDF export template. This bug is not restricted to a specific browser / OS or Kimai Version. This bug even appears in the live-demo on the kimai website (Kimai 1 and Kimai 2).

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.29.1

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![Kimai1 - AllTimes](https://user-images.githubusercontent.com/13415933/217579433-536a621b-e3e0-4c32-89da-58864af067b5.jpg)
![Kimai1 - Export](https://user-images.githubusercontent.com/13415933/217579436-93432088-5c35-41a4-b545-4319a3a834f9.jpg)
![Kimai2 - AllTimes](https://user-images.githubusercontent.com/13415933/217579438-aa633265-4539-4f17-8c2a-ad6355feb3b9.jpg)
![Kimai2 - Export](https://user-images.githubusercontent.com/13415933/217579441-8c5fde48-4e31-41b2-8b01-11fbbee03f81.jpg)

**Comment by kevinpapst** [comment]
The "export module" is for a certain user group, while the "download my hours" function is meant for another purpose. 

I have plans for configurable exports at some point in time, but this is not the time to talk about it.

So this is not a bug and I have no plans to change that in the near future.
