### ISSUE TITLE
Project selecction in timesheet entry now offers all projects even customer is selected

### ISSUE THREAD

**Issue by Mikesch-mp** [kimai/kimai#3838]
### Describe the issue

After an update (dont ask me which) the behavior changed when adding an time entry. Before i select a customer and then the project field is only filled with projects from the selected customers.
Now i select a customer and the list is filled with all projects from all customers.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.5

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![grafik](https://user-images.githubusercontent.com/6574967/217738060-cab9e346-a258-4a2e-a7cf-851cdaf3eb26.png)

**Comment by kevinpapst** [comment]
That is not a bug in Kimai. 
Something is wrong with your environment.
Test the demo for verification.

**Comment by Mikesch-mp** [comment]
Then how can this be fixed. i didnt change any settings or files. Just did the updates and i got this behavior.

**Comment by Mikesch-mp** [comment]
Selecting customer throws this error in the log
```
[2023-02-09 14:26:10] request.INFO: Matched route "get_projects". {"route":"get_projects","route_parameters":{"_route":"get_projects","_controller":"App\\API\\ProjectController::cgetAction","_format":"json"},"request_uri":"https://kimai.ckc-it.de/api/projects?customer=20&end=&start=2023-02-09T14%3A26%3A00&visible=1","method":"GET"} []
[2023-02-09 14:26:10] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "No @ParamInterface configuration for parameter 'globalActivities'." at /opt/kimai2/vendor/friendsofsymfony/rest-bundle/Request/ParamFetcher.php line 88 {"exception":"[object] (InvalidArgumentException(code: 0): No @ParamInterface configuration for parameter 'globalActivities'. at /opt/kimai2/vendor/friendsofsymfony/rest-bundle/Request/ParamFetcher.php:88)"} []
```

**Comment by kevinpapst** [comment]
Then clear your cache properly `cd kimai; rm -r var/cache/*;bin/console kimai:reload`

**Comment by Mikesch-mp** [comment]
> Then clear your cache properly `cd kimai; rm -r var/cache/*;bin/console kimai:reload`

Did it, still same error

**Comment by kevinpapst** [comment]
`git status`?

**Comment by Mikesch-mp** [comment]
```
root@kimai:/opt/kimai2# git status
HEAD detached at 1.30.7
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        db_backup/
        public/ckc-it/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by kevinpapst** [comment]
See this (the last commit in the grey card header):
<img width="1308" alt="Bildschirm­foto 2023-02-09 um 14 37 10" src="https://user-images.githubusercontent.com/533162/217827711-51c23a79-6174-4c5f-b679-f1dc06188638.png">

If this line  does not exists in your installation, it is your environment:
https://github.com/kimai/kimai/blob/1.x/src/API/ProjectController.php#L99

If this line exists and you still see the error, it is your environment => restart php-fpm to clear opcode cache.

**Comment by Mikesch-mp** [comment]
the line is there, but still the same error. even i restart apache (no fpm) or restart the vm.

**Comment by kevinpapst** [comment]
`composer install ...` executed?

**Comment by Mikesch-mp** [comment]
yes, still the same error.

**Comment by Mikesch-mp** [comment]
i even updated composer from 2.2.6 to 2.5.2. i remembered that that was a problem before

**Comment by Mikesch-mp** [comment]
i found it (Head->Table)! It was the redis cache i configured (https://www.kimai.org/documentation/redis.html)
If you use redis you need to flush it after an update/upgrade.

```
redis-cli --no-auth-warning -a 'secretpassword' flushall
```
and now everything works fine again

**Comment by kevinpapst** [comment]
Aha, so my initial comment was correct...

**Comment by Mikesch-mp** [comment]
Yes :) Will send a commit for the docs to add redis database flush if redis is used.
