### ISSUE TITLE
Export times to CSV

### ISSUE THREAD

**Issue by micoots** [kimai/kimai#384]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The demo seems to have the feature to generate a monthly report of times worked, however the download icon just presents a webpage of the times. Really need this export in CSV format.

CSV ideally, but can also do Excel if you like.

These exports can then be easily imported for suppliers who pay our invoices, into their accounting systems etc.

**Describe alternatives you've considered**
There's really no alternative to CSV exports, it's a critical requirement of time tracking software.

**Additional context**
None.

**Comment by kevinpapst** [comment]
There is really no alternative to reading the docs and a proper testing phase, if you plan to use a software that is crucial to your business:
https://github.com/kevinpapst/kimai2/blob/master/var/docs/invoices.md

For everything else, please open a new feature request with more details.
