### ISSUE TITLE
Request for "SAML group" to "Kimai Team" mapping feature

### ISSUE THREAD

**Issue by TSmigielski** [kimai/kimai#3846]
### Describe the problem

I have integrated a SSO service with SAML for my company's Kimai instance. And everything works flawlessly, except for the Team mapping. Which would be an amazing feature to have.

### Describe the solution you'd like

I've looked through the code a bit, and as far as I can tell, this feature isn't implemented yet, which is a bummer, hence the "Request".

**Comment by kevinpapst** [comment]
You can help testing this: #4770 to see if it works. 
I have no matching setup and I am not able to verify the solution from @the-glu

**Comment by TSmigielski** [comment]
Unfortunately I've left that company in November last year. I wish you the best of luck though, Kimai was one of my favorite tools to use.

**Comment by kevinpapst** [comment]
Hahaha, all the best to you! 

Closing here, as the PR is already open.
