### ISSUE TITLE
php.critical

### ISSUE THREAD

**Issue by BeckeBauer** [kimai/kimai#3847]
### Describe the issue

After updating to 1.30.7, I get the following error when opening some of the links (like teams, about Kimai):

`php.CRITICAL: Uncaught Error: Failed opening required '/kimai2/var/cache/prod/ContainerAwVRQer/getAboutControllerService.php' (include_path='.:/usr/share/pear') {"exception":"[object] (Error(code: 0): Failed opening required`

Other links work, however (like my times). Any help is appreciated

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.7

### How do you run Kimai?

Synology

### Which PHP version are you using?

8.0

**Comment by kevinpapst** [comment]
Please: I bet you know for sure that this is not a bug, or does it happen in the demo?

You have to restart PHP after clearing the cache/update ... otherwise opcode cache will still use old references.

**Comment by BeckeBauer** [comment]
Thank you for pointing me in the right direction. After what feels like dozens of upgrades, I never needed to restart PHP before so that I did not think of it. 

By the way, if someone using a Synology NAS with PHP 8.0 as Kimai host happens to stumble about the same issue, this is the command you need to execute: `systemctl restart pkgctl-PHP8.0.service`

**Comment by buzter** [comment]
> Thank you for pointing me in the right direction. After what feels like dozens of upgrades, I never needed to restart PHP before so that I did not think of it.
> 
> By the way, if someone using a Synology NAS with PHP 8.0 as Kimai host happens to stumble about the same issue, this is the command you need to execute: `systemctl restart pkgctl-PHP8.0.service`

Thx for the hint. Did not update to 1.30.7 yet but that will save me trouble.
