### ISSUE TITLE
Update Teams when user is deactivated

### ISSUE THREAD

**Issue by HeinzWuert** [kimai/kimai#3850]
### Describe the problem

When deavtivating a user he still reamins in all teams.

### Describe the solution you'd like

When deavtivating a user he schould be deleted from all teams.

**Comment by kevinpapst** [comment]
Why?

**Comment by HeinzWuert** [comment]
Teams is also used to inform management about deployed personnel.
Otherwise another database must be used. Thats nonsens when all informations are in Kimai available.

**Comment by kevinpapst** [comment]
The new version has these colored status dots:
<img width="392" alt="Bildschirm­foto 2023-02-15 um 14 32 39" src="https://user-images.githubusercontent.com/533162/219041340-ee7dc7f3-af73-4eb1-8ad1-ffd15b8d2fbc.png">

Blue means teamlead, red means deactivated.

**Comment by HeinzWuert** [comment]
thanks a lot!

**Comment by kevinpapst** [comment]
I should have added the question: does that help somehow?

Any idea how else we could achieve your goal?

Without giving it too much thought, I don't really like the idea of automatically removing a user from teams. What if deactivation was a test or a mistake? Or the user is reactivated after two weeks ... and you probably can't remember which teams he was a member of.

I know the behavior is not consistent, as it was never really defined what should happen.
But if we now plan to rethink the workflow, I'd like to see the whole picture.

**Comment by BeckeBauer** [comment]
Maybe, there could be a switch like with customers and projects to make visible all team members (including deactivated users) wheras the user becomes automatically invisable upon deactivation?
I personally wouldn't mind if the user is deleted from the team upon deactivation. Maybe, team assignment could be stored in the database and reasigned upon re-activation?

**Comment by HeinzWuert** [comment]
We do not store teams beyond the end of the project. On the contrary, we are missing a function that at least filters out teams if a project of the same name no longer exists (invisible) in order to delete them.
So Kevin's idea of only marking deactivated users isn't so bad, because that way you have a history of who was involved in a project. 
In order to extend the history idea, you would not have to delete all users who leave a project prematurely, but mark them as "resigned" in the team.
In fact, when history is needed the belonging team of a project should be saved too, set to invisble like his project.

**Comment by BeckeBauer** [comment]
I do not see an advantage to have a team history. If you need to know who did what within a certain project during a certain period, you just export the timesheets and filter the users. What kind of data would you need as team history? The date when the user was assigned or "deactivated" (even if it does not necessarily means that he/she worked during this period)?

**Comment by HeinzWuert** [comment]
As already noted, we do not need this type of history. That was just an idea in case anyone is thinking along those lines.
As suggested by Kevin with colored dots, it's ok for us!

**Comment by kevinpapst** [comment]
Sounds as if this can be closed
