### ISSUE TITLE
use parsedown-extra for rendering markdown

### ISSUE THREAD

**Issue by lduer** [kimai/kimai#388]
## Description

As the documentation files are getting bigger and bigger, I'd like to suggerst to use the [erusev/parsedown-extra](https://github.com/erusev/parsedown-extra)-Parser for rendering the Help-Pages. There are some  more options like linking to headings with an ID, which could be useful.
```
## Adding invoice calculator {#invoice-calculator}
```
is parsed to 
```
<h2 id="invoice-calculator">Adding invoice calculator</h2>
``` 
But there is a problem, that currently the twig-replacer (https://github.com/kevinpapst/kimai2/blob/master/templates/help/index.html.twig#L9) doesn't find the ".md" part in strings like `
[Adding invoice calculator](developers.md#invoice-calculator)` to convert the link to `<a href="developers#invoice-calculator">` 

Maybe we need a better/other replacement method in https://github.com/kevinpapst/kimai2/blob/master/templates/help/index.html.twig#L11, because the `strtr()` (used by the twig `|replace`-Filter) doesn't support regex.

**Comment by kevinpapst** [comment]
If possible I'd like to find a solution that doesn't break the documentation here on GitHub.
But if that is not completely possible, I am fine with pages that at least render "kind of normally".

**Comment by lduer** [comment]
Oh yes, I understand. So it'd be good to have some github-like IDs?!

As an alternative for the previous idea: create an own extension class to `parsedown` - e.g. as `src/Uils/ParsedownExtension.php`. This gives the possibility to hook into the `blockHeader` method to add some attributes

```
    protected function blockHeader($line)
    {
        $block = parent::blockHeader($line);
        $id = $this->convertTitleToID($block['element']['text']);
        $block['element']['attributes'] = [
            'id' => $id
        ];

        return $block;
    }
```

I've done some research how github convertes the heading-text to the ID. The only thing I found were user-comments, no official information (https://github.com/jgm/pandoc/issues/2821#issuecomment-319942807 and https://github.com/jgm/pandoc/issues/2821#issuecomment-319942807) But there, they speak about the following order: 

+ It downcases the header string
+ remove anything that is not a letter, number, space or hyphen
+ changes any space to a hyphen.
+ If that is not unique, add "-1", "-2", "-3",... to make it unique


I like to contribute this feature.

**Comment by kevinpapst** [comment]
That would be awesome. I think the only special characters in Kimai docu headers are brackets.
Being able to create links to headings that work in Kimai and on GitHub would be awesome.

**Comment by lduer** [comment]
Added the Parsedown Extension as written above. The missing feature is now the `strtr()` for links including `#`

**Comment by lduer** [comment]
For the `.md`-replace in https://github.com/kevinpapst/kimai2/blob/master/templates/help/index.html.twig#L9: I am thinking about a `preg_replace` were the `.md`  is removed from all href-tags with a relative URL.

**Comment by lduer** [comment]
Maybe I've not expressed myself clearly enough before:

1. The `replacer` array removes all `.md"` strings (including the ´"´) from the html-code and adds the `"`.
2. Links with anchors are not found because of `filename.md#anchor"` in contrast to `filename.md"`
3. Simply changing to`.md` (without `"`) in the code could be a fix, but I think of paths/URLs e.g. to other github recources or md-files which should not be blindly removed.
4. My suggestion is to replace only the path inside the `href`. This needs to be done with regex.
5. The twig function `replace()` uses the php `strtr()` to replace parts of strings, but someting like `preg_replace` is needed.

**Comment by kevinpapst** [comment]
Ok, thanks for the clarification. 
Could be done on the controller side, which already knows about the filenames and loads the content.

**Comment by lduer** [comment]
For the missing "replacement", I've added the pull request #482

I've noticed, that after klicking on a link with an achor (e.g. `configurations#config-files`) the browser does not scroll to the desired position, although klicking the anchor icon left to the headline itself works (added in https://github.com/kevinpapst/kimai2/commit/321ac74b6af9f9a55f88b784c3e37dbcb4464966)

Can you test it. Maybe we need some Javascript to scroll to the position?

**Comment by lduer** [comment]
Another question regarding the documentation: I've detected some links in the doc-files which are referencing to some config-files (e.g. `Our code-styles are configured in [.php_cs.dist](../../.php_cs.dist).`). 

Of course, rendering the doc-files inside the help section in kimai will create broken links. What do you think about replacing the links to the github file (e.g. `https://github.com/kevinpapst/kimai2/blob/master/.php_cs.dist`

**Comment by kevinpapst** [comment]
Regarding your latest comment, [the replacer](https://github.com/kevinpapst/kimai2/blob/master/templates/help/index.html.twig#L11) takes care about these links. They work for me on GitHub and within Kimai.

**Comment by kevinpapst** [comment]
And clicking the a link with an anchor works for me as well, it just scrolls a bit to deep. 
I only have a "problem" when using the sticky layout where the page header is floating above the text header.

**Comment by kevinpapst** [comment]
Hm true, I just tested with Safari yesterday. On Mac-Firefox it doesn't work for me as well on page change, but when I hit enter in the URL bar after the page change, it scrolls down to the right position. 
So a browser problem and nothing we can fix, as I'd like to avoid using Javascript for scrolling.

**Comment by kevinpapst** [comment]
I lost overview, is this issue "finished" or do you see other open tasks?

**Comment by lduer** [comment]
Finished!

- [x] Anchor is generated the same way as in Github
- [x] Links display anchor icon
- [x] Anchor links are parsed correct inside the controller

And as the firefox seems not to be solved next time (research: there are some open bugs from many years) and javascript should not be used for scroling, all tasks are done :)
