### ISSUE TITLE
Timesheet PDF export using API

### ISSUE THREAD

**Issue by weissdanny** [kimai/kimai#3884]
### Describe the problem

Hello,
I'd like to propose adding an API Method for exporting Timesheets as PDF to process them further using accounting tools.
For Instance to attach Timesheet.pdf to Invoices in tools like lexoffice, sevDesk or easybill for sending to a customer.

### Describe the solution you'd like

It would be great if the API Method allows to get one timesheet per customer in a defined period of time, saving it as a pdf in a specific folder and marking it as exported.

**Comment by tstrohmeier** [comment]
This would be great!

**Comment by kevinpapst** [comment]
If your company requires such a feature, you can always contact me for contract work: a custom plugin that offers such an endpoint.

But this requirement is nothing that I will add to core.
