### ISSUE TITLE
Invoicing export - 500: Internal Server Error

### ISSUE THREAD

**Issue by theprofilinglabs** [kimai/kimai#390]
**Describe the bug**
Oops! An error occured.
500: Internal Server Error
An unexpected error occured, please try again. You may have found a bug, so please contact your administrator if the problem doesn't go away after you tried it again.

**To Reproduce**
1. Go to 'invoices'
2. Click on filter '
3. clear all filter boxes
4. select a customer - app fails 

**Expected behavior**
All entries for a customer exported
**Screenshots**
![image](https://user-images.githubusercontent.com/6179020/48000590-d6ce6b80-e0fd-11e8-8988-8f72aafd6419.png)
![image](https://user-images.githubusercontent.com/6179020/48000647-03828300-e0fe-11e8-91d5-5d9aa1511241.png)

**Desktop (please complete the following information):**
 - Browser [Opera

**Comment by kevinpapst** [comment]
Thanks for finding! I'll fix it asap.
