### ISSUE TITLE
Immediately start clock and add details later.

### ISSUE THREAD

**Issue by sollermun** [kimai/kimai#3903]
### Describe the problem

Sometimes I need to start a new time measurement immediately and would prefer to add the details later, e.g. if there is an incoming call. Ideally, I would be able to just start the clock immediately and then, after the call, assign the entry to a project and task. Right now, it is not possible to start the clock without providing some basic information, re: project, task, etc. I don't want to multitask during the call as it is rude and disruptive.

### Describe the solution you'd like

Hitting the play button would immediately start measuring time. When the stop button his pressed, then a popup shows up asking for the project, task, description, etc.

### Describe alternatives you've considered

N/A

### Screenshots

N/A

**Comment by kevinpapst** [comment]
See #3891 - reopening the same issue will not help. Discuss in the original one.
