### ISSUE TITLE
Drag & Drop in Calendar View a full day

### ISSUE THREAD

**Issue by jb-alvarado** [kimai/kimai#3908]
### Describe the problem

As written under the discussion #3907, it is not possible to drag and drop a task on the calendar that represent a full working day. When dragging a task to a day the working time is only ~1 hour long.

For example: We are using kimai also for tracking sick- and holidays. When you have to add them later, after two weeks of vacation, it need more time to drag a holiday into the calendar, open the task and set the target time. 

### Describe the solution you'd like

When dragging a task from the left list to a day, it would be nice when we don't have to edit the task to set the right length. This could be done, that the list item remembers the last give length.

A better why is maybe, to have a global setting where the admin can configure a fixed length for dragged tasks.

**Comment by kevinpapst** [comment]
But you know, that you don't have to "edit" these new items, but can use drag & pull to set the duration?

**Comment by jb-alvarado** [comment]
Yes in the week view, you are right, that is a bit more easy.

**Comment by kevinpapst** [comment]
Holidays and such should be booked using the "Working hours, vacation, illness (controlling)" plugin:
https://www.kimai.org/store/controlling.html
