### ISSUE TITLE
PHP Error while trying to install "DeductionTimeBundle 1.0"

### ISSUE THREAD

**Issue by schulzc21** [kimai/kimai#3918]
### Describe the issue

Upon reloading Kimai while trying to install "DeductionTimeBundle 1.0" in our running Kimai 1.30.11, I get:

PHP Fatal error:  Declaration of KimaiPlugin\DeductionTimeBundle\Timesheet\Calculator\DeductionTimeCalculator::calculate(App\Entity\Timesheet $record, array $changeset): void must be compatible with App\Timesheet\CalculatorInterface::calculate(App\Entity\Timesheet $record) in /var/www/kimai/var/plugins/DeductionTimeBundle/Timesheet/Calculator/DeductionTimeCalculator.php on line 19

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.11

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Logfile

...no log information regarding this problem.

**Comment by kevinpapst** [comment]
this has nothing to do with kimai core, open a question (not a bug) in the correct repository
