### ISSUE TITLE
Users can register even when user registration is disabled 

### ISSUE THREAD

**Issue by lbm-services** [kimai/kimai#3920]
### Describe the issue

I have registered bogus users which may have bypassed the registration form.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.28.1 

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![Bildschirmfoto vom 2023-03-10 16-45-48](https://user-images.githubusercontent.com/5830407/224360790-b41a7af6-e0a3-4d47-99b8-3961992eea99.png)

**Comment by kevinpapst** [comment]
Unlikely. If the config is turned off, it cannot work:
https://github.com/kimai/kimai/blob/1.28.1/src/Controller/Security/SelfRegistrationController.php#L55

You can test if it is enabled at https://example.com/de/register/

Check System > Settings and make sure that it is really turned off.
<img width="544" alt="Bildschirm­foto 2023-03-10 um 18 47 08" src="https://user-images.githubusercontent.com/533162/224387309-0c4070f5-e409-4e3c-9d96-6462be581168.png">

A long long time ago, there was some docu on how to ONLY remove the links from the login form.
I think that chapter was completely erased from the docs. And that was years ago.

But just in case: show me your local.yaml.

**Comment by kevinpapst** [comment]
You are posting a really super serious & critical report in the public and then do not report back. 
Can you please share some insights asap.

**Comment by kevinpapst** [comment]
Considering that there are thousands of open Kimai installations out there and nobody reported such an issue before, I am not convinced yet. But if your report is true, this is critical and needs to be solved.

Can we investigate further @lbm-services ?

**Comment by Thewhiteevil** [comment]
Hi,

Can I help you to verify this report?

May I know where can I find that user registration turn off?

**Comment by kevinpapst** [comment]
Closing.

**Comment by kevinpapst** [comment]
Public accusations like that and then no more feedback really pisses me off.
I can only assume that you did not turn off user registration
