### ISSUE TITLE
Inconsistent API swagger definition

### ISSUE THREAD

**Issue by Specter-13** [kimai/kimai#3923]
### Describe the issue

Hello,
I'm creating .net MAUI app based on Kimai and I used NswagStudio to autogenerate API client.

I've found multiple inconsistencies between swagger API specification and real response data. The inconsistencies were mainly in model classes.

So far I've found following problems:

1. Using api endpoint `/api/timesheets/recent`
  - Model `Project` has `customer` field as `integer`, however API returns  `Customer` type (see first screenshot).
  
2. Problem in `UserEntity` in model `TeamMembership`
  - user can be added to multiple teams in Kimai, but API specification of TeamMembership only allow to be user in one team (see second screenshot)
  
There can be more problems, so far I've found these.
Thanks.

Device: Windows11
Browser: Microsoft Edge
Kimai running in docker on localhost

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.5

### How do you run Kimai?

Docker

### Which PHP version are you using?

unknown

### Screenshots

1. Api endpoint `/api/timesheets/recent` - model Project
Left - model in swagger definition
Right - api response
![image](https://user-images.githubusercontent.com/56168909/224715948-71bd3974-093f-45fa-8483-f19fac1428f9.png)

2. UserEntity
![image](https://user-images.githubusercontent.com/56168909/224718067-f8f11d2a-e901-42e0-8563-6332c8215fd4.png)

**Comment by kevinpapst** [comment]
Thanks for the report 👍 
See PR #3922 or commit https://github.com/kimai/kimai/pull/3922/commits/9636db97e9524728a9e8a692c2663ca89da33bd1 for the fix. If you apply it locally, you have to reload the cache.

And please open new issues, if you find more problems.
