### ISSUE TITLE
User creating activity and projects

### ISSUE THREAD

**Issue by resistingdestiny** [kimai/kimai#393]
## Description

Thanks so much for releasing it. Have installed it and played around a little, and as far as I can tell only the Super Admin is able to create projects. How can a user define their own projects and activities (if they can at all) and track those so they don't appear globally? Apologies if this is obvious - I'm quite new to all this and can't seem to find anything on it!

**Comment by resistingdestiny** [comment]
I guess the work around is to make every user a SUPER_ADMIN.. if this is possible? And delete normal user functionality

**Comment by kevinpapst** [comment]
Hey, thanks for your kind works. This is currently not possible without changing the code.
It is definitely not desirable to make everyone a SUPER_ADMIN. The role ADMIN at least denies access to the user administration.I will work on a better permission system in the near future, then you will be able to define your own access rules. 
Having said that this, your request about user specific projects will not be covered by this. Lets wait if more users are interested in this.

**Comment by kevinpapst** [comment]
You could have a look into the linked pull requests #424, which allows to define permissions in more detail. So you could allow your users to create activities and projects on their own, without having all SUPER_ADMIN permission.
