### ISSUE TITLE
"Service Unavailable" sometimes on some pages after update 2.0.9.

### ISSUE THREAD

**Issue by juup** [kimai/kimai#3940]
### Describe the issue

After update to 2.0.9. I get following error sometimes:
```
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```
It's very often on _quick_entry_ and almost always on _timesheet_. _Calendar_ for example works.

Running on all-inkl shared server.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.9.

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Logfile

There are no entries for that time, when the error happens.

**Comment by kevinpapst** [comment]
Yeah, search discussions for `all-inkl`.

It is only on their systems. 
They are running a crappy PHP extensions, which they don't want to disable.
That is causing Kimai to crash.
It is not Kimai itself. 
I am closing this issue, there is a lot of information available in the discussions.

**Comment by juup** [comment]
Thanks for quick response.
Before I only searched for the error and not for all-inkl. Will do so and hopefully find a solution.

**Comment by kevinpapst** [comment]
Sorry, but I talked about that problem way too often 😁 so please read all the connected issues and discussion.

There is only some weird workaround by adjusting a config file. I hope that works for you!

**Comment by juup** [comment]
Da es wohl nur all-inkl-Kunden betrifft auf deutsch, hoffe das ist i.O:
Habe jetzt die verschiedenen Beiträge durchgeschaut und finde keinen mit einem Hinweis auf eine angepasste Konfigurationdatei. 
Ich nehme an, dass Du dieses Thema meinst: https://github.com/kimai/kimai/discussions/2859
Da die Benutzer teilweise mit all-inkl im Kontakt waren, habe ich dies ebenfalls versucht um zu prüfen, ob von deren Seite etwas anders eingestellt wurde. Leider geht jetzt das Schwarze-Peter-Spiel los, da all-inkl. behauptet Kimai sei das einzige Programm mit IonCubeLoader-Problemen.
Kannst Du mir bitte angeben, welchen Workaround Du meinst. Danke

**Comment by kevinpapst** [comment]
I added a link to https://github.com/kimai/kimai/discussions/2859
There is enough prove that ioncubeloader tries to interpret (symfony/doctrine) application cache files and crashes. This is a ridiculous bug. 

Thousands of Kimai installations out there work without any issue, but every now and then a new All-Inkl user shows up with the same issue. I understand that this is frustrating for you. Now imagine how I feel after spending years of work with Kimai and then hearing again and again the same problem from customers of the same hosting provider. 

You pay All-Inkl for hosting, and they deliver a broken product. Talk to them.
I am not willing to spend any more of my unpaid time on that topic.
