### ISSUE TITLE
Invoice salutation

### ISSUE THREAD

**Issue by juup** [kimai/kimai#3942]
### Describe the problem

Would be great to set the gender of ${customer.name} and the way how to salute.

### Describe the solution you'd like

In german the result vor invoices look like:
Sehr geehrt**e** Frau Name / Sehr geehrt**er** Herr Name 
Hallo Frau / Herr ...

### Describe alternatives you've considered

Payment terms should be used in other ways, so the workaround from https://github.com/kimai/kimai/issues/1502 with payment terms is not a good option.

**Comment by kevinpapst** [comment]
Not in core.

Use the Custom-Fields plugin for that: https://www.kimai.org/store/custom-fields-bundle.html

Then you can independently define the salutation for each customer.
