### ISSUE TITLE
Site Maintenance on ubserspace installation

### ISSUE THREAD

**Issue by aretaon** [kimai/kimai#3948]
### Describe the issue

I installed kimai according to https://lab.uberspace.de/guide_kimai/. 
When I browse to the page, I get "Site Maintenance"

> We’ll be back soon!
> 
> Sorry for the inconvenience but we’re performing some maintenance at the moment. If you need to you can always [contact us](mailto:#), otherwise we’ll be back online shortly!
> 
> — The Team

It is mentioned on the kimai github that version 1 is shipped in maintenance since 2023, but I can't figure out how to disable maintenance. Installing Version 2 results in an error "  The command "kimai:reset:locales" does not exist. " so I switched back to the latest stable release.

I'm glad for any helpful hints!

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.11

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.2

### Logfile

No logfile in kimai/var/log.

**Comment by kevinpapst** [comment]
Kimai has no maintenance mode.

What happens when you click "contact us". 100% the email of Uberspace support opens => contact them.

@nichtmax your maintenance page needs clarification

**Comment by aretaon** [comment]
Thanks for the swift reply. The „contact us“ did not link anything so I was assuming this was related to the fresh kimai install.

Anyway I will have a closer look at the uberspace configuration.
