### ISSUE TITLE
Unrecognized option "kimai_saml"

### ISSUE THREAD

**Issue by bykof** [kimai/kimai#3956]
### Describe the issue

When I want to start Kimai in version 2.0.10 and use saml configuration from kimai 1.10.3 in `local.yaml` I get the following error: 

```
[ERROR] Unrecognized option "kimai_saml" under
kimai_1  |          "security.firewalls.secured_area". Available options are
kimai_1  |          "access_denied_handler", "access_denied_url", "access_token",
kimai_1  |          "context", "custom_authenticators", "entry_point", "form_login",
kimai_1  |          "form_login_ldap", "host", "http_basic", "http_basic_ldap",
kimai_1  |          "json_login", "json_login_ldap", "kimai_ldap", "lazy", "login_link",
kimai_1  |          "login_throttling", "logout", "methods", "pattern", "provider",
kimai_1  |          "remember_me", "remote_user", "request_matcher", "required_badges",
kimai_1  |          "security", "stateless", "switch_user", "two_factor", "user_checker",
kimai_1  |          "x509".
```

My `local.yaml` file looks like follows:

```
security:
    firewalls:
        secured_area:
            kimai_saml: ~

kimai:
    saml:
        activate: true
        title: Login with Azure AD
        mapping:
            - ...
        roles:
            resetOnLogin: true
            attribute: ...
            mapping: []
        connection:
        idp:
            entityId: "..."
            singleSignOnService:
            url: "..."
            x509cert: "..."
        sp:
            entityId: "..."
            assertionConsumerService:
            url: "..."
            singleLogoutService:
        url: "..."
        debug: true
    user:
        registration: false
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.10

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Contrary to your click, you have not read the documentation:
https://www.kimai.org/documentation/saml.html
Therefor closing

**Comment by bykof** [comment]
I fixed it now by checking my config carefully. Sorry for bothering you. I thought the documentation is still for 1.X version.

**Comment by kevinpapst** [comment]
I agree, the versioning needs to be made more clear.

<img width="732" alt="Bildschirm­foto 2023-03-30 um 21 24 03" src="https://user-images.githubusercontent.com/533162/228942462-7e3c602c-b2cc-4a57-8e41-d59be7458459.png">

The version chooser is misleading. Thanks for pointing it out!
