### ISSUE TITLE
Parse descriptions into a section on the invoice

### ISSUE THREAD

**Issue by jzonthemtn** [kimai/kimai#3959]
### Describe the problem

The descriptions entered for each day's work often include ticket numbers for JIRA items or items in other ticket systems. After generating invoices, I often manually go through those descriptions and make a list of the issues that were worked in the period the invoice covers.

### Describe the solution you'd like

I would like a feature (or a plugin) that can automatically parse the descriptions for a regular expression that matches the ticket numbers and add those tickets (like `PROJ-1234`) to a section on the invoice. Ideally, I would be able to provide one or more regular expressions, e.g. `[A-Z]{2,}-\d+` to match Jira and another to match GitHub issues `#123` for when multiple issue systems have been used.

### Describe alternatives you've considered

Just doing it manually after invoice generation.

**Comment by kevinpapst** [comment]
Thanks for the donation 👍 

Sounds as if that should be possible in a custom invoice template. You can loop the invoice lines, match the comment against your regexp and the merge it into an array with all ticket ids. Then convert that list into an info box with "We worked on these issues this month".
A plugin would not work, as a plugin could only provide the data, but not render the list correctly.
And asyou have to create a custom template anyway, you can directly parse the invoice lines yourself.

**Comment by jzonthemtn** [comment]
Thanks for the idea! I'll give that a shot.

**Comment by kevinpapst** [comment]
Ping me if you need help with the twig part. 
Merging arrays is counter intuitive, in case you never touched that templating language.
