### ISSUE TITLE
Screenshot/Screen Capture functionality

### ISSUE THREAD

**Issue by Ireheart** [kimai/kimai#3969]
### Describe the problem

Implement Screenshot/Screen Capture functionality

### Describe the solution you'd like

Implement Screenshot/Screen Capture functionality

### Describe alternatives you've considered

timedoctor

**Comment by kevinpapst** [comment]
Go for Timedoctor. I will NEVER add such a privacy breaking asshole feature. 

If you can't trust your employees, it's probably because you don't pay them properly.
