### ISSUE TITLE
Standard Docker Image booting but database not writeable

### ISSUE THREAD

**Issue by Haidy777** [kimai/kimai#397]
**Describe the bug**
As described in #376 I tried to run the docker image. Sadly without luck. Today I tried again and used the `test.sqlite` file from the data directory. The DockerImage booted and it seems like it would be working, but the problem is that it seems that the database isn't writeable.

 @tobybatch Thanks for the idea with the file.

As before I'm trying to run the whole thing through Plesk, with the Docker Extension.
![image](https://user-images.githubusercontent.com/5011101/48222266-76a52700-e394-11e8-82d3-49d29a708c18.png)
As you can see there are several Port-Mappings, the working one is 8080 to 32772 which is then proxied through Plesk to a TLD.
Also you can see the Volume-Mapping at the bottom, which links the sqlite-File.

The Error:
![image](https://user-images.githubusercontent.com/5011101/48222387-ca177500-e394-11e8-8609-7c2f2bac1ca3.png)

I think it has to be something with the file permissions. `chmod`ing it to 777 works, but I don't think that should be the solution.

**Comment by tobybatch** [comment]
@Haidy777 You may want to use the container that attaches to a SQL DB.  https://github.com/tobybatch/kimai2/tree/master/prod

**Comment by kevinpapst** [comment]
Can you show us an shell output from the kimai directory: `ls -la var/data/`

**Comment by Haidy777** [comment]
@tobybatch Thanks for your response. As it's only a testing setup I thought I'll give `sqlite` only a try.
It works when you chown the file to `www-data`. Not sure why I didn't test that :)

@kevinpapst I made two screenshots for you, the first one shows the host system, the second one the docker image.
![image](https://user-images.githubusercontent.com/5011101/48269385-bd982880-e437-11e8-8a5a-04c18c4dc2c2.png)
![image](https://user-images.githubusercontent.com/5011101/48269398-c688fa00-e437-11e8-84e6-b9c882d9be88.png)

Maybe this step should be added to the docs.

**Comment by kevinpapst** [comment]
@Haidy777 It was added today: https://github.com/kevinpapst/kimai2/blob/master/var/docs/docker.md#developing-against-the-docker

@tobybatch I tested the ID 33 (as per new docu) on three systems. 

Mac OS:  
`uid=33(_appstore) gid=33(_appstore) groups=33(_appstore),12(everyone),61(localaccounts),701(com.apple.sharepoint.group.1),100(_lpoperator)`

Linux version 3.10.0-714.10.2.lve1.4.79.el7.x86_64 (xxx) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Thu Jan 4 13:30:50 EST 2018
id: 33: User does not exist`

Linux version 4.4.0-112-generic (xxx) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018
`uid=33(www-data) gid=33(www-data) groups=33(www-data)`

Is 33:33 the best command for cross-platform support?

**Comment by kevinpapst** [comment]
Aha, okay. So I was wrong because you have to execute the command on the host. I still have a long way to go before I feel confident handling docker ...

Is ist possible to find a permission setting that works inside and outside the box and still is secure?
For example only `chgrp 33 kimai.sqlite && chmod g+w kimai.sqlite` to prevent permission problems between host and docker.

**Comment by kevinpapst** [comment]
And btw @Haidy777 SQLite is really only meant for development - I can't safely recommend it for production, as it still has some flaws compared to MySQL.

**Comment by Haidy777** [comment]
Sure, thanks again for the help!
