### ISSUE TITLE
Add a field to register "previously worked" hours

### ISSUE THREAD

**Issue by iwa** [kimai/kimai#3976]
### Describe the problem

I'm helping a little business to go from good old excel files to Kimai for their timetracking needs
They have on-going projects for years now and it would be pretty time-consuming to input all the hours of every employees who worked on it for the last years manually...
But they still want to be able to get all the stats in one place, to make things easier to manage and calculate

### Describe the solution you'd like

Would it be possible to add in the Projects configuraiton a field like "Previously Done Hours" or something similar, that would add up to the total hours worked of the project

### Describe alternatives you've considered

An easy way to import all the hours done for every employees? I don't really understand the scheme that needs to be used :/

**Comment by kevinpapst** [comment]
Convert Excel to CSV and use the Importer Plugin for the previous Excel-based times: 
https://github.com/kevinpapst/ImportBundle

Or simply create one huge time entry in the past, start 01.01.2000 with e.g 3000 hours for each project.

The field is not necessary IMO. Thanks for helping your client with Kimai 👍
