### ISSUE TITLE
invalid Kimai minimum version in extra.kimai.require

### ISSUE THREAD

**Issue by chymian** [kimai/kimai#3977]
### Describe the issue

this is a coudron.io installation.
lately the cldrn- team updated kimai.
since then, the following error hinders kimai starting.

restoring older backups did not solve the pbl.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.x

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

Apr 18 15:31:22 => Ensure directories
Apr 18 15:31:22 => Create cloudron.yaml
Apr 18 15:31:22 => Ensure permissions
Apr 18 15:31:22 => Run installer
Apr 18 15:31:22
Apr 18 15:31:22 In PluginMetadata.php line 59:
Apr 18 15:31:22
Apr 18 15:31:22 Bundle "RecalculateRatesBundle" defines an invalid Kimai minimum version in
Apr 18 15:31:22 extra.kimai.require. Please provide an integer as in Constants::VERSION_ID
Apr 18 15:31:22 .

**Comment by chymian** [comment]
before that happened, 2.0.4 was running smoothly.
updating it a week ago to 2.0.5 brought up the error.
for testing purpose I installed a 2 week old backup, which shows the same error. 
what generates that?

**Comment by kevinpapst** [comment]
Upgrade the plugin to a compatible version

**Comment by kevinpapst** [comment]
Ah, RecalculateRatesBundle ist not needed anymore. 

Delete the entire directory under kimai: `var/plugins/RecalculateRatesBundle`

**Comment by chymian** [comment]
@kevinpapst, thanks, removing the plugin did the job.
there is a cloudron forum entry as well, if somebody looks for it: 
https://forum.cloudron.io/topic/9022/err-invalid-kimai-minimum-version?_=1681806015381

dankeschön
