### ISSUE TITLE
Custom fields plugin: Custom timesheet fields not shown on Docx-invoice

### ISSUE THREAD

**Issue by Sarmingsteiner** [kimai/kimai#3978]
**SOLUTION: It works now, after uploading the Docx-invoice-template and deleting the cache another time.**
Nevertheless, the value **${entry.meta.annotations#xx}** is shown for "old" timesheet entries without any value in the custom field.

We have created a custom timesheet field called **annotations** with the help of the custom fields plugin.

According to the invoice documentation, **${entry.meta.foo}** is the variable for custom timesheet fields (at least for self-created custom fields).
So we added to our Docx-invoice-template the variable **${entry.meta.annotations}**

However, we only get the following output in the final Docx-invoice:
${entry.meta.annotations#1}
${entry.meta.annotations#2}
${entry.meta.annotations#3}
etc.

So, is there another variable name / syntax for custom timesheet fields created with the custom fields plugin?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.11

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Please share the exact definition of the field with screenshots and show me an example timesheet.

**Comment by kevinpapst** [comment]
> SOLUTION: It works now, after uploading the Docx-invoice-template and deleting the cache another time.

Closing
