### ISSUE TITLE
Timesheet - Working Day

### ISSUE THREAD

**Issue by linevty** [kimai/kimai#398]
I would like to request an option (as an admin) to be able to pre-populate the begin time and end time for a timesheet entry for (to say 8.30am - 5pm) rather than the current time. 

This could further be expanded so a user that is assigned to a single project for a number of weeks could add their timesheet entries in a single entry by selecting Monday - Friday, tick a box that says 'all day', and have it generate the daily entries for that user based on the defined working day.  An automatic lunch break option would be great too? but less of a concern as we can just deduct that later.

We are using kimai to keep track of the time taken against projects.  We do csv exports into a reporting tool and some users mistakenly do not add their time upto 8,30 hours (8.30am to 5pm) which throws off some of the calculations, we end up re-running the import a few times to weed out these errors.

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/issues/1291
