### ISSUE TITLE
Installation instructions shared host: add HostEurope

### ISSUE THREAD

**Issue by Silun** [kimai/kimai#3980]
### Describe the issue

I have got Kimai up and running on a HostEurope webserver. The procedure was as follows:

- Follow the Instructions for NetCup as found in the [Installation Guide](https://www.kimai.org/documentation/installation.html#netcup)
- It is of note that the procedure must be undertaken with the **FTP** SSH account, not the WP one.
- After those steps are done, go to the control panel of the webserver -> `Webspace & Users` -> `File Management` -> `Kimai` -> `var` and `select all` files/folders. Those all belong to the FTP user, change this to the WP user and apply.

Kimai should then work!

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.11

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Thanks for sharing the docs @Silun 👍 

Can you confirm or update these steps and adapt them, especially the part about SSL and the Webroot.

And what is the `WP user`? 

----

ATTENTION: Procedure must be undertaken **with the FTP SSH account**, not the WP one.

- Clone Kimai in the root folder as stated above and then `cd kimai`
- Install composer: `curl -sS https://getcomposer.org/installer | /usr/bin/php`
- Install dependencies: `php composer.phar install --optimize-autoloader`
- configure your .env file, eg. `nano .env`
- install kimai: `php bin/console kimai:install -n`
- reload config: `php bin/console kimai:reload`

After those steps are done, go to the control panel of the webserver
- Configure `/kimai/public` as root folder for the domain (or subdomain) of your choice and add SSL for this domain
- Select `Webspace & Users` -> `File Management` -> `kimai` -> `var` and select all files/folders. Those all belong to the FTP user, change this to the WP user and apply.

**Comment by Silun** [comment]
> Can you confirm or update these steps and adapt them, especially the part about SSL and the Webroot.
> 
> And what is the `WP user`?

HostEurope provides two users for SSH: ftp{your-number} and wp{your-number} eg ftp12987412 and wp12987412. I believe that by default, the FTP user has file level access, so can clone the repo and install Kimai, but is strictly for access by the user. The WP user ("Webserver Process", or something like that?) does not have sufficient permissions to perform the installation but is needed for Kimai to work, so we give that user ownership of everything in /var/ after installing with ftp.


Maybe change the second to last point and split it in two:

- In HostEurope's webserver administration, select `Domains` -> `Subdomains` and configure `/kimai/public` as `Directory / URL` for the domain (or subdomain) of your choice.
- Optionally, under `Security & SSL` -> `Manage SSL` configure an SSL certificate for the domain.

Edit: Additional step for user creation:

- **Use the WP account** to create your first user, e.g. `bin/console kimai:user:create username admin@example.com ROLE_SUPER_ADMIN`

**Comment by kevinpapst** [comment]
Awesome, thank you. 
Added with commit https://github.com/kimai/www.kimai.org/commit/3f76df0e68110ec25d78aab19e8a6a02859108fb
