### ISSUE TITLE
Drop down menu glitching on 'weekly hours' page

### ISSUE THREAD

**Issue by SaturnusDJ** [kimai/kimai#3981]
### Describe the issue

(Custom CSS disabled.)
Opened the 'weekly hours' page in Firefox, Chrome and Edge.
For empty project and activity fields, the click only registers when clicking quite towards the top of the inside of the box.

![image](https://user-images.githubusercontent.com/14320018/233601973-23e07b7a-9094-494d-bffb-11a683a17155.png)
The click has to be inside the red painted box, otherwise the pull down menu does not open.
The mouse cursor also only changes to 'clickable' in that red boxed area. Outside it, it is a regular pointer.

Once there is text in the box/field, it works like expected.

This occurs since I think Kimai version 2.0.13.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.15

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1.16

**Comment by kevinpapst** [comment]
Test the demo and check if it works there. 
I cannot see your issue.
Docker environments tend to use outdated assets

**Comment by SaturnusDJ** [comment]
Yes same on https://demo-branch.kimai.org

**Comment by kevinpapst** [comment]
Now I see it ... it only happens on this page and only in empty rows.
Strangely it doesn't happen in Brave Browser, which is my daily&dev environment.

**Comment by kevinpapst** [comment]
sorry, forgot about the issue. 
will be fixed with the next minor release next week.

**Comment by SaturnusDJ** [comment]
Excellent, thanks.
