### ISSUE TITLE
TOTP in Kimai 2 Docker does not work

### ISSUE THREAD

**Issue by DunklerPhoenix** [kimai/kimai#3983]
### Describe the issue

Heho 
I use Kimai 2 "2.0.14 prod" in a Docker environment behind Traefik 2 and Authelia.
The Doctor doesn't show any error or problems. The Language is set to German (Switzerland)

Now the Problem is that Kimai doesn't show the TOTP QR Code. Maybe its a problem with the constalation from above or something else, but it would be great if the TOTP String could be shown in clear text under the QR Code. I often dont use the QR.

EDIT: Happens in all languages

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.14

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

No useful logs for this problem :/ just the same 404 as in the screenshot

### Screenshots

![CqzEjPizZD](https://user-images.githubusercontent.com/1261305/233621038-9e413942-d37b-49f7-9ac4-295c2fbffff5.png)

**Comment by kevinpapst** [comment]
Can you make sure, that your environment issues are fixed first. 
The 404 image might just be a follow up issue. 
Is anything in Kimai or docker logs?
The 404 of Kimai looks different than a real webserver 404. Please check which one it is. 

This image URL could potentially send a 404 if your user profile has no "totp_secret" in the database. Can you check the table `kimai2_users` and the column `totp_secret'.

It works at https://demo-branch.kimai.org/de_CH/profile/susan_super/2fa
Usually if something works in the Demo and not on your end, I can only 🤷

**Comment by DunklerPhoenix** [comment]
Heho
The manifest issue is only the favicon. Don't know what he wants there because I don't know where to set the requested header  from the error message (the manifest error is on every page)


The 404 in kimai logs is only a normal access.log 404 error.
The Kimai Container does not show a 404 - the Kimai Proxy container (tobybatch/nginx-fpm-reverse-proxy) shows:
172.18.0.20 - - [21/Apr/2023:11:42:32 +0000] "GET /de_CH/profile/cy/totp.png HTTP/1.1" 404 556 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "144.2.108.76"


In the Database there is a totp_secret

**Comment by kevinpapst** [comment]
Do you have any webserver / reverse proxy rule, that tries to cache/serve png images?

The totp.png is just a route name in Kimai: 
https://github.com/kimai/kimai/blob/main/src/Controller/ProfileController.php#L409

Maybe there is something interfering with the request, so it does not reach Kimai?

**Comment by DunklerPhoenix** [comment]
Not that I know.
Traefik does not cache. The only one could be the tobybatch/nginx-fpm-reverse-proxy container

(I edited the answer above)
> The 404 in kimai logs is only a normal access.log 404 error.
> The Kimai Container does not show a 404 - the Kimai Proxy container (tobybatch/nginx-fpm-reverse-proxy) shows:
> 172.18.0.20 - - [21/Apr/2023:11:42:32 +0000] "GET /de_CH/profile/cy/totp.png HTTP/1.1" 404 556 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "144.2.108.76"

**Comment by DunklerPhoenix** [comment]
I tested it via localhost directly to the tobybatch/nginx-fpm-reverse-proxy container and there is still no QR code. So Authelia and Traefik are not the problem

I will open an issue there
