### ISSUE TITLE
Archived Customers modification of projects leads to reassignment of project to first active customer

### ISSUE THREAD

**Issue by mr2017x** [kimai/kimai#3985]
### Describe the issue

Hi,

thanks for your work, i faced a issue at the moment.

1. do job and project
2. after finishing disabling the customer
3. after modification (Updating information in project) the project is reassigned to first active customer.

all in kimai 1.30.11

thanks

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.11

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
thanks for finding & sharing the issue!
