### ISSUE TITLE
Remove an entry via 'Weekly hours'

### ISSUE THREAD

**Issue by SaturnusDJ** [kimai/kimai#3995]
### Describe the problem

Situation: Someone makes a mistake by booking on the wrong project or wrong day in 'Weekly hours'.

### Describe the solution you'd like

To be able to delete/remove the hours from that same page, 'Weekly hours'.
![image](https://user-images.githubusercontent.com/14320018/235089661-f14e76a6-279b-4c4f-8042-d36e0b1d1509.png)

### Describe alternatives you've considered

Choose a zero duration, which then should result in the entry deleted. But this is conflicting with 'Allow time entries with an empty duration' if it is enabled.

**Comment by kevinpapst** [comment]
Empty the field and save, that will delete the entry
