### ISSUE TITLE
Really hide customers from Kimai users

### ISSUE THREAD

**Issue by SaturnusDJ** [kimai/kimai#3998]
### Describe the problem

Before opening this issue I had a look at the following discussions:
https://github.com/kimai/kimai/discussions/2632
https://github.com/kimai/kimai/discussions/3687
https://github.com/kimai/kimai/discussions/3345

I searched through issues. I looked into the documentation. And I did and internet search. I hope I did not miss anything.

Here we have a certain necessary organisational structure which requires to send invoices to an in between party. The employees using Kimai are unknown with these customers. It confuses them.
[Our company] - [In between company = customer on invoice] - [Real customer]

What I mean here is that the customers are shown (again) in the project pull down menu as header.

(Another argument for this feature could be in case the customer is confidential to the employees.)

### Describe the solution you'd like

The employees are very familiar with the project names. Thus, an option to hide the customer header in the project pull down menu, and only show projects, sorted a-z.

(I tried a CSS solution: hide the customer and space in the project pull down menu, but that is just as confusing because there is no a-z sorting.)

**Comment by kevinpapst** [comment]
You can change the displayed title via these system settings:
<img width="806" alt="Bildschirm­foto 2023-04-28 um 22 16 42" src="https://user-images.githubusercontent.com/533162/235245333-1b081efe-1fcd-49cb-8b3b-87a61b6566c1.png">
E.g. use the description field and write 123 in there.

**Comment by kevinpapst** [comment]
Projects are always ordered by name, just checked in the code.

**Comment by SaturnusDJ** [comment]
I will clarify:

![image](https://user-images.githubusercontent.com/14320018/235252982-d8deae5f-ef64-4874-a075-bf65767edc24.png)

After using description:
![image](https://user-images.githubusercontent.com/14320018/235253820-3641fb79-ddea-44bc-9452-31aa87d07486.png)

There is no a-z sorting?

The feature request is what would result in this list:
Project 100
Project 200
Project 800
Project 999

Nothing of 'customer' visible.

(Edit: improved.)

**Comment by kevinpapst** [comment]
Hide it via Custom CSS:
```css
.ts-dropdown .optgroup-header {display:none; }
.ts-dropdown .optgroup:before {
  margin-top: 0!important;
  margin-bottom: 0!important;
}
```
The sorting works correctly, just checked again.

Are you even displaying the Project name? The list is not sorted in the frontend, only in the backend, always by name.
So if you display e.g .the project description, the order is still by name.

**Comment by SaturnusDJ** [comment]
Thank you.
I don't know what I could be doing wrong. I set it up on https://demo-empty.kimai.org/en/timesheet/ now.

**Comment by kevinpapst** [comment]
Working as expected: 
<img width="331" alt="Bildschirm­foto 2023-04-28 um 23 26 58" src="https://user-images.githubusercontent.com/533162/235257095-9af59f36-a78e-4e2b-8228-ecbd4ea8934f.png">
Both are ordered correctly:
<img width="427" alt="Bildschirm­foto 2023-04-28 um 23 26 53" src="https://user-images.githubusercontent.com/533162/235257107-2673cd44-9b23-41d5-a549-8908c09518e2.png">
Kimai sorts by customer name, then by project name.

**Comment by SaturnusDJ** [comment]
Okay. Next time I will write much more clearly, step by step. It seems that things that make sense to me are not clear to you and only when I see that I realise I should have been more thoroughly. Apologies, I have to work on this.

On topic:
What I do is hide the customer field with CSS. The employees will not see anything related to customers when using the entry form. So they also do not make a selection from the customer pull down menu. They will choose from project immediately and so see on screen what is shown in the last image I posted.
