### ISSUE TITLE
Remove button in filters disappears when using long names

### ISSUE THREAD

**Issue by SaturnusDJ** [kimai/kimai#4001]
### Describe the issue

Tested on the demo site, in Firefox, Edge and Chrome.

When having a long name for customers, projects, etc. the remove button (X) is no longer visible. Saw this in the filter for 'My times' and 'All times'.
![afbeelding](https://user-images.githubusercontent.com/14320018/235417468-fdb9a883-cba4-4981-9166-0385ec694991.png)

The delete key on the keyboard does work to remove the filter item, but many users will not think of this.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.16

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
One of the reasons why you can configure what is shown in the list.

**Comment by SaturnusDJ** [comment]
Not a solution; if you mean `Display of entries in selection lists` options. Projects have a certain format that makes it sorted by year, then a project name, then external customer, so not the customer used in Kimai for invoicing purposes. Apparently this information is already too long. For example "2023-001 - Name of project No. 1 - External customer". The only option could be to drop the order number out of the name. All other is an necessity for people to pick the right project. But the problem is actually worse for activities. There it is "Abbreviation - category - activity description/tags of 1-7 words".

This all needs word wrap.

**Comment by kevinpapst** [comment]
Yes, you are right. Will be fixed with 2.0.17: https://github.com/kimai/kimai/pull/3992

Thanks for your report and feedback 👍 It is always not easy to understand the issue.

**Comment by SaturnusDJ** [comment]
Excellent!
