### ISSUE TITLE
Keep tags of previous activites

### ISSUE THREAD

**Issue by dhoernel** [kimai/kimai#4004]
### Describe the problem

When I select an activity from the "Restart one of your last activities" list, Kimai does not copy tags (e.g. the "Home office" tag) from the selected into the new activity.

### Describe the solution you'd like

It would be helpful if tags were copied as well from previous activities.

**Comment by kevinpapst** [comment]
You have to use "Restart" from the dropdown of any timesheet.
That will copy the tags.

**Comment by dhoernel** [comment]
Ah thanks! The dropdown entry is "Start again".
