### ISSUE TITLE
Double activities in Project Details (Reporting)

### ISSUE THREAD

**Issue by SaturnusDJ** [kimai/kimai#4008]
### Describe the issue

Inserted some test data in the demo.
Then: Reporting - Project Details - bottom part tab Activity.

![afbeelding](https://user-images.githubusercontent.com/14320018/236426017-4bcefb3a-0064-414e-90e8-6ced75d112b1.png)

All activities are double. Seen this for a few months now. At first thought it is normal, but never found an explanation, neither in Kimai nor documentation. No results in issues and discussions. Bug?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.17

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Ha, never occured to me before.
I just checked the code and assume that one row is billable and the other is not.
Could you please verify my assumption in the demo and then think with me how we can visualize that.
Can you please include the URL to the report, so I can check that directly in the demo (there are more than 5 demos available).

**Comment by SaturnusDJ** [comment]
It's on https://demo-empty.kimai.org/en_GB/reporting/project_details?project=1 now. (Last one was removed by a user, then demo restarted.)

![afbeelding](https://user-images.githubusercontent.com/14320018/236446163-a3668720-6b23-4b9d-983f-dfe4fb6e4ddd.png)

![afbeelding](https://user-images.githubusercontent.com/14320018/236446459-fbe8be3f-161c-402d-824f-6bf90ab73211.png)

No difference.

**Comment by kevinpapst** [comment]
Super-Admin:

<img width="1236" alt="Bildschirm­foto 2023-05-05 um 13 36 43" src="https://user-images.githubusercontent.com/533162/236447792-deefe1ce-26ec-49d1-ab50-01a3fea5300f.png">

Anna Admin:

<img width="953" alt="Bildschirm­foto 2023-05-05 um 13 37 57" src="https://user-images.githubusercontent.com/533162/236447982-6cfd6ee4-01c8-42f4-a385-7ecf53127f66.png">

I can't see it. Which user did you use?

**Comment by SaturnusDJ** [comment]
With username `admin`

**Comment by kevinpapst** [comment]
Okay, weird. It happens for the year ...

<img width="815" alt="Bildschirm­foto 2023-05-05 um 13 39 47" src="https://user-images.githubusercontent.com/533162/236448290-bc23b91e-e151-415c-afb5-3a542fae7207.png">

I guess I have to add columns names for billable and non-billable amounts.
And I have to check why one of the rows shows the wrong duration & amount... 

Now that I know how to reproduce it (thanks for your help), I will check the group-by clauses.

**Comment by kevinpapst** [comment]
Will be fixed with the new minor release next week
