### ISSUE TITLE
Make project field optional

### ISSUE THREAD

**Issue by robinrosenstock** [kimai/kimai#401]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when, I have to start a simple activity, which does not belong to any project, because the project  is a mandatory field, and I need to enter something.

**Describe the solution you'd like**
I would like to see time recordings without the need to enter a project (Activity without project)

Version: latest, after the separation of projects and activities)

**Comment by kevinpapst** [comment]
LOL, its like before, just that you have to select a project directly, instead of the indirect selection by activity. I don't think that I can make projects optional.

Would it help if you could define a default customer and project, for example "myself" and "personal stuff"? Then you can skip the manual step to select a project.

**Comment by geniusupgrader** [comment]
> I don't think that I can/will make projects optional for now.

Is this too extensive to program, or just is it not on your priority list?


> Would it help if you could define a default customer and project [...]?

Definitely!
I guess this wouldn't be that hard to program. Then you have the settings: `default customer` and `default project` or something similar. Would be really nice. Thanks beforehand.
I'll open a new feature request for that.

**Comment by kevinpapst** [comment]
Well, for now I want to focus on getting Kimai to a stable state that can be recommended for everyone switching from v1 to v2. Even though it would be nice to make Kimai an all-purpose/fits-everyone time tracker, I want to focus on business needs.

I don't reject feature requests regularly, but that one would be expensive to add without much benefit.
You have to have a structure that you can rely on. If everything is optional, the code gets messy and unnecessary complicated fast.
