### ISSUE TITLE
DB Tables not Properly Renamed During Installation

### ISSUE THREAD

**Issue by martinvahi** [kimai/kimai#402]
[Src downloaded 2014_07_10 from](https://github.com/kimai/kimai/releases/download/v0.9.3-rc.1/kimai_0.9.3.rc1.zip)

Steps that led to the following citation:
_"Error during installation!
Kimai is unable to create necessary tables because tables with the name name already exist. To update your existing installation please click here. Choose another table prefix or delete existing tables with this prefix in order to allow Kimai to perform a clean installation."_
### step_1)

During installation use a huge database table name prefix.

```
kimai_<about 100 characters>
```
### step_2)

Push button "Proceed" and enjoy the error message that says that the table name prefix should be about 64 chars max.
### step_3)

Edit the table name prefix by deleting characters from its end, e.g. by leaving the head part of the text the same.
### step_4)

Push button "Proceed" and enjoy the previously cited error message. :-)

**Comment by Zhigalin** [comment]
@ServiusHack I am getting this error on a clean install from master with default _kimai__ prefix using an existing (but empty) database

**Comment by carrolltondatago** [comment]
I get this error on a clean install.
Existing but empty database.  Ispconfig3 wants to create the databases/users on a per client basis.
I have tried changing kimai_ to kimai2_ makes no difference

**Comment by dasarne** [comment]
Same problem here. Install with clean database fails.

**Comment by martinvahi** [comment]
In my view It would make sense to reopen that bug report, because
if confirmations of the bug appear 4 years after I first reported the bug, 
the issue is certainly NOT RESOLVED.
Thank You.

**Comment by kevinpapst** [comment]
We can certainly reopen the ticket, even though we need more information.
I am reinstalling the Kimai demo a couple of times a day and installed Kimai manually like a hundred times and never experienced the issue.
And when we are on it:  a database or table name with a name length of more than 100 character is simply not allowed, 64 character is the maximum: https://dev.mysql.com/doc/refman/5.7/en/identifiers.html
Taking the table names in account that leaves around 40 character for the prefix ...

**Comment by simonschaufi** [comment]
I also have kimai running in different environments and no problem at all.

**Comment by dasarne** [comment]
Hi @kevinpapst 
nice, that you reopened this issue. I'll try to help you as much as I can. 
Here is my, on my machine reproduceable way to the error.
If I should look at some more facts (logs or versions) please ask...

I'm working on a fresh arch-linux with php 7.1 und mariadb  Ver 15.1 Distrib 10.1.30
This is what I did as root (Bash-History)
```
cd /usr/share/webapps
git clone https://github.com/kimai/kimai.git
cd kimai/
chown -R http .
mysql
create database kimai;
grant all on kimai.* to 'kimai_user'@'localhost' IDENTIFIED BY 'xxxxxx';

```
then went to http://localhost/kimai 

- Select "Deutsch"
- accept license
- See "Systemanforderung" everything is green
- Set Timezone to "Europe/Berlin"
- See "Schreibrechte" everything is green
- Set databaseconnection "localhost","kimai_user","xxxxxx"
- Select Database "kimai"
- Leave table_prefix "kimai_"
- Get config-save information
- and than I get

> Fehler bei der Installation!
> Kimai kann benötigte Tabellen nicht erstellen, da bereits Tabellen mit gleichem Namen existieren.
> Falls Sie Kimai nur updaten wollen klicken Sie bitte hier.
> Wählen Sie ein anderes Tabellenpräfix oder löschen Sie die existierenden Tabellen mit diesem Präfix, damit Kimai eine Neuinstallation vornehmen kann.
> 

Message in /var/log/httpd/error.log

> [Sat Jan 20 17:46:33.309382 2018] [php7:notice] [pid 17684] [client 129.217.xxx.xxx:57628] PHP Notice:  Undefined variable: server_prefix in /usr/share/webapps/kimai/installer/processor.php on line 163, referer: http://localhost/kimai/installer/

Looking at the database after that I see:
MariaDB [kimai]> show tables;
+---------------------------+
| Tables_in_kimai           |
+---------------------------+
| kimai_activities          |
| kimai_customers           |
| kimai_expenses            |
| kimai_fixedRates          |
| kimai_globalRoles         |
| kimai_groups              |
| kimai_groups_activities   |
| kimai_groups_customers    |
| kimai_groups_projects     |
| kimai_groups_users        |
| kimai_membershipRoles     |
| kimai_projects            |
| kimai_projects_activities |
| kimai_rates               |
| kimai_statuses            |
| kimai_timeSheet           |
| kimai_users               |
+---------------------------+
17 rows in set (0.00 sec)

**Comment by simonschaufi** [comment]
> Kimai kann benötigte Tabellen nicht erstellen, da bereits Tabellen mit gleichem Namen existieren.

you need to delete all tables before installing kimai. if you want to update kimai, don't use the installer. for this is the updater.

**Comment by dasarne** [comment]
@simonschaufi see my posting: 
I create the database at the beginning of the installation process. So in the moment when I clicked an "installieren" the database did not have one table - total empty.
It looks like the process of creating the tables will be called twice...

**Comment by kevinpapst** [comment]
@dasarne thanks for the detailed description! 
I'll try to reproduce your finding. At least there is definitely a bug with the server_prefix while writing the config, but I don't think that is the root cause for your troubles.

**Comment by dasarne** [comment]
@simonschaufi I got some more information:
Searching most actuaI files after the broken installrion I found the kimai/temporary/logfile.txt that has the following prosa:
[20.01.2018 18:26:22] -- begin install ----------------------------------
[20.01.2018 18:26:22] [ERROR] in [CREATE TABLE `kimai_preferences` (`userID` int(10) NOT NULL,`option` varchar(255) NOT NULL,`value` varchar(255) NOT NULL,PRIMARY KEY (`userID`,`option`));] => s:63:"Specified key was too long; max key length is 767 bytes (#1071)";
[20.01.2018 18:26:23] [ERROR] in [CREATE TABLE `kimai_configuration` (`option` varchar(255) NOT NULL,`value` varchar(255) NOT NULL,PRIMARY KEY(`option`));] => s:63:"Specified key was too long; max key length is 767 bytes (#1071)";
[20.01.2018 18:26:24] [ERROR] in [INSERT INTO `kimai_preferences` (`userID`,`option`,`value`) VALUES('309443751', 'ui.rowlimit', '100'),('309443751', 'ui.skin', 'standard'),('309443751', 'ui.showCommentsByDefault', '0'),('309443751', 'ui.hideOverlapLines', '1'),('309443751', 'ui.showTrackingNumber', '1'),('309443751', 'timezone', 'Europe/Berlin');] => s:53:"Table 'kimai.kimai_preferences' doesn't exist (#1146)";
[20.01.2018 18:26:24] [ERROR] in [INSERT INTO `kimai_configuration` (`option`, `value`) VALUES('version', '1.2.1'),('login', '1'),('adminmail', 'admin@example.com'),('loginTries', '3'),('loginBanTime', '900'),('revision', '1393'),('currency_name', 'Euro'),('currency_sign', '€'),('currency_first', '0'),('show_update_warn', '1'),('check_at_startup', '0'),('show_daySeperatorLines', '1'),('show_gabBreaks', '0'),('show_RecordAgain', '1'),('show_TrackingNr', '1'),('date_format_0', 'dd.mm.yy'),('date_format_1', '%d.%m.'),('date_format_2', '%d.%m.%Y'),('date_format_3', 'd.m.Y'),('table_time_format', '%H:%M'),('language', 'de'),('roundPrecision', '0'),('decimalSeparator', ','),('durationWithSeconds', '0'),('exactSums', '0'),('defaultVat', '0'),('editLimit', '0'),('roundTimesheetEntries', '0'),('roundMinutes', '0'),('roundSeconds', '0'),('allowRoundDown', '0'),('defaultStatusID', '1')] => s:55:"Table 'kimai.kimai_configuration' doesn't exist (#1146)";
[20.01.2018 18:26:24] -- showing install error --------------------------
l

**Comment by kevinpapst** [comment]
Can you share the collation of your database and tables? If it is utf8mb4 or something similar, that can cause the troubles, at least it did in the past for other users.
It seems that this is the new default collation in some distributions. And if you create your database by hand, it does not use the one we expect: https://github.com/kimai/kimai/blob/master/installer/processor.php#L194

**Comment by kevinpapst** [comment]
@dasarne can you please check if my changes in #1093 fix your problems?

**Comment by dasarne** [comment]
@kevinpapst the default-collation is "utf8mb4" so I try #1093

**Comment by dasarne** [comment]
@kevinpapst @simonschaufi 
#1093 fixes the problem. I installed kimai with no errors.
Thanks for the fast support.
Yours
 Arne

**Comment by martinvahi** [comment]
I'm NOT a kimai develoer, nor have I tested the updates, but 
the ISSUE wit ALL DEVELOPERS, including myself(with my own projects)
tends to be that developers test their creations on the machines that they have
access to and even if there are more than one machine, they're all
"tainted" from previous tests. Basically, what I'm saying is that
**stable release candidates should be tested on a 
clean virtual machine** that has never had the software installed.

You MIGHT be able to download [one from my site](https://technology.softf1.com/various_virtual_appliances/).

**Comment by simonschaufi** [comment]
The demo installation is actually installed every night and my own hosters also use `utf8_unicode_ci` or `utf8_general_ci` or any other latin1 version because other charsets break as you have seen. I have ubuntu 16.04.3 LTS and there it also works fine. We just can't test all different ubuntu versions and all mac and whatever system... you name it. If people install kimai on a non hosted server, we expect them to understand the sytem they have and configure it correctly.

**Comment by martinvahi** [comment]
> The demo installation is actually installed every night and
>...

My conclusion from that is that may be the MySQL/MariaDB is 
not the optimal database, if complicates the creation of "sufficiently portable"
software. Unless the application has a proper database abstraction layer, 
the MySQL/MariaDB can't be swapped any time soon, but in the long run
it might make sense to migrate to something else, may be SQLite. 
Time tracking seems to be a kind of innocent, single-user/few-users application
that SQLite might handle splendidly. Of course, I haven't tested it, so
I can not say that there won't be even more problems with the SQLite, but
I just observe that the current project affirms my suspicion that every 
PHP application must have a proper database abstraction layer.

I actually tried the database abstraction layer once and managed to
get my information system to work so that the application code depended 
only on the database abstraction layer, not on any database specific
library, but that was so long time ago that my PHP library has been
[bitrotting quite a bit](https://technology.softf1.com/sirel/2013/).

Please do [NOT USE THAT](https://github.com/martinvahi/sirel/blob/master/src/src/sirel_db.php).
I only add it here as a nasty style example to demonstrate, how 
laborious the creation of the database layer CAN GET and even
my unpublished, incomplete version at my own computer does not
contain everything that actually is needed. I do not even remember
exactly, what was missing, but I got my abstraction layer to 
a state, where I could use MySQL or PostgreSQL and my
client got the software with a functional abstraction layer, except that
I wanted to rewrite a huge portion of not all, but some upper parts
of the abstraction layers to make the rest of the application code
less laborious. Those are the parts that are probably missing,
but, again, please do not use the GitHub version of my PHP 
library, only the tar from my site is the complete copy and
the year 2013. tar file has not been tested with any of the newer
PHP versions.

**Comment by kevinpapst** [comment]
@martinvahi You are completely right with what you say. Problem with Kimai is its history. When it was originally written, there was no real ORM available like nowadays. We already tried, but there is to much logic tightly coupled in the current Kimai version that makes it almost impossible to add a true abstraction layer.
SQLite should work fine for all the freelancers out there or smaller companies. And if we are going to write a new Kimai version, SQLite will definitely be supported.

**Comment by martinvahi** [comment]
Thank You for the answer, but the actual reason, core message, of my 
current post/comment is that the SQLite can actually handle data sets
that are multiple GiB in size. For example, the [Fossil](https://www.fossil-scm.org/)
repository system(wiki+bugtrack+git-svn-competitor all in one, id est cloning
a Fossil repository clones ALL of the source repository history + 
ALL of the wiki history +
ALL of the bugtrack history)
runs SQLite internally. Fossil is being developed by the
very same author, Richard Hipp, who develops the SQLite
and the SQLite has actually been certified to meet the
requirements of safety critical systems, id est it is certified(some copy of it)
to be used in the very same software that moves the
wings of the planes(avionics).

To "brag" a bit and to do some "name dropping", 
I add that if You do not believe that the Fossil system(read: its internal SQLite db)
can handle multible GiB of data, then You may 
[clone](https://www.softf1.com/cgi-bin/tree1/technology/flaws/silktorrent.bash/wiki?name=User+Guide) my [Silktorrent](https://silktorrent.softf1.com/) project. :-D

As a matter of fact, the Fossil even has its GitHub analogue: [Chisel](http://chiselapp.com/)

I use Fossil that way that every client gets its own Fossil private fossil
repository and at the end of the project clients can get a clone of their 
project Fossil, which contains all of the documentation of the project(the wiki),
bugtrack with all of the contents and, if possible, also code, although, 
sometimes it makes more sense to deliver the code repository only 
in a form of a virtual machine, which, unfortunately, can have its own
set of problems, mainly download size. (I'm actually partly in trouble that 
people find the VM images too big to download, their hosting also costs,
etc. so I'm actually aiming to provide web hosting based delivery, but
the web hosting based solutions have data security related issues
and the use of web hosting is unreliable due to the censorship and
cyber attacks and "innocent" internet outages, so I find that the
VM image based delivery is the form of delivery that has the highest
quality, because it's really reliable, all dependencies have been
preinstalled and everything, but if people have trouble using them...)

Anyways the SQLite can handle quite a bit and the Fossil repository system
demonstrates that capability really well.

Thank You for reading my comment :-)
