### ISSUE TITLE
V2 Lockdown period does not work

### ISSUE THREAD

**Issue by HeinzWuert** [kimai/kimai#4025]
### Describe the issue

see title

Defined project with start / end time 01.03. - 30.06.
Defined lockdown period end of input for march ist the 12 of april
It's still possible to add times in march

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

actual demo

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/45666972/3eefd602-0c75-4629-ac5a-a7af8633e24e)

**Comment by kevinpapst** [comment]
Which demo and which test account?

**Comment by HeinzWuert** [comment]
https://demo-branch.kimai.org/en_US/timesheet/

 

susan_super

project _test

 

Von: Kevin Papst ***@***.***> 
Gesendet: Mittwoch, 10. Mai 2023 18:26
An: kimai/kimai ***@***.***>
Cc: HeinzWuert ***@***.***>; Author ***@***.***>
Betreff: Re: [kimai/kimai] V2 Lockdown period does not work (Issue #4025)

 

Which demo and which test account?

**Comment by HeinzWuert** [comment]
https://demo-branch.kimai.org/en_US/timesheet/
susan_super
project _test

**Comment by kevinpapst** [comment]
<img width="713" alt="Bildschirmfoto 2023-05-10 um 18 35 59" src="https://github.com/kimai/kimai/assets/533162/d00eabd3-92ee-40a8-a94d-16ba4c24c023">

See https://www.kimai.org/documentation/configurations.html#lockdown-period

> If a user has the permission lockdown_grace_timesheet all records in the last lockdown period can be edited, even after the grace period ended
>
> If a user has the permission lockdown_override_timesheet none of the lockdown rules apply


susan_super has all of that.
Test with john_user / kitten

**Comment by HeinzWuert** [comment]
checked, you are wright! Works as it should be.
our ongoing error with possible overbooking budgets under special conditions also no longer occurs.  :-)

**Comment by kevinpapst** [comment]
That is good news!
