### ISSUE TITLE
Language, date format and time format switches when duplicating an entry

### ISSUE THREAD

**Issue by mrclmh** [kimai/kimai#4026]
### Describe the issue

The locale is set to German. Open the calendar view, right click on an entry and select "Kopie erstellen".
A window pops up, where the locale seems to be switched.

The window title and field labels are in English.
The date format is M/DD/YYYY.
The time format is 12hour AM/PM.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.18

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

Unknown

### Logfile

(Doctor menu not found. Is it available in the cloud version?)

**Comment by kevinpapst** [comment]
Thanks for finding and posting!
Will be fixed with the update in the next days.
