### ISSUE TITLE
Timestamp Fields Swapped in Dialog

### ISSUE THREAD

**Issue by martinvahi** [kimai/kimai#403]
![The comment](http://longterm.softf1.com/2014/flaw_reports/kimai/kimai_v_0_9_3_rc1_dialog_swap_timestamp_t1.jpeg)

[Src downloaded 2014_07_10 from](https://github.com/kimai/kimai/releases/download/v0.9.3-rc.1/kimai_0.9.3.rc1.zip)

**Comment by simonschaufi** [comment]
closed as duplicate to #507
