### ISSUE TITLE
Wrong duration calculation behavior while editing times by hand

### ISSUE THREAD

**Issue by StefanGebhardt** [kimai/kimai#4031]
### Describe the issue

Hi, if I change times in the start-time-field "by hand" and do not watch on the exact correct format the duration calculation does not work properly. In minimum a field error should be shown. If I take the dropdown or enter time in the correct format, everything works as designed.

Example: 
filled is: start-time 10:00, duration 01:00, end-time 11:00
changing by dropdown the start-time to 09:00 -> duration changes to 02:00 -> ok
changing by hand the start-time to "09:00" -> duration changes to 02:00 -> ok
changing by hand the start-time to "9:00" -> duration stays on 01:00 -> not ok

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.18

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Logfile

No log entry

### Screenshots

<img width="534" alt="image" src="https://github.com/kimai/kimai/assets/2803552/dc6c04b8-7f22-4e54-bf72-e35bf8f59932">

**Comment by kevinpapst** [comment]
Thanks for sharing, will be fixed with the next release - see #4030
