### ISSUE TITLE
CSV export: time exceeds 24h without supplying date information

### ISSUE THREAD

**Issue by nblock** [kimai/kimai#404]
In the csv export, the following items are exported (snipped)

```
Datum,von,bis,h'm,Zeit,…
09.06.,11:30,13:11,73:41,73.68,…
```

The date range for the above booking stretches across 3 days. However, looking at the export one can't determine the start/stop date. One way to work around this, is by changing the _from_ and _to_ timestamp formats or – better – to split _date_ into _start date_ and _stop date_.

Kimai version: v0.9.2.1306

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/issues/1291
