### ISSUE TITLE
Time in tooltip header does not get updated when changing entries via mouse dragging

### ISSUE THREAD

**Issue by mrclmh** [kimai/kimai#4043]
### Describe the issue

The drag & drop functionality is really nice. As a small nitpick, the displayed start/end time in the tooltip does not get updated for me when changing an entry via mouse dragging. It only gets updated when opening the entry and saving it or reloading the page.

To reprocude the error:
1. Change to calendar view.
2. Hover over an existing entry and check the start/end time in the header line of the tool tip.
3. Change the length of the entry via mouse dragging.
    OR
    Move the entry with the mouse.
5. Check the tooltip again.

Result: The start/end time in the tooltip are still the same.
Expected: The start/end time in the tooltip should reflect the new start/end time.

(tested with Firefox latests & Chrome latest)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.21

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

Unknown

**Comment by kevinpapst** [comment]
Thanks for sharing 👍 Will be fixed with the next update.
