### ISSUE TITLE
Export / Add Tag

### ISSUE THREAD

**Issue by christian-lo** [kimai/kimai#4044]
### Describe the problem

I'm using kimai for time tracking and invoice my times with another software. For each invoice an export is generated and added as a PDF. Times are tracked for multiple users. 

To keep track of which timesheet is related to which invoice (number), I'm adding the invoice number as a tag to each timesheet. 

So far I need to make two steps: 
- Use Time tracking - All times, filter for the relevant timesheets and edit / add a tag.
- Use Export - filter for tag to generate the export / PDF and mark the timesheets as exported.

### Describe the solution you'd like

In Menu - Export an option to add tags (next to the option to mark the timesheets as exported) would be perfect! 

Or in Menu - All times and then Export an option to mark the exported timesheets as exported would be perfect.

### Describe alternatives you've considered

In version 1.30.x there is no option to sum the filtered times in Administration - Timesheets. In version 2.xx the times of filtered timesheets is shown in the title and will help to adjust or find faulty values. But still multiple steps are needed to add information which (external) invoice the filtered timesheets are linked to.

**Comment by kevinpapst** [comment]
You can use the invoice system to generate your "export" and put the invoice number into the invoice description.
Or create a custom field for invoices and fill in the external invoice id.
No matter how you do it: I would recommend to use the invoicing system for that.
Invoicing will automatically marks all included entries as exported.

Tagging upon export is nothing that will be added to core. Happy to help any developer to build that into a plugin though.
