### ISSUE TITLE
Validation Failed when adding Timesheet via API

### ISSUE THREAD

**Issue by fh-dersch** [kimai/kimai#4048]
### Describe the issue

I got an error when i try to add an timesheet into Kimai.
I tried via my tool, postman and api tool integrated in kimai (http://SERVER_URL/api/doc)

I used my own data and the example data from API documentation e.g:

`{
  "begin": "2023-05-23T14:14:11",
  "end": "2023-05-23T14:14:11",
  "project": 26,
  "activity": 3,
  "description": "string",
  "fixedRate": 0,
  "hourlyRate": 0,
  "user": 3,
  "tags": "string",
  "exported": true,
  "billable": true
}`

The Response is always:

`{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "errors": [
      "This form should not contain extra fields."
    ],
    "children": {
      "project": {},
      "activity": {},
      "description": {},
      "fixedRate": {},
      "hourlyRate": {},
      "user": {},
      "tags": {},
      "exported": {},
      "billable": {},
      "billableMode": {}
    }
  }
}`

I tried the exact JSON request in our current productiv build with Version 1.29 which works as expected.

In my test build i use docker (productive is from source) with image apache-2.0.23-prod

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.23

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

No Logs generated

**Comment by fh-dersch** [comment]
I get it by myself...

It is caused of the removing of the tracking mode "[Duration] replaces the end time with a duration input-field" which we are using.

The Fallback is "[Duration] configurable fixed start-time, only duration can be changed" which do not allow to send a beginning time.

Does this work as expected ?

**Comment by kevinpapst** [comment]
You cannot send fields, which are not allowed. And the fields are disallowed, because of the "duration only" mode.

The duration mode you are mention was a mistake from the beginning and therefor removed:
If you can edit start time and duration, you can edit all fields. 

Simply use Standard mode. If you don't like that, you can always hide fields with custom css/js.

**Comment by fh-dersch** [comment]
Hi Kevin,

thanks for reply. Configured years ago and never thought about it. Now i get it, thanks.
Maybe this post helps other with the same "Knoten im Hirn" ;) 

Kind regards

**Comment by kevinpapst** [comment]
It's missing documentation for the API, I know 🤷 sorry!
