### ISSUE TITLE
Error 500 + Error in/with uninstalled Plugin CustomCSSBundle

### ISSUE THREAD

**Issue by maurice-kpw** [kimai/kimai#4049]
### Describe the issue

I was following the upgrade guide and got stuck after "composer install --optimize-autoloader -n"
We were upgrading from 1.3.something to the newest version 2.0.22

I uninstalled (deleted) all Plugins from /var/plugins and set the PHP Version to 8.1.19 on my hosting.

Then (and now with every kimai-command) I get the following error:
```Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In PluginMetadata.php line 59:
!!                                                                                 
!!    Bundle "CustomCSSBundle" defines an invalid Kimai minimum version in extra.  
!!    kimai.require. Please provide an integer as in Constants::VERSION_ID.        
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-install-cmd
```

I tried reuploading the old plugin folder, uploading the most recent plugin version and tried without any plugins. All resulting in the same error. 

I don't understand why the Bundle is requiring something after I uninstalled it? 

I found discussion [3086](https://github.com/kimai/kimai/discussions/3086) which has a similar error – the solution was to install database tables for a plugin we don't use / never used.

What am I missing here? Any idea what to do?
Our Installation is not available with an error 500 but I guess thats because of the upgrade in process.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.22 (?)

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Logfile

No recent error in error log.

**Comment by maurice-kpw** [comment]
Currently I think the problem is that I forgot to clear/reload the cache after uninstalling the plugins and before starting the upgrade process. :(

I just tried the rm -r var/cache/prod/* command this didn't throw the above error but the error still appears when using kimai-commands. 

Is there anything I can do?

**Comment by kevinpapst** [comment]
If you deleted all plugins and `var/plugins/` is empty, then this error can only come from the cache.

You have to delete ALL cache files with `rm -f var/cache/*` and then the error should be gone.
