### ISSUE TITLE
Active filter should stay open

### ISSUE THREAD

**Issue by robinrosenstock** [kimai/kimai#405]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to use the filter to filter my timesheet entries.
After clicking on the filter button the filter form opens. After inserting or changing something in this form the filtering is executed and the form is dismissed/closed. So fine so good. But often you want to change the other fields in the form too. And in the worst case this is what happens:

Click on filter button -> change Records -> waiting ->
Click on filter button -> change Page size -> waiting ->
Click on filter button -> change From -> waiting ->
Click on filter button -> change To -> waiting ->
Click on filter button -> change Customer -> waiting ->
Click on filter button -> change Project -> waiting ->
Click on filter button -> change Activity -> waiting

In the case that you want to change the Activity **only** you first need to set the Customer and the Project, otherwise the field are not visible at all. So in order that you can change the Activity **only** you need to do at least this:

Click on filter button -> change Customer -> waiting ->
Click on filter button -> change Project -> waiting ->
Click on filter button -> change Activity -> waiting

![screenshot_20181111_130222](https://user-images.githubusercontent.com/6190906/48312678-c4977600-e5b2-11e8-9dd5-56e5a7a1d25a.png)

**Describe the solution you'd like**
I would like to see, that an **active filter stays open**. This has the benefit, that you always know, whether a filter is active or not. Later on, there is always the possibility to add some hiding functionality, in order that the filter button gets darker or something (that know if an filter is active or not..). But first an active filter must stay open and must allows further modifications.

The second thing I would like to see is the following:
That you can filter for Activities alone, and that **all fields in the filter form are always visible** (maybe this is needed on other forms as well) This is only possible with the latest separation of project and activities.
So when only filtering for activities, all projects are selected.

**Comment by geniusupgrader** [comment]
> [...] please have a look at #407

Oh, so much better!

> There was a reason for hiding the fields in the first place, but I can't remember what it was.

You've commented 6 days ago, it sounds like the same principle: https://github.com/kevinpapst/kimai2/issues/307#issuecomment-436085236

> I'll see if this can be changed, but could you please open a new issue for that?

I'll open a new issue for making form field visible and not hidden.

> [...] each PR is merged in one commit and the changelog is generated from the commits since the last release.

thanks for this info.
