### ISSUE TITLE
Importer - Import from clockify failed in a few lines

### ISSUE THREAD

**Issue by mircokn** [kimai/kimai#4053]
### Describe the issue

Importing a CSV from clockify throws an error .
Failed to parse time string (14/04/2023 9:00) at position 0 (1): Unexpected character
Some lines with same format are working.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.02.23

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![Bildschirmfoto 2023-05-24 um 09 31 21](https://github.com/kimai/kimai/assets/51916990/5536b9e9-5d49-43ac-9c8f-6059e1855a3d)

**Comment by mircokn** [comment]
Changer Date-Fomat in clockify

**Comment by kevinpapst** [comment]
As this was not the first time, I added it right now to the documentation.

Glad you found the solution yourself and thanks for sharing 👍
