### ISSUE TITLE
Tasks 2.x: Field names overlapping (just an optical glitch)

### ISSUE THREAD

**Issue by pbksol** [kimai/kimai#4054]
### Describe the issue

In the Tasks plugin long field labels don't have a linebreak:

<img width="452" alt="Bildschirmfoto 2023-05-24 um 09 58 37" src="https://github.com/kimai/kimai/assets/8238713/de73c175-7266-42fc-9049-9e8656dca492">

Adding:

`.col-form-label {line-break: anywhere;}`

Seems to fix it – it's not nice, but works.

Tasks Management version 2.1.2

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.x

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Please repeat here: https://github.com/kevinpapst/kimai-plugins
