### ISSUE TITLE
Custom CSS plugin example rules not updated for v2 

### ISSUE THREAD

**Issue by pbksol** [kimai/kimai#4055]
### Describe the issue

The example rules in the Custom CSS plugin are not updated to the new CSS used in Version 2.

I did not check every example but the sidebar css examples don't work

Example:

```
/* START [general] hide-menu-calendar */
ul.sidebar-menu li#calendar { display:none; }
/* END [general] hide-menu-calendar */
```

There is no sidebar-menu class anymore in Version 2.

Custom CSS version 2.0

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.x

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Please repeat here: https://github.com/Keleo/CustomCSSBundle/issues

**Comment by kevinpapst** [comment]
BTW I updated most rules (some had to be deleted) and the navigation rule will not work before 2.0.24
