### ISSUE TITLE
ACLs are buggy

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#406]
I have a complex ACL setup where users belong to 2 different groups with different roles.
The point is: If a user belongs to 2 different groups where one group can edit customers and the other one not allowed, the lower ACL rule applies instead of the higher.

User Max
- global role: user
- groups:
  - Group 1: Group leader
  - User: User

Groups:
- Group 1
- User

Global Roles:
- Admin
- User (can create and edit customers)

Group Roles:
- Admin
- User (is not allowed to create and edit customers)
- Group leader (can create and edit customers)

When I create a new Customer both groups get pre "selected". Customer is saved. Now when i try to edit the customer, the overlay is not displayed.

If I give the Group Role "User" the permissions he needs to edit a customer, the overlay appears.

Expected behavior:
If the Customer is assinged to both groups and the user is in one of those groups and can edit the customer, he should be able to do it

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
