### ISSUE TITLE
Allow expanding collapsed card by clicking the entire header

### ISSUE THREAD

**Issue by pbksol** [kimai/kimai#4062]
### Describe the problem

<img width="703" alt="Bildschirmfoto 2023-05-26 um 09 14 09" src="https://github.com/kimai/kimai/assets/8238713/bb0bb1cb-558b-43ac-a431-c7f2a54123f3">

The additional settings are expanded/collapsed when the little arrow button is clicked. But only if this button is clicked.

That is a little bit of a usability issue especially when working with the tasks management where the tag section is now hidden. It may be only me but I'm somewhat used to expanding such an element by clicking anywhere on the collapsed item.

### Describe the solution you'd like

Expand/collapse the settings by any click inside the card-header element (green lines)

**Comment by kevinpapst** [comment]
Fixed by #4096

**Comment by pbksol** [comment]
This will be ported to all plugins using the same feature?

**Comment by kevinpapst** [comment]
Oh, glad you like it, you are welcome...
