### ISSUE TITLE
Missing translation for "Weekly working hours"

### ISSUE THREAD

**Issue by rglastra** [kimai/kimai#4071]
### Describe the issue

Using the fpm-dev kimai2 image (which seems pretty recent), I've got the language set to Dutch (Nederlands) but there are a few missing translations.

1.
![image](https://github.com/kimai/kimai/assets/497813/f4023de7-1a22-402e-9dae-3be48535eb0f)

I checked the translation files and I wasn't able to figure out where it's sourced from, and accordingly, whether it's just a case of a missing Dutch translation. In any case, the Dutch translation for this would be "Wekelijkse werkuren". 

2. 
![image](https://github.com/kimai/kimai/assets/497813/6d182bf4-55ce-4091-9138-cc75a7dffdc8)
Missing a translation for the page header, month and day of the week.

Happy to send a PR your way if you can point me into a direction where I can make this update. :)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

kimai2:fpm-dev

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Help with translations is highly appreciated!

And there is no need to fiddle around in source files, you can help while watching Netflix 😁 
https://hosted.weblate.org/languages/nl/kimai/

At some point Weblate will sent a PR and I usually merge the changes before the next release.
