### ISSUE TITLE
Invoice Template filename

### ISSUE THREAD

**Issue by 3isenHeiM** [kimai/kimai#4073]
### Describe the issue

I'd like to upload a new invoice template. The filename is "`invoice-EN_v1.docx`" but it's refused.

However, the error says that allowed chars are "A-Z a-z 0-9 _ -" so I don't see where is the problem.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.14

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/26417172/b913f0de-7123-466e-9cec-382c0fa734a6)

**Comment by kevinpapst** [comment]
please send me the file to support@kimai.org

**Comment by kevinpapst** [comment]
Will be fixed with the next release #4066 

You can already work around by making all characters lowercase.
So `invoice-en_v1.docx` instead of `invoice-EN_v1.docx`

**Comment by 3isenHeiM** [comment]
Worked, thanks !
