### ISSUE TITLE
Selecting a Tag after entering it's name doesn't remove the entered text

### ISSUE THREAD

**Issue by pbksol** [kimai/kimai#4076]
### Describe the issue

<img width="701" alt="Bildschirmfoto 2023-05-31 um 21 37 51" src="https://github.com/kimai/kimai/assets/8238713/f7451bf2-d53b-4578-8ff6-23d3add96b6b">

Entering the tag name in the tag field opens the tag selection menu. After selecting a tag, the tag is added to the field but the text entered is not removed.

If one clicks outside the tag field, the text is removed. But (!) if you have to enter multiple tags, you have to remove the text first and then type the new tag. Version 1.x worked way better with entering tags. The entered text was replaced with the selected/matched tag.

I suggest changing the behaviour to how it worked in version 1.x

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.x

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
https://github.com/orchidjs/tom-select/issues/543

**Comment by kevinpapst** [comment]
included in the next release 2.0.30

**Comment by pbksol** [comment]
Thank you :-)
