### ISSUE TITLE
After upgrading Kimai 2 V1.30 to V2.0.24 end users no longer log into Kimai when using LDAP with Active Directory

### ISSUE THREAD

**Issue by echoview** [kimai/kimai#4077]
### Describe the issue

After upgrading Kimai 2 from V1.30 to V2.0.24 found end users could no longer log into Kimai when Kimai configured to use LDAP for authentication, LDAP directory is Active Directory and end user's accounts had previously been manually  created within Kimai.

Prior to upgrade end users could log into Kimai 2 V1.30

All end user's accounts have been created manually within Kimai by a Kimai user with System Admin privileges and not by account being automatically created when an end user goes to log into Kimai for the first time.

Configuration for LDAp authentication in Kimai 2 V2.0.24 as follows:

kimai:
  ldap:
    activate: true
    connection:
      host: <FQDN of Windows Server 2016 DC>
      port: 389
      useStartTls: true
      username: <Fully qualified distinguished name of LDAP service account within Active Directory>
      password: <Service Account Password>
      accountDomainName: <ie example.com>
      accountDomainNameShort: <Pre Wndows 2000 Domain Name>
      accountFilterFormat: (&(objectClass=Person)(sAMAccountName=%s))
    user:
      baseDn: <ie. ou=staff,dc=example,dc=com>
      filter: (&(objectClass=Person))
      usernameAttribute: samaccountname
      attributesFilter: (objectClass=Person)
      attributes:
        - { ldap_attr: mail, user_method: setEmail }
        - { ldap_attr: displayname, user_method: setAlias }
        - { ldap_attr: samaccountname,  user_method: setUsername }
  user:
    registration: false
    password_reset: false
  permissions:
    roles:
      ROLE_USER: ['!password_own_profile']
      ROLE_TEAMLEAD: ['!password_own_profile']
      ROLE_ADMIN: ['!password_own_profile']

User records in <kimai database>.users table auth field value was kimai

User record in <kimai database>.user_preferences table did not contain any record for end users about LDAP distinguished name value.

Solution to fix the problem for each user that uses LDAP for authentication as follows:

After upgrading Kimai 2 from V1.30 to V2.0.24 found end users could no longer log into Kimai when Kimai configured to use LDAP for authentication, LDAP directory is Active Directory and end user's accounts had previously been manually  created within Kimai.

Prior to upgrade end users could log into Kimai 2 V1.30

All end user's accounts have been created manually within Kimai by a Kimai user with System Admin privileges and not by account being automatically created when an end user goes to log into Kimai for the first time.

Configuration for LDAp authentication in Kimai 2 V2.0.24 as follows:

kimai:
  ldap:
    activate: true
    connection:
      host: <FQDN of Windows Server 2016 DC>
      port: 389
      useStartTls: true
      username: <Fully qualified distinguished name of LDAP service account within Active Directory>
      password: <Service Account Password>
      accountDomainName: <ie example.com>
      accountDomainNameShort: <Pre Wndows 2000 Domain Name>
      accountFilterFormat: (&(objectClass=Person)(sAMAccountName=%s))
    user:
      baseDn: <ie. ou=staff,dc=example,dc=com>
      filter: (&(objectClass=Person))
      usernameAttribute: samaccountname
      attributesFilter: (objectClass=Person)
      attributes:
        - { ldap_attr: mail, user_method: setEmail }
        - { ldap_attr: displayname, user_method: setAlias }
        - { ldap_attr: samaccountname,  user_method: setUsername }
  user:
    registration: false
    password_reset: false
  permissions:
    roles:
      ROLE_USER: ['!password_own_profile']
      ROLE_TEAMLEAD: ['!password_own_profile']
      ROLE_ADMIN: ['!password_own_profile']

User records in <kimai database>.users table auth field value was kimai

User record in <kimai database>.user_preferences table did not contain any record for end users about LDAP distinguished name value.

Solution to fix the problem for each user that uses LDAP for authentication as follows:

- For each user change **auth** field value for each user record  in <kimai database>.users table from **kimai** to **ldap**
- For each user's record  in <kimai database>.users table obtain value of user id key field
- For each user add a record to <Kimai Database>.user_preferences table where:
           - set **User ID** field to value obtained for user from user's record  in <kimai database>.users table
           - set **Name** field to ldap
           - set **Value** field value to users fully distinguished name in Active Directory (ie. CN = <First name> <last Name>,OU=staff,DC=example,DC=com)

After altering database end users can know log into Kimai 2 V2.0.24 using LDAP authentication method. For each user change 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.24

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by echoview** [comment]
Solution to fix the problem for each user that uses LDAP for authentication as follows:

- For each user change **auth** field value for each user record  in (kimai database).users table from **kimai** to **ldap**
- For each user's record  in (kimai database).users table obtain value of user id key field
- For each user add a record to (Kimai Database).user_preferences table where:
   - set user id field to value obtained for user from user's record  in (kimai database).users table
   - set name field to ldap
   - Value field to users fully distinguished name in Active Directory (ie. CN=(First name) (Last Name),OU=staff,DC=example,DC=com)

After altering database end users can know log into Kimai 2 V2.0.24 using LDAP authentication method.

**Comment by echoview** [comment]
When writing up the solution, need to set name field in user_preferences table to **ldap_DN** and not **ldap**.

In addition, for LDAP settings should be **ldap_attr: samaccountname,  user_method: setUserIdentifier** and not **ldap_attr: samaccountname, user_method: setUsername**.

With setting changes written in this issue been able to successfully upgrade Kimai installation in both QA and Production environments such that end users can log in using AD credentials via LDAP.

**Comment by kevinpapst** [comment]
I have no clue what you are describing here, but if there would be a BC break in the LDAP implementation, then it needs to be solved in Kimai core and NOT in the database!

If **you** read this: do not follow these steps, I cannot provide any future support for manual database changes!
