### ISSUE TITLE
Expenses / Calculation

### ISSUE THREAD

**Issue by christian-lo** [kimai/kimai#4089]
### Describe the issue

The calculation of expenses in the view Expenses - Expenses is not updated when a new expense is added. It will get updated if I refresh the site manually.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.24

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Screenshots

<img width="1377" alt="Bildschirmfoto 2023-06-08 um 09 30 29" src="https://github.com/kimai/kimai/assets/81588467/087fc061-d979-46ad-b3de-344b6e3bf28f">

**Comment by kevinpapst** [comment]
Pleas post at: https://github.com/kevinpapst/kimai-plugins

This repository here is about Kimai core.
