### ISSUE TITLE
Expenses / Export

### ISSUE THREAD

**Issue by christian-lo** [kimai/kimai#4090]
### Describe the issue

Expenses can't be edited / opend from within the view Export. The button / link "Open" is broken.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.14

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Screenshots

<img width="1335" alt="Bildschirmfoto 2023-06-08 um 09 37 24" src="https://github.com/kimai/kimai/assets/81588467/901f4495-eaf5-4327-b674-b8ca202a7f5c">

**Comment by kevinpapst** [comment]
The button/link is not broken, it is not there on purpose.

Please open requests that target paid plugins in the repository: https://github.com/kevinpapst/kimai-plugins
