### ISSUE TITLE
Search / select-one

### ISSUE THREAD

**Issue by christian-lo** [kimai/kimai#4092]
### Describe the problem

While starting a timesheet, selecting a project, I'd like to search for project name but also customer (as in kimai v1.xx.xx). 

In my case this will allow for better usability that I have two or more projects called "Support" or "Website" just to name a few examples. If there are ten projects matching "Support" but just one customer matching "Bio" for example, I could search for "Bio" and just hit enter. 

### Describe the solution you'd like

Restore functionality of kimai v1.xx.xx 

### Describe alternatives you've considered

Learning to adjust to the new selects.

### Screenshots

<img width="758" alt="Bildschirmfoto 2023-06-08 um 12 25 29" src="https://github.com/kimai/kimai/assets/81588467/9f902e3c-83d6-4a0b-9fb4-a13c3d945ae8">

**Comment by kevinpapst** [comment]
Append the customer name in the dropdown:
<img width="633" alt="Bildschirmfoto 2023-06-08 um 15 52 18" src="https://github.com/kimai/kimai/assets/533162/e8c341d3-7d7f-4e88-949e-1507a599dcca">

**Comment by christian-lo** [comment]
cool - works for me! Thanks!
