### ISSUE TITLE
PHP Update 7.4 to 8.1

### ISSUE THREAD

**Issue by dugs951** [kimai/kimai#4095]
### Describe the issue

How i can Upgrade PHP Version 7.4 to 8.1.
I run nur Kimai 2 Version 1.30.

When i run normal PHP Update i recive thos error 
"Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.2"."

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

7.4

**Comment by kevinpapst** [comment]
PHP Updates have nothing to do with Kimai. Please ask your hoster.
