### ISSUE TITLE
On a fresh install I can login but I cannot open the dropdown lists

### ISSUE THREAD

**Issue by wforumw** [kimai/kimai#4106]
### Describe the issue

Hi,
On a fresh install I can login but I cannot open the dropdown lists like, (Time Tracking, Invoices, Administration, System). If I click nothing happens. Also no pics are displayed.
![kimai1](https://github.com/kimai/kimai/assets/12762849/b100b41c-241f-4a8f-8c9a-497659e4b347)
Any ideas where to look?
I followed the installation docu here
https://www.kimai.org/documentation/installation.html

Many thanks

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.26

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
It is very likely that you dou did not follow the webserver setup docs properly.
Please read them again, then point your vhost to /public/

**Comment by lachlan-00** [comment]
I have a similar issue but i've made kimai a subdir on my site using the public dir. (hostname/kimai)

```
stat /var/www/html/kimai
/var/www/html/kimai -> /var/www/kimai2/public
```

which would be explained by the 404's trying the root and not my subdir

![image](https://github.com/kimai/kimai/assets/1305249/435ab548-fcc4-4cfb-8c53-6fe96a053b01)

that gets fixed by linking the foldes to the web root but i can't see an option for a subfolder for the webroot
```
ln -s /var/www/kimai2/public/bundles /var/www/html/
ln -s /var/www/kimai2/public/build/ /var/www/html/
```

apache redirect works as well okay
```
Redirect permanent /bundles/ https://hostname.org/kimai/bundles/
Redirect permanent /build/ https://hostname.org/kimai/build/
```

**Comment by kevinpapst** [comment]
Subdomains do not cost a penny. If they do, get a new hoster...

<img width="710" alt="Bildschirmfoto 2023-06-13 um 12 08 56" src="https://github.com/kimai/kimai/assets/533162/b3635d91-a1d8-4700-bfe4-aa10cf6ea22c">

**Comment by wforumw** [comment]
Now it works. I use a subdomain now
Thanks!!

**Comment by kevinpapst** [comment]
Thanks for your feedback @wforumw 👍
