### ISSUE TITLE
Start a task with earlier start time

### ISSUE THREAD

**Issue by 85pando** [kimai/kimai#411]
When you start a task without tracking, you might want to add a task that will track until you stop it.

[![bountysource](https://api.bountysource.com/badge/issue?issue_id=4310533)](https://www.bountysource.com/issues/4310533)

**Comment by simonschaufi** [comment]
not clear what this is all about

**Comment by 85pando** [comment]
What I meant is, that starting a task in the tracker does not always occur at the same time as actually starting the task.

What I propose is some mechanism to add a task with an earlier start time, that is still an active time.

For example:

1. Start actual task at 08:30.
2. Add task to tracker at 08:45.
3. Stop task at 09:00.

So when adding the task in step 2 it would be good to have a way to add an active task with earlier start time. This was not possible when I opened this issue. Don't know about now, as I stopped using kimai some time ago.

**Comment by simonschaufi** [comment]
I'm reading it for the third time now and still don't understand what you want. What do you mean with "add an active task with earlier start time"?
Maybe explain by the usecase you need it for.

**Comment by 85pando** [comment]
Thats what I tried to do in the example.

1. Start working on a task.
2. Halway through the task remember to add it in the timetracker.

    * Add it to the tracker with the actual start time from 1.
    * Still have the task active so that tracking continues into the future.

3. Finish the task you are working on.

    * Stop the task in the timetracker.
    * The task now has the time spent from when you started working on it until you entered it (e.g. 15 minutes).
    * The task also has the time from when you entered it in the tracker until you stopped it (e.g. additional 15 minutes).
    * So the overall time spend on this task is 30 minutes.

- - - -

Back in 2014 there were two ways to do that:

* When you realize you forgot to start your task in the tracker. Add it at that moment and then fix the end time once you finished the task.
* Wait with entering the task until you actually finished it and then add it afterwards.

**Comment by kevinpapst** [comment]
I do see the usecase. Its just a convenient way for all the users who regularly forget to start the TimeTracker as the first thing while starting a new task.

Probably we could a checkbox in the "Add" dialog named "make this the active task" (in case thre is no running task at that time). 

I repoen this issue, but it needs more votes.

**Comment by Jonny007-MKD** [comment]
This works for me:

 -  start a new task with the start bitton
 -  edit the active task and change the start time. Now it is still active but has the correct start time.

No need for changes :)

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
