### ISSUE TITLE
Latest releases not in Docker Hub

### ISSUE THREAD

**Issue by derblub** [kimai/kimai#4117]
### Describe the issue

The latest version on Docker Hub seems to be v2.0.23.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.23

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

**Comment by kevinpapst** [comment]
🤷 

Repost at https://github.com/tobybatch/kimai2
