### ISSUE TITLE
php.ini memory_limit=128 (Byte) ?!

### ISSUE THREAD

**Issue by GregorB54321** [kimai/kimai#4118]
### Describe the issue

a lot of OOM errors in the containers log. May because you tried to limit memory to 128 byte?

seems to be internal default. When I set "memory_limit=256M" in environment in docker-compose.yaml. Errors vanishes...

I'm not really familiar with php and can not give solution.

https://www.php.net/manual/en/ini.core.php#ini.memory-limit
kimai        | + handleStartup
kimai        | + sed -i 's/memory_limit.*/memory_limit=128/g' /usr/local/etc/php/php.ini
...
kimai        | PHP Warning:  Failed to set memory limit to 128 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
...
kimai        | PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/var/cache/pro_/twig/4a/4a305ac70d8cc403f05c74dc30b91cc2.php on line 475
kimai        | [2023-06-19T06:48:54.417595+00:00] php.CRITICAL: Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) at /opt/kimai/var/cache/pro_/twig/4a/4a305ac70d8cc403f05c74dc30b91cc2.php:475)"} []

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.23

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

++ cat /opt/kimai/version.txt,
+ KIMAI=2.0.23,
+ echo 2.0.23,
2.0.23,
+ config,
+ '[' -z 128 ']',
+ '[' '!' -z mysql://kimaiuser:mysql_kimaipass_8462405@kimai-sql/kimai ']',
++ awk -F '[/:@]' '{print $1}',
+ DB_TYPE=mysql,
++ awk -F '[/:@]' '{print $4}',
+ DB_USER=kimaiuser,
++ awk -F '[/:@]' '{print $5}',
+ DB_PASS=mysql_kimaipass_8462405,
++ awk -F '[/:@]' '{print $6}',
+ DB_HOST=kimai-sql,
++ awk -F '[/:@]' '{print $7}',
+ DB_PORT=kimai,
++ awk -F '[/?]' '{print $4}',
+ DB_BASE=kimai,
+ re='^[0-9]+$',
+ [[ kimai =~ ^[0-9]+$ ]],
Wait for MySQL DB connection ...,
+ DB_PORT=3306,
+ echo 'Wait for MySQL DB connection ...',
+ php /dbtest.php kimai-sql kimai 3306 kimaiuser mysql_kimaipass_8462405,
+ echo 'Connection established',
+ handleStartup,
Testing DB:** new \PDO(mysql:host=kimai-sql;dbname=kimai;port=3306, kimaiuser, mysql_kimaipass_8462405, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection established,
+ sed -i 's/memory_limit.*/memory_limit=128/g' /usr/local/etc/php/php.ini,
+ '[' 2 -lt 2 ']',
+ cp /assets/monolog.yaml /opt/kimai/config/packages/monolog.yaml,
+ tar -zx -C /opt/kimai -f /var/tmp/public.tgz,
+ '[' -z '' ']',
++ id -u www-data,

**Comment by GregorB54321** [comment]
uhh.. posted secrets. obviously I need to change the credentials now ... :-(

**Comment by kevinpapst** [comment]
Docker image is not managed here. Please re-post at https://github.com/tobybatch/kimai2/issues
