### ISSUE TITLE
Possibility to add to the Invoice products or special service charge 

### ISSUE THREAD

**Issue by Ryach** [kimai/kimai#4119]
### Describe the problem

Could we consider incorporating an option to include an additional service charge in our invoices? This would allow us to account for various expenses, such as subscriptions or device prices, specifically those incurred when services are provided on-site. By introducing this option, we can ensure that our invoicing system accurately reflects the complete range of charges associated with our services.

### Describe the solution you'd like

In the administration, it would be beneficial to incorporate additional positions, such as "Services," that would allow us to define server subscriptions and other related items. These positions can be conveniently added to the invoice after the standard time invoice generation process. By implementing a dropdown list, we can easily select the appropriate service options and include them in the invoice, streamlining the overall administrative workflow.

**Comment by kevinpapst** [comment]
This will not be made part of the time-tracking core application.

But it sounds as if the Expenses Bundle does what you need:
https://www.kimai.org/store/expenses-bundle.html
