### ISSUE TITLE
Import existing data from toggl

### ISSUE THREAD

**Issue by suther** [kimai/kimai#4126]
### Describe the problem

Would it be possible to import data from toggl to kimai in any way (e.g. with existing importer-plugin?)

### Describe the solution you'd like

Import data from toggl  (e.g. via KAMI <--> Toggl API) to kimai

**Comment by kevinpapst** [comment]
The importer currently support Clockify, but not toggl.

I assume toggl allows to export via CSV, so please please send me an (anonymized) data example to support@kimai.org and I'll have a look.

**Comment by ebdavison** [comment]
This would be very helpful to have.  Since the CSV has not yet been attached, I am adding one.

Here is a sanitized time export file from toggl track
[toggl_time_export_sanitized.csv](https://github.com/kimai/kimai/files/15101946/toggl_time_export_sanitized.csv)

**Comment by kevinpapst** [comment]
Thank you @ebdavison 👍 Any chance you can produce one where the `Amount` field has content?

**Comment by ebdavison** [comment]
Sure, I can get that added.

**Comment by ebdavison** [comment]
Turns out that is a paid feature and I had downgraded my account to free and it does not support billing.  I will try to see if I can get an export with this field populated.

**Comment by ebdavison** [comment]
Here you go.

[Toggl_time_entries_2024-01-01_to_2024-12-31(2).csv](https://github.com/kimai/kimai/files/15119414/Toggl_time_entries_2024-01-01_to_2024-12-31.2.csv)

The billing amount column is a calculated field based on the billing rate (not available in the export) and the duration.  The billing rate is part of a different export that would include the client and/or project which would have the billing rate.  It can be calculated though if you need the billing rate with some simple math.

**Comment by kevinpapst** [comment]
Thanks, I'll need a bit to go through that.

> is part of a different export that would include the client and/or project which would have the billing rate

Interesting as well...

**Comment by ebdavison** [comment]
Here is the rest of the export items available.  These are exported separately from the timesheet entries and are delivered via a link in an email.  The timesheet entries, on the other hand, are just exported right to a CSV file in the browser.

[toggl_workspace_8301796_export_0d82bcd8-876e-46c5-996b-9e5ee2bb29db.zip](https://github.com/kimai/kimai/files/15140350/toggl_workspace_8301796_export_0d82bcd8-876e-46c5-996b-9e5ee2bb29db.zip)

**Comment by kevinpapst** [comment]
Hi, please send me an email to support@kimai.org, so we can discuss testing

**Comment by ebdavison** [comment]
email sent yesterday

**Comment by kevinpapst** [comment]
during my night 😁 but I answered 7 hours ago

**Comment by ebdavison** [comment]
Testing successfully imported records!

**Comment by kevinpapst** [comment]
Latest plugin version with support for importing "Toggl Track timesheets" is available at:
https://www.kimai.org/store/keleo-importer-bundle.html

Thanks for your support @ebdavison 👍
