### ISSUE TITLE
Global Projects

### ISSUE THREAD

**Issue by perspicuous** [kimai/kimai#413]
**Is your feature request related to a problem? Please describe.**
We have different Customers, for each customer, we have the same Project's (115) with the same activities (115+)

**Describe the solution you'd like**
I saw that there is a milestone and enough requests for global activities.
I would like to use the same solution for Projects.

**Additional context**
Did i overlook this request or is there really none for global projects?

alternatively i added the needed projects with mysql inserts.. but its sad to have so many "duplicates" in the db with just one colum (customer_id) having different values.

I appreciate the work here!

**Comment by kevinpapst** [comment]
I see that this is a problem for you and that you might run into troubles in the future when your customer base grows. Some UI elements are just not made for having hundreds times hundreds of elements.

To answer your question: there was no request existing for global projects yet and in 10 years of work for Kimai (mainly v1) there was not one person requesting it as far as I remember.
Without knowing anything else about your workflows, to me it sounds weird that you have the same 115 projects for every customer with the same 115 activities, probably the data structure just doesn't match your requirements? Do you really need to use it this way? 

Global projects would be a massive refactoring and I don't see a need for most user, but instead UX problems in many places of the application. I want to be honest: I don't see this feature coming unless you get a vast amount of users voting for it.
But: we can talk about other improvements that might be useful for you (like batch processing, automatic creation of projects when creating a new customer ...).

**Comment by perspicuous** [comment]
Good Morning

The Company im evaluating this for is doing the same things for different customers. And they have the same structure allready just inside excel.

So imagine.

All Customers come from the same industry and this company does the same thing for all Customers repetitively. they organize Congress, workshop, Sponsoring etc. Make theri websites, send out their letters etc.

Cheers Timur

**Comment by srdco** [comment]
Might this use case better be organized as Activities, with the Project being being basically 1:1 (one-to-one, except perhaps when you do a second round or something) with the Client?
