### ISSUE TITLE
php.CRITICAL: Uncaught Error: App\Configuration\SamlConfiguration::getProvider()

### ISSUE THREAD

**Issue by mathias4github** [kimai/kimai#4130]
### Describe the issue

hi,
after the last update, I got the following issue:

 php.CRITICAL: Uncaught Error: App\Configuration\SamlConfiguration::getProvider(): Return value must be of type string, null returned {"exception":"[object] (TypeError(code: 0): App\\Configuration\\SamlConfiguration::getProvider(): Return value must be of type string, null returned at /opt/kimai/src/Configuration/SamlConfiguration.php:30)"} []

No more things where changed. 

Any ideas?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.26

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
> after the last update

which update?

**Comment by mathias4github** [comment]
from 1.30.11 to 2.0.26

**Comment by kevinpapst** [comment]
You checked "I read the documentation". 
So I assume that you adjusted your local.yaml accordingly to the updated SAML docs, did you?

**Comment by mathias4github** [comment]
yep I did ... but I missed the tiny adjustement : provider: keycloak ... now its working

**Comment by kevinpapst** [comment]
I'll add a workaround to core, so others won't hit that issue. Thanks for your feebdack 👍
