### ISSUE TITLE
Icons & CSS not loading

### ISSUE THREAD

**Issue by techx-admin** [kimai/kimai#4131]
### Describe the issue

After configured and run kimai on browser with ip-address/kimai

then dashboard and all loading but CSS & Icons are not loading

FYI I have given all access to the file & folder 

Please find the attached screenshot

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.26

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/131434354/18022dc0-5d10-4c17-aec3-f454edc17835)

**Comment by kevinpapst** [comment]
See https://github.com/kimai/kimai/issues/4106

As written in all requirement sections: Kimai does not support running in a subdirectory.
