### ISSUE TITLE
Possiblity to add a description for a new entry in "Wochenstunden"

### ISSUE THREAD

**Issue by s3ppo** [kimai/kimai#4136]
### Describe the problem

maybe its already included but i coulnt find it. :D

would be nice to add a description also if i add hours per "wochenstunden" mask.
(sorry dont know the english translation)

at the moment i add the hours, then i have to switch to "meine zeiten" and then i have to pick the entry and add the description there.

### Describe the solution you'd like

maybe in the dropdown of the input field where i added hours? or a new column right to project and task.

**Comment by kevinpapst** [comment]
Duplicate of #3307 - which did not get any upvote within one year

**Comment by s3ppo** [comment]
Hmm okay so everybody is doing the work around or nobody is using the „wochenstunden“ mask. Thanks to anybody who can tell me a best practice 😉

**Comment by kevinpapst** [comment]
> nobody is using the „wochenstunden“ mask

far away from reality. 

use the tool that matches your use-case. maybe calendar drag&drop is more what you need.
