### ISSUE TITLE
"provider" option for config is misleading for selfhosted SAML

### ISSUE THREAD

**Issue by darioackermann** [kimai/kimai#4137]
### Describe the issue

The new 2.x version requires `local.yaml` now requires to have a `provider` key present when being used with a SAML solution 

This now required option is very misleading as at first it looked for me like custom SAML support has been dropped.
I have realised that the config will happily accept any provider, so I've simply set it to `own`.

Suggestion 1:
- We add the option `custom`, also to the docs to remove confusion

Suggestion 2:
- We drop the requirement of having to specify `provider` (as in the 1.x versions)

I see you have added a default fallback in https://github.com/kimai/kimai/pull/4107/commits/5f2b7658d955f83184f4fa61e621cb115f4fa6c3, I'm happy to propose the corresponding doc change if you want me to 😊 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.26

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by darioackermann** [comment]
Free easteregg: If you set `provider` to a fontawesome icon name, you actually get a nice image for the login button ;)
![image](https://github.com/kimai/kimai/assets/35274810/715680da-c31f-4060-84b4-53d592da78e4)

**Comment by kevinpapst** [comment]
congratulations, you figured out the exact use-case. 
why exactly do you need a documentation for it? 😁 

I added a sentence to the SAML docs:
- `provider` (string) this is a free string, whose ONLY use-case is to show an icon: you have to define a name from the [fontawesome brand icons](https://fontawesome.com/v5/search?o=r&m=free&f=brands), e.g. `microsoft`, `google`, `aws`)

Edit: the next minor will drop the requirement and incudes a `default` string in the provider key

**Comment by darioackermann** [comment]
Admittedly, I was a bit scared first that the provider option would add potentially breaking magic. Thanks for the docs addendum and sorry for the (unintended) mislabel as bug :)
