### ISSUE TITLE
Error 503 again

### ISSUE THREAD

**Issue by Memurame** [kimai/kimai#4143]
I have found a solution after all.
Apparently the same problem. 
I did an update yesterday and the cache was not cleared cleanly.

https://github.com/kimai/kimai/issues/3432#issuecomment-1192561877

_Originally posted by @Memurame in https://github.com/kimai/kimai/issues/4140#issuecomment-1611130289_
            

Apparently, this does not fix the problem.
I keep getting the message 503 after a while.
After that I delete the cache as described, then it works again for a while.
Possibly a problem with the cache function?

Unfortunately there are no logs, the error 503 just comes. Mostly when calling projects, activities, customers.

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/discussions?discussions_q=is%3Aopen+all-inkl+

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/discussions/2859

**Comment by kevinpapst** [comment]
no feedback, closing
