### ISSUE TITLE
Zero duration does not trigger end-time calculation

### ISSUE THREAD

**Issue by jassonmc** [kimai/kimai#4147]
### Describe the issue

Hello there
Just got started with your wonderful piece of software and are trying to get the hang :)

We are using the "Standard" time tracking mode.
We sometimes have entries, where we need to set a fixed price and zero time.
Therefore, we have left the default setting ON, where zero entries are allowed.

If I start a new time tracking entry and explicitly define "0" or "00:00" as duration and hit the save button, the time is starting to tick anyway, even though I wanted to create a zero minutes entry on purpose.

I tested that behavior also in your demo instance, same outcome.

The documentation states: "to create a running entry the end and duration field needs to be empty"

I would have guessed, to create a zero entry without having the clock run is by entering "0" or "00:00", but that does not work, unforunately.

Any advice would be very welcome, thanks.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.26

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
That is an unusual edge-case, I have to think about it.
Anyway: zero duration does not set the end-time. Copy & paste the start-time into the end-time field and save.

**Comment by jassonmc** [comment]
I just checked it out and in Kimai v1.19.6 exactly that works as I thought.
Entering "0" in duration field fixes the entry to zero and sets the end date/time automatically to the same as start.
No running timer, just finalized time entry with 00:00 duration and exactly what I had in mind.

Would be extremely helpful to have that same behavior reproduced in Kimai v2.
I wouldn't be surprised if others, which have been using Kimai v1 before, are going to miss that feature now.
Thanks for considering.

**Comment by kevinpapst** [comment]
Thanks for your feedback 👍 

But Kimai is a time-tracker. Zero second entries just do not make any sense. To me that sounds as if you are recording expenses with it in a broken manner. Tell me if I am wrong please, but that is the only reason I ever heard someone actually mention 0 sec. entries.

> I wouldn't be surprised if others

I get feedback from hundreds of users, until now no-one said anything about it. I often hear that phrase, when someones workflow is influenced, but that doesn't mean it is relevant for the broad user base 🤷 
Anyway: I am happy to be proven wrong, when this topic receives upvotes.

Maybe you want to check-out the [expenses plugin](https://www.kimai.org/store/expenses-bundle.html) in the meantime, which was made to record fixed prices of "things" and with its purchase support further development of Kimai 👍

**Comment by jassonmc** [comment]
There are three reasons for zero duration in our case:
1. For a certain activity, the employees get a monthly flat fee, which is therefore not to be recorded by hours, only the amount the customer is going to pay.

2. Since Kimai is also recording the history of projects with each time entry, it makes perfect sense to us to put general, important notes also into a time recording. We then just record an empty time entry with a relevant description and tag. Works great!

3. There is also a need for expense recordings and I did indeed check out the mentioned plug in, but it didn't fit our needs. Having to enter another menu just to enter expenses, which cannot be easily seen by the employees together with their time tracking entries, makes every day life harder here, since there always needs to be a package of entries, which an employee should be able to easily spot, if they are all there for a certain day. The only "easy" way to see time entries together with expenses is when having created the invoice, which is way to late for an employee to have spot an eventual error or if he forgot to create the corresponding expenses. Another reason is, that we only have a few invoices created directly out of Kimai, since most time/expense recordings need to be exported from Kimai and imported into another system, as the payment procedure here dictates. There is no export option to have time recordings and expenses exported in one go.
We always need to record the same single expense here and zero duration entries are the perfect fit for our case. Anything else would complicate the process at different stages.

___
Don't get me wrong; I don't try to avoid paying for your great work, quite the opposite, since we did already invest in "Custom Fields" and I will recommend the coming week also the "Audit Trail Logs" internally and hope it gets through. Since there is no "recycle bin" functionality, that does at least help to reproduce what happened, if something gets deleted by someone that should not have done so, but still needs delete permission for daily work.

At the end of the day I try to find the most simple solution to the problem at hand and zero duration entries are just that for us.

If you don't see that zero duration entries make sense, then why did you introduce exactly that setting into the system settings to explicitly allow that? :)

I don't see any draw back to not reintroduce Kimai v1 behavior, as it would be inline with it's corresponding system setting.

On a side note:
Until now, I never have assisted in programming but that might be a simple enough job I might be able to work out :)
Could you eventually help me get started so I can potentially contribute to the project?
Until now I just have written shell scripts and power shells.

**Comment by kevinpapst** [comment]
As I already said: zero second entries work. Just not when entering a 0 in the duration field.

The check is here:
https://github.com/kimai/kimai/blob/main/assets/js/forms/KimaiTimesheetForm.js#L321

But again: I will think about it, because the only time someone mentioned 0 second entries is when he tried to bastardize time-tracking for expense management - and that is not what I care about.
