### ISSUE TITLE
Custom CSV invoice template

### ISSUE THREAD

**Issue by pyranha-ch** [kimai/kimai#4148]
### Describe the issue

According to the [documentation](https://www.kimai.org/documentation/invoices.html) it should be possible to define a custom .csv template which can be used for invoices. However I can't get my .csv to be recognized by kimai. .xlsx works just fine and is picked up immediately after a container restart, but .csv keeps being ignored. I also double-checked that its UTF-8.

The content of my .csv is like this:
"Date","Duration","additional fields"
"${entry.begin}","${entry.duration_format}","additional values"

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.26

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Sorry, but the docs are outdated and were written for Kimai 1.x. 

I just updated them and removed the CSV extension, as it is not supported any longer (actually no-one ever used it or complained that it was removed).

You can checkout https://www.kimai.org/store/invoice-bundle.html which ships support for text (can be used for CSV), json and xml formats.
