### ISSUE TITLE
Fraction of duration been factured (billable flag for timesheets)

### ISSUE THREAD

**Issue by yweidmann** [kimai/kimai#415]
Hi Kimai2

I am looking for a replacement of my "old and home-made" Access-TimeTracking. Kimai looks very promising to me. But I am missing an important feature in my case:
In m

- Most cases, 100% of the duration can be factured.
- Some cases I have to reduce of the duration (e.g. 50% due to research or self-teaching), but I want to keep track of all activities (even at 0%) for controlling.
- The export for invoices should only show the part of the duration which can be factured and the fraction should be hidden.

Question: Do you have or do you plan such kind of feature or is there a workaround?

Looking forward to any hints.

Best regards,
Yvo

**Comment by kevinpapst** [comment]
Hi Yvo,
thanks for the feature request! For now I can think of two solutions:
1. You apply a fixed rate on these tasks that you want to charge only for a percentage (e.g. you charge 100 per hour, work 3 hours and charge 2 hours - then set fixes rate for that entry to 200). Contra: your client will see it in the invoice if you export all time-records.
2. You setup different activities, one which a hourly rate of 100 and one with an hourly rate of 0. Then track 2 hours on the paid task and 1 hour on the unpaid task. Pro: also fixes your invoicing problem, as you only export the paid activity.

I am not sure how many people have the same requirement, lets see if people come up and vote for this. If enough people support this request, I will add it.

**Comment by kevinpapst** [comment]
> Looking forward to any hints.

Looking forward to an answer :-)

**Comment by yweidmann** [comment]
Mh, interesting that not more people having this requirement. The first version does not look applicable for me. The second one would be a workaround with two important drawbacks:
- We will have a duplication of activities. This reduces the nice and simple approach and overview of Kimai
- Quite often, we have to manipulate the hours facturated. In case of product development and research and development projects, we cannot charge all the work done to the clients, so we keep them internally, but connected to the project / product.

The main motivation behind is, to have a complete record of all the activities within a project. Including the hidden numbers of training on the job etc.

**Comment by kevinpapst** [comment]
What about tracking all the work on the same activities, but splitting the work in single entries. Track the ones paid as usual and create new entries for the non-chargeable work and manually setting their rates to 0? I understand this is not ideal, as users normally shouldn't be able to even see or set their rates (which I will work on soon).
All would be just a workaround, if you need a solution now.

In the long run there should be a field which can be set to a percent value. But what would you expect this field to be? A slider between 0 and 100% or can that even be higher than 100%?

**Comment by yweidmann** [comment]
Workaround:
- The mentioned workaround sounds promissing. Will also allow an easy move of hours between the individual (paied and not-paid) entries.

Long run:
- Personally I would not use sliders. What about a DropDown with pre-defined values which are open to be set by the administrator in the settings. E.g. a list such as "0, 25, 50, 100, 150" percentage.

**Comment by rarvin** [comment]
I assume the drop down or billable/non billable with slider would be available at a per task level. If so that would be great.

**Comment by rarvin** [comment]
Would this exclude the record in the invoicing alone or would this exclude in the dynamically calculated values like export (sum), my times etc. This is also what we are looking for.

**Comment by Recoil1980** [comment]
Upvoting this issue - on invoices I just noticed that each users hours spent working are calculated in the totals for the customer, but we charge a flat rate that is separate to cover additional costs.  A boolean flag of making the timesheets not billable, so a per-hour-labor charge could be added as an expense would help to solve this.

**Comment by kevinpapst** [comment]
The billable flag is available under the hood already (eg. in the timesheet table) and taken into account in invoices (non billable records are not included).
This is not yet exposed in the frontend ... but you can see it in the Expenses plugin whose entries are either billable or not.

**Comment by kevinpapst** [comment]
The billable flag is now available in master (for version 1.14).
Non-billable timesheets are excluded from invoices, you can search for them and they are excluded from budget calculations.
