### ISSUE TITLE
Statistic of time-used vs. time-budget

### ISSUE THREAD

**Issue by yweidmann** [kimai/kimai#416]
Dear Kimai

The budget always takes time * rate as reference. Is there a way to use only time (hours) as budget and showing the time (hours) available for each activity?

Thank you very much for any hints.

Best regards,
Yvo

**Comment by kevinpapst** [comment]
Are you sure you are talking about Kimai 2? There is nothing like budget for now.

**Comment by kevinpapst** [comment]
@yweidmann I need further input, otherwise I can't help.

**Comment by yweidmann** [comment]
Oups, sorry for keeping you waiting.
You are fully right, I mixed up the features of v1 and v2.

From my point of view, an indication of how many hours are left for the individual activities would be great. I aggree that the rate is an important factor. But for discussions and group meetings, the number of hours will be more intuitive.

**Comment by kevinpapst** [comment]
Do you want to have budget on projects or activities or both?
What should happen if a budget is reached in the long run (first version will only display it)?
What if activities are global and not associated with a project?
Where would you want to see the information?

**Comment by yweidmann** [comment]
No, it is all about v2.

- Usually we have (time) budget for each activity. Sum of all activities gets the total budget for the project. 
- Budget per project is in my case not used. As above.
- The budget and the statistic about is in my case just informative. Usually I am just using "+ x h" / "+ x %" and  "- x h" / " - x %" in red and green. That will be enough. Otherwise it should be combined with a project management tool. But that will be an overkill.
- A nice feature would be an email message at 50%, 75% and 100% budget used (steps in the configuration).
- The information could be shown in the Dashboard within a section of "Active Projects". Quick overview of the current situation.

Good question about the global activities.
- Currently no need in my case.

**Comment by kevinpapst** [comment]
Ok. I would have expected a budget rather on a project than an activity - so many things are handled different between companies, that its hard to find a way working for all. 
I guess Kimai should support budget on both levels. 

More question that come to my mind: 
- should activity and project budgets influence each other or work completely independent? 
- should the budget be based on money or hours? Both are total valid use-cases, but should Kimai support both at the same time or should the "calculation method" be configurable?

**Comment by yweidmann** [comment]
activity and project budgets influence each other or work completely independent:
- Both can be ok.
- But from my point of view, the project-budget is the sum of all activity-budgets. Therefore not independant.
- Leads to the following idea: Either you set a budget for each activity or you set a budget for the project.

should the budget be based on money or hours:
- Both should be possible, but not at the same time.
- The calculation method should be configurable.

**Comment by ChristianS911** [comment]
Hi Kevin,

we are using KIMAI V1 and also the Budget Control. In general we defined the budget on the Project level.
We use the short summarize in V1 of Total / Budget / Billable / Approved to monitor the projects.

In the End we like to have the same or similar functionality as in V1.
Do you plan something like that in short / middle / long term ? 
Do you have an idea or functional overview about the common needs for a budget control widget ?

Regards,
Christian

**Comment by kevinpapst** [comment]
Hi @ChristianS911 
> Do you plan something like that in short / middle / long term ?

Yes

> Do you have an idea or functional overview about the common needs for a budget control widget ?

I have my own ideas and already received some input, but if you have more ideas: please share them!

**Comment by ClintfromCanada** [comment]
So I added the budget field import from v1 to v2 and it works.  We happen to use the budget field as hours budgeted per project.  So when combined with the fixedRate for each project, Kimai should then be able to calculate the overall cost per project in terms of both budget dollars and expended dollars (via expended time obviously).  I can give more information if needed, I hope this helps out.

One other related area I noticed in the invoice area is that when you are making an invoice template, I can't see any option for "Project Grouped - One entry per Project".  That would also be helpful for multiple projects per customer in the billing period.

**Comment by kevinpapst** [comment]
> Project Grouped - One entry per Project 

@ClintfromCanada new issues please

And to all who commented. You have to vote in the inital posting via the 👍 reaction.
I do [filter the issues by this counter](https://github.com/kevinpapst/kimai2/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) to see which feature requests get the most upvotes to decide what will be implemented.

**Comment by ClintfromCanada** [comment]
Sorry - new to commenting in Github...  I don't follow - did you want me to add the "One Entry Per Project" request as a new issue?

**Comment by kevinpapst** [comment]
Yes, exactly that - probably with some additional words about invoice etc. 
If you put the idea somewhere in a comment in a thread that is related to a different topic it will be lost...
