### ISSUE TITLE
Language setting does not work immediately

### ISSUE THREAD

**Issue by robinrosenstock** [kimai/kimai#418]
**Is your feature request related to a problem? Please describe.**
The language setting in the preferences does not work immediately. You need to logoff and login again. I wasn't aware of this fact and so searched 15min for the failure why the language is not switching.

**Describe the solution you'd like**
Maybe there are technical issues, but it would be better if the language setting executed immediately and the interfaces and its elements are all reloaded.

**Describe alternatives you've considered**
At least, there should be a note (in the settings) that changing the language needs a relogin.

**Comment by kevinpapst** [comment]
I thought about this before as well. I'll check the place and see how complicated it is to perform the redirect after saving the preferences.

**Comment by kevinpapst** [comment]
Was easy to fix, you can test #421 if you like

**Comment by geniusupgrader** [comment]
tested and works, great!
