### ISSUE TITLE
Change settings shortcut card position to be `sticky`

### ISSUE THREAD

**Issue by sharky98** [kimai/kimai#4185]
### Describe the problem

The settings shortcut card is very helpful, but when navigating through the settings, it stays at the top of the page. To use it again to go to another section, I need to manually scroll to the top of the page.

#### Sticky position

The first quick fix could be using Bootstrap [`sticky-top`](https://getbootstrap.com/docs/5.3/helpers/position/#sticky-top) CSS class. I think this would go [there](https://github.com/kimai/kimai/blob/385753fbc38ae140723f2968b9d28ee1d3c23ccd/templates/system-configuration/index.html.twig#L7).

```diff
<div class="row">


    <div class="col-12 col-md-3 mb-3 d-none d-md-block">
-        <div class="card">
+        <div class="card sticky-top">
            <div class="list-group list-group-flush">
```

One downside is, if the user screen height is under 700px, the options at the bottom of the card will be hidden. I think this is fairly minor downside knowing that this card is hidden anyway under the [`md` breakpoint](https://getbootstrap.com/docs/5.0/layout/breakpoints/#available-breakpoints) (768px). Since this is an admin page, I would assume (hopefully not wrongly 😂!) that most admin user will have at least a height of 700px when going through that page on a desktop. However, this might need to be reviewed if new sections are added in the settings.

#### Back to top link

This quick fix is the typical "back to top" button or link. However, I think it would compete spaces with the link to help already shown.

#### Third level of Navigation Menu with anchors

All settings section could be incorporated in the navigation menu as children of `System->Settings`. The links would be anchors (same as in the card), sending the user to the all-in-one setting page anchor position.

#### Third level of Navigation Menu with links

All settings section could be incorporated in the navigation menu as children of `System->Settings`. The links would be "hard" link to specific page for each section. This seems to already be possible (for example, if you append manually `edit/activity` to the system configuration url, seems to be managed by the [`sectionAction`](https://github.com/kimai/kimai/blob/385753fbc38ae140723f2968b9d28ee1d3c23ccd/src/Controller/SystemConfigurationController.php#L90-L114) ).

**Comment by kevinpapst** [comment]
Thanks for your detailed input @sharky98 👍 
 
I applied several changes and made it (hopefully) a bit easier to use on small devices as well.
