### ISSUE TITLE
No (negative!) values in Reports when using AddIn Deduction Times

### ISSUE THREAD

**Issue by RuedigerLorbeer** [kimai/kimai#4191]
### Describe the issue

We're useing the Deduction Times AddIn. When we use weekly, monthly or yearly reports for useres there are no values in lines for activities with activated deduction times. The lines are shown and the addition are working correctly in rows and columns. Only the field where we're expecting the values are empty.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.28

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Screenshots

![grafik](https://github.com/kimai/kimai/assets/139757473/bc70e10f-9f4e-4dd5-a7e4-8a81f1b0af9f)

**Comment by kevinpapst** [comment]
Works for me:
<img width="626" alt="Bildschirmfoto 2023-09-19 um 18 04 08" src="https://github.com/kimai/kimai/assets/533162/c66b959f-1542-4b9f-8009-04b67bb3eb90">
And in report:
<img width="1221" alt="Bildschirmfoto 2023-09-19 um 18 04 54" src="https://github.com/kimai/kimai/assets/533162/f15c7905-f237-4f1b-80f9-e5fe21468103">
