### ISSUE TITLE
Audit logs: Changes to "exported" state are not shown in timesheet specific change history, when using the "mark as exported" switch during exports

### ISSUE THREAD

**Issue by de-sec** [kimai/kimai#4192]
### Describe the issue

Good Morning everyone, 

i'd like to report a bug within the audit trail extention: 
1. if exports of timesheets are performed while using the option "mark as exported", the audit-log plugin doesn't show changes to the exported state within the timesheet specific change history (it's shown in the global change history only)

is there any possibility to add this aspect?

Best regards

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.28

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Please report plugin specific issues at: 
https://github.com/kevinpapst/kimai-plugins

This repository is about the core software only.
