### ISSUE TITLE
Collapsible left panel menu to save horizontal space

### ISSUE THREAD

**Issue by bilekt3** [kimai/kimai#4196]
### Describe the problem

Kimai v1 had collapsible left panel menu. I miss this feature in v2 and I would like to propose new feature to bring similar functionality to v2

### Describe the solution you'd like

Collapsible menu with icons without text (text hints will remain after mouse hover)

<img width="254" alt="Screenshot 2023-07-21 at 7 41 26" src="https://github.com/kimai/kimai/assets/381740/34d44d6d-4426-403f-8640-0a0dfd32b936">

### Describe alternatives you've considered

N/A

**Comment by kevinpapst** [comment]
If [tabler](https://github.com/tabler/tabler) (the frontend framework that is used by Kimai) will add such a feature, I will adopt it.

But until then I have no plans to add it.

**Comment by bilekt3** [comment]
@kevinpapst Thanks for response, OK fully understand, I thought that was intentional decision...

**Comment by kevinpapst** [comment]
No, I would like it as well. I hope at some point this feature will come back.
But I cannot add it myself (as it needs to be implementd upstream at Tabler), so I closed the issue for now.
