### ISSUE TITLE
My times separator and sums for each day

### ISSUE THREAD

**Issue by bilekt3** [kimai/kimai#4197]
### Describe the problem

My most used feature in Kimai v1 was separator between dates in My times section, it helps me quickly validate my entries. V2 currently missing this feature and I would like to propose to bring this feature back to v2.

### Describe the solution you'd like

In My times section when table rows dates crossing day subtotal and visible separator will be added.

<img width="519" alt="Screenshot 2023-07-21 at 7 46 18" src="https://github.com/kimai/kimai/assets/381740/188a8b89-d915-4958-9adc-129d76aad3b8">

### Describe alternatives you've considered

N/A

**Comment by kevinpapst** [comment]
Activate it in your user preferences

**Comment by bilekt3** [comment]
@kevinpapst Thank you! I was unaware of this. Fixed my problem gracefully.
