### ISSUE TITLE
How to create English translation with Czech locale setup?

### ISSUE THREAD

**Issue by bilekt3** [kimai/kimai#4198]
### Describe the problem

This is not particular bug V2, but I unable to figure out how to setup Kimai in English Language (internal policy) but have Locale setup for Czech Republic (legal/user requirements). Any suggestions will be welcome.

### Describe the solution you'd like

Proposed solution will explain how to fully customize Kimai V2 language/locale duo.

### Describe alternatives you've considered

I have considered to switch to Czech language, but is does not suite my needs.

**Comment by kevinpapst** [comment]
See #3934 
If there is no locale existing that does the correct thing: I am sorry, but I currently have no plans to separate locale from translation.
