### ISSUE TITLE
Report Project by month, activity, user: Missing horizontal scroll bar

### ISSUE THREAD

**Issue by HeinzWuert** [kimai/kimai#4202]
### Describe the issue

In this report, the window is not delimited downwards so that a horizontal scroll bar can be displayed in the visible screen area.
Depending on the screen resolution, the scroll bar below disappears if there are too many data records.

A preset how many lines max should be displayed in the window to keep the scroll bar visible.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
The scroll bar is at the end of the table.
I do not think this is really solvable unless people start using devices, that allow horizontal scolling (like touchpads or a modern mouse).

Restricting the amount of lines in the table sounds like trouble.
