### ISSUE TITLE
Dashboard showing wrong data, It showing 24 hours for each day for particular project and activity

### ISSUE THREAD

**Issue by vikasgunjeti** [kimai/kimai#4204]
### Describe the issue

Dashboard showing wrong data, It shows 24 hours for each day for a particular customer, project, and activity. Suppose If I fill 5 hours for today for any activity of any project, then it is showing as 24 hours in the dashboard (extra 19 hours from particular activity).

Total Hours for Month, Week, and Day is correct. But this extra vertical bar showing for each and every day. Though I am not filling it.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.19.4 stable

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![Inkedimage](https://github.com/kimai/kimai/assets/60781391/65a4b3b7-9bc9-497a-8707-b891af25b0cc)

**Comment by kevinpapst** [comment]
Kimai does not magically fill values which are not there.
You have likely a weird timesheet that started in the past and ends in the future and which has hundreds of hours.

Please note: Support for a Kimai version which is so old cannot be given anyway.
But in this case I am certain that this is not a bug.
