### ISSUE TITLE
Check end time with disabled "future time entries" as well

### ISSUE THREAD

**Issue by techx-admin** [kimai/kimai#4205]
### Describe the issue

From setting -> disable "Allow time entries in the future"
to prevent entry of future time
example : today date is 26th July 2023 & time is 10:58am, 
now my assumption for this setting is user cannot enter time of 11:30am as I have  disable "Allow time entries in the future"

If I am doing any wrong please guide me, but my request Is how we can restrict user to enter time of future even 10min also from current time.

kindly do the needful.
Thanks

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.26

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/131434354/5c41754a-725e-4c42-ad78-1b903b961f5a)

**Comment by SaturnusDJ** [comment]
I tried on demo (https://demo-empty.kimai.org) with "Allow time entries in the future" disabled. Then,'the most future entry' I can make is 2 minutes ahead of current time.

Could this be a time zone or server time issue that you have?

**Comment by techx-admin** [comment]
> I tried on demo (https://demo-empty.kimai.org) with "Allow time entries in the future" disabled. Then,'the most future entry' I can make is 2 minutes ahead of current time.
> 
> Could this be a time zone or server time issue that you have?

1. While doing configuration of kimai I have changed timezone with Asia/Kolkata and it display proper timings also while adding any entries in system
2. After your comment I checked my ubuntu server timezone which is Mon 2023-7-31 05:42:43 UTC and same for Universal/Local & RTC time
my question: Is I have to change this configuration also for timezone as its UTC and my timezone is +5.30 GMT

**Comment by techx-admin** [comment]
![image](https://github.com/kimai/kimai/assets/131434354/879e7a5a-ebf8-4748-8e5c-e6abff2421fd)

This screenshot from **kimai demo** 
current time is 7:56AM after disable allow entries in future
still taking time 19 min ahead 

-> FYI I have **changed timezone  of my server** with +5.30 IST but still facing same issue in my ubuntu server
Kindly suggest some solutions for this

PS: I have issue in **End Duration Time** while begin time validation is working file 
but while closing same task in future time, It is taking future entry It must restrict to enter future time, it should allow 2 or 5min ahead 



Thanks in advance

**Comment by kevinpapst** [comment]
This code checks the future time:
https://github.com/kimai/kimai/blob/main/src/Validator/Constraints/TimesheetFutureTimesValidator.php#L42

It uses the timezone of the timesheet (which is changed/created) to compare to "now". 
Which is usually the timezone of the currently logged-in user.

**Comment by kevinpapst** [comment]
Aaaah, now I see your issue (screenshots and explanation helped, I missed that the last time reading!): 
This validation checks the begin date-time, not the end date-time.

**Comment by techx-admin** [comment]
> Aaaah, now I see your issue (screenshots and explanation helped, I missed that the last time reading!): This validation checks the begin date-time, not the end date-time.

Yes you are right
it checks begin time

Question: Is it possible to restrict user while doing End Time
example: if Begin time is 9am and current time is 10am so user cannot enter end time as 10:10 or 10:20

This is real time scenario which happened in our team.

**Comment by kevinpapst** [comment]
Actually I can't remember why I only added a check for the begin date.
I think there was a reason, but why 🤷  

I'll add a check for end-time as well.

**Comment by techx-admin** [comment]
Thanks for adding this request in update

**Comment by kevinpapst** [comment]
Fixed with 2.0.30
