### ISSUE TITLE
404 on projects administration

### ISSUE THREAD

**Issue by pcxeon2** [kimai/kimai#4206]
### Describe the issue

Hi,

Since update 2.0.29 I get a 404 error when I go to the Administration > Projects page

Everything else works fine.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.29

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
> Logfile
> No response

You want help, you have to fill all fields. 

It's an environment issue anyway. Closing.

**Comment by pcxeon2** [comment]
This is a 404 error generated by Kimai and not by apache.
The apache logs don't return anything and neither do the kimai logs.
![Screenshot 2023-07-27 104559](https://github.com/kimai/kimai/assets/20686533/ae023b62-a3a7-4742-af97-2a86e526c07b)
