### ISSUE TITLE
Unable to install into existing new database

### ISSUE THREAD

**Issue by MichelGreijmans** [kimai/kimai#4218]
### Describe the issue

The installer assumes an database must be created. This isn't the case in most cases, and I believe by default the installer should only create a new database if the database doesn't yet exist, or at least give an option to skip database creation:

```
# bin/console kimai:install -n

Kimai installation running ...
==============================

                                                                                                                        
 [ERROR] Failed to create database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user  
         'kimai'@'localhost' (using password: YES)  
```

The documentation also assumes a database is created before the execution of the above command.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.28

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Nope, that is not correct:
https://github.com/kimai/kimai/blob/main/src/Command/InstallCommand.php#L117

You supplied invalid credentials or your DB user has wrong permissions
