### ISSUE TITLE
Custom permission not detected when given to custom role

### ISSUE THREAD

**Issue by Jelle-S** [kimai/kimai#4226]
### Describe the issue

When a plugin defines a custom permission in its `Extension` class, it's not detected when that permission is only given to a custom role, and not one of the default roles. Unfortunately I don't have the time to further debug this, and I've fixed it by giving the permission to `ROLE_SUPER_ADMIN` in the extension, but it's worth looking into imo.

Permission didn't show up with this code after reloading kimai:
```
        $container->prependExtensionConfig('kimai', [
            // ROLE has to be created manually via the Administration UI
            'permissions' => [
                'roles' => [
                    'ROLE_API_SYNC' => [
                        DigipolisBundle::PERMISSION_SKIP_VALIDATION,
                    ],
                ],
            ],
        ]);
```

Permission _does_ show up with this code after reloading kimai

```
        $container->prependExtensionConfig('kimai', [
            // ROLE has to be created manually via the Administration UI
            'permissions' => [
                'roles' => [
                    'ROLE_API_SYNC' => [
                        DigipolisBundle::PERMISSION_SKIP_VALIDATION,
                    ],
                    'ROLE_SUPER_ADMIN' => [
                        DigipolisBundle::PERMISSION_SKIP_VALIDATION,
                    ],
                ],
            ],
        ]);
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.29

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
I think this should be possible by adding it to a fake "set".
```php
            'permissions' => [
                'sets' => [
                    'custom_fake_set' => [
                        DigipolisBundle::PERMISSION_SKIP_VALIDATION,
                    ],
                ],
            ],
```
