### ISSUE TITLE
Weekly working hours : zero-items created for Heat-tasks when adding timesheet

### ISSUE THREAD

**Issue by petervanhee** [kimai/kimai#4228]
### Describe the issue

When creating a timesheet-entry in Weekly working hours where there are also Heat-tasks present , zero-items are created for every day of that week on those Heat-tasks. 
Can be reproduced. See screenshots.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.29

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![Weekly Hours empty](https://github.com/kimai/kimai/assets/69186790/e7e29730-83a4-43ae-aef8-0f1c5736aea2)
![Weekly Hours one entry](https://github.com/kimai/kimai/assets/69186790/dd780107-99ca-4f26-983c-d8d89c38ed9c)
![Weekly Hours zero items](https://github.com/kimai/kimai/assets/69186790/6cd5205b-0c7e-4bef-9270-3ec820a1f97d)

**Comment by kevinpapst** [comment]
Not a Kimai core issue:
Heat tasks are a custom implementation, which was created before "weekly timesheets" nor the new major Kimai version was available.
