### ISSUE TITLE
Weekly working hours : time can be booked on a task which has the invisible state

### ISSUE THREAD

**Issue by petervanhee** [kimai/kimai#4229]
### Describe the issue

In weekly working hours I am able to do a timesheet entry on a task which has the 'invisible' state. This should not be possible. 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.29

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![Weekly Hours invisible](https://github.com/kimai/kimai/assets/69186790/4c252bb6-dd0b-468c-b4ee-7510e54cceeb)
![My Times invisible](https://github.com/kimai/kimai/assets/69186790/e72890aa-5538-4ed5-bea4-810019eec0b8)
![Invisible task](https://github.com/kimai/kimai/assets/69186790/ae6544c2-ef97-4905-93fd-5d0d12d6effa)

**Comment by kevinpapst** [comment]
Thanks, will be fixed with the next minor
