### ISSUE TITLE
Summarize hours in My Timeentries

### ISSUE THREAD

**Issue by xstable** [kimai/kimai#4231]
### Describe the problem

Filtering in "My Timeentries" is awesome. 
Only thing that is missing is a TOTAL amount of duration for all chosen days

### Describe the solution you'd like

![image](https://github.com/kimai/kimai/assets/1778068/f9d38b43-4db1-4218-9617-04bf907fd9f7)

As we have it per day, it would be very time-saving to also have an Total-Duration for the whole filtering.

**Comment by kevinpapst** [comment]
Take a closer look at the title "Meine Zeiten (1:14)" 😀

**Comment by xstable** [comment]
Ahh, thank you. Didn't saw that. 😊 

Great work! 🏆
