### ISSUE TITLE
Upgrade from 1.x to 2.x failing, same issue with a fresh install

### ISSUE THREAD

**Issue by RetroLoom** [kimai/kimai#4232]
### Describe the issue

First attempt to upgrade my kimai installation from 1.30.9 to current 2.0.28 failed. It seems something is not loading with interface correctly. Fortunately I was able to checkout and revert back to 1.30.9 which still works correctly. I tried to a do a fresh install today with another sub-domain, and ended up with a similar problem once everything was set up.  No errors with installation, everything seemed to work as expected. Once logged in I was presented with a similar screen. 

I am using php 8.1 but also tried 8.2 with no success. Checked file permissions, but bluehost does not seem to use www-data as a group. 

Might try to use softaculous to see if it works that way, but I would prefer a manual installation if possible. 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.28

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Logfile

var/log/prod.log does not exist on this fresh install

### Screenshots

![chrome_75ZghHwHOJ](https://github.com/kimai/kimai/assets/80274795/d007c707-d7f7-45af-af50-1582691561e7)

**Comment by RetroLoom** [comment]
After trying to switch the new fresh install to 1.30.9 and reloading it through console, I was able to get some CSS elements but it does not seem to be fully functional.

![chrome_j5N5wPHmBH](https://github.com/kimai/kimai/assets/80274795/3833bf4e-e6ac-45f6-8149-10810866fe36)

**Comment by kevinpapst** [comment]
Kimai does not work in subdirectory. /public/ is not allowed to be in th URL. Read the docs, it is explained how to configure your webserver.

**Comment by RetroLoom** [comment]
It is not installed in a subdirectory, it is in the root of the subdomain. I also have it pointing to /public with .htaccess. I have set up a few kimai installs before without any issues and this is should be the same. I will try with softaculous and see if that works.

**Comment by kevinpapst** [comment]
Your initial screenshot showed that /public/ is in the URL. That is not allowed.
It was never allowed, Kimai 1.x was just kind to you. Fixed your webserver setup.

**Comment by RetroLoom** [comment]
I had changed that as well, and followed the install instructions. But either way, installing with softaculous seemed to work fine. It is still showing the domain with /public in the URL with the working one, so I am not exactly sure what you mean. But I will still have to figure out why my upgrade from 1.30.9 doesn't work as well so I will see what happens there.

**Comment by kevinpapst** [comment]
I am only the developer of this app. If you think you know it better: great. Enjoy 👍
