### ISSUE TITLE
Split registrations that spans across days

### ISSUE THREAD

**Issue by skxtig** [kimai/kimai#4239]
### Describe the problem

Hi, just want to say thanks for the fantastic product.

We have some shifts that span over midnight. Lets say they start at 21:00 day 1, and ends at 03:00 day 2. The duration will then be 6 hours for day 1.
This is easy to fix by manually enter 21:00-23:59, 00:00-03:00, but can be a hassle. We also use deduction time for breaks and stuff like that, so if there was a way to split records at midnight this would be extremely helpful for counting the duration and easier to have an overview of overtime.

Is there a way to implement this?

### Describe the solution you'd like

Automatic split of work hour registrations that span across midnight.

**Comment by kevinpapst** [comment]
> Is there a way to implement this?

Yes: via custom development/plugin. But why?

**Comment by skxtig** [comment]
Thanks for answering. The main reason is because of deduct activities. Say there are some long breaks after midnight that is deducted. Then day 1 will say 6 hours of duration, but day 2 will have a negative of 2 hours.

I have made some custom scripts that report via email, for keeping track of overtime etc. With the 6 hours duration for one day and a negative for the second day the reporting will not have any good functionality except for tweaking a lot with the script.

Does a plugin like this exist today or does it need to be developed?

**Comment by kevinpapst** [comment]
Thanks for the explanation! 👍 

Law says: hours count for the day the work started.
Also it levels out over time: day 1 + hours, day 2 - minus, day 3 + hours ... and so on

There will be a plugin that handles expected and actual times, calculations and such. 
It will not split times on midnight though.

You might have a valid use-case, but I don't think it is generally applicable.
There is no plugin existing, but you can always contact me for custom development.

That feature won't make it into core, closing.
