### ISSUE TITLE
Create a release archive with all deps bundled

### ISSUE THREAD

**Issue by megheaiulian** [kimai/kimai#4250]
### Describe the problem

When deploying kimai running composer is needed. 

### Describe the solution you'd like

When creating a release add an archive that has all necessary deps already installed.
This way running composer is not needed.

**Comment by megheaiulian** [comment]
This could be automated with a GitHub Actions workflow...

**Comment by kevinpapst** [comment]
Thanks for the idea. It takes the fun out of the installation & update process. 
Also composer serves as a gatekeeper to make sure that Kimai is only running on servers, that really support it. 
Please don't feel discouraged to post more ideas, only becuase I reject this one.
