### ISSUE TITLE
Time budget not consumed by working hours

### ISSUE THREAD

**Issue by bonobo-d** [kimai/kimai#4257]
### Describe the issue

I have set a time budget for a project, but when I log hours in the same project the progress bar for the time budget doesn't move. The interface also says that 0.00% of the budget is used, whereas it should be more than 50%.

My expectation is that, since I logged 8:34 in the project, the budget should be consumed by the same duration.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.27

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

Unknown

### Screenshots

![image](https://github.com/kimai/kimai/assets/66203865/c17b2221-0588-4441-acc9-47c4fc12da25)

**Comment by kevinpapst** [comment]
I am afraid that your expectation is wrong here:

Time budget (same as financial budget) is only used by billable hours.

Why are you not using billable timesheets?
What about using billable timesheet with a 0 hourly rate? 
That would work for such internal tasks: the do not cause money billing, but just reduce your time budget.

**Comment by bonobo-d** [comment]
Thank you, I got it working with your suggestion. As I don't need the billing functionality (I'm only tracking my time for personal management) I had not read the documentation related to billing. I only looked for the documentation about time budgets, which doesn't mention that requirement.
