### ISSUE TITLE
If 5 favorites are defined for in last activities, no further entries are added to the list

### ISSUE THREAD

**Issue by JanBIE** [kimai/kimai#4259]
### Describe the issue

Basically, the function works that more than 5 entries are visible in the list of recent activities.

However, if 5 entries are static (i.e. defined as favorites), no further entries are added/displayed.

Probably the list, which is usually limited to 5 entries, was statically adjusted to 5 entries when matching with favorites?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.29

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![screenshot_2](https://github.com/kimai/kimai/assets/143094237/58a19a1c-1e72-46b8-9aa4-e85dcaf2705b)
![screenshot_1](https://github.com/kimai/kimai/assets/143094237/593de173-347a-4e96-ae33-da1c28658395)

**Comment by kevinpapst** [comment]
Thanks for your report! I can confirm that this should not happen.
