### ISSUE TITLE
Redo button missing?

### ISSUE THREAD

**Issue by ZarkoM67** [kimai/kimai#426]
In documentation I find the following recipe for starting new record: "Click the redo button from one of the activities in your timesheet", but I don't find any redo button -- only buttons "Edit" and  "Delete" (and Stop when record is active). Or I missed something?

**Comment by kevinpapst** [comment]
Yes, that's a bug which will be fixed with the next release 0.6 soon, see #412

**Comment by kevinpapst** [comment]
Now in master and later today in the release 0.6
