### ISSUE TITLE
Weekly hours does not work when a locked day is in the week range

### ISSUE THREAD

**Issue by SaturnusDJ** [kimai/kimai#4264]
### Describe the issue

Lockdown settings:
![image](https://github.com/kimai/kimai/assets/14320018/d64f088d-3bbb-4b35-a7e1-9a01c4b941ed)

Now when opening Weekly hours and going back to the beginning of August, adding some hours for August, then saving, this is the result:
![image](https://github.com/kimai/kimai/assets/14320018/419996b9-5cf3-485c-93a5-23c3ec3d5d81)

In other words, it seems like Weekly hours is blocked when there is a day in the week that belongs to a locked down period.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.31

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
I don't think this should be changed. 

What do you suggest?

**Comment by SaturnusDJ** [comment]
The expectation here in the company is that changes for the non-greyed out fields will be accepted (if valid). This makes sense to me too. However, we don't expect to run into this often, thus this bug could be a low priority one or something to leave if you feel like it.

**Comment by kevinpapst** [comment]
Let's leave it open and see how often this is an issue for others.

Not that I donÄt want to fix such things, it is rather tricky to work around that problem in that specific case.

**Comment by kevinpapst** [comment]
Nobody else complained, closing as wont fix, as this is way too complicated to tackle.
