### ISSUE TITLE
Daily Working Hours and overtime Account

### ISSUE THREAD

**Issue by PentaPaetzold** [kimai/kimai#4266]
### Describe the problem

In our Company, we do have fixed daily working Hours, e.g.
Mo-Th 8 hours
Fr-So Free

Working more or less would go into overtime account. Pauses are not booked (no working time).

Holidays of course should not be counted (maybe booked as internal Project "Holiday").

The Hours in that Account can be used to have free Days.

There may be Limits - in both ways positive and negative, and someone should be notified when those are exeeded.

Overtime Hours can be paid out - so there should be ways too book an amount of time which will reduce the hours in the account.

### Describe the solution you'd like

Have the possibility to Customize working hours per Weekday seperatly.

If Projects are overlapping, don't add the time of both, but only once.

Have a Timesheet to view the Account for the user itself and for the team leader and chef (+/- for every day and sum all together).

### Describe alternatives you've considered

I have not considered alternatives so far...

**Comment by kevinpapst** [comment]
Check this plugin: https://www.kimai.org/store/controlling.html

It has most of your requests, others (like notifications) are on the roadmap.

I am currently working on a demo video. 
Until then you can test the demo.
