### ISSUE TITLE
Timer stops automatically after 1 second.

### ISSUE THREAD

**Issue by moriartynz** [kimai/kimai#427]
Hello,

On one particular machine running Win8.1 Chrome, Firefox (does not matter which browser), when the green start button is clicked (top right in Kimai), it turns red and counts for a couple of seconds and then: stops (turns green again). No time entry appears in the list. Nothing of interest shows up in the debug after clicking start:
[26.11.2014 13:42:35] Global role 1 gave true for ki_timesheets-showRates. 
[26.11.2014 13:42:35] KSPI axAction (MCW): reload_timeSheet 
[26.11.2014 13:42:35] KSPI axAction (MCW): reload_timeSheet 
[26.11.2014 13:42:35] KSPI axAction (MCW): reload_timespan 
[26.11.2014 13:42:35] KSPI axAction (MCW): startRecord 
[26.11.2014 13:42:34] KSPI axAction (MCW): setTimeframe 

Version information:\    [version] => 0.9.3
    [revision] => 1384
    [status] => Release Candidate

This occurs consistently on only 1 PC - it is the newest machine we have. Doing the same thing on another PC does not reproduce this issue. On the PC affected, it consistently does this no matter what Kimai account is used and it also does this irrespective of what browser is used (Chrome, Firefox, Internet Explorer).

Things I have tried: Uninstalling browser (firefox and chrome), removing all appdata under %appdata% and reinstalling the browser does nothing, disabling anti-virus does nothing, uninstalling silverlight, java and flash player does nothing.
Workaround: Avoid using the large green button and clone an existing time entry instead (small green button next to any time entry), then edit to select appropriate project and activity. This is painful as the lists are long and there is no shortcut to search for a project or activity.

Any ideas?

**Comment by moriartynz** [comment]
As Murphy would have it, it stopped misbehaving shortly after this post. We did, however, discover that the time-zone settings on the machine were wrong and that the right hand date in the range at the top of Kimai was indicating the day earlier as the current date range. 

I think that it may have had something to do with the filtering of the dates of time entries as a result of a clock skew and regional setting discrepancies that caused the maximum date in the range to be a day earlier than the actual clock date and the time entry was therefore hidden from view as a result.

**Comment by ServiusHack** [comment]
Thanks for letting us know that you've resolved the issue. Your guess is probably right. It did happen that the buzzer becomes green if no recording is in the currently selected timespan. This is now fixed since ebf54fa21ff7bfdd626b8771e0ba24022837588a. So, for a short moment, the buzzer was red right after you clicked it. Then the list of entries was reloaded and the buzzer became green again.

This means you probably have some unfinished (still recording) entries in your database.
