### ISSUE TITLE
Not able to read the custom fields in User List API (/api/users)

### ISSUE THREAD

**Issue by vikasgunjeti** [kimai/kimai#4277]
### Describe the issue

Hi Team,

I am using the kimai REST API for displaying the users list. However response containing only the below fields

{
        "id": 143,
        "alias": "Vikas Gunjeti",
        "username": "vikas gunjeti",
        "accountNumber": null,
        "enabled": true,
        "color": null
}

I am using this api **/public/api/users**, How can I get the custom fields information also in API response.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.19.4

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
<img width="880" alt="Bildschirmfoto 2023-09-07 um 23 21 02" src="https://github.com/kimai/kimai/assets/533162/52004e20-e747-474e-9ea7-ab0dbe6a1b7e">

**Comment by vikasgunjeti** [comment]
Thanks for closing without resolving.

**Comment by kevinpapst** [comment]
You asked

> How can I get the custom fields information also in API response.

And I gave you the answer => so it was resolved. 

And btw: thanks for not reporting back on #4204
Where I already told you that 

> Support for a Kimai version which is so old cannot be given anyway.
