### ISSUE TITLE
Non-excisting page opened, 404 given and page stuck when not applying filter but using page buttons immediately

### ISSUE THREAD

**Issue by SaturnusDJ** [kimai/kimai#4279]
### Describe the issue

Came across this bug for the `All items` page. It probably applies to all pages with filter and page buttons.

1. Make sure there are more entries than the current page size. So that page buttons appear at the bottom.
2. Using the filter, select a project that has less entries than the current page size.
3. Do *not* press the search button in the filter window.
4. Scroll down and select e.g. page 2.
5. You will get a 404 page, and no way to reset. The only way to get back to normal is log out and log in.

The explanation for this is that apparently when clicking the page button in the bottom, the filter will still get applied, while at the same time page 2 is opened, which actually does not exist.

Searched for 'page', 'filter' and '404' in issues and discussions. No match found.
Linking https://github.com/kimai/kimai/issues/4207, https://github.com/kimai/kimai/issues/4206 and https://github.com/kimai/kimai/discussions/4208 for hits on "404".

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.31

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
I saw something similar before ... but no-one ever reported it, so 🤷 

Seems now I have to tackle it 😁

**Comment by SaturnusDJ** [comment]
😇 
Thank you for the patch!!

**Comment by kevinpapst** [comment]
Thanks for reporting 👍
