### ISSUE TITLE
sAMAccountName with dot - AD authentication successful (ID=4624) but Kimai says "Incorrect credentials".

### ISSUE THREAD

**Issue by HansBorelius** [kimai/kimai#4280]
### Describe the issue

Setting up ldap to use on Active Directory is very error prone as the syntax is not reliable.
After finding a working local.yaml that worked with plain sAMAccountNames, I ran into the problem with sAMAccountNames with a dot (jim.knopf) that the authentication to the domain controller was successful (Security Protocol ID:4624), but Kimai could not process it. Instead of a successful login, "Incorrect credentials" appeared. I suspected processing problems in Kimai and manually created the username with dot in it. Now the user could log in with the passport assigned in Kimai, as well as the password from the Active Directory account.
Browsers used: Edge, Firefox

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.7

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Logfile

no info in this situation

**Comment by kevinpapst** [comment]
Please test with 2.x and report back. Version 1 is not maintained anymore.

**Comment by HansBorelius** [comment]
After Update to v2.0.32 same error (Auth on Active Directory OK ID=4624 but Kimai say: "Incorrect credentials").
But it is now more secure: The hack to create an internal user with the same name (with a dot) and then to log in as the same Active Directory user does not work anymore ;-) 
But I'm not the only one where the names are given as firstname.lastname!?

**Comment by kevinpapst** [comment]
Oh snap... nah, actually that is a good sign. 

Not first.last@example.com is a very common pattern. I checked the code and I do not see any place that handles dots in a username and I don't understand why that should be an issue at all. 
Unfortunately I have no clue to verify that error as well, as I do not have AD access.

**Comment by HansBorelius** [comment]
STOP! - I definitely should have done it earlier: I created a new user "kimai.testlogin" under the cn=Users,dc=domain,dc=tld and .. the login works! So it is not the dot in the user name. That was not a thorough job, sorry! 
I have to search further now: The new user has empty attributes, e.g. no email address, maybe it is because of an attribute.

**Comment by kevinpapst** [comment]
No feedback usually means: solved.

I assume you just forgot but anyways: 
I my software and time is good enough for consumption, I expect a at least a short feedback 👎
