### ISSUE TITLE
Option to edit time tracking entries in invoice section

### ISSUE THREAD

**Issue by dirkhoefling** [kimai/kimai#4285]
### Describe the problem

Currently in the invoice section it is not possible to edit the shown time tracking entries.

This makes it difficult to adjust wrong time tracking entries which are listed in the invoice section

### Describe the solution you'd like

It would be great to have a context menu for the time tracking entries in the invoicing section. (with the option to edit the shown entry)

### Screenshots

![image](https://github.com/kimai/kimai/assets/152764/59bdc246-99ad-4557-862b-2662a9a305b0)

**Comment by kevinpapst** [comment]
That would only work when you do not group invoice entries, e.g. by project. 
Features that appear and disappear are terrible to explain, therefor I will not add such a feature
