### ISSUE TITLE
Reporting show wrong values

### ISSUE THREAD

**Issue by xstable** [kimai/kimai#4288]
### Describe the issue

1. Create a user `Test` which is Teamleader of Group "TyrePortal". 
2. Add users to this project, which participate also in other Projects.
3. create some timeentries for those useres
4. Login as User `Test` and go to `Reporting -> Yearly view for all customers` 

# Issue
You'll see an overview of all estimates and all users. In the header you see a Date-range selector and a "Project" Selector
(Note the amount of hours: 331:17 ): 

![image](https://github.com/kimai/kimai/assets/1778068/d0a68b9d-3ac9-4d8e-ae67-35f8bfb226dc)

Then select the one and only Project, `Test` is assigned to (role: teamleader.. but he also don't participate in other roles or Projects!). 
You see the same amount of hours as in the initial-screen: 

![image](https://github.com/kimai/kimai/assets/1778068/3f1a9e41-5793-4d31-8d13-f651bd5049a6)

After this click on the hours of the user, and you are redirected to `Yearly view for one user`.
On this Page you'll see, that the user is in other projects too, and that the total amout of was wrong... as it was the total amout of **all** projects the user are participating in.

![image](https://github.com/kimai/kimai/assets/1778068/768eb6a2-7e94-4e9b-ab2c-07af4a76533b)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.33

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Logfile

Empty logfile

**Comment by kevinpapst** [comment]
This is a "Team select" dropdown, not a project selector.

**Comment by xstable** [comment]
Ah, I see. As I had same name for Project and Team, I've mistaken it. 
Thx for the clarification.
