### ISSUE TITLE
Prevent user from editing own time

### ISSUE THREAD

**Issue by msawyer91** [kimai/kimai#429]
A friend of mine owns a small business and wants a time tracking solution that includes a time clock so users can clock in and out. She doesn't just want time sheets, but rather a time clock. Kimai seems to offer both.

I set up Kimai v0.9.3.1384 RC and we set up some test user IDs so we could try it out. We could clock users in and out to simulate a regular workday.

The issue I see, unfortunately, is that the user can go back and edit their time after the fact! I made sure these users were not in any admin groups or roles, but instead were just regular users. Even so, let's consider this test case:

User A is supposed to report to work at 8:00am. User A shows up 45 minutes late and clocks in at 8:45. He is supposed to work until 4:30pm, but sneaks out 15 minutes early--and clocks out at 4:15pm. He then clicks the green edit button and can tweak both the clock in and clock out times, making it look like he worked a full workday, when in fact he "cheated" by adding an hour to his timesheet that he did not actually work. This seems to defeat the purpose of a time clock.

One of the reasons my friend wants a time clock solution is because she believes some employees may be "stealing time" (coming in late and/or leaving early, yet claiming a full day's pay).

Is there a setting or security permission that I am overlooking?

Matt

**Comment by kevinpapst** [comment]
Glad you found a solution to your problem! I will close this old issue.
