### ISSUE TITLE
user started time measurement cannot be stopped

### ISSUE THREAD

**Issue by HolsteinHamburg** [kimai/kimai#4290]
### Describe the issue

A user started the time measurement top right corner and forgot to end it. Now it's going on for 340 hours and cannot be stopped, because "stop" is only available within 10:45 hours. 
![Kimai01](https://github.com/kimai/kimai/assets/144805769/651fb174-3122-4a7f-a89f-e1476a13d61b)
![Kimai02](https://github.com/kimai/kimai/assets/144805769/5307fd4b-1c86-4ec7-9a0b-b60f6675f657)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.032

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
As paying customer, you can use the support function in the future:
https://www.kimai.cloud/de/support-center/request

Here is the answer:
https://www.kimai.org/documentation/timesheet.html#stop-records

**Comment by HolsteinHamburg** [comment]
Dear Kevin,
Thank you very much!
We are not paying (too small), but I will donate 😊
BR Claass


Von: Kevin Papst ***@***.***>
Antworten an: kimai/kimai ***@***.***>
Datum: Dienstag, 12. September 2023 um 15:07
An: kimai/kimai ***@***.***>
Cc: "C. Barth" ***@***.***>, Author ***@***.***>
Betreff: Re: [kimai/kimai] user started time measurement cannot be stopped (Issue #4290)


As paying customer, you can use the support function in the future:
https://www.kimai.cloud/de/support-center/request

Here is the answer:
https://www.kimai.org/documentation/timesheet.html#stop-records
