### ISSUE TITLE
Date-Range-Template

### ISSUE THREAD

**Issue by lippoliv** [kimai/kimai#43]
Hey there,
I have an "endless-project". That is an project that never ends, titled "administrative tasks". One of my Customers and I have raised this project because he had some projects and then, between this projects, some things like "create an e-mail-adress for xyz" or "setup an NAS in our office".

So we open up this project for just write one Invoice per month, over all tasks for this project.

So what does this have to do with kimai? On the first or second of a new month, I have to open up Kimai, set the date-filter to first day of last month and last day of last month, klick an Filter for Project and export this view as PDF to generate an Invoice.

It would be nice if i dont just could pick a date-range, i would like to have some pre-defined views like

```
"this week"
"last week"
"this month"
"last month"
"this year"
"last year"
```

That would speed up my work Smiley

You could visualize it, like piwik do. Highlight not just one Day, highlight the Week, the Month or the year (that has to be a new datepicker, showing years instead of showing days)

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
