### ISSUE TITLE
The database specified in .env or .env.local is ignored by postgresql.

### ISSUE THREAD

**Issue by CampusCityNord** [kimai/kimai#4301]
### Describe the issue

I tried to connect Kimai to my PG database but the database specified in the DATABASE_URL is simply ignored. I adjusted the URL in the .env and .env.local but when I try to install Kimai I get in the error message an access attempt to the database "postgres" and not "kimai".

```
DATABASE_URL="postgresql://kimai:<MyPassword>@<MyDbHost>:5432/kimai?serverVersion=14&charset=utf8"
```

```
bin/console kimai:install -n
```
ends in 
```
 [ERROR] Failed to create database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at
         "<MyDbHost>" (<IP>), port 5432 failed: FATAL:  no pg_hba.conf entry for host
         "<IP>", user "kimai", database "postgres", SSL encryption
         connection to server at "<MyDbHost>" (<IP>), port 5432 failed: FATAL:  no pg_hba.conf
         entry for host "<IP>", user "kimai", database "postgres", no encryption
```

I have also tried to adjust the config/packages/doctrine.yaml by entering the correct driver there.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.33

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
postgres is not supported
