### ISSUE TITLE
On export times are marked as "exported" even if not selected

### ISSUE THREAD

**Issue by empx92** [kimai/kimai#4304]
### Describe the issue

As there is no possibility to set "export" to "no" we use the recommended javascript out of the documentation:

```
document.addEventListener('kimai.initialized', function(event) {
    const cb = document.querySelector('#preview_export #markAsExportedCheck');
    if (cb !== null && cb.checked) { cb.checked = false; }
});
```
Optically it is "unchecked", but on export the entries are all "exported". With about 20 employees and the need of weekly print from the times this is absolutely not good for us. Some Project are running over one year with advanced payments so the mark es "export" would be a year later with the final settlement.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.34

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
The code needs adjustment. I updated the examples in the docs. Use this:
```javascript
document.addEventListener('kimai.initialized', function(event) {
    const ec = document.getElementById('markAsExportedCheck');
    if (ec !== null && ec.checked) { ec.checked = false; document.getElementById('markAsExported').value = 0; }
});
```

**Comment by empx92** [comment]
After editing the Code everything works as expected. Thank you
