### ISSUE TITLE
"Revenue this year" in Dasboard shows Billable "No"

### ISSUE THREAD

**Issue by cybacoffee** [kimai/kimai#4308]
### Describe the issue

After Upgrading from 1.30.5 to 2.0.34, the Dashboard shows the " Revenue this year " with Billable items which are also selected as "No". In the old version v1.30.5 this behaviour was only to show revenvue which is billable.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.34

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
Yes, seems to be true. Thanks for posting @cybacoffee 👍 

These widgets were made before the `billable` flag and then forgotten ...

What do you expect for non-billable items? Simply ignore them / leave them out of the calculation?

**Comment by cybacoffee** [comment]
Hi @kevinpapst, thanks for checking! 😃 
I think the same behavior as in v1.30.5 would be fine? 
As of my understanding, non-billable items shouldn’t be calculated in revenue, because it was set on purpose, right?
Compared to the "internal" items, they are also not counted.

Thanks Kevin! 😃
