### ISSUE TITLE
Error 500 after new Project, User

### ISSUE THREAD

**Issue by darkol** [kimai/kimai#4309]
### Describe the issue

I have installed Kimai 2.0.34 using Softaculous on sPanel based hosting on a dedicated Domain (subdomain actually, subdir install not allowed).
English language selected.
No Plugins etc.

The PHP is 8.2.9
All checkmarks under System->Doctor for File Permissions and PHP extensions.

After loging in with Admin user I have firstly created 1 Customer.

Then I have created 1 Project "Prisotnost" and upon adding the Project the 500 error page showed.
I see the project under Projects, but any action including '...' -> Delete resolves in 500 error page

Then I have created 1 another User - all well.
Then I have tried to add 2nd User and upon clicking "Save" error 500 again.
The 2nd (3rd including Admin) user is shown in Users list but as with Project any action resolves in 500 error page.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.34

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.2

### Logfile

[2023-09-20T23:22:14.147858+02:00] request.CRITICAL: Uncaught PHP Exception Error: "Failed opening required '.../var/cache/prod/doctrine/orm/Proxies/__CG__AppEntityUser.php' (include_path='.:/opt/alt/php82/usr/share/pear:/opt/alt/php82/usr/share/php:/usr/share/pear:/usr/share/php')" at .../vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php line 197 {"exception":"[object] (Error(code: 0): Failed opening required '.../var/cache/prod/doctrine/orm/Proxies/__CG__AppEntityUser.php' (include_path='.:/opt/alt/php82/usr/share/pear:/opt/alt/php82/usr/share/php:/usr/share/pear:/usr/share/php') at .../vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php:197)"} []

**Comment by kevinpapst** [comment]
Fix your file permissions. This is not a Kimai bug, but an environment issue

**Comment by darkol** [comment]
Hi Kevin.

Firstly thank you on your quick reply :)

I understand your point, I guess this might be some environment sPanel - Softaculous instalation issue.
As a user I do not see the ownership of the files, but it seems for www user the 755 and 644 permissions are set for whole att.cognitas.si folder.

Doctor page in System shows that **var/cache/, var/log/ and var/data have no warnings** e.g. no write privileges error.
Anyways I have set 777 permissions for var/cache/prod/doctrine/orm/Proxies but the error persist and Proxies folder is empty.

And why I could create the 1st user (after initial Admin) and I can view its form whereas I can not view for 2nd user?
I have tried to add 3rd user and again 500 error on "Save" with usr/edit url, also user form gives error 500.

**Comment by kevinpapst** [comment]
Why do I have to spend time on a "Why" if the reason is clear: the cache is empty.
You need to fix that.
You can try to (as documented):
- delete the log file
- rm -rf var/cache/* 
- then make sure permissions are 777 
- open the web again

Still not working? Post your log.

**Comment by darkol** [comment]
Dear Kevin,

I am grateful for your time and replies and as a user I would like to say thank you on your implicit answer that helped.

But I can see plenty of those in other posts and completely agree with you as stated  (#3640):
> Permission problems were discussed one gazillion times here and in the discussion.

but **that did no help me** realize **what exactly can I do in a limited cPanel based hosting environment**, as in our cPanel based hosting users have no shell access and the available software is limited by what Softaculous provides to install, 
and will write here maybe to help somebody else, someday:

> In short, after observing the 500 error, open the cPanel File Manager and delete all in **var/cache/** folder inside installation folder of Kimai app and check that Folder Permissions are "755".
> Reopen the Kimai app in a browser and 500 error should be gone.

I hope this is it.

**Comment by kevinpapst** [comment]
I know this is your first time, but to me this is the probably posting number 400 with the same issue.
It gets harder and harder to stay calm, which is nothing personal obviously! Just my personal weakness...

I hope the error is finally gone and stays away.
Thanks for your kind words 👍 and for your explanation for the next person.

**Comment by darkol** [comment]
I completely agree with you, again my compliment and thanks for your quick replies, no offense taken, hopefully it's mutual ;)

And as a senior fellow developer, although on other fields of knowledge, I would like to contribute more on "Why" for Community of this great project and potentially for developer or Softaculous integrators
as in this case, the reason is not clear, at least not to me, the cache is not empty.

I have replicated the problem on a new installation.

>Congratulations, the software was installed successfully
>
>Kimai has been successfully installed at :
>https://test.cognitas.si
>Administrative URL : https://test.cognitas.si/public/en_US/login
>
>We hope the installation process was easy.
>
>NOTE: Softaculous is just an automatic software installer and does not provide any >support for the individual software packages. Please visit the software vendor's web site >for support!
>
>Regards,
>Softaculous Auto Installer 

After not opening the Kimai application at installed URL, I have checked the **var/cache/** folder that is already populated?!?

```
- var
  - cache
    .gitkeep
    - prod
      - Container939v2o2
      - doctrine
        - orm
          - Proxies
	  - jms_serializer_default
      - pools
        + app
        + system
      - translations
      - twig
```

Then opened Kimai application, signed in and passed Wizard steps to start the app.

Firstly created the Customer – only added “Test” in mandatory Name field and pressed “Save”

Afterwards, created a new Project by only adding “Test” in mandatory Name field and selected “Test” customer in mandatory Customer field, pressed “Save” and ... got Internal Server Error **500**.

Then I deleted **prod** subfolder under the **var/cache** folder, restarted the app in the browser going to "Home" e.g. https://test.cognitas.si
and **Kimai is working**.

I can conclude that this issue is due to unclean var/cache that must be a bug of the Softaculous installation.

I will report bug there as their *NOTE* was exhausted :)

**Comment by darkol** [comment]
A support ticket request #125337 has been created at Softaculous.

Best regards Kevin and keep up the good work.

**Comment by kevinpapst** [comment]
Thanks for the updates!
During installation the cache is pre-warmed.
But that does not wok for all caches, especially database/content related ones.
So cache will be written during runtime as well.

During installation the cache is written by sudo(?) or some other privileged account.
During runtime, the cache is written as PHP-FPM or Webserver user with less privileges.

That means during installation the correct permissions need to be given recursively. 
When you delete the entire prod/ folder, all cache files will be written by the webserver on the first page hit (that's why it is working after deletion).

So all boils down to invalid permissions after installation.
That's why there is an extra chapter in the docs about it:
https://www.kimai.org/documentation/installation.html#file-permissions

I guess Softaculous needs to address that in their installer

**Comment by nikitakothari06** [comment]
> A support ticket request #125337 has been created at Softaculous.
> 
> Best regards Kevin and keep up the good work.

Hi,

Apologies for the inconvenience caused to you.

We have replied to the ticket.
