### ISSUE TITLE
Concurrent timers

### ISSUE THREAD

**Issue by BrianGilbert** [kimai/kimai#431]
Is it possible to have multiple timers running concurrently?

**Comment by TheWanderingCoder** [comment]
+1

**Comment by simonschaufi** [comment]
usecase?

**Comment by kevinpapst** [comment]
Here you have a usecase: #288

**Comment by m3rlinux** [comment]
+1

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
