### ISSUE TITLE
Deduction-Time Bundle upgrade with non-deductable Margin time

### ISSUE THREAD

**Issue by darkol** [kimai/kimai#4322]
### Describe the problem

If the Kimai is used for Working time logging e.g. Time Attendance Registration application with punch-in - punch-out Activity the Deduction-Time Bundle comes handy to register Lunch breaks, Private breaks etc.

But regulations in some countries require that part of Lunch break is included in working hours.
It would be great if only excess time of that kind of Activity is deducted from working hours.

### Describe the solution you'd like

I think usable addition to the Deduction-Time Bundle would be to add "Deduction time margin" to allow the Activity time to be excluded from deduction up to this margin.

### Describe alternatives you've considered

I have done a simple example implementation by extending the Deduction-Time Bundle adhoc and is usable for our case. Since Deduction-Time Bundle is a simple plugin, I would not consider complicating it much further.
[DeductionTimeBundle.zip](https://github.com/kimai/kimai/files/12709518/DeductionTimeBundle.zip)

### Screenshots

![Zaslon_25](https://github.com/kimai/kimai/assets/19587376/c393e257-1ee4-4b63-aa77-bdc2c99fbf3a)
![Zaslon_21](https://github.com/kimai/kimai/assets/19587376/f82aa3f5-40bc-4987-909d-290d6e93795d)
![Zaslon_22](https://github.com/kimai/kimai/assets/19587376/90db3b8e-b3d8-4d5e-944b-562470f530a2)
![Zaslon_23](https://github.com/kimai/kimai/assets/19587376/fa1cb95a-5250-48fc-8e84-dfb9f419f9cf)
![Zaslon_24](https://github.com/kimai/kimai/assets/19587376/c396537f-2367-4ff7-b0d7-acb2290b004c)

**Comment by kevinpapst** [comment]
Thanks for sharing 👍 

But please fork the repo https://github.com/Keleo/DeductionTimeBundle and add your changes. We can link it from the Store page as additional choice.

I have no plans to add any more features to this plugin. Is it "feature complete" for me.

You are talking about breaks and that will be incorporated in a larger scope into the "Working times" plugin:
https://www.kimai.org/store/controlling.html

**Comment by darkol** [comment]
Will fork and add, just one quick question, how do you generate translation trans-item id codes?
Can you generate 2 proper id code for the forked bundle?

I have just updated last character in translation files for adHoc solution:

>       <trans-unit id="zc6XdUj" resname="deduction.label">
>       added <trans-unit id="zc6XdUk" resname="deduction_margin.label">
>       <trans-unit id="8uh0_wt" resname="deduction.help">
>       added <trans-unit id="8uh0_wz" resname="deduction_margin.help">

**Comment by kevinpapst** [comment]
If you have your bundle installed in var/plugins/ then you can run:
```

bin/console kimai:translation --resname
```
