### ISSUE TITLE
Total time amount missing in mobile view

### ISSUE THREAD

**Issue by xstable** [kimai/kimai#4323]
### Describe the issue

In Zeiterfassung > Alle Zeiten there is a `total amount` badge at the top of the page. 

But on mobile-devices, there are none. Even if you use "show as Desktopwebsite" at your smartphone, it doesn't appear.
![image](https://github.com/kimai/kimai/assets/1778068/f2aa2646-bd89-49de-ad9d-fb632368be7b)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.34

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
Stats will never be shown on mobile. 
Not enough space. 
Other languages have longer titles. 
Doesn't fit.
Mobile is not meant to duplicate the entire feature set of the desktop website.

**Comment by xstable** [comment]
@kevinpapst ok, but would be nice to have any kind of alternative on mobile. Maybe an Menu-Entry or icon. 
Because as it's currently is, you are not able to use such an important feature via mobile. 

That's a huge downside if project-owner is on the road and have to find any workstation or pc to get an overview of  it's team estimates (e.g. if he is at the customer company and the customer ask.. how far we are with estimates)

**Comment by kevinpapst** [comment]
I question this use-case.
But anyway: you can still use one of the report screens.
Or use the export screen, where you see such numbers.

You can easily make this feature happen via Custom JS / CSS. 
But I am not going to add it to core.

If you have ideas for better reports on mobile: let me know!
