### ISSUE TITLE
Project and activity can't be cleared using keyboard anymore.

### ISSUE THREAD

**Issue by RikHDigi** [kimai/kimai#4334]
### Describe the issue

Since the new release it's no longer possible to clear & change "Project" and "Activity" fields once you've selected something. This makes it impossible to change these using keyboard.

You can still pick another value from the dropdownmenu with your mouse, but keyboards users have this usability issue.
![image](https://github.com/kimai/kimai/assets/50359123/468422f9-cfcf-445e-af84-67d0ba8764c4)

If in the project field i CTRL-A and start typing, do i get a new search action for the new text (green), but the old value is still visible in the input field (organge)
![image](https://github.com/kimai/kimai/assets/50359123/e5f010ff-4b1e-4102-843f-9a4892be0f45)

This is confusing behavior, that worked better in the previous version. 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

Since the new release it's no longer possible to clear & change "Project" and "Activity" fields once you've selected something. This makes it impossible to change these using keyboard.

You can still pick another value from the dropdownmenu, but keyboards users have this usability issue.
![image](https://github.com/kimai/kimai/assets/50359123/468422f9-cfcf-445e-af84-67d0ba8764c4)

If in the project field i CTRL-A and start typing, do i get a new search action for the new text (green), but the old value is still visible in the input field (organge)
![image](https://github.com/kimai/kimai/assets/50359123/e5f010ff-4b1e-4102-843f-9a4892be0f45)

This is confusing behaviour, that worked better in the previous version.

**Comment by kevinpapst** [comment]
Yes you can, just click arrow down and the menu opens again.

**Comment by kevinpapst** [comment]
I'll re-open if you can let me know what exactly does not work

**Comment by RikHDigi** [comment]
Ik ga er geen tijd in steken.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
