### ISSUE TITLE
Export report data (monthly view per user)

### ISSUE THREAD

**Issue by thmo** [kimai/kimai#4348]
### Describe the problem

In earlier versions, it was possible to export `/reporting/user/month` as excel sheet, csv, or similar. This is not possible with the current version.

(See also #4342)

### Describe the solution you'd like

We'd like to have a button in said view to download the data.

**Comment by kevinpapst** [comment]
> In earlier versions, it was possible to export /reporting/user/month as excel sheet, csv, or similar. 

Can't remember that one, when was that?

**Comment by thmo** [comment]
Wasn't that what was implemented in #3154 ?

**Comment by kevinpapst** [comment]
![image](https://github.com/kimai/kimai/assets/533162/cb91822b-c395-4879-b2be-9d9afa85b4ab)

**Comment by thmo** [comment]
That works, now the feature request here to have a similar functionality in this view:
![image](https://github.com/kimai/kimai/assets/422646/34acd00a-3070-4af8-9c54-d37a2f221bb8)

(or, ideally, in _all_ reports)
