### ISSUE TITLE
Die Anzeige von Meine Zeiten läuft bei schmalem Bildschirm aus dem Ruder

### ISSUE THREAD

**Issue by JoergGiencke** [kimai/kimai#4358]
### Describe the issue

Die Anzeige der Tabelle in Meine Zeiten läuft bei schmalem Bildschirm (Smartphone) nach rechts aus dem Ruder (siehe Screenshot).

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.x

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Screenshots

So sieht es auf dem Handy aus (Screenshot gesamter Bildschirm in Edge als App laufend):
![Screenshot_20231020-145330](https://github.com/kimai/kimai/assets/45542833/d480397a-3725-42ee-a1fe-b3951f7ff184)
Abhilfe ist einfach (overflow-x: scroll an der richtigen Stelle):
![Screenshot 2023-10-20 144752](https://github.com/kimai/kimai/assets/45542833/af635eea-644a-4fd0-90bb-f84327d94b62)

**Comment by kevinpapst** [comment]
Dafür gibt es unterschiedliche Profile. Desktop und Mobile, im Dialog wo man auch die Spalten umschalten kann.

**Comment by JoergGiencke** [comment]
Das ist mir bekannt, nur das nützt nichts. Egal, was man einstellt, die Anzeige läuft aus dem Ruder. Dabei spielt es auch keine Rolle, ob man das Ganze auf dem Handy anzeigt oder auf dem Notebook das Browserfenster schmal zieht.

**Comment by kevinpapst** [comment]
Wenn man die Einstellung löschst, wird es Responsive. Dann hat man aber keine Wahl welche Spalten man siehst.

Wenn man was konfigurierst, wird auch das exakt angezeigt. 

Was soll denn da sonst passieren, wenn auf einem Handy mit 2 Spalten Breite 10 Spalten aktiviert sind?

**Comment by JoergGiencke** [comment]
Was passieren soll bei 10 aktiven Spalten ist einfach und die Lösung hatte ich ja auch schon mitgeliefert. Siehe Screenshot 2. Wenn der Platz nicht reicht, dann muss man halt scrollen können. Mit einem schlichten overflow-x: scroll im Wrapper ist das erschlagen. Da wird die ganze Logik, die da verbaut ist (das was ich sehe, wenn man das Telefon dreht, also mal mehr mal weniger Spalten), hinfällig. 

"Responsive" bedeutet nicht, dass man die Anzahl der angezeigten Spalten künstlich begrenzt, sondern dass man die Anzeige unter Berücksichtigung der Hardwarebedingungen so anpasst, das der Anwender das zu sehen bekommt, was er möchte / eingestellt hat.

**Comment by kevinpapst** [comment]
Auch wenn das Thema interessant wäre weiter zu verfolgen.
Ton und Inhalt gehen gar nicht.
So diskutiere ich nicht weiter

**Comment by kevinpapst** [comment]
Lösung im ersten Javascript-Beispiel hier: https://www.kimai.org/documentation/plugin-custom-content.html
