### ISSUE TITLE
Error when creating invoices with custom template. (TWIG/PDF)

### ISSUE THREAD

**Issue by bryan065** [kimai/kimai#4363]
### Describe the issue

As of version 2.1.0, I'm unable to create any invoices using my custom template. I will get the error:

`Changes could not be saved: Filter "date_format" is not allowed.`

Throughout my template, I am using filters similar to `invoice['invoice.date']|date_format('M d, Y')` to get customized, readable dates. 

I'm also using something similar to `{%- set filename = 'ACME_' ~ (customer is not null ? customer.name|replace({' ': '-'}) ~ '_' : '') ~ query.begin|date_format('Y-m') -%}` to name my file. Taken directly from the Wiki.

Is there an alternative to these filters? Right now, I have just disabled the check in `/src/Twig/SecurityPolicy/ForbiddenPolicy.php`.

I'm unable to find anything

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.1.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

[2023-10-23T01:04:53.444332+00:00] app.CRITICAL: Filter "date_format" is not allowed. [] []

### Screenshots

![image](https://github.com/kimai/kimai/assets/30362590/1b232542-ff3e-4e41-9412-4a8ad350c4d3)

**Comment by kevinpapst** [comment]
Yes, there is a new policy. 
But the `ForbiddenPolicy` is not used anywhere, so I don't understand how changing it should fix anything.

Try to add it to the list of allowed methods:
https://github.com/kimai/kimai/blob/main/src/Twig/SecurityPolicy/InvoicePolicy.php#L37

**Comment by bryan065** [comment]
Sorry, you're right it wasn't `ForbiddenPolicy`, I had just removed all the checks in general and a temp workaround.

I'll add it to the list of allowed methods/filters instead. Don't know why I didn't see that part originally, thanks!.

In the future is it possible to get a config option in `local.yaml` or similar to configure this?

**Comment by kevinpapst** [comment]
In the future I shouldn't be so stupid and forget to add these filters in the first place 😁 
I somehow missed to add them to the list of allowed filter.

Disabling the check can lead to severe security issues (as I learned recently), which doesn't matter if you host for yourself and/or nobody else can upload templates.
