### ISSUE TITLE
Make time entry optional in expenses

### ISSUE THREAD

**Issue by EduNetEurope** [kimai/kimai#4367]
### Describe the problem

Our expenses have a day (date of the invoice). However, the time entry does not really apply here.

### Describe the solution you'd like

Make the time entry optional in expenses.

**Comment by kevinpapst** [comment]
Paid plugin topics go here: https://github.com/kevinpapst/kimai-plugins

**Comment by EduNetEurope** [comment]
Sorry. Wir lernen es noch!
