### ISSUE TITLE
Expenses count towards a client's or a project's money budget

### ISSUE THREAD

**Issue by EduNetEurope** [kimai/kimai#4369]
### Describe the problem

We have an overall project money budget. To calculate the remaining open budget, we need to subtract billable hourly rates and expenses.
I don't think expenses can count towards project budgets at this time?

### Describe the solution you'd like

We would like to have a simple budget overview that shows us the total money budget for a given project.
Billable hours and expenses should be deducted from the money budget to show the remaining budget.
Right now, expenses do not count towards the money budget (see screenshot).
![Budget wish](https://github.com/kimai/kimai/assets/148647197/1cdbe7d4-661e-4246-ab76-4f31adfab7dd)

Ideally, we could filter the project budget by user(s) or teams.

### Screenshots

![Kimai budget](https://github.com/kimai/kimai/assets/148647197/1abfed1d-7cc9-440c-9243-f6eaeab0e35f)

**Comment by EduNetEurope** [comment]
@kevinpapst 
We read [elsewhere](https://github.com/kimai/kimai/issues/4283#issuecomment-1711805307) that new budget types are planned. Would the new budget types cover our feature request?
We know: wait or pay. So how much would it be to get it within the next say 8 months?

I think this one also needs to be moved to kevinpapst / kimai-plugins.
Or merged in this one: https://github.com/kevinpapst/kimai-plugins/discussions/69?
Btw: setting "adds expenses to consumed budgets" is active.

**Comment by kevinpapst** [comment]
New ticket in other repository please.
But you can always have a look at System > Einstellungen:

<img width="618" alt="Bildschirmfoto 2023-10-23 um 23 32 32" src="https://github.com/kimai/kimai/assets/533162/4af2b0c1-2ab7-4712-8fcf-05c2069a9abd">

**Comment by EduNetEurope** [comment]
This setting is activated (we are still in the trial phase of Kimai Cloud).
