### ISSUE TITLE
Filter budgets by teams and/or users

### ISSUE THREAD

**Issue by EduNetEurope** [kimai/kimai#4370]
### Describe the problem

In Time Tracking / All Times, we can filter time sheets by teams.
Unfortunately, [we don't get totals for the filtered results](https://github.com/kimai/kimai/issues/4270).

In Administration / Projects, we cannot show only a team's budget, i.e. filter by teams.

### Describe the solution you'd like

Please add more filters in Administration / Clients and Projects.
Add the ability to show budgets per users or teams.

**Comment by kevinpapst** [comment]
Check the project details report.
Aside from that, users can be in multiple teams and a breakdown per team is therefor impossible.
