### ISSUE TITLE
Budgets for teams 

### ISSUE THREAD

**Issue by EduNetEurope** [kimai/kimai#4372]
### Describe the problem

We can define budgets for clients, projects and activities.
Our teams have budgets for activities, projects and clients. 

### Describe the solution you'd like

It would be amazing if we could define budgets for teams per activity, project or client.

**Comment by HeinzWuert** [comment]
It also makes sense for us, but only if the team budget is automatically adjusted to the overall budget.
Total budget 100h
Team budget 100h
some teamless user book 10h on total budget.
In this case the team budget has also to decrease, even if no team bookings have been made yet.
Total Budget free 90h
Team Budget free 90h

**Comment by kevinpapst** [comment]
Will not be added, closing
