### ISSUE TITLE
Working Contract jump marker opens wrong user

### ISSUE THREAD

**Issue by HeinzWuert** [kimai/kimai#4373]
### Describe the issue

As an admin, you can directly select another user from the Working Contract > working times main menu, if no target hours have been defined yet.
If you use the jump marker, the user menu opens, but for your own name and not for the name that is to be edited.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/45666972/ea59ac0a-a95e-4b78-8262-55b25b38b91f)

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/kimai-plugins
