### ISSUE TITLE
PHP Parse error while "composer install --optimize-autoloader -n"

### ISSUE THREAD

**Issue by Regnalf** [kimai/kimai#4379]
### Describe the issue

Step two of the self-hosted installation throw this PHP Parse errors while executing `composer install --optimize-autoloader -n`

```
PHP Parse error:  syntax error, unexpected 'HttpDownloader' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /data/web/0/html/kimai2/vendor/symfony/flex/src/Downloader.php on line 44

Parse error: syntax error, unexpected 'HttpDownloader' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /data/web/0/html/kimai2/vendor/symfony/flex/src/Downloader.php on line 44
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.1.0

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Likely outdated composer installation. Or you are not using PHP 8.1. Verify with php -v
Anyway: not a Kimai issue.

**Comment by Regnalf** [comment]
The whole thing runs on a shared host.
PHP version is 8.1.18 and composer is on 2.2.22. All necessary PHP extensions are active.

The error happens when installing the extension symfony/flex. But this can't be fixed with the composer update either. This must mean that no self-hosted Kimai installation is possible at the moment?

**Comment by kevinpapst** [comment]
> This must mean that no self-hosted Kimai installation is possible at the moment?

Yes 🤯 Don't you see the not not ending list of posts about the same problem?

Run `composer diagnose` and `composer check-platform-reqs` in the Kimai directory and show me screenshots.

**Comment by Regnalf** [comment]
### PHP Version
![screenshot_ 2023-10-26 um 09 17 34](https://github.com/kimai/kimai/assets/43412166/4841634d-71d0-4bd6-a8e2-6a1091782fbd)

### composer diagnose
![screenshot_ 2023-10-26 um 09 16 15](https://github.com/kimai/kimai/assets/43412166/0fd49b62-c209-47e0-83d9-71ca1b645a61)

### composer check-platform-reqs
![screenshot_ 2023-10-26 um 09 18 00](https://github.com/kimai/kimai/assets/43412166/71526196-ccfc-4985-afac-798d0f2f6411)

**Comment by kevinpapst** [comment]
Told you

> Or you are not using PHP 8.1.

You are running PHP 7.1 when executing composer, because your hoster is crap.

Read the installation docs, there are many examples on how to execute composer with another php binary.

Again: not a Kimai issue. Contact your hoster for support, they actually earns money.

**Comment by Regnalf** [comment]
Ok, seems that i missed that line. And you are right, seems to be that my host have to explain that crap.

But thanks for your lightspeed response.
