### ISSUE TITLE
global variables for reports/invoices

### ISSUE THREAD

**Issue by kabums** [kimai/kimai#438]
We want to change from kimai1 to kimai2 and we have some problems to trasfer our templates.
Because of project centric reports and invoices we nedd some global variables for the project.
We need project id, name, comment as global variables. in kimai1 reports we could use [var.project].
What can we do? Is there an work-around?

**Comment by kevinpapst** [comment]
Can you test the attached PR #439, which adds these variables?

**Comment by kabums** [comment]
tested and it works well
Thank you for the fast response !!!

**Comment by kevinpapst** [comment]
Now available in master!
