### ISSUE TITLE
Lack of privileges doesn't hide menu items

### ISSUE THREAD

**Issue by dasJ** [kimai/kimai#4385]
### Describe the issue

Some users in our instance aren't allowed to create invoices.
On Kimai 1.30.11, this means that the relevant menu items are hidden.

Kimai 2.0 doesn't hide these items and when clicking them redirects me to the login. I don't actually have to log in and can press the back button instead, but this behaviour feels buggy to me.
The right thing to do is probably to hide the menu items as well.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.1.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Screenshots

![image](https://github.com/kimai/kimai/assets/4971975/4e88b519-babf-4cf7-b1e1-f984b1ce8a06)

**Comment by kevinpapst** [comment]
Which exact permissions are you talking about?
A User in a setup from GitHub does NOT see the menu.

The logic will ONLY add the menus if the user has the invoice permission:
https://github.com/kimai/kimai/blob/main/src/EventSubscriber/MenuSubscriber.php#L111C50-L111C50

Your screenshot looks as if the user has all invoice permissions.

> Kimai 2.0 doesn't hide these items and when clicking them redirects me to the login

Are these users probably only remembered? Do they really see the login or the screen where they see their avatar and only need a password? That is an entire different functionality.

**Comment by dasJ** [comment]
It was two issues:
- My session was somewhat broken, I fixed that by logging in again
- When setting up Kimai 1 (which is now updated to 2), I didn't read this section on your permissions structure docs:
  > There is no reason for changing the default permission through your [local.yaml](https://www.kimai.org/documentation/local-yaml.html). It can be considered bad practice, as it can lead to problems with future updates.

Sorry for the noise. I removed the config and reconfigured everything in the web interface and it works as expected

**Comment by kevinpapst** [comment]
Thanks for the feedback 👍
