### ISSUE TITLE
Entry could not be deleted - cannot delete time entries or change team access to customers

### ISSUE THREAD

**Issue by sorcer1122** [kimai/kimai#4392]
### Describe the issue

When I try to delete time entries or adjust team's access to customers, I get the following error:

team - 
![Screenshot from 2023-11-02 12-43-12](https://github.com/kimai/kimai/assets/15838362/76a4ba7b-4789-4852-836c-ac9733b23714)
![Screenshot from 2023-11-02 12-44-05](https://github.com/kimai/kimai/assets/15838362/391eff07-b79f-4fa3-ab7c-63f69d4ab09b)

time entry - 
![Screenshot from 2023-11-02 12-45-47](https://github.com/kimai/kimai/assets/15838362/5402db24-b5b3-4838-8504-4d836a0c6dc1)

Kimai log - 
![Screenshot from 2023-11-02 12-47-27](https://github.com/kimai/kimai/assets/15838362/c3f114ae-ea0b-4c41-9ccc-73df32af772e)

My issue looks very similar to https://github.com/kimai/kimai/issues/2010 but since there is no answer in 2010, I open this one.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.2.1

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Logfile

[2023-10-28T20:34:26.544231+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET https://mydomain.com/api/teams/1/customers/6": Method Not Allowed (Allow: POST, DELETE)" at /var/www/kimai/vendor/symfony/http-kernel/EventListener/RouterListener.php line 131 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET https://mydomain.com/api/teams/1/customers/6\": Method Not Allowed (Allow: POST, DELETE) at /var/www/kimai/vendor/symfony/http-kernel/EventListener/RouterListener.php:131)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/kimai/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:46)"} []

**Comment by kevinpapst** [comment]
Some browser plugin is causing this. You are likely requesting via GET, which is not possible.
This is usually caused by plugins that interfer with your traffic - often privacy tools or ad blocker.

**Comment by sorcer1122** [comment]
It was working fine a few versions ago. Today I tried it in different browsers (including in clean browsers, without any addons) and I am getting the same error. Are you able to point a direction where to dig?

**Comment by kevinpapst** [comment]
Your network. VPN. Proxy or alike. 
Something is changing the HTTP verb from PATCH/DELETE to GET/POST.
Maybe your webserver was updated and the admin deactivated the methods. 

Tests are existing: no release could be published if that would be broken.
And why should it suddenly break in multiple places?
I don't know what happens, but it is working correctly in the demo: https://demo.kimai.org/ 
It is your environment, if you need further support: https://www.kimai.org/en/support.html

**Comment by sorcer1122** [comment]
Thanks, you idea re webserver pushed me into playing with my caddy's settings. After adding directive 'method', it now gives me 403 error:
![Capture](https://github.com/kimai/kimai/assets/15838362/052837a0-8d4b-4bf9-a281-8b1651600ab2)

While I appreciate this is not Kimai's bug, any ideas would be appreciated.
