### ISSUE TITLE
Tags administration > filter timesheets - does not work under 500 tags

### ISSUE THREAD

**Issue by divemasterza** [kimai/kimai#4396]
### Describe the issue

The end point /api/timesheet according to the docs can accept the parameter tags:
tags[]array(query) | List of tag names, e.g. tags[]=bar&tags[]=foo

This does not seem to work.

Also in the frontend going to Adminstration -> Tags -> Filter Data -> Filter Timesheets yields and error (screenshot)
It seems that the API and frontend are expecting an **ID** (int) rather than a **string**

Secondary but related: /api/tags returns a collection of strings but no ID

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.2.1

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Screenshots

![CleanShot 2023-11-03 at 11 08 13](https://github.com/kimai/kimai/assets/5737056/57a1cba2-12bb-4996-9331-eafc0262d1fb)

**Comment by kevinpapst** [comment]
How many tags do you have?

<img width="253" alt="Bildschirmfoto 2023-11-16 um 18 32 09" src="https://github.com/kimai/kimai/assets/533162/445341e0-dbf2-4acb-9003-3f2999176cb6">

**Comment by divemasterza** [comment]
Two
![CleanShot 2023-11-16 at 20 03 08](https://github.com/kimai/kimai/assets/5737056/6aa81f2d-ccfe-4939-b4f8-f0cbc7e0e2d5)

**Comment by kevinpapst** [comment]
Okay.

When you have many tags (more than 500), the used form-field-type will change for performance reasons:
https://github.com/kimai/kimai/blob/main/src/Form/Type/TagsType.php#L40

My test system has over 1k tags, so I didn't see the issue before.
But now I can see it if I change [this line](https://github.com/kimai/kimai/blob/main/src/Repository/TagRepository.php#L29) to `1500`.

Please lower the linked `500` constant to 1 and retry. Just to confirm if that is the issue.

**Comment by divemasterza** [comment]
I can confirm changing 
'public const MAX_AMOUNT_SELECT = 500;'  to 
'public const MAX_AMOUNT_SELECT = 1';  sorts it out  for the frontend. 
But I still can't retrieve a collection of timesheets with a certain tag using the API enpoints. passing a list to the param tags, yields a 400

**Comment by divemasterza** [comment]
Just quick update - finally managed with the API. 

![CleanShot 2023-11-17 at 07 27 40](https://github.com/kimai/kimai/assets/5737056/d011aaf1-d286-462a-8d4f-738ac05c01c0) from giving me 400 it started giving me empty JSON if nothing found, or the list if we hit results. (desired behaviour)

We still have the issue on the frontend however if MAX_AMOUNT_SELECT is set 500
