### ISSUE TITLE
ImportBundle: Cannot import Billable flag from CSV

### ISSUE THREAD

**Issue by sideeffect42** [kimai/kimai#4398]
### Describe the issue

I'm using ImportBundle version 2.5.0.

No matter what I input into the `Billable` column in a CSV file, all timesheet entries are marked as billable.

Also, unfortunately the error is only visible after all rows have been imported into Kimai (the preview only shows the raw values, not what they are processed as).
When importing many timesheet entries with mixed billable/unbillable correcting this after the fact is very time consuming.

Please consider improving the preview to show the processed values instead.

This patch fixed it for me:

```diff
--- Importer/AbstractTimesheetImporter.php.orig	2023-11-03 13:49:41.770996785 +0100
+++ Importer/AbstractTimesheetImporter.php	2023-11-03 13:49:52.230949644 +0100
@@ -232,9 +232,7 @@
             $timesheet = $this->timesheetService->createNewTimesheet($user);
             $this->timesheetService->prepareNewTimesheet($timesheet);

-            if (\is_bool($record['Billable'])) {
-                $timesheet->setBillable($this->convertBoolean($record['Billable']));
-            }
+            $timesheet->setBillable($this->convertBoolean($record['Billable']));
             $timesheet->setActivity($activity);
             $timesheet->setProject($project);
             $timesheet->setBegin($begin);
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.1.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
Thanks for sharing the diff!

Here you go: https://github.com/kevinpapst/ImportBundle/releases/tag/2.5.1
