### ISSUE TITLE
ImportBundle: abort when rows contain errors

### ISSUE THREAD

**Issue by sideeffect42** [kimai/kimai#4399]
### Describe the problem

I'm using ImportBundle version 2.5.0.

When I import timesheet entries from a CSV file and some of them contain errors, the correct rows are imported into Kimai nonetheless.

### Describe the solution you'd like

The import should not be committed to the database when any rows contain errors.
If the database transaction is rolled back, I can fix the errors in the CSV file and re-upload it.

Otherwise I either
- need to delete all newly imported timesheet entries from Kimai (manually), or
- find and separate the faulty rows from the CSV to only re-upload those again.

**Comment by kevinpapst** [comment]
Can you pleas post that here: https://github.com/kevinpapst/ImportBundle/issues

**Comment by sideeffect42** [comment]
Done (kevinpapst/ImportBundle#9).
Sorry, I didn't get to the idea the repo might be in your personal account 🤦.
