### ISSUE TITLE
users can change their role to system-admin

### ISSUE THREAD

**Issue by j0hannesr0th** [kimai/kimai#440]
**Describe the bug**
Users can change their role to system-admin

**To Reproduce**
1. Login as a normal user and go to user profile
2. Click on roles
3. click on system-admin
4. watch the success message

**Expected behavior**
A normal user should not be possible to change his role to super-admin or to any other role.

**Screenshots**
<img src="https://s2.gifyu.com/images/20181124_100326.gif" />

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 63.0.3

**Comment by kevinpapst** [comment]
This is feedback for the PR #424

**Comment by kevinpapst** [comment]
Okay, tested and verified. Pushed an update to the PR #440 as this was a wrong assignment. Thanks for testing! Everything related to the PR can be posted there as a comment.
