### ISSUE TITLE
Tags field visible in create timesheet record even if I don't have permission `view_tag`

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#4400]
### Describe the issue

If I don't have the permission `view_tag`, I would expect the field "tags" not to be visible when I create a new timesheet record.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.2.1

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/941794/b3b8728b-7e90-438d-9a08-14be3ced17e6)

**Comment by kevinpapst** [comment]
Not what this permission is meant to do: https://www.kimai.org/documentation/permissions.html

If you want to hide that field, hide it with custom css.

**Comment by simonschaufi** [comment]
Well, people who have the permission should see the dropdown with tags while others who don't have that permission should not see that field, otherwise it is useless to select "nothing".

**Comment by simonschaufi** [comment]
@kevinpapst what would be your suggested implementation if you don't want to hide the field generally but only when the dropdown has no entries?

**Comment by kevinpapst** [comment]
I don't want to hide the field at all. Tags are free for everyone to use.
If you hide it, nobody will be able to create tags on the fly.

**Comment by simonschaufi** [comment]
ok.
