### ISSUE TITLE
Error submitting form according to language

### ISSUE THREAD

**Issue by Hansanghyeon** [kimai/kimai#4402]
### Describe the issue

If the language is in Korean, the time setting is 'A hh:mm.' If you spend time 'A hh:mm' in the API, you will be disappointed.

And if you change the language setting to English and call the API, it will work normally.

I think I need to modify the API Velocity according to the i18n time setting.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.2.1

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Screenshots

<img width="1214" alt="image" src="https://github.com/tobybatch/kimai2/assets/42893446/4f12a123-2f3a-4a78-ba77-1a56f2b90f06">

**Comment by Hansanghyeon** [comment]
Shouldn't we send it to UTC when we spend time on form data?

**Comment by kevinpapst** [comment]
I never tested Korean before and it seems to be the only locale that is affected.
Korean was currently defined as `A g:i` and it is the only locale that starts times with AM/PM.
BUT: there is a problem in PHP itself, that prevents time like `PM 1:42`.  PHP can't parse that, it needs to be `1:42 PM`.

This PR fixes the format definition: #4408
You can replace the file `config/locales.php` in your installation by the one from the PR.

Can you report back if that fixes your issues?

**Comment by Hansanghyeon** [comment]
@kevinpapst 

Thanks I got and tested the version of `sha256:508a2e284d8fd871733208e264df1e5c4dba6e0e414acf3b151c3e6a8d1875ce` from docker hub. It worked well in Korean without any errors. Thanks for the quick fix!
