### ISSUE TITLE
Huge performance hit when accessed via Microsoft Remote Desktop (RDP)

### ISSUE THREAD

**Issue by jassonmc** [kimai/kimai#4414]
### Describe the issue

I am using Kimai v2.2.1 and wanted to access it via a Microsoft Remote Desktop Server.
There is a massive performance hit, as soon as I open any entry, that opens up a menu in front and blurs the background, like creating a new time entry.
I used two different Kimai instances, one installed via Docker and another one installed via a shared hosting. Both are v2.2.1 and end up with the same issue.
I am pretty sure that it's the blur effect, which is causing server performance to its knees, it's really that extreme and it happens when creating a new time entry, a new customer, a new project or when modifying an entry.
I am using Kimai v2.2.1 and wanted to access it via a Microsoft Remote Desktop Server.
There is a massive performance hit, as soon as I open any entry, that opens up a menu in front and blurs the background, like creating a new time entry.
I used two different Kimai instances, one installed via Docker and another one installed via a shared hosting. Both are v2.2.1 and end up with the same issue.
I am pretty sure that it's the blur effect, which is causing server performance to its knees, it's really that extreme and it happens when creating a new time entry, a new customer, a new project or when modifying an entry.

Firefox browser has the most extreme hit, server becomes unusable. Edge browser or Brave also generate a huge hit, but not as much, still renders the Remote Desktop Server kinda unusable.

Is there a way to deactivate that background blur effect globally in Kimai, so I could make some further testing?

Firefox browser has the most extreme hit, server becomes unusable. Edge browser or Brave also generate a huge hit, but not as much, still renders the Remote Desktop Server kinda unusable.

Is there a way to deactivate that background blur effect globally in Kimai, so I could make some further testing?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.2.1

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
Is there are reason you post everything twice? Doesn't make reading easier...

Start by tuning your browser settings. Not that I am an expert in that area, but I am pretty sure that every browser has different performance and graphic related settings.

https://superuser.com/questions/387980/scrolling-browser-through-rdp-is-jerky-other-applications-behave-fine-why
