### ISSUE TITLE
the number of hours per day in the weekly calendar view

### ISSUE THREAD

**Issue by javiergalipienso** [kimai/kimai#4419]
### Describe the problem

In the previous version of Kimai (1.30), when the user used the weekly calendar view, the user could see the number of hours per day at the top of the column, this information disappears in version 2.0.

### Describe the solution you'd like

There is a possibility that this feature may reappear.
Thanks for you application
Best regards.

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/issues/4292
