### ISSUE TITLE
27.12.2023 is seen as holiday and therefore no absence booking is allowed

### ISSUE THREAD

**Issue by idemus** [kimai/kimai#4421]
### Describe the issue

I've imported the holidays for Germany (bavaria) for 2023 and 2024.
![image](https://github.com/kimai/kimai/assets/71780381/e50028d5-5bad-44ce-9263-32f62f7c53c6)
![image](https://github.com/kimai/kimai/assets/71780381/f9457005-940e-46d0-94b8-fdc93be20b54)

As far as good.
But when I want to create an absence request for 27.12.2023 - 5.1.2024 I get the error: "This is an public holiday. Booking not allowed."

![image](https://github.com/kimai/kimai/assets/71780381/66d5400a-eb74-446d-aadb-7b3bfc520caa)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.2.1

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Logfile

There is no log in the prod.log file. Last entry from 5.11.2023.

**Comment by idemus** [comment]
I've made further tests. As it seems booking holidays in 2024 is not possible right now. 
Should be changed to be able to create holiday requests for the first January days.
Besides the shown error message is wrong.

**Comment by kevinpapst** [comment]
1. This repo is not for paid plugins, post here instead: https://github.com/kevinpapst/kimai-plugins
2. You can book holidays, you are just not allowed to book them on a public holiday. So you currently have to create multiple holidays (if you want to cover christmas until the start of new year). Yes, far from ideal...
3. ... and therefor fixing this is already on the roadmap: https://www.kimai.org/store/controlling.html
