### ISSUE TITLE
links wont work after install

### ISSUE THREAD

**Issue by Fabianf1983** [kimai/kimai#4424]
### Describe the issue

after install all the links wont work and u get 2 Errors in your Console

`Failed to find a valid digest in the 'integrity' attribute for resource 'http://SERVER:8080/build/app.63b27bee.js' with computed SHA-384 integrity 'wwJlyhNjGeYv3Q0WhKHgUGLmKv9QTRphbk12zYoSWBDRCn5rdP0ZVYQm1xpjxB/p'. The resource has been blocked.`

`Uncaught ReferenceError: KimaiWebLoader is not defined`

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.3.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
environment issue 🤷

**Comment by Confuset** [comment]
We do have exactly the same issue. Just installed a fresh Kimai (v. 2.8.0.) on an IIS. My PHP Version is 8.3.
I can't use the links Rechnungen, Administration, Zeiterfassung und System.
Dashboard and Berichte look like they are working fine. I can also click the links of all the subitems of Zeiterfassung.

When I remove the "integrity" part of "\public\build\entrypoints.json" the links work as expected. But I do not know why, how and what that means...

**Comment by siinghd** [comment]
Getting the same issue. Can the probleme be CDN?

**Comment by kevinpapst** [comment]
Something changes your files and the integrity breaks. That could be some obscure CDN "minification" features, yes.

**Comment by nrgbistro** [comment]
For anyone else on Cloudflare: I created a configuration rule that excludes Kimai with this filter: `(http.request.full_uri contains "time.domain.com")`, then disabled minify and rocket loader. This fixed the issue.
