### ISSUE TITLE
"ProjectInvoiceCalculator" Identifier leads to wrong merging

### ISSUE THREAD

**Issue by habibhaidari1** [kimai/kimai#4432]
### Describe the issue

Hello, 
I really appreciate this project, absolutely nice piece of tech. Today I found a bug (imo) and maybe also a solution to this. 
The bug occurs when creating an invoice for items that have the same hourly or fixed rate and belonging the same project. 
The algorithm in AbstractSumInvoiceCalculator.php merges all the items with the same attributes I mentioned before even though they are belonging to different activities. 

This is a little bit problematic to me since I am using the DIN-5008 invoice template and shows distinct items with their activity name but the merging algorithm merging different activities together as long they are having the same rate or fixed price.  

I would suggest to add the activity name to the identifier in the projectinvoicecalculator. 

What are your thoughts?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.3.0

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
No. As the name says:

Project merges by project.
Activity merges by Activity.

But you can write a `ProjectActivityCalculator` and submit it as PR, then we can all enjoy the new method.

**Comment by kevinpapst** [comment]
BTW: closing because this is no bug. You can open always submit a feature request if you can't create the PR.

**Comment by habibhaidari1** [comment]
oh sorry, my mistake 🤦🏼‍♂️. I just saw the option in the template options
