### ISSUE TITLE
Fix price for project

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#4435]
### Describe the problem

I as a freelancer have sometimes the case that I bargin with a customer to do something and get a fix price for that no matter how long I need (shorter or longer than what I estimate and i usually charge per hour).

At the moment I can only set a fix price PER ENTRY but not for the whole project. I still want to have several chunks of slots where I work on the project because i also need a break sometimes ;)

### Describe the solution you'd like

Have a fix price per project available that will be billed when I generate an invoice no matter the time entries.

**Comment by kevinpapst** [comment]
Closing as duplicate #4381 
Lets collect all ideas over there.
