### ISSUE TITLE
Can you Add Brazilian Portuguese Translation? I can help it..

### ISSUE THREAD

**Issue by marquesmatheus** [kimai/kimai#444]
Hi i'm Brazilian and i'm using the v1 kimai, could you add the Brazilian Portuguese Translation?
I can help you translate if you want it.

Thx.

**Comment by marquesmatheus** [comment]
Now i've saw the folder for translations, can i add the pt-br translation for you?

**Comment by kevinpapst** [comment]
Sure, that would be awesome.
Here is a short documentation how to start (basically copy all English files in the translation/ directory and translate the contents: https://github.com/kevinpapst/kimai2/blob/master/var/docs/translations.md

**Comment by marquesmatheus** [comment]
I've allready translated all files, how can i send you the files?

**Comment by marquesmatheus** [comment]
Ok i'm going to do a pull request! :) thx

**Comment by marquesmatheus** [comment]
About the portuguese translation, how to show it on preferences?

**Comment by kevinpapst** [comment]
If you have everything correct, you need to flush your cache `bin/console cache:clear` - afterwards it should show up

**Comment by marquesmatheus** [comment]
I've runned this bin/console cache:clear and now got again this msg:

Oops! An error occured.
500: Internal Server Error
An unexpected error occured, please try again. You may have found a bug, so please contact your administrator if the problem doesn't go away after you tried it again.

**Comment by kevinpapst** [comment]
I tried your branch and it is working fine. 
Your error must be related to something else (check file permissions, also the log file in var/logs/).
I will push some required changes to your PR soon.

**Comment by marquesmatheus** [comment]
Sucess! Thx man!

**Comment by marquesmatheus** [comment]
I just have another question, i've made changes on the messages file in the translation folders, the application was working good, I runned again the bin/console cache:clear command, and again got 500 internal error.

Everytime that i made a change i need to do this console cache clear???? Always after do this i got the error, and the only way is to do everything over again. :(

**Comment by kevinpapst** [comment]
You have to clear your cache for some types of changes, adding translation files is one of them.
But changing a single translation inside an existing file should be displayed after reloading the page, no need to clear the cache IMO.
Clearing the cache shouldn't give you a 500. Why does your log file say?

**Comment by marquesmatheus** [comment]
Found out what happened i was using the command without passing the root or group.

I've used `sudo -u www-data bin/console cache:clear --env=prod`
Was missing permissions to write on /var/www/kimai2/var/cache/prod
....

Finally understood better, thx for the patience.
