### ISSUE TITLE
Azure SAML icon missing

### ISSUE THREAD

**Issue by CreMindES** [kimai/kimai#4440]
### Describe the issue

In case of enabling Azure SAML login, the Microsoft icon is missing.

The [docs says](https://www.kimai.org/documentation/saml-azure.html#kimai-configuration) to put in a `azure` as provider. [This code snippet shows that the icon is resolved directly from the name of the prodiver](https://github.com/kimai/kimai/blob/6a828cc9bd3769fc24d486f52e3153cbf5ff5299/templates/security/login.html.twig#L58). The only problem is that there seems to be no `azure` icon, but a `microsoft` one, which works just fine.

> I haven't checked where else the provider is used. 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.3.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/5306361/21cb062c-c015-4397-bd34-716fcce251ae)

vs.

![image](https://github.com/kimai/kimai/assets/5306361/44a05ada-d1ce-4b41-8d04-99d8f8cc8a97)

**Comment by kevinpapst** [comment]
Thanks for sharing your finding!

Fontawesome does not provide a brand image for "azure".
Actually the docs are wrong, it should be "microsoft" and not "azure". I fixed it.

**Comment by CreMindES** [comment]
Thanks @kevinpapst
