### ISSUE TITLE
Performance Issues with blurred background in RDP Sessions

### ISSUE THREAD

**Issue by schulzc21** [kimai/kimai#4443]
### Describe the problem

We are currently testing Kimai 2.3 in an environment using RDP Sessions / Terminal Server connections.
When Adding entries to timesheets in Kimai 2, the background window is blurred, which looks and works fine on "normal" clients.

Using RDP Sessions over VPN connections e.g. from the home office, the whole App becomes really unresponsive, you can watch letters appear while you type.

Thanks in advance,

Christian

### Describe the solution you'd like

Will there be a possibility to switch the "blurred" effect off using parameters?

**Comment by kevinpapst** [comment]
See https://github.com/kimai/kimai/discussions/4415

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/discussions/4415#discussioncomment-7523332
