### ISSUE TITLE
Columns that are too long (from older 2.x versions) prevent database schema update

### ISSUE THREAD

**Issue by gbl** [kimai/kimai#4449]
### Describe the issue

(This is similar to, but not the same as, the closed #1028)

I updated my Kimai 2.x installation (not sure about the version, it was from early June 2020) to version 2.3.0. When running `bin/console kimai:install -n`, I got an error about the total column size being too long (and the installer aborted). 

After some debugging and manually reducing column sizes in the existing database, specifically in `kimai2_users`and `kimai2_customers`, I was able to run the installer successfully.

It seems like some of the tables use their allowed column length to the max, and the installer tries to add new columns before it reduces the excessive size of old ones, which leads to this problem.

Not sure how to fix this, but moving the long columns which need to be shortened to the top of the corresponding ORM-defining files might already help as it could make the installer reduce their sizes first.

I don't think it's an issue with old DB versions, as the older installation had 10.6.12-MariaDB and the new one 10.11.4-MariaDB.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.x (not sure, from June 2020) now updating to 2.3.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Logfile

There are no entries from the installer in the log file, and as I used `strace` to find out which `ALTER TABLE` statements caused the error, I don't have useful messages in the scrollback either, I'm afraid.

**Comment by kevinpapst** [comment]
There have been a couple of bugs related to that strict MariaDB setting, maybe you find some hints in the already closed issues: https://github.com/kimai/kimai/issues?q=is%3Aissue+column+length+is%3Aclosed

I am updating old Kimai installations every week and never came across such a problem. Even when updating from 8 year old  Kimai 1 installations. As your installation was already 3 years old, which is like stone age (or thousands of commits ago), and there was no such feedback for a long while, I am going to close this as not reproducible. 

Anyway, thanks for sharing your findings. Very much appreciated 👍
