### ISSUE TITLE
v0.9.3.1384 - Export to PDF does not export comments even if "print comments" is selected. 

### ISSUE THREAD

**Issue by Kurgan-** [kimai/kimai#445]
After I have upgraded to 0.9.3rc1 (which I suppose is 0.9.3.1384, I still have not managed to understand Kimai version numbering scheme) I have found that doing an Export in "list" format does not export the "comments" field anymore.

**Comment by Kurgan-** [comment]
After further research, I have found that by modifyng the file export_pdf2.php I can have the comments back. I have just set up a very quick and dirty hack around line 270.

The original file reads:
    270     if (isset($this->columns['comment']) && !empty($row['comment']))
    271       $comment_string = $kga['lang']['comment'].': <i>'.nl2br($row['comment']).'</i>';
    272     else
    273       $comment_string = '';

simply by removing the if clause and always setting the "comment_string" variable I have been able to print comments (also to print empty comments, of course).

**Comment by Kurgan-** [comment]
I have just found that it also does not print total times (only total amount due).
It seems that (isset($columns['dec_time']) returns false while it should be true.

**Comment by ServiusHack** [comment]
Are you sure the columns are not disabled in the export extension? Disabled columns have a red background color. Just to be sure please also empty your browser cache.

If you can provide the request headers which are sent in the request to download the file, that would be of help.

I was unable to reproduce the error with the latest development version. You can try it out at our [demo installation](http://www.kimai.org/demo/).

**Comment by Kurgan-** [comment]
I have checked (emptied cache, run an anonymous browsing session) and it seems that no colums are disabled.  Some of the cells are marked in red background (both now on the anonymous browsing session with clean cache as before, on a normal browsing session with the cache still not cleaned), and I don't understand why, but no full column is marked in red background. Also, if I export in a different format (csv, excel, or the othe PDF format, the comments are in fact exported correctly. I'm attaching a screenshot to show you the strangely red-background cells.

As for the headers, I suppose that you are looking for this:

print_comments=true&print_summary=true&create_bookmarks=true&download_pdf=true&document_comment=&axAction=export_pdf2&axValue=%7C%7C%7C&first_day=1414796400&last_day=1420326000&axColumns=date%7Cfrom%7Cto%7Ctime%7Cdec_time%7Crate%7Cwage%7Cbudget%7Capproved%7Cstatus%7Cbillable%7Ccustomer%7Cproject%7Cactivity%7Cdescription%7Clocation%7CtrackingNumber%7Cuser%7Ccleared&timeformat=H%3AM&dateformat=d.m.&default_location=&filter_cleared=-1&filter_refundable=-1&filter_type=-1

![kimai columns](https://cloud.githubusercontent.com/assets/10371854/5606736/276808d8-943d-11e4-8dd4-a694cabf29ef.jpg)

**Comment by ServiusHack** [comment]
Are those black lines between entries of different days really not shown for the description and comment column? Then something is really wrong. The background of a column should also either always be red or normal.

You're right, by request headers I actually meant the request parameters. From them I can see that the comment column is not selected for export. So it makes sense you don't get comments in the exported PDF. But then the comments should not be included in any export. Do the request parameters include "comment" for other export types?

Click on the column title "Comment" to enable and disable the column. Try exporting a PDF after toggling once. The column seems to be disabled but that is not displayed correctly.

Maybe something went wrong while overwriting the old files with those from the new version. You could try uploading the files again, just to make sure they are all up to date. I don't really have an explanation how this behavior can happen at the moment.

**Comment by ServiusHack** [comment]
I just found a bug in toggling the state of the description column. To make it work you need to apply #447.

**Comment by Kurgan-** [comment]
Yes, black lines are really not shown. Apart from the black markings over some of the text, the screenshot is "as-is" in my browser, complete with wrongly positioned headers at the right of the table.. I come from a long story of Kimai updates, both stable and nightly, so maybe my database has somehow become corrupt, even if I don't see any errors. When I update, I set up a new directory, rename the old one, and then I copy config file to the new one. I work locally with ssh, no FTP. I don't think that I can have missed some files in an update.

Comments were exported correctly before last update.

After toggling comment colum off (red) and on again, I get comments in export.
I can confirm that description does not in fact get toogled at all (no red backuground) when I click it.
After toggling comment column I have also a proper visualization (no single red cells, black lines are OK).

Please check also this issue from a previous post (3rd from the top): "I have just found that it also does not print total times (only total amount due). It seems that (isset($columns['dec_time']) returns false while it should be true."

It seems to me that the "dec_time" column is set in the request parameters, but still no total times showed unless I remove the "if" clause from export_pdf2.php. They where shown before last update.

**Comment by ServiusHack** [comment]
If you also include the summary in the PDF file, does the summary show the total times? If you have a long list for the same project, is the total time shown just before page breaks?

Maybe try the same thing here as well: Click on the column to disable and enable it again.

**Comment by Kurgan-** [comment]
It seems that also this column was somehow disabled (even if there was no red background).  After toggling it once, time totals appeared both in the summary  table and in totals and subtotals before page braks. 

Is seems to me that all of these issues where caused by some bad condfiguration data in the database regarding columns. What I don't understand is why is was not shown in the column background colour, and how it could have happened.

I believe that the problem is more or less solved now.

**Comment by ServiusHack** [comment]
I checked the old and new version if there is some change which could cause this behavior but I found nothing.

**Comment by ServiusHack** [comment]
I just found out why the disabled columns were displayed incorrectly. It's fixed now.
