### ISSUE TITLE
Built-in accounts cannot log in if ldap is also enabled

### ISSUE THREAD

**Issue by nebulade** [kimai/kimai#4452]
### Describe the issue

For installations which have built-in accounts (user db column type `kimai`) as well as ldap auth enabled. Only the LDAP users are able to log in.

This seems related to https://github.com/kimai/kimai/commit/92c6922afb625699322a0393cc31a7820f5216d9#diff-6e0fa87aa2dd10ec693f77efb0baded2b184c3d4b08ec20f52ddebfeac0c0660L87 where now all users are checked against LDAP source regardless of user auth source from the db.

This is happening since 2.4.0 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.4.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Can you please test #4453 to see if that fixes your issue?

ping @gramakri and @fabio-pif as well

**Comment by nebulade** [comment]
Thanks for the fast fix, I can confirm it works again with the changeset.
