### ISSUE TITLE
More Options for Invoice History

### ISSUE THREAD

**Issue by derdeimos** [kimai/kimai#4456]
### Describe the problem

There should be more options to customize the invoice history. Now we have fields from the invoice and the customer name. This table is not clear enough, because we have many projects for one client. It would be helpful if we could display fields from the project to distinguish invoices from different projects for the same client.

### Describe the solution you'd like

Now we have Date, User, Description, ...
There should be more fields for the project, like Order Number, Order date, time Budget, ...
Also, it should be possible to display custom variables for projects and customers.

### Screenshots

![image](https://github.com/kimai/kimai/assets/32060272/43fede17-1343-4438-9195-04c872b849b1)

**Comment by kevinpapst** [comment]
Thanks for the ideas! Unfortunately the invoice only knows which customer it belongs to.
What use-case do you see for custom fields of a customer here?

**Comment by derdeimos** [comment]
When we create an invoice, we can select a customer and a project. Why is it not saved for which project an invoice is generated?
Would it be a lot of effort to change that?

We have some additional information about the customer, who in our team is responsible for a customer, due date, vendor number...
The workflow would be faster if we have all this information in the invoice overview. Now we have to look up this information for each invoice.

**Comment by kevinpapst** [comment]
Project connection is not saved. And I have no plans to change that anytime soon.
