### ISSUE TITLE
Invoce History search and sort by project

### ISSUE THREAD

**Issue by derdeimos** [kimai/kimai#4457]
### Describe the problem

In the invoice history, we can search for invoices in a Time range, by Customer, and Status. 
We have many projects for one client. It would be easier to find a specific invoice if we could also search for a project.

### Describe the solution you'd like

Add an option to search for the project of an invoice. 
Display the project in the table Invoice history and sort by project.

### Screenshots

![image](https://github.com/kimai/kimai/assets/32060272/f2bf4270-bf33-4605-ba8c-4d476dd965d2)

**Comment by kevinpapst** [comment]
Invoices do not know anything about projects. 
They store a list of timesheets, the selected search filters are not stored.
You have to use the invoice free text field to store the project name
