### ISSUE TITLE
More Detailed Project Overview

### ISSUE THREAD

**Issue by derdeimos** [kimai/kimai#4460]
### Describe the problem

Now in the project list (admin/project/) all projects are in one list. There should be all project information available in this table.

> 

### Describe the solution you'd like

There should be an option to sort open and closed projects.

All project information should be accessible as table columns. For example, from Time Budget: Time budget, Working hours total, and Billable. And all the information from Prices, Budget, Expenses, Tasks
This would give a better overview over all open projects. 

### Screenshots

![image](https://github.com/kimai/kimai/assets/32060272/956a9dfc-6b0a-45ca-9c92-d6cfc28e2de3)

**Comment by kevinpapst** [comment]
No, won't do that. That would be an excessively expensive page.
Information overload.
Thanks for the suggestion though.
