### ISSUE TITLE
Invoice information for Projects

### ISSUE THREAD

**Issue by derdeimos** [kimai/kimai#4461]
### Describe the problem

There should be invoice information for a project in the project overview.
We have many projects with more than one invoice. Now we have to search for all these invoices in the invoice menu.

### Describe the solution you'd like

All invoice information for a project should be in the project details. (Invoice Number, Invoice date, billed hours, net amount, total amount, due date, invoice status,  ...)

These fields should also be optional in the project overview.

**Comment by kevinpapst** [comment]
Invoices are not connected to projects. 
That will not be changed anytime soon, so this feature is impossible to build.
