### ISSUE TITLE
On creating invoices comes the error: Filter "format_decimal_number" is not allowed:

### ISSUE THREAD

**Issue by alexh-swdev** [kimai/kimai#4467]
### Describe the issue

I am using the twig format_decimal_number filter in my invoice template, which was working fine until the last upgrades. 
What happened? How kann I use this filter again?
![grafik](https://github.com/kimai/kimai/assets/18015530/e29ccfab-3af8-4a02-ac61-752089ba7dcb)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.4.1

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Hm, should be allowed: https://github.com/kimai/kimai/blob/main/src/Twig/SecurityPolicy/InvoicePolicy.php#L107

I'll add it explicit.
