### ISSUE TITLE
Add maintenance mode

### ISSUE THREAD

**Issue by bjinthahouse** [kimai/kimai#4469]
### Describe the problem

When updating OS packages or Kimai instance, I cannot prevent people from trying to add timesheet entries.

### Describe the solution you'd like

Add a button on webinterface, or an option for local.yaml to activate (and deactivate) maintenance mode

**Comment by kevinpapst** [comment]
Switch your webserver config for a second, reload webserver, update kimai, revert config, reload.
All of that is scriptable.

Won't be added to Kimai.
