### ISSUE TITLE
On Kimai 2.0.34  and Chrome I can often login - CSRF token issue

### ISSUE THREAD

**Issue by yardstudio** [kimai/kimai#4480]
### Describe the issue

I have installed Kimai CSRF token. Often if I trying login from Chrome, CSRF token issue is displayed.  With Firefox I can login at the same time

![2023-12-04_16-39-08](https://github.com/kimai/kimai/assets/25852179/d517ea22-155f-48d2-b537-ecbd9db785e1)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.34

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Cannot reproduce. But if you leave the screen open for a long time without reloading, this might happen.
