### ISSUE TITLE
API - /timesheet POST does not allow for "fields" which are in the documetnation (see demo instance)

### ISSUE THREAD

**Issue by KatjaGlassConsulting** [kimai/kimai#4484]
### Describe the issue

On the Swagger API: https://demo.kimai.org/api/doc - when I want to create a timesheet via a POST request, there is an error. It seems there is a validation which checks for "extra fields", but according example data content, these fields should be possible. 

The following works:
```
{
  "begin": "2023-12-06T07:00:00",
  "end": "2023-12-06T07:10:00",
  "project": 31,
  "activity": 417,
  "description": ""
}
```

What I would need is the support for "billable", e.g.
```
{
  "begin": "2023-12-06T07:00:00",
  "end": "2023-12-06T07:10:00",
  "project": 31,
  "activity": 417,
  "description": "",
  "billable": true
}
```

But executing this, I do get a 400 error - which unluckily does not really show the issue - it seems "billable" is not supported, but should:
```
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "errors": [
      "This form should not contain extra fields."
    ],
    "children": {
      "begin": {},
      "end": {},
      "project": {},
      "activity": {},
      "description": {},
      "tags": {}
    }
  }
}
```

Executing the full example with all fields results in the same.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

Unknown

**Comment by kevinpapst** [comment]
It depends on the user permissions if the field is visible.

**Comment by KatjaGlassConsulting** [comment]
Ah, I see. Could in such cases the error message be adopted? It's a bit frustrating. The issue can also be closed. Thanks

**Comment by kevinpapst** [comment]
> Could in such cases the error message be adopted

Unfortunately not, at least I don't know how. That automatic logic is buried too deep and the API layer does not have access to that info.
