### ISSUE TITLE
Fatal Error In DefinitionErrorExceptionPass.php line 49

### ISSUE THREAD

**Issue by Borega** [kimai/kimai#4485]
### Describe the problem

Delted (or renamed) the cache/prod folder for clean rebuild after update of Image. Now I get the following error:

In DefinitionErrorExceptionPass.php line 49:

                                                                               

  Cannot autowire service "App\Command\UserLoginLinkCommand": argument "$logi  

  nLink" of method "__construct()" references interface "Symfony\Component\Se  

  curity\Http\LoginLink\LoginLinkHandlerInterface" but no such service exists  

  . Did you create a class that implements this interface?   

Results in a white page not loading anything
When using the old prodcache folder I dont get it but then get the error regarding https://github.com/kimai/kimai/issues/4478

### Describe your setup and add your Docker compose file (redact your credentials)

version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    volumes:
      - kimai2_kimai-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxx
      - MYSQL_ROOT_PASSWORD=xxx
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:apache-latest
    volumes:
      - kimai-local:/opt/kimai/config/packages/
      - kimai2_kimai-var:/opt/kimai/var
    ports:
      - 8001:8001
    environment:
      - memory_limit=1024M
      - ADMINMAIL=xxx
      - ADMINPASS= xxx
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai?charset=utf8&serverVersion=5.7
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,
    restart: unless-stopped

volumes:
  kimai-local:
  kimai2_kimai-var:
    external: true
  kimai2_kimai-mysql:
    external: true

**Comment by kevinpapst** [comment]
No support can be given with such a volume:

- kimai-local:/opt/kimai/config/packages/

Anyway. It works. There is no bug. Your installation is broken. Likely missing config files.

**Comment by Borega** [comment]
Unmounting the volume worked. Thanks for the Help.
