### ISSUE TITLE
Overwrite/Add to an existing Timesheet over Import

### ISSUE THREAD

**Issue by ramillionaire** [kimai/kimai#4487]
### Describe the problem

I've noticed when using the importer that it cannot update existing time entries through an import. Everything I import is logged as a new entry. If, for example, I want to add something to the description of times that have already been entered, or through newly created fields.

If there is a workaround for this, I look forward to your solutions. Otherwise, a feature for the importer that allows editing existing times would be a blessing.

### Describe the solution you'd like

I think if the exported timesheets were supplemented with an additional column containing the IDs, and these were then re-imported, that would solve the problem. It's just my idea – maybe you have a quicker and more straightforward solution.

**Comment by kevinpapst** [comment]
Thanks for posting! 
But in that case I can tell you right away: won't be added. 
You can use the API for complex and ongoing syncronization tasks.
