### ISSUE TITLE
Ability to not display anything related to Expenses / Money / Customers

### ISSUE THREAD

**Issue by TheWanderingCoder** [kimai/kimai#449]
Firstly, great piece of software. It was very simple to implement.

Secondly, on the feature request side. I was wondering if it would be possible to exclude all items related to money / customers to show mainly Team Members, Project, Tasks and Times only.

Also, would it be possible at all to (for example logged in as admin with access to all groups) when viewing the overviews on the timesheets panel, to show which user is doing which task.

Thanks in advance. If I need to clarify anything please let me know.

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/issues/1291
