### ISSUE TITLE
Ability to Change/Update Username

### ISSUE THREAD

**Issue by treverehrfurth** [kimai/kimai#4493]
### Describe the problem

I do not see a way to change usernames once a user has been created.

### Describe the solution you'd like

For an admin to update/change usernames.
For example, if an employee gets married and lastname changes, it would be nice to reflect that or any other change in their username.

**Comment by kevinpapst** [comment]
That is what the `name` field is for. 

The username is a unique key that cannot be changed.
If you want to change it, do it via database.
I will not add a feature in the frontend for it.


Thanks for sharing your idea 👍 even if it is a no this time

**Comment by treverehrfurth** [comment]
Doing it via database is fine... as long as there is some documentation on how to do that, I haven't found any around it, is there some you can point me to?

Thanks
