### ISSUE TITLE
Currency Symbol not showing in Report

### ISSUE THREAD

**Issue by dominik2727** [kimai/kimai#4498]
### Describe the issue

In the following Report the Currency Symbol is showing:

- weekly report one User
![grafik](https://github.com/kimai/www.kimai.org/assets/8851325/cc11ab42-889a-46b1-ab7a-f139c4288e11)

In the following Reports the Currency Symbol is NOT showing in the sum:

- monthly report one User
- yearly report one User
![grafik](https://github.com/kimai/www.kimai.org/assets/8851325/49cbad23-fb33-4707-a869-91466f03234b)

In the following Reports the Currency Symbol is NOT showing at all:

- weekly report all Users
- monthly report all Users
- yearly report all Users
![grafik](https://github.com/kimai/www.kimai.org/assets/8851325/d7a9750d-4f1a-4a88-9617-5c8001903a6d)

Kimai running on Kubernetes Cluster on RPi kimai2:apache-2.6.0-prod, Database mysql:8.2.0

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.6.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

**Comment by kevinpapst** [comment]
Yeah. True. On purpose.
The weekly view contains customer and project information => thus a currency from the customer.

All other views only have aggregated sums, but NO customer information, so a currency cannot be displayed as it is not known. The sums might even consist of mixed currencies.
