### ISSUE TITLE
Memory leak in kimai2:apache-1.30.2-prod docker image

### ISSUE THREAD

**Issue by agabarre97** [kimai/kimai#4505]
### Describe the issue

We are using `kimai2:apache-1.30.2-prod` docker image in AWS, as a task into an ECS. This task just contains the docker image. As you can see in the image below, we've found that the memory is constantly increasing. Is this a known issue? I haven't seen any issue/discussion talking about that.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

kimai2:apache-1.30.2-prod

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

### Screenshots

![image](https://github.com/kimai/kimai/assets/72514374/0a8d16a8-4679-442a-9a3a-56692cf62f4a)

**Comment by kevinpapst** [comment]
Retry with a recent docker image and report back. No support given for the old 1.x branch.

This docker image was widely used, so I doubt that this was a general issue, we would have heard about it.
So please include an image for a time range that is at least a couple of days and that includes numbers, not just some radom graph. E.g. if the available memory was 128MB then 98% isn't much...
