### ISSUE TITLE
Reverse Proxy: TRUSTED_PROXIES env variable is ignored

### ISSUE THREAD

**Issue by Not-Code** [kimai/kimai#4533]
### Describe the issue

Hi,
I tried to configure Kimai behind Traefik with TLS termination as described in the section **Reverse Proxy** of the [Kimai documentation](https://www.kimai.org/documentation/webserver-configuration.html).

Traefik by default adds the following headers:

<img width="323" alt="image" src="https://github.com/kimai/kimai/assets/18069705/ba33d435-f119-49b6-8ffa-b69280b28440">

and the TRUSTED_PROXIES was set to the subnet that Traefik was using to connect to Kimai. Unfortunately, the website was not working for some resources and, for example, executing a curl to the following url:

`curl -kv https://fqdn:44300/en/homepage`

always returned a redirect pointing to a http location.

I searched globally in Kimai codebase to understand how the TRUSTED_PROXIES environment variable is used in PHP but the only reference I found is inside the apache configuration file .docker/000-default.conf:

`PassEnv TRUSTED_PROXIES`

So I extended my research to [Symfony documentation](https://symfony.com/doc/current/deployment/proxies.html) where I found the following information:

<img width="553" alt="image" src="https://github.com/kimai/kimai/assets/18069705/a2f7d4d0-d8ab-4748-b911-031b72030ca5">

Adding the Symfony configuration to the file /opt/kimai/config/packages/framework.yaml did the trick in my case.

Can anyone, with more knowledge of Kimai, confirm if the TRUSTED_PROXIES variable is ignored and a PR is indeed needed?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

kimai/kimai2:apache-2.8.0-prod

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
That is interesting! Thanks for your investigation and poking around @Not-Code 👍 

Seems the config transfer got lost during the Symfony upgrade from 4 to 6 (in Dec 2022):
https://github.com/kimai/kimai/commit/90a0fd8a221dce23dbd27451682d7134ab1ce9df#diff-ab1615a3a159df0750aa7b76472124966ab3076c26abcd050f6b9120fbda6c61

I just wonder, why nobody ever happened to stumble upon that.
Using a reverse proxy is pretty common in Docker setups.

@tobybatch did we have feedback on this one?

Yes, I think it needs a PR. Do you want to do it @Not-Code , as you found it? Otherwise I will add it to the next release.

**Comment by Not-Code** [comment]
Thanks @kevinpapst! If it's faster, you can simply add it to the next release.

I don't know why I'm the first to notice it, but on a functional level the problem only manifests during the login/logout flow. So I assume that any of the following additional configurations can work around the issue:

- HSTS
- SAML or any authentication process that bypasses the login/logout flow
- Reverse proxy with HTTP to HTTPS redirection

Also I think that if someone is using a TLS terminated reverse proxy, it should be pretty common to have one of those additional configurations. While most people using it on docker maybe just use it on plain http (at the end of the day a reverse proxy setup is not at the level of the average user).

**Comment by kevinpapst** [comment]
Ok, I'll add it.

True, I guess most terminate SSL at the reverse proxy. Is HTTPS that the only use-case you need this flag for?

**Comment by Not-Code** [comment]
Yes, it is only needed for HTTPS. Otherwise without this fix you will get into the scenario described in the Kimai documentation no matter the value you use in TRUSTED_PROXIES.

<img width="1360" alt="image" src="https://github.com/kimai/kimai/assets/18069705/2f2929ff-d364-4c1d-ae22-83a7a3f129d1">

**Comment by kevinpapst** [comment]
Oh, hahaha. Can't even remember that I wrote these docs 🙈
