### ISSUE TITLE
API endpoint for POST/API/TIMESHEETS no longer support "begin" and "end"

### ISSUE THREAD

**Issue by KatjaGlassConsulting** [kimai/kimai#4534]
### Describe the issue

Using susan_super and the stable demo API - https://demo-stable.kimai.org/api/doc - 2.8.0

When creating a new timesheet via API, I receive an error that "This form should not contain extra fields." - when I remove begin and end it is working. (Remark: project and activity newly created, role edit_billable_own_timesheet set to yes for all).

{
    "begin": "2024-01-04T10:30",
    "end": "2024-01-04T12:00",
    "project": "209",
    "activity": "2677"
}

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.8.0

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
This test for example makes sure the API works: 
https://github.com/kimai/kimai/blob/main/tests/API/TimesheetControllerTest.php#L452

There are hundreds of users synching data from and to Kimai, such a bug wouldn't go unnoticed.
If the time-tracking mode (System > Settings > Timesheet > the first dropdown) is changed to punch-in only, then these fields do not exists. Neither in the frontend, nor in the API.

The demo is often misconfigured, do not use it to test your implementation, always test against your own dev system.
