### ISSUE TITLE
demo experience

### ISSUE THREAD

**Issue by eddyizm** [kimai/kimai#4535]
### Describe the issue

Tested the demo using `john_user` account and logged in with the english US interface, however upon login, it took me directly to the German interface. 
https://demo.kimai.org/de/timesheet/

Not knowing german and wanting to share this demo with someone, would be rather difficult. I went and updated the URL with `en` to fix it but wanted to at least let someone know so it is addressed.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

demo

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

Other (please mention below)

**Comment by kevinpapst** [comment]
The UI language is user setting (you can change it in the users preferences). It will always lead you to the user defined language upon login. As this is a public demo, someone before changed that specific account to german.

So there is nothing to address here. Wait max. 12 hours and the demo is reinstalled and all accounts are back to english.

But I appreciate that you took the time to report, thanks 👍
