### ISSUE TITLE
Dropdown items loose ordered upon typing

### ISSUE THREAD

**Issue by aldas** [kimai/kimai#4545]
### Describe the issue

Unlike 1.30.X version when adding new calendar item and starting to type in Activities list, the list that poped up - it was sorted (alphabetically I think).  In 2.7.0+ it is not anymore.

When I inspect source the HTML option elements seem to be ordered correctly but when the autocomplete list is rendered the items seem to be out of order.

Example:
![image](https://github.com/kimai/kimai/assets/2320301/0a026bd3-5e35-4aa7-b25d-8546071a5a45)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.7.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Screenshots

From Kimai demo site: https://demo.kimai.org/

Added 3 activities: "test 1", "test 2", "test x 3"  

when typing "est" into activities autocomplete field the following options are shown and they do not seem to be ordered alphabetically.
![image](https://github.com/kimai/kimai/assets/2320301/03c28568-bb10-4948-bec9-2e0c043f684f)

**Comment by aldas** [comment]
I have not tested this with Kimai, but maybe adding https://github.com/kimai/kimai/blob/12ef19df28fd9bf2bf4a849664bea681c2fe55fd/assets/js/forms/KimaiFormSelect.js#L73

[`sortField`](https://tom-select.js.org/docs/#sortfield) to options would help getting displayed list ordered. 

p.s. dunno if I even linked correct place. I have no understanding understanding how Kimai displays forms and does JS

**Comment by kevinpapst** [comment]
Just for reference, add:
```
sortField:[{field:'$order'},{field:'$score'}]
````
to https://github.com/kimai/kimai/blob/main/assets/js/forms/KimaiFormSelect.js#L85
