### ISSUE TITLE
Error while updating from 2.8.0 to 2.9.0

### ISSUE THREAD

**Issue by ghost** [kimai/kimai#4552]
### Describe the issue

While updating from Kimai 2.8.0 to 2.9.0 I got the following error:

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 88:
The service "doctrine.orm.default_annotation_metadata_driver" has a dependency on a non-existent service "annotation_reader".

Rebuilding the cache failed. Kimai won’t load anymore. Kimai is hosted on a shared hosting server at all-inkl.com

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.9.0

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
hard delete the cache: 
```
cd kimai
rm -r var/cache/*
```
retry

**Comment by kevinpapst** [comment]
If that does not help, remove all plugins and retry, maybe one of them is too old and still requires this deprecated service

**Comment by kevinpapst** [comment]
Asking for support and then not commenting back... 👿 fantastic feedback 👍
