### ISSUE TITLE
[Plugin Importer] If existing project has dash in name while importing timesheet new project is created

### ISSUE THREAD

**Issue by codiflow** [kimai/kimai#4562]
### Describe the issue

I hope this is the right place for reporting this issue as I could not find a dedicated bug tracker for the Importer plugin.

This is just a small bug which I tested with a recent installation of Kimai Docker, with the newest Importer plugin version and with the CSV import. Don't know if the JSON import is affected too.

If the **project name** contains a **dash** (e.g. like in the German word `IT-Dienstleistungen`) the Importer plugin **always** creates a new project for all timesheet entries with this name on each import.

What I did:
I **precreated** a project named `IT-Dienstleistungen` in Kimai and specified the same project name in my CSV file. But the Importer always creates a **new** project named `IT-Dienstleistungen` which is linked to the specific customer for every import (not every record).

As soon as I **remove the dash** from the precreated project name and adjust the CSV file accordingly it behaves correctly and appends the records to the already existing project in Kimai.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.9.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

Other (please mention below)

### Logfile

-

### Screenshots

-

**Comment by kevinpapst** [comment]
The correct bugtracker is here: https://github.com/kevinpapst/ImportBundle

If you could re-post there, that'd be great. Unfortunately, I can't move the issue over there.
