### ISSUE TITLE
Import fails via Firefox, Unsupported file given

### ISSUE THREAD

**Issue by techsupportkoeln** [kimai/kimai#4565]
### Describe the issue

Unfortunately, you cannot carry out CSV imports via Firefox. Unfortunately I don't know whether the bug is related to Kimai or Firefox.
I see the following error on the Kimai Import Page: Unsupported file given, invalid mimetype (text/plain / application/vnd.ms-excel). Try to use another browser.
With edge it is working.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.7.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Logfile

there is no entry for this in the logfile.

### Screenshots

![kimai_import](https://github.com/kimai/kimai/assets/78727046/2b65ab01-4612-44d8-9679-22e53c3bbe61)

**Comment by kevinpapst** [comment]
Next time: https://github.com/kevinpapst/ImportBundle

Clearly a Firefox issue. A CSV file is a `text/csv` mimetype and not `application/vnd.ms-excel`.

Maybe I can add a workaround here, but it feels wrong:
https://github.com/kevinpapst/ImportBundle/blob/main/Importer/ImporterService.php#L73

**Comment by kevinpapst** [comment]
Lets close here, wrong repo.

**Comment by kevinpapst** [comment]
Move on here: https://github.com/kevinpapst/ImportBundle/issues/6
