### ISSUE TITLE
Importing fails if two or more Customer use the same Project Name

### ISSUE THREAD

**Issue by techsupportkoeln** [kimai/kimai#4566]
### Describe the issue

I have some different Customers and they have the same Project Name, e.g.

Customer | Project | Activities
-----------------------------------------
Customer1 | Service | Remote Support
Customer2 | Service | Remote Support
Customer3 | Service | Remote Support

As i understand, i can set the Activities as Global. But the Projects are always Customer related, but I can use the same name multiple times. The Project ID is different from each one.

Unfortunately, this circumstance causes an error during import.
The importer cannot assign the Project and then wants to create a new Project for this Customer. Also with the same name as the existing Project.

I also tried to import the CSV file with the Project ID shown in the URL, but the importer doesn't seem to recognize the Project ID.

In my case the importer cannot be used because I have to use the same Project names for multiple Customers.

Maybee it's possible to import in the future via Project ID and not only with the Project Name.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.7.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by techsupportkoeln** [comment]
wrong repo. I will open it again the ImportBundle Repo.

**Comment by kevinpapst** [comment]
Don't re-open. It is already fixed. Fetch the latest release from the repo.
