### ISSUE TITLE
Plugin Employee account: manual adjustments for holidays - half days possible?

### ISSUE THREAD

**Issue by david-proba** [kimai/kimai#4567]
### Describe the problem

added in version 1.4: manual adjustments for holidays, e.g. top up available days with remaining days from last year
Is it possible to adjust e.g. 2.5 days from last year?
At the moment with version 1.5 of the employee account plugin I can only adjust full days.

### Describe the solution you'd like

add possibilty to manual adjust half days.

### Screenshots

![Bildschirmfoto vom 2024-01-15 15-44-58](https://github.com/kimai/kimai/assets/156685774/f5ac4ba8-a566-4cf1-bee3-7a31f62ecb94)

**Comment by kevinpapst** [comment]
Please re-post here: https://github.com/kevinpapst/kimai-plugins/issues
