### ISSUE TITLE
Kimai looks strange after fresh install. No images/icons. Function missing

### ISSUE THREAD

**Issue by macbef** [kimai/kimai#4568]
### Describe the issue

Hello,
after a fresh installation (and after upgrading from 1.30 to 2.9 as well)  kimai is not working any more the way it used to.
Funny thing is, I can log in with a new admin user and I can see the dashboard, but all images/icons seem to be missing and the "administration" and "System" menu items are not working (ROLE_SUPER_ADMIN is set). I can't even log out.

I'm running on a strato webspace (and I have used the /opt/RZphp81/bin/php-cli workaround).

In the past, I had V1.30 running on the same webspace without any problems.
Any suggestions? Is this an issue with Strato?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.9

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/26661902/b219b2ce-b557-4875-bc35-7fec79a47dc8)

**Comment by kevinpapst** [comment]
You have likely public/ in the URL, which is now allowed. 
This is a hosting issue, not a bug.

Also: you have NOT searched, because this issue was discussed multiple times.

**Comment by macbef** [comment]
Thanks for the fast response. Wow!
But I don't have public in the URL. I created a softlink with something like 'ln -s kimai/public timesheet' and I'm pointing the browser to .../timesheet
This used to work with 1.30.
I just re-installed 1.30 and that's running with my database-backup
