### ISSUE TITLE
Assignment of n customers to one project

### ISSUE THREAD

**Issue by markus7777777** [kimai/kimai#4573]
### Describe the problem

Hi,

Is it possible to assign more than one customer to a project in Kimai? 

### Describe the solution you'd like

Currently, I couldn't find a way. If not, could this feature be considered for future updates? It would greatly enhance flexibility for users handling projects involving multiple customers.

### Describe alternatives you've considered

Currently, we are utilizing custom fields. The issue arises when searching for a second or third customer; we are unsure whether to filter for the custom field or simply use "customer."

**Comment by kevinpapst** [comment]
No, not possible.
Thank you for sharing your idea, but that feature request will not be taken into account. 
Use tags instead.
The custom fields plugin has a feature called auto-tagging.
You can configure that a timesheet which is created against Project A, automatically recives certain tags.
Create tags: Customer A, Customer B, Customer C
Create project A
Create timesheet for project A, timsheet will automatically have the tags: Customer A, Customer B, Customer C

**Comment by markus7777777** [comment]
Thanks for response. A workaround would be to improve the filter GUI. Is it planned to include meta fields in the search bar? Until now its necessary to know the **internal title** of the metafield.

_METAFIELD:searchterm_

**Comment by CorentinWicht** [comment]
> No, not possible. Thank you for sharing your idea, but that feature request will not be taken into account. Use tags instead. The custom fields plugin has a feature called auto-tagging. You can configure that a timesheet which is created against Project A, automatically recives certain tags. Create tags: Customer A, Customer B, Customer C Create project A Create timesheet for project A, timsheet will automatically have the tags: Customer A, Customer B, Customer C

I agree with @markus7777777 that this feature would be a game changer. We also have many projects which are not linked to only one customer and this makes Kimai unusable in these cases...
I am having a hard time understand your reply @kevinpapst. I mean what would be the point to define Customers as Tags when they are already defined in the "Customer" category? That sounds like a very messy solution.

**Comment by kevinpapst** [comment]
> and this makes Kimai unusable in these cases...

🤷 That's why so many different software systems exists.

> That sounds like a very messy solution.

In your eyes. For others it is a proven workaround. 

Your way of communication and on top using a ping in an already closed topic shows that you only care about yourself. 

That's the point where a topic becomes locked...
