### ISSUE TITLE
Plugin/TaskManagementBundle: add additional sort of 'Tasks' -> t.id 

### ISSUE THREAD

**Issue by acaliebe** [kimai/kimai#4574]
### Describe the problem

Hello,
I often have to search for a task that is already marked as 'Completed', when I open 'tasks' I unfortunately don't have the sorting by 't.id' - so just 'newest first', as a task doesn't have to have a start/end time at this point. 

### Describe the solution you'd like

It would be great if the sorting criterion ID were included in one of the next versions. 

As a quick test, I changed the $orderBy='endsort' to $orderBy='t.id' in var/plugins/TaskManagementBundle/Repository/TaskRepository.php for this purpose.

### Describe alternatives you've considered

```
--- kimai.original/var/plugins/TaskManagementBundle/Repository/TaskRepository.php  2024-01-18 13:57:30.806894624 +0100
+++ kimai.testing/var/plugins/TaskManagementBundle/Repository/TaskRepository.php      2024-01-18 14:07:22.257200822 +0100
@@ -321,12 +321,14 @@
                 $orderBy = 'team.name';
                 break;
             case 'end':
-                $orderBy = 'endSort';
+               /* (quickfix/testing) Use 'order by END' as 'order by ID' to show the last created entries first  */
+               $orderBy = 't.id';
+                /* $orderBy = 'endSort';
                 if ($query->getOrder() === TaskQuery::ORDER_ASC) {
                     $qb->addSelect('COALESCE(t.end, \'9999-12-31 23:59:59\') AS HIDDEN endSort');
                 } else {
                     $qb->addSelect('COALESCE(t.end, \'0000-12-31 23:59:59\') AS HIDDEN endSort');
-                }
+                } */
                 break;
             default:
                 $orderBy = 't.' . $orderBy;
```

**Comment by kevinpapst** [comment]
Please re-post here: https://github.com/kevinpapst/kimai-plugins/issues

**Comment by acaliebe** [comment]
re-posted at https://github.com/kevinpapst/kimai-plugins/issues/124
