### ISSUE TITLE
Feature Request - change start/end date according to end/start date

### ISSUE THREAD

**Issue by data-blade** [kimai/kimai#459]
the date fields in kimai's header (ts_in, ts_out) do not adjust automatically when
- a start date is selected that postdates the active end date (end date should change to new start date)
- an end date is selected that predates the active start date (start date should change to new end date)

this puzzled me because it is already implemented (and very useful) for the 'edit entry' pop up (start_day, end_day).

what do you think?

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/issues/1291
