### ISSUE TITLE
Approval for Absences

### ISSUE THREAD

**Issue by DaveeeKR** [kimai/kimai#4593]
### Describe the problem

Approval for Absences in WorkContractBundle

### Describe the solution you'd like

Additional menu for Admin/Team-Leader, where absences can be approved or rejected.

**Comment by kevinpapst** [comment]
Thanks!

Issues for paid plugin belong here: https://github.com/kevinpapst/kimai-plugins

In that case you can post it again, if it does not yet exists, but it is already on the roadmap, so there is no need.
Please read https://www.kimai.org/store/controlling.html (scroll down to Roadmap and ideas).
