### ISSUE TITLE
Balance of working time

### ISSUE THREAD

**Issue by DaveeeKR** [kimai/kimai#4594]
### Describe the problem

Balance of the extra time reduce when submitting new "Time Off". Current balance does not change if you submit new time off.

### Describe the solution you'd like

When user have Balance of the working time possitive for example: 14h, and he submit new time off of the 2h. New balance of Working time should be 12h.

### Screenshots

![image](https://github.com/kimai/kimai/assets/129747290/2cf09d7f-cb34-4db7-8f96-40012ecc6d63)
![image](https://github.com/kimai/kimai/assets/129747290/bf208260-5ba2-4eb5-b7b8-1793ab0ae4d2)
![image](https://github.com/kimai/kimai/assets/129747290/d3d421f4-beed-4332-b552-43c81a7a01b8)

**Comment by kevinpapst** [comment]
Time-Off goes down, when the user does not track the working time for that day.

As written in the docs: https://www.kimai.org/documentation/absence.html

Adding a Time-Off entry is for informational purpose and it will show up in the Absence calendar (which is not yet existing).
But it will not reduce the working-time-account balance by itself.

**Comment by DaveeeKR** [comment]
I didn't understand what You mean in first sentence. 

When user is able to see reduced balance of the overtime?

I saw Absence calendar in the roadmap, have you planned about adding this in near future?

**Comment by kevinpapst** [comment]
> Time-Off goes down, when the user does not track the working time for that day.

If you book today (29 January) an time-off for february 3, then this entry does NOT change your balance.
But on Feb 2, you only log 6 instead of 8 hours. This will lower your balance.
