### ISSUE TITLE
Nginx failed to connect error 111

### ISSUE THREAD

**Issue by nrgbistro** [kimai/kimai#4597]
### Describe the problem

After a day or two of using my Kimai instance, I get this error and cannot connect to the webUI.

Here is the error message when I try to connect locally to the nginx server:

`2024/01/29 18:42:27 [error] 7#7: *9758 connect() failed (111: Connection refused) while connecting to upstream, client: 100.97.60.12, server: nginx, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.176.5:9000", host: "nrgserver:8001"`

After restarting JUST the nginx container, the application works again as expected. Could this be an issue with the nginx container specified in the official production docker compose? Please let me know if you need any additional information to help debug, I look forward to a fix for this problem as Kimai is currently unusable for me.

### Describe your setup and add your Docker compose file (redact your credentials)

Unraid: 6.12.6
Docker: 20.10.24, build 297e128
Docker compose: 2.21.0

```version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=${SQL_PASS}
      - MYSQL_ROOT_PASSWORD=${SQL_PASS}
    volumes:
      - /mnt/user/appdata/kimai/mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    ports:
      - 8001:80
    volumes:
      - /mnt/user/appdata/kimai/public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:latest
    environment:
      - ADMINMAIL=xxxxxxxxxxxxx@xxxxxxxxx.com
      - ADMINPASS=${KIMAI_PASS}
      - DATABASE_URL=mysql://kimaiuser:${SQL_PASS}@sqldb/kimai?charset=utf8mb4&serverVersion=5.7.40
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    volumes:
      - /mnt/user/appdata/kimai/public:/opt/kimai/public
      - /mnt/user/appdata/kimai/data:/opt/kimai/var/data
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8031:80
    environment:
      - PMA_ARBITRARY=1

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8030:8080
    volumes:
      - ./swagger.json:/swagger.json
    environment:
      - SWAGGER_JSON=/swagger.json```

### Command used to run the container

started via unraid docker compose interface, which should be docker-compose up -d

**Comment by kevinpapst** [comment]
This `tobybatch/nginx-fpm-reverse-proxy` is not supported in production. 

See docs: 
<img width="1345" alt="Bildschirmfoto 2024-01-29 um 20 05 06" src="https://github.com/kimai/kimai/assets/533162/75b6adf1-e1b1-4c0b-af2a-39c27cdf15a5">

https://www.kimai.org/documentation/docker-compose.html#fpm-and-nginx

FPM and nginx is ONLY for people who already have a reverse proxy, it just doesn't make sense to run 3 container, if you can run 2 (Apache prod).

**Comment by nrgbistro** [comment]
Whoops, didn't see that warning when I found the docker compose example I used. For anyone encountering this issue in the future, I removed the nginx container entirely, set the main Kimai container's image to `kimai/kimai2:apache-prod`, and opened port `8001:8001`. Thank you for the help @kevinpapst!
