### ISSUE TITLE
Show Tags in Export-List

### ISSUE THREAD

**Issue by xstable** [kimai/kimai#4603]
### Describe the problem

I use Tags to differ estimates between different Departments (HR / IT).
It is very handy that I'm able to filter between those Tags in the Export-Dialog.

### Describe the solution you'd like

What's missing is to show the Tags as Column in the result-list.

![image](https://github.com/kimai/kimai/assets/1778068/55c65809-b0cc-44b3-8071-058896cb24d5)

# Why is that needed?
Currently I can filter for one or more Tags, but:  
1.  I can not see which entry don't have any Tag assigned.
2. If I filtered for more then one Tag, it would be handy to see which entry is assigned to which tag

**Comment by kevinpapst** [comment]
Accepted 👍

**Comment by suther** [comment]
:heart:  :100:  
Thx. That's a great feature
