### ISSUE TITLE
Team needs Customer Access to see a project

### ISSUE THREAD

**Issue by kosmoskosmos-team** [kimai/kimai#4613]
### Describe the issue

When I give a team access to a single project, the team members still can't see the project. I have to give access to the whole customer instead, but then the team sees all projects of that customer.
As far as I understand the documentation, this shouldn't be necessary. Any hints?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.11.0

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

Unknown

**Comment by kevinpapst** [comment]
That only happens if you have limited access to the customer.
If you assign one team to the customer, no-one else besides that team will see the customer.
General rule of thumb: do not mix team assignments between customer and project, only use one level.

Please use https://www.kimai.cloud/support-center/request to create a new support case in the future.

**Comment by kosmoskosmos-team** [comment]
Thanks for your fast response. I think it's a bit cumbersome having to assign all projects individually, only to get limited acces for single users/teams.
Maybe it's a feature request ;)

Will create an account in the support-center. Didn't know it exists.

**Comment by kevinpapst** [comment]
Permission structure worked for years for all customer, so I think there is a misunderstanding somewhere (maybe on my end). Lets share some screenshots afterward.

Don't create an account if you are not the owner.
Simply send an email to support@kimai.cloud from your domain.

**Comment by kevinpapst** [comment]
Closing here
