### ISSUE TITLE
Error 500 loading Invoice (init.php)

### ISSUE THREAD

**Issue by fnorbenden** [kimai/kimai#463]
php 5.3
apache 2.2
Kimai 9.3 RC

I attempt to access the invoice tab on a fresh install and it sits on the loading bar, never loads.

Firefox (35) web inspector: 

GET http://****/kimai/extensions/ki_invoice/init.php [HTTP/1.0 500 Internal Server Error 3ms]

httpd error_log:

[Mon Feb 09 12:23:23 2015] [error] [client 192.168.5.201] PHP Parse error:  syntax error, unexpected '[' in /var/www/kimai/extensions/ki_invoice/init.php on line 41, referer: http://******/kimai/core/kimai.php

Everything else works. I saw a resolved similar bug (https://github.com/kimai/kimai/issues/377#issuecomment-42188496), but this appears to be different behavior post-fix. I cannot upgrade php from 5.3 due to my middleware provider.

**Comment by ServiusHack** [comment]
I don't see how this issue differs from #377 which was fixed by 2535941deee73b90a81fbcc69e2514dd5ce70f28. Feel free to comment and reopen this issue if the fix doesn't work for you.

**Comment by huguesmax** [comment]
Open file extensions/ki_invoice/init.php
replace line 41 by 

$projects = $database->get_projects_by_customer(array_keys($view->customers[0]), $kga['user']['groups']);

this is small mistake
bye
Hugues.
