### ISSUE TITLE
Time-tracking for a customer without project

### ISSUE THREAD

**Issue by CorentinWicht** [kimai/kimai#4643]
### Describe the problem

I would like to associate a time-tracking to a customer which is not linked to any project but this can't be done because the "project" field is mandatory (while the "customer" field isn't):
![image](https://github.com/kimai/kimai/assets/52161904/1e72b2e4-547a-4225-856d-daf80c7e1fa7)

### Describe the solution you'd like

Be able to start a time-tracking for a customer not linked to any project.
It would be good to be able to define in the parameters whether the "project" and the "customer" field should be mandatory or not.

### Describe alternatives you've considered

Associate customers to a "fake" project to bypass the fact that the "project" field is mandatory.
This alternative is not really good though...

**Comment by kevinpapst** [comment]
Just think of these timesheets as being connected to the project "customer support".

I understand what you are saying, I have the same feeling with some customers ... but it won't be changed. It's way too complicated and problematic to change that, the entire codebase relies on the project being existent.
