### ISSUE TITLE
Pull-down-menu on project details does not adjust to windows size

### ISSUE THREAD

**Issue by Phi-Sch** [kimai/kimai#4651]
### Describe the issue

The pull-down-menu on project details does not adjust to windows size and stays very small

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.10.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/160625781/9345aad0-cbb7-424d-a262-6e9562379961)

**Comment by kevinpapst** [comment]
As this is a JS library and not a native dropdown field the sizing is not as easy as it could...
Anyway, the size is limited on purpose: that field would look really strange if it would stretch to full-size.
Closing as I do not have any plans to change it
