### ISSUE TITLE
en_US locale configuration may be missing?

### ISSUE THREAD

**Issue by sj-patel** [kimai/kimai#4652]
### Describe the issue

Setting user's locale to English (United States) renders dates incorrectly (e.g. 22/02/2024, instead of 02/22/2024). Looking at the locales.php, I did not find en_US configured. 

Thank you!

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.11.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/109171297/437a7a57-a8a8-41e4-a21b-08951fd66a23)

**Comment by kevinpapst** [comment]
Only unique locales are added, `en_US` is not needed, as it shares the same configuration than others.

... edit: removed non-sense ...

**Comment by kevinpapst** [comment]
Wait, you are right, something is odd.
United states shouldn't be in there, the list looks wrong.
I'll check.
