### ISSUE TITLE
TimeTracker

### ISSUE THREAD

**Issue by inanutshellus** [kimai/kimai#466]
Ok, this is definitely not a bug or even feature request, sorry, but your forums have disabled registration, so I can't figure out where else to put this.

This isn't a question about Kimai, but about [TimeTracker](https://itunes.apple.com/at/app/timetracker/id721776102?mt=12), the OSX app you have listed on your [Kimai Apps](http://www.kimai.org/apps/) page. It doesn't work at all, but I suspect it's just a bad build rather than broken software.

`TimeTracker`, when started on the command line(1), says "`No credentials in keychain!`" and exits, but it didn't give me the chance to put in credentials! I dug into the app folder and found and ran the `TimeTrackerLoginHelper` app on command line(2) from within the `TimeTracker` app, and it blows up because it's missing an executable named `LaunchAtLoginApp`. That file simply doesn't exist! Could it just be a bad build?

Anyway, since I assume the Kimai people didn't make TimeTracker, I don't think this is the right way to ask about the problem, but perhaps you know who I could talk to to get a new build?

 (1) Running TimeTracker from command line gives some interesting errors:

    $ /Applications/TimeTracker.app/Contents/MacOS/TimeTracker
    TimeTracker[18546:707] No credentials in keychain!
    TimeTracker[18546:707] Error Domain=com.samsoffes.sskeychain Code=-25300 "The operation couldn’t be completed. (com.samsoffes.sskeychain error -25300.)"
    TimeTracker[18546:707] Launcher 'com.blockhausmedia.timetracker.helper' is not configured to start at login

(2) Running TimeTrackerLoginHelper from command line shows we're missing an executable!

    $ /Applications/TimeTracker.app/Contents/Library/LoginItems/TimeTrackerLoginHelper.app/MacOS/TimeTrackerLoginHelper
    TimeTrackerLoginHelper[18534:707] KimaiLoginHelper app is about to try launching Kimai
    TimeTrackerLoginHelper[18534:707] Trying to launch Kimai application binary at path /Applications/TimeTracker.app/Contents/MacOS/LaunchAtLoginApp
    TimeTrackerLoginHelper[18534:707] LSOpenFromURLSpec() returned -43 for application /Applications/TimeTracker.app/Contents/MacOS/LaunchAtLoginApp path (null).
    TimeTrackerLoginHelper[18534:707] Launching Kimai failed!

**Comment by simonschaufi** [comment]
this seems to be the right place to report bugs: https://blockhaus-timetracker.uservoice.com/
