### ISSUE TITLE
Description column in "My times"/Timesheet pages

### ISSUE THREAD

**Issue by sonroyaalmerol** [kimai/kimai#4662]
### Describe the problem

Currently, the columns present are date, begin, end, duration, customer, project, and activity. When a user is not allowed to edit a certain timesheet, they are not able to view the description as it disables the modal from appearing when the row from the table is clicked.

### Describe the solution you'd like

Options:
- It would be nice if the description is in the table as another column
- Have a more flexible way of choosing which columns are presented in the table but I'm guessing that would be complicated
- Allow people to click the row and show the "Edit record" modal but prevent them from editing the fields in the modal when editing permissions are disabled

**Comment by kevinpapst** [comment]
I'll share secret with you, but psssss please don't tell anyone else:
![image](https://github.com/kimai/kimai/assets/533162/b46cbef4-994a-45c4-a246-eddaa64dd38c)
