### ISSUE TITLE
Display Date and Time in US Format

### ISSUE THREAD

**Issue by nmpdan** [kimai/kimai#467]
Hey there. I've been asked to implement Kimai for a client and all has gone very well with the install.

They have asked if the date and time formatting can be shown in as US formatted style. I found some old information relating to 0.7.x releases but they don't appear to apply to the 0.9.x release.

Is this possible with the current version stable version, 0.9.2?

Thanks all.

**Comment by ServiusHack** [comment]
Have a look at the advanced tab in the admin extension. In 0.9.3 there are some fields to set date and time formats. I think they are in 0.9.2 as well.

**Comment by nmpdan** [comment]
I tottaly missed that at the bottom of the screen. Doh!

Thank you for such a quick reply!

Is it possible to show the times in the 12 hour AM/PM format at all?

**Comment by ServiusHack** [comment]
The times in the table? Unfortunately not. That's hardcoded in _extensions/ki_timesheets/templates/zef.tpl_.

**Comment by nmpdan** [comment]
OK. Thanks. I'll let them know.

Again, appreciate the quick reply.
