### ISSUE TITLE
Sort order of project and global activities

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kimai/kimai#4674]
### Describe the problem

In Kimai 1.x, the global activites used to be sorted below the project activities within the activity selector.
In Kimai 2.x, this behavior changed: global activities are shown first and project activities below.
I wonder why this had been changed?
For us, the behavior in Kimai 1.x was perfect. A project specific activity seems to be of higher importance than a global activity. In our case the default is to use a project activity. We have some global activities like "presales" or "goodwill" that can be selected instead.

### Describe the solution you'd like

As the sort order had been changed, there are possibly use cases, where this order is preferred.
I'd wish a setting to change the sort order.

### Describe alternatives you've considered

Don't know of any.

**Comment by rbuehler-teletrend** [comment]
It's been a while ago I posted this. I wonder what your thoughts are on this @kevinpapst ?
Or basically, what was the intention to reverse the order of global and project activities?

**Comment by kevinpapst** [comment]
Appreciate your feedback 👍 

You are entirely correct, this is one of the small but annoying frictions that need to be eliminated.
This was not on purpose, just accidentally.

Order will change to "project specific activities first, then global ones" with the next release.

**Comment by rbuehler-teletrend** [comment]
Very appreciated, thank you! :)
