### ISSUE TITLE
Ability to assign an activity to multiple projects

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kimai/kimai#4675]
### Describe the problem

Activities can be either global or assigned to one single project.
In certain cases it would be great to assign an activity to several projects (but not to all).
We often use activities in connection with different hourly rates. So let's say we have a number of different hourly rates and for project X we've got two tasks, one with hourly rate Y and another with hourly rate Z.

### Describe the solution you'd like

Today we need to create these (often same) activities for every project.
For us it would be much easier if we could assign activities to multiple projects.

### Describe alternatives you've considered

An alternative is to have them as global activities, but this gives way too many selection options in the timesheets and the people actually working on the projects would need to do research which activity is the correct one to select.
The other alternative is to create activities for every project as we used to do it.

**Comment by kevinpapst** [comment]
Sorry, but I am going to close this one immediately.
The structure is a 1 project to N activities, So project is a nullable foreign key on the activity.

This is not going to be changed anytime soon (I'm intrigued to say never).

Close as wontfix.
