### ISSUE TITLE
HTML tags in company name field

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kimai/kimai#4676]
### Describe the issue

According to https://www.kimai.org/documentation/configurations.html#my-company one should be able to use a limited set of HTML code tags within the company name field, e.g. to display an image instead of plain text.
This was working in Kimai 1.x, but no more in Kimai 2.x.
Although by leaving the company field empty, it is now automatically using the image from the logo URL field. But due to background color differences between the login screen (light) and the menu bar (dark), I would need to use two different styles of our logo.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.12.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Logfile

n/a

**Comment by kevinpapst** [comment]
Thanks, you found some outdated documentation. I adjusted it: the company name cannot include HTML any longer.

You should be able to replace the image with custom CSS or simply apply a color gradient to it.
Not sure if that needs handling, maybe remove the image from the navbar completely?

**Comment by rbuehler-teletrend** [comment]
Thanks for the hint using custom CSS plugin - works perfectly!
