### ISSUE TITLE
Kimai forgets time format when closing and re-opening browser

### ISSUE THREAD

**Issue by cresh** [kimai/kimai#4677]
### Describe the issue

I have set my language preference to "English (Germany)". When I login to Kimai, I see the dates formatted as expected and times formatted as 24-hours clock as I expect:

<img width="424" alt="Screenshot 2024-03-04 at 21 34 28" src="https://github.com/kimai/kimai/assets/48236/cd565fee-4e3f-4e79-b19c-e9b3aab88f2c">

When I close my browser and re-open it, I am still logged in but Kimai has forgotten that it should render times in 24-hours format:

<img width="427" alt="Screenshot 2024-03-04 at 21 35 25" src="https://github.com/kimai/kimai/assets/48236/276c40cb-43b5-4218-a3c9-87a11509d510">

To get the date format and 24-hours time format back, I have to log out of Kimai and log back in.

I would expect that Kimai always shows 24-hours clocks.

Arc Browser Version 1.32.0 (46908) with Chromium Engine Version 122.0.6261.94 on macOS Sonoma 14.3.1 (23D60) on Apple M1

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.12.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

### Logfile

Missing logfile

**Comment by kevinpapst** [comment]
Check the URL in your browser, probably a bookmark with the wrong locale in the URL?

**Comment by cresh** [comment]
That was the problem! I've bookmarked my Kimai instance before I've adjusted the locale settings and failed to realize that it is encoded in the URL. Thank you very much for your great support!
