### ISSUE TITLE
Allow more than 2 decimal places for hourly rate to help with day rate rounding

### ISSUE THREAD

**Issue by iDontWantAUsername** [kimai/kimai#4678]
### Describe the problem

This might be a bit of a specific use case but i will detail in case it will be considered.

I was hoping to use Kimai for time keeping and generating the invoices for my contracting work but the generated invoices all have rounding issues due to my rate being a day rate (based on 8 hour day).

I have entered the rate in Kimai as my day rate / 8 which as my day rate is an odd number gives a 3 decimal places e.g. 105/8 = 13.125, this is rounded to 13.13 in all the hourly rate input fields.

When i enter my individual activities into the time logger this means that the rate for an 8 hour day actually comes out as 105.04 which is incorrect for my case.

I have manually updated the hourly rates and the calculated activity rates in the database to a 3 decimal place number and the overall calculations are then correct table `timesheet.hourly_rate` and `timesheet.rate`. It seems that the backend code can handle the 3 decimal places but this is being rounded in the frontend prior to being stored in the DB?

### Describe the solution you'd like

It would be great if the hourly_rate and all derived columns allowed more than 2 decimal places, any the rounding can then take place as the invoice is generated rather than at each prior step resulting in an incorrect overall calculation in the invoice. This may require bankers rounding for the invoice generation as well.

### Describe alternatives you've considered

Being above to override the rates may work but this does slightly defeat the point if the software to make life easier.

**Comment by kevinpapst** [comment]
Time with base 60 and money with base 100 is not fully compatible. No matter what you do, you will at some point see rounding issues if you e.g. log exactly by the minute and not rounding to 15 minute durations.

You could try to change this form type: https://github.com/kimai/kimai/blob/main/src/Form/Type/HourlyRateType.php
And add the scale option: https://symfony.com/doc/current/reference/forms/types/money.html#scale

So replace
https://github.com/kimai/kimai/blob/e293d62aa1f7a87bab354c82d54c257959f43f53/src/Form/Type/HourlyRateType.php#L29-L30
with 
```php
 'required' => false, 
 'label' => 'hourlyRate', 
 'scale' => 3,
```

**Comment by iDontWantAUsername** [comment]
That seems to work for the Hourly Rate on the timesheet, thank you.

Is there a datatype definition for the Projects Rate?

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/blob/main/src/Form/EntityFormTrait.php#L33

**Comment by iDontWantAUsername** [comment]
That seems to be the Budget, i am after the Rate here:
![image](https://github.com/kimai/kimai/assets/13792942/4c38ef1e-43e7-4107-b5df-235a00f19548)

This is stored in `projects_rates.rate`

Thanks again for your help so far

**Comment by iDontWantAUsername** [comment]
Ignore that, i found it, it is in https://github.com/kimai/kimai/blob/main/src/Form/AbstractRateForm.php#L37
