### ISSUE TITLE
Kimai invoice reverse task order

### ISSUE THREAD

**Issue by Devoteq** [kimai/kimai#468]
The standard task order for the kimai invoice extension starts with the most recent date and ends with the least recent date. 
My problem is that we need this the other way around, so start with the least recent task date and end with the most recent task date. So the task dates should be chronological. 

With older versions of the print.php i was able to reverse this, but so far i cant figure it out with the most recent version of kimai.

**Comment by kevinpapst** [comment]
Hey @Devoteq 
I added the requested feature into the UI with the linked Pull Request.
This will be merged within the next days.
Once this ticket is closed, it will be available in the latest "developer build" AKA the master.
