### ISSUE TITLE
Calendar Week view showing date in American format i.e. 3/14 instead of 14/3

### ISSUE THREAD

**Issue by iDontWantAUsername** [kimai/kimai#4684]
### Describe the issue

In calendar week view the dates are showing in American format instead of the expected Locale in this case English (United Kingdom) or English (Australian).
![image](https://github.com/kimai/kimai/assets/13792942/af1fdcfd-c615-42d1-aadf-41d5214ec345)

Dates elsewhere are all showing in the proper format e.g 12/3

This could be related to #4653 but i am not sure, please close and merge if they are the same.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.12.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

### Screenshots

![image](https://github.com/kimai/kimai/assets/13792942/af1fdcfd-c615-42d1-aadf-41d5214ec345)

**Comment by kevinpapst** [comment]
Which locales did you configure in the user profile?

**Comment by iDontWantAUsername** [comment]
Language is English with English (United Kingdom), I've tried English (Australian) too:

![Screenshot_20240308-085355](https://github.com/kimai/kimai/assets/13792942/a4afc118-47bd-4a1a-b2bd-5b7c97184337)
