### ISSUE TITLE
Yes/no checkbox values not correctly displayed on (project) overview page

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kimai/kimai#4686]
### Describe the issue

For projects created in Kimai 2, yes/no checkbox values are not correctly displayed on (project) overview page.
"No" values are dismissed, "Yes" values are shown. If "Yes" value is changed back to "No" it disappears again.
They are correctly shown on project detail page.

In the attached picture, the line missing the "No" values is newly created in Kimai 2, other lines have been created in Kimai 1.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.12.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![grafik](https://github.com/kimai/kimai/assets/54700498/762127f5-b189-45ea-b54e-cbc650ec9c94)

**Comment by kevinpapst** [comment]
I can confirm the issue. 
And I found the place of origin. Just can't remember why I added it... will need some more testing, but is planned for the next release.
