### ISSUE TITLE
How to fully delete, or reactivate deleted, users?

### ISSUE THREAD

**Issue by brylie** [kimai/kimai#469]
We have deleted several users from Kimai, and they show up when we click "Show deleted users" as expected. However, we would like to fully delete these users, or reactivate them, so that we can use their usernames. How can we fully delete users, or reactivate them?

**Comment by ServiusHack** [comment]
Kimai currently does not offer this in the user interface.

Reactivating users could be easily added.

Fully deleting users is more problematic since timesheet entries still reference that user. So either we have timesheet entries without an associated user or these need to be deleted as well.

**Comment by kevinpapst** [comment]
In the master branch isn now the new feature to reactivate "trashed" users.
Upon finally deleting the user we empty more db tables, but keep expenses and timesheet entries.
