### ISSUE TITLE
[ERROR] Cannot load resource...

### ISSUE THREAD

**Issue by pylearn2030** [kimai/kimai#4698]
### Describe the issue

Currently, I got an error occurred while rebuilding PeriodInsertBundle plugin 
++++++++
Rebuilding your cache, please be patient ...
// Clearing the cache for the prod environment with debug
// false
[ERROR] Cannot load resource "../../Controller/". Make sure there is a loader supporting the "attribute" type.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [x] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

1.30.11

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![Error rebuilding PeriodInsertBundle](https://github.com/kimai/kimai/assets/162970815/4784f152-d83e-4fc4-b52a-9f2f6bc7f54a)

**Comment by kevinpapst** [comment]
> 1.30.11

Not supported any longer, upgrade!

> PeriodInsertBundle

You are trying to use a plugin for Kimai 2.x. That doesn't work.

**Comment by pylearn2030** [comment]
Thank you @kevinpapst !
I have updated to Kimai 2.0 and installed this plugin. It worked.
