### ISSUE TITLE
Weekly-Hours is blocked if lockdown is active in selected week

### ISSUE THREAD

**Issue by sj-patel** [kimai/kimai#4703]
### Describe the issue

With the following preconditions, a user is not able to create a timesheet:

**Preconditions**
1. create_own_timesheet is turned off for a user - to disable the start/stop button 
2. global lockdown period start/end has been configured in our case: lockdown start: epoch, end: last day of last month
3. **condition** The end of the month happens during the working week (for example: March 1st, 2024 happed on Friday)
4. The user uses Weekly Hours to create a timesheet.

Given the above conditions, when a user attempts to create a timesheet for days allowed (not blocked by lockdown settings), the user gets error messages for locked days for that week. (screenshot attached)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0 latest docker

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Screenshots

<img width="1247" alt="image" src="https://github.com/kimai/kimai/assets/109171297/5b669c3e-f805-4f29-98bf-8a27320dd900">

**Comment by kevinpapst** [comment]
This was fixed in one of the last releases. Please re-open if you still see the issue.
