### ISSUE TITLE
Base table or view not found: 1146 Table 'kimai_database.kimai2_ext_approval_overtime_history' doesn't exist

### ISSUE THREAD

**Issue by pylearn2030** [kimai/kimai#4704]
### Describe the issue

Dear,
I upgraded Kimai 1.30.0 to 2.5.0 successfully.
Currently, I got an error occurred while installing ApprovalBundle plugin.
++++++++++++++++++++++++++++++++++++++++++++++++++++++
CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai_database.kimai2_ext_approval_overtime_history' doesn't exist" at /var/www/html/kimai/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 49 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai_database.kimai2_ext_approval_overtime_history' doesn't exist at /var/www/html/kimai/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:49)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai_database.kimai2_ext_approval_overtime_history' doesn't exist at /var/www/html/kimai/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai_database.kimai2_ext_approval_overtime_history' doesn't exist at /var/www/html/kimai/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} []
++++++++++++++++++++++++++++++++++++++++++
It will occur the error "500 Something is wrong" when accessing to "Hours approval"
![image](https://github.com/kimai/kimai/assets/162970815/5998c860-d0d0-4078-b281-d841eb2e9cde)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.5.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Logfile

CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai_database.kimai2_ext_approval_overtime_history' doesn't exist" at /var/www/html/kimai/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 49 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai_database.kimai2_ext_approval_overtime_history' doesn't exist at /var/www/html/kimai/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:49)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai_database.kimai2_ext_approval_overtime_history' doesn't exist at /var/www/html/kimai/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai_database.kimai2_ext_approval_overtime_history' doesn't exist at /var/www/html/kimai/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} []

**Comment by kevinpapst** [comment]
This is not a bug. Open a discussion in the forum.

**Comment by pylearn2030** [comment]
Yes Kevin. I created this topic on discussion forum. Please help!
Thank you!
