### ISSUE TITLE
.env file secure

### ISSUE THREAD

**Issue by 0x7466** [kimai/kimai#4705]
### Describe the issue

Hi, I'm a huge fan of this project. Thanks for the great work!

Somehow, my email credentials for Kimai got compromised and quite some spam was sent.

Before I set the new password in the .env file, I want to assure that this doesn't happen anymore. Unfortunately, I don't have any logs that show how the credentials got leaked.

My guess was that the .env file in the public_html folder was somehow publicly accessible. However, I wasn't able to confirm that. I get an 404 if I try to access mykimaiserver.com/.env.

I'm also running on OpenLiteSpeed, which doesn't fully support .htaccess files. But since there are no .htaccess files in Kimai, this shouldn't be a problem right?

I'm a little stressed right now 😅

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.13.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
You environment MIGHT be compromised. 
There are dozens of possible ways how that could have happened.

The .env file is a normal part of every Symfony project. 
If you think there is a security issue in Symfony, open a bug there. 

You can open a discussion with more information about your environment and we can have a look at it. 
But I am closing here right away, because this is not a bug.

**Comment by 0x7466** [comment]
Ok, thanks! I'll take a deeper look if there are any other anomalies.

**Comment by kevinpapst** [comment]
I understand your feelings, but you did not share a lot of information:
> Somehow, my email credentials for Kimai got compromised and quite some spam was sent.

- Are your credentials only used by Kimai
- What kind of Spam
- How is your webserver setup exactly looking
- ...

All in all there is nothing I can do.


The only real known problem is, if you are running Kimai with the document root not pointing to public/
Which is clearly indicated in the docs, but sometimes overseen.

In that case all files can be read by the outside world. 
By default hidden files like .env should not shown by webservers (but I don't know the one you are using). 
But still there are other possible issues, like the var/cache/ folder, which could contain sensitive data as well.
