### ISSUE TITLE
Die E-Rechnung wird Pflicht in Deutschland

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#4724]
### Describe the problem

Die E-Rechnung wird ab 2025 obligatorisch.

## Ein PDF ist noch keine E-Rechnung

Als E-Rechnungen in diesem Sinne gelten nur Rechnungen, die der europäischen Norm EN 16931 entsprechen. Vereinfacht ausgedrückt muss den Rechnungen ein bestimmter XML-Datensatz beigefügt sein, der relevante Rechnungsdaten enthält und maschinell verarbeitet werden kann. In Deutschland erfüllen die Anforderungen unter anderem der XStandard oder das ZUGFeRD-Format ab Version 2.0.1.
Bei einer „normalen“ PDF-Rechnung handelt es sich also nicht um eine E-Rechnung.

Es besteht eine Übergangsfrist bis zum 31. Dezember 2026, so lange können noch Papierrechnungen oder normale PDF-Rechnungen versendet werden.

## Empfänger können E-Rechnungen verlangen

So lange solltest Du allerdings nicht warten. Mit Sicherheit werden einige Deiner Kund:innen auf dem neuen Format bestehen, so wie es Bundesbehörden und viele größere Unternehmen schon seit einiger Zeit tun.

Links:

- https://www.bmi.bund.de/DE/themen/moderne-verwaltung/verwaltungsmodernisierung/einfuehrung-e-rechnung/einfuehrung-e-rechnung-node.html
- https://www.youtube.com/watch?v=MSSEssx-akQ
- https://github.com/easybill/zugferd-php

### Describe the solution you'd like

Zusätzlich zu einer PDF sollte auch das notwendige XML generiert werden.

Eventuell kann diese PHP lib verwenden werden:

- https://github.com/easybill/zugferd-php

**Comment by kevinpapst** [comment]
Can you add your arguments and links here please: https://github.com/kimai/kimai/issues/1396
