### ISSUE TITLE
time error and once enter comment, project's "in" time and "out" time will change

### ISSUE THREAD

**Issue by chongwj** [kimai/kimai#474]
Hi All,
Now i'm facing a serious problem on timesheet system.

First problem is time error : 
cannot edit that time, h'm always show an negative hours and minutes
![timesheet1](https://cloud.githubusercontent.com/assets/11517689/6685097/d7c0476e-ccd1-11e4-95ed-928d2a75bd5f.png)
...please refer to picture (timesheet1.png) . thanks

No.2 , once i press edit buttom on indivual task, project's "in" and "out" will change.
Once i press the edit key and did not change edit entry panel anything then i click OK.The "In" and"Out" will auto change. Please refer to picture( timesheet2.png and timesheet3.png)
THANKS AND REGARDS
![timesheet2](https://cloud.githubusercontent.com/assets/11517689/6685284/5dfce48a-ccd3-11e4-83a0-8ebae9e063e9.png) 
![timesheet3](https://cloud.githubusercontent.com/assets/11517689/6685290/69fa5c2c-ccd3-11e4-8b64-7311cf1b96a4.png)

.

**Comment by ServiusHack** [comment]
I need some more information to help you with these problems.

What version of Kimai are you running?

What happens if you try to edit the entry with a negative duration? It should still open the edit dialog and allow you to change the start and end time.

Regarding your second problem: What is shown when you reload the page?

Are there any errors in temporary/logfile.txt or your PHP error log file?

**Comment by chongwj** [comment]
Hi ,
Glad to have your reply. :)
First problem
1,KIMAI Version :-
* 0.9.3.1384*

*2,If i try to edit the entry with negative duration...system will show
"The start time must be before the end time"*


*Second problem*

*1,What is shown when you reload the page :- No different2,*
*Are there any errors in temporary/logfile.txt or your PHP error log file?
:- think NO*
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> *[24.03.2015 13:10:06] login: admin as user[24.03.2015 13:10:07] Global
> role 1 gave true for ki_budget-access.[24.03.2015 13:10:07] Global role 1
> gave true for ki_expenses-access.[24.03.2015 13:10:07] Global role 1 gave
> true for ki_export-access.[24.03.2015 13:10:07] Global role 1 gave true for
> ki_invoice-access.[24.03.2015 13:10:07] Global role 1 gave true for
> ki_timesheet-access.[24.03.2015 13:10:07] Global role 1 gave true for
> adminPanel_extension-access.[24.03.2015 13:10:07] Global role 1 gave true
> for deb_ext-access.[24.03.2015 13:10:07] Global role 1 gave true for
> core-user-otherGroup-view.[24.03.2015 13:10:07] Global role 1 gave true for
> core-customer-otherGroup-add.[24.03.2015 13:10:07] Global role 1 gave true
> for core-customer-otherGroup-edit.[24.03.2015 13:10:07] Global role 1 gave
> true for core-project-otherGroup-add.[24.03.2015 13:10:07] Global role 1
> gave true for core-project-otherGroup-edit.[24.03.2015 13:10:07] Global
> role 1 gave true for core-activity-otherGroup-add.[24.03.2015 13:10:07]
> Global role 1 gave true for core-activity-otherGroup-edit.[24.03.2015
> 13:10:12] Global role 1 gave true for ki_timesheets-showRates.[24.03.2015
> 13:10:33] KSPI axAction (admin): add_edit_timeSheetEntry[24.03.2015
> 13:10:33] Global role 1 gave true for
> ki_timesheets-ownEntry-edit.[24.03.2015 13:10:33] Global role 1 gave true
> for ki_timesheets-otherEntry-otherGroup-edit.[24.03.2015 13:10:33] Global
> role 1 gave true for ki_timesheets-editRates.[24.03.2015 13:10:34] KSPI
> axAction (admin): reload_activities_options[24.03.2015 13:12:21] KSPI
> axAction (admin): add_edit_timeSheetEntry[24.03.2015 13:12:21] Global role
> 1 gave true for ki_timesheets-ownEntry-edit.[24.03.2015 13:12:21] Global
> role 1 gave true for ki_timesheets-otherEntry-otherGroup-edit.[24.03.2015
> 13:12:21] Global role 1 gave true for ki_timesheets-editRates.[24.03.2015
> 13:12:21] KSPI axAction (admin): reload_activities_options[24.03.2015
> 13:12:23] KSPI axAction (admin): add_edit_timeSheetEntry[24.03.2015
> 13:12:23] Global role 1 gave true for
> ki_timesheets-ownEntry-edit.[24.03.2015 13:12:23] Global role 1 gave true
> for ki_timesheets-editRates.[24.03.2015 13:12:23] Global role 1 gave true
> for ki_timesheets-ownEntry-edit.[24.03.2015 13:12:23] timeEntry_edit:
> 189[24.03.2015 13:12:23] KSPI axAction (admin): reload_timeSheet[24.03.2015
> 13:12:23] Global role 1 gave true for ki_timesheets-showRates.[24.03.2015
> 13:12:28] Global role 1 gave true for ki_budget-access.[24.03.2015
> 13:12:28] Global role 1 gave true for ki_expenses-access.[24.03.2015
> 13:12:28] Global role 1 gave true for ki_export-access.[24.03.2015
> 13:12:28] Global role 1 gave true for ki_invoice-access.[24.03.2015
> 13:12:28] Global role 1 gave true for ki_timesheet-access.[24.03.2015
> 13:12:28] Global role 1 gave true for
> adminPanel_extension-access.[24.03.2015 13:12:28] Global role 1 gave true
> for deb_ext-access.[24.03.2015 13:12:28] Global role 1 gave true for
> core-user-otherGroup-view.[24.03.2015 13:12:28] Global role 1 gave true for
> core-customer-otherGroup-add.[24.03.2015 13:12:28] Global role 1 gave true
> for core-customer-otherGroup-edit.[24.03.2015 13:12:28] Global role 1 gave
> true for core-project-otherGroup-add.[24.03.2015 13:12:28] Global role 1
> gave true for core-project-otherGroup-edit.[24.03.2015 13:12:28] Global
> role 1 gave true for core-activity-otherGroup-add.[24.03.2015 13:12:28]
> Global role 1 gave true for core-activity-otherGroup-edit.[24.03.2015
> 13:12:33] Global role 1 gave true for ki_timesheets-showRates.[24.03.2015
> 13:12:35] KSPI axAction (admin): add_edit_timeSheetEntry[24.03.2015
> 13:12:35] Global role 1 gave true for
> ki_timesheets-ownEntry-edit.[24.03.2015 13:12:35] Global role 1 gave true
> for ki_timesheets-otherEntry-otherGroup-edit.[24.03.2015 13:12:35] Global
> role 1 gave true for ki_timesheets-editRates.[24.03.2015 13:12:36] KSPI
> axAction (admin): reload_activities_options[24.03.2015 13:12:37] KSPI
> axAction (admin): add_edit_timeSheetEntry[24.03.2015 13:12:37] Global role
> 1 gave true for ki_timesheets-ownEntry-edit.[24.03.2015 13:12:37] Global
> role 1 gave true for ki_timesheets-editRates.[24.03.2015 13:12:37] Global
> role 1 gave true for ki_timesheets-ownEntry-edit.[24.03.2015 13:12:37]
> timeEntry_edit: 189[24.03.2015 13:12:38] KSPI axAction (admin):
> reload_timeSheet[24.03.2015 13:12:38] Global role 1 gave true for
> ki_timesheets-showRates.[24.03.2015 13:12:39] Global role 1 gave true for
> ki_budget-access.[24.03.2015 13:12:39] Global role 1 gave true for
> ki_expenses-access.[24.03.2015 13:12:39] Global role 1 gave true for
> ki_export-access.[24.03.2015 13:12:39] Global role 1 gave true for
> ki_invoice-access.[24.03.2015 13:12:39] Global role 1 gave true for
> ki_timesheet-access.[24.03.2015 13:12:39] Global role 1 gave true for
> adminPanel_extension-access.[24.03.2015 13:12:39] Global role 1 gave true
> for deb_ext-access.[24.03.2015 13:12:39] Global role 1 gave true for
> core-user-otherGroup-view.[24.03.2015 13:12:39] Global role 1 gave true for
> core-customer-otherGroup-add.[24.03.2015 13:12:39] Global role 1 gave true
> for core-customer-otherGroup-edit.[24.03.2015 13:12:39] Global role 1 gave
> true for core-project-otherGroup-add.[24.03.2015 13:12:39] Global role 1
> gave true for core-project-otherGroup-edit.[24.03.2015 13:12:39] Global
> role 1 gave true for core-activity-otherGroup-add.[24.03.2015 13:12:39]
> Global role 1 gave true for core-activity-otherGroup-edit.[24.03.2015
> 13:12:44] Global role 1 gave true for ki_timesheets-showRates.[24.03.2015
> 13:12:49] KSPI axAction (admin): add_edit_timeSheetEntry[24.03.2015
> 13:12:49] Global role 1 gave true for
> ki_timesheets-ownEntry-edit.[24.03.2015 13:12:49] Global role 1 gave true
> for ki_timesheets-otherEntry-otherGroup-edit.[24.03.2015 13:12:49] Global
> role 1 gave true for ki_timesheets-editRates.[24.03.2015 13:12:50] KSPI
> axAction (admin): reload_activities_options*
>


*Thanks :)*

Thanks and Regards,
*WJ CHONG*

**Comment by kevinpapst** [comment]
I believe you got the negative time, because Kimai used to use the client time for starting and server time for stopping each timesheet entry. This is fixed in the next release, as we decided to take the server time only, so this should not be happing any longer.

Kimai is right to tell you, that the end-time is not allowed to be lower than the start-time. The error is definitely that you were able to produce such entries, not that is tells you that saving such a key failes.

I close this ticket, as I believe the mentioned bug is fixed in develop
