### ISSUE TITLE
Doctor: allow_url_fopen and curl_multi_exec()

### ISSUE THREAD

**Issue by joho1968** [kimai/kimai#4740]
### Describe the issue

Under **Doctor > PHP**, you may want to check for the PHP setting `allow_url_fopen`, and show a warning if it's disabled.

Also under **Doctor > PHP**, you may want to check if `curl_multi_exec()` exists. We lock down our environments quite a bit by disabling a number of functions. Currently it throws and exception if I go to **System > Plugins**. The exception is 

    Exception Error: "Call to undefined function Symfony\Component\HttpClient\Response\curl_multi_exec()" at CurlResponse.php line 284

You may also want to change the word **Doctor** to **Health** or **Health check**.

The documentation / installation instructions should probably mention these two.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.13.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Thanks for sharing.
Can you share where `allow_url_fopen` is used?

**Comment by joho1968** [comment]
> Can you share where `allow_url_fopen` is used?

Sorry, my bad. I had that in the note text, but apparently did not copy it 🙄 

If `allow_url_fopen` is disabled, this appears in the log:

```
[2024-04-04 14:55:48] [php] WARNING: Warning: file_get_contents(https://api.github.com/repos/kimai/kimai/releases): Failed to open stream: no suitable wrapper could be found {"exception":"[object] (ErrorException(code: 0): Warning: file_get_contents(https://api.github.com/repos/kimai/kimai/releases): Failed to open stream: no suitable wrapper could be found at /kimai/src/Utils/ReleaseVersion.php:43)"} []

[2024-04-04 14:55:48] [php] WARNING: Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 {"exception":"[object] (ErrorException(code: 0): Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 at /kimai/src/Utils/ReleaseVersion.php:43)"} []
```

**Comment by kevinpapst** [comment]
Okay, so allow_url_fopen is used to find the latest Kimai version and the curl method to fetch the plugins. 

Gracias 😄

**Comment by joho1968** [comment]
Why not simply write a function that checks if `curl_multi_exec` is available, if so use that, if not, check if `allow_url_fopen` is true/on, and if so, use that; and if none of them are available, display a warning on the "Health" (Doctor) screen ... 🤔

**Comment by kevinpapst** [comment]
I cannot write custom code for every possible environment combination. 
It is documented that curl is required. You decided to disable it anyway....

I am catching Throwables / RuntimeExceptions in the next release, so you will see the default error once every 24 hours:

![image](https://github.com/kimai/kimai/assets/533162/b446832e-080e-4d7a-a82f-3543a5b33717)


Should be enough. Thanks for the report!
