### ISSUE TITLE
Sort by project or activity number not working

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kimai/kimai#4760]
### Describe the issue

With the introduction of the project and activity numbers in Kimai 2.14 I was expecting to be able to sort by these columns (there is also an icon indicating it's sortable). But it doesn't work.
Also, the search filters both in project and activity overview don't give the option to sort by these new columns.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.14.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
I always work in an iterative manner. 
Build the minimal viable product and progress from there.
And I probably also forgot about sorting 😁

**Comment by kevinpapst** [comment]
Added for the next release
