### ISSUE TITLE
Timesheet API - GET request returns HTTP 400 (Bad request) because of passed dates (begin + end)

### ISSUE THREAD

**Issue by CodeShakingSheep** [kimai/kimai#4763]
### Describe the issue

I cannot get the timesheet GET request to work. No matter in which format I enter the date params, I always receive a HTTP 400 (Bad request) response, see screenshot. When I untick the begin param, the request works.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.12.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/kimai/kimai/assets/19874562/65ba7f44-de3d-40e4-8b93-640a93062fbe)

**Comment by kevinpapst** [comment]
Open a discussion in the future, the API is working as expected.

Or RTM https://www.kimai.org/documentation/rest-api.html#datetime-formats-iso-8601-and-html5

**Comment by CodeShakingSheep** [comment]
I see that opening a bug was probably not the best way. I'll take that with me in the future.

Nevertheless, I think the API docs are not quite precise on that. They say `begin: Only records after this date will be included (format: HTML5)`. From my understanding HTML5 format would also be `YYYY-MM-DD` (see [here](https://www.digitalocean.com/community/tutorials/how-to-use-the-time-element-in-html5)) which I tried as well with `2023-03-24` and this also returned a HTTP 400 response (should have posted a screenshot with that instead).

So, this is my suggestion for a more precise documentation about date params in GET requests `begin: Only records after this date will be included (format: HTML5 local datetime - YYYY-MM-DDThh:mm:ss)`.

**Comment by kevinpapst** [comment]
Thanks for your feedback, I will add a note that "datetime-local" is meant
