### ISSUE TITLE
Your local changes to the following files would be overwritten by checkout (2.14.0)

### ISSUE THREAD

**Issue by joho1968** [kimai/kimai#4764]
### Describe the issue

Here's what I did (I'm on 2.13.0):

`git checkout 2.14.0`

Here's what I got:

```
error: Your local changes to the following files would be overwritten by checkout:
        .docker/test-lite.sh
Please commit your changes or stash them before you switch branches.
```

The problem is that I'm a) not using Docker, and b) haven't touched that file; possibly its ownership and/or file permissions has changed, but I haven't done anything with the content.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.13.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
That is not a bug. 
This is a GIT issue, likely a configuration problem / git attribute whatever magic on your end.

Anyway: the file was deleted in the last release. Just git revert / reset the change.

**Comment by joho1968** [comment]
I just cloned 2.14.0, did some manual stuff and then followed the upgrade procedure. So it works. But I see I need to go over the entire Swedish translation again. It shall be done 😊
