### ISSUE TITLE
Hierarchial projects/activities 

### ISSUE THREAD

**Issue by martonmiklos** [kimai/kimai#4773]
### Describe the problem

At our company many of the internal projects are hierarchical due to the nature of the products we develop (user facing apps -> gateways -> ECUs -> sensors). Making this hierarchy flat would result a very long project list which would make the project selection quite hard. 

The same applies to the activities: I would like to trace down the type of the activities preferably in the similar way:
Production support - Test development - Test equipment hardware development - Test equipment documentation activity

### Describe the solution you'd like

I would like be able to assign child projects to projects and child activities to activities

### Describe alternatives you've considered

Using a flat hierarchy

**Comment by kevinpapst** [comment]
I make that quick, so you can starting searching for alternative solutions (probably using auto-applied tags with the help of the custom field bundle).

Sorry, this feature request is not gonna happen.
