### ISSUE TITLE
New API tokens fail with insufficient permissions

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#4774]
### Discussed in https://github.com/kimai/kimai/discussions/4750

<sup>Originally posted by @tofuSCHNITZEL April  6, 2024</sup>
I tried to switch my scripts to the new bearer tokens and I followed the API examples but I always get:
```
  Client error: `POST http://kimai.test/api/customers` resulted in a `401 Unauthorized` response:
  {"code":401,"message":"Full authentication is required to access this resource."}
```
I even copied the code from the API example 1:1 and just inserted my token but I still get the "Full authentication required" error

What am I missing here? the "KIMAI_API_TOKEN" should just be the token displayed once when creating it, right?

**Comment by lingged-in** [comment]
I am running into the exact same issue on our installation. (We set it up yesterday). 
API calls work from the DOC area but now with Postman I get the error 401 "Unauthorized".

Everything else works. We even set up SAML authentication with Azure which also works.

These are the logs in /var/log/prod.log:
```
[2024-04-12 07:00:05] [request] INFO: Matched route "app_api_status_ping". {"route":"app_api_status_ping","route_parameters":{"_route":"app_api_status_ping","_controller":"App\\API\\StatusController::pingAction"},"request_uri":"https://***/api/ping?Authorizazion=Bearer***","method":"GET"} []
[2024-04-12 07:00:05] [security] NOTICE: No Authentication entry point configured, returning a 401 HTTP response. Configure "entry_point" on the firewall "api" if you want to modify the response. [] []
[2024-04-12 07:00:06] [request] ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "Full authentication is required to access this resource." at ExceptionListener.php line 232 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): Full authentication is required to access this resource. at /var/www/kimai/vendor/symfony/security-http/Firewall/ExceptionListener.php:232)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\InsufficientAuthenticationException(code: 0): Full authentication is required to access this resource. at /var/www/kimai/vendor/symfony/security-http/Firewall/ExceptionListener.php:143)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/kimai/vendor/symfony/security-http/Firewall/AccessListener.php:87)"} []
```

**Comment by kevinpapst** [comment]
Show me the Postman call, this URL is wrong: `https://***/api/ping?Authorizazion=Bearer***`

Besides the fact that `Authorizazion` !== `Authorization`, that needs to be a header.

Can you share a CURL call that is failing instead?

**Comment by nidzho** [comment]
Request:
`curl --location 'http://***/api/ping' --header 'Authorization: Bearer ***'`

Response:
> `{"code":401,"message":"Unauthorized"}`

From the log:
> `[request] ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "Full authentication is required to access this resource." at ExceptionListener.php line 232`

**Comment by kevinpapst** [comment]
Ahhhhh, why can I not see this?!? What about https?

**Comment by kevinpapst** [comment]
Can you try the changes in https://github.com/kimai/kimai/pull/4749 ?
I switched the base permission check for all API calls.
Not sure if that has anything to do with it, this is blind patching, as I am not able yet to reproduce the problem.
@tofuSCHNITZEL @h3nr1-g

**Comment by nidzho** [comment]
> Ahhhhh, why can I not see this?!? What about https?

Same response

> Can you try the changes in #4749 ? I switched the base permission check for all API calls. Not sure if that has anything to do with it, this is blind patching, as I am not able yet to reproduce the problem. @tofuSCHNITZEL @h3nr1-g

I don't have access to this instance, the maintainer will try the upgrade next week.

**Comment by kevinpapst** [comment]
The error is pretty generic and means that the application did not find a way to authenticate the user. That could be the case if something redirects from http to https without forwarding the header properly, e.g. a reverse proxy with bad configs.

So if you skip the entire Authorization header or write `'Authorization: bearer xyz` instead of `'Authorization: Bearer` this error will show...


Compare these calls:
```bash
$ curl --location 'https://demo.kimai.org/api/ping'
{"code":401,"message":"Unauthorized"}%

$ curl --location 'https://demo.kimai.org/api/ping' -H 'Authorization: bearer _2dc9b3d77b7641c955d911c8c'
{"code":401,"message":"Unauthorized"}%

$ curl --location 'https://demo.kimai.org/api/ping' -H 'Authorization: Bearer _2dc9b3d77b7641c955d911c8c'
=> empty result, access denied 401 in header

$ curl --location 'https://demo.kimai.org/api/ping' --header 'Authorization: bearer _2dc9b3d77b7641c955d911c8c'
{"code":401,"message":"Unauthorized"}%

$ curl --location 'https://demo.kimai.org/api/ping' --header 'Authorization: Bearer _2dc9b3d77b7641c955d911c8c'
=> empty result, access denied 401 in header

$ curl --location 'https://demo.kimai.org/api/ping' --header 'Authorization: Bearer _2dc9b3d77b7641c955d911c8c' --head
HTTP/2 401
server: nginx
content-type: application/json
www-authenticate: Bearer error="invalid_token",error_description="Invalid credentials."
cache-control: no-cache, private
date: Fri, 12 Apr 2024 12:16:44 GMT
strict-transport-security: max-age=31536000
```

Your request ` curl --location 'http://***/api/ping' --header 'Authorization: Bearer ***'` should NOT return `{"code":401,"message":"Unauthorized"}` unless the header is stripped/changed somewhere. 

I am not 100% certain here, but I'd say that Kimai simply doesn't receive the `'Authorization: Bearer ***'` header.

**Comment by kevinpapst** [comment]
Here is a possible reason and solution: https://github.com/kimai/kimai/discussions/4750#discussioncomment-9095609

**Comment by tofuSCHNITZEL** [comment]
I suggest we add ` SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` to the htaccess - it seems it would not do harm if not needed.

**Comment by pkoevesdi** [comment]
I run into the same error. Authorization and `/api/ping` in the Swagger UI on `timetracking.example.com/api/doc` works. But executing the copied `curl` command from there:
```
curl -X 'GET' \
  'https://timetracking.example.com/api/ping' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer 5de08a108b19783c3a08cf0b7'
```
on a shell, I get a `{"code":401,"message":"Unauthorized"}`.
I have Kimai 2.18.0, the changes from https://github.com/kimai/kimai/pull/4749/files#diff-ba277bbff724255df1f11e1b9441f2690bea9565604563a8c9d5bdebb9681ee4 I can find reflected in my `public/.htaccess`.

**Comment by tofuSCHNITZEL** [comment]
What Webserver are you using?

**Comment by pkoevesdi** [comment]
Sorry for missing that info: Apache/2.4.59 (Debian)

**Comment by pkoevesdi** [comment]
If I follow https://github.com/kimai/kimai/issues/4774#issuecomment-2051749197 and put `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` (not knowing, what I'm doing there) into `.htaccess`, it works.
Otherwise, my `.htaccess` is the same as https://github.com/symfony/recipes-contrib/blob/main/symfony/apache-pack/1.0/public/.htaccess

**Comment by kevinpapst** [comment]
Hm, so weird that the official Symfony htaccess doesn't work.
Can you @pkoevesdi post your entire htaccess?

And could you try what happens if you remove these two lines:
```
    # Sets the HTTP_AUTHORIZATION header removed by Apache
    RewriteCond %{HTTP:Authorization} .+
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%0]
```
    
They should exactly care about that, but maybe they were only working in Apache 1...

**Comment by pkoevesdi** [comment]
> Hm, so weird that the official Symfony htaccess doesn't work. Can you @pkoevesdi post your entire htaccess?

I made a diff with the linked one - it's really the same (except the first comment line with that link to it's source).

> And could you try what happens if you remove these two lines:

Doesn't solve it, same error `{"code":401,"message":"Unauthorized"}`.

**Comment by kevinpapst** [comment]
Thanks! So these two lines have no effect in Apache 2. 

Where exactly did you add the `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` line.

**Comment by pkoevesdi** [comment]
I tried several locations, worked everywhere, now I have it in the beginning.

**Comment by pkoevesdi** [comment]
Any news here? Yesterday I updated Kimai from 2.18 to 2.19.1 and ran into the same problem again (probably because my .htaccess was overwritten). Again put that line into it, and it works again.

**Comment by kevinpapst** [comment]
@pkoevesdi Its there: https://github.com/kimai/kimai/blob/main/public/.htaccess#L44

**Comment by pkoevesdi** [comment]
Ah, yes, sorry, I see, I have it. But, contrary to my test  results before, now it only works, if outside that `<IfModule mod_rewrite.c>`-Block. I probybla don't have that mod_rewrite.

**Comment by pkoevesdi** [comment]
Yes, consistently, it works after enabling rewrite: `a2enmod rewrite`.
Question arises: Why Do I need that module, if everything else works without it?

**Comment by kevinpapst** [comment]
> Why Do I need that module

Because it is written in the requirements section of Kimai at https://www.kimai.org/documentation/installation.html

<img width="822" alt="Bildschirmfoto 2024-07-29 um 22 25 43" src="https://github.com/user-attachments/assets/81470ef2-ad94-40f4-a018-133f9b290919">

I haven't  seen an Apache host without mod_rewrite since ages. 
Why would you deactivate one of the most common Apache modules?

Let's celebrate that that this topic is solved 🎉

**Comment by pkoevesdi** [comment]
Ok, then I'll leave it activated. 👍
