### ISSUE TITLE
Natural sort ordering for project/activity/customer numbers

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kimai/kimai#4783]
### Describe the problem

The fields for project, activity and customer numbers allow insertion of any kind of string despite the naming "number". I completely understand this is not limited to integer input as somebody might want to create sub-project numbers like "101a" or "101.1".

However, the sorting mechanism is not using natural sort which will lead to the output pictured below.
This is avoidable, if one uses the leading zero notation for any of these. The default for project numbers is up to 2 leading zero's. In this case the problem appears delayed after project number 999, which isn't great either.

### Describe the solution you'd like

Using PHP natural sorting algorithm instead.

### Screenshots

![grafik](https://github.com/kimai/kimai/assets/54700498/2d9169d6-f07a-417d-a233-1d143675906f)

**Comment by kevinpapst** [comment]
As you said yourself: use a formatted string for everything below 100 or 1000, e.g. 007 or 0007.
That's why the default setting is `{ac,4}`, which allows for 9999 correctly ordered project/activities.
The same behavior works flawless with customer numbers since a long time.

I am using database sorting and this column will not get a special treatment. 
So I am closing this one.

And as always: thanks for sharing your idea, keep em coming 😄

**Comment by rbuehler-teletrend** [comment]
OK, understood.
How about changing all string based columns to naturally sorted then? Would there be any disadvantages in doing this?
There is a NATURAL_SORT_KEY in MariaDB so I believe from the technical side it should be easily possible.
Should I put this into the discussions section?

**Comment by kevinpapst** [comment]
Please, discussion are always open. If you find many people that support the idea AND if there is a technical solution that runs both in Mysql 5+ and MariaDB, I can look into it.

**Comment by rbuehler-teletrend** [comment]
Thanks for you reply.
I guess this idea dies on the MySQL requirement. As I understand, MySQL doesn't have any native natural sorting method. :(

**Comment by kevinpapst** [comment]
This sorting of the datatable is a global function shared by all screens, so yes, it needs to work on all platforms.
Due to the amount of data some companies use, it can't be done in PHP,
