### ISSUE TITLE
Auto-Updater for Kimai

### ISSUE THREAD

**Issue by derStephan** [kimai/kimai#4786]
### Describe the problem

Hi,

I wrote a small bash script to perform auto updates. 

```
#! /bin/bash

#Change into your Kimai directory
cd /var/www/kimai

# Get new tags from remote
git fetch --tags

# Get latest tag name
latestTag=$(git describe --tags "$(git rev-list --tags --max-count=1)")

# Checkout latest tag
git checkout $latestTag

#Update all composer dependencies
composer install --optimize-autoloader -n

#run the Kimai updater
php bin/console kimai:update

#Adjust file permission
chown -R :www-data .
chmod -R g+r .
chmod -R g+rw var/
```
I run it from crontab once a week. 

### Describe the solution you'd like

Add something similar to kimai's sources or add some point & click updater directly to kimai

### Describe alternatives you've considered

manually updating according to 
https://www.kimai.org/documentation/updates.html

**Comment by kevinpapst** [comment]
We can add that to the documentation, but I will not work on an auto-updater or include something like it in the core package.

Do you want to propose a PR to the docs? 
https://github.com/kimai/www.kimai.org/edit/main/_documentation/updates.md
