### ISSUE TITLE
Tags JSON missing key for key value pair

### ISSUE THREAD

**Issue by treverehrfurth** [kimai/kimai#4787]
### Describe the issue

For work we need to export all our Kimai data into Snowflake.
We are using Matillion DPC to automate the endpoints/ingestion and everything's been great except Tags.
the API call for getting all the tags lists it without a key, and just shows the value.

Example:
```
[
    "Client Weekly Sync",
    "Daily Standup",
    "Engineer Synch"
]
```

Automated API tools struggle with handling a key value pair with no key from the JSON.

Is this something that can be added to make it play well with other data integration/development tools?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.13

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
`[]` is an array, `{}` is a key-value map.
In which world is this a bug? Did I miss something obvious?
Sounds as if that Snowflake app has a flaw.

**Comment by treverehrfurth** [comment]
Okay sorry, I don't spend my life in JSON. 
And you're right its more of a feature request to add {"tags": ["xyz"]} instead of just an array vs a bug, my bad.

In which world is Matillion a Snowflake app?
Its an enterprise SaaS data pipeline builder with HQ in multiple countries and it needs an identifier for the array otherwise it parses everything as null.

My company is a Matillion Partner and i've reached out to support to figure out a way to handle this, but that could be months to never as its not high on their priority list as every api call i've ever used prior was a key-value map.
I figured I could also ask you as the developer here to add a wrapper around the tags API thinking that would be the easiest boulder to move. Sorry for asking.

**Comment by kevinpapst** [comment]
Your post has so many flaws that I am just going to close here instead of answering.
