### ISSUE TITLE
Does not work with the mysqli-extenstion

### ISSUE THREAD

**Issue by resli** [kimai/kimai#479]
I try to move my old Kimai installation to the new server containing PHP 5.6.7
I found that it's not advisably to use the deprecated mysql extension because it fills up the log files:
http://php.net/manual/de/migration55.deprecated.php

Is there a plan to support the mysqli or pdo_mysql extension?

Thanks,
Andreas

**Comment by simonschaufi** [comment]
Yes we plan to make it compatible with mysqli as well.

**Comment by simonschaufi** [comment]
duplicate to #363

**Comment by kevinpapst** [comment]
This is fixed in the latest master branch. You can try it out and leave us feedback if you encounter a problem.
