### ISSUE TITLE
REST API - Filter by non existant tag returns all records

### ISSUE THREAD

**Issue by sinag** [kimai/kimai#4792]
### Describe the issue

We are planning to use tag field to integrate kimai records to another systems records.
I am not sure if the original behaviour, when tag does not exist return all rows is meaningfull for other scenarios but generally when you filter for something which does not exist you expect to see zero records.

Is there a workaround for this?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.15.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

**Comment by sinag** [comment]
Let me give you more details on my usage scenario;

1) user opens a record on external system with record.id = 1
3) external system is configured to show current record's related kimai timesheets
2) external system queries kimai api with tags[]=1, if tag has not been created before, kimai returns all timesheets, expectation was to see no timesheets

**Comment by kevinpapst** [comment]
> when you filter for something which does not exist you expect to see zero records.

No. This behavior is unspecified. Kimai can't find a tag, so it queries without tag, which leads to all results. That's how tags currently work. 

In the API it would be better if there was a validation, in that case your result would be a `Bad request`.

**Comment by kevinpapst** [comment]
A little late... I forgot about the issue.
Let me ask you, what you would see as best API behavior:
1. request with one or more unknown tags = BadRequest
2. you request 5 tags and all 5 are unknown = BadRequest
3. you request 5 tags and 4 are unknown = you get the list of all timesheets with that one tag

I tend to go with 2 currently. What's your opinion @sinag ?
