### ISSUE TITLE
Reporting: Display total number of hours, internal price and total revenue at the same time

### ISSUE THREAD

**Issue by EduNetEurope** [kimai/kimai#4795]
### Describe the problem

In Reporting, we can either view the total number of hours, the internal price or the total revenue.

### Describe the solution you'd like

It would be great to see all three next to each other.

### Describe alternatives you've considered

The perfect solution would be to have an [extra row in "All times" that provides the totals for all columns](https://github.com/kimai/kimai/issues/4270).

**Comment by kevinpapst** [comment]
Lets stick with #4270

**Comment by EduNetEurope** [comment]
Definitely the MUCH better option. :-) Glad to hear it's on your radar.
