### ISSUE TITLE
LDAP login with TLS broken again

### ISSUE THREAD

**Issue by abrain** [kimai/kimai#4796]
### Describe the problem

It seems that PR #4586 reverted the fix provided in #4598. Therefore, the login via LDAP + TLS is not possible anymore beginning with Release 2.14.0. The login credentials are always rejected as incorrect.

Manually running `apt-get install libldap-common` inside the container fixes the issue. We are using the apache version of the image (`kimai/kimai2:apache-2.15.0-prod`).

### Describe your setup and add your Docker compose file (redact your credentials)

- OS: Debian 11.9
- Docker version: 26.0.1
- Docker compose version: 2.11.1

**Comment by kevinpapst** [comment]
@tobybatch ups

@abrain up for one more PR?

**Comment by abrain** [comment]
> up for one more PR?

Sure, will submit it shortly.
