### ISSUE TITLE
Administration / Client / Budget: ability to hide rows, e.g. "Revenues (Billable - Internal price)"

### ISSUE THREAD

**Issue by EduNetEurope** [kimai/kimai#4800]
### Describe the problem

We track project costs without invoicing anyone. 
We would like to be able to share a very simplified budget view with our project partners.

### Describe the solution you'd like

We would like to be able to decide what to show in the budget section (e.g. only show "Budget" and "Total revenue").

**Comment by kevinpapst** [comment]
This will never be part of Kimai core.
You can check the Shared project plugin (not sure how it is exactly called).

**Comment by EduNetEurope** [comment]
Yes, thanks for the reply.
https://www.kimai.org/store/vettersolutions-shared-project-timesheets-bundle.html
