### ISSUE TITLE
API Token expiry in the past

### ISSUE THREAD

**Issue by divemasterza** [kimai/kimai#4808]
### Describe the issue

When creating an API token, it is possible to create a new one with an expiry date  in the past. The Calendar picker should only allow dates in the future.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.15.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
Thanks, will be fixed in 2.16
