### ISSUE TITLE
Update netcup (shared hosting) installation instructions 

### ISSUE THREAD

**Issue by lubrell** [kimai/kimai#4816]
### Describe the issue

I have tried to install Kimai 2.15.0 [according to the documentation](https://www.kimai.org/documentation/shared-hosting.html#netcup) on a [Webhosting 4000](https://www.netcup.eu/bestellen/produkt.php?produkt=3342) from [netcup.](https://www.netcup.eu/) 

Even if #1620 was helpful, it **does not** address the [memory_limit problem,](https://www.kimai.org/documentation/installation.html#memory-limit) which **always occurs** with netcup. This happens because only 128M are available in the console, regardless of which shared hosting package you have. As a result, the memory_limit must be increased manually for each console command.

For this reason I have created this issue to present the currently working procedure, maybe it will help others, and maybe you want to update it in the official documentation:

- [ ] Use git in the desired directory
`git clone -b 2.15.0 --depth 1 https://github.com/kimai/kimai.git`
- [ ] Switch to the Kimai folder
`cd kimai`
- [ ] Use cURL to get Composer
`curl -sS https://getcomposer.org/installer | /usr/bin/php`
- [ ] Install Composer
`COMPOSER_MEMORY_LIMIT=512M php -d memory_limit=512M composer.phar install --no-dev --optimize-autoloader`
- [ ] Open the configuration file and enter the database data
`nano .env`
- [ ] Install Kimai
`php -d memory_limit=512M bin/console kimai:install -n`
- [ ] Reload Kimai
`php -d memory_limit=512M bin/console kimai:reload`
- [ ] Configure netcup (using the customer controlpanel) to use “/kimai/public” as root folder for the domain (or subdomain) of your choice and add SSL (Let´s Encrypt) for this domain.

cheers

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.15.0

### How do you run Kimai?

netcup shared hosting

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
Thanks @lubrell for sharing ❤️  

I updated the docs accordingly: https://www.kimai.org/documentation/shared-hosting.html#netcup
