### ISSUE TITLE
Display issue with Firefox on v0.9.3.1384

### ISSUE THREAD

**Issue by climb4fun** [kimai/kimai#482]
Hi all,

I upgraded today from old version to Kimai v0.9.3.1384. Upgrade worked well. Unfortunately a display issue occurred afterwards with most recent version of Firefox. It works well again, if I switch in Firefox rendering machine to Internet Explorer. The old version of Kimai still works well with Firefox.

Regards,

climb4fun

**Comment by simonschaufi** [comment]
screenshot?

**Comment by climb4fun** [comment]
Hi Simon,
attached a screenshot. In this logon window, it's not possible to logon - results is allways to be redirected to "http://.../kimai/index.php?a=logout". Strange.

![2015-04-22 12_15_34-kimai login - waterfox](https://cloud.githubusercontent.com/assets/9963426/7272399/e0a236b4-e8ea-11e4-9f60-ab2a7226160e.jpg)

Thanks

climb4fun

**Comment by simonschaufi** [comment]
I have version 0.9.3.1384 but mine looks ok and works. could it be that any browser addon affects this?

**Comment by climb4fun** [comment]
I tried your suggestion - brought no progress. But it was a wonderful guiding hint to restart browser after deleting all cookies and history. This solved the issue. Silly me, I could have found solution by my self and saving your valuable time.
Thx.
