### ISSUE TITLE
Can't see the new user in any Select-Box ( Assigned to wrong user)

### ISSUE THREAD

**Issue by xstable** [kimai/kimai#4832]
### Describe the issue

I have add a new User and assigned him to a Project. 
He is able to login and had tracked some times during the month. 

If I go the project > export page, where he is assigned to I see him in the list of single estimates: 

![image](https://github.com/kimai/kimai/assets/1778068/6d78ba9c-b58e-41bd-89a1-7ce844265c33)

But if I click on this Entry to edit it, it shows that in the User-Field he isn't added ... but always the first entry in the select-list ist selected: 

![image](https://github.com/kimai/kimai/assets/1778068/756e9488-c581-4da6-bd15-c09c7b1a6677)

Everywhere in Kimai, where a Select-Field is, I "don't" see this particular user.

If I go to Kimai Settings > User I see his tracked estimates: 

![image](https://github.com/kimai/kimai/assets/1778068/20eb4725-f360-41ae-8d9d-89a644c3f359)

But if I click on one BAR in the chart, I'll be redirected to "reports"-Page, and there (again) I don't have this user in the selectbox to see any of his timetracks. 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.4.1

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
Edit user, deactivate System user

**Comment by xstable** [comment]
@kevinpapst thanks a lot. That was the solution
