### ISSUE TITLE
Importer - Clockify Import duration rounding problems

### ISSUE THREAD

**Issue by bepixeld** [kimai/kimai#4838]
### Describe the issue

Importer Version: 2.10.0

The Clockify column `Duration (decimal)` is used to import the duration.
This leads to rounding errors in some constellations.

e.g. Start: 10:01; End: 10:42 = Duration 1:41h = 1.6833 in decimal.
![duration-decimal-import-preview](https://github.com/kimai/kimai/assets/7001544/fac47f05-cf71-4135-a5fd-6d9e57136815)

After the import, the start/end is displayed correctly.
But the duration is displayed incorrectly as 1:40.
![duration-decimal-import-result](https://github.com/kimai/kimai/assets/7001544/20f15c8c-ae6b-4920-ad8a-c7dd236e2e4a)

The duration is stored in the database as 6059 seconds.
The correct value would be 6060 seconds

It seems that the importer always rounds down.
When formatting from seconds to h:m, it rounds down again.
Therefore, one minute is displayed too little.

**Solution for me:**
Use the Clockify column `Duration (h)` when importing.
In file ImportBundle/Importer/ClockifyTimesheetImporter.php (Line ~112)
Swap the lines `case 'Duration (h)':` and `case 'Duration (decimal)':` with each other.
![duration-h-import-preview](https://github.com/kimai/kimai/assets/7001544/03101367-d799-4d93-9b81-609a5aab0b04)

This will import the duration correctly.
![duration-h-import-result](https://github.com/kimai/kimai/assets/7001544/165c3792-f116-4030-a667-40a10ea3e5f4)

I hope, this helps.
Or is there any better way?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.16.1

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
Can you try to switch your rounding rules in System > Preferences to `0` for all values and also change the rounding mode?
Kimai by default rounds minutes.

**Comment by bepixeld** [comment]
I have set all rounding rules to 0. Then made an import attempt for each rounding mode.
The problem remains with the wrong display of 1:40, instead of 1:41.

I have investigated the problem further:
When importing, the duration (decimal) is processed with the function [Duration::parseDecimalFormat](https://github.com/kimai/kimai/blob/661bb163428b68b19bc9dc9701dffd285dee6732/src/Utils/Duration.php#L105).
The duration is converted to seconds and then converted to int (round down).
```
$duration = 1.6833;
$duration = $duration * 3600; // 6059.88
return (int) $duration; // 6059
```
6059 is saved as the duration in the database.

As far as I have found, when displaying the duration in the Kimai timesheets, the function
[Duration::format](https://github.com/kimai/kimai/blob/661bb163428b68b19bc9dc9701dffd285dee6732/src/Utils/Duration.php#L29) is used to format the duration.
Here too, only rounding down is used.
```
$seconds = 6059;
$hour = (int) floor($seconds / 3600); // 1
$minute = (int) floor((int) ($seconds / 60) % 60); // 40
```

The rounding rules from preferences are never used here.
I think the easiest way to solve the problem is to use the Clockify field `duration (h)` for the duration column.
This eliminates the rounding problems for me.

[Here](https://github.com/kimai/kimai/files/15223131/clockify_test_rounding.csv) is a test file so that you can try it yourself.

**Comment by kevinpapst** [comment]
Thanks for the detailed input. I could reproduce the issue and your fix is working. 
And yes, I was previously wrong, the rounding rules are not applied during import (which would be wrong anyway).
Its fixed in the [latest release of the plugin](https://github.com/kevinpapst/ImportBundle/releases/tag/2.13.0).
