### ISSUE TITLE
Submit time entry form on CTRL + Enter

### ISSUE THREAD

**Issue by cngJo** [kimai/kimai#4843]
### Describe the problem

When creating new time entries, I always find myself pressing CMD + Enter (CTRL + Enter) to submit the form, which then never works 😅

### Describe the solution you'd like

Detecting CMD + Enter (CTRL + Enter) on the Time Entry Modal and submit if for the user when the form is valid. 

### Describe alternatives you've considered

Maybe related to #4707

**Comment by cngJo** [comment]
Would you accept an PR implementing this?

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/keyboard-shortcuts.html ?

**Comment by cngJo** [comment]
... It's CTRL + Center on macOS and not CMD + Enter as I expected ... RTMF to me, and sorry for them unnecessary issue

**Comment by kevinpapst** [comment]
Its always good to talk 😁
