### ISSUE TITLE
Change strings with label "Do not translate!" at Hosted Weblate to "read-only"

### ISSUE THREAD

**Issue by milotype** [kimai/kimai#4863]
### Describe the problem

Currently, strings which you don´t want to be translated at "Hosted Weblate" have a label `Do not translate!`.

### Describe the solution you'd like

If strings with the label `Do not translate!` shouldn´t be translated, I´d suggest to mark them as `read-only`. It helps translators, because the don´t have to bother to translate such strings.

Here is the list I found for Croatian
https://hosted.weblate.org/search/kimai/-/hr/?q=label%3A%22Do+not+translate%21%22&sort_by=-priority%2Cposition&checksum=

### Screenshots

1. **Example 1: Kimai Mobile**
![Kimai Mobile](https://github.com/kimai/kimai/assets/43657314/bccb4f8f-dec4-485b-a065-de98dc952c69)
2. **Example 2: SAML**
![SAML](https://github.com/kimai/kimai/assets/43657314/55ec37bb-ffae-4663-ab68-29b8cfde2396)

**Comment by kevinpapst** [comment]
I learned something new today about Weblate 😄 

Adding the `read-only` flag is really helping.
I think there are more strings then the ones with the label, but we'll identify them one by one.

Cool hint, thanks for sharing @milotype 👍 

I removed the `Do not translate!` label from all entries.
