### ISSUE TITLE
Everybody's username is their password

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4864]
### Describe the issue

I tried setting up kimai.cloud today. When the account is created your username is your password (regardless of what password you input on the signup page).

---

This is a concern because if you see this you may not want to invite anybody else to your team. Most people do not change their password, and that means you are inviting all your employees to login and see each others pay rates and other private information.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
This is only for the initial user account that is created for the cloud. 
This person is hopefully responsible enough to change the initial password...

Thanks for sharing your concerns though.
Next time if you have questions about the cloud, you can also use the support form on the website.

**Comment by fulldecent** [comment]
This note would be helpful to show on that notice where it tells you that your email address is your password. (Sorry, not sure if _this_ is part of Cloud, or the open source part.)

That notice could address the contern of other people that may be afraid to proceed setting up and using Cloud.

**Comment by kevinpapst** [comment]
Thanks for sharing the feedback. 

I am already working on improving the onboarding flow.
