### ISSUE TITLE
Have the time entry box be modal

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4867]
### Describe the problem

I tried watching several people on our team try Kimai for the first time. Several people had this problem:

When entering a time entry, they clicked outside the modal dialog. And the box closed. This required them to start over entering the time.

In one case, somebody misclicked below the "Save" button. They thought the time was recording but actually the time entry was stopped.

### Describe the solution you'd like

When the modal dialog is open, if somebody clicks outside the modal dialog:

1. Scroll to the action buttons
2. Yellow flash the action buttons to indicate that they must be clicked.

### Screenshots

![Screenshot 2024-05-20 at 11 44 04](https://github.com/kimai/kimai/assets/382183/4a07243e-7853-447a-825f-f044968310d8)

**Comment by kevinpapst** [comment]
When you change any field before clicking outside the modal, something like that already happens.
Its totally fine that the form closes if no value was changed. 
But I am not sure why the duration field does not trigger the "isDirty" check on the form, I'll check. 
Thanks for sharing!

**Comment by sjthiessen** [comment]
Dunno if related, but I encounter an annoying UX bug when starting time tracking:
1. Clicking the play button
2. Clicking in the customer-Dropdown
3. App selects a time from the timepicker-dropdown

When I just want to start time tracking without setting a duration.

https://github.com/user-attachments/assets/1f2e14d7-7116-4ae1-a802-3abf9ffe5e89

I'm on Firefox 130.0.1

**Comment by kevinpapst** [comment]
Please open a new discussion @sjthiessen for that. I cannot verify this issue in any browser (FF 130.0.1 tested on mac)- Check your browser console and share what you see there. Also share your Kimai version.

**Comment by kevinpapst** [comment]
Will be fixed with the next release 2.25 soon. See https://github.com/kimai/kimai/commit/8b55cd369385969faeddd15adfcb4a28f4e0ea65
