### ISSUE TITLE
Update website logo to look different than the record time button

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4868]
### Describe the problem

I tried test-running Kimai with several people on our team and watched how they used the product. 

One of the people got confused because they were instructed to "look for the play button on the top to start recording time", but they tried clicking on the Kimai logo at the top-left of the screen instead. They reported the website as "not working".

### Describe the solution you'd like

One option is to change the Kimai logo so it does not look the same as the other button.

To be honest, the "record time entry" button is the only important button or feature whatsoever for all of my staff using this product.

A second option is to implement tooltips that immediately show before clicking on the button. I provided a crude mockup below.

### Describe alternatives you've considered

I renamed the main button to "Return to homepage" so that it is very clear this is not related to tracking time. (Previously it was named "Dashboard".)

Also I made a mockup of how it looks when there is a popup tooltip that shows immediately:

https://github.com/kimai/kimai/assets/382183/8f1fed5b-3284-42d9-b4ac-9db895eda8a1

Hopefully this can prevent people from clicking the logo and thinking it will do time tracking.

### Screenshots

![Screenshot 2024-05-20 at 11 44 04](https://github.com/kimai/kimai/assets/382183/2bee01dd-a68b-4a52-803e-479d4488ef54)

**Comment by kevinpapst** [comment]
Interesting feedback, always fascinating to see why people struggle 🤷 

Add your company name at System > Settings, then the logo will be gone.

**Comment by fulldecent** [comment]
Yes, I am horrified sometimes watching screen shares :-p
