### ISSUE TITLE
Kimai Cloud: compress HTTP responses

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4869]
### Describe the problem

The Kimai Cloud server is not configured to compress HTTP outputs. This is contributing to unnecessary slowness, especially for our staff in Asia.

See how NGINX is not configured to compress the response:

![Screenshot 2024-05-20 at 12 13 05](https://github.com/kimai/kimai/assets/382183/14c41bd3-bbee-4841-bf27-0595ac7aab35)

Whereas on Google.com, their response is compressed:

![Screenshot 2024-05-20 at 12 16 09](https://github.com/kimai/kimai/assets/382183/3e2ba96a-1d69-4563-82b8-5039f0fbc306)

This contributes to (it is surely not the only reason) to an unnecessarily slow page load time as shown here:

![slow](https://github.com/kimai/kimai/assets/382183/5124c5b1-f9ec-44a7-8aba-7737511a7b48)

That screenshot is from Philadelphia with 100MB internet, shared in a small office. The impact for our workers in Asia is more significant.

### Describe the solution you'd like

Configure NGINX to use gzip/deflate compression of outputs

**Comment by kevinpapst** [comment]
This is not the right place for Kimai-Cloud topics. 
Please sent them to support@kimai.cloud

**Comment by fulldecent** [comment]
Got it, thank you, sent there
