### ISSUE TITLE
Data validation error when entering time

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4877]
### Describe the issue

Somehow somebody entered more time in a day than the Earth currently allows.

![Screenshot 2024-05-24 at 16 44 49](https://github.com/kimai/kimai/assets/382183/e3012bdc-5756-443e-9712-b7a3cf428331)

---

A hard limit of 24 hours should be enforced.

# Other notes

Limits of less than 24 hours should be configurable and documented. 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
This duration is not limited to a day. If you allow unlimited durations, a record can start on the 24 and end on the 28.

You can configure it at System > Settings > Timesheet:

<img width="720" alt="Bildschirmfoto 2024-05-24 um 22 50 18" src="https://github.com/kimai/kimai/assets/533162/8f7b2de6-7515-4c66-a6ed-84ea67556255">

**Comment by fulldecent** [comment]
But shouldn't that show on this report as some hours on the first day and then more hours on the next day, etc. ?

So maybe the concern here is not entering the time but presenting the time on a report

**Comment by kevinpapst** [comment]
Working time is always calculated for the day the record started. 
As you said yourself: such entries don't make sense, but they are possible.

**Comment by fulldecent** [comment]
I don't know any other service that lets you make time sheets ending at 25:00 26:00 and later. 

We should probably consider to make Kimai work they way that time is measured in everywhere else.

That means:

* A time entry starting before 24:00 and ending after 24:00 should be broken in to entries for each of the different days.

**Comment by kevinpapst** [comment]
The more often you post, the more I believe you are hired by a competitor to spread wrong accusations.

Have the decency to at least check what you post BEFORE posting it.
