### ISSUE TITLE
var.projectComment

### ISSUE THREAD

**Issue by juup** [kimai/kimai#488]
Hi,
as [var.projectComment] was not working for my invoice templates, I added:
**$projectComment  = html_entity_decode($timeArray[0]['pct_comment']);**
(Line 80, print.php)

Is that the right way or did I miss the right place?

Regards
juup

**Comment by ServiusHack** [comment]
I could have sworn I created that pull request to update the documentation regarding project comments but apparently I didn't. So here it is now: kimai/documentation#2

As you can see from the change, there should be no `[var.projectComment]` as an invoice can be for more than one project. An alternative (to get the comment of the first project) is to write `[var.projects.0.comment]`.
