### ISSUE TITLE
Reporting: show all time on the correct day

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4882]
### Describe the issue

Here is the problem:

![Screenshot 2024-05-28 at 17 06 10](https://github.com/kimai/kimai/assets/382183/03b2af6a-306a-47f4-9dcc-093fd4962fdd)

It will be improper for me to speculate how the system works or which part is broken.

But in general, as an employer, it is never acceptable (except leap seconds, and daylight savings change) that my employee's timesheet should have more than 24 hours in one day. 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
I said it before: times are always calculated for the start day, no matter how long they are. 
If you start working on 02. May at 23:30 your entire shift (assuming you just use one time entry) will be calculated for the 02.05. That is btw how the law defines it as well. 

The system is not there to check whether such entries make sense, it gives you the information what was booked.
Don't allow booking 50 hours long entries and don't allow overlapping entries. Still possible to create more than (in your 
words) 24 hours for one day, but that is another topic.

This is not a bug and will not be changed as it works as expected. 
Want to discuss new checks / reports to find invalid entires? Great!
