### ISSUE TITLE
Menubar app

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4888]
### Describe the problem

Our team is testing Kimai and here is some of the feedback we got compared to another software we are currently using.

If there can be a menubar app this could be helpful.

### Describe the solution you'd like

It should allow:

- Show time worked so far
- Notify if a limit has been reached/approaching (if they continue to work they will not be paid, so this is really valuable information to them)
- Recommend to stop time tracking if the computer is idle for a certain amount of time

### Describe alternatives you've considered

I understand this issue may not be implemented any time soon. But I hope this issue, or some other thread, can stay open so that I and others can be notified if/when this is implemented.

### Screenshots

![mbar](https://github.com/kimai/kimai/assets/382183/06b8741a-9040-4459-b91d-da3dc61cc6bb)

**Comment by kevinpapst** [comment]
https://www.kimai.org/store/ticesoftware-kimaibar-macos-client.html

**Comment by fulldecent** [comment]
Thank you, that software makes sense and should be the way to go
