### ISSUE TITLE
Show summary of time worked for day

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4890]
### Describe the problem

Our team is testing Kimai and here is some of the feedback we got compared to another software we are currently using.

I have instructed the team to use Kimai on a trial basis and I have not provided any further instruction. It is possible that this feature already exists somewhere. If that is the case then I may please recommend that it be easier to find or be turned on by default.

Our team is using multiple shifts per day. And they have a limit on the number of hours they are allowed to work for the day. This limit is very important for them because they are not paid for time worked past that limit. And people do not like working without being paid.

In Kimai, the staff are seeing the time worked in the current session. But they do not see the time worked in total for the day. Mystically, it is important for people to look forward to a goal, like 8 hours, after which they can go play with their kids and not do more work.

### Describe the solution you'd like

By default, the number shown is the total time worked for that day.

Or, alternatively, wherever the session time is shown, the day-total is shown next to that.

### Screenshots

![Screenshot 2024-06-02 at 07 54 45](https://github.com/kimai/kimai/assets/382183/74c50ba3-0c65-4f18-8551-c062b050727c)

**Comment by kevinpapst** [comment]
My times
<img width="884" alt="Bildschirmfoto 2024-06-02 um 14 16 00" src="https://github.com/kimai/kimai/assets/533162/a63fec55-df15-467d-8d56-a650c9fbb06e">
<img width="870" alt="Bildschirmfoto 2024-06-02 um 14 15 45" src="https://github.com/kimai/kimai/assets/533162/a46c7cb6-7c04-4cce-afee-47030557f72f">

Dashboard
<img width="982" alt="Bildschirmfoto 2024-06-02 um 14 16 16" src="https://github.com/kimai/kimai/assets/533162/d35446d3-399a-413e-92cd-30594bf782fb">

Report
<img width="1429" alt="Bildschirmfoto 2024-06-02 um 14 16 36" src="https://github.com/kimai/kimai/assets/533162/4c2fe18e-ae93-448d-9123-33bde335a2c9">
