### ISSUE TITLE
Project number in Excel export

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kimai/kimai#4891]
### Describe the problem

When timesheets are exported as Excel file, the lately introduced project number is not part of the otherwise quite extended XLS output.

### Describe the solution you'd like

Could the project number be added as an additional row in the Excel export?

**Comment by kevinpapst** [comment]
Its really time for a configurable export ... sorry that it is still not existing

**Comment by kevinpapst** [comment]
Working on it, the next version will ship an updated Excel and CSV exporter, which is much faster, less memory consuming and allows to export at last twice the amount of rows in one go.
