### ISSUE TITLE
The `Create Activity` form contain extra fields

### ISSUE THREAD

**Issue by sharky98** [kimai/kimai#4897]
### Describe the issue

As a TeamLead user of Team A, in a Project inside a team-limited Customer to Team A, do the following.

1. Open a project administration page.
2. Click on the `+` to add an activity.
3. Fill out the only required field (Name).
4. Click the `Save` button.
5. The form is shown again with the error `This form should not contain extra fields`. The fields related to the budget are not shown anymore.
6. Click the `Save` button again, it works.

When doing the same as the System-Admin, I do not have the error showing up. In the past, I modified my Teamlead role permissions so that they can create activity and projects inside a customer they have access. I suspect I didn't add all the required permissions. Is there an easy way to "dump" the current role permissions to help debug?

Otherwise, since the form does save correctly once the field are removed, maybe the form could be loaded without the related fields is the user does not have the required roles?

#2765 seems related.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.15.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

### Screenshots

![create-activity-form](https://github.com/kimai/kimai/assets/8150191/ed61a3fe-bac7-4e89-903e-ca39ffaba01a)

![create-activity-form-result](https://github.com/kimai/kimai/assets/8150191/7adbb092-5a0e-481a-a89b-5e122412c249)

**Comment by kevinpapst** [comment]
Thanks for sharing 👍 

I found one place that might be related, even though I am not sure. I hope it can fix this problem.
My assumption is that after submitting the form, the project is loaded too late and therefor the permission is checked globally. And the global budget permission is not active for teamleads (only this project specific one).

Anyway, this is the commit: https://github.com/kimai/kimai/pull/4878/commits/42bb2f556a162f9961f6622b1d414eddb4f64820
you could try to change it on your end and retest.
