### ISSUE TITLE
Error 500 class Doctrine\ORM\Query not found after upgrade to 2.17.0

### ISSUE THREAD

**Issue by did1979** [kimai/kimai#4903]
### Describe the issue

Hello,

I have just launch the upgrade from 2.11.0 to 2.17.0. and now I get this error when I try to add a task in the calendar or with the quick_entry link.
I have followed the upgrade process. So why do I get this Error 500?

Here is my php log il var/log/prod.log.

Thanks.
Didier

```log
[2024-06-06 14:47:47] [request] INFO: Matched route "patch_timesheet". {"route":"patch_timesheet","route_parameters":{"_route":"patch_timesheet","_controller":"App\\API\\TimesheetController::patchAction","id":"71385"},"request_uri":"http://temps.cariforefnormandie.fr/api/timesheets/71385","method":"PATCH"} []
[2024-06-06 14:47:47] [request] CRITICAL: Uncaught PHP Exception Error: "Class "Doctrine\ORM\Query\TokenType" not found" at Date.php line 29 {"exception":"[object] (Error(code: 0): Class \"Doctrine\\ORM\\Query\\TokenType\" not found at /var/www/kimai2/src/Doctrine/Extensions/Date.php:29)"} []
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.17.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Logfile

[2024-06-06 14:47:47] [request] INFO: Matched route "patch_timesheet". {"route":"patch_timesheet","route_parameters":{"_route":"patch_timesheet","_controller":"App\\API\\TimesheetController::patchAction","id":"71385"},"request_uri":"http://temps.cariforefnormandie.fr/api/timesheets/71385","method":"PATCH"} []
[2024-06-06 14:47:47] [request] CRITICAL: Uncaught PHP Exception Error: "Class "Doctrine\ORM\Query\TokenType" not found" at Date.php line 29 {"exception":"[object] (Error(code: 0): Class \"Doctrine\\ORM\\Query\\TokenType\" not found at /var/www/kimai2/src/Doctrine/Extensions/Date.php:29)"} []

**Comment by did1979** [comment]
I verified and in the folder of the library Doctrine there is no Token class file. So maybe there is a problem in the composer.json file with the version of doctrine.

Thanks.

```bash
ls vendor/doctrine/orm/lib/Doctrine/ORM/Query/
drwxrwxr-x 3 didier www-data   4096 Jan 26 20:41 AST
drwxrwxr-x 2 didier www-data   4096 Jan 26 20:41 Exec
drwxrwxr-x 2 didier www-data   4096 Jan 26 20:41 Expr
-rw-rw-r-- 1 didier www-data  19211 Jan 26 20:41 Expr.php
drwxrwxr-x 2 didier www-data   4096 Jan 26 20:41 Filter
-rw-rw-r-- 1 didier www-data   7323 Jan 26 20:41 FilterCollection.php
-rw-rw-r-- 1 didier www-data   7544 Jan 26 20:41 Lexer.php
-rw-rw-r-- 1 didier www-data   2171 Jan 26 20:41 Parameter.php
-rw-rw-r-- 1 didier www-data   1818 Jan 26 20:41 ParameterTypeInferer.php
-rw-rw-r-- 1 didier www-data 120712 Jan 26 20:41 Parser.php
-rw-rw-r-- 1 didier www-data   3872 Jan 26 20:41 ParserResult.php
-rw-rw-r-- 1 didier www-data   1695 Jan 26 20:41 Printer.php
-rw-rw-r-- 1 didier www-data   7385 Jan 26 20:41 QueryException.php
-rw-rw-r-- 1 didier www-data   6337 Jan 26 20:41 QueryExpressionVisitor.php
-rw-rw-r-- 1 didier www-data  16803 Jan 26 20:41 ResultSetMapping.php
-rw-rw-r-- 1 didier www-data  19843 Jan 26 20:41 ResultSetMappingBuilder.php
-rw-rw-r-- 1 didier www-data  97856 Jan 26 20:41 SqlWalker.php
-rw-rw-r-- 1 didier www-data  14551 Jan 26 20:41 TreeWalker.php
-rw-rw-r-- 1 didier www-data  21986 Jan 26 20:41 TreeWalkerAdapter.php
-rw-rw-r-- 1 didier www-data  26346 Jan 26 20:41 TreeWalkerChain.php
-rw-rw-r-- 1 didier www-data   3546 Jan 26 20:41 TreeWalkerChainIterator.php
```

**Comment by did1979** [comment]
I think I've found the solution 👍 
I tried to make a composer update and now it's OK.
I think you should update the Upgrade documentation page to add the composer update command. Otherwise, we stay in 2.8 Doctrine/ORM version and the 2.19 there is :
```
Deprecate Doctrine\ORM\Query\Lexer::T_* constants
Use Doctrine\ORM\Query\TokenType::T_* instead.
```
Thanks ! 
Didier

**Comment by kevinpapst** [comment]
You mean this page:
https://www.kimai.org/documentation/updates.html

![image](https://github.com/kimai/kimai/assets/533162/f5cc824b-d7cc-4830-b310-cc34d69d36be)

No, updating composer dependencies is **NOT** a solution. 
You might get invalid dependencies. 
I cannot provide support for such an installation.

**Comment by did1979** [comment]
Ok, but I think we need to update the composer : Upgrading doctrine/orm (2.17.4 => 2.19.5). So what is the good way to do the update ?

**Comment by kevinpapst** [comment]
Thats what should be installed: https://github.com/kimai/kimai/blob/main/composer.lock#L1390

There are thousands of test running before a new release is published. 
If something basic like that it doesn't work on your end, it is an issue on your end and not with Kimai.

Let me guess , LDAP user? 
See https://www.kimai.org/documentation/updates.html#changed-files
