### ISSUE TITLE
You can't stop time on one project and then immediately start on the next

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4905]
### Describe the issue

Test case

1. Disable "Allow overlapping time entries"
2. Start tracking time on project A
3. Stop tracking time on project A
4. Start tracking time on project B

Expected outcome

Entry A is recorded and entry B begins.

Actual outcome

> You already have an entry for this time.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

### Screenshots

![Screenshot 2024-06-07 at 12 28 51](https://github.com/kimai/kimai/assets/382183/8543ed65-ae3a-49d1-8ad5-21c03ecc04ad)

---

# Discussion

I guess I understand *why* this is happening, based on my understanding of the inner workings (implementation details) of the system.

Because the time entry for project A ends at 12:32 (presumably at 12:32:59.999999) and then the second project wants to start also at 12:32 (presumably 12:32:00.000000), which overlap.

However, my staff did not actually TRY to make overlapping times, they were just hurt by the implementation details of the system.

The system should specifically handle this case better because:

1. it is very common for somebody to record time on one project and then immediately on another
2. a manager doesn't want overlapping times (disallow overlapping times)
3. literally speaking, the worker honestly did not attempt to double-bill their time

**Comment by fulldecent** [comment]
The above is a reproducible test that I have created myself

**Comment by kevinpapst** [comment]
That happens because of your rounding rules.
This doe snot happen if you use the default rules. 

If you round your end time up it will be in the future if you use the stop button.
If you now start the timer again (you make it worse if you round the start time up), the times will be overlapping.

Only the administrator can fix this situation.

**Comment by fulldecent** [comment]
I have the standard rounding rules:

![Screenshot 2024-06-07 at 16 31 41](https://github.com/kimai/kimai/assets/382183/1a4072df-46b0-4d15-a85b-a2afc4949dda)

What should I change them to?

---

Ending the timer and then immediately starting a new project is a such a common use case. I think this should be supported under any possible settings. And if the settings don't make sense then special cases and explanations should be added.

**Comment by kevinpapst** [comment]
Please retry with `Floor` or `Ceil`
