### ISSUE TITLE
DOS attack: you cannot stop the time if you started in the future

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4907]
### Describe the issue

If you start the time in the future, it is impossible to stop the time except to wait until that future time.

Error:

> Time recording could not be stopped
>
> End date must not be earlier then start date.

It is possible that you might intentionally set your start time in the future because you are doing a workaround for this issue: https://github.com/kimai/kimai/issues/4905

---

I didn't try it but maybe if you accidently set the start time as next year then you would be locked out of the system until next year.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

### Screenshots

![Screenshot 2024-06-07 at 12 44 46](https://github.com/kimai/kimai/assets/382183/7e56abc8-fbde-4377-9d61-5a058365f35a)

https://github.com/kimai/kimai/assets/382183/af639861-ae00-40a3-a992-cb0196ca279f

**Comment by kevinpapst** [comment]
RTM? 
https://www.kimai.org/documentation/timesheet.html#stop-records

**Comment by kevinpapst** [comment]
I will make sure to update the docs to make it clearer that this matches for all of these "cannot stop timesheet **errors**".
