### ISSUE TITLE
Exclude the three dots from clicking the whole entry

### ISSUE THREAD

**Issue by niels-przybilla** [kimai/kimai#4908]
### Describe the problem

When i want to duplicate or restart a time entry i have to be very exact with the mouse not to open the time entry itself

### Describe the solution you'd like

exclude the last part from clicking to open the whole line.

![Monosnap 0:00 2024-06-08 19-15-36](https://github.com/kimai/kimai/assets/99684821/db24f42b-f89e-438e-877c-ca2deb536263)

**Comment by kevinpapst** [comment]
Are you aware that you can use the context-menu on all of these listing views?
Right click anywhere on the row and you will see that action menu.

**Comment by niels-przybilla** [comment]
deep facepalm for my stupidity :-) ... Thank you very much!
