### ISSUE TITLE
Custom content: Always expand extended timesheet settings not working (in Demo)?

### ISSUE THREAD

**Issue by Sarmingsteiner** [kimai/kimai#4909]
### Describe the issue

We are preparing to change from Kimai1 to Kimai2. Since we have done a lot of customization in Kimai1, we have to check many things beforehand.

One important thing for us is to always expand extended timesheet settings. According to the documentation, this should be possible with the custom content plugin and the following JS code:
```
document.addEventListener('show.bs.modal', (e) => { 
    e.srcElement.querySelector('#timesheet_extended_settings a[data-bs-toggle]')?.click(); 
});
```
However, in the demo installation, logged-in as admin, this code does not seem to work. Any ideas?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.17.0 (Demo)

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

Unknown

**Comment by kevinpapst** [comment]
Issues for paid plugins go here: https://github.com/kimai/Paid-plugins

This time it is not necessary, the documentation is updated.
