### ISSUE TITLE
Remove sensitive data from debug

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#491]
The following keys should not be displayed in the debug log of kga:
- kga[password_salt]
- kga[user][password]
- kga[user][apikey] - probably leave it until it can be edited (why is that field gone?)

**Comment by ServiusHack** [comment]
Agreed, these fields should not be displayed. Instead of leaving the apikey in there a field in the user floater should just be added, it's not that much work. Skimming through changes related to the api key I couldn't see that field being there at any point.

**Comment by kevinpapst** [comment]
I am so sure that I added the field in the past, completely weird. But true, its not that much work.
