### ISSUE TITLE
Cannot select a project, admin not notified

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4911]
## Background

The project dropdown box is not able to select a project for some people on our team. This may possibly be a configuration issue about how I as admin have misused the product. But this issue is not about the configuration problem. This issue is that Kimai failed to notify me of this problem and I had to wait to hear about it from staff.

## Issue

**The issue I am reporting is that Kimai did immediately send me an email or notify me when it happened that one of my staff was not able to start logging time.**

Please note that timekeeping is business critical software. If Kimai stops working, all my staff stop working, and each one of them calls me on the phone, and my entire business stops. If I am sleeping, I must be woken up.

## Recommended solutions

1. If somebody loads the time entry screen, and it is impossible for them to make/start a time entry (because of unable to select project, or any other reason), then immediately email the administrator and tell them what happened and how to fix it. 

Please note in this situation, every time, that person will ALSO being receiving a phone call or email from the worker themself. Receiving the email Kimai directly will be useful.

2. If the system is in some configuration state where any of the users could possibly get in to the (1.) situation then immediately show an error message and help to fix it.

This allows to avoid problems before they happen.

## Screenshots

![Screenshot 2024-06-12 at 10 29 28](https://github.com/kimai/kimai/assets/382183/4a3fb19b-aa91-4dad-aff5-610f8c2deefa)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

**Comment by fulldecent** [comment]
Related issue: it is possible that just the page is loading slowly (separate issue and proposed fix: https://github.com/kimai/kimai/issues/4870).

**Comment by kevinpapst** [comment]
This is not a bug.
No data available => empty dropdown (or in case of customer missing dropdown).

Kimai cannot detect whether a setting is on purpose or if it happened accidentally.
This will not be changed.

**Comment by fulldecent** [comment]
![Screenshot 2024-06-12 at 22 10 03](https://github.com/kimai/kimai/assets/382183/030ca265-6cdc-4fef-9865-61123d9fbfe0)

**Comment by fulldecent** [comment]
^ This latest screenshot indicates that the system does allow tracking. But only if you do it one way and not the other way. This is a bug.

---

Regarding this:

> Kimai cannot detect whether a setting is on purpose or if it happened accidentally.

Yes, it should be assumed that if an administrator is using Kimai and one of their staff cannot track their time that this in not on purpose.

The purpose of Kimai is to track time. Not tracking time is a problem.

**Comment by fulldecent** [comment]
If everybody is confused and the software doesn't tell you right there how to fix it, the software is broken.

![Uploading Screenshot 2024-06-14 at 12.31.17.png…]()

**Comment by fulldecent** [comment]
The software doesn't tell you what's wrong, and I have tried MANY settings: customers, teams, project, activities... and my staff are all still purplexed.

The permanent solution is that if time cannot be logged, ALARMS, WARNINGS, and EMAILS should be dispatched by Kimai to the people that can fix it, explaining what to do.

And explanations and actionable advice should be shown to the innocent workers that are unable to log their time.

Anything less results in sad people, not getting paid for their work, hopelessly posting on Slack, decreasing morale at the company :-(

![Screenshot 2024-06-14 at 13 22 39](https://github.com/kimai/kimai/assets/382183/b3616a41-42d0-40bb-bb07-d5d1aa9d092b)

**Comment by kevinpapst** [comment]
We can do a 1:1 screenshare and I bet that this is a team permission problem.

Did you setup global activities or project activities?
If the activities are project related, then the dropdown is empty until you select a project.
If the project dropdown is empty, it means you restricted visibility on the customer.
If you have only one customer, you can remove all teams from it.
Then you can restrict projects one by one, by adding teams to them.
