### ISSUE TITLE
Rationalise the docker labels

### ISSUE THREAD

**Issue by tobybatch** [kimai/kimai#4918]
### Describe the problem

Historically we have supported a number of docker tags:

## Built containers

All conatiners are built using kimai versin number, e.r. `kimai/kimai2:fpm-2.18.0-prod`, these are also tagged without the version number as:

 * kimai/kimai2:fpm-prod
 * kimai/kimai2:fpm-dev
 * kimai/kimai2:apache-prod
 * kimai/kimai2:apache-dev

## Aliased tags

 * kimai/kimai2:fpm-prod -> kimai/kimai2:fpm
 * kimai/kimai2:fpm-prod -> kimai/kimai2:fpm-latest
 * kimai/kimai2:fpm-prod -> kimai/kimai2:latest
 * kimai/kimai2:fpm-prod -> kimai/kimai2:prod
 * kimai/kimai2:apache-prod -> kimai/kimai2:apache
 * kimai/kimai2:apache-prod -> kimai/kimai2:apache-latest
 * kimai/kimai2:apache-dev -> kimai/kimai2:dev

The list of aliased tags is supporting older documentation and set up. If you had a docker compse set up that used the image `kimai/kimai2:fpm-prod` that will only ever use the latest tagged `kimai/kimai2:fpm` image.

I'm suggesting that we drop the tagging of all aliases except `:latest`. The latest tag will be automaticaly assigned to the last built image by the docker repo, and in our case will probably the apache dev image.

This will clean up the docker repo and eliminate a lot of historical cruft. The only issue will be people potentiallt running older versions of Kimai and missing features/patches.

### Describe your setup and add your Docker compose file (redact your credentials)

N/A

**Comment by sharky98** [comment]
It's been a while I worked with PHP, but if there is no adverse effect, maybe dropping also the "dev" tags. The reasoning is that typically, Docker image published are for production usage. Having the "dev" tag may create confusion (at least it did for me when I first started using the images!).

Another suggestion, going a step further, would be to have a gradient in the tags, similar to what [the node image](https://hub.docker.com/_/node) is doing. They have three OS alternatives, with a prefered one. They start with the basic major version and then each element is optional, using the latest or the prefered version. And `latest` tag is assigned to the greatest and latest version with all prefered options.

Based on their tags pattern, Kimai tags could be as follows.

```
kimai/kimai2:X.Y.Z-OS-VARIANT
             │ │ │ │    │
             │ │ │ │    └── Build type:   prod | dev
             │ │ │ └─────── Kimai flavor: fpm  | apache
             │ │ └───────── Patch Version
             │ └─────────── Minor Version
             └───────────── Major Version

kimai/kimai2:latest-OS-VARIANT
               │    │    │
               │    │    └── Build type:   prod | dev
               │    └─────── Kimai flavor: fpm  | apache
               └─────────── Indicate the latest release
```

This would produce tags as follows, assuming Apache is the prefered flavor and prod is the prefered build type. This may no reduce the number of tags, but in my view it would clarify a lot their usage.

- Apache
  - Prod
    - Main image: `kimai/kimai2:2.18.0-apache-prod`
    - `latest` alias
      - `kimai/kimai2:latest`
      - `kimai/kimai2:latest-apache`
      - `kimai/kimai2:latest-apache-prod`
    - Version X alias
      - `kimai/kimai2:2`
      - `kimai/kimai2:2-apache`
      - `kimai/kimai2:2-apache-prod`
    - Version X.Y alias
      - `kimai/kimai2:2.18`
      - `kimai/kimai2:2.18-apache`
      - `kimai/kimai2:2.18-apache-prod`
    - Version X.Y.Z alias
      - `kimai/kimai2:2.18.0`
      - `kimai/kimai2:2.18.0-apache`
      - `kimai/kimai2:2.18.0-apache-prod`
  - Dev
    - Main image: `kimai/kimai2:2.18.0-apache-dev`
    - `latest` alias
      - `kimai/kimai2:latest-dev`
      - `kimai/kimai2:latest-apache-dev`
    - Version X alias
      - `kimai/kimai2:2-dev`
      - `kimai/kimai2:2-apache-dev`
    - Version X.Y alias
      - `kimai/kimai2:2.18-dev`
      - `kimai/kimai2:2.18-apache-dev`
    - Version X.Y.Z alias
      - `kimai/kimai2:2.18.0-dev`
      - `kimai/kimai2:2.18.0-apache-dev`
- FPM
  - Prod
    - Main image: `kimai/kimai2:2.18.0-fpm-prod`
    - `latest` alias
      - `kimai/kimai2:latest-fpm`
      - `kimai/kimai2:latest-fpm-prod`
    - Version X alias
      - `kimai/kimai2:2-fpm`
      - `kimai/kimai2:2-fpm-prod`
    - Version X.Y alias
      - `kimai/kimai2:2.18-fpm`
      - `kimai/kimai2:2.18-fpm-prod`
    - Version X.Y.Z alias
      - `kimai/kimai2:2.18.0-fpm`
      - `kimai/kimai2:2.18.0-fpm-prod`
  - Dev
    - Main image: `kimai/kimai2:2.18.0-fpm-dev`
    - `latest` alias
      - `kimai/kimai2:latest-fpm-dev`
    - Version X alias
      - `kimai/kimai2:2-fpm-dev`
    - Version X.Y alias
      - `kimai/kimai2:2.18-fpm-dev`
    - Version X.Y.Z alias
      - `kimai/kimai2:2.18.0-fpm-dev`

**Comment by chinmaypurav** [comment]
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/22b40709-e73f-490c-9f02-6435e79627da">


I would like to add, `linux/arm64` architecture is missing in the latest/fpm tags.

I specifically need `linux/arm64` as I am deploying it on my Raspberry Pi or try to run on my Mac Book Pro.

I eventually got it to work by locally building the image; ideally would love to have the arch as a consistent thing

**Comment by kevinpapst** [comment]
@chinmaypurav fixed with the latest release.

@sharky98 thanks, but you are actually proposing to make it more tags instead of less

@tobybatch I worked on docker installations and docs and wrote down the list of tags at: https://www.kimai.org/documentation/docker.html

And I think we can safely deprecated the following tags:
```
kimai/kimai2:apache-prod: same as kimai/kimai2:apache
kimai/kimai2:apache-latest: same as kimai/kimai2:apache
kimai/kimai2:fpm-prod: same as kimai/kimai2:fpm
kimai/kimai2:fpm-latest: same as kimai/kimai2:fpm
kimai/kimai2:prod: same as kimai/kimai2:fpm
kimai/kimai2:apache-dev: development image based on Apache
kimai/kimai2:fpm-dev: development image based on PHP-FPM Alpine
```

If someone uses one of these tags and doesn't receive updates, it is easy to fix.

So we should definitely get rid of these tags. 
And probably also the version specific `dev` images `kimai/kimai2:apache-x.xx.x-dev` and `kimai/kimai2:fpm-x.xx.x-dev`. 

But I am not sure about switching `latest` from `fpm` to `Apache` right now. 
That would be a HUUUUUUGE BC Break and I already see all the complaints coming in.

**Comment by kevinpapst** [comment]
Here is the PR, can you please have a look @tobybatch : https://github.com/kimai/kimai/pull/4995
