### ISSUE TITLE
"All privileges" does not necessarily grant show/create database permission on some shared hosts.

### ISSUE THREAD

**Issue by PowerInside** [kimai/kimai#492]
I was trying to install Kimai on a shared host called hostinger, and their cPanel only allows creating 
databases from the web interface. Kimai Installer however looks for the MySQL privilege called "ALL PRIVILEGES" and assumes that "show" and "create" database is true, which is not always the case.

Problem is here: https://github.com/kimai/kimai/blob/master/core/installer/steps/60_db_select_mysql.php#L39

Solution: I commented the line 40 and 41 and was able to install it fine. (ie, $showDatabasesAllowed and $createDatabaseAllowed should both be false; since my shared host did not support it)

**Comment by simonschaufi** [comment]
thanx for looking into this.

**Comment by kevinpapst** [comment]
Hey @PowerInside - I know this quite a while ago since you opened the issue.
Thanks for your feedback. If you want, you could try the latest master and let us know if the solution worked for you.
