### ISSUE TITLE
Unable to create initial user from CLI

### ISSUE THREAD

**Issue by kale1d0code** [kimai/kimai#4920]
### Describe the issue

I am attempting to create the initial user using the kimai:user:create command

this throws an error message:
```
CRITICAL  [console] Error thrown while running command "kimai:user:create <REDACTED> '<REDACTED>' ROLE_SUPER_ADMIN". Message: "An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory" ["exception" => Doctrine\DBAL\Exception\ConnectionException^ { …},"command" => "kimai:user:create <REDACTED> '<REDACTED>' ROLE_SUPER_ADMIN","message" => "An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory"] ["channel" => "console"]
```

web interface is accessible.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.18.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

### Logfile

couldn't find log file at /opt/kimai/var/log/prod.log
or /var/log/prod.log

docker logs only show web access logs

**Comment by kale1d0code** [comment]
can I have the sql for creating a user?

**Comment by kale1d0code** [comment]
I think I've figured this out.

the DATABASE_URL environment variable is only accessible by the initial process.

I'll try to start up the container with a command to create the user, however this will be tricky due to the password requiring an interactive shell

**Comment by kale1d0code** [comment]
I've gotten this working with the following command for the container
```
    command: >
      bash -c '
      export DATABASE_URL="mysql://$$DB_USER:$$DB_PASS@dbms/$$DB_BASE?charset=utf8mb4";
      echo "using url: $$DATABASE_URL";
      /opt/kimai/bin/console kimai:user:create "$ADMIN_USER" "$ADMIN_EMAIL" "$ADMIN_ROLE" "$ADMIN_PASS"
      '
```

this constructs the DATABASE_URL environment variable. echoes out (for debugging). and then runs the command for creating the user.

environment variables with a double dollarsign are resolved within the container.
environment variables with a single dollarsign are resolved within the stack and their values are sent to the container.

This would only be required if you construct your DATABASE_URL environment variable instead of providing it in full

**Comment by kevinpapst** [comment]
i doubt it, oterwise every docker user would run into that problem.
maybe some initialization failed due to the urlencode issue?

**Comment by kevinpapst** [comment]
#4976 added URL encoding to the database url parts
