### ISSUE TITLE
Disable Modules/Sections

### ISSUE THREAD

**Issue by kale1d0code** [kimai/kimai#4921]
### Describe the problem

It is great that the system provides functionality for invoices, reporting, etc
We have systems which already provide such functions and would like to disable these sections of the app client and server side.

### Describe the solution you'd like

an administration page with toggles to turn features on and off within kimai

### Describe alternatives you've considered

short term - css to hide menu items

long term - learn how kimai works, find where modules are initialised and remove modules which are not required.

**Comment by kevinpapst** [comment]
> long term - learn how kimai works

you can deactivate most of the additional features through permissions, see System > Roles.
https://www.kimai.org/documentation/permissions.html#existing-permissions
