### ISSUE TITLE
Implement correct localized date and time formats

### ISSUE THREAD

**Issue by milotype** [kimai/kimai#4926]
### Describe the issue

Currently date and time formats are not properly localized in "demo" pages. In this case Croatian language.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

Demo versions

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

Unknown

### Screenshots

<img width="886" alt="Date and time form 01" src="https://github.com/kimai/kimai/assets/43657314/d8fe7427-285f-483c-b150-bab6509c108b">

<img width="1066" alt="Date and time form 02" src="https://github.com/kimai/kimai/assets/43657314/dc311013-3d40-4886-b1ca-06d3bf3581e8">

<img width="765" alt="Date and time form 03" src="https://github.com/kimai/kimai/assets/43657314/ae055b39-cfa2-4014-8e3d-fcced741d17e">

**Comment by kevinpapst** [comment]
Have you switched to Croatian format as well?

<img width="402" alt="Bildschirmfoto 2024-06-21 um 19 54 07" src="https://github.com/kimai/kimai/assets/533162/bb00a511-db3a-41db-ae09-1e945992e3d6">

The format definition is here:
https://github.com/kimai/kimai/blob/main/config/locales.php#L1458

**Comment by milotype** [comment]
@kevinpapst 
After switching to Croatian in the Preferences, pages display translated.
