### ISSUE TITLE
Error message "There was a problem saving / You already have an entry for this time" missing needed detail and help

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4929]
### Describe the issue

Under some reasonable circumstance, where a normal worker is trying to record their time they will see this message:

> There was a problem saving
>
> You already have an entry for this time

This message is insufficiently detailed, and it causes the worker to escalate the issue to me. Therefore this is a bug.

---

Solution:

Kimai should use available information to inform the worker how to fix the problem themself.

* If a time already exists in the system, show details for that other recorded time.
* If the problem is an off-by-one error or a rounding error, silently do something to just fix the problem without causing an error message. (I still consider https://github.com/kimai/kimai/issues/4905 an unresolved bug.)

Related issues:

* It is possible that worker will click "stop time" and the server will be unresponsive, and then they will open another tab and click it again, causing the "you already have an entry" error. This can be caused by the server responding too slowly. (I still consider https://github.com/kimai/kimai/issues/4870 an unresolved bug.)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

### Screenshots

![Screenshot 2024-06-24 at 10 45 56](https://github.com/kimai/kimai/assets/382183/a7a47ab6-f156-4cc4-965a-f2fc9a5a4d1a)

**Comment by kevinpapst** [comment]
Not a bug
