### ISSUE TITLE
Buzzer gets inactive again right after starting it

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#493]
Through debugging of the javascript i found out that (on one server only) the requests and responses vary between different servers which result in different results.

1. Request: axAction:"setTimeframe"
2. Request: axAction:"startRecord" 
3. Request: axAction:"reload_timeSheet" with response content: updateRecordStatus(false);
4. Request: axAction:"reload_timespan" with response content: Zeitspanne:  <b>xx.xx.2015 - xx.xx.2015</b>
5. Request: axAction:"reload_timeSheet" with response content: updateRecordStatus(1286, 1434502313,...)

The problem lies here at the 3rd request. On my localhost i get the response like this:
updateRecordStatus(1276, 1434502997,...

It is reproducable but I don't know where exactly lies the problem as the files AND the db are identical on both systems.

I just know that here the $kga['customer'] variable is not set on one system and the other one it is set: https://github.com/kimai/kimai/blob/master/core/extensions/ki_timesheets/init.php#L60

**Comment by ServiusHack** [comment]
There is only one place where `$kga['customer']` is set and that is here:
https://github.com/kimai/kimai/blob/master/core/libraries/Kimai/Database/Mysql.php#L2559

This, again, is only called from `checkuserInternal` in the same class. The whole login process is started from the `checkUser` function in `includes/func.php`. This 'customer_' prefix should only be set if the currently logged in user is a customer. Please check why your login is identified as a customer login instead of the login of a real user. (Or is the buzzer shown for a logged in customer?)

**Comment by simonschaufi** [comment]
can somebody explain me why reload_timeSheet is called twice?

i figured out, the main problem is here in this line: https://github.com/kimai/kimai/blob/master/core/extensions/ki_timesheets/processor.php#L372

**Comment by ServiusHack** [comment]
So It's basically race condition.

Starting from `function buzzer()` these are the code paths:

* `setTimeframe`
  *  ajax call setTimeframe
    * asyncronous response calls `hook_timeframe_changed` which calls `timesheet_extension_timeframe_changed` which calls `ts_ext_reload`
* `startRecord`
  * ajax call startRecord
    * asynchronous response calls `ts_ext_reload`

We can probably just call setTimeframe after the startRecord ajax response. I think it is only called to make sure that the running entry is being displayed. Maybe even that can be removed as the state whether the buzzer is running or not is now detected independant of what is shown to the user.

**Comment by simonschaufi** [comment]
> We can probably just call setTimeframe after the startRecord ajax response. I think it is only called to make sure that the running entry is being displayed. Maybe even that can be removed as the state whether the buzzer is running or not is now detected independant of what is shown to the user.

sounds like a good idea!

**Comment by HenryNe** [comment]
> We can probably just call setTimeframe after the startRecord ajax response. I think it is only called to make sure that the running entry is being displayed.

If the setTimeframe would fail on server, the call ts_ext_reload would not help to display the running entry.

Simply not call ts_ext_reload in startRecord.

If setTimeframe was called successfully with server response, then the hook will call ts_ext_reload.
If nothing changed on the timesheet, or if the timesheet is not active, then not need to call ts_ext_reload. That is handled in the hook.

**Comment by simonschaufi** [comment]
fixed via #690
