### ISSUE TITLE
Installer fails after selecting time zone

### ISSUE THREAD

**Issue by skosonen** [kimai/kimai#494]
0.9.3 RC and dev Installer tries to load "/installer/steps/30_select_layer.php" after selecting time zone, but this file doesn't exist and the installation procedure cannot continue.

**Comment by simonschaufi** [comment]
not reproduceable with current git master.

**Comment by skosonen** [comment]
For me workaround was to install stable version and update to beta.

- Sami

**Comment by simonschaufi** [comment]
Can I close this issue then?

**Comment by skosonen** [comment]
This issue happened with the RC 0.9.3 version. Maybe my browser used some cached pages from the Stable 0.9.2 version I installed in the same URL just few minutes earlier?

**Comment by simonschaufi** [comment]
This could be, because the steps are in a javascript file which is cached in the browser.
