### ISSUE TITLE
tiny changes in main.js

### ISSUE THREAD

**Issue by claude-ws01** [kimai/kimai#496]
Hello,

v0.9.3rc1
timesheet panel: prohibited edition of customers (according to rules I have set)
issue: the "floater" window frame still fades-in (without content, obviously).

So I did some modifications.
file: core/js/main.js
modified code:

``` javascript
function floaterLoadContent(phpFile, axAction, axValue, id, width, callback) {
    $("#floater").load(phpFile,
        {
            axAction: axAction,
            axValue: axValue,
            id: id
        },
        function () {
            var floater = $('#floater'),
                el, x;

            if (floater[0].innerHTML != '') {
                floater.css({width: width + "px"});

                resize_floater();

                x = ($(document).width() - (width + 10)) / 2;
                if (x < 0) x = 0;
                floater.css({left: x + "px"});
                floater.fadeIn(fading_enabled ? 200 : 0);

                $('#focus').focus();
                $('.extended').hide();
                $('#floater_content').css("height", $('#floater_dimensions').outerHeight() + 5);

                // toggle class of the proberbly existing extended options button
                $(".options").toggle(function () {
                    el = $(this);
                    el.addClass("up");
                    el.removeClass("down");
                    return false;
                }, function () {
                    el = $(this);
                    el.addClass("down");
                    el.removeClass("up");
                    return false;
                });

                if (callback != undefined)
                    callback();
            }
        }
    );
}
```

There probably is a better way to test what is returned by the ".load". You tell me. :)

---

While I'm here...  another tiny modification in the same file.
function buzzer().  (the stop-watch button)
changed from:

``` javascript
    if (currentRecording > -1) {
        stopRecord();
        currentRecording = 0;
```

to

``` javascript
    if (currentRecording > -1) {
        stopRecord();
        currentRecording = -1;
```

because once I stopped the watch, I could not restart it again, unless I refresh the page.
I did not do a long investigation on that one. So if it should have been done differently, you tell me.

Thank you

Claude.

**Comment by kevinpapst** [comment]
Hey Claude, 
thanks for your contribution! Is it possible for you to sent in pull requests instead of these written descriptions which code needs to be changed where?
Apart from that, thanks for taking your time to make Kimai better!
Regards
Kevin

**Comment by cloudeasy** [comment]
Hi Kevin...

I will try :)
But it may be a bit overwhelming, as I'm reformating (inside phpStorm) 
whole file when I get it.
But I will try.

regards

Claude.

**Comment by kevinpapst** [comment]
Oh no, no white space changes please. That is not a good idea at all. 
You might have other preferences, we might too ;-) but please only sent in code changes, no reformattings!

**Comment by cloudeasy** [comment]
Hello Kevin,

I try to follow PSR-1-basic-coding-standard 
<https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md> 
and PSR-2-coding-style-guide 
<https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md> 
standards as much as I can.

I noticed that it is not the case in Kimai, which I respect, and that is 
why I just sent you the modifications :)

regards

C.

**Comment by kevinpapst** [comment]
I do as well, but Kimai is a grown piece of software, which was written by a lot of people and there were no rules in the beginning. We want to clear up a lot after the next release.

**Comment by simonschaufi** [comment]
I think this can also be closed since #504 is already merged.

**Comment by simonschaufi** [comment]
no, not everything but some parts of it.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
