### ISSUE TITLE
Teamlead of Team A sees Tasks from Team B in Timesheet

### ISSUE THREAD

**Issue by AB-C360** [kimai/kimai#4967]
### Describe the issue

I have these teams as an example

Team 1: User 1 (teamlead), User 2, User 3
Team 2: User 1, User 2 (teamlead), User 3

Users are shared between teams but there are different teamleads on each team. Team 1 is assigned to project 1 and Team 2 to project 2.

User 1 checks timesheet and sees tasks done by User 2 and 3 that are from project 1 but also from project 2. 

In my understanding User 1 should only see in his timesheet his tasks and tasks from User 2 and 3 regarding project 1 but not from project 2. Is this correct?

Thanks

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.18.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
No. That is how Kimai works.
If you are a teamlead of User B you can see all timesheets of User B.
Team assignments are not checked when vieweing, only when reporting.

**Comment by AB-C360** [comment]
So there is no way in kimai of having 2 projects each one with one different lead where each lead can see the times of only the project where he is the lead? I'm not sure if i understood correctly that this can't be possible in the timesheet view but it can be achieved in the project view?

Is this not a common thing? In companys you normally have different projects in which a project lead needs to report the times to his superiors.
