### ISSUE TITLE
Undefined variable: customerID

### ISSUE THREAD

**Issue by cloudeasy** [kimai/kimai#499]
hello
some tipo error
file; libraries/Kimai/Database/Mysql.php
replace:
```php
	if (strncmp($kimai_user, 'customer_', 4) == 0) {
```
with
```php
	if (strncmp($kimai_user, 'customer_', 9) == 0) {
```

c.

**Comment by simonschaufi** [comment]
bug introduced here: https://github.com/kimai/kimai/commit/963286a0de08c3f68c89718ab0c6c69821c34315#diff-ab5dc60038ee883760377e014c86e135R2436
