### ISSUE TITLE
Automatically update dashboard after saving a time entry

### ISSUE THREAD

**Issue by RKLBusinessDevelopment** [kimai/kimai#4993]
### Describe the problem

The dashboard with with the overview of all recorded time entries should automatically updated/refresh when a new time entry is saved.

### Describe the solution you'd like

Just refresh the dashboard when a new time entry is saved.

**Comment by kevinpapst** [comment]
Thanks for your post! But this is nothing I do consider right now.

**Comment by RKLBusinessDevelopment** [comment]
Could you please elaborate as to why not? This shouldn't be too hard to implement, so I'd like to understand the reasoning behind that decision to decide if it is worth to open any other issues in the future. Thank you.

**Comment by kevinpapst** [comment]
The only viable solution are websockets and that is way too complicated for the expected benefit. 

You are welcome to provide a PR if it is easy to implement. 
Please always post new ideas. 
But I can obviopusly NOT implement every idea every user has, otherwise Kimai would be a complete mess.
