### ISSUE TITLE
Iframe https Mixed content

### ISSUE THREAD

**Issue by corentin-begne** [kimai/kimai#4994]
### Describe the issue

I am trying to integrate Kimai within an iFrame through the external application feature in Nextcloud. However, I am encountering a mixed content error. Kimai seems to be making HTTP requests even though the site is served over HTTPS, which results in the mixed content warning in the browser.
I have found this thread that discusses a similar issue related to reverse proxies: [Forum Thread](https://forum.cloudron.io/topic/4848/mixed-content-warning-while-embedding), but my setup does not involve a reverse proxy because I use the cloned repo directly with Apache in Ubuntu 22.04 not a reverse proxy with the image inside docker.
Anyway you can see the same behavior outside the iframe, you've got a double access, http which redirect to https.
If I logging outside iframe after it works but it seems the redirection to the login page and all login requests makes this isssue.
Can you help me please ?
Thx !

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.13.0

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
This is an issue on your end.

**Comment by kevinpapst** [comment]
Either an invalid redirect or webserver config.
Combined with a aggressive browser cache. Use private mode.

**Comment by corentin-begne** [comment]
I have the problem even in private mode.
I use the apache config provided by kimai documentation
https://www.kimai.org/documentation/webserver-configuration.html
Why the issue occur only on the login redirection ?
I tried many things but nothing working I always have the first redirection in http 200 Temporary Redirect.
What could I do ?

**Comment by corentin-begne** [comment]
Do you have any clues of what could do that on my side ?
As I see it's like there's an http redirection hardcoded on your side on the redirections, I try many config in Symfony and server configuration but noting working.

**Comment by kevinpapst** [comment]
> As I see it's like there's an http redirection hardcoded on your side on the redirections

There is no "my side".
There is no "hard-coded" redirect.
If you request http, there is a redirect to http. That is exactly as it should be.
If your reverse proxy is not correctly forwarding the necessary headers then the protocol might be mis-identified.
I am pretty sure this is an issue in the virtual host config of your reverse proxy.
