### ISSUE TITLE
500 (Internal Server Error)

### ISSUE THREAD

**Issue by cloudeasy** [kimai/kimai#500]
Hello,

Just for your information... I was getting this error when adding a new user.
I pinned the issue to the mysql class. More precisely, in the attempt to "Release" in the "MySQL->Close()".
A 500 error is the kind I do not get any error message from php, so I simplify the resolution by trying alternatives in the programming. (I remember replacing a "switch" with an "if" to solve it)

Long story short, I removed the "release" attempt and solved it.  Furthermore, I'd like to point out my doubt in the usefulness of releasing just before closing the DB connection.

Here's the code:
file: /core/libraries/mysql.class.php
```php
    public function Close()
    {
        $this->ResetError();
        $this->active_row = -1;

        // $success = $this->Release();

        $success = @mysql_close($this->mysql_link);
        if (!$success) {
            $this->SetError();
        }
        else {
            unset($this->last_sql);
            unset($this->last_result);
            unset($this->mysql_link);
        }


        return $success;
    }
```

regards

c.

**Comment by simonschaufi** [comment]
this is a library and shouldn't be changed. Do you have access to the server logs and can figure out what exactly is the error? I cannot reproduce it.

**Comment by cloudeasy** [comment]
a. Even the best written library may need adjustment at times.
b. There is nothing to figure out. Please read again... there are no PHP error messages, nor any other.
c. I doubt you can reproduce.
d. This is just info, not a recommendation, nor a request.
thx.
c.
