### ISSUE TITLE
Incomplete delete - users

### ISSUE THREAD

**Issue by claude-ws01** [kimai/kimai#501]
Hello again,

I'm looking at the admin->membership roles, and I see a users count of 20 on the admin role... but there are only 5 users...

So, Mysql->user_delete() does not include the following related tables
  groups_users
  preferences
  rates
  timesheet
I will leave timesheet alone because of possible negative consequences, but the other tables should be cleaned of the deleted user, otherwise we are leaving dead data.

So here's my version of function user_delete():
file: libraries/Kimai/Database/Mysql.php
```php
    public function user_delete($userID, $moveToTrash = false)
    {
        $userID = MySQL::SQLValue($userID, MySQL::SQLVALUE_NUMBER);
        if ($moveToTrash) {
            $values['trash']  = 1;
            $filter['userID'] = $userID;
            $table            = $this->kga['server_prefix'] . "users";

            $query = MySQL::BuildSQLUpdate($table, $values, $filter);

            return $this->conn->Query($query);
        }

        $query  = "DELETE FROM " . $this->kga['server_prefix'] . "groups_users WHERE userID = " . $userID;
        $result = $this->conn->Query($query);

        if ($result === false) {
            $this->logLastError('groups_user_delete');

            return false;
        }

        $query  = "DELETE FROM " . $this->kga['server_prefix'] . "preferences WHERE userID = " . $userID;
        $result = $this->conn->Query($query);

        if ($result === false) {
            $this->logLastError('preferences_delete');

            return false;
        }

        $query  = "DELETE FROM " . $this->kga['server_prefix'] . "rates WHERE userID = " . $userID;
        $result = $this->conn->Query($query);

        if ($result === false) {
            $this->logLastError('rates_delete');

            return false;
        }

        $query  = "DELETE FROM " . $this->kga['server_prefix'] . "users WHERE userID = " . $userID;
        $result = $this->conn->Query($query);

        if ($result === false) {
            $this->logLastError('user_delete');

            return false;
        }

        return true;
    }
```
Ideally, it's probable that a check should be done on the other table, that depends on the user entry, before performing a delete (that's probably why the trash was put there in the first place).

correct me if you see fit. :)

Anyway, that's it for now.

c.

**Comment by simonschaufi** [comment]
thank you for your contribution but you don't consider the $moveToTrash parameter which is important. could you create a pull request? that would be great!

**Comment by cloudeasy** [comment]
Actually yes, I have considered the $moveToTrash. There are no delete when it is a move to trash. Read again. :)
