### ISSUE TITLE
Markup in Descriptions

### ISSUE THREAD

**Issue by pkoevesdi** [kimai/kimai#5022]
### Describe the problem

Currently I see no way of adding a link, a heading or some other simple markup in descriptions, for instance of projects.

### Describe the solution you'd like

Markdown rendering, including automatic rendering of URLs as clickable links.

### Describe alternatives you've considered

None

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/configurations.html#theme

**Comment by pkoevesdi** [comment]
Ah, thank You! Is there a reason why [Headings](https://github.github.com/gfm/#example-32) don't work?
