### ISSUE TITLE
Version out of sync

### ISSUE THREAD

**Issue by mundry** [kimai/kimai#5023]
### Describe the issue

Hi,

currently git tag `2.20.1` along with GitHub [release 2.20.1](https://github.com/kimai/kimai/releases/tag/2.20.1) exist. The docker image is tagged at [2.20.1](https://hub.docker.com/r/kimai/kimai2/tags?page=&page_size=&ordering=&name=2.20.1), too. However, the source code is still at [version 2.20.0](https://github.com/kimai/kimai/blob/2.20.1/src/Constants.php#L20).

This leads to doctor incorrectly detecting an update being available.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.20.1

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

### Logfile

From the docker image:
```
$ podman run --rm -it docker.io/kimai/kimai2:apache-2.20.1 sh  
# env | grep ^KIMAI=
KIMAI=2.20.1
# cat /opt/kimai/version.txt
2.20.0
# grep -w VERSION /opt/kimai/src/Constants.php
    public const VERSION = '2.20.0';
```

### Screenshots

![image](https://github.com/user-attachments/assets/eb7d2161-9eec-46f6-864c-8740b795ec7e)

**Comment by kevinpapst** [comment]
Yeah, happens sometimes. Thanks for posting. Will be fixed with the next update.
