### ISSUE TITLE
Zeiterfassung > Export > Drucken: Formatierung

### ISSUE THREAD

**Issue by JoergGiencke** [kimai/kimai#5029]
### Describe the issue

A) Bei der Druckausgabe sollte 'Preis pro Sunde' rechtsbündig sein - wie alle Preise,
<img width="197" alt="image" src="https://github.com/user-attachments/assets/12d93f8c-e796-474e-9a91-f0f23514e860">

B) Dann wäre es schön, wenn man 'Preis pro Stunde' abkürzen könnte in z.B. 'Preis/h', da die lange Überschrift der Spalte eine unnötige Breite aufzwingt und Raum verschwendet, der dann in anderen Spalten fehlt.

C) Für das Format von Datum ist standardmäßig 'dd.mm.yy' ausgewählt. Abweichend davon wird aber in der Auflistung standardmäßig 'dd.mm.yy hh:ii' verwendet. Man muss immer erst das Format hin- und herschalten, um als Datumsformat 'dd.mm.yy' in der Auflistung zu erhalten.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.20.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
Thanks, a + c will be fixed with the new release.

For b you could use the translation plugin.

**Comment by JoergGiencke** [comment]
Sehr schön! Danke!
