### ISSUE TITLE
Swagger file (OpenAPI 3.0 specification) has a lot of errors and warnings

### ISSUE THREAD

**Issue by svzi** [kimai/kimai#5042]
### Describe the issue

Hi there!

As described in the API Quickstart Guide I tried to import the Swagger Documentation into my tool of choice (namely: Insomnia for MacOS). Sadly it didn't work out. Initially I thought that Insomnia doesn't handle the file correctly, but it already shows some issues (see first attached screenshot). After that I tried some online validators for openapi and one of them (https://pb33f.io/doctor/) even called the file "a disaster". So maybe something is broken on my installation, or other API tools like Postman aren't so restrictive about errors, but at least I'm unable to import the collections into my tool of choice, Insomnia (https://insomnia.rest/).

Any help would be really much appreciated and I need to import a bunch of historic data and I don't want to create several CSV files and format them accordingly. A direkt API access would be very much preferred.

Best,
Sven 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.20.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

### Screenshots

<img width="1279" alt="Bildschirmfoto 2024-08-31 um 18 01 52" src="https://github.com/user-attachments/assets/ed6dda55-25f5-4a57-9bcf-24adc2479eb0">

<img width="547" alt="Bildschirmfoto 2024-08-31 um 18 00 55" src="https://github.com/user-attachments/assets/020afd85-a7cf-4e4f-9ebb-6388893962fe">

**Comment by kevinpapst** [comment]
Closing, because I am not interested in discussing what some tool spits out.

Don't know why you think this is even important to include. 
Your profile tells me that you don't know how it feels to receive such comments.

But I am not tolerating such posts. So I lock this topic and block your account.
