### ISSUE TITLE
Invisible entries if no team permission on projects

### ISSUE THREAD

**Issue by ccpadrian** [kimai/kimai#5049]
### Describe the issue

Some of our employees/trainees switch between teams and are granted permissions for different teams and their activities for a specific period. Once they leave the team (e.g., at the end of the month), they lose the permission to view their own activities on past projects (see picture 1), which were only accessible by their previous team. However, administrators can still view the entries they made (see picture 2).

Additionally, I noticed that as a user, you can still view your hours in the working hours tab (see picture 3), but you cannot export them for yourself (see picture 4).

I would expect that users cannot add new entries to teams they are no longer members of, nor modify existing entries in any way, to prevent inconsistencies, such as moving or altering the data. EDIT: But should always view and export them.

---
User OS Windows 10, accessing Kimai via Browser (MS Edge Version 128.0.2739.54)
Kimai OS Ubuntu 22.04

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.17.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

Picture 1: Users view on calender
![image](https://github.com/user-attachments/assets/1b6c2f6e-144d-4311-b8bf-1669dc3f3403)

Picture 2: Administrators view on users calender
![image](https://github.com/user-attachments/assets/96c599e2-01a9-40ac-961a-32756c96e6ad)

Picture 3: Users view on working hours
![image](https://github.com/user-attachments/assets/559dbe45-bd82-4976-98a8-e566696eb761)

Picture 4: Users view on exporting their hours
![image](https://github.com/user-attachments/assets/c97aa7e6-52c5-40c0-a3f5-51b0a94d9b1e)

**Comment by kevinpapst** [comment]
Can users export their hours in "My times"?
This view has a different permission restrictions than the general Export module.

**Comment by ccpadrian** [comment]
Hi,
users can indeed export their hours in "My Times."
Please see the screenshot below (the red-marked areas correspond to the blue content from the previous images).

![image](https://github.com/user-attachments/assets/150631e0-fd2e-4a03-9aca-38cffa2c87d2)

FYI: The issue remains unchanged after updating to Kimai 2.24.0.

**Comment by kevinpapst** [comment]
This screen uses a different set of permissions than personalized views.
This behavior is expected.
The next user would complain that invisble entries can be seen.

Closing as "wont fix".
