### ISSUE TITLE
WorkAround - main tab order difference between Windows and CentOS.

### ISSUE THREAD

**Issue by cloudeasy** [kimai/kimai#505]
I can not explain it, nor have time to look for the reasons.
On Windows:
![2015-07-06 15_36_34-admin - kimai](https://cloud.githubusercontent.com/assets/5797415/8531407/244855d4-23f5-11e5-8ae0-6718fdb264d2.png)

On CentOS:
![2015-07-06 15_36_20-admin - kimai](https://cloud.githubusercontent.com/assets/5797415/8531394/07cb4600-23f5-11e5-8b09-04d83e3a27e0.png)

My work around
v0.9.3rc1
file: includes/classes/extensions.class.php
public function loadConfigurations()

code added (minus last line)
```php
        //CN - keeping tab order in relation with the folder name. I got some differences between linux and windows (?!)
        $iniFile = array();
        foreach ($this->extensions as $key => $row)
        {
            $iniFile[$key] = $row['iniFile'];
        }
        array_multisort($iniFile, SORT_DESC, $this->extensions);

        closedir($handle);
```

regards
c.

**Comment by simonschaufi** [comment]
I'm quite sure it has to do with how the files/folders are stored on the filesystem. It just iterates over the folders and takes them as they are stored on the hard drive without any sorting. I also "experienced" that already.

**Comment by kevinpapst** [comment]
I had in mind that I already fixed that in the past. Seems I didn't :( 
My idea was to include a "sort" key in the config, so we can pre-sort them and let the admin still be able to change it to their needs.

**Comment by kevinpapst** [comment]
Yeah, seems I did in the next version:
https://github.com/kimai/kimai/tree/0.9.4/core/libraries/Kimai/Extension

**Comment by kevinpapst** [comment]
I am closing this one, as we don't want to spend more time with 0.9.3 (which is not yet released) as this is already "adressed".

**Comment by cloudeasy** [comment]
Oops... some errors in my code... here's the correction:
```php
        //CN - keeping tab order in relation with the folder name. I got some differences between linux and windows (?!)
        $iniFile = array();
        foreach ($this->extensions as $key => $row)
        {
            $iniFile[$key] = $row['initFile'];
        }
        array_multisort($iniFile, SORT_ASC, $this->extensions);

        closedir($handle);
```
