### ISSUE TITLE
`requests.post` on `/api/timesheets` fails creating `kimai2_timesheet_meta` entry for fields with restricted visibility

### ISSUE THREAD

**Issue by pkoevesdi** [kimai/kimai#5053]
### Describe the issue

I try to set meta fields on a newly created timesheet. This works under `/api/doc` and also with cURL:  
```bash
curl -X 'PATCH' 'https://kimai.example.com/api/timesheets/147/meta' -H 'accept: application/json' -H 'Authorization: Bearer 1223423543452345' -H 'Content-Type: application/json' -d '{"name": "fieldname","value": 211}'
```
But the same request doesn't work with python as long as there is no metadata yet:  
```python
requests.patch('https://kimai.example.com/api/timesheets/147/meta', data = {"name": "fieldname","value": 211}, headers = {'Authorization': 'Bearer 1223423543452345'})
```
So, it fails when trying to create a _first_ meta record. It works with creating or updating, when there's already an entry in the `kimai2_timesheet_meta` table of kimai database, for instance made by  `/api/doc` or cURL, no matter if for the same meta field or a different one.

I'm not sure, if this is a bug on kimai, if not I appreciate any help: What else might be wrong?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.21.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Logfile

Doctor > Logs: `Empty logfile`

**Comment by pkoevesdi** [comment]
As far as I can see, it works on the demo server.

**Comment by pkoevesdi** [comment]
One more thing I found out: it works, when the timesheet was created before by the WebGUI or the `/api/doc` (used the same content as my python call!), instead by the API. So there might be something wrong with either the way Kimai creates timesheets via API, or something wrong with my python request before, the one creating the timesheet.

**Comment by pkoevesdi** [comment]
When I create a timesheet with WebGUI, `/api/doc` or cURL, in the table `kimai2_timesheet_meta`, the entries for every custom field get created, with value NULL. This ensures, that the following call to `/timesheets/147/meta` works.

In contrary, if I make a new timesheet with python `requests`, this doesn't happen for my wanted custom field, but for the other I made for testing purpose.

The difference between them: the failing one's visibility was restricted to `ROLE_SUPER_ADMIN`. If I eliminate that restriction, this field gets created in `kimai2_timesheet_meta` with the python request too. Of course, I use the same API key, and the same request.

Can this now be considered a bug, or am I missing something?

**Comment by pkoevesdi** [comment]
The fields creation seemingly fails with python requests,  no matter what I put into the `Permission` field under `Restrict visibility` of the custom field. But in cURL, it makes a difference: with something meaningful/correct in there, the cURL call works, the python call still doesn't.

**Comment by pkoevesdi** [comment]
Also any restriction to "Customer", "Project" or "Activity" make the creation of that field on python request fail. While the general "visibility" switch makes no difference, only the restrictions do.

**Comment by kevinpapst** [comment]
Sorry, you need to provide clear explanations in one post.
I don't get what your problem is. 

If the visibility setting is causing troubles, then this has nothing to do with Kimai core.
The additional permission layer is introduced by the CustomFields Plugin.

And to wrap it up: a call that works via curl **is** working. 
If the same call doesn't work with Python, its the python code thats buggy - obviously not a Kimai issue 🤷

**Comment by pkoevesdi** [comment]
Well, sorry, the multiple posts came, because I cooked down the error further, which is supposed to help the developer, otherwise he has to go through that process himself again.

In both cases (python or cURL), the request result is 200, the request is executed on the table `kimai2_timesheet`, so seemingly nothing wrong with my python request. But the changes in `kimai2_timesheet_meta` are different, depending on the visibility setting of the custom field. I can't imagine how I could make that difference from outside. Even if my requests are different (maybe in the headers), this shouldn't result in such a behaviour.

I'll repost the report integrating what I found out so far in https://github.com/kimai/Paid-plugins/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen. (As soon as I can repeat the error, which is not the case atm.)

**Comment by pkoevesdi** [comment]
Btw.: I't a bit hard to expect a user to know, whether a bug comes from core, plugin, or conjunction of both. I can't help but leaving that judgement to the developers.

**Comment by pkoevesdi** [comment]
I can't reconstruct that error any more, although I spent hours having it (see coments above). So, I think, this can be closed. In case, it comes back, I'll make a bug report in the Plugins repo.
Nevermind, thank you.

**Comment by kevinpapst** [comment]
Closing 😁
