### ISSUE TITLE
absence time added to "is-hours"

### ISSUE THREAD

**Issue by pkoevesdi** [kimai/kimai#5054]
### Describe the issue

Absence times like holidays must reduce the "expected number of hours", not be added to the "is hours" on the `/en/contract` page.

Example screenshot: The page shows 184 hrs expected time and 8 hours is-time. Neither is true: 
- in january 2024, the normal expected work time (40 hrs/week) in germany is (31 days - 8 weekend days - 1 day new year's eve)  * 8 = 176 hrs.
- in this example the employee didn't work at all, also not on new year's eve

Of course, also the totals below these 2 columns are wrong this way.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.21.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Screenshots

![grafik](https://github.com/user-attachments/assets/d5383b88-051c-4dc7-8abc-c08344d45048)

**Comment by kevinpapst** [comment]
He didn't work, but the public holiday counts as work. That's how Kimai calculates:

- every day that has a working hour setting counts a expected
- certain types of absences (public holidays are basically one type of absence) are treated as "hours"

You might disagree and I am open to discussions, but that's how its done and many companies/people are fine with it.

**Comment by pkoevesdi** [comment]
That's sad and misleading, at this point Kimai simply shows wrong data. A user like me doesn't care how something calculates inside, but the view to the outside should be true.

**Comment by pkoevesdi** [comment]
Also, this is totally inconsistent with the weekends, there Kimai shows it correctly: No expected time, no worked time. Why differently on holidays?

**Comment by kevinpapst** [comment]
> That's sad and misleading, at this point Kimai simply shows wrong data. 

I had several companies talk this though with their HR and legal departments. No one complained. 

> weekends

You did not set expected hours for weekends, completely different case.

You can work on e.g. public holidays, which needs a different type of calculation.

**Comment by kevinpapst** [comment]
> Neither is true:
> Of course, also the totals below these 2 columns are wrong this way.
> Kimai simply shows wrong data
> totally inconsistent
> A user like me doesn't care

I would kindly ask you to think about the way how and what you post.

**Comment by pkoevesdi** [comment]
> > That's sad and misleading, at this point Kimai simply shows wrong data.
> 
> I had several companies talk this though with their HR and legal departments. No one complained.

Yes, and they probably neither would have complained, if Kimai would show correct data.
I complain for my company.

> You did not set expected hours for weekends, completely different case.

See, that's the developers view and no real argument, it _can_ be done differently. The point is not, what I set (I have no descision over this setting), it's about the reality. And the weekend are no different case at all. Neither on weekends, nor on holidays someone is expected to work, simply the same case.

So, to speak internally, instead of adding holidays to working hours, holidays should overwrite expected weekday's hours. 
Not much rocket science.

> You can work on e.g. public holidays, which needs a different type of calculation.

I don't understand this, I can also work on weekends.

**Comment by kevinpapst** [comment]
> See, that's the developers view and no real argument, it can be done differently. 

Yes, it is. And yes, can be done differently.

> And the weekend are no different case at all. Neither on weekends, nor on holidays someone is expected to work, simply the same case.

There is such a huge amount of people/businesses that work on public-holidays (Healthcare, Emergency Services, Hospitality, Retail, Transportation, Utilities, Media and Broadcasting, Security and so much more). 
Not your business, understood. 
But I talk to business owners from different industries daily.  

> Not much rocket science.

Not much rocket science to create a time-tracker. Just a few works years of work. 

I am done with this discussion. Not because of the topic, but by your disrespectful way. 

If you want a refund, please send me your email to support@kimai.org - I am happy to provide it

**Comment by kevinpapst** [comment]
Latest plugin release has a flag to change the behavior
