### ISSUE TITLE
kimai2 with SAML for keycloak SSO

### ISSUE THREAD

**Issue by gschnepp** [kimai/kimai#5057]
### Describe the issue

> I tried several (a lot of) different settings and followed the documentation (not sure if the documentation is still uptodate with Keycloak as the interface looks quite different now).
> 
> Still, I could not get it to work. It goes to Keycloak, does the SSO login process, then it's redirected to https://kimai2.xxx.xx/auth/saml/acs and a POST occurs with a subsequent redirect to https://kimai2.xxx.xx/en/login seems not responsive. There I simply get an error from nginx like this URL does not exist. But if I go to https://kimai2.xxx.xx/index.php/en/login I get the message "An authentication exception occurred."
> 
> I installed the firefox extension SAML tracer to try to track down the issue and it seems to me that the ACS part with /auth/saml/acs is fine but the redirection after that is having an issue. Also, I could see through that firefox extension that all the information required is being passed on by keycloak back to kimai2 (including the roles and attributes).
> 
> > Page not found
> > We could not find the page you were looking for. Please return to your dashboard and start over. 
> 

We are having the same issue here as described in discussion #4942 . Since this is reproducable on more than one installation I like to open an official bug report here.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.18

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
You are welcome to join the linked discussion. 

I am going to close this right away as there is no bug (at least none that is known) and SAML works for Azure and Google Workspace for dozens of customers. And I know from multiple customers who use Keycloak with Kimai successfully. 

Keycloak is more complicated to setup (compared to Microsoft and Google) and I was never able to figure it out myself, so I can't help.

If you can point to something that is clearly broken and name it, you can re-open.
