### ISSUE TITLE
CORS preflight OPTIONS 400-Bad Request for HTTPS API calls from browser

### ISSUE THREAD

**Issue by TimothyK** [kimai/kimai#5067]
### Describe the issue

I'm getting a 400-Bad Request response for an OPTIONS preflight CORS request when using the Kimai API. 

**Reproduction plan**
I'm making API requests from a Web Assembly project.  It is my open source project and I've stood it up on a public server.  You can access it (and reproduce this issue) by going to https://satori.nexus.

On the home page click the Add Kimai button and enter a https URL to your Kimai v2.21.0 instance, and an API key.  I've tested this with a local docker instance and an environment on kimai.cloud, and I get the same results.

**Expected Result:**
After the API integration information is saved (in your browser's local storage) it should hit the kimai api/users/me API endpoint.  It should read your avatar from kimai and display that in the top left (replacing the question mark placeholder avatar).

**Actual Result:**
There is "An unhandled error has occurred" at the bottom.  

In Chrome dev tools (F12) Console I get:
Access to fetch at 'https://kimai-xxx/api/users/me' from origin 'https://satori.nexus' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

and on the Network tab I get:
![Network tab](https://github.com/user-attachments/assets/6e86b807-fecc-410b-878e-27f1a28fff18)

and for the request:
![Request](https://github.com/user-attachments/assets/223b1ab2-091e-41eb-ae96-616296674431)

**Additional Context**
The https://satori.nexus project is an open source Web Assembly project.  It runs completely in the browser (there is no server).  It can be used to export Kimai data to Azure DevOps (Microsoft's bug tracking system).  Azure DevOps is not required to run Satori; it can be connected only to Kimai.

It is implemented in C# with the Microsoft Blazor framework.  Not that I expect you to go though the C# code, but the source code specifically for the Kimai API requests is [here](https://github.com/TimothyK/Satori/blob/main/Satori.Kimai/KimaiServer.cs#L30): 

I am just doing a GET request.  The framework does all the CORS preflight request stuff (I don't really have any control over it).  It adds the OPTIONS request.  It only does this if Kimai is running HTTPS.  I can run the code locally in dev mode on HTTP against an HTTP docker instance of Kimai and it works fine.  But the Satori site running in HTTPS requires all the endpoints it hits to be HTTPS too.

Let me know if you need any more information.  Sorry I'm not really an expert on CORS or PHP.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.21.0

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Hm, the API token was recently added and maybe I forgot to adjust the necessary config...

Can you do me a favor and try to replace this line:
https://github.com/kimai/kimai/blob/main/config/packages/nelmio_cors.yaml#L23

Before:
```
allow_headers: ['X-AUTH-USER', 'X-AUTH-TOKEN', 'Content-Type']
```
After:
```
allow_headers: ['X-AUTH-USER', 'X-AUTH-TOKEN', 'Content-Type', 'Authorization']
```

then delete the cache `bin/console kimai:reload`

Edit: you are not using `KIMAI CLOUD`, are you?

**Comment by TimothyK** [comment]
I've tested this with Kimai Cloud and the official Docker images.  Sorry, I don't have a Kimai dev environment setup.  I haven't run it from the source code.  Although I am a developer, I've never worked with PHP.

Note the [Satori](https://satori.nexus) application is WebAssembly.  So it runs completely in the browser.  You can point it at an environment on your local machine, as long as it is running HTTPS.  So it can be tested without pushing anything up to the cloud.

**Comment by TimothyK** [comment]
Satori does support both API Token or API Password.  I've tested it with both.  I get the same results.

Using the API Password it is passing the X-Auth-Token and X-Auth-User, but it still returns the same 400 Bad Request.

**Comment by kevinpapst** [comment]
When I add Authorization it seems to work.
But I will investigate further tomorrow, its too late to think 😁

**Comment by kevinpapst** [comment]
Update is currently being rolled-out (but staged, so it might take up to 24 hours to reach your cloud). 

But I can confirm, that my test cloud works now. 

Thanks for finding this issue and sharing detailed feedback!

**Comment by TimothyK** [comment]
Thanks so much for the fix.

On Chrome/Edge I confirm this (v.2.22.0) fixes it when https://satori.nexus (C# Blazor WASM) runs against Kimai Cloud.  Also my local dev environment for HTTP and HTTPS work against my docker container running Kimai v2.22.0 on HTTPS.

However on Chrome/Edge, https://satori.nexus **does not** work against my docker container running Kimai on HTTPS.  I get the same CORS preflight errors as before.  Disabling caching doesn't solve this.

However on Firefox, https://satori.nexus does work against my docker container running Kimai on HTTPS.

It is so weird that only one of these test fails.  I wonder if there is some casing/capitalization issue that is causing this one browser to fail.

**Comment by kevinpapst** [comment]
> However on Chrome/Edge, https://satori.nexus/ does not work against my docker container running Kimai on HTTPS. I get the same CORS preflight errors as before. Disabling caching doesn't solve this.

Hm, that's annoying. I am pretty certain, that headers are always lowercased before checked, to prevent such case issues. 
Honestly, I am using a plugin to take care of CORS requests, becuase that topic can get complicated. 

There is a setting that is called `allow_private_network`, just in case you are running at 127.0.0.1 you could change the file, reload cache and retry: https://github.com/kimai/kimai/blob/main/config/packages/nelmio_cors.yaml#L20

I am closing the issue, as the main case is solved. But I will keep on reading your responses!

**Comment by TimothyK** [comment]
I finally got back to looking at this.  CORS preflight requests were failing in Chromium, working fine in Firefox.  Yes, it was an issue in how we were installing Kimai.  We had to make the following changes to the conf file we were using with nginx.

```
location / {
    if ($request_method = 'OPTIONS') {
        add_header Access-Control-Allow-Origin $http_origin;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT, PATCH, DELETE';
        add_header Access-Control-Allow-Headers 'Content-Type, Authorization, X-AUTH-USER, X-AUTH-TOKEN';
        add_header Access-Control-Allow-Credentials true;
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 204; # No content
    }
    try_files $uri /index.php$is_args$args;
}
```
