### ISSUE TITLE
Accurate time tracking

### ISSUE THREAD

**Issue by sollermun** [kimai/kimai#507]
Please correct me if I'm wrong, but it seems that Kimai alternates between using the server's time and the client machine's time in order to calculate the duration of time tracked. If that is the case, it should be changed so that the start and end time are both drawn from the same source. Assuming that the server and the clients are perfectly synced can lead to errors if, for example, the start time is taken from the server and the end time is taken from the client.

**Comment by cloudeasy** [comment]
You are absolutly correct. The start time is sent from the browser to the server. The end time comes from the time on the server.

**Comment by jguithues** [comment]
I thought this was strange too.  My server likes to lose about a second every few weeks, so if I clock in and out quickly my time is negative 30 seconds or so.  I am curious why this was chosen as the behavior.  That would be a neat feature, being able to choose one way or the other, browser/client-time or server-time.

**Comment by claude-ws01** [comment]
And what happens if you punch out from a different computer(browser-client) than the one you did your punch in?  Chances that both computer are not perfectly synchronized.

**Comment by nooneto1** [comment]
Is this what could be causing the problems I recently reported on the forums? I didn't know if it was a bug per-say or if it was intentional, which is why I didn't post it there.

http://forum.kimai.org/index.php?topic=3756.0

**Comment by claude-ws01** [comment]
Possibly. try other [Demo](https://kimaii.demo.ws01.info/)

**Comment by simonschaufi** [comment]
someone willing to make a PR to fix this to use server time only?
