### ISSUE TITLE
There is a bug in Kimai timesheet filtering.

### ISSUE THREAD

**Issue by seleondevel** [kimai/kimai#5077]
### Describe the issue

When Activity filters timesheets, it only shows the timesheets for that activity, so far it's normal.
But if you click the filtering icon at the top left, click the Find button, and click Retrospective Filtering in that project, it does not reset, and it looks the same as the previous filtering.
If you click the filtering icon in the upper left corner, the previously found filtering settings will remain the same. You won't see the timesheets of other projects or the timesheets of those projects.

When filtering timesheets with a project, I think the activity of filtering should be modified to initialize.

This issue was confirmed in the demo.

Please check.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.22.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Screenshots

![스크린샷 2024-09-23 145109](https://github.com/user-attachments/assets/ba6cea2c-6355-4bf2-b779-92056d6990a0)

**Comment by kevinpapst** [comment]
Will be fixed with the next release
