### ISSUE TITLE
UX Issue when starting a new timer

### ISSUE THREAD

**Issue by sjthiessen** [kimai/kimai#5087]
### Describe the issue

 I encounter an annoying UX bug whenI just want to start time tracking without setting a duration.

1. Clicking the play button
2. Clicking in the customer-Dropdown
3. App selects a time from the timepicker-dropdown

My expectation is that the duration field remains empty and just the customer-Dropdown opens.

https://github.com/user-attachments/assets/dbbee947-5e19-45bb-b2b4-5da9b53605ff

The instance is hosted on kimai.cloud - I don't now how to figure out the version. The Console shows just this:
![grafik](https://github.com/user-attachments/assets/d25ac697-a9cc-441f-b2e3-43c84396dd5d)

OS: Windows 10 KB5043131
Browser: Firefox 130.0.1

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.xx

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

Unknown

**Comment by kevinpapst** [comment]
This issue is so severe that I would have heard about it before.
So my best guess is, that this is cause by a browser plugin.

As this is not reproducible for me, could you please:
- Try another browser
- Use private mode for testing (which usually deactivated most plugins)

**Comment by sjthiessen** [comment]
Hey, thanks for coming back to this so fast!

On chrome I can't reproduce it, too. But in Firefox private mode I'm able to do so. Only uBlock Origin was activated. Deactivated it - still. Completely closed the browser and reopened a private tab with no plugins active from the start and still, it appears.

A new observation: I *have* to click right where the timepicker dropdown would appear, so right below that field, not left or right of it.

**Comment by kevinpapst** [comment]
Okay, if anyone else can reproduce this one reliable: please let me know.

I am not able to reproduce it and to me that sounds like a browser glitch and not a bug in Kimai.

**Comment by kevinpapst** [comment]
Please re-open if this can be reproduced reliable.
