### ISSUE TITLE
Export: Team selection shows time entries for other teams

### ISSUE THREAD

**Issue by BeckeBauer** [kimai/kimai#5089]
### Describe the issue

When I select a team to export its time entries, the time entries for other (not selected) teams are exported as well. 
In the demo, I created the teams "test team 1" (with the project "project test team 1) and "test team 2" (with the project "project test team 2") and added two persons each whereas one person is member of both teams. 

Then, I created an entry for this person for "project test team 1" and "project test team 2".
 
When I now open the export tab and select "test team 1", I got time entries for the project test team 2 as well (among a lot of other entries). 
 
![image](https://github.com/user-attachments/assets/39aad7e7-0b1a-4451-b6c2-9ac41eee72af)

I would have expected to get only time entries for customers belonging to the selected team

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.22.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
Teams filtering is ONLY a way to selected multiple users at once without the need to know these users.
It is NOT filtering content.

Works as planned (maybe not as expected though).

**Comment by BeckeBauer** [comment]
thanks for explaining
