### ISSUE TITLE
Processor.php issues redirecting

### ISSUE THREAD

**Issue by Fogest** [kimai/kimai#510]
When doing things such as adding new customers, projects, or tasks processor.php seems to be trying to handle the request, but seems to fail to redirect and I just see a blank page and I'm at the url:

`/kimai/core/processor.php`

If I go back to `/kimai` the change has been made, it is just the redirect failed. Same thing happens when updating something in admin panel, except on the page I see text just saying "ok" on a blank white page and that is all. The application is working apart from the redirects not working.

**Comment by simonschaufi** [comment]
Not reproducable for me. I never experienced this. Do you use the latest stable or the latest git version?

**Comment by Fogest** [comment]
Looks like it was a cache issue with Cloudflare.
