### ISSUE TITLE
Don't show projects in dropdown for new entries that have no more hours available

### ISSUE THREAD

**Issue by KatrinIhler** [kimai/kimai#5100]
### Describe the problem

In our company, if the time budget on a contract (= project in Kimai) is used up, that customer usually gets a new contract with a new order number which maps to a new project. However, old projects are still available for selection in the drop down when creating a new time entry, but when one of us selects them, we will get a warning that the budget has been used up and no more hours can be booked. Because of this, it can be annoying to figure out which projects still have hours left to be used.

### Describe the solution you'd like

I would like for full contracts not to be available for selection when creating new time entries. Alternatively, these projects could be shown but be greyed out or something like that.

### Describe alternatives you've considered

I am aware of the visibility setting for projects, but this setting has more implications and also requires manual intervention, which isn't convenient if you manage a lot of customers and projects.

**Comment by kevinpapst** [comment]
The data must be live calculated which is way too expensive to do.
Therefor this won't be added. 

And as manual work is necessary anyway, when you create a new project, I would recommend that you simply set an end date in the past for those projects.
