### ISSUE TITLE
RC0.9.3 : bugs

### ISSUE THREAD

**Issue by jobart** [kimai/kimai#511]
Hello Everybody,

I have installed the released version 0.9.3 as the installer of the 0.9.2 does not work with my database provider (OVH). Indeed, the installer did not find the database... which is a problem for me as my computer knowledge is poor.

The 0.9.3 version is quite impressive but have some bugs which I want to relate to help you.

First, I have created an ODT file for exporting an invoice. But when selecting the export of the invoice, nothing happens. I only get a white screen and the adress bar mentionned :  http://monsiteweb/kimai/extensions/ki_invoice/print.php

Here you will find the debug :
[29.08.2015 12:15:56] Uncaught exception: can't found the end of the tag '[var.today'][29.08.2015 12:15:56] Round 0.25 to 0.3 with 1 
[29.08.2015 12:15:56] Round 0.66666666666667 to 0.7 with 1

For escaping this issue, I have modified the short time model invoice and keep it name. It works but I have two problems.
The date of [var.today] is "1440843880", which is a little problem.

Besides, the date of [row.date;fmt='dd-mm-yyyy'] is in an US format : 08/29/2015, which is not what I am looking for, even if I have modified it in the admin panel.

The [var.ttltime] is displaying too much decimals. It is not possible to adjust it.

Finally, I have two suggestions of improvement of the RC candidate. For my part, it could be useful to have the ability of changing the order of displaying the different task, so as to display at first glance the most used tasks. Indeed, when you have 50 différents tasks, it is quite boring to go at the full down of the list as it is a recent task that you have created.

The same improvement could be applied for the project choice and the client choice.

I am sorry for my English as this is not at all my native language.

Kind regards

**Comment by simonschaufi** [comment]
Hi, I think you are talking about different things here:

1. Your database provider
2. Your invoice template

right?

1. currently kimai supports only mysql (i hope to switch to mysqli soon)
2. the white screen only appears if there are errors in your template. Make sure there is NO formatting within a [...] block. That will break the parser.
You can easily adjust the date like this to any other format: [var.today;frm='dd.mm.yyyy'] for example. The format in the backend is not taken into account in this case. In my own template i use this: [var.fttltime] h to show the total amount of time but you can also format it like this: [var.fttltime;frm='0,00']
hope this helps.
