### ISSUE TITLE
Monthly target times with running sum per project

### ISSUE THREAD

**Issue by Benimautner** [kimai/kimai#5132]
### Describe the problem

Kimai doesn't support working times per project at the moment.
If I have two employers with different target times per month, I'd like to set that up in either the customer or project view. The monthly budget that exists now is not sufficient since it does not carry any negative/positive balance to the next month.

### Describe the solution you'd like

A user could add multiple different employment contracts, with different monthly target times and a start date. Kimai then tells the user what the balance per customer and month is, and increases it every month by the amount that is set in the settings.
eg: Contract for 30 hours per month starting in January:

Worked in January: 10 hrs; balance -20hrs
Worked in February: 40 hrs; balance -10hrs
Worked in March: 40 hrs; balance 0hrs
Worked in April: 0 hrs; balance -30hrs
etc.
This should be customer(/employer)-dependent.

The first part is already kind of supported with the hourly quota feature per project, it just isn't rolling.

### Describe alternatives you've considered

I know there is the controlling plugin, but as far as I can see (and have tried on the demo instance) it doesn't support this either. I realise Kimai is more built for contractors/freelancers but this would be a nice feature for employees. 

If the time would be per project, this could also be a useful feature for employees with only one contract, since they could see more clearly what the total of their time is. It would already suffice if the monthly budget per project (as it exists now) would be rolling (meaning it remembers and adds the sums for previous months).

**Comment by Benimautner** [comment]
I've created a fork with that feature here:
https://github.com/Benimautner/kimai

Let me know what you think and what is missing for a pull request.

**Comment by Benimautner** [comment]
I read in a recent pull request that you're not a big fan of new graphs in kimai, so I moved it to a plugin instead:
https://github.com/Benimautner/RunningBalanceBundle

I'm open to feedback, but I'll close this issue now. Thanks for the great product that is Kimai! :)

**Comment by kevinpapst** [comment]
Nice! If you add a few tags to your repository, people can find it more easily. Like that:

<img width="435" alt="Bildschirmfoto 2024-10-25 um 17 07 26" src="https://github.com/user-attachments/assets/861f2c74-2c8e-434e-bf36-85f4171ac6ec">

**Comment by Benimautner** [comment]
I'll do that and add a couple improvements in a couple of weeks!
