### ISSUE TITLE
Show time worked on current working day

### ISSUE THREAD

**Issue by jv-barsuk** [kimai/kimai#514]
I have the overall view on the whole month but I would be interessted how much I was working today. I find it very anoying to always have to change the timeframe, so it would be nice to always have the working hours of the current day displayed in the top area.

**Comment by stefanke** [comment]
This would also help us a lot, thanks for the suggestion. Maybe it´s possible to add 4 buttons similar to geofancys interface: daily, weekly, monthly. This would combine the weeks (days, months) so you have a great overview (see attached screenshot). 
<img width="216" alt="geofencyview" src="https://cloud.githubusercontent.com/assets/15725888/11028959/c93d57fc-86c3-11e5-9f65-311ec7a0cda0.png">

**Comment by simonschaufi** [comment]
Is somebody willing to sponsor this feature? It will take a lot of time to implement it.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
