### ISSUE TITLE
Invoice preview duration in decimal time

### ISSUE THREAD

**Issue by ofarrill** [kimai/kimai#5145]
### Describe the issue

Since updating from 1.x to the Kimai 2.24.0, the invoice durations are displayed in decimal times now (instead of h:m as before) which is pretty unintuitive and it seems it's not controlled by any setting.
<img width="469" alt="Screenshot 2024-11-01 at 21 27 48" src="https://github.com/user-attachments/assets/8813e532-ba3a-458e-b507-35f891b4d6fb">

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.24.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

**Comment by kevinpapst** [comment]
That's correct behavior and not a bug. Open a discussion if you want to talk about it.
