### ISSUE TITLE
Checkbox in timesheet list is barely visible anymore

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#5146]
### Describe the issue

Since a few releases the checkboxes are not really visible anymore. See attached screenshot. Please adjust the contrast.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/user-attachments/assets/f56adcc3-693a-454b-a282-dd1129bb17cc)

**Comment by kevinpapst** [comment]
I already wondered myself if it was always like that. 
The theme author must have changed the contrast... will have look.
