### ISSUE TITLE
Bug during enter Timetrack for "another user"

### ISSUE THREAD

**Issue by suther** [kimai/kimai#5147]
### Describe the issue

1. Login as Adimn
2. Make sure, timetracker mode is set to "Default" to be able to manually add timetracks
3. open "Timetrack > All Times" and press Button "For multiple users"
4. Add some Timetracks in the past

**What happend?**
Saving isn't possible, as the error-message notes that there is still an entry on this date & time

That's not possible, as I did it with a brand new created user, that hasn't any times tracked at all in the timetracker yet.

If I look into time-listing, I see that there are timetracks of "other users" at this time. 

** So what's the bug?**
The Bug may be, that Kimai didn't really check for the user I've selected, but just check if there are "any" entries on this project.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.22.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Screenshots

![image](https://github.com/user-attachments/assets/4e4ac431-e8f7-4d4e-a813-7e159aa43be2)

![image](https://github.com/user-attachments/assets/d8bb5aa4-11a8-4c5b-b5bc-b3c668f2ed9c)

**Comment by kevinpapst** [comment]
Thanks for sharing 👍 

You are right, the underlying logic triggers the overlapping validator for the current user, even if that one is not in the list of the selected users. Will be fixed with the next release.
