### ISSUE TITLE
Record Again

### ISSUE THREAD

**Issue by globaljetservices** [kimai/kimai#515]
There seems to be a bug with the Record Again functionality and permissions.  

Our users have no access to modify their own time and with that the record again does not work.  

In testing the global role permissions under "Timesheet" "Own entry" "Edit Entry" is unchecked the user will not be able to use the record again button.

Anyone else see this issue?

**Comment by simonschaufi** [comment]
confirmed. only the big bizzer in the top corner works

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
