### ISSUE TITLE
Editing from calendar view will return to my times table instead of calendar

### ISSUE THREAD

**Issue by jaapcrezee** [kimai/kimai#515]
**Describe the bug**
Editing registrations from calendar view will not return to the calendar view.

**To Reproduce**
1. Go to My times, select calendar view.
2. Pick a registration and click on it, edit window will open.
3. Now either make changes or not;
4. both `save` and `back` will go back to the My times list and not the calendar view.

**Expected behavior**
Goes back to calendar view, not the list version.

**Desktop (please complete the following information):**
 - OS: linux
 - Browser Chromium
 - Version 71.0.3578.98 (Official Build) Arch Linux(64-bit)

**Comment by kevinpapst** [comment]
True, the calendar needs some love ;-)

I'll have a look at it.

**Comment by jaapcrezee** [comment]
Thank you. Using your software for many years now, also with love :). So a big thanks.

**Comment by kevinpapst** [comment]
I created a PR which you can test if you like.

**Comment by kevinpapst** [comment]
Now available in master
