### ISSUE TITLE
problems with 'filters and search' with meta-fields (checkbox)

### ISSUE THREAD

**Issue by wobouser** [kimai/kimai#5154]
### Describe the issue

we have created a checkbox as a meta field in the timesheets.
according to the documentation -> https://www.kimai.org/documentation/timesheet.html
the value of a checkbox is 0 or 1

so the default value should be 0 / with activated checkbox 1

with the search filter "customfieldname:1" it gives me all timesheets with activated checkbox.
so the search expression “customfieldname:0” should return all entries with a non-active checkbox.

but that is not the case

I have taken a look at the sql “kimai2_timesheet_meta”. 
When I activate the checkbox there is a 1 in there.
For a new timesheet entry the value is empty (not NULL or 0)
if i deactivate the checkbox the value also changes from 1 to empty.

therefore the search expression for the checkbox cannot work

### I already tried

- [x] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.20.0

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

8.1

### Screenshots

![image](https://github.com/user-attachments/assets/944cdd49-5198-4dc9-911b-c85948d2a21e)

![image](https://github.com/user-attachments/assets/08b3cf8e-5779-48c3-8f26-edd2b92e65ba)

**Comment by kevinpapst** [comment]
Thanks for sharing!

Seems you are correct on the initial save. 
I will add a fix for the next release.
