### ISSUE TITLE
Download Invoices in multiple languages

### ISSUE THREAD

**Issue by kbkozlev** [kimai/kimai#5160]
### Describe the problem

When Invoicing between countries, it is sometimes required to have invoices in more than 1 language.

### Describe the solution you'd like

Once an Invoice has been posted, provide the option to download it in other languages.

A simple solution would be to, be able to upload multiple templates with different languages - or the same template but translated.
Once the Invoice has been posted to have a dropdown with the list of available templates or "translations".

This allows to post the Invoice with one template or language and it will be stored like this in the system, but it could be downloaded additionally in other languages if it is needed.

![image](https://github.com/user-attachments/assets/cdb82fbd-0fe7-4086-9afa-e50110dec561)

**Comment by kevinpapst** [comment]
That is not possible from a technical perspective (without an immense change in the entire system) and will not be implemented therefor.

Thanks for sharing your idea though, always appreciated 👍

**Comment by kbkozlev** [comment]
> That is not possible from a technical perspective (without an immense change in the entire system) and will not be implemented therefor.
> 
> Thanks for sharing your idea though, always appreciated 👍

This should not require barely any changes to the system.
If you add the option to add "translated" files in the Invoice template creation screen, once the invoice has been posted you can just download the files with the populated variables. The system already has the variables - it just needs to populate a new document.

![image](https://github.com/user-attachments/assets/363f9422-f356-4064-b6b0-654590876304)

**Comment by kevinpapst** [comment]
Create a fork, add the necessary changes.
Investigate how it works.
Propose a PR.
