### ISSUE TITLE
Add isFavourite attribute to timesheet API

### ISSUE THREAD

**Issue by Benimautner** [kimai/kimai#5168]
### Describe the problem

Currently, even though the frontend shows the status of a timesheet entry in the "restart one of your last activities" popup, it is not included in the api.

### Describe the solution you'd like

Either just add the field as a boolean flag to the API, add a filter to the api request allowing to filter by favourite status or add a separate endpoint only returning favourite activity/client combos.

I am happy to contribute a pull request, I just wanted to know whether this has been considered/which solution you like more. I am thinking about creating a little device for my desk (just an arduino with a display and a couple buttons) showing stuff like current time on the active timesheet, and recent (and more importantly favourite) activities to start/stop by button click.

I'd like to avoid having to configure which activities to show on device. I'd rather have kimai tell it "those are the favourites" and since the frontend already has that information it should be trivial to add to the API.

Let me know if you want to see a pull request and which method you'd prefer!

### Describe alternatives you've considered

I briefly looked into ways to extend the api via a plugin, but I didn't find anything about that. I'd like it to be served via token and from a /api endpoint. And since I think it's a good idea to add the field to the api response, I quickly moved on.

**Comment by kevinpapst** [comment]
What about adding that route via plugin?

**Comment by Benimautner** [comment]
Sorry, just thought this might be a good addition to the api.

https://github.com/Benimautner/FavouriteTimesheetApiBundle

**Comment by kevinpapst** [comment]
This is something I never planned to expose as API. And a public endpoint needs to be maintained for a long time, which then is my burden. So I do appreciate that you added it via plugin 👍

**Comment by Benimautner** [comment]
Yes, I absolutely get that, just wanted to make sure you are intentionally not exposing it. Thanks for the quick reply!
