### ISSUE TITLE
Minor-UI Bug for Tags

### ISSUE THREAD

**Issue by suther** [kimai/kimai#5169]
### Describe the issue

If you shrink the page-size and if you have long Tag-Values in your page, the Text overlap the Borders of the tag

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.24.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Screenshots

![image](https://github.com/user-attachments/assets/850e9873-77fa-4ac0-b240-ce487876b40f)

**Comment by kevinpapst** [comment]
Thanks for sharing 👍
