### ISSUE TITLE
Bad Gateway when saving Settings

### ISSUE THREAD

**Issue by philippkayser** [kimai/kimai#5178]
### Describe the issue

I try so change settings in the admin backend via the UI and klick on save.

I get a bad gateway after 10 seconds. Just if I use kimai behind a reverse proxy (traefik).

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

latest

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

### Logfile

kimai-app_1  | localhost:8001 127.0.0.1 - - [25/Nov/2024:15:42:29 +0100] "GET / HTTP/1.1" 302 626 "-" "curl/7.88.1"

**Comment by kevinpapst** [comment]
So Kimai works until you use a POST request on one specific screen? 
How did you login?
This bug posts misses so much information...

What in the docker logs?
This one line is a health check and not related.

**Comment by philippkayser** [comment]
> So Kimai works until you use a POST request on one specific screen? How did you login? This bug posts misses so much information...
> 
> What in the docker logs? This one line is a health check and not related.

All Post requests works fine, excepting the Settings part.

**Comment by kevinpapst** [comment]
Try without Traefik to identify the root cause.

**Comment by philippkayser** [comment]
Without different reverse proxies the settings part works fine. So as I told it just happens in the system settings part and just with reverse proxy.

**Comment by kevinpapst** [comment]
I don't think that this is a Kimai bug. Works just fine with Caddy in front.
