### ISSUE TITLE
Create Time Entry for Multiple Users Simultaneously

### ISSUE THREAD

**Issue by EduNetEurope** [kimai/kimai#5187]
### Describe the problem

Currently, it seems that a team leader cannot create a single time entry for multiple team members simultaneously.

In some cases, several team members need to log the exact same number of hours (e.g., during meetings). Efficiency would greatly improve if team activities could be created centrally.

### Describe the solution you'd like

A team leader creates a single time entry and selects one or more team members for whom the entry should be created.

### Describe alternatives you've considered

Alternatively, it might be simpler to implement a feature allowing a team leader to copy (duplicate) an existing time entry from one user (e.g. user A) to another (e.g. user B).

**Comment by kevinpapst** [comment]
> Currently, it seems that a team leader cannot create a single time entry for multiple team members simultaneously.

All times > For multiple users

<img width="468" alt="Bildschirmfoto 2024-12-02 um 10 42 42" src="https://github.com/user-attachments/assets/e13011ab-dda0-44b8-900f-f2ce7738891f">

**Comment by EduNetEurope** [comment]
Sorry I missed it and thanks!
