### ISSUE TITLE
Trying to change month in reporting/user/month report does not work

### ISSUE THREAD

**Issue by liayn** [kimai/kimai#5188]
### Describe the issue

Clicking the arrows does not update the view.
It works if I change the user afterwards as well. (but that discovery was more luck than knowledge)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.25.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

### Logfile

no logs available in "Doctor"

**Comment by kevinpapst** [comment]
Works on my machine and on the demo. Which docker image?

**Comment by liayn** [comment]
This image: https://hub.docker.com/layers/kimai/kimai2/latest/images/sha256-824f5ed32e7d913dc3c0df343cff85ab035d22fb4daed31c79ee9f2efc7de475?context=explore

Browsers testet:
* Firefox 134.0b3
* Vivaldi 7.0.3495.20 (Stable channel) (64-Bit)

**Comment by kevinpapst** [comment]
So nginx? Happy to provide you the link to the docs: https://www.kimai.org/documentation/docker-compose.html#fpm-image

**Comment by liayn** [comment]
What do you mean?

We run Apache in front of the FPM image. And this has been working ever since and stopped working with the latest update from 2.24 to 2.25.

**Comment by liayn** [comment]
Okay, got it. You are referring to this:
> To fix this you need to copy the newer files from a fresh image over the top.

**Comment by kevinpapst** [comment]
Some updates ship JS changes and that's when you think "there is a bug". 
Often updates only contain CSS changes, which hardly cause real bugs, but only UI glitches.
But with JS changes parts of the UI might stop working.
I would recommend to use the `:apache` image.

**Comment by liayn** [comment]
Thanks, that fixed it. (of course)

I have no problem with this update procedure, but I wasn't aware of it. Wrote a script now, so won't happen again.

> I would recommend to use the :apache image.

Yes, we could, but since the server already runs other FPM-containers, that's just wasted RAM to have yet another Apache running (nested).

**Comment by kevinpapst** [comment]
True. If you have any idea how to get rid of that manual step, please let me know, so I can adapt the docs

**Comment by liayn** [comment]
> True. If you have any idea how to get rid of that manual step, please let me know, so I can adapt the docs

We're actually thinking about improving the `entrypoint.sh` script and the `Dockerfile`.
For the FPM image the `public`-folder is not placed in the `/opt/kimai/public` during build, but into a different folder (e.g. `/opt/kimai/public-tmpl`).
On startup this `public-tmpl` is copied over into `public` and the `/opt/kimai/bin/console assets:install` is called.
