### ISSUE TITLE
Weekly hours view switching between calendar weeks does not work

### ISSUE THREAD

**Issue by schanz92** [kimai/kimai#5190]
### Describe the issue

When clicking the buttons in the weekly hours view to switch to another week, nothing happens. I do not get an error in the console

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

kimai2:apache-2.25.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

### Screenshots

![Screenshot 2024-12-02 at 15 21 12](https://github.com/user-attachments/assets/a72964be-c34b-4c9f-8d99-f629b34ec989)

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/issues/5188
