### ISSUE TITLE
Customer Portal evaluation does not work for past months

### ISSUE THREAD

**Issue by strausmann** [kimai/kimai#5196]
### Describe the issue

I just took a closer look at Kimai and found a bug in the Customer Portal plugin. I created time entries for the months of October and November as a test.
Then I created a Customer Portal for this customer and switched to the months October and November. 

The entries are displayed correctly, but unfortunately the budget calculations are still based on the current month, in my case December. The budget unfortunately remains at zero.

After I created an entry for December, the budget was evaluated in the Customer Portal, but still from December. Even though I selected October or November.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.25.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

**Comment by kevinpapst** [comment]
Works as expected. 
The budget status is ALWAYS calculated for now. The status of previous months is not displayed, you only see the time worked for those. 
You can use recurring monthly budgets if you need that.

**Comment by reenstix** [comment]
The budget from future months is also not displayed. After changing the month to the next one, still the stats of the current month are visible further. Is it possible to add such functionality to show stats from choosen month?
