### ISSUE TITLE
Customer Portal uses http:// instead of https:// URL for Action Form

### ISSUE THREAD

**Issue by strausmann** [kimai/kimai#5197]
### Describe the issue

If the Customer Portal is used with a password-protected link, the URL with http:// and not https:// is displayed in the Action form, which leads to a call via http://kimai.domain.de after entering the password.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.25.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

**Comment by kevinpapst** [comment]
Which Docker image? I assume that PHP doesn't see that https is used.
Do you use the FPM image with a proxy in front?
If you use Apache, you could try if that fixes your issue: https://github.com/kimai/kimai/pull/5071

**Comment by kevinpapst** [comment]
I added a workaround in the latest plugin version 4.3.0, you can fetch it at the license center:
https://license.kimai.org/
