### ISSUE TITLE
MISSING FEATURE: Edit while tracking

### ISSUE THREAD

**Issue by lippoliv** [kimai/kimai#52]
MISSING FEATURE: While tracking a Task in Kimai 1366 i was able to modify Comment and Start-Time (sometimes i forgot to start tracking, than i start tracking and modify the start-time for some minutes), why is it gone?

**Comment by jniggemann** [comment]
+1, please reimplement this

**Comment by simonschaufi** [comment]
can this issue be closed with the PR from @claudegel which is already merged?

**Comment by jniggemann** [comment]
I guess that depends on how you use the issue tracker :-)
Either you keep this issue open until a version is released that contains the fix OR you close it, as the issue is fixed in the current trunk.

**Comment by simonschaufi** [comment]
If the feature is the one requested which is already merged again, I'll close this issue now. if it isn't, please comment again and tell me what you are expecting.
