### ISSUE TITLE
CRITICAL: Uncaught PHP Exception Error: "Call to undefined method App\WorkingTime\WorkingTimeService::getLatestApproval()" at ApprovedWorkingTimesPeriodValidator.php line 40

### ISSUE THREAD

**Issue by gschnepp** [kimai/kimai#5202]
### Describe the issue

Getting the following error after upgrade to Kimai 2.25.0 and WorkingTime 1.15.0:

> [2024-12-04 15:21:35] [request] CRITICAL: Uncaught PHP Exception Error: "Call to undefined method App\WorkingTime\WorkingTimeService::getLatestApproval()" at ApprovedWorkingTimesPeriodValidator.php line 40 {"exception":"[object] (Error(code: 0): Call to undefined method App\\WorkingTime\\WorkingTimeService::getLatestApproval() at /home/pacs/cdo00/users/kimai/kimai/var/plugins/WorkContractBundle/Validator/Constraints/ApprovedWorkingTimesPeriodValidator.php:40)"} []

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.25.0

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.2

### Logfile

[2024-12-04 15:21:35] [request] CRITICAL: Uncaught PHP Exception Error: "Call to undefined method App\WorkingTime\WorkingTimeService::getLatestApproval()" at ApprovedWorkingTimesPeriodValidator.php line 40 {"exception":"[object] (Error(code: 0): Call to undefined method App\\WorkingTime\\WorkingTimeService::getLatestApproval() at /home/pacs/cdo00/users/kimai/kimai/var/plugins/WorkContractBundle/Validator/Constraints/ApprovedWorkingTimesPeriodValidator.php:40)"} []

**Comment by glazperle** [comment]
I'm experiencing the same issue after updating to Kimai 2.25.0 (in combination with WorkingTime 1.15.0.)

This is blocking critical business operations as our employees cannot submit their timesheets.

The error occurs consistently when trying to create/submit timesheets or accessing sick leave / holiday information.

Environment details:

- Kimai 2.25.0
- WorkingTime Bundle 1.15.0
- PHP 8.3

Our stack traces and error messages are identical to the original report. The urgency is high as this affects our entire organization's time tracking capabilities.

Would appreciate any guidance on either:

- A temporary workaround to restore functionality
- Confirmation if this is a known compatibility issue
- Expected timeline for a fix

Happy to provide any additional information needed.

**Comment by kevinpapst** [comment]
Downgrade to 2.24 or wait for 2.26 or the next plugin version. Sorry!
Shouldn't have happened, but did... my mistake. 
See https://github.com/kimai/Paid-plugins/issues/205

**Comment by kevinpapst** [comment]
Should be fixed with 2.26 => https://github.com/kimai/kimai/releases/tag/2.26.0

Please let me know if that works now.

**Comment by glazperle** [comment]
> Should be fixed with 2.26 => https://github.com/kimai/kimai/releases/tag/2.26.0
> 
> Please let me know if that works now.

I haven't encountered any of the before mentioned issues since upgrading to 2.26.0. Thank you.
