### ISSUE TITLE
Contrast issues in calendar date picker in dark mode

### ISSUE THREAD

**Issue by plolock** [kimai/kimai#5206]
### Describe the issue

In some cases, the contrast is not great in dark mode, for example when select a time range in the calendar. Dates between the start and end date should have a darker color to more legible.

PS Love Kimai

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.25.0

### How do you run Kimai?

Other (please mention below)

### Which PHP version are you using?

Other (please mention below)

### Logfile

PHP 8.3.12
Self hosted

### Screenshots

![image](https://github.com/user-attachments/assets/e35ab047-eafd-4f38-9b4f-a570f2596fb1)

**Comment by kevinpapst** [comment]
Odd. Mine looks like that: 
<img width="329" alt="Bildschirmfoto 2024-12-05 um 10 09 25" src="https://github.com/user-attachments/assets/823066fe-f669-496a-a2fa-20c4df1c43c1">

Yours looks like pre https://github.com/kimai/kimai/releases/tag/2.24.0 (which had "fix daterange highlight color in dark mode
" in it). As if you either not use 2.25 or have outdated CSS.

**Comment by plolock** [comment]
Right, I'll investigate further.

The text would be even more legible if it was highter contrast, for example with the background color or even better pure black on the lighter blue fill. It'd pass more WCAG contrast checks in that sense.

**Comment by kevinpapst** [comment]
Happy to get help on that front, as I am a backend dev and have my troubles around "design and stuff" 😁

**Comment by plolock** [comment]
My pleasure, I'm the other way around: Produxt/UX/UI (but have worked a lot with in particular backend devs in my days)
