### ISSUE TITLE
More than one running Times viewable on Dashboard like V1.30

### ISSUE THREAD

**Issue by mr2017x** [kimai/kimai#5209]
### Describe the problem

Hi together,

sometimes a Projekt runs under two time frames, under v1.30 there it was possible to see two times at once and running, running seems to be possible, but not viewable on dash. 

### Describe the solution you'd like

can you implement it again to see more than one time slot be viewable?

**Comment by kevinpapst** [comment]
You can view all running timesheets in "my times".
There will be no visible support somewhere else re-added: this feature was removed deliberately.
