### ISSUE TITLE
Focus cursor on input field #name in popup (creating client/project/task)

### ISSUE THREAD

**Issue by b0rt** [kimai/kimai#522]
In the WebClient:

### Now
- in the timesheet view, 
- clicking the plus symbol (at the very bottom) to add e.g a new client 
- a popup opens up to create one. 
- One moves the mouse cursor from the bottom of screen to the input field (middle) of the popup to give it a name.

### Suggestion
make the focusing part automatic. 
- clicking +
- popups opens
- cursor (for typing) is in the name input field of the popup

Obviously this would be a (little) time saver and i think would improve the user experience,
saving the mouse moving, to allow faster creation.

Additional benefit: if the focus would be on the name input field, the other fields (except those behind tabs) could be reached by the tabulator key, allowing fast creation of new entries. (type name>tab key>type etc, hit enter, be done)

### some quick observations
it looks like every of those name input fields can be identified by #floater fieldset#general input#name

### related thoughts on expanding the idea
In an ideal scenario, the tabs (in the popup, or maybe in whole gui) could be reached by keyboard keys as well. Maybe the whole gui should be capable of being shortcut driven (in a helpful thoughtout way), i'm not sure what would be a good implementation of such features and its maybe a topic for another issue.

## posibly helpful article (use ARIA)
- http://www.smashingmagazine.com/2015/12/making-accessibility-simpler/

**Comment by simonschaufi** [comment]
Yeah, there is a lot to optimize. I also had this idea already but spending hours and hours on kimai is not possible right now because of financial reasons.

**Comment by kevinpapst** [comment]
Hey @b0rt - support ARIA or even achiving WCAG conformity is a huge (and probably almost unsolvable) task. Nevertheless we can strive for a better UX, so we appreciate every input & idea.

I just published a pull request that implements your request for the autofocus, thanks for that.
