### ISSUE TITLE
Unused options for \App\Form\Toolbar\ToolbarFormTrait::addActivitySelect

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#5220]
### Describe the issue

It is not possible to overwrite the options for \App\Form\Toolbar\ToolbarFormTrait::addActivitySelect while it is possible for the project and the customer. For the activities there is an internal variable $activityOptions for some reason that is not merged with the options. So the options parameter is completely useless.

Please make this method consistent with the project and customer so these methods behave the same.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.x

### How do you run Kimai?

Shared-Hosting

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Interesting. Like this: https://github.com/kimai/kimai/pull/5212/commits/43e570299c726c9c0ab0f02c346a12b5ff078848 ?
