### ISSUE TITLE
add then option to add a price + price per hour

### ISSUE THREAD

**Issue by Giuseppe-TD** [kimai/kimai#5223]
### Describe the problem

hi, i like this product, and i'm wondering if there's a way to add a specific amount in addition to the hour costs,
for example:
i'm working in IT and i'm payed 30 € for hour, i work for 2 hours for a client and i will be payed 60€, but i need the possibility to add an extra amount of ( example) 20 € for going to the client.
so the 60 € for 2 hours of work are for remote work and if i go to the client i would like to add 20€ because the "call"

### Describe the solution you'd like

ability to add an extra amount in the activity creation

**Comment by kevinpapst** [comment]
https://www.kimai.org/store/expenses-bundle.html

**Comment by kevinpapst** [comment]
Zero duration record with a fixed price is the alternative.

**Comment by Giuseppe-TD** [comment]
> Zero duration record with a fixed price is the alternative.

thanks but i prefer to put the extra cost in the same "activity" that involved me to go to the client, and sincerely pay 99 € per year just for this function is more that i was expecting :D

**Comment by kevinpapst** [comment]
> for this function is more that i was expecting

I hope your clients don't argue like that
