### ISSUE TITLE
Broken rates

### ISSUE THREAD

**Issue by turbojev** [kimai/kimai#523]
[logfile.txt](https://github.com/kimai/kimai/files/68982/logfile.txt)
[hpts.zip](https://github.com/kimai/kimai/files/68985/hpts.zip)

In both the stable and dev 0.9.3 releases, fixed rates aren't working.

If the fixed rate is set either in the admin panel for a project or activity, the cost defaults to 0. Say I have a fixed rate of 0.25, and the activity goes on for 4 hours, with only the fixed rate but not the regular rate set, those 4 hours come out to 0.00$.

If I set a standard rate and a fixed rate, it defaults to the standard rate. For example, if I set both the rate and fixed rate to 0.25, and the activity goes for 4 hours, the cost comes out to 1.00$, not 0.25$.

If I set the fixed rate when creating a new entry in the Budget tab (but it's not set in the admin panel), the entry won't create. In the debug extension it writes that the column 'rate' cannot be left empty. When I add a standard rate it works, but the rate is used and not the fixed rate.

This was reported by another user but not addressed, on the forum: http://forum.kimai.org/index.php?topic=3680.0

Logs and SQL data attached is for 0.9.3-13

**Comment by simonschaufi** [comment]
In my opinion the rates are totally buggy in general. I also had a discussion about them already here: #173.
@kevinpapst @ServiusHack

**Comment by simonschaufi** [comment]
I'm working on it...

**Comment by simonschaufi** [comment]
@turbojev I created a pull request. could you please test it? Just clone my forked repo and checkout the fixed_rate branch.
