### ISSUE TITLE
Minor terminological inconsistency: Time Sheet vs. Timesheet

### ISSUE THREAD

**Issue by EduNetEurope** [kimai/kimai#5230]
### Describe the issue

Not really a bug.
In pdf exports based on the template "Timesheet", the PDF title is "Timesheet".
In pdf exports based on the templates "Default", "With internal rates", "With remaining budget", the PDF title is "Time Sheet".

![image](https://github.com/user-attachments/assets/002928ec-f74d-4203-a45f-aab95d119d35)
![image](https://github.com/user-attachments/assets/15d60286-89b7-4a06-ba14-37d63c9bc2c4)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.26.0 Cloudron

**Comment by kevinpapst** [comment]
I doubt. Can't find that translation anywhere. Translation plugin? Test demo.

**Comment by EduNetEurope** [comment]
You are absolutely right, the above inconcistency is due to the translations plugin. I apologise, I meant to be helpful. Clearly failed.
