### ISSUE TITLE
Employment contract: define hours per day for specific periods + change history

### ISSUE THREAD

**Issue by EduNetEurope** [kimai/kimai#5231]
### Describe the problem

This request is specific to the community version of Kimai, not the Working Contract plugin.

In System / User / Edit / Employment Contract, we can set "Hours per day" under Working Time Calculation, which is an absolutely fantastic feature. Thank you for making this available in the free version, which is a true blessing for us and many others.

### Describe the solution you'd like

It would be absolutely amazing if we could define "Hours per day" for specific periods and view a history of changes. One can dream... :-)

**Comment by kevinpapst** [comment]
Thanks for your idea, but I have no plans to add support for that.
