### ISSUE TITLE
"Lock a month" doesn't work (no context menu)

### ISSUE THREAD

**Issue by mmospanenko** [kimai/kimai#5233]
### Describe the issue

In the [docs](https://www.kimai.org/documentation/contract.html) I see that we can lock completed months, but in the app there is no any context menus. Seems a UI bug.
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/a3f0410f-070e-4914-bfae-068db73a12f1" />

https://demo-stable.kimai.org/en/contract?date=2024-01-01&user=5

I see only MacOS menu, tested on Arc Browser (Chromium) and Safari current versions 
<img width="1300" alt="image" src="https://github.com/user-attachments/assets/6ea80c75-efa0-46c3-8f03-1b8f6be9a3b6" />

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.x.x

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
If you are a Kimai-Cloud user, please get in touch via support@kimai.cloud
It is available for users of the Pro subscription.

This feature is part of the WorkContract plugin. Use a demo that has all plugins installed.

**Comment by mmospanenko** [comment]
Thank you for quick response. Maybe you should mention this in the docs https://www.kimai.org/documentation/contract.html?
