### ISSUE TITLE
Please provide variants for the export templates "Default" and "Timesheet" - without the activity descriptions (only with client / project / tasks)

### ISSUE THREAD

**Issue by EduNetEurope** [kimai/kimai#5236]
Since for the average user, it turns out to be quite challenging [to add new export templates](https://www.kimai.org/documentation/export.html), would you consider providing variants of the existing export templates "Default" and "Timesheet" that are identical but do not show the descriptions? 
So basically variants that look like the existing ones when no description is present.

**Comment by kevinpapst** [comment]
It is not challenging: put a file into a directory as documented and reload the cache.

I am not going to add dozens of variants for every possible use-case. 
That's why they can be added.

**Comment by EduNetEurope** [comment]
Thanks, @kevinpapst.
I tried. They are not added to the dropdown menu automatically. For that to happen, another step seems to be required:

> You can translate the button for your template, by adding its name to the export translation file, eg. translations/export.en.xlf. Internally for each template a new ExportRenderer service is registered, called exporter_renderer.filename_EXT_twig (see ExportServiceCompilerPass).

This is where it got tricky for me. I do not exactly understand the instruction.

But it might also be a [limitation of the Cloudron environment](https://github.com/kimai/kimai/discussions/5235), which seems to have a "data" directory instead of the expected "var" directory.

**Comment by kevinpapst** [comment]
I updated the docs to be clearer and removed the fuss that is not necessary for 95% of the uses-cases.

**Comment by EduNetEurope** [comment]
Thank you, @kevinpapst.

To ensure the template is selectable in the dropdown, we still need to add its name to the export translation file, correct?

Where can we find this file? I attempted to copy the one from GitHub, adapt it, and save it in the export directory, but this approach didn’t work.

Or should the export templates appear automatically in the dropdown, and is this step only required to modify their displayed name (e.g., replacing the file name with something more descriptive)?

**Comment by kevinpapst** [comment]
If there is nothing about the filename in the docs, it is not required.

You need to clean the cache, as written in the docs. Which is likely what is missing.
