### ISSUE TITLE
Invoice number not iterated.

### ISSUE THREAD

**Issue by kbkozlev** [kimai/kimai#5247]
### Describe the issue

I have set the number to be a custom format having 8 leading zeros, so it should be 000000001, 000000002 etc.
![2024-12-18_10-29_1](https://github.com/user-attachments/assets/ce0aab94-4aeb-4bdd-b15c-499d5a48467b)

As seen in the screenshot below, it worked for the first 2 iterations.
![2024-12-18_10-27](https://github.com/user-attachments/assets/c8ed8aa1-7b77-493d-a650-803d3b1075a2)

Suddenly, when it came to the third iteration, the counter stopped and will not append +1 
![2024-12-18_10-29](https://github.com/user-attachments/assets/eeb02551-d13b-41f6-a3cc-a7961fb7b406)

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.26.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

Other (please mention below)

### Logfile

PHP version 8.3.14, otherwise "logfile missing"

**Comment by kevinpapst** [comment]
You checked the `I've read and searched the documentation`.

So I assume you have been at https://www.kimai.org/documentation/invoices.html#invoice-number-format

<img width="676" alt="Bildschirmfoto 2024-12-18 um 17 04 06" src="https://github.com/user-attachments/assets/8c2a12b6-db39-48f8-8494-2e2631603a57" />


Right? Tell me: is `cnumber` really what you want?
