### ISSUE TITLE
Batch Selection and Editing Not Working

### ISSUE THREAD

**Issue by mpyr6** [kimai/kimai#5249]
### Overview

The batch options for time entries are no longer visible when selecting multiple entries under Time Tracking > My Times or Time Tracking > All Times. Additionally, the "Select All in View" feature is not functioning as expected.

### Steps to Reproduce

1. Navigate to Time Tracking > My Times or Time Tracking > All Times.
2. Select multiple time entries.
3. Observe that the batch options are missing.
4. Attempt to use the "Select All in View" functionality.

### Expected Behavior

- Batch options (e.g., delete, export, or edit) should appear when multiple entries are selected.
- The "Select All in View" feature should select all currently visible entries on the page.

### Observed Behavior

- No batch options are displayed after selecting multiple entries.
- The "Select All in View" functionality does not work.

### System Information

- Operating System: Windows 11
- Browser: Firefox 133.0.3
- Server Environment: Synology NAS (DS716+)
- Deployment: Docker Image (kimai/kimai2:latest)
- Additional: 
- PHP 8.3.14
- System: Linux kimai 3.10.108 #42962

### Additional Context
This issue appeared after updating to the latest Docker image version (kimai/kimai2:latest). No custom configurations or third-party plugins were added post-update. This problem affects usability and efficiency when managing time entries in bulk.

### Severity
Medium: The absence of batch options and "Select All in View" functionality hinders workflow management.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.26.0 Prod

### How do you run Kimai?

Docker

### Which PHP version are you using?

Other (please mention below)

### Logfile

Do not have a log "Missing logfile" as well as int he var/log folder.

### Screenshots

![Multi Select Issue Image 2](https://github.com/user-attachments/assets/fdba045d-e3b5-41cc-9c83-c5ae0a5d0607)
![Multi Select Issue Image 1](https://github.com/user-attachments/assets/34543a11-9ea1-4d05-af49-58039488d5ea)

**Comment by kevinpapst** [comment]
> I've read and searched the documentation

Really? https://www.kimai.org/documentation/docker-compose.html#fpm-image

**Comment by mpyr6** [comment]
Thanks @kevinpapst. Read over that page a few times but it didn't click. Will keep that in mind for future updates!
