### ISSUE TITLE
Wrong currency format for Switzerland

### ISSUE THREAD

**Issue by FUF1** [kimai/kimai#5264]
### Describe the issue

When setting "Time, date and currency format" in "Preferences" to "Deutsch (Schweiz)" the currency format is €. Since CH (Switzerland) is not in EU, we are using CHF (Swiss Francs). (Date format DD.MM.YYYY and 24-hour format is correct).

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.27.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.3

**Comment by kevinpapst** [comment]
You really think your user preference is connected to the customers currency?

Please use discussions first.
