### ISSUE TITLE
New EventSubscriber in Report 11016 Create XML-File VAT Adv.Notif. 

### ISSUE THREAD

**Issue by OlgicaDejanovic** [kimai/kimai#5267]
### Describe the problem

Currently we cannot insert new Fields for export in XML, which is commonly requested by our customers.

Creating new event would make it possible

### Describe the solution you'd like

            if not AddElement(XmlRootElem, XmlElemNew, 'Ort', CompanyInfo.City, XmlNameSpace) then
                exit;
            XmlRootElem.GetParent(XmlRootElem);
        end;
        if not AddElement(XmlRootElem, XmlElemNew, 'Steuerfall', '', XmlNameSpace) then
            exit;

**OnAfterAddSteuerfallElement(XMLRootElem, XMLElemNew,XMLNameSpace);**

        XmlRootElem := XmlElemNew;
        if not AddElement(XmlRootElem, XmlElemNew, 'Umsatzsteuervoranmeldung', '', XmlNameSpace) then
            exit;
        XmlRootElem := XmlElemNew;

 
    [IntegrationEvent(false, false)]
    local procedure OnAfterAddSteuerfallElement(var XMLRootElem: XMLElement; XMLElemNew: XmlElement; XMLNameSpace: XmlNameSpace)
    begin
    end;

### Describe alternatives you've considered

it is not possible to add Eventsubscriber when there is AddFunction in exit Value:

    local procedure AddElement(var XmlNodeCurr: XmlElement; var XmlNodeNew: XmlElement; Name: Text; NodeText: Text; NameSpace: Text): Boolean
    begin
        XmlNodeNew := XmlElement.Create(Name, NameSpace, NodeText);
        exit(XmlNodeCurr.Add(XmlNodeNew));
    end;

**Comment by kevinpapst** [comment]
I have no clue what you are talking about. Are you sure, you are in the correct repository?
