### ISSUE TITLE
No error message is generated when MySQL fields can not be Null.

### ISSUE THREAD

**Issue by ghost** [kimai/kimai#531]
Hello,
Some fields that cannot be null are not indicated as required on the add edit customer floater.

According to my logfile.txt https://gist.github.com/JulienTremblayMcLellan/9285ae027d9cea7cfb4a
Some values can not be null, would it be possible to edit the HTML text and specify which fields are required? 

For example:
Address
Company (*required):
Contact person:
Street:
Zipcode:
City:

From my analysis only the company name and comment fields are required for creating a customer.

This is my first time reporting a bug, was it okay ? Do you need more info? Was this a valid issue to report? Should I of reported this in the user forum under Missing Features?

**Comment by simonschaufi** [comment]
Thank you for reporting this! Your provided info was helpful, even though your gist is not available.

I tried to get an error message back from mysql library but somehow this library does not return the mysql error.
anyway, i fixed this bug with commit 16c8046a91051baf4440cca4219304cdb0bd6b7d
