### ISSUE TITLE
language mixup with check for update

### ISSUE THREAD

**Issue by claudegel** [kimai/kimai#546]
Kimai have been installed with french language. Then switch to english in preference and admin panel. If I log out then the login screen is still in french. when I log in again and go in admin panel, everything is in english  as it should be but if I click on "look for update" I get a french answer.
if I go to preference and switch to french, then in admin panel all is in french and when I check for update I get a french answer. Switching for english again I still have a french answer for the look for update.

**Comment by simonschaufi** [comment]
well, there is the system language in the settings file and the user language which is stored in db. this bug needs some research what is going on.

**Comment by claudegel** [comment]
I'll check if I can find where is the problem.

**Comment by kevinpapst** [comment]
@claudegel I guess I found the problem. The welcome/login screen uses the language setting from autoconf.php, which is written when saving the admin settings. But it used the old language setting from the DB, instead of the submitted one. Check my linked PR for more details.
