### ISSUE TITLE
mysqli support for PHP 7

### ISSUE THREAD

**Issue by joejoe31b** [kimai/kimai#547]
PHP 7 no longer contains the mysql extension, and instead only has mysqli.

Arch offers only PHP 7 as the latest stable PHP version. This meant when I did a full system upgrade, my current Kimai installation showed only a white screen (with mysqli enabled). Even the installer wouldn't recognize my PHP installation as having MySQL enabled.

In my case, I had to temporarily downgrade php and php-apache to 5.6.17 to be able to continue using Kimai.

**Comment by simonschaufi** [comment]
Are you using latest master or a release version? I implemented mysqli some time ago but not sure if it works on php 7

**Comment by joejoe31b** [comment]
I only tested the latest release version. I will test the latest master, and get back to you.

**Comment by cljk** [comment]
PHP 7 is released one month and you´re updating a productive system?!

**Comment by joejoe31b** [comment]
I use Kimai to timekeep freelance work on my personal device. Arch is a rolling release distribution where packages are provided upstream, and it is therefore [recommended to update regularly.](https://wiki.archlinux.org/index.php/System_maintenance#Upgrading_the_system) 

PHP 7 is the current stable package offered in official Arch repositories.

**Comment by simonschaufi** [comment]
yes, please test the latest master and then report any issues that rise. I myself haven't installed php7 yet...

**Comment by slikarch** [comment]
...same here, after the latest Arch update Kimai won't run anymore (0.9.3 stable, just re-downloaded to make sure). Would be cool if you could test it in PHP7, let me know if I can help (not beeing a pro though)!

**Comment by jaapcrezee** [comment]
I got it working here:

[jaap@www ~ ]$ php -v
PHP 7.0.2 (cli) (built: Jan  6 2016 11:50:59) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
[jaap@www ~ ]$ cat /etc/issue 
Arch Linux \r (\l)

[jaap@www ~ ]$ 


I did a:

sudo pear install MDB2_Driver_mysqli-beta

**Comment by joejoe31b** [comment]
OK, I can confirm that mysqli isn't supported in the latest release version (0.9.3). The latest master supports mysqli, and works fine with PHP 7.

@jaapcrezee You shouldn't need to install that extension for it to work. It works fine with the [default pdo/mysqli extensions.](https://wiki.archlinux.org/index.php/PHP#MySQL.2FMariaDB)

**Comment by simonschaufi** [comment]
I'll close this issue as mysqli is implemented in master already, just not yet released.
