### ISSUE TITLE
New App for "Apps" page

### ISSUE THREAD

**Issue by Viras-** [kimai/kimai#548]
Can you please add our new App "TimeTrapp" with support for kimai to your "Apps" page on your website?

You can find out more here: http://forum.kimai.org/index.php?topic=3732.0

If you need more information please let me know!

**Comment by kevinpapst** [comment]
Hi Viras, sure we can.

Please send us a Pull request for the website - its the following file: 
https://github.com/kimai/kimai.github.io/blob/master/apps.md

We are very happy to hear about the new App btw ;-)
