### ISSUE TITLE
syntax error in extensions/ki_expenses/processor.php

### ISSUE THREAD

**Issue by jaapcrezee** [kimai/kimai#549]
Please fix:

    diff --git a/core/extensions/ki_expenses/processor.php b/core/extensions/ki_expenses/processor.php
    index a8e2f86..eb574e8 100644
    --- a/core/extensions/ki_expenses/processor.php
    +++ b/core/extensions/ki_expenses/processor.php
    @@ -34,7 +34,7 @@ function expenseAccessAllowed($entry, $action, &$errors) {
       // check if expense is too far in the past to allow editing (or deleting)
       if (isset($entry['id']) && $kga['conf']['editLimit'] != "-" && time()-$entry['timestamp'] > $kga['conf']    ['editLimit']) {
         $errors[''] =  $kga['lang']['editLimitError'];
    -    break;
    +    return false;
       }

**Comment by cljk** [comment]
Merged it to my repo (and pull request #545)

**Comment by simonschaufi** [comment]
please describe the error in more details why this is a bug.

**Comment by jaapcrezee** [comment]
The code is not doing what is specified in the comment.

**Comment by simonschaufi** [comment]
how can i test it?

**Comment by cljk** [comment]
I would recommend to just look at the code - https://github.com/kimai/kimai/blob/master/core/extensions/ki_expenses/processor.php line 34.... obviously the "break" makes no sense here - there is no loop or switch clause. The author wanted to output an error.... and exit the function...

**Comment by jaapcrezee** [comment]
Thank you.
