### ISSUE TITLE
Fixed rates totally broken

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#551]
I just added a fixed rate to a task and expected that for that task I get that amount of money no matter how long I work on it. Is my understanding right of what a "fixed rate" means?

What I see in the time entry is 0. Even after editing the entry afterwards manually and set a fixed rate there again, the amount of money still is not considered.

@kevinpapst @ServiusHack can you say something to this?

**Comment by kevinpapst** [comment]
Nope, sorry. I never used fixed rates and don't know what they are expected to do.
Neither do I know who implemented it in the first run.
I would say a fixed rate is an amount of money that is always taken as final value for one time entry, no matter how long it is.

**Comment by SeeVee** [comment]
I can confirm this feature is not working as intended.

Here is my particular use case: part of my job requires installation and configuration of network equipment/software. On my last job, some of that hardware was purchased by me and some was purchased by my client. Clearly I don't need to bill for hardware the client purchased, but I need to be able to include several items as fixed-cost line items.

While billing hourly for the installation/configuration makes sense, time is not a factor in the cost of the hardware I provided. Despite this, it should be fully billable to my client, and it should not confuse my client.

The current workaround is to manually modify the odt/HTML file output by Kimai.

**Comment by kevinpapst** [comment]
Can we close this one as duplicate of #523 ?

**Comment by simonschaufi** [comment]
jup
