### ISSUE TITLE
[bug] cannot hit OK when editing timesheet after server update, processor.php 500 error

### ISSUE THREAD

**Issue by jguithues** [kimai/kimai#552]
I started with a new database to make sure it wasn't something in my specific installation of Kimai.
When I try to edit any entry in the timeclock, if I try to hit OK nothing happens.  Even if I don't modify anything, just try to open and close, it fails. I can X or Cancel out of it of course, losing any changes.

If I open the console in Chrome, I get 
POST http://website.com/kimai/extensions/ki_timesheets/processor.php 500 (Internal Server Error)
whenever I hit OK

I saw a lot of issues here with a similar problem, but I'm using the latest release (0.9.3-1384) which already has every relevant patch I saw mentioned here.  I've been using 0.9.3rc1 for over six months with great success, hadn't had problems until just recently.

Problem started when my server admin updated apache, php, etc. to new versions after about a year of only security updates.  PHP updated to 5.6, but the issue persists even if I switch back to 5.4.  mysql was replaced by mariadb 10.0, but that is supposed to be a drop-in replacement.  Everything should be the latest industry standard; CentOS

**Comment by cljk** [comment]
Did your admin perhaps do an inplace update of CentOs itself? Had a similar issue with newer CentOs because of the SeLinux blocked write access. Did you have a look at the app-log (temporary/logfile.txt) or the apache-php-log (/var/log/httpd/error_log)??

For me I experience another similar bug : if a user has no loan/rate set, he cannot edit entries... perhaps you experience the same?! I made a small sql script for me as workaround (last 2 stmts of https://github.com/cljk/kimai_skripts/blob/master/kimai_update_users.sql).
Haven't filed it yet because I wanted to debug this further before opening an issue.

**Comment by jguithues** [comment]
He simply used the update tools in cpanel, updated to CentOS 6.7  My user has rate set, so that doesn't appear to be my issue.  Here is my kimai logfile.txt which doesn't seem to have any errors.  I'll update with httpd/error_log when I get it
[logfile(2).txt](https://github.com/kimai/kimai/files/110558/logfile.2.txt)

**Comment by cljk** [comment]
Seems so... :-(

Perhaps the php log reveals some issues or the devs have an idea....

**Comment by simonschaufi** [comment]
maybe related to #483 or #178?

**Comment by jguithues** [comment]
I appreciate your attention.  I manually set my cache directory as suggested in #483, but that doesn't seem to have an effect.  Similarly to #178 I don't seem to be getting a response back, but I've attached the text of my request.  I've also attached a chunk of the error_log, during which I was attempting to edit entries. I don't see anything relevant, but it couldn't hurt.  I figure I need to adjust the level of php error reporting, but I'm on a shared host, so I have to wait until tomorrow to work with my admin to make that happen.  
[httpPOSTerror.txt](https://github.com/kimai/kimai/files/111078/httpPOSTerror.txt)
[error_log 1-30-2016.txt](https://github.com/kimai/kimai/files/111079/error_log.1-30-2016.txt)

**Comment by joejoe31b** [comment]
I am having the same problem. Everything worked smoothly for me, both the master and the current stable, but suddenly this morning I cannot edit an entry (the 'OK' button does nothing and the popup stays). I can't even manually add a timesheet entry.

I tried reinstalling fresh (both master and current stable), and downgrading to PHP5, but I still can't solve the problem.

I get a 500 POST error on the processor.php file like @jguithues, and my response + request headers, and POST data are almost identical to his.

**Comment by cljk** [comment]
Have you set a rate for your user too!?

**Comment by joejoe31b** [comment]
Yes, even with a rate set in the user preferences the problem occurs.

Here is what my 500 error post looks like:
```
id=3
axAction=add_edit_timeSheetEntry
projectID=1
filter
activityID=1
filter
description
start_day=07.02.2016
end_day=07.02.2016
start_time=11:38:38
end_time=11:38:58
duration=00:00:20
location
trackingNumber
comment
commentType=0
userID=900183106
budget
approved
statusID=1
billable=0
rate=20.00
fixedRate=0.00
```

**Comment by joejoe31b** [comment]
Here is what is recorded in my temporary/logfile.txt:
```
# Login as admin
[07.02.2016 13:35:02] login: admin as user
[07.02.2016 13:35:02] Global role 1 gave true for ki_invoice-access.
[07.02.2016 13:35:02] Global role 1 gave true for ki_timesheet-access.
[07.02.2016 13:35:02] Global role 1 gave true for ki_export-access.
[07.02.2016 13:35:02] Global role 1 gave true for adminPanel_extension-access.
[07.02.2016 13:35:02] Global role 1 gave true for ki_budget-access.
[07.02.2016 13:35:02] Global role 1 gave true for deb_ext-access.
[07.02.2016 13:35:02] Global role 1 gave true for ki_expenses-access.
[07.02.2016 13:35:02] Global role 1 gave true for core-user-otherGroup-view.
[07.02.2016 13:35:02] Global role 1 gave true for core-customer-otherGroup-add.
[07.02.2016 13:35:02] Global role 1 gave true for core-customer-otherGroup-edit.
[07.02.2016 13:35:02] Global role 1 gave true for core-project-otherGroup-add.
[07.02.2016 13:35:02] Global role 1 gave true for core-project-otherGroup-edit.
[07.02.2016 13:35:02] Global role 1 gave true for core-activity-otherGroup-add.
[07.02.2016 13:35:02] Global role 1 gave true for core-activity-otherGroup-edit.
[07.02.2016 13:35:02] Global role 1 gave true for ki_timesheets-showRates.
# Installer security warning
[07.02.2016 13:35:02] KSPI axAction (admin): securityWarning
# Click edit icon, change duration, and click the OK button once
[07.02.2016 13:35:07] KSPI axAction (admin): add_edit_timeSheetEntry
[07.02.2016 13:35:07] Global role 1 gave true for ki_timesheets-ownEntry-edit.
[07.02.2016 13:35:07] Global role 1 gave true for ki_timesheets-otherEntry-otherGroup-edit.
[07.02.2016 13:35:07] Global role 1 gave true for ki_timesheets-editRates.
[07.02.2016 13:35:07] KSPI axAction (admin): reload_activities_options
[07.02.2016 13:35:12] KSPI axAction (admin): add_edit_timeSheetEntry
[07.02.2016 13:35:12] Global role 1 gave true for ki_timesheets-ownEntry-edit.
[07.02.2016 13:35:12] Global role 1 gave true for ki_timesheets-editRates.
```

The corresponding line in my Apache error_log file:
`[Sun Feb 07 17:35:12.541134 2016] [:error] [pid 6207] [client 127.0.0.1:33924] PHP Fatal error:  Call to undefined function iconv_get_encoding() in /srv/http/kimai-master/kimai-master/core/libraries/Zend/Locale/Format.php on line 781, referer: http://localhost/kimai-master/kimai-master/core/core/kimai.php`

**Comment by cljk** [comment]
Ok, without further looking I guess your system is missing the iconv-module...
Debian/Ubuntu?!

# sudo apt-get install php5-iconv

**Comment by kevinpapst** [comment]
Thanks for the information, I created a pull request to inform users about this new requirement (iconv PHP module) during installation process here: https://github.com/kimai/kimai/pull/553

As it is enabled by default in PHP this never showed up in our development and production systems and should hopefully not be a big deal for most new users.

Sorry for the trouble you guys have right now! As @cljk pointed out, there is an easy fix if you host it on your own server. If you installed Kimai in a managed/hosted environment, send you administrator an email, pointing him to the following page and ask him if he can install or activate it for you:
http://php.net/manual/en/iconv.installation.php

**Comment by kevinpapst** [comment]
Guys, as you found out that this is a new server requirement and therefor not "a bug" we can really fix, I updated the installer to reflect that and closed this issue.
I also updated the download page: http://www.kimai.org/download/
and the documentation page: http://www.kimai.org/documentation/installation/index.html

Please reopen this or create a new issue, if you still experience problems after installing the iconv extension.
