### ISSUE TITLE
Not able to add Timesheet entry without setting rate for user

### ISSUE THREAD

**Issue by cljk** [kimai/kimai#557]
As already pointed out by others the rates are a bit buggy - but I digged into a concrete problem for the current HEAD source tree.

If a user has no rate set, he is *not* able to add a timesheet entry. As I´ll try to show this has more than one reason.

`ki_timesheets/processor.php` is called with the field `rate` unset.... so far so clear. To initialize the form first `$database->get_best_fitting_rate` is called - there is the first error?!
In `Mysql.php` the function `get_best_fitting_rate` tries to estimate the best rate... if there are globals set (thats what I understand the function to do). But on my system it doesn´t. 

The query is produced correctly
```
      $query = "SELECT rate FROM " . $this->kga['server_prefix'] . "rates WHERE
    (userID = $userID OR userID IS NULL)  AND
    (projectID = $projectID OR projectID IS NULL)  AND
    (activityID = $activityID OR activityID IS NULL)
    ORDER BY userID DESC, activityID DESC, projectID DESC
    LIMIT 1;";

        $result = $this->conn->Query($query);
```
results to 
```
SELECT rate FROM kimai_rates WHERE (userID = 535744355 OR userID IS NULL) AND (projectID = 2 OR 
 projectID IS NULL) AND (activityID = 4 OR activityID IS NULL) ORDER BY userID DESC, activityID DESC, projectID 
 DESC LIMIT 1
```

I´ve filled a rate for the project (ID 2) previously and if I query it manually I get a single result as expected: "rate = 1.00"
BUT - (BUG) in `Mysql.php`on line 2889 the check for `RowCount`
```
if ($this->conn->RowCount() == 0)
            return false;

        $data = $this->conn->rowArray(0,MYSQLI_ASSOC);
        return $data['rate'];
```
returns "-1" instead of "1" - so the flow continues and an assoc array is tried to be fetched - but instead of an assoc array "false" is assigned to `$data`.
BTW $result->num_rows IS "1". (result is of type mysqli_result).

So obviously the query is executed correctly and the mysql-server returns a row - but the mapper class doesn´t work correctly here.

I tracked it down to `mysql.class.php`
```
$result = @mysqli_affected_rows($this->mysql_link);
			if (! $result) {
				$this->SetError();
				return false;
			} else {
				return $result;
			}
```
I don´t understand why but `@mysqli_affected_rows($this->mysql_link);` does indeed return "-1" and is the source for the confusion.

Field `error_desc` is written meanwhile to MySQL-class with
```
Row number is greater than the total number of rows
```

We continue our flow in `processor.php` - my next problem is in line 540 (552 to be concrete)

```
       $database->transaction_begin();

        foreach ($_REQUEST['userID'] as $userID) {
          $data['userID'] = $userID;

          if (!timesheetAccessAllowed($data,$action,$errors)) {
            echo json_encode(array('errors'=>$errors));
            $database->transaction_rollback();
            break 2;
          }

          Logger::logfile("timeEntry_create");
          $database->timeEntry_create($data);
        }

        $database->transaction_end();
```
`$database->timeEntry_create` is called - and returns `false` because the column `rate` is NON-Null. - but the return value is not checked. So there is no error displayed.

So - long story short..... we need to
* fix the error check on `$database->timeEntry_create($data);`
* fix the RowCount-Check in `get_best_fitting_rate`
* and/or `get_best_fitting_rate` should return a default value if none is found

**Comment by cljk** [comment]
If nobody volunteers, I´ll look to find time for that... ;-)

**Comment by kevinpapst** [comment]
Wow, great detective at work here :-) 
If I read the docu correctly http://php.net/manual/en/mysqli.affected-rows.php returns mysqli_num_rows() for select statements but they also have that statement on the man page:
> -1 indicates that the query returned an error.
So, can you see anything in the logfile file (kimai, php and database)?

**Comment by cljk** [comment]
Yeah, I read the same - but I don´t think the query provokes an errror. I couldn´t find out why
`$result->num_rows` returns the correct result "1" - but `@mysqli_affected_rows($this->mysql_link)` returns "-1". No errors in the log nor anywhere I could think of. I even can see in the debugger, that the $result var is filled with the correct database answere. There is something wrong in the DB-wrapper class (did I see this correct, that we have cascaded wrappers?).

My first guess is, that this has smth. to do with wrong used `$this->mysql_link` but I couldn´t check this further because my time ran out. Hope my debugger brings something to light on thursday.

I could solved my specific "problem" with just changing one line in `processor.php` - but then I would have to bypass the Mysql-mapper-class. This would only be a dirty workaround.

**Comment by cljk** [comment]
in `mysql.class.php` on line 1122 is another bug:
```
$numrows = mysqli_field_count($this->mysql_link);				
```
Obviously not the number of rows is fetched - but the number of columns.... It´s "working" because its only needed for the check if ANY result is present....

**Comment by cljk** [comment]
Perhaps you want to integrate my commit https://github.com/cljk/kimai/commit/43c3c936c7175c19747ed88b852f305df66f5ed8
* default value "0.00" for `get_best_fitting_rate` if none present
* error check in `ki_timesheets/processor.php` on `timeEntry_create` -> displays error on SQL-Error (at least in the log and the floater doesn´t close)
* bugfix in `mysql.class.php` - this is the only part I can not guarantee WHY this works and not the older solution - but on my system it´s the case - I can safely refer to `$last_result->num_rows` but not get `mysqli_affected_rows($this->mysql_link)`. Currently I just don´t want to investigate further WHY this is the case ;-) The complete mysql.class.php is....... to be "improved"

**Comment by cljk** [comment]
.... not?!

**Comment by kevinpapst** [comment]
Yes, we want to fix this. The bug was initially introduced by an upgrade of the underlying mysql.class.php, which potentially lead to other bugs as well. We have to sort these problems out first, before we continue with your commit. 

We might have to extend the mysql.class.php and implement your changes in there, because patching an external library was the problem in the first place (the old version of mysql.class.php was patched as well and we didn't knew that).

So yes, we are working on it and thanks again for your help!!!

**Comment by cljk** [comment]
Thanks guys...

**Comment by kevinpapst** [comment]
Thanks for your support and the improvement ideas!
