### ISSUE TITLE
Remove support for mutiple database

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#560]
Kimai has had the feature to support usage of different databases, through Request/Cookie settings.
I never used the feature, never heard any user asking for such a feature or complaining that it doesn't work nor did I ever find any documentation about how to use it.
This feature is still kind of active in https://github.com/kimai/kimai/blob/master/includes/basics.php#L68 and following lines.

I would recommend that we delete this feature, which I believe does not work anymore.

Thoughts on that @kimai/core-team ?

**Comment by kevinpapst** [comment]
More related code here: 
https://github.com/kimai/kimai/blob/master/index.php#L39
and here: 
https://github.com/kimai/kimai/blob/master/index.php#L231

**Comment by simonschaufi** [comment]
I just know that somebody was making a PR about PostgreSQL here: #428

**Comment by kevinpapst** [comment]
Thats not related IMO. There seems to be a "hidden" feature that none of the current developers know, where you can select between mutiple backend databases. 
Maybe for something like a huge company, managing only one Kimai installation, but using multiple databases for different teams.

**Comment by simonschaufi** [comment]
still don't understand the usecase but imho can be removed.

**Comment by kevinpapst** [comment]
I don't as well, thats why I want to remove that old code ... but wanted to discuss it first.
Lets see if someone else comments that one, otherwise I an going to delete that code in the next days

**Comment by kevinpapst** [comment]
Variables to search for while refactoring:
kimai_db
$server_ext_database
$server_ext_verbose
$server_verbose
$view->selectbox in login/panel.php
