### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ebelix** [kimai/kimai#579]
![kimai-installation](https://cloud.githubusercontent.com/assets/8679103/13421059/d4e49ebe-df8b-11e5-87ce-478aecaa8eca.png)
I wanted to install kimai and there is no coming further. I cant choose the time zone and therefore I cant go on to install

**Comment by kevinpapst** [comment]
That is a strange behaviour. Which version: latest master or official release?

**Comment by xaro1** [comment]
Maybe linked to #580 ?

**Comment by ebelix** [comment]
php 5.4
kimai-kimai-0.9.3-183-gcf500fd.zip

**Comment by kevinpapst** [comment]
I don't know that zip file. Is that the official release? 
The list of timezones is fetched by PHP, seems it is not populated. Can you access your server logs?

**Comment by kevinpapst** [comment]
@ebelix - I added a workaround for an empty timezone list, which will be available tomorrow:
https://github.com/kimai/kimai/pull/586

@xaro1 - I don't think that it comes from #580 - I cannot verify the bug, might be related to a none-default PHP setup / hosted environment.

**Comment by xaro1** [comment]
@ebelix : #580 is fixed.

**Comment by kevinpapst** [comment]
Ah, see... fetchTimezoneList() list was located in func.php , which was included in that installation step.
Yeah, probably you were right @xaro1 with #580 
Can you retest with the current master @ebelix ? Maybe my workaround in #586 is not even required...

**Comment by kevinpapst** [comment]
I close this issue as resolved. If you still experience troubles, go ahead and reopen this issue.

**Comment by ebelix** [comment]
das funktioniert jetzt, nun aber bleibt die Installation nach diesem Bild hängen... es passiert nichts mehr :-(
![fehler-kimai](https://cloud.githubusercontent.com/assets/8679103/13555930/c65c19d0-e3cd-11e5-9cce-b94b8d7e873b.png)

**Comment by kevinpapst** [comment]
Hm, da kann man nur raten. Du musst mehr Informationen besorgen aus den Server Logfiles oder Deiner Javascript Konsole. Die Installation läuft hier auf mehreren Servern problemlos durch.

**Comment by simonschaufi** [comment]
the next step would be database connection. is that service running correctly?

**Comment by claudegel** [comment]
Hi I don't read german but I had a problem with installation of last merged git kimai.
Problem is in the file ../steps/60_...
At the beginning the request for mysql.class.php is wrong. The path for that file is not good.
I'm not in front of my computer so cannot say more

Hope this help

Claude Gelinas agr.
Phyto Ressources Inc.

**Comment by simonschaufi** [comment]
@claudegel fixed right now!

**Comment by claudegel** [comment]
I fetch the latest master and now I can login but the login page is all scrambled:
![login_screen](https://cloud.githubusercontent.com/assets/4268938/13590954/50eaf618-e4b2-11e5-8f7d-2a2a8914b25e.png)
after I fetch upstream, when I did git merge --ff-only upstream/master, I got two error about file 
includes/func.php and includes/version.php. I had to stash them in order to complete the merge. Don't know why git ask me to stash them because I didn't play with these files.

**Comment by ebelix** [comment]
Ich habe eine Datenbank eingerichtet für Kimi, aber es wurde bis zu diesem Zeitpunkt noch nicht danach gefragt :-(
weder nach dem Namen noch nach dem Benutzer

**Comment by kevinpapst** [comment]
@claudegel Please flush your browser cache, might be due to some moved CSS and image files.
@ebelix The admin account is displayed in the last step of the installation: User "admin" and password "changeme"

**Comment by ebelix** [comment]
es hat geklappt, die Installation ist durch..
DANKE

**Comment by kevinpapst** [comment]
Finally, thanks for your feedback and help in solving the issues on our end!

**Comment by claudegel** [comment]
Ok I've flushed the cash and still the same. I dig a little and found this:
<p>The requested URL /skins/standard/login.css was not found on this server.</p>
That css is there but maybe the path is incorrect or permissions are bad

**Comment by kevinpapst** [comment]
@claudegel http://demo.kimai.org/ <= is automatically installed and uses the latest master. It works there and on my local dev environments as well.
If you have any hint what migh be going on (e.g. incompatible changes with subdirectory hosting) I'd be happy to investigate and fix it. But please open a new issue for that.
