### ISSUE TITLE
Current master install/upgrade not working

### ISSUE THREAD

**Issue by xaro1** [kimai/kimai#580]
When installing fresh clone of current master, I get this error at install step 3:

<pre>PHP Parse error:  syntax error, unexpected 'return' (T_RETURN) in /var/www/kimai-master/includes/func.php on line 138, referer: http://xxx/installer/index.php</pre>

Previous steps passed successful.
PHP version: 5.4.23

**Comment by xaro1** [comment]
I think is caused by your f*** Stupid Auto-Scrutinizer-o-matic of death.
Please check : https://github.com/kimai/kimai/commit/02e8161174fda8d980f9387d051c96e41b3da130

**Comment by xaro1** [comment]
Bingo! I reverted commit on func.php and now, it works...

Auto-Scrutinizer + CRAPPY code = TOTAL MESS !

**Comment by kevinpapst** [comment]
Yeah, thats for finding it. We know the code is messy. We took over the project to keep it alive. No reason for bitching. If you know how to revert the commit, send in a pull request.
And yes, true, we will not use Scrutinizer any more.

**Comment by simonschaufi** [comment]
@xaro1 thank you for your report but please be respectful! master branch is under heavy development right now.

**Comment by xaro1** [comment]
Please be respectful with Kimai users by using devel branch instead of master branch when experimenting with some gadgets !

**Comment by simonschaufi** [comment]
we don't use devel branch. master is the only one where things go on so please don't always expect a stable master. use the latest release if you don't need the latest features/bugfixes

**Comment by xaro1** [comment]
Simon, you don't understand me... I don't expect a stable master, I just expect a true development master branch, maybe with some corrected bugs, some enhancements or some new features... The master branch is not the place for experimenting with an automated tool which is definitely not compatible with crappy code and especially that does nothing positive...

**Comment by kevinpapst** [comment]
Hot-fixed it. Please retry and let us know if it works now. 
I just tested quickly and at least Kimai loads again. I have no clue if there is still some hidden bugs left.
Promised: we wont use Scrutinizer anymore. 

And thanks for both, the open feedback and upvoting for the Workflow topic!

**Comment by xaro1** [comment]
I confirm that master branch work now. Some other bugs still exist but I will open issues for them.

Yes, devel branch is the best solution while master will be used to cleanup current code. Maybe, this will attract more contributors.

**Comment by kevinpapst** [comment]
Cool, we will be going to use develop soon. 
Just give us some time to merge all open issues and make sure we all understand that approach in the same way. I will update the CONTRIBUTING guidelines accordingly.
Thanks for helping @xaro1 :)
