### ISSUE TITLE
Scrutinizer make mess everywhere

### ISSUE THREAD

**Issue by xaro1** [kimai/kimai#582]
PHP code broken here :
extensions/ki_adminpanel/init.php on line 131
extensions/ki_adminpanel/processor.php on line 113
extensions/ki_adminpanel/processor.php on line 115

**Comment by xaro1** [comment]
also here :
extensions/ki_adminpanel/processor.php on line 115

Come on guys... Seriously, do you test your code before/after committing ?

**Comment by kevinpapst** [comment]
Thanks for the info and no need to be rude. 
@simonschaufi Please revert all Scrutinizer commits!
