### ISSUE TITLE
Team discussion: Use Gitflow Workflow

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#584]
Hi @kimai/core-team,

I'd like to make a suggestion to improve our development process. In my business projects I am successfully using the [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) with multiple teams. I'll try try to cover it in a short summary (but please read the linked documentation as well, if you don't know it yet): 

- We work on a branch called "develop". 
- All feature branches go off from "develop" and will be merged back into develop once reviewed via PR. 
- Once there is a stable "develop" version, this will be merged back to "master". 
- If we are done with all features/changes for a new release, we create a new branch "0.9.x" from "master" and perform all changes necessary for the release (change version number ...) there
- the "0.9.x" branch will be kept for later bugfixes (if necessary). 
- The release TAG will be created from that branch as well

I would suggest that we start using this Workflow and see how it goes. This way, we could keep the master stable and do not run into troubles (like today) if people use the master for their production systems (which is a bad idea, no doubt).

Whats your opinion? Shall we give it a try?

**Comment by xaro1** [comment]
+1 !!!

**Comment by kevinpapst** [comment]
We shall not forget to write it down at:
https://github.com/kimai/kimai/blob/master/CONTRIBUTING.md

**Comment by simonschaufi** [comment]
important things to consider:

- no PRs in master!
- issues need a clear information on which branch the issue relates to
- who decides when and how often a merge into master happens? (after a feature, bugfix which is stable or after a feature freeze and some weeks of testing?)
- will the master or devel branch be used for the demo site? (probably master, just a question...)

**Comment by kevinpapst** [comment]
Valid points and as discussed:
- PRs only against devel (with the exception of a hotfix, which would be merged from master to develop)
- We should add issue and pull request templates, see https://help.github.com/articles/helping-people-contribute-to-your-project/
- Merging should happen after bugfixes and for a release. Probably more often if see that a stable version is there or only minor adjustments happened since the last release. Open for discussion, I believe almost everything is better than working on master directly ;-)
- I would use the master, so the demo won't break. Buts its a valid point. We could think about hosting a second demo using the develop branch, not sure yet. Probably people who consider to try develop are experienced enough to host it by themself.

**Comment by kevinpapst** [comment]
Accepted and closing - we can still discuss it here, but users don't have to see this issue.
