### ISSUE TITLE
permission to view tracked time of other user

### ISSUE THREAD

**Issue by Nef10** [kimai/kimai#604]
I have not found any setting for viewing tracked time of the same group, only editing. Is there any setting to disallow users to see any tracked time other than their own? 

Or maybe another way to accomplish this?

**Comment by kevinpapst** [comment]
Hey @Nef10 - thanks to your comment I found a bug in the current master, which I believe is there for quite some time. A user should by default only see himself. 

He should only see other users of the same group, if the setting "Membership role > Permission > Regular user > View" is activated. Or if "global role" > "Permission" > "Regular user, different group" > "View" is activated.

I submitted a fix for that here: https://github.com/kimai/kimai/pull/605
Your issue will be closed once it was integrated. You can then try the latest version and see if that fixes your problem.
