### ISSUE TITLE
Changing The Time Format in Export Window.

### ISSUE THREAD

**Issue by ShahadatHossainRafi** [kimai/kimai#615]
![lylstov](https://cloud.githubusercontent.com/assets/941794/13807382/36b6c244-eb61-11e5-8497-8918da8e8391.png)

#### Expected behaviour
I just want to see the time format in DD:MM:YYYY from current DD:MM format. Which file to edit and which line? Any idea?

#### Actual behaviour
Currently the column showing only DD:MM format date.

#### Steps to reproduce the behaviour
I think this customization is very simple.

#### Kimai version
Latest

#### Relevant log entries from Kimais Debug tab

**Comment by kevinpapst** [comment]
Hey @ShahadatHossainRafi - I created a Pull request to fix this problem.
The format should be taken from the global config and will be, once the PR is merged.

The relevant changes are:
https://github.com/kimai/kimai/pull/616/files#diff-b25898b71ec0044853bc236aa5b9ee97R42
and
https://github.com/kimai/kimai/pull/616/files#diff-b25898b71ec0044853bc236aa5b9ee97L62

**Comment by ShahadatHossainRafi** [comment]
Hello @kevinpapst thanks for your reply. As I am new here in github so still I need to learn a lot. Actually what should I do now? Should I download the file you provided to me and then replace existing extensions/ki_export/init.php file?

**Comment by ShahadatHossainRafi** [comment]
Hello @kevinpapst many thanks for your help... :)
