### ISSUE TITLE
Add audit logs

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#62]
Add automated audit logs

For example:
- https://github.com/DamienHarper/DoctrineAuditBundle

Probably outdated: 
- https://github.com/simplethings/EntityAuditBundle
- https://github.com/xiidea/EasyAuditBundle
- https://github.com/DATA-DOG/DataDogAuditBundle

**Comment by kevinpapst** [comment]
no feedback for almost a year, closing. please re-open if you want to have that

**Comment by simone-gasparini** [comment]
Are you working on this? Have you started the plugin?

**Comment by kevinpapst** [comment]
Yes, it's ready. But I am going to sell it, it won't be for free. I am currently figuring out some details (license, shop)- thats why it is not announced. 
Contact me via my email, I don't mind sharing it with a contributor.
Thanks for finding this issue, I need to close it.
