### ISSUE TITLE
rename db fields

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#626]
- The column name 'option' is a MySQL reserved keyword in table kimai_configuration, kimai_preferences
- make all tables and columns lowercase (partially revert [r1368](https://github.com/kimai/kimai/blob/master/updater/updater.php#L695))

**Comment by kevinpapst** [comment]
:+1: 
Lets try to be consistent as well. A lot of the tables have an underscore in their name, some (like fixedRates, globalRoles or membershipRoles) don't. That should be changed as well.
Codewise, I'd like to see the usage of the "Mysql::getTableName()" functions everywhere. That might sound stupid in the first place, but would make 1. updating or 2. creating extensions ... much safer.

**Comment by kevinpapst** [comment]
Lets move that to kimai/roadmap ?

**Comment by simonschaufi** [comment]
yes
