### ISSUE TITLE
Expenses also shows data from invisible customers

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#627]
#### Expected behaviour
invisible customer data is not included in the charts

#### Actual behaviour
they are included

#### Steps to reproduce the behaviour
make a customer invisible

**Comment by kevinpapst** [comment]
Charts means Budget or really Expenses? And why am I assigned, don't you want? :-)

**Comment by simonschaufi** [comment]
I mean the whole chart boxes in the budget tab. You have a deeper code knowledge now than me ;)

**Comment by kevinpapst** [comment]
Okay, the visible flag is completely ignored for customers, projects and activities.
I will implement a check on every level for the visible setting
