### ISSUE TITLE
 Uncaught exception: Plugin by name 'Cycle' was not found in the registry

### ISSUE THREAD

**Issue by jasonpasnikowski** [kimai/kimai#631]
#### Expected behaviour
 Uncaught exception: Plugin by name 'Cycle' was not found in the registry; used paths:Zend_View_Helper_: Zend/View/Helper/:/home4/domainname/public_html/timetracker//templates/helpers/

#### Steps to reproduce the behaviour
Log into Kimai for the first time with admin/changeme, get blank screen. logfile.txt displays:

[22.03.2016 11:16:08] login: admin as user
[22.03.2016 11:16:08] Global role 1 gave true for ki_timesheet-access.
[22.03.2016 11:16:08] Global role 1 gave true for ki_expenses-access.
[22.03.2016 11:16:08] Global role 1 gave true for adminPanel_extension-access.
[22.03.2016 11:16:08] Global role 1 gave true for ki_budget-access.
[22.03.2016 11:16:08] Global role 1 gave true for ki_invoice-access.
[22.03.2016 11:16:08] Global role 1 gave true for ki_export-access.
[22.03.2016 11:16:08] Global role 1 gave true for core-user-otherGroup-view.
[22.03.2016 11:16:08] Uncaught exception: Plugin by name 'Cycle' was not found in the registry; used paths:Zend_View_Helper_: Zend/View/Helper/:/home4/domainname/public_html/timetracker//templates/helpers/
[22.03.2016 11:20:15] Global role 1 gave true for ki_timesheet-access.
[22.03.2016 11:20:15] Global role 1 gave true for ki_expenses-access.
[22.03.2016 11:20:15] Global role 1 gave true for adminPanel_extension-access.
[22.03.2016 11:20:15] Global role 1 gave true for ki_budget-access.
[22.03.2016 11:20:15] Global role 1 gave true for ki_invoice-access.
[22.03.2016 11:20:15] Global role 1 gave true for ki_export-access.
[22.03.2016 11:20:15] Global role 1 gave true for core-user-otherGroup-view.
[22.03.2016 11:20:15] Uncaught exception: Plugin by name 'Cycle' was not found in the registry; used paths:Zend_View_Helper_: Zend/View/Helper/:/home4/domainname/public_html/timetracker//templates/helpers/

I noticed that there are double slashes between "timetracker" and "templates"... is there perhaps an error in the code somewhere?

**Comment by kevinpapst** [comment]
Hey @jasonpasnikowski , 

the double slashes do not matter, but thanks for pointing out!

1. Which Kimai version is that? I believe we had one version online for a short time that had a bug, sounding like your problem. If this is the website download, please try this one: 
https://github.com/kimai/kimai/archive/master.zip

2. For some reason, your installation does not find a file, which should be autoloaded, this one:
https://github.com/kimai/kimai/blob/master/libraries/zendframework/zendframework1/library/Zend/View/Helper/Cycle.php
Can you confirm that it is available in your installation?

Last option would be to patch a file and see if this would fix your problem, but only if point 1. does not work. Probably your server is configured in a "funny" way, preventing the autloader from working properly.
In that case, you have to edit the file index.php in the Kimai folder and add one line. Should be line 47. 
Find and change like here https://github.com/kimai/kimai/blob/master/index.php#L47:
```
$view` = new Zend_View();
$view->setBasePath(WEBROOT . '/templates');
$view->addHelperPath(WEBROOT . '/libraries/zendframework/zendframework1/library/Zend/View/Helper');
```
The last line is the new one.

**Comment by simonschaufi** [comment]
well, double slashes should be avoided.

**Comment by kevinpapst** [comment]
Maybe, but the probleme here does definitely not come from the double slash. 
Interesting read on this topic and why it doesn't matter:
http://unix.stackexchange.com/questions/1910/how-does-linux-handle-multiple-consecutive-path-separators-home-username

**Comment by jasonpasnikowski** [comment]
Thank you!
I think I was using version 0.9.3? I had just downloaded it a few days ago.

I used the version you sent and all is well. I found when I was extracting
the files that I received an error on my Windows PC that the path name was
too long to extract some files, so I moved my extraction point to the root
folder, and that fixed that. I wonder if perhaps the same issue had
happened with the previous installation and I had ignored the error.

Thanks again!

On Tue, Mar 22, 2016 at 5:16 PM, Kevin Papst <notifications@github.com>
wrote:

> Hey @jasonpasnikowski <https://github.com/jasonpasnikowski> ,
>
> the double slashes do not matter, but thanks for pointing out!
>
>    1.
>
>    Which Kimai version is that? I believe we had one version online for a
>    short time that had a bug, sounding like your problem. If this is the
>    website download, please try this one:
>    https://github.com/kimai/kimai/archive/master.zip
>    2.
>
>    For some reason, your installation does not find a file, which should
>    be autoloaded, this one:
>
>    https://github.com/kimai/kimai/blob/master/libraries/zendframework/zendframework1/library/Zend/View/Helper/Cycle.php
>    Can you confirm that it is available in your installation?
>
> Last option would be to patch a file and see if this would fix your
> problem, but only if point 1. does not work. Probably your server is
> configured in a "funny" way, preventing the autloader from working properly.
> In that case, you have to edit the file index.php in the Kimai folder and
> add one line. Should be line 47.
> Find and change like here
> https://github.com/kimai/kimai/blob/master/index.php#L47:
>
> $view` = new Zend_View();
> $view->setBasePath(WEBROOT . '/templates');
> $view->addHelperPath(WEBROOT . '/libraries/zendframework/zendframework1/library/Zend/View/Helper');
>
> The last line is the new one.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/kimai/kimai/issues/631#issuecomment-200032949>
>



-- 
Jason Pasnikowski
315-333-0039
JasonPasnikowski@sapsaj.com

**Comment by kevinpapst** [comment]
Hi Jason, thanks for your feedback and glad that it works now!
