### ISSUE TITLE
Help Me To Find The On Click Events for Buzzer Buttons.

### ISSUE THREAD

**Issue by ShahadatHossainRafi** [kimai/kimai#632]
http://prnt.sc/aiszvv

#### Expected behaviour
I want to show custom alerts whenever the buzzer buttons will be pressed. What I planned to do is, I will call a function on click of the buzzer button. Then the function will use sweet alert to generate nice looking alert boxes. I want to show some custom alert boxes for my employees. http://prnt.sc/aiszvv

#### Actual behaviour
At this moment buzzer is just starting counting time whenever it/these is/are pressed.

#### Steps to reproduce the behaviour
I just need the HTML code block and specific file name for the buzzer so that I can put on click events within the HTML code block. I can call a function from init.php too but the problem is I cant use sweet alert's .js file in kimai's .js file directly as javascript doesn't support importing modules like Python or Ruby. So I need to know the HTML code block and the HTML file from where I can bridge the sweet alert .js file and kimai .js file.

#### Kimai version
Latest

**Comment by kevinpapst** [comment]
Buzzer: https://github.com/kimai/kimai/blob/master/templates/scripts/core/main.php#L269
Record Again: https://github.com/kimai/kimai/blob/master/extensions/ki_timesheets/templates/scripts/timeSheet.php#L80

**Comment by simonschaufi** [comment]
and here is the javascript code:
https://github.com/kimai/kimai/blob/master/js/main.js
just search for 'buzzer'

**Comment by ShahadatHossainRafi** [comment]
Thanks for the helps. Let me check if that works.
