### ISSUE TITLE
Upgrade to 0.9.3.1387 : not working

### ISSUE THREAD

**Issue by jobart** [kimai/kimai#646]
I had installed a former release candidate 0.9.3 and have just decided to install the stable version.

I copy the file to my server and have done the installation as required. All the lights were green.

I can have an access to Kimai, but nothing happens when I click on the Admin Panel button.

According to the debug, i have the following lines:
_[29.03.2016 13:35:46] E_WARNING in_array() expects parameter 2 to be array, null given @/home/monordi/kimai/extensions/ki_adminpanel/templates/scripts/activities.php line 52 
[29.03.2016 13:35:46] E_NOTICE Undefined index: projects @/home/monordi/kimai/extensions/ki_adminpanel/templates/scripts/activities.php line 52 
_

These lines are repeated at least 20 times.

The line 52 is the following:
	if (in_array($project['projectID'], $activity['projects'])) {

What should I do ? I am a little be lost.

Thank you very much for any help and I apologize for my poor English.

Jo Bart

**Comment by kevinpapst** [comment]
Hi Jo Bart,

please try to replace the mentioned line with this code:
`if (isset($activity['projects']) && in_array($project['projectID'], $activity['projects'])) {`

If that does not work, try
`if (isset($activity['projects']) && is_array($activity['projects']) && in_array($project['projectID'], $activity['projects'])) {`

And please let me know, which one worked.

Regards
Kevin

**Comment by jobart** [comment]
Thank for you prompt reply.

Unfortunately, both do not work.

Now, the previous cited line disappeared on the DEBUG, but I have:
[29.03.2016 14:58:12] KSPI axAction (jobart): refreshSubtab 
[29.03.2016 14:58:12] KSPI axAction (jobart): refreshSubtab 

But nothing appears when I click on the Admin Panel.

Kind regards.

JoBart

**Comment by kevinpapst** [comment]
Did you install new or did you perform upgrade? I assume you did a fresh installation.

Now, the version you mentioned is not(!) stable, it is the latest master version - so you are using a DEV version (which could be potentially instable). But this one is also installed automatically every couple of hours on http://demo.kimai.org - where I cannot verify your problems.

Please try the latest version from today:
https://github.com/kimai/kimai/archive/master.zip

If that gives you the same problems, please check your server logs if you find more suspicious messages. Kimais log file will not catch fatal exceptions, they will be in your servers log file (for Apache somewhere around var/log/apache/error.log or /var/log/httpd/error.log).

**Comment by jobart** [comment]
Hello Kevin,

I installed the file 0.9.3 - 359gd816685 for upgrading. I used FileZilla for transfering the zip file to the server. I understood that it was the way for upgrading.

Further to your recommandations, I download kimai from your link and did the same thing.

Unfortunately, it still does not work.

I did the update procedure:

> Kimai Auto Updater v0.9.3.1387

La base de données a été mise à jour et une copie de sauvegarde a été créée.
Connexion
Database Utility
58 Requêtes exécutées.

Légende
La requête a été exécutée correctement. 	  
La requête a causé une erreur - trècertainement mineure. 	  
La requête a causé une erreur fatale. 	!


Fichier de log de la sauvegarde:
CREATE TABLE kimai_bak_1459262211_championtime_activities LIKE championtime_activities
	  
INSERT INTO kimai_bak_1459262211_championtime_activities SELECT * FROM championtime_activities
	  
CREATE TABLE kimai_bak_1459262211_championtime_configuration LIKE championtime_configuration
	  
INSERT INTO kimai_bak_1459262211_championtime_configuration SELECT * FROM championtime_configuration
	  
CREATE TABLE kimai_bak_1459262211_championtime_customers LIKE championtime_customers
	  
INSERT INTO kimai_bak_1459262211_championtime_customers SELECT * FROM championtime_customers
	  
CREATE TABLE kimai_bak_1459262211_championtime_expenses LIKE championtime_expenses
	  
INSERT INTO kimai_bak_1459262211_championtime_expenses SELECT * FROM championtime_expenses
	  
CREATE TABLE kimai_bak_1459262211_championtime_fixedRates LIKE championtime_fixedRates
	  
INSERT INTO kimai_bak_1459262211_championtime_fixedRates SELECT * FROM championtime_fixedRates
	  
CREATE TABLE kimai_bak_1459262211_championtime_globalRoles LIKE championtime_globalRoles
	  
INSERT INTO kimai_bak_1459262211_championtime_globalRoles SELECT * FROM championtime_globalRoles
	  
CREATE TABLE kimai_bak_1459262211_championtime_groups LIKE championtime_groups
	  
INSERT INTO kimai_bak_1459262211_championtime_groups SELECT * FROM championtime_groups
	  
CREATE TABLE kimai_bak_1459262211_championtime_groups_activities LIKE championtime_groups_activities
	  
INSERT INTO kimai_bak_1459262211_championtime_groups_activities SELECT * FROM championtime_groups_activities
	  
CREATE TABLE kimai_bak_1459262211_championtime_groups_customers LIKE championtime_groups_customers
	  
INSERT INTO kimai_bak_1459262211_championtime_groups_customers SELECT * FROM championtime_groups_customers
	  
CREATE TABLE kimai_bak_1459262211_championtime_groups_projects LIKE championtime_groups_projects
	  
INSERT INTO kimai_bak_1459262211_championtime_groups_projects SELECT * FROM championtime_groups_projects
	  
CREATE TABLE kimai_bak_1459262211_championtime_groups_users LIKE championtime_groups_users
	  
INSERT INTO kimai_bak_1459262211_championtime_groups_users SELECT * FROM championtime_groups_users
	  
CREATE TABLE kimai_bak_1459262211_championtime_membershipRoles LIKE championtime_membershipRoles
	  
INSERT INTO kimai_bak_1459262211_championtime_membershipRoles SELECT * FROM championtime_membershipRoles
	  
CREATE TABLE kimai_bak_1459262211_championtime_preferences LIKE championtime_preferences
	  
INSERT INTO kimai_bak_1459262211_championtime_preferences SELECT * FROM championtime_preferences
	  
CREATE TABLE kimai_bak_1459262211_championtime_projects LIKE championtime_projects
	  
INSERT INTO kimai_bak_1459262211_championtime_projects SELECT * FROM championtime_projects
	  
CREATE TABLE kimai_bak_1459262211_championtime_projects_activities LIKE championtime_projects_activities
	  
INSERT INTO kimai_bak_1459262211_championtime_projects_activities SELECT * FROM championtime_projects_activities
	  
CREATE TABLE kimai_bak_1459262211_championtime_rates LIKE championtime_rates
	  
INSERT INTO kimai_bak_1459262211_championtime_rates SELECT * FROM championtime_rates
	  
CREATE TABLE kimai_bak_1459262211_championtime_statuses LIKE championtime_statuses
	  
INSERT INTO kimai_bak_1459262211_championtime_statuses SELECT * FROM championtime_statuses
	  
CREATE TABLE kimai_bak_1459262211_championtime_timeSheet LIKE championtime_timeSheet
	  
INSERT INTO kimai_bak_1459262211_championtime_timeSheet SELECT * FROM championtime_timeSheet
	  
CREATE TABLE kimai_bak_1459262211_championtime_users LIKE championtime_users
	  
INSERT INTO kimai_bak_1459262211_championtime_users SELECT * FROM championtime_users
	  


Fichier de log de la mise a jour:
ALTER TABLE championtime_customers CHANGE `comment` `comment` TEXT NULL;
	  
ALTER TABLE championtime_customers CHANGE `company` `company` VARCHAR(255) NULL;
	  
ALTER TABLE championtime_customers CHANGE `vat` `vat` VARCHAR(255) NULL;
	  
ALTER TABLE championtime_customers CHANGE `contact` `contact` VARCHAR(255) NULL;
	  
ALTER TABLE championtime_customers CHANGE `street` `street` VARCHAR(255) NULL
	  
ALTER TABLE championtime_customers CHANGE `zipcode` `zipcode` VARCHAR(255) NULL;
	  
ALTER TABLE championtime_customers CHANGE `city` `city` VARCHAR(255) NULL;
	  
ALTER TABLE championtime_customers CHANGE `phone` `phone` VARCHAR(255) NULL;
	  
ALTER TABLE championtime_customers CHANGE `fax` `fax` VARCHAR(255) NULL;
	  
ALTER TABLE championtime_customers CHANGE `mobile` `mobile` VARCHAR(255) NULL;
	  
ALTER TABLE championtime_customers CHANGE `mail` `mail` VARCHAR(255) NULL;
	  
ALTER TABLE championtime_customers CHANGE `homepage` `homepage` VARCHAR(255) NULL;
	  
ALTER TABLE championtime_projects CHANGE `comment` `comment` TEXT NULL;
	  
ALTER TABLE championtime_projects CHANGE `budget` `budget` DECIMAL(10,2) NULL DEFAULT '0.00';
	  
ALTER TABLE championtime_activities CHANGE `comment` `comment` TEXT NULL;
	  
ALTER TABLE championtime_expenses CHANGE `comment` `comment` TEXT NULL;
	  
UPDATE `championtime_configuration` set `value`= 'dd.mm.yy' WHERE `option` = 'date_format_0'
	  
INSERT INTO `championtime_configuration` (`option`,`value`) VALUES('date_format_3','d.m.Y')
	  
UPDATE `championtime_configuration` SET value = '0.9.3' WHERE `option` = 'version';
	  
UPDATE `championtime_configuration` SET value = '1387' WHERE `option` = 'revision';
	  
58 Requêtes exécutées.

> Connexion

All these stuff were OK.


I am a little bit lost.

**Comment by simonschaufi** [comment]
can you open dev console in your browser and see what response you get when after you click on the admin tab? if it is 500, check your server error logs.

**Comment by kevinpapst** [comment]
Thanks to your feedback I found a bug, that only occurs when updating a site without deleting the old files. I'll check for a solution and report back.

**Comment by kevinpapst** [comment]
Okay, a quick fix to your problem @jobart is to delete the directory libraries/Zend/
And we have to find a solution that works through the updater.

**Comment by simonschaufi** [comment]
kevin, is it because Zend is in 2 different folders available?

**Comment by kevinpapst** [comment]
Yes. Its because of this line:
https://github.com/kimai/kimai/blob/master/composer.json#L36
leading to this autoloader include-path line:
https://github.com/kimai/kimai/blob/master/libraries/composer/include_paths.php#L9

Removing the former and calling "composer dump-autoload" afterwards seems to fix the problem, but I need to test if other components are influenced by the missing path. I'll send a PR soon, that includes the patched activities.php.

**Comment by simonschaufi** [comment]
in general we should explain how to update kimai. delete all stuff except the includes/autoconf.php file and then overwrite the installation with the new files.

**Comment by kevinpapst** [comment]
Yes, true. If you want, sent in a PR for https://github.com/kimai/documentation/blob/master/installation/updates.md

**Comment by simonschaufi** [comment]
not just documentation. it should be in readme as well in this project, or what do you think?

**Comment by kevinpapst** [comment]
Wherever it might be useful. But having it in the official documentation is crucial in the first place.
But lets discuss this in another thread or in chat, lets not hijack this thread ;-)

**Comment by jobart** [comment]
Yes, you were right. It was a 500 error.

As instructed, I deleted the Zend folder and... it WORKS !!!

Thank you very much. I really appreciate your support.

Just for information, when I click on Budget, my computer is freezing. Mozilla offers to stop the script.

Kind regards

**Comment by kevinpapst** [comment]
Glad we could fix the first problem (and thanks for reporting!). 

The budget extension is quite heavy, when working woth a lot of projects and tasks. 
If you do not stop it, is there ever something rendered?
How many projects and task combinations (that have tracked time) do you use?

**Comment by jobart** [comment]
Nearly 300 projects for 30 different tasks. Your explanation is consistent. Perhaps, a way for disactiving partially the budget extension could be appreciated by users.

For my part, I do not use the budget extension, so it does not matter.

Besides, on the invoice extension, the 2016 odt export looks very good. But I wonder if there is a easy way to obtain a pdf file instead of an odt file ? I understand from the documentation that a pdf file can be obtained by encoding in php, but it is too complex for me.

**Comment by simonschaufi** [comment]
> Besides, on the invoice extension, the 2016 odt export looks very good. But I wonder if there is a easy way to obtain a pdf file instead of an odt file ? I understand from the documentation that a pdf file can be obtained by encoding in php, but it is too complex for me.

Thank, you, that odt file is from me and i created it for my own customers. This file is actually in productive use ;) The way how i do it is to open the file in openoffice and then export it directly as pdf as openoffice has a direct pdf print option. you are right, coding a php script to create a pdf is quite complex...

**Comment by jobart** [comment]
For the export to a pdf file, I do exactly the same thing by OpenOffice. Unfortunately, when I open the odt file with Word, it does not really work. I have been bound to install OpenOffice.

I was very happy to see that you suceed to have a common format for the date on your odt, because I failed... I always had a US date.

**Comment by simonschaufi** [comment]
word 2007 also supports odt files, or?

> I will use your 2016 odt and translate it in French.

if you want to, you can share it with us. make a pull request here: https://github.com/kimai/invoice-templates

**Comment by kevinpapst** [comment]
@jobart If you want to get rid of the budget extension, I believe you are safe to rename "/extensions/ki_budget" to "/extensions/#ki_budget" - which should hide it from the UI.

If you want PDF export for invoices, fill it as new issue (feature request) here in the tracker.
I believe its a good idea for Kimai.

Could you please open another issue for the budget extension (even if you don't use it)? 
You are likely not the only person using a lot of tasks and projects and we should address that issue (I just don't like to mix several issues into one thread here). I already did some optimizations for the upcoming release, but your numbers require a complete new way of thinking/rendering the budgets.

**Comment by simonschaufi** [comment]
@kevinpapst pdf rendering of invoice templates [exist](https://github.com/kimai/kimai/blob/master/libraries/Kimai/Invoice/HtmlToPdfRenderer.php) already but im not sure if this really works as i have never tried it out due to complexity

**Comment by kevinpapst** [comment]
@simonschaufi I am pretty sure, this is not production ready, otherwise I would have added a working template for it ;-)
