### ISSUE TITLE
Kiami Installation

### ISSUE THREAD

**Issue by BDub-Hay** [kimai/kimai#649]
Hello, I attempted to install Kiami on my digital ocean droplet. i got to the "Database Server" part of installation and now I am stumped.  it is asking me for a host, a username, and a password.  I am unsure of the database Kiami is using.  I thought it might be mysql but when i type mysql -u root into a command line it tells me mysql isn't installed. 
What database is Kiami using?  For future how would one figure that information out?
What would i enter for the host, would it be the domain name of the server or is the host referring to the name the database kiami will be using? 
Also, are there any tutorials out there to setup https for Kiami.  I've done it for my owncloud setup but I don't know if the steps are the same.  Thanks for the help

Brian.

**Comment by BDub-Hay** [comment]
Update:
I insalled mysql 5.5 server.  I went back to the kiami installation webpage and entered the mysql root user and password as the database credentials.  Is that a good idea?  Should i have created a kiami user, granted it the necessary permissions and then used it as the user?  I am a little light on my database experience so please be patient with my obvious questions.  Thanks again.

Brian.

**Comment by simonschaufi** [comment]
Yes, kimai requires mysql. mariadb should also work. we are currently working on a more clear installation requirements documentation.
Generally, it is always good to only give the permissions needed and never root access. If someone breaks into the system and has root access, he has full access to all databases.

**Comment by kevinpapst** [comment]
Hey @BDub-Hay - I have no clue what a "digital ocean droplet" is. Normally you have a Webserver and Database up and running. Then you could do something like:
```
CREATE USER 'kimai'@'localhost' IDENTIFIED BY  '***';
GRANT USAGE ON * . * TO  'kimai'@'localhost' IDENTIFIED BY  'password' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
CREATE DATABASE IF NOT EXISTS  `kimai` ;
```
And then use "kimai" and "password" for the installer. Is that information sufficient for you to go on?

**Comment by simonschaufi** [comment]
@kevinpapst https://www.digitalocean.com its a cloud hosting company

**Comment by BDub-Hay** [comment]
> `CREATE USER 'kimai'@'localhost' IDENTIFIED BY  '***';
GRANT USAGE ON * . * TO  'kimai'@'localhost' IDENTIFIED BY  'password' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
CREATE DATABASE IF NOT EXISTS  `kimai` ;`

Perfect, First I tried to create a user kiamiadmin, then i created a kiami database, then I tried to grant certain privileges as specified by a document I found on the github page, but i needed to create tables under the datatbase before i could grant user kiamiadmin privileges.  granting usage to the kiami user first then letting kiami make the tables under the database makes sense.  Thanks for the help.

**Comment by BDub-Hay** [comment]
anybody know of a good step by step guide for configuring https?

**Comment by kevinpapst** [comment]
That really depends on your webserver & environment. But I believe there are thousands of tutorials out there ;-)

I have even written one myself, but its in german (and for apache): 
http://www.keleo.de/blog/Apache-Virtual-Host-mit-SSL-einrichten.html

**Comment by BDub-Hay** [comment]
so apparently Kiami is not the project name.  Sorry Simon. 

What does Kimai use as the webserver?  I thought it was apache.  I configured https on my owncloud server and that used apache so i thought i would refer back to those guides.

**Comment by simonschaufi** [comment]
yes, it's kimai ;)
apache is default but nginx for example should also work.

**Comment by BDub-Hay** [comment]
I deleted my first attempt at Kimai and started over.  I created a kimai mysql user as explained above and created my kimai database.  When i get to the database server section i enter my kimai database username and password, click proceed then the installer tells me that i dont have permission to list databases.  I enter the name of my kimai database then the installer tells me its unable to open that database.  Looking at the INSTALL.md file in git, it directs us to grant different privileges to the kimai user.  After i did that, i finished the installation and everything is working properly now.  Hopefully this helps somebody in the future.

**Comment by simonschaufi** [comment]
your "problem" has nothing to do with kimai. It's a general db setup issue...

**Comment by kevinpapst** [comment]
Hey @BDub-Hay - thanks for the explanation and feedback!

@simonschaufi Probably you did not read "everything is working properly now" and "Hopefully this helps somebody in the future"?

**Comment by BDub-Hay** [comment]
No, Thank you @kevinpapst, it was your post that helped me reach the point of a working Kimai install.  I apologize for not thanking you in my first comment of the day, but thank you, i appreciate all help and feedback.
