### ISSUE TITLE
Installation on Windows Server - PHP trouble

### ISSUE THREAD

**Issue by Guenny0488** [kimai/kimai#650]
Hi,
i try to Setup Kimai on a Windows Server 2012 R2 machine.

I have an MySQL 5.7 Community Server
IIS 8.5 and PHP 7.0.4 installed

I get the error on the third Screen on the installer: 

**The MySQL extension for PHP has to be loaded.
For PDO the extensions pdo and pdo_mysql are required**

Within PHP.ini the extension=php_pdo_mysql.dll is activated and the extension_dir Options are as follows:

; Directory in which the loadable extensions (modules) reside.
; http://php.net/extension-dir
; extension_dir = "./ext"
; On windows:
 extension_dir = "ext"

I am not sure what I can do or what I have to Change.

![installation_kimai_error](https://cloud.githubusercontent.com/assets/18172313/14149901/b6157706-f6a6-11e5-95f2-20bf96c45aa9.PNG)

**Comment by simonschaufi** [comment]
Hi, is this the latest git version or the latest zip version from the website?
Please try activating mysqli extension as well.

**Comment by kevinpapst** [comment]
@simonschaufi check the header, it says "v0.9.2.1306"

@Guenny0488 Where did you even find such an old version? Sourceforge?
Please try to install this version: https://github.com/kimai/kimai/archive/master.zip

And as simonschaufi pointed out, make sure you have mysqli loaded.

**Comment by simonschaufi** [comment]
oh yeah, thats like stone age version :)

**Comment by Guenny0488** [comment]
Oh - this is an old version? 
I have loaded them from the Prodct Homepage. 
I will start again with the latest master from Github. 

How can I check if mysqli is loaded?

**Comment by simonschaufi** [comment]
Where exactly? I only found the link to version 0.9.3
you can use phpinfo() for that.

**Comment by Guenny0488** [comment]
ah - you are right. It was loaded from SourForge

My PHPinfo shows that regarding mysqlli.
![mysqlli](https://cloud.githubusercontent.com/assets/18172313/14157075/c8ec35d6-f6c9-11e5-9a18-1d444c94a499.PNG)

**Comment by kevinpapst** [comment]
Looks like Sourceforge (I did some updates on the page yesterday, so it might have been featured somewhere on the page): https://sourceforge.net/projects/kimai/
I will upload the latest version to Sourceforge as well.

The installer will tell you if something is missing, but the screenshot looks good. Give it a try!

**Comment by Guenny0488** [comment]
now it works
Thanks for your support
