### ISSUE TITLE
Exporting odt invoice to pdf format

### ISSUE THREAD

**Issue by jobart** [kimai/kimai#665]
I believe that it would be a great improvement if the invoice extension allow from an odt file to have immediatly a pdf file.

Indeed, currently, I can not use MS Word for kimai odt files as there are slight changes due to compatibility issue. I use OpenOffice and then I print with a virtual pdf printer the odt invoice.

This is not really convenient when you are editing several invoices.

Kind regards.

JoBart

**Comment by simonschaufi** [comment]
Won't fix because there is no odt->pdf conversion possible. The only way is to install openoffice on the server and use command line to render the pdf, otherwise there is no way. I did a lot of research about this already because i also need it.

**Comment by kevinpapst** [comment]
Hey @jobart - you could still add a Feature Request for printing PDF invoices. That might not be possible for ODT to PDF, but probably through HTML or even an PDF template directly.

**Comment by Gulliverkli** [comment]
@kevinpapst How can i export a HTML invoice to a pdf file?
Why did you lock the community forum? I think github is not a good choice to communicate with/for the community!

**Comment by MisterChoc** [comment]
yes, please - we need a solution!

**Comment by kevinpapst** [comment]
Use a PDF printer,  works on all OS.
Otherwise open a Feature request for a direct PDF invoice export.
