### ISSUE TITLE
Search in comments

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#67]
Forum post: http://forum.kimai.org/index.php?topic=1846.0

The idea is to implement a search function which allows searching through comments (and maybe more fields).

**Comment by klemensz** [comment]
+1
Example: You are working on different issues/tasks, and write the issue # in the description field. Then you want to know how many hours you needed for one issue. Or is there another way to do this that I'm not aware of?

**Comment by joejoe31b** [comment]
+1
For anyone with a large amount of timesheet entries, this is essential. 

Having a generic search box that searches multiple fields, or being able to run Gmail-style queries like `time:0:25-0:45` or `tracking-number:12563` would be even better as it gives more flexibility.

**Comment by simonschaufi** [comment]
Kimai is open source so everyone can improve the code and make a pull request. Even if you are not a developer, you can still support the project by enabling others to code some features.

**Comment by kevinpapst** [comment]
Archiving old issues. [Please switch to Kimai 2](https://github.com/kevinpapst/kimai2)...
