### ISSUE TITLE
Time Lock Option

### ISSUE THREAD

**Issue by sudirmedi** [kimai/kimai#675]
Hi All, Good Day
I am using kimai from long back for my small business its a great time tracking system. Now the issues is i want a option like time edit lock i found it in new update but already i am using old version and i modified and enhanced so many things in old version. How can i update my kimai with losing my changes or is there any chance to add this lock option to my old version. please help me

**Comment by simonschaufi** [comment]
Hi, if you have modified kimai with git commits, it will be relatively easy to update as you can apply your changes again. There are different ways of doing this. The main problem is that we moved all files one folder up and that alone will make it a nightmare but generally speaking you can do different things:

1. make a patch and apply it after updating
2. git rebase (use IDEs if possible) and do manual merge conflicts
3. make all changes by hand

does that help?
