### ISSUE TITLE
How to Install Software

### ISSUE THREAD

**Issue by mg827** [kimai/kimai#676]
Our small company ran the demo software for Kimai and thought it was the perfect fit for our needs and were very excited to start using it. However, none of us are programmers, and we cannot understand how the process to install works. There seem to be multiple ways of installing listed across different forums. We have tried to follow the listed steps multiple times, but can't get further than the part of extracting the file to the htdocs because nothing works as is stated from there. The demo was so easy too, just click - download - use. Is there an installation guide for non-programmers? Any help would be appreciated. We are running Windows PCs and were planning to install to our server, but can't even get it installed on a PC in order to try it out for a bit (after installing the XXAMP and enabling the modules). Thanks in advance for the dumbed-down advice we need.

**Comment by simonschaufi** [comment]
Hello and thanx for using kimai!
Here is the official documentation: http://www.kimai.org/documentation/installation/index.html
Please write us, what is not clear, then we will improvie it.
If you use xampp, you probably have to copy the files to c:\xampp\htdocs\kimai and then access it using http://localhost/kimai/
