### ISSUE TITLE
How can I allow editing of Description in the TimeSheet while disallowing time editing?

### ISSUE THREAD

**Issue by dritchie-mtc** [kimai/kimai#679]
#### Expected behaviour

Log as user, start a timed job. End timed job and edit the description of the job without being able to change the actual time on the job.
#### Actual behaviour

Allowing editing of job, allows changing of the time the job took.
#### Kimai version

0.9.3.1384

[![bountysource](https://api.bountysource.com/badge/issue?issue_id=33166414)](https://www.bountysource.com/issues/33166414)

**Comment by simonschaufi** [comment]
Sorry, we don't have such a fine granular permission setting (yet). In our opinion time editing should always be enabled since mistakes happen and the user should be able to fix them by himself, otherwise you have a trust problem in your staff and you should work on that ;)

**Comment by dritchie-mtc** [comment]
When you say "sponsor such a feature", what are you referring to?

**Comment by kevinpapst** [comment]
We could use the "quick edit button" for that feature. That button opens a screen where you can currently only enter a comment (not description). 

So the feature request would be:
- a new permission for enabling/disabling the quick edit function for user groups
- make the description editable in quick edit floater

I guess that should be enough to fulfill your request.

And even though @simonschaufi might be right with his trust comment ;-) I know that a lot of companies have such requirements and thats why we have the feature to deactivate editing after a certain time amount.

**Comment by dritchie-mtc** [comment]
Where is the "quick edit button"? I am not seeing it. Does it have to be turned on somewhere?

**Comment by kevinpapst** [comment]
Yes, user preferences, third tab, last checkbox.

**Comment by simonschaufi** [comment]
right now we don't have a good platform to sponsoring features but you are always welcome to do that personally via http://www.kimai.org/donate/ (Kevin and I are the ones to go for)

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
