### ISSUE TITLE
Ok button in edit frame not responding

### ISSUE THREAD

**Issue by kimaiuser** [kimai/kimai#694]
#### Expected behaviour
Pressing Ok closes Edit Frame and saves changes
#### Actual behaviour
nothing
#### Steps to reproduce the behaviour
click "+" above entries or pencil (edit) at one entry
then try to click ok.
#### Kimai version
0.9.3 stable
#### Relevant log entries from Kimais Debug tab
E_NOTICE Undefined index: fixedRate @/extensions/ki_timesheets/processor.php line 451
iconv_set_encoding(): Use of iconv.internal_encoding is deprecated @/libraries/Zend/Locale/Format.php line 782
Uncaught exception: Could not determine temp directory, please specify a cache_dir manually

**Comment by kevinpapst** [comment]
Thanks for your report. That problem was fixed already fixed. 
You could test our latest version from here: https://github.com/kimai/kimai/archive/master.zip
