### ISSUE TITLE
All projects and activities disappeared time is still right

### ISSUE THREAD

**Issue by jv-barsuk** [kimai/kimai#696]
There are no projects and no activities (big list) shown anymore in my kimai installation. The time at the top is right and also changes when I change the date. The users and customers are shown, sometimes also the tasks (right bottom). 

Yesterday I changed the visibility of some projects that are already finished. I forgot to stop the time tracking before I stopped working. Today I logged in and there were no records and also no projects anymore.

I reinstalled kimai because at some point whilst I was changing the settings, my autoconf.php file got cleared. The DB was kept (Edit: all entries seem to be correctly in the DB).

v0.9.3.1384

(the tab with the debug information is also not there anymore, but this happened after reinstalling)

**Comment by kevinpapst** [comment]
Doesn't sound good, but without more information no help possible.
What did you do? Upgrade from which version to v0.9.3.1384?
How did you upgrade/reinstall?
What do you mean by "config got cleared"?

**Comment by jv-barsuk** [comment]
easy solution: there was no space left on the server :-)
