### ISSUE TITLE
Einträge lassen sich nicht ändern... und Kommentare... lassen sich auch nicht hinzufügen 

### ISSUE THREAD

**Issue by cryptoxyz** [kimai/kimai#697]
Kimai version 0.9.3.1384

wenn ich Eintragungen editieren will lassen sie sich nur löschen alles andre funktioniert nicht, beim klick auf ok passiert nichts. Ich habe mehrere Browser ausprobiert!
 
[logfile.txt](https://github.com/kimai/kimai/files/244230/logfile.txt)

**Comment by kevinpapst** [comment]
Probier mal bitte ein Upgrade auf die aktuelle Entwicklerversion aus: 
https://github.com/kimai/kimai/archive/master.zip

**Comment by kevinpapst** [comment]
Ich glaube das war ein Fehler in der DB, man kann nur speichern wenn eine Rate eingetragen ist. 
Auf jedenfall ist das Problem bereits gefixt in der neuesten Version
