### ISSUE TITLE
Installer fails to recognise MySQL PHP extension as being enabled

### ISSUE THREAD

**Issue by VBScab** [kimai/kimai#698]
Environment is Windows 7 Enterprise SP1, IIS 7, PHP 7, MySQL 5.7

#### Expected behaviour
Installer proceeds to database creation

#### Actual behaviour
Fails to recognise that the extension is enabled

#### Steps to reproduce the behaviour
Run the installer

#### Kimai version
0.9.3.1384

#### Fix:
In 'Installer\processor.php' change line 78 from :
       `if (!extension_loaded('mysql')) {`
to
       `if (!extension_loaded('mysqli')) {`

**Comment by kevinpapst** [comment]
Hey, that one is already fixed: https://github.com/kimai/kimai/blob/master/installer/processor.php#L82

But thanks for reporting and supporting :-)
