### ISSUE TITLE
Adding a user that already exists - empty error message

### ISSUE THREAD

**Issue by VBScab** [kimai/kimai#701]
#### Expected behaviour
To be able to add a user with a blank email address

#### Actual behaviour
'Edit User 'screen prompts "Password not set" and a yellow exclamation triangle appears for that user's 'Status' in the summary screen

#### Steps to reproduce the behaviour
Add a user with no email address set

#### Kimai version
0.9.3.1387

I expect to be able to add users with no email address. I also expect that the option to 'Email this user' to be greyed-out if there's no valid email address but, of course, I haven't been able to test that :-)

**Comment by VBScab** [comment]
I have set up some users and, when I log in as a user who's part of the Admins group, the password is showing as not set, even though I set it and it appears in the database. I log off, log in as Admin, set the password again, log back in as that user and it's still showing as not set.

**Comment by VBScab** [comment]
Dear God...

I do a 'Show deleted users'. The invisible user isn't in that list. I do a 'Hide deleted users' and lo! The invisible user is back!

TBH, this getting a bit tiresome. Perhaps I'll come back when v1.1 is released. I'll sleep on it.

**Comment by kevinpapst** [comment]
Maybe we have a different Kimai, but when I add a user it has no email and no password by default.

If you close the dialog, that appears directly after hitting the "add user" button, then you will see a exclamation mark - which is correct as Kimai tells you that this user won't be able to login.
The dialog itself also shows the "user has not password set" message, which is still correct.

Once you entered a password and saved the user, this message will disappear. 
Yes, the password will not show up in the dialog again after reopening it, as that would be a huge safety problem. It won't show, neither for Admins nor for the user itself. 
But do you see the error message "no password set"? I don't after giving the user a password once.

Btw, thats default behaviour with most software I use, except for password managers maybe ;-)

No user has an email by default and that is fine for Kimai, it will work fine without an email. The "email this user" icon is then deactivated as well. I cannot reproduce what you say. Maybe Kimai does not work as you want it to do, but sorry, I do not see any faulty behaviour here.

Yes you are right, there seems to be a missing translation if I try to create a user that already exists, thanks for pointing that one out.

Also, the invisible user is not reproducable for me. If you have more information about how to reproduce that, I would be glad to look into it!

**Comment by VBScab** [comment]
>different Kimai
The version I'm using is shown in the top post and was the one recommended to me to use, following the other issues I'd been having with the 'mysqli' extension.

To be blunt, I've given up on Kimai. The straw that broke the camel's back was the way that screens aren't refreshed properly. That is to say, I'd be looking at a list of users, go into a record to edit and, on returning to the screen, many of the users wouldn't be listed any longer. I'd have to bring up another list (say, 'Groups') and then return to the list of users.

As I mentioned eklsewhere, I may come back when I see v1.1 released. Good effort, anyway. Almost there.
