### ISSUE TITLE
DOMDocument not found after fresh install of kimai-master.

### ISSUE THREAD

**Issue by hpeyerl** [kimai/kimai#706]
I built a lamp server on Ubuntu 16.04 and downloaded kimai-master (clicked the 0.9.4 link) and proceeded through the install.  After the install was done, I tried to add a timesheet on the test-company and test-project but see these errors on the Debug tab:

[14.05.2016 06:55:17] Uncaught exception: Class 'DOMDocument' not found 
[14.05.2016 06:55:17] KSPI axAction (admin): add_edit_timeSheetEntry 
[14.05.2016 06:55:15] Uncaught exception: Class 'DOMDocument' not found 
[14.05.2016 06:55:15] KSPI axAction (admin): add_edit_timeSheetEntry 
[14.05.2016 06:54:31] Uncaught exception: Class 'DOMDocument' not found 
[14.05.2016 06:54:31] KSPI axAction (admin): add_edit_timeSheetEntry 

I checked 'php -i' and I have 

DOM/XML => enabled
DOM/XML API Version => 20031129

as well:

root@kimai:/var/www/html/kimai# more /etc/php/7.0/cli/conf.d/20-dom.ini
; configuration for php xml module
; priority=20
extension=dom.so

My overall goal here is to evaluate Kimai as a replacement for Billings.

**Comment by simonschaufi** [comment]
php7 should ship [DOMDocument](http://php.net/DOMDocument) out of the box. I use XAMPP with win7 and there it works. I don't see why it does not work on your machine.

You can try it with this snippet:
```php
<?php
if (class_exists('DOMDocument')) {
	echo "class DOMDocument exists.";
} else {
	echo "ERROR: class DOMDocument does not exist";
}
```

**Comment by kevinpapst** [comment]
We should add the check to the installer, therefor I will re-open the issue (sorry simon!)

**Comment by kevinpapst** [comment]
I created a PR that checks for existence of DOMDOcument during installation.

@hpeyerl you displayed the config for the PHP command line client, not the config for the apache module or php-fpm. You should have two configs. Please test it with a PHP script <?php phpinfo(); ?> with your browser.

**Comment by hpeyerl** [comment]
Thanks for fixing this.  I don't have the VM with Kimai anymore so I can't test.  (my time tracking requirements changed so I went a different way).
