### ISSUE TITLE
Empty timesheet after date now or start stopwatch

### ISSUE THREAD

**Issue by HenryNe** [kimai/kimai#708]
#### Expected behaviour

Click on "now" in calender icon between current date and time should view entries from current day.
#### Actual behaviour

A click on calender icon or start the stopwatch makes the filter date to my local day.
All entries in timesheet are hidden.
#### Steps to reproduce the behaviour
- fresh login as admin in last hour before midnight (23:00 ... 23:59, I think)
- Filter date is displayed as "17.05.2016 - 18.05.2016"
- Have some entries before midnight, maybe create some, for example
  - 17.05.  21:13 - 21:14
  - 17.05.  21:04 - 21:05
- Click to the calendar icon near current date, or click stopwatch start
- The filter date was changed to "17.05.2016 - 17.05.2016" - that is ok, this is today
- The Timesheet was complete cleared and will display "no Entries" now.

To see entries again, needs to change end date from 17.05.2015 (today) to 18.05.2016 (tomorrow), for example "17.05.2016 - 18.05.2016".
#### Setings
- Current local time is 23:15 2016-05-17 CEST
- Current Server time: 21:15 2016-05-17 (found in debug log)
- local timezone: Europe/Berlin
- defaultTimezone: Europe/Berlin
#### Kimai version

0.9.3-1387 (demo server)
#### Relevant log entries from Kimais Debug tab

[17.05.2016 21:16:38] KSPI axAction (admin): reload_timeSheet 
[17.05.2016 21:16:38] KSPI axAction (admin): setTimeframe

**Comment by kevinpapst** [comment]
Confirmed, the calculation of start and end is wrong:
https://github.com/kimai/kimai/blob/master/extensions/ki_timesheets/js/ts_func.js#L208
Both calculate the timestamp, without taking into account that the end date should be 23:59:59.

Could you replace the function with this code:
```
function ts_ext_reload() {
	var lastDay = new Date($('#pick_out').val());
	lastDay.setHours(10);
	lastDay.setMinutes(59);
	lastDay.setSeconds(59);

	$.post(ts_ext_path + "processor.php", {
		axAction: "reload_timeSheet",
		axValue: filterUsers.join(":") + '|' + filterCustomers.join(":") + '|' + filterProjects.join(":") + '|' + filterActivities.join(":"),
		id: 0,
		first_day: new Date($('#pick_in').val()).getTime() / 1000,
		last_day: lastDay.getTime() / 1000
	}, function(data) {
		$("#timeSheet").html(data);

		ts_ext_set_TableWidths();
		ts_ext_applyHoverIntent();
	});
}
```
and let me know if that works better and/or breaks anything else?

**Comment by HenryNe** [comment]
Maybe your changes fixes the problem for click on "now". I can not test it, because I have no lable "now" in my kimai 0.9.3, and a newe version dows not run on my server (PHP to old).

Your changes does not solve the problem, the "no Entries" after click on stopwatch.

The problem exist, if server timezone and local timezone are on different days. If you are testing in the late afternoon, you should use a positive timezone (UTC+12:00). If you are testing in the evening, try it with a negative timezone (UTC-12:00). Here is an other example:

* I changed my local time to an extreme different timezone to the server, for example UTC -10:00 Hawaii.
* Local time is **16.08.2016 20:00** Hawaii
* Login as user on demo.kimai.org, v1.0.1.1388
* The display views 16.08.2016 - 16.08.2016. That is OK for my local timezone
* Server date is 17.08.2016 08:00, found in debug log. It is CEST -2:00 Europe/Berlin
* Now 2x click on stopwatch to create a new entry
* No time entries are added (displayed) in timesheet, the message is now "**no Entries**"
* Logout and login does not help to displaying the missed entries. The date on "pick_out" will not change on Logout/Login.
* Click on the "pick_out" and change it from 16.08.2016 to 17.08.2016
* The entry from above is shown: **17.8. | 08:00 | 08:00** - For my current timezone, this is bad.

Steps continue. It is reproduceble again
* 2x click on stopwatch
* The timesheet says "no Entries"

Sorry, that this issure describes multiple problems. I feel, the main problem is, that the local timezone is not strictly used for communicate with the user.

I would says, the problem is, that the time entries in timesheet are displayed/recorded with server timezone.

**Comment by simonschaufi** [comment]
This is related to the fact that we store the time entries based on server time zone. The question is: You work in Hawaii and the next day you work in Germany. How should the time from Hawaii be displayed? I don't know how other time tracking systems "solve" that issue.

**Comment by HenryNe** [comment]
No, no. For testing I have changed my timezone before start the test. I have changed it to some extreme timezone, so you can reproduce it in a bigger time range of day. Along the test, the timezone was not changed. - Like a user who is living outside of servers timezone.

On my steps at 2016-05-17 the servers time was differ 2 hours from my localtime. I have not changed my timezone. I was simply using the stopwatch. The problem was only seen near midnight in this case.

In this issue it is not the question of changing timezone, for example between logins. This is also a Problem, and would be solve by storing timestamps in UTC on server and use local timzone for viewing.

**Comment by HenryNe** [comment]
@kevinpapst wrote

> Both calculate the timestamp, without taking into account that the end date should be 23:59:59.
> `lastDay.setHours(10);`

Why you used 10 o'clock and not 23 in code?

**Comment by kevinpapst** [comment]
Accidentaly ;-) Was playing around and copy&pasted the "wrong" version.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
