### ISSUE TITLE
Editing entries throws: "fixedRate can not be null": Activity Fixed Rate cannot be blank or 0.

### ISSUE THREAD

**Issue by TrevorBradleyCDN** [kimai/kimai#709]
#### Expected behaviour

Click on green pen icon, change project.  Click on Advanced tab, leave comment.  Click Green OK button.  Changes should be saved.
#### Actual behaviour

I moved my Kimai server to my new Ubuntu 16.04LTS server to consolidate my websites in one place, and upgraded from 0.9.3 master to the git/dev version so it would run.  Things appeared to work perfectly for a few days.  On day 3, I'm unable to save changes to Project or Comment.  There's no error in the logs, the changes simply don't take.
#### Steps to reproduce the behaviour

Unknown.  I'm assuming it's specific to my database.  Upgrading from an existing 0.9.3 database?
#### Kimai version

0.9.3-403-g75814ae (Most recent github checkout as of 2016-05-27
#### Relevant log entries from Kimais Debug tab

This looks interesting... 

[27.05.2016 11:13:30] KSPI axAction (Trevor): reload_timeSheet
[27.05.2016 11:13:30] timeEntry_edit: Column 'fixedRate' cannot be null (#1048)
[27.05.2016 11:13:30] timeEntry_edit: 2403
[27.05.2016 11:13:30] KSPI axAction (Trevor): add_edit_timeSheetEntry
[27.05.2016 11:13:29] KSPI axAction (Trevor): budgets
[27.05.2016 11:13:29] KSPI axAction (Trevor): bestFittingRates
[27.05.2016 11:13:29] KSPI axAction (Trevor): reload_activities_options 
### Wherein the user has an "aha!" moment.

If I make two modifications, the error _sometimes_ goes away and allows me to save:

1) Admin Panel > Projects

If I edit each project, select the budget tab and put in a value into "Fixed Rate" (previously blank)

2) On the Timesheet, if I _fiddle_ with the Fixed Rate on the Budget tab, I can get it to work, but not consistently.

I'm guessing this is a Database upgrade issue of some kind.

**Comment by kevinpapst** [comment]
Yes, that is fixed in the newest version, but I have no clue why it still appears for you.
Did the upgrade process kick in when you upgraded the files?

If you have the experience, could you please check if the lines below the linked line were applied to our database: https://github.com/kimai/kimai/blob/master/updater/updater.php#L1086

Is your database revision 1387?

**Comment by TrevorBradleyCDN** [comment]
OK, let's have a look at this.  

The Kimai database has a backup with a unix timestamp of 1464199290... 2 days ago.

mysql> select * from kimai_configuration where kimai_configuration.option = "revision";

Reports the revision is 1387.  Previous revision...

select * from kimai_bak_1464199290_kimai_var where var="revision";

Reports 1306.

And the table names have obviously changed. kimai_var => kimai_configuration, for example.

As for the changes... yes, it looks like they were made:  (Hoping this looks better after I save the comment)
```
mysql> describe kimai_customers;
+-------------------+--------------+------+-----+---------+----------------+
| Field             | Type         | Null | Key | Default | Extra          |
+-------------------+--------------+------+-----+---------+----------------+
| customerID        | int(10)      | NO   | PRI | NULL    | auto_increment |
| name              | varchar(255) | NO   |     | NULL    |                |
| password          | varchar(255) | YES  |     | NULL    |                |
| passwordResetHash | char(32)     | YES  |     | NULL    |                |
| secure            | varchar(60)  | NO   |     | 0       |                |
| comment           | text         | YES  |     | NULL    |                |
| visible           | tinyint(1)   | NO   |     | 1       |                |
| filter            | tinyint(1)   | NO   |     | 0       |                |
| company           | varchar(255) | YES  |     | NULL    |                |
| street            | varchar(255) | YES  |     | NULL    |                |
| zipcode           | varchar(255) | YES  |     | NULL    |                |
| city              | varchar(255) | YES  |     | NULL    |                |
| phone             | varchar(255) | YES  |     | NULL    |                |
| fax               | varchar(255) | YES  |     | NULL    |                |
| mobile            | varchar(255) | YES  |     | NULL    |                |
| mail              | varchar(255) | YES  |     | NULL    |                |
| homepage          | varchar(255) | YES  |     | NULL    |                |
| trash             | tinyint(1)   | NO   |     | 0       |                |
| vat               | varchar(255) | YES  |     | NULL    |                |
| contact           | varchar(255) | YES  |     | NULL    |                |
| timezone          | varchar(255) | NO   |     | NULL    |                |
+-------------------+--------------+------+-----+---------+----------------+
21 rows in set (0.00 sec)

mysql> describe kimai_projects;
+------------+---------------+------+-----+---------+----------------+
| Field      | Type          | Null | Key | Default | Extra          |
+------------+---------------+------+-----+---------+----------------+
| projectID  | int(10)       | NO   | PRI | NULL    | auto_increment |
| customerID | int(3)        | NO   | MUL | NULL    |                |
| name       | varchar(255)  | NO   |     | NULL    |                |
| comment    | text          | YES  |     | NULL    |                |
| visible    | tinyint(1)    | NO   |     | 1       |                |
| filter     | tinyint(1)    | NO   |     | 0       |                |
| trash      | tinyint(1)    | NO   |     | 0       |                |
| budget     | decimal(10,2) | YES  |     | 0.00    |                |
| effort     | decimal(10,2) | YES  |     | NULL    |                |
| approved   | decimal(10,2) | YES  |     | NULL    |                |
| internal   | tinyint(1)    | NO   |     | 0       |                |
+------------+---------------+------+-----+---------+----------------+
11 rows in set (0.00 sec)

mysql> describe kimai_activities;
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| activityID | int(10)      | NO   | PRI | NULL    | auto_increment |
| name       | varchar(255) | NO   |     | NULL    |                |
| comment    | text         | YES  |     | NULL    |                |
| visible    | tinyint(1)   | NO   |     | 1       |                |
| filter     | tinyint(1)   | NO   |     | 0       |                |
| trash      | tinyint(1)   | NO   |     | 0       |                |
+------------+--------------+------+-----+---------+----------------+
6 rows in set (0.00 sec)

```

**Comment by TrevorBradleyCDN** [comment]
Looking at updater.php, the script likely created a fixed_rates table from my revision 1306 database, later renamed to a fixedRates table, which had no entries in it whatsoever.  I have five entries in mine now, likely because I tried to repair it manually. ....

Looking at the kimai_fixedRates table.... waiiiit a second.

I noticed the structure of the table was as follows:
```

mysql> select * from kimai_fixedRates;
+-----------+------------+-------+
| projectID | activityID | rate  |
+-----------+------------+-------+
|        20 |       NULL |  0.00 |
|        21 |       NULL |  0.00 |
|         2 |       NULL |  0.00 |
|        16 |       NULL |  0.00 |
|        25 |       NULL |  0.00 |
+-----------+------------+-------+

```

Now those 5 rows were there after I tried to put in fixed rates... but I also noticed that Activity ID was null... I tried editing and saving my activityID and it added a row to this table, but then my lone activity ("Coding) got mangled.  I added in a new activity, and now everything appears to be working fine again.

Is it possible something's not set up properly on both projects and activities when the database is rolled forward?

(I'm thinking of starting over with a fresh copy of my 1306 DB to see what steps I need to do to fix it).

**Comment by TrevorBradleyCDN** [comment]
OK, I've flashed my database with a fresh copy of my 1306 database.  I'm still getting the following error in my debug:

[27.05.2016 13:00:42] KSPI axAction (Trevor): reload_timeSheet
[27.05.2016 13:00:42] timeEntry_edit: Column 'fixedRate' cannot be null (#1048)
[27.05.2016 13:00:42] timeEntry_edit: 2404
[27.05.2016 13:00:42] KSPI axAction (Trevor): add_edit_timeSheetEntry
[27.05.2016 13:00:41] KSPI axAction (Trevor): budgets
[27.05.2016 13:00:41] KSPI axAction (Trevor): bestFittingRates
[27.05.2016 13:00:41] KSPI axAction (Trevor): reload_activities_options 

But now I suspect it to be the fault of the activity, rather than the project.

If I edit the activity, and put in  values for each of default rate, fixed rate, and my rate, kimai now works as expected.

And even more interesting, if I blank out the fields for  fixed rate and my rate (apparently permitted), kimai now breaks as it was breaking for me before.

Narrowing down the parameters, it's just fixed rate.  It doesn't accept an empty value, nor does it accept 0.

**Comment by simonschaufi** [comment]
I'm quite sure I fixed this issue some time ago already. Anyway, can you try to change the db column to allow NULL values?

**Comment by TrevorBradleyCDN** [comment]
I assume you're talking about allowing fixedRates.rate to be NULL?

```
mysql> describe kimai_fixedRates;
+------------+---------------+------+-----+---------+-------+
| Field      | Type          | Null | Key | Default | Extra |
+------------+---------------+------+-----+---------+-------+
| projectID  | int(10)       | YES  | MUL | NULL    |       |
| activityID | int(10)       | YES  |     | NULL    |       |
| rate       | decimal(10,2) | NO   |     | NULL    |       |
+------------+---------------+------+-----+---------+-------+
3 rows in set (0.00 sec)

mysql> alter table kimai_fixedRates modify rate decimal(10,2);
Query OK, 0 rows affected (0.13 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> describe kimai_fixedRates;
+------------+---------------+------+-----+---------+-------+
| Field      | Type          | Null | Key | Default | Extra |
+------------+---------------+------+-----+---------+-------+
| projectID  | int(10)       | YES  | MUL | NULL    |       |
| activityID | int(10)       | YES  |     | NULL    |       |
| rate       | decimal(10,2) | YES  |     | NULL    |       |
+------------+---------------+------+-----+---------+-------+
3 rows in set (0.00 sec)
```

No change. If I then blank out "Fixed Rate" on my one Project Activity (which consequently removes all rows from kimai_fixedRates) I can't modify entries (edit activity, change from one to another) .  

```
[31.05.2016 10:49:21] KSPI axAction (Trevor): reload_timeSheet
[31.05.2016 10:49:21] timeEntry_edit: Column 'fixedRate' cannot be null (#1048)
[31.05.2016 10:49:21] timeEntry_edit: 2406
[31.05.2016 10:49:21] KSPI axAction (Trevor): add_edit_timeSheetEntry
[31.05.2016 10:49:20] KSPI axAction (Trevor): bestFittingRates
[31.05.2016 10:49:20] KSPI axAction (Trevor): budgets
[31.05.2016 10:49:20] KSPI axAction (Trevor): reload_activities_options 
```

I'm don't think this was the right fix.  The DB column "fixedRate.rate" and the code's "fixedRate" don't match up, and the problem occurs when my fixedRates table is empty of all rows, why would there being one null column matter?

**Comment by simonschaufi** [comment]
Guys, today I got a breakthrough in this topic!
By default in newer mysql versions `sql mode` is set to strict:
`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

I use MariaDB and there the value is: `NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

The problematic value is: `STRICT_TRANS_TABLES`.

Here is a possible (temporary) solution: https://mattstauffer.co/blog/how-to-disable-mysql-strict-mode-on-laravel-forge-ubuntu#your-lines until kimai get's fixed to support strict mode.
