### ISSUE TITLE
location of skins

### ISSUE THREAD

**Issue by svenn71** [kimai/kimai#710]
#### Expected behaviour
find skins in myserver.org/kimai/skins

#### Actual behaviour
find skins in myserver.org/skins

#### Steps to reproduce the behaviour
Install kimai, see the error in apache error log.
copy www/kimai/skins to www/skins
reload page and the skin is found

#### Kimai version
Kimai dev 0.9.3.1387

#### Relevant log entries from Kimais Debug tab
File does not exist: /home/myserver.org/www/skins/standard, referer: http://myserver.org/kimai/index.php?a=checklogin

When looking at the code in git, the skins are referred like this:
extensions/#ki_demoextension/css/demo.css.php:    $table_header = "../../../skins/standard/grfx/g3_table_header.png";

Could it be that there is one level of .. too much?

**Comment by simonschaufi** [comment]
The path in the css is correct but the path here is wrong: https://github.com/kimai/kimai/blob/master/templates/scripts/core/main.php#L11 because the file is one level higher than the other ones (in core/)
