### ISSUE TITLE
Kimai automatically fills out empty times

### ISSUE THREAD

**Issue by choriner** [kimai/kimai#711]
#### Expected behavior: 

Breaks should be recorded.
#### Actual behavior: 

After stopping the time recording and making a break (f.e. over night), and then starting the recording again (f.e. next morning) kimai automatically prolongs the last entry tip the start of the new entry. It is impossible to record breaks. After you started the new recording after the break, you can go back and change the end time of the entry before the break. Our kimai is running over an sql and has several users. problem only for one user.

#### Steps to reproduce the behavior: 

stop a recording. go to bed. return to work. start next recording. the recording from the day before will prolong until the start of the next recording.

#### Kimai version: 

v0.9.2.1306  / GPL Version 3 (Deutsche Übersetzung). 

#### Relevant log entries from Kimais Debug tab: 

where can I find the debug tab

**Comment by simonschaufi** [comment]
We don't support old versions of kimai any more.
Please update to 0.9.3 (releases can be found on [github](https://github.com/kimai/kimai/releases)) and let us know if the problem still exist there.
