### ISSUE TITLE
Rechnungszeitraum

### ISSUE THREAD

**Issue by 5-2** [kimai/kimai#712]
#### Expected behaviour
Ich möchte zur Rechnungserstellung auswählen können, für welchen Zeitraum sie sein soll.
#### Actual behaviour
Die Zeitspanne ist fest eingetragen
#### Steps to reproduce the behaviour
Das Menü Rechnungen auswählen.
#### Kimai version
 0.9.3.1384
#### Relevant log entries from Kimais Debug tab
-

**Comment by simonschaufi** [comment]
you can select the date when clicking on it. a calendar should pop up

**Comment by kevinpapst** [comment]
Die Zeitspanne ist auf jedenfall auswählbar, zumindest im aktuellsten GitHub Stand:
https://github.com/kimai/kimai/archive/master.zip

**Comment by 5-2** [comment]
Alles klar, das funktioniert. Ich bin nicht auf die Idee gekommen in der obersten Box, mittig zu klicken.
Vielen Dank!
