### ISSUE TITLE
"Forgot My Password" email system not working.

### ISSUE THREAD

**Issue by andyarnoldgb** [kimai/kimai#713]
#### Expected behaviour
Receive an email regarding password change.

#### Actual behaviour
Nothing received. 
#### Steps to reproduce the behaviour
Everytime.

#### Kimai version
Latest

Where is the code to prompt the email to be sent?

**Comment by simonschaufi** [comment]
Here is the code https://github.com/kimai/kimai/blob/master/processor.php

**Comment by kevinpapst** [comment]
There is purposely no visual feedback if the email was sent or not.

**Comment by simonschaufi** [comment]
After clicking "reset password" a text appears: 

> An email has been sent to the associated email address. Please follow the instructions provided in that email. If no email address is associated with this username you won't receive an email and need to contact your administrator.

so for me there is a visual feedback.

**Comment by kevinpapst** [comment]
Let me clarify "There is purposely no visual feedback if the email was sent or not.":
There is always the message you mentioned, without an indication whether the email was really sent or not or even if the user exists. That is to prevent abuse of the form. You won't get a message whether the tested username exists or not

**Comment by simonschaufi** [comment]
fixed in #732
