### ISSUE TITLE
Main Page Location

### ISSUE THREAD

**Issue by ChuTang23** [kimai/kimai#720]
Hello, I've just started using this system and it's amazing. Thanks for all your hard work. I'm tech savvy and got this guy up and running and customized a bit to my liking. I was wondering a few things:

1. Where can I edit the main layout page? Right now it seems the logo is hard coded at 151x52 and I need to change that. I've made my adjustments in the CSS, just need to remove that hard coded value. 

2. How can I display time format in 12 hour time? I read on an old thread it was hardcoded in.  Could you point me to where it's hard coded and is it possible to change? 

Thanks in advance for your help,

DrChu

**Comment by kevinpapst** [comment]
Hi! Thanks for the kind words :)

- https://github.com/kimai/kimai/blob/master/templates/scripts/core/main.php#L190
- I am not sure if it is easy to change, interesting question ... might be a good feature request (in a new issue please). Which time(s)/display positions are you talking about?

Regards
Kevin

**Comment by ChuTang23** [comment]
@kevinpapst Thanks for your quick reply.  I'm talking about the "time in / time out".  Currently they are displayed like "In - 20:58  Out - 21:30".  I'd like it to be a 12 hour format like "In - 10:00   Out - 12:00"

**Comment by simonschaufi** [comment]
> How can I display time format in 12 hour time? I read on an old thread it was hardcoded in. Could you point me to where it's hard coded and is it possible to change?

This is hard coded so far:
https://github.com/kimai/kimai/blob/master/extensions/ki_timesheets/templates/scripts/timeSheet.php#L128

**Comment by kevinpapst** [comment]
10 days and no feedback... 👎

**Comment by simonschaufi** [comment]
I just left this open as a reminder that we need to make an issue to make this configurable

**Comment by simonschaufi** [comment]
done with #721
