### ISSUE TITLE
moving kimai to a different server

### ISSUE THREAD

**Issue by piflixe** [kimai/kimai#722]
Hi there!

Could someone please give me a hint on how to move kimai to a different server? 

What I tried so far:
1. copy installation folder to new server
2. copy mysql database to new server
3. change includes/autoconf.php on new server to grant access to the new database

I also tried:
1. perform a new blank installation on the new server
2. delete mysql database that what created by the installer
3. replace mysql database on new server with the database from the old server

I end up with a weird behaviour: I see the kimai login screen but can neither login with the default admin credentials after installation nor with the credentials from the old server.

I hope I was clear enough to explain what I am trying to do. I am not an IT expert, so please be indulgent :-)

Thanks for your help!
Kind regards,
Felix

**Comment by simonschaufi** [comment]
Hi Felix,
your steps sound good so far, my idea is that the php version is different on the other server or something else with the setup is very different. We cannot provide support for server environments. Better get in touch with your hosting provider!

**Comment by kevinpapst** [comment]
Have a look at the logfile at temporary/logfile.txt - maybe there is a hint

**Comment by piflixe** [comment]
Hi Simon, 
I tested the moving by creating another instance on the same server. So the environment should be exactly the same. 
Any more ideas?
Kind regards, Felix 
--von einem mobilen Gerät gesendet. Bitte entschuldigen Sie die Kürze.
Sent from a mobile device. Please excuse the brevity. 
Felix Piela August & Piela Konstruktiv GbR Tempelhofer Weg 11-1210829 Berlin www.konstruktiv-berlin.deemail. piela@konstruktiv-berlin.de tel. 030 9190 5511fax. 030 9190 9733

-------- Ursprüngliche Nachricht --------
Von: Simon Schaufelberger <notifications@github.com> 
Datum: 23.06.2016  14:25  (GMT+01:00) 
An: kimai/kimai <kimai@noreply.github.com> 
Cc: Felix Piela <piela@konstruktiv-berlin.de>, Author <author@noreply.github.com> 
Betreff: Re: [kimai/kimai] moving kimai to a different server (#722) 

Hi Felix,

your steps sound good so far, my idea is that the php version is different on the other server or something else with the setup is very different. We cannot provide support for server environments. Better get in touch with your hosting provider!

**Comment by piflixe** [comment]
With the help of Simon I could solve the problem as follows:
1. Copy installation folder to new location
2. Copy database to new location
3. change $server_database and $server_username and $server_password in ./includes/autoconf.php to match the mysql accounts in the new location (don't change anything else)

**Comment by azmatullah** [comment]
Hi Piflixe,

I'm facing same problem. I'm follow exact step which you mentioned but no any PHP page showing.

Please help,
Azmat

**Comment by piflixe** [comment]
Dear Azmat,
sorry, I can't help you with that, since I do not deeply understand the underlying mechanisms. Please consider asking the kimai developers for professional help.
Kind regards, Felix

**Comment by youngmicroserf** [comment]
Just in case someone comes accross this thread: I moved a server and didn't realize that some table names are referenced using *camelCase* names in the code, say "timeSheet". They were, however, exported by phpmyadmin as all lower case, which meant the code found some, but not all tables. Thus, potentially, you need to manually recreate the camelCase names for some tables in the new database.
