### ISSUE TITLE
config/config.ini billable values not updating on dev 0.9.3

### ISSUE THREAD

**Issue by nmpribeiro** [kimai/kimai#724]
#### Expected behaviour
If I change the config/config.ini file with more billable values, changes update on 'edit' timesheet entry
#### Actual behaviour
If I change the config/config.ini file with more billable values, changes do **not** update on 'edit' timesheet entry
#### Steps to reproduce the behaviour
Update RC to dev
#### Kimai version
0.9.3

**Comment by simonschaufi** [comment]
the feature has been replaced by config settings in ``includes/autoconf.php``.
```php
$billable = array (
  0 => 0,
  1 => 50,
  2 => 100,
);
```
