### ISSUE TITLE
CSV importer for 3rd party ticketing software

### ISSUE THREAD

**Issue by yayitazale** [kimai/kimai#724]
A CSV importer to automate the creation of the time records from the Ticketing software.

It would be a nice feature to have a GUI uploader of CSV archives to create automatic entrys for the employees that are Service Desk agents. 

The best solution it would be to have 2 types of importing systems:

1. Manual mode in GUI with file selector.
2. Automatic upload and delete any CSV file from a configured path.

You can link to a template of importing CSV with a fixed columns for each information. I give you an example of an exported CSV from my Ticketing System (Lansweeper) with almost the same structure of the exporting CSV of Kimai:
[TicketExport.zip](https://github.com/kevinpapst/kimai2/files/3115713/TicketExport.zip)

The column matching would be like this in that case:
    

- **CSV           ->              KIMAI**
- LastUpdate       ->        Date
- AssignedAgent  ->        User
- Company          ->      Customer
- Department      ->        Project
- Activity fixed on configuration page to one, for example: "HelpDesk"
- Text                   ->     Description
- MinutesWorked ->      Duration

 
Many thanks for your work!

**Comment by yayitazale** [comment]
You have been promoted:

https://ethical.net/resources/?resource-category=team-collaboration-software

Cheers

**Comment by zeezhao** [comment]
Yes, this will be extremely useful. We have a situtation too where all the tasks are coming from an "incident" system. Thanks.

**Comment by kevinpapst** [comment]
Kimai has CSV importer for the command line: https://www.kimai.org/documentation/imports.html
So you should be able to script what you need, in case your 3rd party system has an export via command line.

**Comment by zeezhao** [comment]
@kevinpapst - thanks for your reply. I have been able to test this for projects.

Please can you confirm that the importer also works for tasks? I do not have the task management module (https://www.kimai.org/store/task-management-bundle.html) yet, but want some confirmation. Thanks.

**Comment by kevinpapst** [comment]
No, task module doesn't have import support. Next version will ship an API, maybe that can help to script automated import.

**Comment by kevinpapst** [comment]
If someone needs a new format, please open an issue here:
https://github.com/kevinpapst/ImportBundle

Or send in a PR, that would be even better.
