### ISSUE TITLE
Cannot add or edit timesheet entry

### ISSUE THREAD

**Issue by carstenlucke** [kimai/kimai#729]
#### Expected behaviour
I click edit on an existing timesheet entry. The popup dialog opens, i can edit values and clicking OK will submit/save the timesheet data.
Directory permissions are alright. 777 for 'temporary'.

#### Actual behaviour
Clicking OK results in an XHR request to the URL https://HOSTNAME/extensions/ki_timesheets/processor.php. Response code is 200. But the edit dialog doesn't close and also the timesheet data is not saved.

#### Steps to reproduce the behaviour
Click edit on a timesheet entry. Edit duration. Click OK.

#### Kimai version
Kimai 1.0.1.1388

#### Relevant log entries from Kimais Debug tab
[05.07.2016 00:06:39] Uncaught exception: Could not determine temp directory, please specify a cache_dir manually 

#### Additional information
It seems this bug existed before: https://github.com/kimai/kimai/issues/483.

I applied the proposed hack in File.php (Zend_Cache Backend) and hardcoded the absolute path to the temporary directory. This solves the problem. 

Shouldn't the installer somehow configure the cache-directory?

**Comment by simonschaufi** [comment]
We are doing a lot of code refactoring and will take care about this bug in the future even though we still don't know exactly what is the root cause of this bug.

**Comment by kevinpapst** [comment]
Thanks for the feedback! This is only happening on some systems and as @simonschaufi mentioned unclear why that happens at all. But we will look into it!

**Comment by carstenlucke** [comment]
Hi guys,

probably the wording should be: it somehow works on some systems instead of: it doesn't work on some systems. ;-)

I suppose the Zend_Cache component u are using isn't properly configured. You should instantiate the cache component with a factory method. The documentation of ZF 1.x shows this: https://framework.zend.com/manual/1.12/en/zend.cache.introduction.html

Hard-coding the cache-dir in Zend_Cache_Backend_File is the worst case.

HTH.

Regards,
Carsten

Anyway, Kimai is a great tool!!! Thanks for your work!

**Comment by simonschaufi** [comment]
We only use Zend_View. There is nothing about caching set. Could you help us digging deeper and find the solution to this problem?

**Comment by kevinpapst** [comment]
Hahaha Carsten - I would say something in between... as Simon wrozte: we do not use Zend_Cache directly. I tried to find the link to Zend_Cache with a simple search through the project without luck/success.. 

We have to do two things:
- find out where the heck the Cache class is used, seems neither Zend_Config, Zend_Registry or Zend_View utilizes it (probably some View Helper?)  / probably by patching the Backend class and add a backtrace to find it
- find a way to set a default path for all these systems that do not have a global system TMP dir configured (likely shared hosts?)

**Comment by kevinpapst** [comment]
Zend Framework 1 is creepy ;-)
I found the reason:
https://github.com/kimai/kimai/blob/master/extensions/ki_timesheets/processor.php#L471

Zend_Validate_Date is using Zend_Date::isDate() which then is using Zend_Locale_Format and Zend_Locale_Data => and these two classes use a Zend_Cache instance.

It seems we have to set some global Zend Caches. I will have a look into it.

**Comment by carstenlucke** [comment]
Nice, Kevin! :)

**Comment by simonschaufi** [comment]
and to explain it even more, this line will look for the temp directory: https://github.com/kimai/kimai/blob/master/libraries/zendframework/zendframework1/library/Zend/Cache/Backend/File.php#L130
