### ISSUE TITLE
Can't connect to Database with different port

### ISSUE THREAD

**Issue by PCE-Christian** [kimai/kimai#736]
Hi,

i'm trying to install kimai on my webspace. Setup said everything is okay, all folder permissions are correct. Then i enter my SQL data, and always get the error that the database could not be opened. SQL connection data is 100% correct. Any suggestions why it is not working? Database ist not running at localhost, it's an ip with port like 123.456.789.99:9876 - is that a problem for kimai?

EDIT:
It is a problem. Without the port it works. Maybe someone else is running into this problem and will now know how to fix.

**Comment by kevinpapst** [comment]
Indeed, I guess Kimai or the underlying database class does not support passing a port yet.
If you have enough experience, you could try to edit this file:
https://github.com/kimai/kimai/blob/master/libraries/phpclasses/ultimatemysql/mysql.class.php#L1064

This is currently the only solution. You need to change 
```
$this->mysql_link = @mysqli_connect (
				$this->db_host, $this->db_user, $this->db_pass);
```
to 
```
$this->mysql_link = @mysqli_connect (
				$this->db_host, $this->db_user, $this->db_pass, 'yourDatabase', 9876);
```

Sorry, this is not easily fixable right now.

**Comment by PCE-Christian** [comment]
Hi Kevin,

no problem, it works for me without the port :) Maybe you could keep it in mind for future releases, or you insert a note at this point to tell the users that there might be a problem :)

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
