### ISSUE TITLE
Remote start/stop from a BDE-terminal

### ISSUE THREAD

**Issue by resli** [kimai/kimai#737]
...May be I'm not the first asking this...

With Kimai 0.9.1 I wrote a hand-crafted php script that allows my BDE-terminal to control kimai by simple http-requests (server.tld/bde.php?cmd=start&user=XXX). This hack does not function anymore with v1.0

Is there already a function like this? I prefer 'clean' software ever possible. This is the only missing function that prevents me in using v1.0.

**Comment by kevinpapst** [comment]
There is a JSON and SOAP API available: https://github.com/kimai/kimai/blob/master/core/json.php
This project could help you to understand how to use it: https://github.com/kimai/kimai-mobile

**Comment by simonschaufi** [comment]
If you could share your script here, that would be great for help.
As Kevin said, better use the proper API and if there is something missing, please feel free to change the code and make a Pull Request so that everybody can make use of it!

**Comment by resli** [comment]
Thanks for the hints. I look into it and try to adapt it.
