### ISSUE TITLE
Cant edit configuration - configuration_edit: Column 'value' cannot be null

### ISSUE THREAD

**Issue by tiMon1987** [kimai/kimai#738]
Hey,
im on it now for the second day. I wanted to test the latest Kimai Version on our webserver. Installation works fine. But I am not able to change the configuration. Seems to be a 'not null' problem, because it tries to set NULL for all unchecked checkboxes.
The "NOT NULL" bit for "value" seems to be correct when i look at the install php:

```
$query =
"CREATE TABLE `${p}configuration` (
  `option` varchar(255) NOT NULL,
  `value` varchar(255) NOT NULL,
  PRIMARY KEY  (`option`)
);";
exec_query($query);
```
If go to the database and allow NULL for the value-column i can change the config in kimai. The default 0s for the unchecked checkboxes are then overritten with NULL.

#### Expected behaviour
Edit the the Configuration
#### Actual behaviour
Not able to edit - getting "configuration_edit: Column 'value' cannot be null (#1048)"
#### Steps to reproduce the behaviour
Clean install of newest Version and change any configuration value (it need not to be the checkbox)
#### Kimai version
latest stable 1.0.1 and same behavior with latest masterbranch
#### PHP/mySQL Version:
PHP Version 5.6.20-0 / mySQL Version 5.7.11
#### Relevant log entries from Kimais Debug tab
> [11.07.2016 13:48:57] -- begin install ----------------------------------
> [11.07.2016 13:49:00] -- installation finished without error ------------
> [11.07.2016 13:49:04] login: admin as user
> [11.07.2016 13:49:11] KSPI axAction (admin): securityWarning
> [11.07.2016 13:49:14] KSPI axAction (admin): refreshSubtab
> [11.07.2016 13:49:14] KSPI axAction (admin): refreshSubtab
> [11.07.2016 13:49:14] KSPI axAction (admin): refreshSubtab
> [11.07.2016 13:49:43] KSPI axAction (admin): sendEditAdvanced
> [11.07.2016 13:49:43] configuration_edit: Column 'value' cannot be null (#1048)

I get similar problems when i try to add a user and set a password:
> [12.07.2016 10:53:29] KSPI axAction (admin): createUser
> [12.07.2016 10:53:30] KSPI axAction (admin): editUser
> [12.07.2016 10:53:30] KSPI axAction (admin): refreshSubtab
> [12.07.2016 10:53:34] KSPI axAction (admin): sendEditUser
> [12.07.2016 10:53:34] user_edit failed: 
> [12.07.2016 10:53:34] KSPI axAction (admin): reload_users
> [12.07.2016 10:53:34] KSPI axAction (admin): refreshSubtab
> [12.07.2016 10:53:34] KSPI axAction (admin): refreshSubtab

Its a problem with the e-mail value. If its empty i get the error above. If i allow NULL or enter any text everything works.

I have no idea if its a php/html problem, a kimai problem or a database problem. But if i try it with the old 0.9.2.1306-3 Version everything works as expected and it sets the 0 instead of trying to set NULL.

I really hope u can help me with my problems.
Thanks in advance, Timo

**Comment by simonschaufi** [comment]
Are you talking about config settings in the Administration?

**Comment by tiMon1987** [comment]
Yes, im talking about Administration/Advanced settings. The demoversion on your server doesnt make any problems for me.
I tried it with several fresh installs on all possible ways (unzip on server or local, with different Versions, install and then update...). And also made a clean install with the 0.9 Version and then updated to the latest version. There is no difference. Only the old 0.9.2 works for me.

**Comment by tiMon1987** [comment]
I gave it to our trainee and he tried to install it on his local testmachine with a local database and he gets the same issues. Is there anything we can try?
Or can i maybe download somewhere an older 1.0 Version? I was only able to test it with the latest dev and the stable 1388. But the 0.9 Version works for some reason.

**Comment by simonschaufi** [comment]
Let us find out why there is a NULL value. Can you please tell me which key is setting a NULL value?

**Comment by wgillingham** [comment]
Great stuff - thanks :)

I'm running into this also... seems every unchecked checkbox causes this.

Tried chrome and firefox, same.

I'm running IIS, php 5.6

**Comment by kevinpapst** [comment]
Hi! Could anyone of the people who experience the bug, please test the changes from pull request #755 and let me know if that fixes your problems? 
I wasn't able to reproduce the problem, so I can't tell if the fix is sufficient.

**Comment by tiMon1987** [comment]
Thanks for reply.
It doesnt help, but i get some new notices instead of the NULL-Error after checking one of the unchecked checkboxes and saving the changes:

> [02.08.2016 14:25:31] KSPI axAction (admin): securityWarning 
> [02.08.2016 14:25:30] E_NOTICE Undefined index: editLimitEnabled @/www/zeiterfassung/extensions/ki_adminpanel/processor.php line 467 
> [02.08.2016 14:25:30] E_NOTICE Undefined index: exactSums @/www/zeiterfassung/extensions/ki_adminpanel/processor.php line 465 
> [02.08.2016 14:25:30] E_NOTICE Undefined index: durationWithSeconds @/www/zeiterfassung/extensions/ki_adminpanel/processor.php line 464 
> [02.08.2016 14:25:30] E_NOTICE Undefined index: allowRoundDown @/www/zeiterfassung/extensions/ki_adminpanel/processor.php line 459 
> [02.08.2016 14:25:30] E_NOTICE Undefined index: currency_first @/www/zeiterfassung/extensions/ki_adminpanel/processor.php line 449 
> [02.08.2016 14:25:30] E_NOTICE Undefined index: show_gabBreaks @/www/zeiterfassung/extensions/ki_adminpanel/processor.php line 444 
> [02.08.2016 14:25:30] E_NOTICE Undefined index: check_at_startup @/www/zeiterfassung/extensions/ki_adminpanel/processor.php line 442 
> [02.08.2016 14:25:30] KSPI axAction (admin): sendEditAdvanced 
> [02.08.2016 14:24:39] E_WARNING in_array() expects parameter 2 to be array, boolean given @/www/zeiterfassung/extensions/ki_adminpanel/templates/scripts/activities.php line 52 
> [02.08.2016 14:24:39] KSPI axAction (admin): refreshSubtab 
> [02.08.2016 14:24:39] KSPI axAction (admin): refreshSubtab 
> [02.08.2016 14:24:39] KSPI axAction (admin): refreshSubtab 
> [02.08.2016 14:24:24] KSPI axAction (admin): securityWarning 
> [02.08.2016 14:24:23] login: admin as user 
> [02.08.2016 14:24:14] -- installation finished without error ------------ 
> [02.08.2016 14:24:09] -- begin install ---------------------------------- 

Furthermore all boolean database values are set to 0 and all the corresponding checkboxes get unchecked after saving.

**Comment by simonschaufi** [comment]
Could you add the following line in the ``/www/zeiterfassung/extensions/ki_adminpanel/processor.php`` file where this E_NOTICE comes from and post the result here?
Open console in your browser and then check the result of the ajax request.
```php
print_r($_REQUEST);
exit;
```
I have the strong feeling that something with that variable is wrong.
mine looks like this:
```php
Array
(
    [adminmail] => xxx@xxx.xxx
    [logintries] => 3
    [loginbantime] => 900
    [language] => de
    [show_update_warn] => 1
    [show_daySeperatorLines] => 1
    [show_RecordAgain] => 1
    [show_TrackingNr] => 1
    [currency_name] => Euro
    [currency_sign] => €
    [currency_first] => 1
    [date_format_2] => %d.%m.%Y
    [date_format_0] => dd.mm.yy
    [date_format_3] => d.m.Y
    [date_format_1] => %d.%m.
    [roundPrecision] => 1
    [allowRoundDown] => 1
    [decimalSeparator] => ,
    [defaultTimezone] => Europe/Berlin
    [roundTimesheetEntries] => 1
    [roundMinutes] => 1
    [roundSeconds] => 0
    [axAction] => sendEditAdvanced
)
```

**Comment by simonschaufi** [comment]
could it be that you have a strange [php.ini setting](http://stackoverflow.com/a/5701703)?

**Comment by kevinpapst** [comment]
As this page http://demo.kimai.org/core/kimai.php is using the latest master and I cannot verify the problem there (my local dev box doesn't show this problem as well), it is likely that this is some kind of PHP version or environment problem. If anyone has more insights please share! We can't fix a problem we can't see.
You can download an old version from here: https://github.com/kimai/kimai/releases
But it would be great if you could help us to solve this problem.
Could you attach an output of "phpinfo()"?

**Comment by simonschaufi** [comment]
@tiMon1987 if you don't provide more info, we can't solve the problem

**Comment by tiMon1987** [comment]
Sorry for the late reply. There wasnt enough time for kimai in last week.

1. I dont know what im doing wrong. I added the 
`print_r($_REQUEST);
exit;`
in the sendEditAdvanced block in the processor.php, but i allways get the same error in the console:

> VM343:3 Uncaught TypeError: Cannot read property 'length' of undefinedcb @ VM343:3each @ jquery-1.9.1.min.js:2each @ jquery-1.9.1.min.js:2(anonymous function) @ jquery.form.min.js:11t.success @ jquery.form.min.js:11c @ jquery-1.9.1.min.js:2fireWith @ jquery-1.9.1.min.js:2k @ jquery-1.9.1.min.js:4r @ jquery-1.9.1.min.js:4

Could you tell me the line where i should add the print_r... statement in the default processor.php file

2. I checked the php.ini settings and the request_order is correct.

3. The info.php:

> PHP Version 5.6.20-0+deb8u1
>  
> 
> System  Linux web2 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64  
> Build Date  Apr 27 2016 11:25:08  
> Server API  FPM/FastCGI  
> Virtual Directory Support  disabled  
> Configuration File (php.ini) Path  /etc/php5/fpm  
> Loaded Configuration File  /etc/php5/fpm/php.ini  
> Scan this dir for additional .ini files  /etc/php5/fpm/conf.d  
> Additional .ini files parsed  /etc/php5/fpm/conf.d/05-opcache.ini, /etc/php5/fpm/conf.d/10-pdo.ini, /etc/php5/fpm/conf.d/20-curl.ini, /etc/php5/fpm/conf.d/20-gd.ini, /etc/php5/fpm/conf.d/20-intl.ini, /etc/php5/fpm/conf.d/20-json.ini, /etc/php5/fpm/conf.d/20-ldap.ini, /etc/php5/fpm/conf.d/20-mysql.ini, /etc/php5/fpm/conf.d/20-mysqli.ini, /etc/php5/fpm/conf.d/20-pdo_mysql.ini, /etc/php5/fpm/conf.d/20-readline.ini, /etc/php5/fpm/conf.d/20-xmlrpc.ini  
> PHP API  20131106  
> PHP Extension  20131226  
> Zend Extension  220131226  
> Zend Extension Build  API220131226,NTS  
> PHP Extension Build  API20131226,NTS  
> Debug Build  no  
> Thread Safety  disabled  
> Zend Signal Handling  disabled  
> Zend Memory Manager  enabled  
> Zend Multibyte Support  provided by mbstring  
> IPv6 Support  enabled  
> DTrace Support  enabled  
> Registered PHP Streams https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip 
> Registered Stream Socket Transports tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2 
> Registered Stream Filters zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk 


I also tried to install the latest version on my private machine at home with an fast installed xampp testenviroment. And of course everything works fine there. So i am fortunately not to stupid to install kimai ;) and it must be an enviroment or an php problem here. 

The 0.9.3 version works fine in our enviroment.

**Comment by Ruckhaber** [comment]
I have the same problem. Is there currently a solution ? I am using kimai 1.01. 1388 dev on Linux debian-server 3.16, PHP Version 5.6.14, Apache 2.4.10, MySQL 5.5.46.
Can I make the entries in the configuration by hand directly in the database? 
On the same system kimai version 0.9.2.1306 is installed. The configuration can be modified and stored without problems for version 0.9.2.1306 .

**Comment by simonschaufi** [comment]
we switched from mysql to mysqli in version 1.0.0. Can you please test if the problem still exists on the develop branch?

**Comment by Ruckhaber** [comment]
I'm not a PHP developer. I installed Xdebug and NetBeans on my machine. I can run kimai line by line. What expenses are required?

**Comment by simonschaufi** [comment]
Guys, I think i found the problem!

**Comment by Ruckhaber** [comment]
It works. Thank you

**Comment by tiMon1987** [comment]
The Problem with the Checkboxes is solved. It works fine. Thanks for that!


Not a big problem for me, but i still cant edit userprofiles without an mailaddress or at least one character in the mail formfield.

```
[29.08.2016 10:40:37] KSPI axAction (admin): refreshSubtab
[29.08.2016 10:40:37] KSPI axAction (admin): refreshSubtab
[29.08.2016 10:40:37] KSPI axAction (admin): reload_users
[29.08.2016 10:40:37] user_edit failed:
[29.08.2016 10:40:37] KSPI axAction (admin): sendEditUser
[29.08.2016 10:40:24] KSPI axAction (admin): editUser 
```
The other formfields can be empty. But they can be NULL in the database. The mail is NOT NULL.

**Comment by simonschaufi** [comment]
please open a new issue for that.
