### ISSUE TITLE
Http Auth not working

### ISSUE THREAD

**Issue by snoopyf** [kimai/kimai#739]
#### Expected behaviour
User gets authenticated by HTTP Basic Auth ("REMOTE_USER")

#### Actual behaviour
Login Screen is shown, user isn't logged in to Kimai

#### Steps to reproduce the behaviour
-> Change Authenticator to "Http" in "autoconf.php"
-> Try to login with an HTTP - Auth User (who exists in Kimai User DB)

#### Reverse Engenieered cause
In libraries/Kimai/Auth/Http.php there are several mysql function (mysql_query, mysql_real_escape_string) without a ressource link identifier to a valid mysql connection set, for example:
```php
public function performAutoLogin(&$userId) {
        // User is authenticated by web server. Does the user exist in Kimai yet?
        global $kga;
        $check_username = $this->HTAUTH_FORCE_USERNAME_LOWERCASE ? strtolower($check_username) : $check_username;
        $result = mysql_query(sprintf("SELECT * FROM %susers WHERE name ='%s';", $kga['server_prefix'], mysql_real_escape_string($check_username)));
}
```

Without link identifier, PHP tries to use the last connection and if it doesn't find any, tries to connect to mysql as it would with "mysql_connect()" without any arguments.
The last is, what happens... changing the line:
```php
$result = mysql_query(sprintf("SELECT * FROM %susers WHERE name ='%s';", $kga['server_prefix'], mysql_real_escape_string($check_username)));
```
to
```php
$result = mysql_query(sprintf("SELECT * FROM %susers WHERE name ='%s';", $kga['server_prefix'], mysql_real_escape_string($check_username))) or die(mysql_error());
```
gives this output in browser:
```
Access denied for user 'www-data'@'localhost' (using password: NO)
```
So the authenticated user can't be found in the Kimai DB and so the login screen is shown.

**Comment by simonschaufi** [comment]
oh, this is a place where no db api is used. Thank you for your investigations!

**Comment by simonschaufi** [comment]
Can you please verify that https://github.com/kimai/kimai/pull/745 fixes the issue?

**Comment by snoopyf** [comment]
Just applied the patch of #745 and did a quick test. It seems to fix the issue, the HTTP - Auth User is correctly logged in automatically. 
Thx for the quick help!

**Comment by simonschaufi** [comment]
merged.
