### ISSUE TITLE
Kimai_Config Class error in develop branch installer

### ISSUE THREAD

**Issue by joejoe31b** [kimai/kimai#742]
_This error only occurs in the develop branch._

#### Expected behaviour
After pressing 'Install' at the final installation wizard screen, it should fade to black. After remaining black for a few seconds (at the same URL of the installer, http://localhost/kimai_master/kimai/installer/), the login page loads.

#### Actual behaviour
After pressing 'Install' at the final installation wizard screen, it fades to black before a white screen appears. The URL of this screen is http://localhost/kimai_develop/kimai/installer/install.php?accept=1&timezone=UTC

This page returns a 500 error code, and creates this error in my PHP log file:
`[Wed Jul 13 16:51:48.575376 2016] [:error] [pid 2686] [client 127.0.0.1:36178] PHP Fatal error:  Uncaught Error: Class 'Kimai_Config' not found in /srv/http/kimai_develop/kimai/includes/vars.php:50\nStack trace:\n#0 /srv/http/kimai_develop/kimai/includes/basics.php(48): require_once()\n#1 /srv/http/kimai_develop/kimai/installer/install.php(57): include('/srv/http/kimai...')\n#2 {main}\n  thrown in /srv/http/kimai_develop/kimai/includes/vars.php on line 50, referer: http://localhost/kimai_develop/kimai/installer/`

Looking in the includes folder, I can see that autoconf.php has been created, but it is an empty file.

#### Steps to reproduce the behaviour
This always occurs when pressing 'Install' at the final installation wizard screen on the latest code from the develop branch.

#### Kimai version
The latest from the master branch performs the expected behaviour (the installer says v1.0.1.1388), but the develop branch performs the actual behaviour.

#### Relevant log entries from Kimais Debug tab
Cannot be accessed as the error occurs at the installation stage.

**Comment by simonschaufi** [comment]
I wonder why you are using develop as this branch is under heavy development and constantly changing. If you want to have a reliable version, please use master.

Anyway, I cannot reproduce this.

**Comment by joejoe31b** [comment]
I am interested in contributing to the project, and was of the impression that we were to to use the develop branch. 

I am still learning PHP, and am struggling to simply initialize/install the branch. I spent a while trying to troubleshoot it but to no avail.

Is there any information that I could provide that would help troubleshoot it?

**Comment by simonschaufi** [comment]
Can you please install composer and execute ``composer dump-autoload`` in kimai's root folder? If the error is gone afterwards, please let us know which files have changed (with ``git status``)

**Comment by joejoe31b** [comment]
Thank you for your reply.

Running `composer dump-autoload` fixes the problem so that it now performs the expected behaviour. The only files that were changes were changed are `/libraries/composer/autoload_namespaces.php` and `/libraries/composer/autoload_static.php`.

```
diff --git a/libraries/composer/autoload_namespaces.php b/libraries/composer/autoload_namespaces.php
old mode 100644
new mode 100755
index 75e0432..5725b12
--- a/libraries/composer/autoload_namespaces.php
+++ b/libraries/composer/autoload_namespaces.php
@@ -8,5 +8,5 @@ $baseDir = dirname($vendorDir);
 return array(
     'Zend_' => array($vendorDir . '/zendframework/zendframework1/library'),
     'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
-    'Kimai_' => array($vendorDir),
+    'Kimai_' => array($vendorDir . ''),
 );

diff --git a/libraries/composer/autoload_static.php b/libraries/composer/autoload_static.php
old mode 100644
new mode 100755
index ab30320..9fc5cab
--- a/libraries/composer/autoload_static.php
+++ b/libraries/composer/autoload_static.php
@@ -29,7 +29,7 @@ class ComposerStaticInit8c00ac27a90dfc4ac1a7acb480023ed4
         array (
             'Kimai_' => 
             array (
-                0 => 'C:\\xampp704\\htdocs\\kimai\\htdocs\\libraries',
+                0 => __DIR__ . '/../..' . '/libraries',
             ),
         ),
     );

```

The corrected line in `autoload_namespaces.php` corrects the behaviour for me.

**Comment by joejoe31b** [comment]
Sorry for messing you around a little bit. I somehow missed `autoload_static.php` being the other changed file.

Thank you guys for your help, all has been fixed :)

**Comment by simonschaufi** [comment]
Don't worry, we want to find and fix all the bugs. Feel free to just crab an issue and fix it ;)
