### ISSUE TITLE
OK Button editing entries in timesheet doesn't work

### ISSUE THREAD

**Issue by mahoplus** [kimai/kimai#749]
#### Actual behaviour OK-Button does nothing - other OK-Buttons works fine!
testet with different actual browser. OK Button works in kimai-demo, but not in my installation

#### Kimai version: 1.0.1.1388

thank you for support

Martin
--
(der tut nichts - der will nur spielen)

**Comment by simonschaufi** [comment]
Hi Martin, this sounds very much like this bug #731 which has been fixed already. Can you download latest git master and see if it works?

**Comment by mahoplus** [comment]
thank you - now it works fine!

Martin
--
(der tut nichts - der will nur spielen)
