### ISSUE TITLE
Update Error unknown Column 'Groupleader' & 'Admin'

### ISSUE THREAD

**Issue by holgerpopolger** [kimai/kimai#751]
Kimai version 1.0.1-1380

Updater shows errors:

UPDATE `kimai_membershipRoles` SET `core-user-view` = 1 WHERE `name` = 'Admin';
Unknown column 'core-user-view' in 'field list' (#1054)
---
UPDATE `kimai_membershipRoles` SET `core-user-view` = 1 WHERE `name` = 'Groupleader';
Unknown column 'core-user-view' in 'field list' (#1054)
---
I will ignore all "Duplicate entry "-Entries

Can't continue to any further steps. Even when I hit the "login"-Button I am redirected to the updater start page.
Thanks a lot!!

![bildschirmfoto 2016-07-18 um 17 18 04](https://cloud.githubusercontent.com/assets/20519821/16919884/aa273950-4d0b-11e6-9af2-c548edd7946b.png)

**Comment by kevinpapst** [comment]
Hi! From which Kimai version are you trying to update?
Can you post the structure of the kimai_membershipRoles table?

**Comment by holgerpopolger** [comment]
Thanks for your reply! The Version I am using right now is **0.9.3**.

Here comes the kimai_membershipRoles-table:
![bildschirmfoto 2016-07-19 um 10 40 49](https://cloud.githubusercontent.com/assets/20519821/16943711/4df945a0-4d9d-11e6-83ce-bebe13e7dba2.png)

since i try to update my kimai there are a lot of **"kimai_bak_"-tables** in my db. can i just delete them?

thanks a lot!

**Comment by kevinpapst** [comment]
Yes, you can delete them. But please wait until the update runs fine. 
Are these really all columns in this table? Can you export the table without data and attach the output here?

**Comment by holgerpopolger** [comment]
`
-- phpMyAdmin SQL Dump
-- version 3.4.11.1deb2+deb7u4
-- http://www.phpmyadmin.net
--

-- Erstellungszeit: 19. Jul 2016 um 12:06
-- Server Version: 5.6.29
-- PHP-Version: 5.4.45-0+deb7u4

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Datenbank: `xxx`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `kimai_membershipRoles`
--

CREATE TABLE IF NOT EXISTS `kimai_membershipRoles` (
  `membershipRoleID` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `core-customer-add` tinyint(4) DEFAULT '0',
  `core-customer-edit` tinyint(4) DEFAULT '0',
  `core-customer-delete` tinyint(4) DEFAULT '0',
  `core-customer-assign` tinyint(4) DEFAULT '0',
  `core-customer-unassign` tinyint(4) DEFAULT '0',
  `core-project-add` tinyint(4) DEFAULT '0',
  `core-project-edit` tinyint(4) DEFAULT '0',
  `core-project-delete` tinyint(4) DEFAULT '0',
  `core-project-assign` tinyint(4) DEFAULT '0',
  `core-project-unassign` tinyint(4) DEFAULT '0',
  `core-activity-add` tinyint(4) DEFAULT '0',
  `core-activity-edit` tinyint(4) DEFAULT '0',
  `core-activity-delete` tinyint(4) DEFAULT '0',
  `core-activity-assign` tinyint(4) DEFAULT '0',
  `core-activity-unassign` tinyint(4) DEFAULT '0',
  `core-user-add` tinyint(4) DEFAULT '0',
  `core-user-edit` tinyint(4) DEFAULT '0',
  `core-user-delete` tinyint(4) DEFAULT '0',
  `core-user-assign` tinyint(4) DEFAULT '0',
  `core-user-unassign` tinyint(4) DEFAULT '0',
  `core-group-edit` tinyint(4) DEFAULT '0',
  `core-group-delete` tinyint(4) DEFAULT '0',
  `ki_timesheets-otherEntry-ownGroup-add` tinyint(4) DEFAULT '0',
  `ki_timesheets-otherEntry-ownGroup-edit` tinyint(4) DEFAULT '0',
  `ki_timesheets-otherEntry-ownGroup-delete` tinyint(4) DEFAULT '0',
  `ki_expenses-otherEntry-ownGroup-add` tinyint(4) DEFAULT '0',
  `ki_expenses-otherEntry-ownGroup-edit` tinyint(4) DEFAULT '0',
  `ki_expenses-otherEntry-ownGroup-delete` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`membershipRoleID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=6 ;

--
-- Daten für Tabelle `kimai_membershipRoles`
--

INSERT INTO `kimai_membershipRoles` (`membershipRoleID`, `name`, `core-customer-add`, `core-customer-edit`, `core-customer-delete`, `core-customer-assign`, `core-customer-unassign`, `core-project-add`, `core-project-edit`, `core-project-delete`, `core-project-assign`, `core-project-unassign`, `core-activity-add`, `core-activity-edit`, `core-activity-delete`, `core-activity-assign`, `core-activity-unassign`, `core-user-add`, `core-user-edit`, `core-user-delete`, `core-user-assign`, `core-user-unassign`, `core-group-edit`, `core-group-delete`, `ki_timesheets-otherEntry-ownGroup-add`, `ki_timesheets-otherEntry-ownGroup-edit`, `ki_timesheets-otherEntry-ownGroup-delete`, `ki_expenses-otherEntry-ownGroup-add`, `ki_expenses-otherEntry-ownGroup-edit`, `ki_expenses-otherEntry-ownGroup-delete`) VALUES
(1, 'Admin', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
(2, 'User', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(3, 'Groupleader', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1),
(4, 'User', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(5, 'Groupleader', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
´

**Comment by simonschaufi** [comment]
@holgerpopolger the version number is not so interesting, more interesting is the database version number behind (4 digits)

**Comment by holgerpopolger** [comment]
The old database is show on the top:
-- phpMyAdmin SQL Dump
-- version 3.4.11.1deb2+deb7u4

in the new database i find this info:
phpMyAdmin 3.4.11.1deb2+deb7u4 / MySQL 5.6.29-76.2-log

Is this helpful?

**Comment by simonschaufi** [comment]
no, not at all. We need to know the kimai database version that needs migrations. It's the number behind 1.9.x in the login panel

**Comment by holgerpopolger** [comment]
the thing is i had to move from an old server to a new one. the old one is not running anymore so that i can't lookup the login panel. is there another way to find out?

**Comment by simonschaufi** [comment]
```
SELECT `value` FROM `kimai_configuration` where `option` = 'revision'
```

**Comment by holgerpopolger** [comment]
![bildschirmfoto 2016-07-19 um 18 50 54](https://cloud.githubusercontent.com/assets/20519821/16958668/c09bf06e-4de1-11e6-90b5-15457948372b.png)
 is this correct?

**Comment by simonschaufi** [comment]
I think you are one in a million users who had problems with previous migrations:
Please execute:
```
ALTER TABLE `kimai_membershipRoles` ADD `core-user-view` tinyint DEFAULT 0 AFTER `core-user-unassign`;
```
which actually should be there since [r1374](https://github.com/kimai/kimai/blob/master/updater/updater.php#L1067)

**Comment by holgerpopolger** [comment]
Cool, that worked fine. 

But now I am not able to login. All User/Passwords Combinations are not working anymore. Also when I change the 'password' column in database. Any Idea?

**Comment by simonschaufi** [comment]
make sure that the secret key in the autoconf file is the same as before. that is used to hash the passwords. if you want to generate a new pw, the code is:
```
md5(hash + pw + hash)
```

**Comment by holgerpopolger** [comment]
Thanks a lot Simon & Kevin! Kim works fine now!

**Comment by simonschaufi** [comment]
great.

**Comment by ShortBuss** [comment]
Hello-

I see this thread is closed, hoping this gets seen. If not I'll create a new post.
I installed Kimai development version 0.9.3.1380 way back in 5/2013 & it's been great! I need to update because of depreciated php 5.6. I'm planning on updating to 1.3 for a stable version before I up the php to 7.1. At time of v2 update I'll up to php7.2 or 7.3.
Today I had the same problems as the OP, the 2 items (UPDATE kimai_membershipRoles SET core-user-view = 1 WHERE name = 'Admin'; UPDATE kimai_membershipRoles SET core-user-view = 1 WHERE name = 'Groupleader';) in red.

Do you think the above action will help me?

Thanks in Advance
Karl
