### ISSUE TITLE
Start logging without a chosen activity

### ISSUE THREAD

**Issue by Kayakflo** [kimai/kimai#752]
I would like to know whether it is possible to start logging (call it "Quick Timetracking") without choosing an activity in before.

In case this is not possible, I would be grateful for any information regarding a "default activity" aka, how to set a users default project / activity combination to one specified by me as an admin.

Thanks a lot in advance!

**Comment by simonschaufi** [comment]
The way how kimai works i always a combination of  somebody to work for (customer), a project (group of tasks) and a single task what you are currently doing. Anything else doesn't make sense.

If you just want to create a default task, create a task and don't assign it to a project. Then it is always available for all projects.
