### ISSUE TITLE
"Eintrag bearbeiten" / "Editing Entries" ok Button doesn't work

### ISSUE THREAD

**Issue by SavGuard** [kimai/kimai#754]
#### Expected behaviour
OK-Button writes the changes and quit the windows

#### Actual behaviour
OK-Button does nothing - other OK-Buttons works fine!
testet with different actual browser. 

#### Steps to reproduce the behaviour
I have seen the Bug #731 and #749 but i use the latest master and develop version but no change,
the button do nothing. I get an Error log in the Webserver Log, for each click he wrote:
[Tue Jul 26 13:08:02.016829 2016] [:error] [pid 9960] [client 192.168.30.36:54925] PHP Fatal error:  Class 'DOMDocument' not found in /var/www/html/kimai/libraries/zendframework/zendframework1/library/Zend/Xml/Security.php on line 82, referer: http://dssweb01/kimai/core/kimai.php

#### Kimai version
1.0.1.1388 "dev"

#### Relevant log entries from Kimais Debug tab
[26.07.2016 13:08:02] KSPI axAction (admin): add_edit_timeSheetEntry
[26.07.2016 13:07:58] KSPI axAction (admin): reload_activities_options
[26.07.2016 13:07:58] KSPI axAction (admin): add_edit_timeSheetEntry

thank you, Sav

**Comment by simonschaufi** [comment]
Duplicate to #706
