### ISSUE TITLE
var.total includes VAT

### ISSUE THREAD

**Issue by arnadan** [kimai/kimai#756]
#### Expected behavior
When using [var.total] in an invoice the amount **without** VAT should be printed there.

#### Actual behaviour
When using [var.total] in an invoice the amount **including** VAT is printed there.

#### Steps to reproduce the behavior
Create a bill using the VAT template.

#### Kimai version
Don't know where to find the version.

**Comment by kevinpapst** [comment]
Please include the version from Login Screen or Help Dialog.

**Comment by arnadan** [comment]
Version from Login Screen: Kimai 1.0.1.1388 

Somehow I seem to be too stupid to find the help screen......

**Comment by kevinpapst** [comment]
Hey, thanks for the reminder!
I forgot to update the documentation after the last release...
var.total is the total invoice sum including vat
Use var.amount for the sum without vat.
I will come back to you, after the documentation has been updated.

**Comment by kevinpapst** [comment]
Let me know if the new documentation is correct: http://www.kimai.org/documentation/developer/invoice-templates.html

**Comment by arnadan** [comment]
Thank you for the update. The documentation is now correct.

Daniel
