### ISSUE TITLE
New version does not encode umlaut (äöü) in projects table after update

### ISSUE THREAD

**Issue by felixkretschmer** [kimai/kimai#757]
#### Expected behaviour
Project Name is shown in WebGUI
#### Actual behaviour
Project Name is empty, but project exists as row
Project Name is shown via phpmyadmin
#### Steps to reproduce the behaviour
Put an umlaut (äöü) and just confirmed "ß" as well in a project name
#### Kimai version
Update from v0.9.3.1384 to v1.0.1.1388
#### Relevant log entries from Kimais Debug tab
none
#### Work around/ solution
Changed all project names to:
ä -> ae
ö -> oe
ü -> ue

**Comment by kevinpapst** [comment]
I cannot reproduce that one demo.kimai.org

Check https://github.com/kimai/kimai/blob/master/includes/vars.php and try to switch the utf-8 flag.

**Comment by felixkretschmer** [comment]
Solves the problem. Thanks.
