### ISSUE TITLE
ldapadvanced | use commonNameAttribute instead of usernameAttribute with Enhanced Identity Privacy enabeld

### ISSUE THREAD

**Issue by felixkretschmer** [kimai/kimai#758]
#### Expected behaviour
Show logged in user with username. Add users to groups.
#### Actual behaviour
Our Active Directory has encrypted cn entries (= some UUID) for privacy reasons. So the actual username is just written as the uid or sAMAccount attribute.
The ldapadvanced Authenticator uses usernameAttribute to show the username and resolve group membership.
I'd like to use the commonNameAttribute as username and the usernameAttribute only to resolve group memberships.
Reason: Now I see: "Logged in as: 4a12345-bb431-d42156-a445-1326549852" after I logged in with my readable username: "fkr". I'd like to see "fkr" there as well as an the users table for admins to edit my rights.
#### Steps to reproduce the behaviour
Use Active Directory with "Enhanced Identity Privacy"
#### Kimai version
v1.0.1.1388
#### Relevant log entries from Kimais Debug tab
The funny thing is, that the log registers the logged in user as: 
login: fkr as user

**Comment by felixkretschmer** [comment]
Work around:
Modify ldapadvanced.php in Line 360:
`$check_username = $this->forceLowercase ? strtolower($uidAttribute) : $uidAttribute;`
To:
`$check_username = $this->forceLowercase ? strtolower($username) : $username;`

I am too less of an PHP developer to realize if this is a permanent solution and can be committed to the master.

**Comment by kevinpapst** [comment]
Sounds like a special case for your company. I would create a subclass of ldapadvance, overwrite that method where you did the patch and register that new class in your autoconf as authenticator.
This way you won't loose your changes with an update.

**Comment by felixkretschmer** [comment]
Well, it's a Microsoft Active Directory Feature. But yeah, will be a solution. Thanks

**Comment by kevinpapst** [comment]
Hey Felix, if you provide the code of your adjustments, we can put it in the Kimai repository.
You don't have to worry about updates and we have an AD implementation.
Is the AD used in a "default" way? I don't have access to test one, otherwise I would implement it by myself...

**Comment by felixkretschmer** [comment]
Hi Kevin,
yes, it is used in a default way with the option "Enhanced Identity Privacy" (https://technet.microsoft.com/en-us/library/f351e0e3-6c78-49dc-9b0f-2b24e1b7411c) enabeld.

The adjustments I did were in my own subclass copied from Ldapadvanced.php
Original Ldapadvanced.php:
```
// User is authenticated. Does it exist in Kimai yet?
$check_username = $this->forceLowercase ? strtolower($uidAttribute) : $uidAttribute;
```
My Adjustments in MyAuth.php:
$check_username = $this->forceLowercase ? strtolower($username) : $username;

I am not sure if this will work after an update for previous installations. On the other side, die allowed usernames can be adjusted by the userfilter.
