### ISSUE TITLE
Missing Documentation/Restore Forum

### ISSUE THREAD

**Issue by tjarkrasche** [kimai/kimai#759]
I know this is not a typical Code Issue, which should be discussed on Github. But I would find it kind of helpful when the Forum would still be online in a  readonly version.

A lot of the documentation is missing in the official version, but it seems to me like their was a lot of it posted in the forum, as many articles and search results reference it. 

I would love to contribute to the documentation but at the moment their is almost no source were a newbie could get infomrations about Kimai, especially about the Kimai API.

I think it would be very helpful if the subdomain forum.kimai.org wouldn't be simply redirecting to Github, but if it would be a readonly version of the forum with the advice to use Github for further issues.

**Comment by kevinpapst** [comment]
Hey, let me think about it. I will see, if I can provide a read-only version.

**Comment by tjarkrasche** [comment]
Thank You!

Yeah, I'm new to Kimai and it's really difficult for a developer to use the API without Documentation and quite depressing because basically every link which sounds like a good source links to the Forum which is redirecting to Github.

I'm sure a lot of other People who are new to the Project would appreciate this to.

**Comment by kevinpapst** [comment]
Okay, I re-activated the forum. I will not link it from anywhere and you cannot register.
But you can read. I would be happy, if you ask questions here and remind us every time to improve the documentation ;-) 
As developer you might know how hard it is to write documentation, especially if nobody asks for it....
