### ISSUE TITLE
Could you please set up an English Demo version?

### ISSUE THREAD

**Issue by stretchr-xx** [kimai/kimai#762]

**Comment by kevinpapst** [comment]
The demo is in english, unless someone testing it reconfigured the demo to use another language.
You can always log in as admin - see http://www.kimai.org/demo/ and change the global language to english. Or you change your user account to english.
Either way, Kimai is multi language.

**Comment by stretchr-xx** [comment]
Changed to America/New York but is still in German.
Daniel Lackey

Quoting Kevin Papst <notifications@github.com>:
