### ISSUE TITLE
Adding groups not working

### ISSUE THREAD

**Issue by actionDOTch** [kimai/kimai#764]
Hi all,

After installing Kimai I wanted to enter customers - not possible, because groups were missing. Entering new groups and klicking on "add group" did not produce a result.

Open Kimai, click on "Admin Panel", klick on "Groups", enter new group name and click on "Add group".

Kimai version 1.0.1.1388

Incidentally, I cannot enter new users either - after clicking on "add user" I get the message "Permission denied". 

Thanks in advance for your much appreciated help!

Regards, Joerg

**Comment by actionDOTch** [comment]
Additional find, while waiting for a sign of life - Log entry:

[09.08.2016 17:10:32] get_groups: Access denied for user 'vsite_xxxxxx'@'127.0.0.1' to database 'xxxxx' (#1044)

**Comment by kevinpapst** [comment]
So, there is a problem with your database, which we can't solve.
Can you enter any data? Timesheet entries, user, projects, tasks?

**Comment by actionDOTch** [comment]
Thank you very much for your time and insight, Kevin

Timesheet = yes, data entry possible
Invoice = yes, creation of word document possible
Admin panel = no, error message: access denied
Export = yes (PDF, XLS, CSV, Printer)
Expenses = yes, data entry possible
Customers = no, message: At least one group has to be selected
Projects = no, message: see above
Activities = no, message: see above

Through Admin Panel:
Customer = no, message: At least one group has to be selected
Projects = same as above
Activities = same as above
Users = same as above
Groups = no reaction visible (entry in log = [09.08.2016 17:10:32] get_groups: Access denied for user 'vsite_xxxxxx'@'127.0.0.1' to database 'xxxxx' (#1044)

Global roles = yes, data entry possible
Membership roles = yes, data entry possible
Status = yes, data entry possible

Are these information helpful or do you want me to elaborate?

Kind regards, Jörg

**Comment by kevinpapst** [comment]
Sounds highly akward. You have to fix these datasbe permissions, before we can proceed with searching for errors in Kimai.
Did you install Kimai from scratch or was it an update?

**Comment by actionDOTch** [comment]
installation from scratch on Blue Onyx with PHP 5.6, no errors during installation, mobile add-on installed ok as well

**Comment by actionDOTch** [comment]
Success! Thank you very much for your hint, Kevin!!

What I did:
opened the database with phpMyAdmin and granted the necessary rights to the user in question ... hey presto, job done!!!

I'll check that everything works and get back to you in a couple of minutes :-)

**Comment by actionDOTch** [comment]
Works like a charm, Kevin

Almost ... I still can't create new users, all other topics work fine!

**Comment by kevinpapst** [comment]
Thats weird, but glad we could solve the first problems :)
Can you access the server logs as well? Sometimes there are more errors visible than in the Kimai log.

**Comment by actionDOTch** [comment]
Yes. Server logs show creation of user:

[10.08.2016 12:47:56] KSPI axAction (admin): createUser
[10.08.2016 12:48:24] KSPI axAction (admin): createUser

Error message "Access denied" ist still active.

**Comment by kevinpapst** [comment]
Is that a Javascript alter message? 
Please check the network tab and see if there is a proper request / response?
Are you using the automatically created admin account? If not that could that be a permission problem inside Kimai as well...

**Comment by actionDOTch** [comment]
![kimai-1](https://cloud.githubusercontent.com/assets/20865694/17552229/fbd9b2e6-5efe-11e6-8f91-7945114ad49a.JPG)

Yes, Kevin ... seems like a javascript message (see above)

Yes, as this automatically created admin account is actually the one and only ... as new users are still far away :-)

**Comment by kevinpapst** [comment]
That looks like the Kimai debug logs, not server logs.
I have the slight feeling, that your database installation did not work properly. Every user is checked the same way, so this might happen due to improper permission settings in Kimai.
Please open "Administration" > "Membership roles" > "Admin" > "Permissions" and see if all checkboxes are checked.

**Comment by actionDOTch** [comment]
![kimai-2](https://cloud.githubusercontent.com/assets/20865694/17559577/fda2a93c-5f1e-11e6-9871-030f060cf90e.JPG)

Done - ALL boxes are checked. Still, the same error is displayed.

**Comment by kevinpapst** [comment]
Does your admin user look like this:
<img width="977" alt="bildschirmfoto 2016-08-11 um 01 02 04" src="https://cloud.githubusercontent.com/assets/533162/17572829/4bdbd264-5f5f-11e6-8947-49cdfd64d30f.png">
?

**Comment by actionDOTch** [comment]
![kimai-3](https://cloud.githubusercontent.com/assets/20865694/17577589/d471eb02-5f7f-11e6-9219-0c9fd0b82665.JPG)

Yes, all other columns are set to "1" as well.

**Comment by kevinpapst** [comment]
Still a mystery why the user had wrong group assignment ... but hey, glad we could solve the problem.

**Comment by skylord123** [comment]
I just wanted to post this in case someone else runs into this issue:

Groups were not displaying for me at all anywhere. I ended up debugging the code and found out the user I was using for kimai on mysql didn't have access to lock tables. If the table cannot be locked then the get_groups function will return false causing no groups to be displayed.

So if anyone else runs into this issue of groups not displaying check the database user kimai is using and make sure it has access to lock tables (I transferred kimai from one host to another and missed this check).

**Comment by francwalter** [comment]
@skylord123 you are my evening hero :)  Thank for this hint.
I as well had emtpy group field and php_errors as e.g.:

```
Invalid argument supplied for foreach() in /var/www/7fw.de/kimai/includes/func.php on line 151
array_intersect(): Argument #2 is not an array in /var/www/7fw.de/kimai/includes/func.php on line 510
Undefined index: customerGroups in /var/www/7fw.de/kimai/core/processor.php on line 279
```

So I looked into webmin ( I use that tool to check db permissions) and voila, that was it. I was to tight-assed, when I granted the permissions to my kimai user :)
Thanky!!!
frank

PS.: I have kimai2 already installed and running, imported the data from kimai but still using that old kimai :)
Fully enough for my single use case :)
