### ISSUE TITLE
Problems with the < OK > button and the editing of entries

### ISSUE THREAD

**Issue by Ruckhaber** [kimai/kimai#766]
I used the version 0.9.x and everything worked. After the update to version 1.0.1 the problems started.
When I log in as user, I can create entries for time recording. If I want to edit the entries , a window is opened for editing, but the window can only be closed with the Cancel button and not with the OK button. The OK button has no function. The changes are not accepted.
When I log in as admin, I can, for example, create a new user, but the user is automatically an admin. I cant not change to profile "User"
The same errors also occur in a new installation with new database .

Kimai 1.0.1.1388
MySQL-Server 5.5.27
PHP Version 7.0.7

**Comment by kevinpapst** [comment]
Hi, please test it in the demo version. If errors do not occur there, you can either update to the "develop" version or post more infos, like log messages.

**Comment by simonschaufi** [comment]
@kevinpapst I'm running kimai with php7 successfully.

**Comment by Ruckhaber** [comment]
Hi, now I use die latest development version. I could modify a entries for time recording as user admin.
I checked the logfile. I think that was the problem in Version 1.0.1 : `Uncaught exception: Could not determine temp directory, please specify a cache_dir manually` 
But there are a few other problems exist. It takes very long to update a filter. A progress bar will appear and then…sometimes waiting, waiting. If I reload the browser window I get the message `[object Object],`
If I wait I get the message `[object Object], <checkbox> Tabs mit 192.168.1.2 in den Vordergrund holen, wenn diese einen Dialog anzeigen`. 
The logfile shows:
 `[10.08.2016 10:30:47] KSPI axAction (admin): reload
[10.08.2016 10:35:47] KSPI axAction (admin): reload_exp
[10.08.2016 10:35:48] KSPI axAction (admin): reload_timeSheet`

**Comment by kevinpapst** [comment]
Sounds as if the original problem was solved. Please create a new issue for another problem (and try to include more infos).
If something is slow, first check the network tab if the request needs to long or if some javascript is running wild. If you have a huge amount of data, that might be a problem as well. We need more infos in the new issue.
