### ISSUE TITLE
'Show daily stats in timesheet' for all users individually (rows wise) in a unified view which is exportable

### ISSUE THREAD

**Issue by rarvin** [kimai/kimai#766]
**Is your feature request related to a problem? Please describe.**
I could see that in the development version you have added the option allowing the admin user to view the summarised statistical summary of each user individually. A feature requested is if we could have a summarised view of one users time in daily, weekly, monthly fasion but the same report view must include similar summary of all other users. That is if there are 5 users in kimai then it would be good to see the summary of that users daily time as one row, followed by the summary of the second user, followed by the summary of the next user and so on.

one view for daily weekly and monthly times where we can summarise by user, more like a group by user option.  

**Describe the solution you'd like**
A group by report by user but one report to show all users data in a single view but as individual records when logged in as the admin user.

Any manual way of doing this if you can think of something I can try that too. If there is some way of creating reports in kimai if you can guide me i could try. But I am not a programmer. I could see that in the widgets you have some kind of fucntions where you collect such data so that you can populate the results for the dashboard. Something similar by for all users would be good, but in one view. Currently this is limited to each users login screen (Show daily stats in timesheet).

**Describe alternatives you've considered**
None available, need to extract the data and create a pivot table in an excel sheet and try summarising, but due to the timevalue formats etc, summarising the data is very difficult.

**Additional context**

**Comment by rarvin** [comment]
Giving some examples of reporting functionality from the clockify application

![Screenshot_20190617_162326](https://user-images.githubusercontent.com/50443902/59599715-de86d180-911c-11e9-8fff-570ffc457a99.png)

Please see the following link https://clockify.me/feature-list
Summary report which would give you better idea of filtering and group by reports.

**Comment by relume** [comment]
Hello

I hope my feature request is related to this feature request.

**Is your feature request related to a problem? Please describe.**

- In Kimai < v1.0 as administrator I could see in the time reporting for every user or selected users a statistic summary of workhours. 
- In Kimai > v1.0 (actually v1.3) this information is missing in time reporting and exporting section (preview) but is available only on MyTime section.

**Describe the solution you'd like**

- As administrator I would like to have in the time reporting and exporting section a statistic summary rown  as it is available on the MyTime section.
- The above clockify example would be nice, but a single simple statistic row would be also very much appreciated.

Many thanks in advance.

**Comment by kevinpapst** [comment]
Nowadays available in the reporting section.
