### ISSUE TITLE
wrong standard time in REPORT

### ISSUE THREAD

**Issue by chougula** [kimai/kimai#770]
#### Expected behaviour
when i take the report for the project/user it should give the correct standard/decimal time of user/project.
#### Actual behaviour
in my case decimal time is correct but standard time id only its giving completely wrong so please check the issue.

**Comment by kevinpapst** [comment]
Can you provide your configuration, your export settings and some screenshots, so we know better what is wrong?

**Comment by chougula** [comment]
this are the reports using decimal and standard time.....



![standard_time](https://cloud.githubusercontent.com/assets/20458913/17585338/c74f13a6-5fd8-11e6-9ef4-4fb0de50b901.PNG)
![decimal_time](https://cloud.githubusercontent.com/assets/20458913/17585339/c75014f4-5fd8-11e6-9e61-ec72665f424e.PNG)

**Comment by claudegel** [comment]
The problem is with gmdate(). I've just sent a PR to fix it. now the summary total should show the correct time in std-time and decimal time

**Comment by kevinpapst** [comment]
I guess this was the PR that @claudegel referred to: #775 
It was merged into develop branch, so I close this ticket.
@chougula Please test it and let us know if it fixes your problem :)
