### ISSUE TITLE
Admin Panel Advanced needs double Save

### ISSUE THREAD

**Issue by HenryNe** [kimai/kimai#773]
#### Expected behaviour

A click on the button "Save" should store and view the changes.
#### Actual behaviour

After the first click on "Save" button, changes on drop down boxes are not changed.
After the second click on "Save" button, the changes are displayed correctly.
Changes in input fields are changed on the first click on "Save".
#### Steps to reproduce
- Login as admin
- open Admin Panel Advanced
- Change "Language" to "de", "time zone" to "Europe/Paris" and an input field "Currency Symbol" to "Euro"
- Click "Save"
- Only the input field "Currency Symbol" was changed.
- "Language" and "time zone" views the old value.
- Click "Save" again, without touch or change the drop down boxes "Language" and "time zone"!
- The drop down boxes "Language" and "time zone" view the correct values now.

PS: The first click on "Save" stores the value correctly. You can verify it by a logout and login after the first "Save".
#### Reproducable on demo.kimai.org?

yes
#### Kimai version

[version] => 1.0.1
[revision] => 1388
#### Relevant log entries from Debug tab

[12.08.2016 14:53:18] text: test end
[12.08.2016 14:53:18] KSPI axAction (admin): shoutbox
[12.08.2016 14:52:24] KSPI axAction (admin): sendEditAdvanced
[12.08.2016 14:50:43] KSPI axAction (admin): refreshSubtab
[12.08.2016 14:50:43] KSPI axAction (admin): refreshSubtab
[12.08.2016 14:50:43] KSPI axAction (admin): refreshSubtab
[12.08.2016 14:50:18] text: test midle
[12.08.2016 14:50:18] KSPI axAction (admin): shoutbox
[12.08.2016 14:50:09] KSPI axAction (admin): sendEditAdvanced
[12.08.2016 14:49:25] KSPI axAction (admin): refreshSubtab
[12.08.2016 14:49:25] KSPI axAction (admin): refreshSubtab
[12.08.2016 14:49:25] KSPI axAction (admin): refreshSubtab
[12.08.2016 14:49:23] text: test start 
#### Tested Browsers

Mozilla Firefox 45.0.2
Google Chrome 52.0.2743.116 m (64-bit)
Microsoft Edge 25.10586.0.0

**Comment by simonschaufi** [comment]
I cannot reproduce it on demo. Data is saved, kimai is reloaded. I think you have some browser settings that affect kimai.

**Comment by simonschaufi** [comment]
Ok the time zone is not properly reloaded. but language works for me.

**Comment by HenryNe** [comment]
There are 3 drop down boxes. Try to change all at same time. Timezone sometimes works on browser Microsoft Edge. Most problems I have with Google Chrome.

**Comment by lcgauthier** [comment]
i tried chrome and i tried edge,  i cannot make any change to the advanced tab

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
