### ISSUE TITLE
Problems with the user management

### ISSUE THREAD

**Issue by Ruckhaber** [kimai/kimai#776]
I have been releasing a new installation of kimai. I logged in as admin and change to the admin panel. Next , I created a new user. The new user is automatically an admin. I can not change the global role of the new user. I can also not set a password for the new user:

Reproducable on demo.kimai.org? [no] admin panel unreachable

Kimai version [dev 1.0.1.1388| develop]

**Comment by kevinpapst** [comment]
Try admin/changeme via http://demo.kimai.org directly. I could change the global role of a user.
Did not test the rest though. Please do so and which PHP version are you using?

**Comment by Ruckhaber** [comment]
Now it works on http://demo.kimai.org. I am using PHP version 7.0.9 on a windows server 2008 with IIS7.

**Comment by Ruckhaber** [comment]
Why the entry will be closed ? User management is working on http://www.kimai.org/demo/ but not on my local installation.

**Comment by simonschaufi** [comment]
You just said it yourself: it is working on demo! If it is not working for you, you first need to find the problem on your side.
