### ISSUE TITLE
Excel does no longer open xls files exported from Kimai

### ISSUE THREAD

**Issue by Stadly** [kimai/kimai#779]
The xls-files exported by Kimai can no longer be opened in newer versions of Microsoft Excel. With a security patch released 2016-07-12, Excel changed it's behavior to not open html files origination from the Internet. It does not even show a warning. See [StackOverflow](http://stackoverflow.com/questions/38377796/export-html-table-to-excel-doesnt-open-in-office-2010) for details and how to work around the problem.

Maybe it is time to change the export function to create proper xlsx-files instead of a html table? At least I think the file would then open in Excel without problems. I have not tested this, though.

#### Expected behaviour
The exported file is opened in Excel.

#### Actual behaviour
The exported file is not opened in Excel.

#### Steps to reproduce
1. Make sure you have the latest version of Microsoft Excel
2. Track some time in Kimai
3. Export to XLS
4. Open the exported file in Excel - nothing happens

#### Reproducable on demo.kimai.org?
yes

#### Kimai version
1.0.1.1388

**Comment by simonschaufi** [comment]
in the dev branch we already merged a commit that uses PHPExcel. Since I don't have Excel 2010 i cannot test it. Use Openoffice or Libreoffice instead for now or change the setting in Excel ;)

**Comment by Stadly** [comment]
Great! Is there a live demo using the latest dev-version? Then I can easily confirm whether using PHPExcel solves the issue.

**Comment by simonschaufi** [comment]
ups.
yes there is but I dont know if i can share it here.

**Comment by kevinpapst** [comment]
Sure. I will have a look into hosting it properly with links from the demo page and automatic user-account creation.

**Comment by simonschaufi** [comment]
I merged develop into master. Please test again!

**Comment by Stadly** [comment]
Great! Did an export from the demo.kimai.org, and the file is opened in Excel without any issues. Thanks for the good work :)

**Comment by jst2017** [comment]
simonschaufi mentioned that there is already commit in dev branch using PHPExcel to realize the Excel- Export in format xlsx. Which files must be edited / changed to change from xls export to xlsx export?
