### ISSUE TITLE
Cannot find time registration

### ISSUE THREAD

**Issue by markb81** [kimai/kimai#782]
Hi,

I'm just playing around with Kimai to get to know the product. For one project I added some time in the past (few months ago). I checked the 'paid' checkbox.

I see in the budget tab the amount is taken from the total budget. However I cannot find the time registration anywhere anymore. It's completely gone. I am logged in with the user that created it.

Other time registrations which aren't paid I can just see.

How can I view the time registration again?

Thanks!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
