### ISSUE TITLE
Unable to stop timer

### ISSUE THREAD

**Issue by Uturnadmin** [kimai/kimai#786]
Everything is running fine except I have two "clocks" running and I am unable to stop the earlier clock that does not disappear. I attach a screen shot of the lower clock still ticking and the shot does not show the current clock at the top of the page also ticking time. Can you advise how to delete the one clock please? Thx.

![snip of kimai](https://cloud.githubusercontent.com/assets/21123022/17807310/f8923150-6609-11e6-868a-452447cea8d6.JPG)

**Comment by kevinpapst** [comment]
I believe that this error could only occur in older versions. 
You can always stop it via database. 
Which Kimai version?

**Comment by Uturnadmin** [comment]
v0.9.2.1306 - © 2006-16 is the version I am using.
How do I clear it via database?

**Comment by simonschaufi** [comment]
we don't support older versions any more. please update.

**Comment by Uturnadmin** [comment]
thanks - how can I upgrade?

**Comment by simonschaufi** [comment]
read the docs!

**Comment by kevinpapst** [comment]
Hey, you can look in the database in the timesheet table for an entry where the stoptime is = 0
Sorry, I don't know the name of the column, as this version is really older.

Here is the link to the update documentation: http://www.kimai.org/documentation/installation/updates.html
