### ISSUE TITLE
Add record via +: wrong hourly rate

### ISSUE THREAD

**Issue by bgeiser** [kimai/kimai#787]
#### Expected behaviour
The hourly rate assigned to a project is shown in the budget tab and correctly recorded.

#### Actual behaviour
For (internal) projects with 0 hourly rate the rate of a previously selected project is shown in the budget tab and recorded.

#### Steps to reproduce
Add record to time sheet by clicking on +. Select a project with an hourly rate >0. Then select project with hourly rate ==0. Click on budget tab. The previous rate >0 is still shown and will be recorded

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.0.1.1388|github master|github develop]
v1.0.1.1388

**Comment by kevinpapst** [comment]
fixed in develop
