### ISSUE TITLE
Projects cannot be created with new Tasks assigned

### ISSUE THREAD

**Issue by Ruckhaber** [kimai/kimai#796]
I wanted to create a new project in the admin-Panel. I added some new activities. After pressing the OK button nothing happens. The project is not created. Only the CANCEL button works .

#### Reproducable on demo.kimai.org?
yes

#### Kimai version
dev 1.0.1.1388, github develop

**Comment by simonschaufi** [comment]
please don't modify our issue template! Add your own changes BELOW our lines!

**Comment by simonschaufi** [comment]
```
Request URL:http://demo.kimai.org/core/processor.php
Request Method:POST
Status Code:500 Internal Server Error
```
this would be a helpful information!
