### ISSUE TITLE
Cannot save Fixed rate on activity.

### ISSUE THREAD

**Issue by juhamoisio** [kimai/kimai#806]
#### Expected behaviour

Fixed rate should be saved when adding or updating activity.

#### Actual behaviour

No value has been saved. 

#### Steps to reproduce

create activity and set fixed rate.

#### Reproducable on demo.kimai.org? [yes|no]

yes

**Comment by simonschaufi** [comment]
I can confirm that and know why this bug is there. The better usage of the rates is if you assign the activity to a project and set the rate there. This should work for sure.
