### ISSUE TITLE
update an old 0.9.1.1205 version

### ISSUE THREAD

**Issue by RalfAli** [kimai/kimai#808]
#### Expected behaviour
After updating the db via http://kimai.myurl.de/updater/updater.php use kimai normally by kimai.myurl.de/index.php

I followed the instruction at http://www.kimai.org/documentation/installation/updates.html

There was no "finished update"-message!! Just many green markers.

Hope anyone can help me. Thanks in advanced.

#### Actual behaviour
although I remove the updater folder it leds to the no longer existing update-page (http://kimai.myurl.de/updater/updater.php) but without the kimai-logo.

#### Steps to reproduce
restore folder and db. overwrite with version 1.0.1. copy old autoconf.php. Start updater.

#### Reproducable on demo.kimai.org? [yes|no]
don't know

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
0.9.1.1205
#### Relevant log entries from Debug tab
don't know how to do this

**Comment by kevinpapst** [comment]
Hey, please check the file temporary/logfile.txt and send us the relevant content. 
Serach for "BEGIN update" within the file - everything below is important.

**Comment by RalfAli** [comment]
I didn't know this file. the last 4 lines are importent:

<schnipp>
[27.08.2016 11:34:23] E_WARNING require(../installer/installPermissions.php): failed to open stream: No such file or directory @/.........../kimaialt/updater/updater.php line 941
[27.08.2016 11:34:23] E_WARNING require(../installer/installPermissions.php): failed to open stream: No such file or directory 
</schnapp>

I restored the installer directory and the db. started the updater directly via http://kimai.myurl.de/updater/updater.php and all worked well.

Maybe you have to review your update notes?

thanks for your help and your exquisite software. used it since 2009 and haven't had any problems!!

**Comment by kevinpapst** [comment]
Thats true - the update docu wasn't adjusted after the latest updater changes.
Thanks for the info, I fixed it: http://www.kimai.org/documentation/installation/updates.html
