### ISSUE TITLE
 incorrect formatting when PDF Export

### ISSUE THREAD

**Issue by Ruckhaber** [kimai/kimai#811]
#### Expected behaviour

I want export saved working hours as a pdf file.
#### Actual behaviour

The export works. If the action description is very long , the description will be show in the "Duration " column. See what I mean [https://dl.dropboxusercontent.com/u/57458505/Bilder/Kimai-pdf.jpg](url)
#### Reproducable on demo.kimai.org?

yes
#### Kimai version

dev 1.1.0.1389

**Comment by simonschaufi** [comment]
I'm saying it again: DO NOT CHANGE THE ISSUE TEMPLATE!!!
Put your "yes", kimai number... BELOW the lines!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
