### ISSUE TITLE
Install Permission issue

### ISSUE THREAD

**Issue by rketcham** [kimai/kimai#813]
I am unable to install Kimai with PHP permisisons.  I set the permissions to 777 for the whole folder with no luck.  Can you please assist?  (I plan to adjust the permissions as this is a throw away install and not expect to be my final product)

[root@time html]# php --version
PHP 5.4.16 (cli) (built: Jul 22 2016 04:50:37)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

[root@time html]# httpd -v
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built:   Jul 12 2016 05:02:54

[root@time html]# uname -a
Linux myhostname 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

![image](https://cloud.githubusercontent.com/assets/21324555/18072730/06a7be80-6e26-11e6-907e-7cd1126c89b7.png)

[root@time html]# ll
total 100
-rwxrwxrwx.  1 root root 35147 Aug 23 01:03 COPYING
drwxrwxrwx.  2 root root  4096 Aug 23 01:03 core
-rwxrwxrwx.  1 root root  1422 Aug 23 01:03 error.php
drwxrwxrwx. 10 root root  4096 Aug 23 01:03 extensions
-rwxrwxrwx.  1 root root  1150 Aug 23 01:03 favicon.ico
-rwxrwxrwx.  1 root root  2604 Aug 23 01:03 forgotPassword.php
drwxrwxrwx.  2 root root  4096 Aug 23 01:03 includes
-rwxrwxrwx.  1 root root  7906 Aug 23 01:03 index.php
drwxrwxrwx.  4 root root  4096 Aug 29 20:12 installer
-rwxrwxrwx.  1 root root  4628 Aug 23 01:03 INSTALL.md
drwxrwxrwx.  2 root root    34 Aug 23 01:03 js
drwxrwxrwx.  2 root root  4096 Aug 23 01:03 language
drwxrwxrwx. 11 root root  4096 Aug 23 01:03 libraries
-rwxrwxrwx.  1 root root  1992 Aug 23 01:03 processor.php
drwxrwxrwx.  5 root root    46 Aug 23 01:03 skins
drwxrwxrwx.  4 root root    34 Aug 23 01:03 templates
drwxrwxrwx.  2 root root    22 Aug 23 01:03 temporary
drwxrwxrwx.  2 root root  4096 Aug 23 01:03 updater

Thank you for the support.

**Comment by simonschaufi** [comment]
This has nothing to do with kimai. please ask in linux forums.

**Comment by rketcham** [comment]
Love to, but the forums reflect:
This forum will be shut down soon and runs in read-only mode! 

Please go to our GitHub page for any question or support issue

**Comment by rketcham** [comment]
Please reopen this...

**Comment by simonschaufi** [comment]
This is the wrong place for "how to setup a webserver". if php can't write a file, it's your fault, not kimai's
