### ISSUE TITLE
V 1.0.1 how to disable the red line between overlapping entrys. 

### ISSUE THREAD

**Issue by maikl-swiss** [kimai/kimai#815]
Hello Team 

after the update to V1.0.1 i noticed the red lines showing overlapping times in the timtable. 
I often have this and rly like to remove the red line. 

Can someone point me how to disable it?

Best Regards
and thx
maikl

**Comment by simonschaufi** [comment]
look inside your user settings. there is a setting for it.

**Comment by maikl-swiss** [comment]
that was my first thought but im not able to find something. 

Only this: 
Draw a line between entries of different days.
Draw a line between two records that are not perfectly continuous. 
But that will not affect the red line. 


![redline](https://cloud.githubusercontent.com/assets/21668558/18171017/bb7cf622-7060-11e6-998a-8728e440e058.PNG)

**Comment by kevinpapst** [comment]
Check the users preferences: "List" => "Don't indicate time overlap of
entries"

2016-09-01 15:37 GMT+02:00 maikl-swiss <notifications@github.com>:

**Comment by maikl-swiss** [comment]
Now i see the problem, i tried this before but when i check the box it does not save.
All settings under "user preferences" seams not to work. 

Any idea why? 

thx
maikl

**Comment by simonschaufi** [comment]
Maybe the same problem like here? #738

**Comment by maikl-swiss** [comment]
i made the changes in extensions/ki_adminpanel/processor.php but still same behavior. 
Maybe i made something wrong - not a programmer myself. 

Where are the error logs saved pls.

**Comment by simonschaufi** [comment]
check debug tab or temporary folder.

**Comment by maikl-swiss** [comment]
within the temp folder i found logfile.txt
last entries 
don't know if this is correct? 

[02.09.2016 13:31:30] login: admin as user
[02.09.2016 13:31:40] KSPI axAction (admin): prefs
[02.09.2016 13:31:50] KSPI axAction (admin): editPrefs
[02.09.2016 13:31:50] remove_rate: Unknown column 'userID' in 'where clause' (#1054)

thx maikl

**Comment by simonschaufi** [comment]
Does your kimai_rates table have a column "userID"?

**Comment by maikl-swiss** [comment]
The title is irritating bec. it's not only the red line, the whole preferences aren't editable. 

Please lets comment only in this issue #826
