### ISSUE TITLE
A button "yesterday" for quick selection of date

### ISSUE THREAD

**Issue by klemensz** [kimai/kimai#816]
Feature request: It would be really nice to have a button "yesterday" when adding or a new record or editing one. Because (at least from my usage patterns) you often want to create new time entries for the last day. Then you need several clicks to select both the start date and the end date. It could look similar as the "Current time" ("Aktuelle Zeit") link next to the time selection.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
