### ISSUE TITLE
cannot create new customer

### ISSUE THREAD

**Issue by piflixe** [kimai/kimai#817]
#### Expected behaviour
click on "add customer"  button in admin or timesheet view opens a window to fill out details
#### Actual behaviour
no window opens, new customer cannot be created
#### Steps to reproduce
click on button
#### Reproducable on demo.kimai.org? [yes|no]
no
#### Kimai version 
dev 1.1.0.1389|github master
moved installation to different server, works in same version (after upgrade) on old server, doesn't work on new server
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
I don't see a logentry with that timestamp, neither in the debug tab nor in the logfile

**Comment by piflixe** [comment]
I figured by trying a fresh install that the php dom module was missing. I could fix this on ubuntu xenial by installing
`sudo apt-get install php-xml`
`systemctl restart apache2`

**Comment by kevinpapst** [comment]
Thanks for posting the fix!
