### ISSUE TITLE
Round time feature

### ISSUE THREAD

**Issue by l0co** [kimai/kimai#82]
This is a feature request.

For some kinds of project Tasks it would be nice to have an option "Round time to..." with choice among some predefined values: 10 min, 15 min, 30 min, 1 h. This would be useful to trace the time spent on support with specific support contract, where customer pays eg. for each started 15 min or 1 h of support team work.

I'm new to Kimai so maybe there's another way to achieve it (?)

**Comment by kevinpapst** [comment]
This is very old and Kimai has an rounding option. If that is not enough, please open a new issue for dicussion.
