### ISSUE TITLE
Not able to change preferences / v1.1.0.1389

### ISSUE THREAD

**Issue by maikl-swiss** [kimai/kimai#826]
#### Expected behaviour
im not able to change anything in the preferences after Update 

#### Actual behaviour
If i try to change something in the preferences, and press ok, the window close and nothing happen.

#### Steps to reproduce
Update Kimai 0.9?? to V1.1.0 with auto update process
I had to alter the table before i started the auto update 
USE kimai;
ALTER TABLE kimai_exp ADD KEY (exp_ID);

Update without error messages.

#### Reproducable on demo.kimai.org? [yes|no]
no 
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.0.1.1388 - © 2006-16 by the Kimai-Team: 

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[06.09.2016 10:06:41] login: admin as user
[06.09.2016 10:06:42] KSPI axAction (admin): securityWarning
(installer folder still there) 
[06.09.2016 10:06:49] KSPI axAction (admin): prefs
[06.09.2016 10:06:52] KSPI axAction (admin): editPrefs
[06.09.2016 10:06:52] remove_rate: Unknown column 'userID' in 'where clause' (#1054)
[06.09.2016 10:06:53] KSPI axAction (admin): securityWarning
I tried to find a solutions but wasn't able to. 

On my way to find the issue i made a new installation auf kimai 1.1.0 and it works well. 
I can change skin etc. 

After that, i made an export of the Database of my old/updated Kimai and imported it into the new installation /new DB.

Under autoconfig i had to change the salt key. But than login was ok

... but again im not able to change preferences. 

I tried diff. browser and cleared cache - also i tried private session. Nothing. 

Hope someone can help me. 
Best regards
maikl

**Comment by simonschaufi** [comment]
Hi Maikl, please respect our issue template. It's there for a purpose. Please edit your issue and use the template (Copy it from [here](https://github.com/kimai/kimai/blob/master/.github/ISSUE_TEMPLATE))

**Comment by simonschaufi** [comment]
relates to #815

**Comment by simonschaufi** [comment]
Does your kimai_rates table have a column "userID"?

**Comment by maikl-swiss** [comment]
Will update my first post to meet the template. 

kimai_rates has a column user_id  (wonder if it is ok that there are many NULL entries. 

i.E:
user_id 	project_id 	event_id 	rate 	
NULL	NULL	2 	160.00
128434339 	NULL	2 	160.00
NULL	NULL	3 	160.00
128434339 	NULL	3 	160.00
128434339 	2 	NULL	160.00
NULL	1 	NULL	160.00
190825293 	NULL	NULL	160.00

**Comment by simonschaufi** [comment]
ok, that table looks totally wrong.
Somehow you didnt migrate the following migration:

https://github.com/kimai/kimai/blob/master/updater/updater.php#L826-L830

are the other tables correct in this revision migration?

Please do the migration manually and then check if everything is fine.

**Comment by maikl-swiss** [comment]
did i say  im not a programmer.... to much for me :) 
I still have running the original DB with kimai.0.9.2.1306  i will create a copy and restart the full update. 
Maybe better than trying to find an error now ... 

Last time i wrote one step down ... don't know if there is the whole error ....
Before you visit the update installation on the web to run the auto update process i had to submit following SQL string: 
ALTER TABLE kimai_exp ADD KEY (exp_ID);

Without this auto update gave an error in the first steps. 

Maybe you can point me to an other upgrade manual?

Best regards and many thx for trying to help me. 

cheers
maikl

**Comment by simonschaufi** [comment]
well, usually the updater should migrate the database without problems but in the past the updater was not always doing everything perfect. I'm sorry for all the trouble you have but I guarantee that the updater works perfectly from 0.9.3 on. There is no upgrade manual except the little peace on the official docs that you find linked on kimai.org.

I'm available for payed support but since I don't know what your db structure looks like, I can't tell you if everything is fine or not.

**Comment by maikl-swiss** [comment]
hey simon, thx so far. 
Maybe i can update to 0.9.3 first and than run the update. 
I will post my results here. 


But first i need to fix my other problem with pdf export. #827 (Not related to this issue)
