### ISSUE TITLE
PDF Export after Update to V1.1.0 shows white page 

### ISSUE THREAD

**Issue by maikl-swiss** [kimai/kimai#827]
PDF Export

When i try to create a pdf it will move me to a white site 
....../kimai/extensions/ki_export/processor.php

#### Steps
Kimai - Export - PDF 

#### Kimai version
v1.0.1.1388 - © 2006-16 by the Kimai-Team

From log: 
[06.09.2016 16:24:53] KSPI axAction (user1): PDF
[06.09.2016 16:25:00] KSPI axAction (user1): export_pdf2

I tried to find something similar but was not the case. 
Anybody can help me please? 

cheers
maikl

**Comment by simonschaufi** [comment]
Hi Maikl, please respect our issue template. It's there for a purpose. Please edit your issue and use the template (Copy it from [here](https://github.com/kimai/kimai/blob/master/.github/ISSUE_TEMPLATE))

**Comment by maikl-swiss** [comment]
Sorry i did not used the template. Edited first post.

**Comment by maikl-swiss** [comment]
I tried to solve this with a new update. 
I installed kimai 0.9.2.1306 and imported the my old DB (Backup) all worked well. 

Than i updated to kimai.0.9.2.1306-1 and after that to kimai.0.9.2.1306-3
Export, preferences all was ok. 

Than update to 1.1.0 
-Unzip 
-Delete all files except:
 -includes/autoconf.php```
  -any self made invoice templates under ```extensions/ki_invoice/invoices/```  (nothing)
  -any self written extensions under ```extensions/```    (nothing)
- Upload all files and subdirectories directly in your Document Root
  
Kimai now shows the Auto Updater v1.1.0.1389 screen. 
It showed me some error so i stopped and will wait for your response. 

Backup Log - all fine (green) 
Update Log - Total 8 warnings and 2 errors(red) 

**1. red:
ALTER TABLE `kimai_exp` RENAME TO `kimai_expenses`, CHANGE `exp_ID` `expenseID` int(10) NOT NULL AUTO_INCREMENT, CHANGE `exp_timestamp` `timestamp` int(10) NOT NULL DEFAULT '0', CHANGE `exp_usrID` `userID` int(10) NOT NULL, CHANGE `exp_pctID` `projectID` int(10) NOT NULL, CHANGE `exp_designation` `designation` text NOT NULL, CHANGE `exp_comment` `comment` text NOT NULL, CHANGE `exp_comment_type` `commentType` tinyint(1) NOT NULL DEFAULT '0', CHANGE `exp_refundable` `refundable` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'expense refundable to employee (0 = no, 1 = yes)', CHANGE `exp_cleared` `cleared` tinyint(1) NOT NULL DEFAULT '0', CHANGE `exp_multiplier` `multiplier` decimal(10,2) NOT NULL DEFAULT '1.00', CHANGE `exp_value` `value` decimal(10,2) NOT NULL DEFAULT '0.00' ;**

Incorrect table definition; there can be only one auto column and it must be defined as a key (#1075)

2. dark green: 
ALTER TABLE `kimai_grp_evt` DROP INDEX `grp_ID`;
Can't DROP 'grp_ID'; check that column/key exists (#1091)

3. dark green: 
ALTER TABLE `kimai_grp_knd` DROP INDEX `grp_ID`;
Can't DROP 'grp_ID'; check that column/key exists (#1091)

4. dark green
ALTER TABLE `kimai_grp_pct` DROP INDEX `grp_ID`;
Can't DROP 'grp_ID'; check that column/key exists (#1091)

5. dark green
ALTER TABLE `kimai_expenses` ADD INDEX (`userID`);
Table 'xyz_zeiterfassung.kimai_expenses' doesn't exist (#1146)

6. dark green
ALTER TABLE `kimai_expenses` ADD INDEX (`projectID`);
Table 'xyz_zeiterfassung.kimai_expenses' doesn't exist (#1146)

7. dark green 
ALTER TABLE `kimai_timesheet` DROP INDEX zef_usrID
Table 'xyz_zeiterfassung.kimai_timesheet' doesn't exist (#1146)

8. dark green 
ALTER TABLE `kimai_timesheet` DROP INDEX zef_pctID
Table 'xyz_zeiterfassung.kimai_timesheet' doesn't exist (#1146)

9. dark green 
ALTER TABLE `kimai_timesheet` DROP INDEX zef_evtID
Table 'yz_zeiterfassung.kimai_timesheet' doesn't exist (#1146)

**10. red
ALTER TABLE kimai_expenses CHANGE `comment` `comment` TEXT NULL;
Table 'xyz_zeiterfassung.kimai_expenses' doesn't exist (#1146)**


I really hope you can help me, problem is the updated DB is running well and we switched beginning August to it. All entries are now made in the new DB but we can't export Data using PDF. 

If you have any questions, feel free to ask, i will answer asap.

Best regards
maikl

**Comment by maikl-swiss** [comment]
Problem solved... don't know what was wrong but it works now. 
Way to my solution: 

Fresh new installation of Kimai 1.1.0 with new "DBtime". 
Backup old DBpdf (the one with PDF error) 
Move backup "DBpdf" to new DBtime

the new prefix is time - old was kimai so i had to edit the autoconfig.php (/includes) 
also i picked up the salt key from there and edit all user pw with mysql 

Kimai ask me to updrade ont he first visit - only took 1-2 sec and no errors reported. 
Logged in and all works well. 


Best Regards and thx for help. 

maikl
