### ISSUE TITLE
can not change project or type of activity of timesheet entry

### ISSUE THREAD

**Issue by piflixe** [kimai/kimai#830]
#### Expected behaviour
Klick on edit entry in timesheet view. Choose different project or different activity. Klick Ok. Project or activity should change

#### Actual behaviour
different project or activity can be chosen. Klick OK -> Windows closes. No changes saved in timesheet entry.

#### Steps to reproduce
For our workgroup we use a group. Alle members have the role "User". I created a role "Groupleader" that has many rights. Since we are responsible and work closely together, we all have the role Groupleader. Please see attached screenshots for exact role settings.
![kimaigrouprolesetting1](https://cloud.githubusercontent.com/assets/6273829/18344610/4814165e-75b8-11e6-86b9-25f5301b57e6.PNG)
![kimaigrouprolesetting2](https://cloud.githubusercontent.com/assets/6273829/18344612/48162390-75b8-11e6-97c9-1eac1d6cbdcb.PNG)
![kimaigrouprolesetting3](https://cloud.githubusercontent.com/assets/6273829/18344609/48134544-75b8-11e6-9ab3-5f40474f53f9.PNG)
![kimaigrouprolesetting4](https://cloud.githubusercontent.com/assets/6273829/18344608/48123ae6-75b8-11e6-8846-86b7f3877fda.PNG)
![kimaiusersetting1](https://cloud.githubusercontent.com/assets/6273829/18344611/4815150e-75b8-11e6-8e42-5ce94b84cc72.PNG)
![kimaiusersetting2](https://cloud.githubusercontent.com/assets/6273829/18344607/48120bb6-75b8-11e6-9c09-343072f6fd0f.PNG)
![kimaiusersetting3](https://cloud.githubusercontent.com/assets/6273829/18344613/48284cdc-75b8-11e6-86a0-27c401c5f757.PNG)
![kimaiusersetting4](https://cloud.githubusercontent.com/assets/6273829/18344614/4828f448-75b8-11e6-9a11-74afd0b78f0b.PNG)
![kimaiusersetting5](https://cloud.githubusercontent.com/assets/6273829/18344615/482ebb4e-75b8-11e6-9adf-95aba3e7068b.PNG)

Create a timesheet entry. Save it. Then klick on edit. Klick OK. Confirm if changes have been saved in timesheet view

#### Reproducable on demo.kimai.org?
no. works in current demo. Can't reproduce on demo

#### Kimai version
dev 1.1.0.1389|github master

#### further notes
if this appears to be a problem of our instance and not in the source, please contact me, so we can agree on how you can could help us as professional consultant

**Comment by kevinpapst** [comment]
Hi Felix,
we have multiple requests that saving doesn't work properly.
It is not reproducable for us, so I assume that something with either the
PHP/ MYSQL versions is wrong or the update failed for some tables.
The best would be to install kimai from scratch and do a structure export
for both the new and the updated database. Then compare both files and see
if you find any differences.

Am 08.09.2016 11:58 schrieb "Felix Piela" <notifications@github.com>:

**Comment by piflixe** [comment]
it seemed mysql was in strict mode and this caused the described bug.
what worked for me:
https://tjosm.com/5266/disable-strict-mode-mysql-5-7-ubuntu-16-04/
I recommend changing the install documentation so requirements are met.
