### ISSUE TITLE
disabling expenses breaks budget

### ISSUE THREAD

**Issue by Nef10** [kimai/kimai#831]
#### Expected behaviour

The budget extensions is still usable.
#### Actual behaviour

The budget extensions shown an empty container and the console shows: `Failed to load resource: the server responded with a status of 500 (Internal Server Error) /extensions/ki_budget/processor.php`
#### Steps to reproduce

Disabled the expenses extensions by renaming the folder to start with a `#`. (As written [here](http://www.kimai.org/documentation/developer/extensions.html))
#### Kimai version

1.1.0 Stable
#### Relevant log entries from log file

```
[Thu Sep 08 14:43:26 2016] [error] PHP Warning:  include(../ki_expenses/private_db_layer_mysql.php): failed to open stream: No such file or directory in /srv/www/kimai/extensions/ki_budget/private_func.php on line 20
[Thu Sep 08 14:43:26 2016] [error] PHP Warning:  include(): Failed opening '../ki_expenses/private_db_layer_mysql.php' for inclusion (include_path='/srv/www/kimai/libraries/zendframework/zendframework1/library:.:/srv/www/kimai/libraries') in /srv/www/kimai/extensions/ki_budget/private_func.php on line 20
[Thu Sep 08 14:43:26 2016] [error] PHP Fatal error:  Call to undefined function get_expenses() in /srv/www/kimai/extensions/ki_budget/private_func.php on line 31
```

**Comment by simonschaufi** [comment]
In my opinion this doesn't make sense. Of course you need to fetch data from the expenses table (which in this case is located in this extension). If you just want to hide the tab, you can also do that in the Global Roles

**Comment by kevinpapst** [comment]
Both true. Buts lets check if we csn get it lossely coupled. Budget and expenses should not rely on each other.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
