### ISSUE TITLE
[row.projectName] doesn't work in .odt invoice extensions

### ISSUE THREAD

**Issue by wildview** [kimai/kimai#832]
#### Expected behaviour
To output the actual projectName in long.odt

#### Actual behaviour
It just outputs the string [row.projectName] versus my actual project name.

#### Steps to reproduce
place row.[projectName] in place of [row.comment] in long.odt

#### Reproducable on demo.kimai.org? [yes|no]
Don't no, since I don't have the login/pwd to try it.

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
dev 1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
None.

Thanks, I'm hoping there is a work around for this or maybe it doesn't work in the .odt extensions, not sure what is going on since it appears to work with .html extensions, but just not the .odt extensions. Can some let me know what is going on with this and how to resolve if not a bug? This is kind of show stopper for me since I need to have the project name on my invoices =)

Thanks so much!

![long odt - libreoffice writer](https://cloud.githubusercontent.com/assets/22099751/18389488/62773638-7663-11e6-97ea-c67586c1d21e.png)

**Comment by kevinpapst** [comment]
Try row.name instead of row.projectName

**Comment by wildview** [comment]
Kevin, row.name didn't work, but I found the font used on the text was causing the problem and it works with [row.projectName] now. Strange =) 

One last struggle is getting the [row.rate] to work. See the attached... I noticed this is not an option in the documentation, but is available in one of the html invoices, so I assume it should work in the odt documents as well. Is this true? For some reason it throw an error when I generate an invoice 'Failed rendering invoice: item '

Is there a document that describes how to make invoices in Kimai? There are so many different codes and such it would be great to know how all this works. 

![eg odt - libreoffice writer](https://cloud.githubusercontent.com/assets/22099751/18406594/5994a7ea-76bc-11e6-8d11-0bfef339dcfc.png)

**Comment by wildview** [comment]
Actually, I found creating a custom html invoice works way better then using the open office forms since I never got consent results from it. The html/php stuff works great though =)

**Comment by norwegianblue-nz** [comment]
> One last struggle is getting the [row.rate] to work.
I've been struggling with this too in ODT. Any chance of a clue from the developers?

**Comment by simonschaufi** [comment]
Check https://github.com/kimai/kimai/blob/master/libraries/Kimai/Invoice/PrintModel.php#L96 to see what is available. There are some more but I don't find them right now. these should be the root elements.
