### ISSUE TITLE
Deleting timesheet entries

### ISSUE THREAD

**Issue by wildview** [kimai/kimai#833]
#### Expected behaviour
Add  trashcan icon to each timesheet entry for easy removal.
#### Actual behaviour
It's too time consuming to edit each entry, click on the advance tab and remove them. The trash icon would be so helpful =)
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389

**Comment by kevinpapst** [comment]
Afaik there is a setting to activate quick delete.

Am 10.09.2016 23:01 schrieb "wildview" <notifications@github.com>:

**Comment by wildview** [comment]
Could you let me know where that setting is since I don't see it and it's not in the advance settings =)

Tnx.

**Comment by wildview** [comment]
I found it in the preferences at the top =) Tnx.
