### ISSUE TITLE
TimeSheet records are left behind after a project is deleted

### ISSUE THREAD

**Issue by wildview** [kimai/kimai#834]
#### Expected behaviour

This is a bug I think that hopefully can be resolved. There should be a confirmation box or something that allows for us to remove all Timesheet/Expense records if a project they are associated with is removed since it's hard to remember to remove all the timesheet and expense entries first.
#### Actual behaviour

Timesheet/Expense records get left behind in the database if a project they are associated w/ is removed.

Timesheet/Expense records should be deleted if a project they are associated with is removed since the user has no way to access the TimeSheet records again unless you delete all the projects, logout and log back in. Then they are all listed again to remove.

If you opt to not delete all the projects just to gain access again to all the missing Timesheet/Expense records for the deleted projects, you can logout and log back in again and they all appear, but you can only delete one entry at a time and they all disappear again and only the Timesheet/Expense records for the active projects remain listed.

This really needs to be addresses because it's too easy just to delete a project and forget to delete the time records for it first. Painful =)
#### Steps to reproduce

Create a project then create a bunch of timesheet records, then delete the project without deleting the timesheet records first. The timesheet records remain behind. It's painful to delete all the projects to get access to delete them again since you have to logout and back in again to see and delete them. If you still have a valid project loaded you'll only be able to delete one record entry at a time for each logout/login section since it switches back to the active project after deleting the record for the deleted project as I described above =)
#### Reproducable on demo.kimai.org? [yes|no]

Probably since I'm using the latest version.
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]

1.1.0.1389

**Comment by simonschaufi** [comment]
I haven't really thought about that. Time tracking entries are what kimai is all about. If you delete a project "accidentally" and delete all the time entries also, you have a huge problem while restoring just a deleted project is not a big thing.
Deleting something in general is not really a good choice in kimai. Just inactivate a project if you want to hide it. If you really want to delete all related records, what about deleting a customer or a user? You see, it's getting quite complex.

**Comment by wildview** [comment]
Yes I agree to some point, but if you think about it, some people don't like to keep old projects around and clutter up the database with a bunch of old time records especially if you have the invoice for it? It's probably a major change to prompt saying "Delete all time records Y/N" to delete existing time records for a project you want to remove, so we just have to remember I guess to delete the time records first for a project before removing it because it is time consuming to get rid of the associated time records if you delete project first =)

This is a really awesome program and I really appreciate the time that went into providing it us.

**Comment by kevinpapst** [comment]
The behaviour is implemented like this for a reason, so: no bug ;-) this might not relate for freelancer or single users but  loosing this data could mean big trouble for companies. We can think about deep deletion as a feature request for the future.

**Comment by wildview** [comment]
Yeah, i agree for companies you probably need to keep the data in tact.  So changing it for single end users like myself is probably not going to happen =) I'll just remember to never delete a project w/o first getting rid of the data records for it first.  It's obviously not a bug, but what would be nice is never let a project be deleted if there's time records associated with it.  This I believe would resolve the problem altogether and help protect and mistake proof the data just in case someone deletes a project by mistake since it happened to me because I didn't know the functionality of the software and what would happen and I found out the hard way =) Would this feature be possible to add do you think?

**Comment by simonschaufi** [comment]
We don't need that feature but if you need it, you can sponsor it. The best is to use bountysource.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
