### ISSUE TITLE
Install kimai using linux commands

### ISSUE THREAD

**Issue by nduhura** [kimai/kimai#835]
Hello,

I am trying to install on a virtual server without display.
Can someone help me with the set of commands that need to be run for the installation?

Thanks in advance,

Justin

**Comment by kevinpapst** [comment]
I cannot see a readon for That.  Why would you do it? You always need a webserver to use kimai. Even if it is the built in version from php.

**Comment by kevinpapst** [comment]
And here are some scripts That might give you an idea on bash only installation: https://github.com/kimai/scripts/tree/master/installer

**Comment by nduhura** [comment]
Thank you very much kevinpapst fr your reply.
I need command to properly install and configure that webserver.
My machine is a remote server and I can only access using commands

**Comment by kevinpapst** [comment]
Sorry, cant help you with that. It highly depends on your OS. Best is to ask a Linux forum or follow one of the thousand tutorials out there. ;-) you need mysql or mariadb as database,  php and a webserver (apache or nginx).

**Comment by nduhura** [comment]
Thank you Kevinpapst, your previous past gave the answer I was expected.

**Comment by nduhura** [comment]
Just a few message to thank for the reply. This solved my problem and everything works as expected.
Nice environnement.
Thks.
