### ISSUE TITLE
Installation problems using MariaDB

### ISSUE THREAD

**Issue by Breisand** [kimai/kimai#836]
#### Expected behaviour
Normal installation, complete the installation, then the mainpage is shown

#### Actual behaviour
Installation normal until page "Write Config-File" (step 7 of 8)
After clicking "Install" in this page, then it says:
"Error during installation!
Kimai is unable to create necessary tables because tables with the name name already exist.
To update your existing installation please click here.
Choose another table prefix or delete existing tables with this prefix in order to allow Kimai to perform a clean installation. "

#### Steps to reproduce
Use a server that have MariaDB latest version. (it has PHP7 but is probably not relevant)
Create the database.
Upload files, install the usual way, including setting some directory writable.
Installation also tested on another server using PHP 5.5.9 and connected the database remotely, same result/errror.
(Works fine using PHP7 and a remote mysql database)

#### Reproducable on demo.kimai.org? [yes|no]
no

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[logfile.txt](https://github.com/kimai/kimai/files/473672/logfile.txt)
(Tried to install several times)

**Comment by simonschaufi** [comment]
I'm also using mariadb with php7 and everything works fine for me.

**Comment by Breisand** [comment]
Thanks, now it works!
I created a new database using UTF-8 instead of "default", then it works fine. 
(I used ISPConfig to create the databases; "default" works when using the MySQL database I had before, but not to the new MariaDB)
