### ISSUE TITLE
Date Entry Problem - Skips ahead a year!

### ISSUE THREAD

**Issue by wildview** [kimai/kimai#837]
#### Expected behaviour

If you edit a time record from a previous day and change the start and the end date it should retain it.
#### Actual behaviour

If you a have start date on a time record and want to go back a day, it doesn't work instead it skips a complete year ahead. Ooops! 

**If I select the previous day of 15.09.2016**
![datepickerfrom](https://cloud.githubusercontent.com/assets/22099751/18605803/c4e09c64-7c59-11e6-9807-36fb36ebb528.png)

**If forces this date into the field a year later and a random day. It should be 15.09.2016 that I selected.**
![datepickerproblem](https://cloud.githubusercontent.com/assets/22099751/18605794/931a49b4-7c59-11e6-8aa4-50ec88aa79f5.png)

**Even if you create a new record, then edit, click now, it changes the end date a year ahead and the duration switches to the following.**
![clickingnow](https://cloud.githubusercontent.com/assets/22099751/18607836/b8589406-7c95-11e6-91ac-e71385c833f0.png)
#### Steps to reproduce

Edit a time record select a start date from the list using a prior day, it will then choose a random day a year later in the month and use that instead of the date I pick, to me this a serious problem since I need to be able to go back and add time records for previous days if I need to. 
#### Reproducable on demo.kimai.org? [yes|no]

No, for some reason the demo works, I'm not sure why mine doesn't since it's the same version and matches the demo settings except my timezone is America/denver. I even unloaded everything off my server, deleted the database and put a fresh new copy of the latest dev 1.1.0.1389 and it still has the same issue.
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]

1.1.0.1389
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

Can you help me figure this out? In the mean time I'm going to switch back to using toggl.com to track my time now for a while since it works and is more stable until I hear back from. Tnx.

**Comment by wildview** [comment]
btw, I decided to delete the entire database and reload the software and it has the same problem as described above. What is causing this?

**Comment by wildview** [comment]
Ok, I found the problem and it's bug with the Date format for the datepicker if you change your default from dd.mm.yy to mm.dd.yy the date picking doesn't work properly when editing dates for a time record. The demo has the same bug and does the same thing. I hope at some point you can fix this problem for others that prefer a different date style in the day settings.  I have all the other date formats set to mm.dd.yy in the admin settings and are fine, it's just the datepicker format that causes problems if you change it from the default =)

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
