### ISSUE TITLE
database user privileges

### ISSUE THREAD

**Issue by BDub-Hay** [kimai/kimai#839]
Hello, I made myself a new install of Kimai.  This time around I wanted to create a mysql database user specifically for Kimai and not use the root user again.  I created the database and granted select, insert, update and create privileges on the kimai database to 'kimai_user'@'localhost'.  the installation seemed to go fine but when i am in the admin panel trying to setup users and projects and activities, nothing is working.  I can click the "add project" button, enter the details of the project but when I am done and click ok, nothing happens.  Another example, i can create a user but the user i created doesn't show up under the list of users.  If i add the user again, i get a message telling me this user has already been added.  I can even log in with that user name and password.  I suspect I have fouled something up on the database setup but I can't see what it could be.  I am trying to keep the kimai_user database privileges to a bare minimum for security purposes.  Any help or suggestions would be greatly appreciated.  Thanks.

**Comment by simonschaufi** [comment]
why not just grant all privileges and then reduce them? this is not our business if you are not able to setup your privileges correctly.

**Comment by BDub-Hay** [comment]
Wow, thanks for the support.

**Comment by simonschaufi** [comment]
Please understand that kimai is our hobby, not our fulltime job ;)

**Comment by BDub-Hay** [comment]
I understand that, but here is where i am coming from.  I am not a super smart ninja sys admin, server admin, I.T. guy, etc.  I'm just some putz who was looking for something to scratch an itch i had.  I have enough knowledge to be dangerous and sometimes i need somebody to hold my hand.  Now surely, in all of the Kimai user land there must be somebody who had the same idea, and made it work.  That was all I was looking for, somebody who has already done this and was willing to share their experience on database user permissions.  I'm not asking anybody to sink a bunch of hours into researching this, but my question (in my opinion) is quite trivial for a seasoned pro.  

I'm not quite sure how this github thing works, but it is the only place i could find to ask for help.  If there is a better place to go for help then please direct me there, I would certainly appreciate it.  Thank you.
