### ISSUE TITLE
Kimai unusable with mysql strict mode enabled

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai#840]
#### Expected behaviour
works like a charm

#### Actual behaviour
Column 'xxx' cannot be null (#1048)

#### Steps to reproduce
not sure where all the spots are that are broken

#### Reproducable on demo.kimai.org? [yes|no]
no, since strict mode is not enabled

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
all

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
user_edit failed: Column 'mail' cannot be null (#1048)
project_activity_edit [3]: Column 'budget' cannot be null (#1048)
...and many more. **Let's find them all!**

See #709 for details

**Comment by kevinpapst** [comment]
Are you working on that or is that just a reminder?

**Comment by simonschaufi** [comment]
Not yet. For now i just want to list all places that are broken
