### ISSUE TITLE
Not able to export report in csv and xls format on live server but same working on localhost

### ISSUE THREAD

**Issue by dineshluck1** [kimai/kimai#841]
Expected behaviour
Report should be downloaded

Actual behaviour
Redirecting to extensions/ki_export/processor.php with no error displayed.Only blank page and no errors logged in apache errors log.

Steps to reproduce
Login to admin panel and try to download report in excel format

Kimai version [latest]

**Comment by q00d0** [comment]
Have you tried to install these PHP extensions?

php5.6-xml + php5.6-xmlrpc

This has worked for me on Ubuntu

**Comment by simonschaufi** [comment]
no feedback.
