### ISSUE TITLE
Choose entry with arrow up / down when searching activity and project fields in manual timesheet entry

### ISSUE THREAD

**Issue by piflixe** [kimai/kimai#844]
I really like the feature in the kimai 1.1 that in the manual timesheet entry the list of project and activity can be dramatically reduced with the  "search as you type" search field.
![kimai110_manual_entry](https://cloud.githubusercontent.com/assets/6273829/18865473/bf58c63c-849b-11e6-9424-1073bbf97c19.PNG)

It would be really handy if one could also select the project / activity out of the list with the up / down arrows and jump to the next field when pressing enter (or space or whatever)
#### Expected behaviour
1. open manual timesheet entry
2. type something in the project search field
3. use arrow up / down key to select project out of the short list (due to search as you type)
4. press enter to select project -> cursor automatically jumps into activity search field
5. same as above
#### Actual behaviour

search as you type works, but project and activity have to be selected using the mouse, thereby right hand hast to switch between mouse and keyboard back and forth when using the search as you type fields
#### Reproducable on demo.kimai.org? [yes|no]

yes
#### Kimai version

dev 1.1.0.1389|github master

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
