### ISSUE TITLE
H:M:S in odt shows hour:month:second NOT minutes

### ISSUE THREAD

**Issue by Tobicic** [kimai/kimai#845]
#### Expected behaviour
Variable 'M' in odt shows Minutes in Timeformat
#### Actual behaviour
Variable 'M' in odt shows Month in Timeformat

**Comment by simonschaufi** [comment]
please more info how you use the format.

**Comment by Tobicic** [comment]
Hi, thanks for your quick reply. I use this format in .odt to show starting- and ending-time of process. 
In /help_timeformat.php i read that 'm' is for month and 'M' is for minute. but any case (m, M, mm, MM) shows month: [row.start;frm='H:M:S']

**Comment by simonschaufi** [comment]
Here is the documentation:
http://www.tinybutstrong.com/manual.php#html_field_auto
scroll a bit UP to `frm=format`

**Comment by Tobicic** [comment]
Thank You!
