### ISSUE TITLE
Enable budget for time instead of money

### ISSUE THREAD

**Issue by lenucksi** [kimai/kimai#846]
#### Expected behaviour

I would like to be able to budget on time instead of money, i.e. a fixed amount of hours per month.
If the amount is reached I would like to have a notification that is has been reached.
If more than the amount has been spent, I would like to know how much.
It would be nice to be able to get the amount of time spent over the paid amount to be deducted from the next month (or added to the next month in the reverse case)
#### Actual behaviour

Kimai only allows to budget for money - given a fixed hour rate this would allow a simulation of parts of the above, however this is not the desired behaviour. 
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]

GitHub master

[![bountysource](https://api.bountysource.com/badge/issue?issue_id=41466195)](https://www.bountysource.com/issues/41466195)

**Comment by lenucksi** [comment]
#705 and #73 look related

**Comment by saschafoerster** [comment]
+1

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
