### ISSUE TITLE
KIMAI Time sheets entries are not shown 

### ISSUE THREAD

**Issue by haridb** [kimai/kimai#848]
Entries given in the time sheets are not shown eventhough when the time and date has been changed as per the entries which has been already recorded. And the entries are not shown in the export tab too.. Can anyone give me a idea to resolve this error?

**Comment by simonschaufi** [comment]
There is a limit of 100 in the user settings. Increase that and you will see all.

**Comment by haridb** [comment]
i have increased the limit to 1000 but still the entries are not shown in the export... and the same problem is faced in the admin panel too... What to do?

**Comment by kevinpapst** [comment]
Check the log file and have a look at your javascript console.

**Comment by haridb** [comment]
where to check the log file ?

**Comment by haridb** [comment]
can you please explain me why this error occured?

**Comment by kevinpapst** [comment]
1. The log file is in Kimai "debug" tab. 
2. Check if there is an error in the javascript console shown.
3. If you have enough know-how check if the entries are reloaded via Javascript and what the output is.

**Comment by haridb** [comment]
help me to sort out this error....

**Comment by simonschaufi** [comment]
first of all, which kimai version are you using?

**Comment by haridb** [comment]
I am using KIMAI v1.1.0.1389

**Comment by haridb** [comment]
can you please help me to sort out this error simon....

**Comment by simonschaufi** [comment]
actually, we need more info as we cannot easily reproduce it ourselves. how many entries are shown? how many should be shown? and things like that...

**Comment by haridb** [comment]
what are the informations you need?.......   the entries are displays for a second when the page is reloaded and again it disappears both in the timesheet tab and export tab... and when a new is given the entry is stores in the database but it is not displayed in the timesheet

**Comment by simonschaufi** [comment]
ok then try to figure out why the entries are hidden at some point. I have no glue what the problem is honestly

**Comment by kevinpapst** [comment]
what if you choose a shorter timeframe?
And answer my questions from above, I did not write them because I am bored, but because we are trying to help

**Comment by haridb** [comment]
[05.10.2016 22:48:16] E_NOTICE Undefined index: activity_ID @/hermes/bosnaweb21a/b2788/ipg.internationalstudent/timesheet/libraries/Kimai/Database/Mysql.php line 318 

this what shows in the kimai log file....

**Comment by haridb** [comment]
This error is shown in the java console...

A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Wed Oct 05 2016 23:15:14 GMT+0530 (India Standard Time)
Full Message: Error: page-thumbnail:error
Full Stack: observe@resource://gre/modules/BackgroundPageThumbs.jsm:112:22
BackgroundPageThumbs._onCaptureOrTimeout@resource://gre/modules/BackgroundPageThumbs.jsm:275:7
Capture.prototype._done/done@resource://gre/modules/BackgroundPageThumbs.jsm:413:7
Capture.prototype._done@resource://gre/modules/BackgroundPageThumbs.jsm:425:7
Capture.prototype.notify@resource://gre/modules/BackgroundPageThumbs.jsm:390:5
BackgroundPageThumbs.jsm:112
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Wed Oct 05 2016 23:15:44 GMT+0530 (India Standard Time)
Full Message: Error: page-thumbnail:error
Full Stack: observe@resource://gre/modules/BackgroundPageThumbs.jsm:112:22
BackgroundPageThumbs._onCaptureOrTimeout@resource://gre/modules/BackgroundPageThumbs.jsm:275:7
Capture.prototype._done/done@resource://gre/modules/BackgroundPageThumbs.jsm:413:7
Capture.prototype._done@resource://gre/modules/BackgroundPageThumbs.jsm:425:7
Capture.prototype.notify@resource://gre/modules/BackgroundPageThumbs.jsm:390:5
BackgroundPageThumbs.jsm:112
no element foundrequest:1:1
Use of getAttributeNode() is deprecated. Use getAttribute() instead.jquery-1.9.1.min.js:3:29041
TypeError: this.transport is null[Learn More]main.js:1411:5

**Comment by simonschaufi** [comment]
could you try to open kimai in privacy mode (in your browser)? this looks like it's coming from an addon.

**Comment by haridb** [comment]
yes i can open the kimai in privacy mode ...but the same error occurs

**Comment by haridb** [comment]
the main issue is that whenever i login into the kimai i can view my entries .... but if i try to do some activities then the entries disappears and it shows " no entries"..

And when i click on the export tab the entries are shown for a second and then it gets disappeared... i have attached a document ...please take a look at it
[kimai timesheet error.docx](https://github.com/kimai/kimai/files/512047/kimai.timesheet.error.docx)

**Comment by kevinpapst** [comment]
@simonschaufi I have seen something similar before. It happened only after an action (javascript reload) because the initial tab load had slightly different logic than the reload axAction. 
Thats why I moved all the loading logic in the admin module into separate functions.
I can't remember what it was exactly, but I believe it had to do with the users permissions.

@haridb since when does that happen? Did you do an update? Are the time entries from yourself or from a different user? What groups does your user belong to? Did you try an admin account?

**Comment by haridb** [comment]
from last few days it happens... and i did not done an update.... and 
the time entries are given by me ... the user belongs to the admin group ...
and i have tried the admin account too.. the same error occurs in the admin account also..
i am the admin of the account...and my users are also facing the same problem.

**Comment by simonschaufi** [comment]
ok and what do you mean with 

> and the same problem is faced in the admin panel too

?

**Comment by haridb** [comment]
entries are not shown in the admin panel...both in the timesheet tab and also in the export tab

**Comment by haridb** [comment]
is there any way to sort out this error??

**Comment by haridb** [comment]
can you guys help me to sort out this issue....

**Comment by simonschaufi** [comment]
Could you upload a db dump somewhere so we can download it and try to reproduce?

**Comment by Xav24** [comment]
Hi,
    Would it be better for you if i let you access the software
      directly ?
    We've got nothing special on it at the moment.
    
    
    Le 14/10/2016 à 23:03, Simon
      Schaufelberger a écrit :
    
    
      Could you upload a db dump somewhere so we can download it and
        try to reproduce?
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kimai/kimai","title":"kimai/kimai","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kimai/kimai"}},"updates":{"snippets":[{"icon":"PERSON","message":"@simonschaufi in #848: Could you upload a db dump somewhere so we can download it and try to reproduce?"}],"action":{"name":"View Issue","url":"https://github.com/kimai/kimai/issues/848#issuecomment-253918647"}}}

**Comment by simonschaufi** [comment]
yes, but having a db dump to verify it on my own system would still be nice

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
