### ISSUE TITLE
how to edit the font size in the PDF export

### ISSUE THREAD

**Issue by maikl-swiss** [kimai/kimai#849]
#### Expected behaviour

small font size within the PDF Export
#### Actual behaviour

standard font size
#### Steps to reproduce

Kimai - export - pdf export
#### Reproducable on demo.kimai.org? [yes|no]

yes
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]

v1.1.0.1389 - © 2006-16 by the Kimai-Team:
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

no error's 

Hello Kimai Master's, 
i need to edit the font size of the PDF export. In the old version i had a solution but i don't work in the VU1.1 for me. 

The old steps: 
\xampp\htdocs\kimai\libraries\tcpdf\tcpdf.php 
row  1531           $this->FontSizePt = 8; (basic =12) 
footer: 
\htdocs\kimai\extensions\ki_export\ki_export_pdf.php & ki_export_pdf.php
/*$this->SetFont('helvetica', '', 7)  (8 = basic) 

Maybe i made a mistake, but after the changes in the VU 1.1 my pdf export didn't work any more. 

Maybe someone can point me to a solution.

Thx and best regards
maikl

**Comment by kevinpapst** [comment]
Hi Maikl,
what do you mean with "my pdf export didn't work any more"?
Is there an on-screen error message or a debug log entry?

**Comment by simonschaufi** [comment]
Maikl, never touch a library! It's much better to use the API for that (in this case, use the file where kimai calles the library).

**Comment by maikl-swiss** [comment]
@kevinpapst - didn't work anymore sounds stupid ... if i change the values and try an export i only get a white page w/o error's and w/o log entry. 

@simonschaufi  I bet you are right with that. But can you please help me. In the old VU i had to changes the values in these files: \extensions\ki_export\ki_export_pdf.php & ki_export_pdf.php but they are not around any more. I guess they are renamed to export_pdf.php and export_pdf2.php?

`/**
   * Print a footer on every page.
   */
  public function Footer() {
    global $kga, $customerData, $projectData;

    // Position at 1.5 cm from bottom 
    $this->SetY(-15);

    // customer data
    /*$this->SetFont('helvetica', '', 7); // Set font
    $this->Cell(80, 10, $customerData['customerName'].' ('.$projectData['pct_name'].')', 0, 0, 'L');*/`

This should be the footer ... but i can't find the value for the "main text".

thx for helping a bloody beginner :) 


maikl

**Comment by kevinpapst** [comment]
Search for the `->SetFont()` calls and adjust them to your needs in:
https://github.com/kimai/kimai/blob/master/extensions/ki_export/export_pdf.php
https://github.com/kimai/kimai/blob/master/extensions/ki_export/export_pdf2.php

**Comment by maikl-swiss** [comment]
Hello Kevin, thx so far. 
I can change the footer font now, but still not able to find the right setting for the main/body text.
It is still size 12 if im right, even i changed this value: 

  // determine font sizes to work with
                    $current_font_size = $this->getFontSizePt();
                    if ($current_font_size <= 0) {
                        $current_font_size = 8;   **This was 12 before**


thx for your advise. 

maikl

**Comment by blu-IT** [comment]
Hello,

what is the difference between 
> https://github.com/kimai/kimai/blob/master/extensions/ki_export/export_pdf.php

and

> https://github.com/kimai/kimai/blob/master/extensions/ki_export/export_pdf2.php

Are the two differnt ways of exporting as a PDF? 

Thanks!

**Comment by maikl-swiss** [comment]
Not 100% sure but there are two different Formats to choose for export (List and table.)

**Comment by blu-IT** [comment]
OK, thanks! I found a similar comment in the forum.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
