### ISSUE TITLE
KIMAI Time sheets entries are not shown in admin panel 

### ISSUE THREAD

**Issue by haridb** [kimai/kimai#850]
I have increased the limit to 1000 and again the time entries are not shown in the export and also in the time sheet... and i face the same problem in the admin panel too...by logging in as admin ,i can't see my users entries and also the entries are not shown in export too...

note: but i can see those entries in my database...the only problem is that i cant view those entries in my kimai timesheet..the entries shows up for a second and it disappears when the page is refreshed.
[kimai timesheet error.docx](https://github.com/kimai/kimai/files/511767/kimai.timesheet.error.docx)

**Comment by kevinpapst** [comment]
Please one ticket for one issue. All the rest in #848 . 
And post the exact same problem description there as well, this one sounds different from #848
