### ISSUE TITLE
Installation Not Starting

### ISSUE THREAD

**Issue by canbarry** [kimai/kimai#851]
#### Expected behaviour
Guided Installation when attempting to install the application.

#### Actual behaviour
There are no error messages or application installation guidance. The screen is black. 
#### Steps to reproduce
Installed Xampp on Windows 7. Tested the php and sql, updated the root sql password. Extracted the Kimai files to the c:\xampp\htdocs\ directory. Attempted to run the installation from this location and receive a black screen only.
#### Reproducable on demo.kimai.org? [yes|no]
no
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Lastest download version as of 10/10/2016
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
Currently attempting to install on the latest version of Xampp - php ver 5.6.24 with mysqli and iconv. Current sql is version 10.1.16 MariaDB.

**Comment by kevinpapst** [comment]
This is definitely not a Kimai bug, but an environment/hosting problem.
Did you try it via http://localhost/ ?

2016-10-10 23:45 GMT+02:00 canbarry <notifications@github.com>:
