### ISSUE TITLE
var.today and var.date within invoice template setting the format

### ISSUE THREAD

**Issue by maikl-swiss** [kimai/kimai#853]
#### Expected behaviour
Date is shown in wrong format
#### Actual behaviour
var.today shows some strength numbers 
var.date has the wrong format for me  "10/14/2016 "
#### Steps to reproduce
Use Invoice 
#### Reproducable on demo.kimai.org? [yes|no]
didnt tried it bec. its individual setting 
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389 - © 2006-16 by the Kimai-Team
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

In the old print.php (VU0.9..)  i remember a setting for date but don't know where to find it in the new version.

![row_date](https://cloud.githubusercontent.com/assets/21668558/19385059/fc640fc2-920c-11e6-8baf-4629cbe264f9.PNG)

![var_today](https://cloud.githubusercontent.com/assets/21668558/19385060/fc656bc4-920c-11e6-8e2a-e1ee75b97df2.PNG)

Date setting within kimai: 

![settings_kimai](https://cloud.githubusercontent.com/assets/21668558/19385101/2eedab10-920d-11e6-829a-f8ef7de6c94f.PNG)

Let me please know where i can change the format to var.today = 14.10.2016
and row.date = Tag/Monat/Jahr    ("14.10.2016")

Many thx and best regards
maik

**Comment by simonschaufi** [comment]
The time settings in admin panel don't apply for the odt rendering! You can find the documentation here: http://www.tinybutstrong.com/manual.php

**Comment by maikl-swiss** [comment]
oh... that looks very complicated and rly, i don't know where to start....

In the old version there was to change some settings in the print.php ... 
example: $today           = date("d.m.Y");

I'm not good with programming..... maybe you can help me a lil more to find the right way. 

regards
maikl

**Comment by simonschaufi** [comment]
I'm no pro either with odt templating but look at the existing template provided with kimai and then read the docs and try to understand it yourself. If you are totally stuck, we may help you.

**Comment by maikl-swiss** [comment]
got it.. no need to edit the print.php.
It is possible to format the date within the .odt file. 
Switched for 

var.today to  [var.dueDate; frm='dd.mm.yyyy'] 
and added format to the row.date  = [row.date; frm='dd.mm.yyyy']

Works perfect. 

Sometimes only writing a question in the forum help's to solve things. 
Maybe someone can use it. 

regards
maikl





FORMAT INVOICE DATE
