### ISSUE TITLE
Don't show version in copyright footer for unauthenticated visitors

### ISSUE THREAD

**Issue by xelan** [kimai/kimai#854]
#### Expected behaviour

IMHO, the detailed kimai version information should not be displayed in the footer for unauthenticated visitors.

One option would be to just remove it from the login screen, but to leave it in other situations (e.g. about dialog floater). Another option is to make the displayed version information configurable, e.g. like Apache2's `ServerToken` setting:
- ShowVersion Prod - Kimai
- ShowVersion Full - Kimai 1.1.0.1389 (current behaviour)

For the latter approach, an additional configuration value in `includes/autoconf.php` which is merged with its default value in `includes/vars.php`, like already done with other variables, would be required. 
Based on that configuration value, the displayed version information in `templates/scripts/misc/copyrightnotes.php` varies. For authenticated users, the detailed version information can still be shown via the "About Kimai" dialog.

If you are interested in this feature, I can provide a PR.
#### Actual behaviour

The detailed kimai version is displayed in the footer.
#### Reproducable on demo.kimai.org? [yes|no]

yes
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]

1.1.0.1389

**Comment by kevinpapst** [comment]
Why do you propose that in the first place?

**Comment by xelan** [comment]
Hi Kevin and thanks for your fast response :smiley: 

When server software versions are exposed to the public, it is much easier for hackers/script-kiddies/... to find vulnerable installations.

The general recommendation is to disable the disclosure of specific server software unless required. 

See for example:
* https://www.owasp.org/index.php/Testing_for_Web_Application_Fingerprint_%28OWASP-IG-004%29
* https://www.troyhunt.com/shhh-dont-let-your-response-headers/

The simple measure of removing detailed version information for non-authenticated users is a small step towards increased security. While one may say that it is security by obscurity, it is an additional bit of defense against automated vulnerability scanners.

**Comment by kevinpapst** [comment]
I thought that this would be your reason... thats why I added noindex,nofollow a long time ago to the index file. Should prevent it from showing up in the search results. Try googling "by Kimai Team".

**Comment by xelan** [comment]
To prevent spidering via "normal", well-behaving search engines, this sounds fine. However, it doesn't help against automated scans, which are happening all the time. If there is no benefit of the fully-fledged version string, I'd opt for dropping it from the index page.

**Comment by kevinpapst** [comment]
I don't mind a PR if you would like to add that feature!

**Comment by simonschaufi** [comment]
I would say 99% of the people using kimai have it installed on an intranet server which is not exposed to the public. If they do, simply for people working remote.
I don't want another configuration option so better drop the output of the version.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
