### ISSUE TITLE
Kimai not working in Chrome

### ISSUE THREAD

**Issue by johannesscherbaum** [kimai/kimai#855]
Kimai 1.x does not work in Chrome. 

The only thing you can see is the progress bar.

![image](https://cloud.githubusercontent.com/assets/5869027/19445147/67e5a05c-9493-11e6-8ee3-e8797bf0c995.png)

**Comment by simonschaufi** [comment]
Hello Johannes,
as long as demo.kimai.org works in chrome, there must be an error in your
installation. Can you please press F12 and check the debug console of your
browser?

**Comment by slikarch** [comment]
...same problem here, install gives no errors but Kimai won't run. Any idea what could be the issue?

![kimai_1 1](https://cloud.githubusercontent.com/assets/7642638/21864626/e32e7854-d842-11e6-972b-f295b6bae02f.gif)

**Comment by CC-Netzwerk** [comment]
Delete your browser-cache. This solved the problem at me.

**Comment by simonschaufi** [comment]
and make sure your installation is not broken. it seems like some files are missing (status 404)
