### ISSUE TITLE
Exported report doesn't show projects

### ISSUE THREAD

**Issue by keteague** [kimai/kimai#856]
#### Expected behaviour
Reports show project.

#### Actual behaviour
Project is not shown, or replaced with a hash mark.

#### Steps to reproduce
Add multiple manual entries with current date, start & stop time.  After that, export to PDF.  It only shows activities but not the related project.

#### Reproducable on demo.kimai.org? [yes|no]
Yes.

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
from logfile.txt... Not sure if this has anything to do with it...
[04.11.2016 10:53:09] E_NOTICE Undefined index: fixedRate @/var/www/html/kimai/extensions/ki_timesheets/processor.php line 459

**Comment by nbickel** [comment]
i have the same problem after upgrading from Release 0.9.3 to Release 1.1.0. My logfile does not show any error.

**Comment by nbickel** [comment]
as my code review showed the # is comming from an trackingnumber in export_pdf.php in row 140. i changed $trackingnumber with $row['projectName']

**Comment by keteague** [comment]
nbickel, good catch!  That works, although it doesn't handle parenthesis correctly... but it's better than what we were getting.  THANKS!

**Comment by simonschaufi** [comment]
Can somebody please make a pull request to fix this?

**Comment by keteague** [comment]
Not quite sure what a "pull request" is or how to do one, but I've gone ahead and posted a pull request using the template provided here on github.  Not sure if it's correct.  I included a diff file with the changes nbickel found and fixed.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
