### ISSUE TITLE
No user filter for logged in user and invoice creation

### ISSUE THREAD

**Issue by kernie** [kimai/kimai#857]
Hi!

Thanks for this wonderful tool!

If somebody could comment on my issue I'd be glad:

I have several freelancers (i.e. users of role "user") grouped to work in a project for a customer. I would like them to generate an invoice for their work only but the invoice shows the work of all users of the project rather than that of the logged in user. 

Is this by design?

The "Export" tab correctly filters for the logged-in user

Best regards,
Maarten

#### Expected behaviour
Maybe only the group leader and admin should see everything.

#### Actual behaviour
All items of all workers of a project are printed

#### Steps to reproduce
see above
#### Reproducable on demo.kimai.org? [yes|no]
?
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.0.1 1388
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

[![bountysource](https://api.bountysource.com/badge/issue?issue_id=39043949)](https://www.bountysource.com/issues/39043949)

**Comment by simonschaufi** [comment]
Well, usually when I want to invoice a customer, I want to send him an invoice for all users, not just for a single one.
In your case it is exactly the other way round, that single users want to invoice their company.
Are you willing to sponsor this feature? That would be great!

**Comment by kernie** [comment]
I'm interested in sponsoring. Can you outline how much effort it would need and what realistic time frame you  consider ?

**Comment by kernie** [comment]
Sorry, closed it accidentally.

**Comment by simonschaufi** [comment]
Hello kernie!
First of all I would define the features. I would suggest the following:
Admin users can created invoices for all users. Then there needs to be a role setting to let normal users create invoices only for them self or disable it. How about group leaders? I would suggest that group leaders can also create invoices for just a subset of users that they have access to. Does this make sense?

What is your personal requirement for this feature? I can only say how long we need to code if the feature has clear specifications.

**Comment by kernie** [comment]
Hi,

That's the exact requirement ...

From handling I would expect that as a group leader I can loop through all (or specified) group members (additional dropdown menu?) in ods tables or odt texts of invoices.

**Comment by kernie** [comment]
Dear simonschaufi,

Would like to express again my interest in sponsoring this feature. 

Can we discuss further  off-List, if somebody is willing to do it?

**Comment by simonschaufi** [comment]
Hi kernie, if you want to, you can sponsor through https://www.bountysource.com/issues/39043949-no-user-filter-for-logged-in-user-and-invoice-creation or later on via paypal/whatever you like.

I can implement it. You can contact me directly via my github username [at] gmail.com

**Comment by mattvenn** [comment]
I've posted a small bounty.
my requirement is just to be able to filter users when creating invoice.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
