### ISSUE TITLE
Select what is shown in PDF (XLSX, CSV,...) when exporting a list

### ISSUE THREAD

**Issue by blu-IT** [kimai/kimai#860]
#### Expected behaviour
I want to select which information is exported in the PDF file (e.g. date, time, activity, summary and description), but NO rate by hour, costs, total costs.

#### Actual behaviour
All the information above are integrated in the PDF file,

#### Steps to reproduce
Create / export a PDF

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
V. 1.1.0.1389 (stable)

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

Hello,

even if I can't select the informations I want (date, time, activity, summary and description) from the kimai browser backend for now (this would be a feature wish!!!), can you please point me to the variables/code I have to change to in "export_pdf2.php" ?

Thanks a lost!

Regrads

**Comment by blu-IT** [comment]
So, as I mentioned before: False alarm! I'm sorry for that!
Most things I want to select/deselect are possible. 
The only thing I did not get working: What I write down in "Description" is NOT shown in the PDF, only when I write it down in "Comment". Is it possible to print also the text in "Description" in the exported PDF file?

**Comment by kevinpapst** [comment]
Good to hear that you found the right buttons ;-)
If, after excessive testing, the description is still not exported, please file a new issue. Thanks!
