### ISSUE TITLE
Exported PDF does not show content of description and end/out time

### ISSUE THREAD

**Issue by blu-IT** [kimai/kimai#861]
#### Expected behaviour
Export a PDF and get shown the description of tasks.

#### Actual behaviour
When exporting a PDF file (list or table), the description of the tasks and the end time ("out") is not shown. Only the comment field is shown in the PDF. This happens only with the PDF file, **not** when exporting as XLSX or CSV file.

#### Steps to reproduce
Export a PDF file (list or table view).

#### Reproducable on demo.kimai.org?
yes

#### Kimai version 
V. 1.1.0.1389 (stable) & V. 1.2.1.1393 (dev)

Hello,

so I tested again (as mentioned in issue #860 before ;-) and noticed that no description is available in the PDF output when exporting a report. It happens **only** with the PDF files (list and table), not when exporting as XLSX or CSV. Is this a bug or a feature? ;-)

By the way: Thanks for this great piece of software! I like it very much!

Regards,

**Comment by q00d0** [comment]
+1

**Comment by blu-IT** [comment]
So I tested again with the hosted demo on https://demo.kimai.org : v1.2.1.1393

The problem still persits: The field _**description**_ is **not** shown in the PDF export.
Also the end **_time ("out")_** is **not** printed in both PDF versions  (list or table view).

Any solutions? 

Regards

**Comment by blu-IT** [comment]
Hi ptalus,

thanks a lot for your effort!

Will the changes also take effect on `extensions/ki_export/export_pdf.php` or do I have to/can I add the code 1:1 by myself?

Regards,
Ivan

**Comment by ptalus** [comment]
Second report was updated: now it shows description, but not the end time because there is not enough space to fit in the table. Maybe it is not necessary?

**Comment by blu-IT** [comment]
Hi,

I will test it and give you a feedback soon as possible, OK?
I will use descripton OR comment (using comment field was a workaround for the moment), so I hope that there will be enough space. 
My customers want to see the end time, so I need it.

Thanks!

Regards,
Ivan

**Comment by ptalus** [comment]
I added the end time.
![screenshot - 06222017 - 06 18 46 pm](https://user-images.githubusercontent.com/54216/27442163-238067d2-5778-11e7-87eb-e5f7a2e44ba0.png)

**Comment by blu-IT** [comment]
WOW, looks very good! Thank you!!!

I downloaded your code now (export_pdf.php and export_pdf2.php) and tested it on my server, but pdf export is broken now. It opens another browser tab and redirects me to

`https://tt.blu-it.de/extensions/ki_export/processor.php`

I'm not sure, if I mentioned clearly that I still work with Kimai V. 1.1.0.1389 (stable) and your code maybe is based on actual dev branch?

Regards,
Ivan

**Comment by ptalus** [comment]
I used dev branch v1.2.1.1393, it opened new tab for pdf before my updates.  

regards,
Pavel

**Comment by blu-IT** [comment]
OK, so I will have to wait until your code will be pushed? Just changing the two files you modified, won't work for me...?

**Comment by ptalus** [comment]
I patched files to be compatible with stable. 
[export.zip](https://github.com/kimai/kimai/files/1098133/export.zip)

**Comment by blu-IT** [comment]
It works now. Great job, thanks a lot!!!
