### ISSUE TITLE
Active Directory auth

### ISSUE THREAD

**Issue by Bo1337** [kimai/kimai#864]
Hi!

We are trying to use Kimai in our infra. Can You post example auth.php for Microsoft AD?

**Comment by simonschaufi** [comment]
does this help? https://github.com/kimai/kimai/issues/292#issuecomment-32280995

**Comment by Bo1337** [comment]
Nop.
I have problem configuring advanced options to access Windows AD with bind requets from Kimai.
I appreciate example of working config with 

My config:
<?php
return array(
    'host' => 'ldaps://server.local:636',
    'bindDN' => 'CN=Kimai binduser,OU=System Accounts,OU=Example,DC=domain,DC=local',
    'bindPW' => 'passishere',
    'searchBase' => 'dc=domain,dc=local',
    'userFilter' => '(sAMAccountName=%1$s)',
    'groupFilter' => '(&(objectClass=group)(member=%2$s))',
    'usernameAttribute' => 'sAMAccountName',
    'commonNameAttribute' => 'cn',
    'groupidAttribute' => 'cn',
    'mailAttribute' => 'mail',
    'allowedGroupIds' => array('kimai-access','Domain Users','Event','TimetrackerAccess'),
    'forceLowercase' => true,
    'nonLdapAcounts' => array('admin'),
    'autocreateUsers' => true,
    'defaultGlobalRoleName' => 'User',
    'defaultGroupMemberships' => array('Users' => 'User'),
);

**Comment by kevinpapst** [comment]
Are you using the AD auth class?
https://github.com/kimai/kimai/blob/master/libraries/Kimai/Auth/ActiveDirectory.php

Did you follow the documentation?
http://www.kimai.org/documentation/administrator/authenticator.html


2016-11-14 13:50 GMT+01:00 Bo1337 <notifications@github.com>:

**Comment by Bo1337** [comment]
> Are you using the AD auth class? https://github.com/kimai/kimai/blob/master/libraries/Kimai/Auth/ActiveDirectory.php
Yes - $authenticator = "activeDirectory"; in includes/autoconf.php

> Did you follow the documentation? http://www.kimai.org/documentation/administrator/authenticator.html
Did you mean - edit /kimai/libraries/Kimai/Auth/Ldapadvanced.php ?

**Comment by Bo1337** [comment]
Still looking for example auth.php with ActiveDeirecotry enabled.

**Comment by simonschaufi** [comment]
Sorry, I can't help. I have no possibility to test it.

**Comment by flacco** [comment]
Here is a working example for auth.php with Active Directory:

<?php
// auth.php
// Example Kimai Configuration 
// for ActiveDirectory Authentication
// Set in autoconf.php:
// $authenticator = 'activeDirectory';
return array(
    'host' => 'ldaps://server.invis-net.loc',
    'enhancedIdentityPrivacy' => 'false',
    'bindDN' => 'CN=Admin LDAP,CN=Users,DC=invis-net,DC=loc',
    'bindPW' => 'supersecret',
    'searchBase' => 'CN=Users,DC=invis-net,DC=loc',
    'groupFilter' => 'member=%2$s',
    'userFilter' => 'sAMAccountName=%1$s',
    'usernameAttribute' => 'sAMAccountName',
    'commonNameAttribute' => 'displayName',
    'groupidAttribute' => 'cn',
    'mailAttribute' => 'mail',
    'allowedGroupIds' => array('kimai')
);
?>

By the way we have packaged kimai for openSUSE: 

https://build.opensuse.org/package/show/spins:invis:unstable/kimai

Stefan (invis-server.org)

**Comment by timlegge** [comment]
After a lot of debugging, wireshark captures I have finally gotten a working config for my environment:

`<?php
return array(
    'host' => 'ldaps://ad-server.domain.com:636',
#    'enhancedIdentityPrivacy' => 'false',
    'bindDN' => 'CN=ldapbind,OU=Users,DC=domain,DC=com',
    'bindPW' => 'bind_password',
    'searchBase' => 'OU=Company Users,dc=domain,dc=com',
    'groupFilter' => 'distinguishedName=%2$s',
    'userFilter' => 'sAMAccountName=%1$s',
    'usernameAttribute' => 'samaccountname',  //appears to be case sensitive
    'commonNameAttribute' => 'displayname',
    'groupidAttribute' => 'memberof', //appears to be case sensitive
    'mailAttribute' => 'mail',
    'allowedGroupIds' => array('CN=Domain Users,CN=Users,DC=domain,DC=com'),
    'forceLowercase' => true,
    'nonLdapAcounts' => array('admin'),
    'autocreateUsers' => true,
    'defaultGlobalRoleName' => 'User',
    'defaultGroupMemberships' => array('Users' => 'User'),
);
?>`

The big issue I was seeing was that the Windows AD server was there appeared to be errors in the log like:

PHP Notice:  Undefined index: sAMAccountName in /var/www/kimai_1.1.0/liries/Kimai/Auth/Ldapadvanced.php on line 280, referer: https://timeentry.alc.ca/index.php

PHP Notice:  Undefined index: memberOf in /var/www/kimai_1.1.0/librarieimai/Auth/Ldapadvanced.php on line 338, referer: https://timeentry.alc.ca/index.php

After dumping the ldap results with var_dump I realized that the results were changed to lower case and once I change it as above it worked.

I now realize that the 
    'forceLowercase' => true,

 from the documentation example is likely causing the issue.

**Comment by timlegge** [comment]
Actually I have tested it and the 'forceLowercase' => true, has no impact on the ldap data returned.

It appears that ldap_get_entries http://www.nusphere.com/kb/phpmanual/function.ldap-get-entries.htm? frturns the attribute data in lower case

The attribute index is converted to lowercase. (Attributes are case-insensitive for directory servers, but not when used as array indices.)

**Comment by timlegge** [comment]
The patch below seems to correct the issue:
```

--- /tmp/src/kimai/libraries/Kimai/Auth/Ldapadvanced.php        2016-08-23 01:03:38.000000000 -0300
+++ /var/www/time/libraries/Kimai/Auth/Ldapadvanced.php 2017-02-08 16:28:35.187659136 -0400
@@ -277,14 +277,14 @@
         // bother the server any more.
         ldap_free_result($_ldapresults);
         $distinguishedName = $_results[0]['dn'];
-        $uidAttribute      = $_results[0][$this->usernameAttribute][0];
+        $uidAttribute      = $_results[0][strtolower($this->usernameAttribute)][0];
         $emailAddress      = '';
         $commonName        = '';
-        if (isset($_results[0][$this->mailAttribute][0])) {
-            $emailAddress = $_results[0][$this->mailAttribute][0];
+        if (isset($_results[0][strtolower($this->mailAttribute)][0])) {
+            $emailAddress = $_results[0][strtolower($this->mailAttribute)][0];
         }
-        if (isset($_results[0][$this->commonNameAttribute][0])) {
-            $commonName = $_results[0][$this->commonNameAttribute][0];
+        if (isset($_results[0][strtolower($this->commonNameAttribute)][0])) {
+            $commonName = $_results[0][strtolower($this->commonNameAttribute)][0];
         }

         // Now lets try to bind with the returned distinguishedName and the
@@ -331,8 +331,8 @@
         $groups = array();
         foreach ($_results as $result) {
             $resultGroups = array();
-            for ($i = 0; $i < $result[$this->groupidAttribute]['count']; $i++) {
-                $resultGroups[] = $result[$this->groupidAttribute][$i];
+            for ($i = 0; $i < $result[strtolower($this->groupidAttribute)]['count']; $i++) {
+                $resultGroups[] = $result[strtolower($this->groupidAttribute)][$i];
             }
             $groups = array_merge($groups, $resultGroups);
         }

```

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
