### ISSUE TITLE
Time and Date Issues

### ISSUE THREAD

**Issue by wordpress1209** [kimai/kimai#868]
Hi kimai team,

We are using kimai software from 6 months and now we have got some errors like below.

1. some of our users getting time stamp and date skipping ( like yesterdays working hours showing with today's date).

2. time of working hours are showing in negative. please check the below screenshot for more info regarding time stamps missing.

![screenshot](https://cloud.githubusercontent.com/assets/22099184/20353077/9595c7d4-ac3f-11e6-80d9-63043448e8c6.PNG)

Thanks

**Comment by kevinpapst** [comment]
Try the latest version if you don't use it yet

**Comment by wordpress1209** [comment]
Hi kimai team,

Thanks for reply. If we use the latest version will that lost my data ..?
And currently we are in v0.9.3, How to update it aplication to the latest
version without lost any data and all.

Thanks

**Comment by simonschaufi** [comment]
Of course your data should not get lost but I would still make a copy of your kimai installation and try it there first before doing it on the production server.

See: http://www.kimai.org/documentation/installation/updates.html

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
