### ISSUE TITLE
Can not logging in after install!

### ISSUE THREAD

**Issue by mattish91** [kimai/kimai#869]
#### Expected behaviour
Getting logged in.

#### Actual behaviour
Wrong username and/or password

#### Steps to reproduce
Fresh install, try to login.

#### Reproducable on demo.kimai.org? [yes|no]
No (not that I know of)

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.1.0 (stable)

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[19.11.2016 00:10:15] -- begin install ----------------------------------
[19.11.2016 00:10:31] -- installation finished without error ------------
[19.11.2016 00:11:33] login:as user

**Comment by simonschaufi** [comment]
without more details this is useless.
