### ISSUE TITLE
Screen for project activity budget - new feature

### ISSUE THREAD

**Issue by mariusl** [kimai/kimai#870]
#### Expected behaviour
A screen is needed to capture and edit the budget figures for activities per project
#### Actual behaviour
There is no way to edit that except by putting it in when a time entry is created

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
