### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by Madchatthew** [kimai/kimai#871]
I would like to add a couple of signature lines and date line to the pdf export file. How would one go about doing that? I am not a coder. I am good at placing things where they need to be with good instructions.

Thanks

Chad

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
