### ISSUE TITLE
Installation failed. Documentation inconsistent.

### ISSUE THREAD

**Issue by new-gen23** [kimai/kimai#872]
I have tried to install from the git by cloning a version to /var/www/html/kamai
I configured the nginx to use /var/www/html/kamai or /var/www/html/ as root.

Upon surfing with a firefox to the Webserver, I get a white page. No redirect to installation.

Furthermore, the Install.md says I would have to delete "all" except for the autoconf.php in /includes.
-> There is no autoconf.php

How am I supposed to install the tool?

Nginx sites_available/default:
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html/kimai;
        index index.php index.html index.htm index.nginx-debian.html;

        server_name _;
        location / {
                try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                include fastcgi_params;
        }
}
```

PHP-fpm is listening on port 9000 and reachable.
Neither nginx nor php-fpm throw an error.

**Comment by new-gen23** [comment]
Ok, it was a nginx installation problem. 
apt-get install php7.0-fpm 
instead of
php-fpm
solved the problem.

Furthermore, 
`include snippets/fastcgi-php.conf;`
was missing in nginx sites_available/default.

**Comment by simonschaufi** [comment]
Probably you were looking at the Update part, not the installation. For installation you don't have to delete anything ;)
How about improving the [documentation](https://github.com/kimai/documentation)? Please help us to make it better!
