### ISSUE TITLE
US date format

### ISSUE THREAD

**Issue by userzen** [kimai/kimai#873]
This is not a programming issue, but a user question--it appears the forum is no longer functioning so I apologize for posting a simple user question here.  I'm using the latest version of Kimai.  I've used Kimai for a while, just installed the latest version, am not a programmer.  I tried to edit the date format in Advanced on the admin tab in order to use common USA date format month-day-year.  I have broken the functionality however and can't get back to the defaults.  Can someone please post the default values?  Also if someone has a US date formatting that works in Date format of the timespan, Date format for the datepicker, Date format of datepicker in PHP, Date format for tables.  Thank you

**Comment by simonschaufi** [comment]
Just have a look at the demo installation ;)
US date format is not yet fully possible. Sorry for that.

**Comment by userzen** [comment]
That worked--back to defaults.  Thank you!  Really enjoying this great time software!

**Comment by sollermun** [comment]
Will this issue with the date picker going by day/month instead of month/day be fixed? It is very aggravating.

**Comment by colincci** [comment]
Here is my vote for correcting the date picker problem.  All the great work on allowing universal date formatting is, unfortunately, essentially useless due to the date picker problem.  Thanks for an otherwise GREAT piece of software!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
