### ISSUE TITLE
How to add a custom field in Project-add project

### ISSUE THREAD

**Issue by samaresh55** [kimai/kimai#877]

**Comment by samaresh55** [comment]
Hi,

Can any body help me on this??

**Comment by janvanl** [comment]
Please give a more detailed description of what you want

**Comment by samaresh55** [comment]
Hi,
Thank you for your reply!! By this time I have done with few changes by still I need some help from your end. Let me explain here.

I have added one filed in Edit Entry project:   http://prnt.sc/dujlak
I have entered on row on DB table “kimai_projects” -> EstimatedTime

My Estimated time field is working fine and all the values are getting save in DB
**Expectation:** 
Need to display the same value (EstimatedTime) from DB here http://prnt.sc/dujrpq

**Change1**
kimai\templates\scripts\floaters\add_edit_project.php     line 52

					<li><label for="EstimatedTime"><?php echo $this->kga['lang']['EstimatedTime'] ?>*:</label>
                        <?php echo $this->formText('EstimatedTime', $this->EstimatedTime, array('required' => 'required')); ?> </li>
						
**Change2**   
kimai\language\en.php        line 42
"EstimatedTime" => "Estimated Time",

**Change3**
kimai\core\floter.php       line 173
$view->assign('EstimatedTime', $data['EstimatedTime']);

**Change4**
kimai\core\processor.php       line 306
$data['EstimatedTime'] = $_REQUEST['EstimatedTime'];

**Change5**
kimai\libraries\Kimai\Database\Mysql.php   line 572
$values['EstimatedTime'] = MySQL::SQLValue($data['EstimatedTime']);

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
