### ISSUE TITLE
Desktop/offline version

### ISSUE THREAD

**Issue by wimpunk** [kimai/kimai#88]
Hi,

Is there any possibility to work offline with kimai?  I think the best solution would be to have an import possibility so everyone could provide his own import conversion for his own time tracker.

regards,

wimpunk.

**Comment by TheWanderingCoder** [comment]
+1

**Comment by Mutz** [comment]
+1

**Comment by taikedz** [comment]
+1. Wondering if this could be more interestingly be implemented as a synchronized solution - a sort of "subscribe to a timer" model?

This would allow a client/offline Kimai to sync to a subset of a medium Kimai's timers, which could in turn sync with a central Kimai, when deployed across a large org...

**Comment by seevee** [comment]
+1

**Comment by HugoVonk** [comment]
+1

**Comment by simonschaufi** [comment]
Without financial support we won't do this. Please make an investment on bountysource to support further development!

**Comment by piflixe** [comment]
Since we use kimai with our small company we could offer spending €50 for that feature. But it needs to clear which operating systems would be supported and so on. Maybe there are more users willing to finance the development?

**Comment by buscon** [comment]
i would be willing to finance this feature. as i am an individual, i can offer 20€

**Comment by gabrielrota** [comment]
+1

**Comment by xakiru** [comment]
Hello guys, I've made a desktop version for time tracking almost like a widget. So I should be able to add the offline support if needed.
https://github.com/xakiru/KimaiDesktop

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
