### ISSUE TITLE
"â‚¬" is printed instead of "€"

### ISSUE THREAD

**Issue by q00d0** [kimai/kimai#883]
#### Expected behaviour
print the €-sign on an export instead of "â‚¬"
#### Actual behaviour
"â‚¬" is printed instead of "€"
#### Steps to reproduce
export something as PDF or XLS
#### Reproducable on demo.kimai.org? [yes|no]
no
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
dev 1.1.0.1389

####PHP.ini
default_charset = "UTF-8"

####vars.php
$kga['utf8'] = 1; 

Can you please tell me where is the mistake in the configuration?
Kimai keeps printing this "â‚¬" instead of the €-sign.

**Comment by janvanl** [comment]
Did you check the locales on the server?

**Comment by q00d0** [comment]
the command "locale" outputs this:

`LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
`

**Comment by kevinpapst** [comment]
It might be related to the font, which is used to render the PDF.
I remember some changes to the PDF and it worked for me, but maybe that broke it for you.
Please check out the changes done in #802 and revert them in your installation.

**Comment by q00d0** [comment]
Ok, I've replaced "helvetica" with "freesans" in these files: export_pdf.php and export_pdf2.php. It's still not working...

**Comment by q00d0** [comment]
So I've discovered why the €-sign is wrong.

![bug](https://cloud.githubusercontent.com/assets/11162933/22168106/d223b0c2-df6a-11e6-8d33-bf2200754a6f.jpg)

**Comment by janvanl** [comment]
What was wrong then?

**Comment by q00d0** [comment]
If you look at the picture I've uploaded there is a yellow marked input field. There should be the €-sign, but it wasn't there....

**Comment by janvanl** [comment]
Sorry had images blocked in the browser, now I see!
