### ISSUE TITLE
Bad preferences dialog behavior

### ISSUE THREAD

**Issue by jlquinn** [kimai/kimai#884]
#### Expected behaviour
Preferences dialog closes with no message.

#### Actual behaviour

Closing preferences complains that I didn't reenter a password.

#### Steps to reproduce
I created a user in the demo as admin.  I then logged out and logged into the user.  I opened the preferences dialog as the user, made no changes and hit OK.

It complains that I didn't enter the password a second time. It had filled in the new password field with the user's current password.

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
 v1.2.1.1393 - © 2006-17 by the Kimai-Team:

**Comment by simonschaufi** [comment]
Well, you either leave the password field empty, OR you fill in a new password and confirm that. That behavior is totally correct.
