### ISSUE TITLE
Request: Weekly hour input

### ISSUE THREAD

**Issue by izznogooood** [kimai/kimai#885]
This is a feature request: I would like to be able to input a whole week of work at a time.

Example: I worked for the same customer 0800-1600 for 1 week.

One input that makes all the lines would be great. This happened now as i worked for the same customer The whole of desember. Then i have to make an input every day...

**Comment by simonschaufi** [comment]
Hi, This is a quite unique feature request as nobody works exactly every day from point 8 to point 16. You always have +-5min difference. In my opinion this request is very low prio as we have a lot more pain in other areas that should be optimized right now.

**Comment by InteractiveLoope** [comment]
Hi, I also want too see this feature in Kimai, sometimes we work on a project for weeks and its the same amount of time spent each week. I know you got a lot to do, but please, this would be a great addition to Kimai :)

Thanks

**Comment by simonschaufi** [comment]
Hi together!
We would love to help you solve your problems!

How do you imagine the input form? The more input you give us, the easier it will be to implement it.

If it has such a high value for you, you have the possibility to sponsor this feature. You can use bountysource, paypal or whatever you want.

**Comment by simonschaufi** [comment]
@InteractiveLoope if you have big need for this feature, please sponsor it! Thanks
