### ISSUE TITLE
Time Tracker Android gives a webpage

### ISSUE THREAD

**Issue by janvanl** [kimai/kimai#886]
Hi
Expected behaviour, I had Kimai installed once before and the Android app gave me a very simple way to start/stop tracking with large buttons.
Now I can only use the extra mobile site on a browser.

Actual behaviour
Now I get a full webpage that is very small so hardly readable, 

Steps to reproduce
Install the latest Kimai on a server, install the Android app from F-Droid on a Android with jelly bean (I know it is a bit older.)

Kimai version stable 1.1.0

I still think Kimai is superb!

**Comment by simonschaufi** [comment]
Hi, thank you for using kimai!
We are not maintaining F-Droid. Please contact the developer directly. We only maintain the jQuery mobile version of kimai.

**Comment by janvanl** [comment]
Misunderstanding, I use the jquery mobile version now great job! Just starting to track my activities.
