### ISSUE TITLE
Custom extension not present

### ISSUE THREAD

**Issue by gbozzetti** [kimai/kimai#888]
Hi guys,

i'm trying to create my custom extension: i copy the demo folder and rename it with my custom name, after i change all the variables in config.ini and the name of variables inside php and js files.

But when i return on admin page no tab is showing and in the debug i have the error: global_role_allows: Unknown column 'calendar_ext-access' in 'where clause' (#1054) 

How can i activate my extension in the right way?

Thx

**Comment by kevinpapst** [comment]
This is a stupid "bug" in the plugin architecture.
You have to create the column "calendar_ext-access" in the table "globalRoles" and fill it accordingly, then it should show up

**Comment by gbozzetti** [comment]
Do you mean in extensions/ki_adminpanel/templates/scripts/globalRoles.php?

**Comment by kevinpapst** [comment]
Nope, you have to change the database

**Comment by gbozzetti** [comment]
Yep, now works.... i agree "stupid bug" :)
