### ISSUE TITLE
Global Time & Date Field Only for Admin

### ISSUE THREAD

**Issue by samaresh55** [kimai/kimai#890]
Hi,

Is there any way to add a separate field or in the exiting field of time sheet for Date and Time field ( http://prnt.sc/dv3kmj ) where admin can overwrite the user's entry??

Thank you in advance !!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
