### ISSUE TITLE
How to install Kimai on Azure? Is it Possible?

### ISSUE THREAD

**Issue by JZalazar** [kimai/kimai#891]
Hi there,

I m trying to install Kimai on Azure, and i m not finding the way, could you help me with this? Or please give me some documentation in case that exists some...

Thanks a lot!
Jorge

**Comment by JZalazar** [comment]
Hi there,

I m trying to install Kimai on Azure, and i m not finding the way, could you help me with this? Or please give me some documentation in case that exists some...

Thanks a lot!
Jorge

**Comment by jfilz** [comment]
Yes you should be able to. See: 
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-php-get-started

QUOTE: This tutorial shows you how to create, configure, and deploy a PHP web app for Azure, and how to configure Azure App Service to meet the requirements of your PHP web app.
