### ISSUE TITLE
BUZZER_STOP_TRIGGER not working

### ISSUE THREAD

**Issue by gbozzetti** [kimai/kimai#893]
In config.ini i set BUZZER_STOP_TRIGGER value with my own function "my_ext_triggerSTP();".

In func.js i set the function 

my_ext_triggerSTP() {
alert('test');
}

when i start and stop the buzzer no alert is showed.

ps. if i call my_ext_triggerSTP() in $(document).ready(function) the alert is showed.

What am i doing wrong?

Thx

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
