### ISSUE TITLE
Consecutive invoice numbering

### ISSUE THREAD

**Issue by tectanus** [kimai/kimai#894]
Dear kimai-team,

is it possible to achieve a consecutive numbering of invoices?
As an example: I'm going to finish 4 projects this January, 3 of them are for customer A, 1 for customer B. The latter is finished just before the 3rd project of customer A. The invoice numbering should look like 17-01, 17-02, 17-04 for customer A and 17-03 for customer B.  If such a consecutive numbering is possible, what has to be done? 
A step beyond would be having such consecutive numbering per user - conceivable?

Thanks.

**Comment by simonschaufi** [comment]
I was in the process of making this feature but didn't have the time to finish it yet. See #159 
If you want to sponsor this feature, that would be great. I would highly appreciate any donations!
