### ISSUE TITLE
Non-billable times

### ISSUE THREAD

**Issue by tectanus** [kimai/kimai#896]
Dear kimai-team, 

sorry for another stupid question - I'm trying to evaluate whether your very promising tool is suitable for my needs...

If a project needs more working input than a customer is willing to pay for, I need to mark those plus times: They had been fulfilled (I need to see them in following-ups) but they aren't billable (they must not appear on an invoice). Can kimai help in that situation?

Thanks for your patience.

**Comment by simonschaufi** [comment]
Hi,
unfortunately this is not yet implemented. What you could do is to give the items a different status but the thing is, that status is not used anywhere as a filer.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
