### ISSUE TITLE
Editing activity for entry doesn't seem to work

### ISSUE THREAD

**Issue by heiglandreas** [kimai/kimai#897]
#### Expected behaviour
When a user edits one of her entries and assigns a different activity that new activity should be set for that entry after hitting "OK"

#### Actual behaviour
When a user edits one of her entries and assigns a different activity after hitting "OK" he previous activity is still assigned

#### Steps to reproduce
Edit an entry, change the activity and click "OK"

#### Reproducable on demo.kimai.org? [yes|no]
no
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[17.01.2017 10:18:45] KSPI axAction (heiglandreas): reload_timeSheet 
[17.01.2017 10:18:45] timeEntry_edit: Column 'fixedRate' cannot be null (#1048) 
[17.01.2017 10:18:45] timeEntry_edit: 2 
[17.01.2017 10:18:45] KSPI axAction (heiglandreas): add_edit_timeSheetEntry 
[17.01.2017 10:18:42] KSPI axAction (heiglandreas): bestFittingRates 
[17.01.2017 10:18:42] KSPI axAction (heiglandreas): budgets 
[17.01.2017 10:18:29] KSPI axAction (heiglandreas): reload_activities_options 
[17.01.2017 10:18:29] KSPI axAction (heiglandreas): add_edit_timeSheetEntry 

Might this be related to #814 , #807 and #697?

**Comment by heiglandreas** [comment]
Problem can be fixed with this SQL-Snippet:

```
ALTER TABLE kimai_timeSheet MODIFY fixedRate decimal(10,2) NULL DEFAULT '0.00';
```

But that will allow ```NULL``` values to appear between the decimals and I'm not sure what that might cause later! Looks like the default values are not used. Might there be an empty string passed to the DB instead of a ```NULL```-value?

**Comment by simonschaufi** [comment]
I think you have an old version of kimai. That bug should be fixed since a long time already.

**Comment by heiglandreas** [comment]
Hi @simonschaufi- I know that the bug *should* be fixed. As I'm running this in a corporate environment I'm trusting in that the information on the website as well as on [github](https://github.com/kimai/kimai/releases/) is correct and the latest **stable** release is 1.1.0.1389 - So this is the latest release and in there the issue does not seem to be fixed. 

A *long time™" ago would then mean since last August. Can you perhaps point me to the actual commit where it was fixed? That might be of more value to me than a simple "update to the latest master branch". Because that boils down to "we don't care about the releases any more". If so, then please state that on the website.

**Comment by heiglandreas** [comment]
According to the applications internal update-checker I'm on the latest release: 
![bildschirmfoto 2017-01-26 um 13 26 40](https://cloud.githubusercontent.com/assets/91998/22331360/4ecf9852-e3cb-11e6-888d-b3a0fbb652cd.png)

**Comment by simonschaufi** [comment]
Sorry, we don't release kimai so often. Here is the commit:
https://github.com/kimai/kimai/commit/3a13dfda26f09abb37b21e579a5494a79b0a7e09
Of course we care about releases but we don't just make a new release when 1 bug is fixed. We as kimai team also work on kimai in our free time, hence the slow development circle...

**Comment by heiglandreas** [comment]
Thanks @simonschaufi for the relevant commit! 

> Of course we care about releases but we don't just make a new release when 1 bug is fixed. 

Why not? Being a PHP-Developer and Maintainer of different OpenSource-Libraries myself I found that - depending on the severity of a bug - a new (bugfix)-release after just one bugfix can make sense. It keeps the dev-version very close to the latest release and shows to non-dev people that the application is actively and that fixes are rolled out regularily.

> We as kimai team also work on kimai in our free time, hence the slow development circle...

Working in your spare time on the application does not necessarily need to result in a slow development circle. I'm ususally tagging a new (bugfix-)release either after every bugfix (or after several when I merge them within a day or week or so). But I admit that I don't know what effort is involved in tagging a release for kimai. But I'm happy to assist in checking whether there are ways to make that more easy via automation or by creating scripts! Feel free to ping me! Just recently I [wrote about automated packaging on tagging](https://andreas.heigl.org/2017/01/18/building-a-phar-automated/) using Travis-CI

**Comment by norwegianblue-nz** [comment]
So reading this thread - if an issue is closed, the fix isn't necessarily in the latest stable ? 
To get the all the bug fixes, we need to get the latest master from git? 
(I was looking for the same commit as heiglandreas)
