### ISSUE TITLE
How to write a condition for Time Field

### ISSUE THREAD

**Issue by samaresh55** [kimai/kimai#898]
Hi,
I want to add a condition for time field in "add_edit_timeSheetEntry.php" e.g. as below. Can I get some help for this??

if project id = 16
{
$('#start_time').val("08.30").timepicker(configuration); 
$('#end_time').val("17.30").timepicker(configuration); }

**Comment by samaresh55** [comment]
Hi,

Can anybody help me on this??

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
