### ISSUE TITLE
timesheet entries of invisible projects are still listed

### ISSUE THREAD

**Issue by enricop** [kimai/kimai#901]
#### Expected behaviour
When a project is set to "not visible" from its floater, the associated entries in "timesheet" tab should disappear.

#### Actual behaviour
The project is removed from projects sublist but its entries are still listed in Timesheet

#### Steps to reproduce
Unset "Visibility" flag for a project with has some recorded entries

#### Reproducable on demo.kimai.org?
yes

#### Kimai version
github master

**Comment by enricop** [comment]
What does happen if I mark in the database the field "filter" to 1 for a project?

Moreover, looking at this issue (https://github.com/kimai/kimai/issues/904), it is possible to mark as cleared single entries in the export panel. Are they still visible in timesheet then?

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
