### ISSUE TITLE
GPS Location

### ISSUE THREAD

**Issue by nathanmemoria** [kimai/kimai#902]
Feature Request:

Kimai is great, but one missing feature that keeps us from switching over is GPS location tracking for start and stop time. This is very easy / quick to implement with JS, but it would need to be stored in the database.

This would be amazing! Thanks!

**Comment by simonschaufi** [comment]
do you mean longitute and latitute or what is gps location for you?

**Comment by nhadsall** [comment]
@simonschaufi, yes that would be a great start. The idea is to make sure people clock in and out on site or not.

**Comment by nathanmemoria** [comment]
@simonschaufi, yes that would be a great start. The idea is to make sure people clock in and out on site or not.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
