### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by MichalKononenko** [kimai/kimai#903]
Can someone please provide me with a link to this application's JSON API documentation?

**Comment by simonschaufi** [comment]
There is non yet but when you can look at [kimai mobile](https://github.com/kimai/kimai-mobile) to see how it works

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
