### ISSUE TITLE
can't close a selection of timesheet entries

### ISSUE THREAD

**Issue by mattvenn** [kimai/kimai#904]
Sorry if this is the wrong place to post this question - I saw from the website that the forum is closed and users should post questions/issues here.

My problem:

After invoicing a customer I want to make sure the entries are not used in another invoice. I want to close the project or close the entries. I see in the invoice page a drop down select to choose 'only open' entries.

The only way I can see to close an entry is to edit each entry in turn from the timesheet, go to advanced tab and click the 'cleared' button.

Is there no way to close a selection of entries at once? I did this in the database:

update kimai_timeSheet set cleared = 1 where projectID = 5;

Thanks for the great software!

**Comment by simonschaufi** [comment]
Hi, I know this is horrible usability, I also don't like the current situation.
The fastest way via the kimai app is the export tab and click the last bubble. When it's checked, the entry is closed.

**Comment by mattvenn** [comment]
great! Thanks a lot, just what I wanted to find out!
