### ISSUE TITLE
GUI sync issues with Start/Stop button.

### ISSUE THREAD

**Issue by ghost** [kimai/kimai#905]
Expected behaviour:

Press start button. Row in table appears, starts recording and start button changes to stp button.

Actual behaviour:

Press start button. The button changes to stop then quickly back to start again, no new row doing recording. If I refresh the page everything is as it should be.

Note: Most times the button works correctly, its jut every now and again that is fails

Steps to reproduce:
It's obviously a timing issue. I'm using Firefox not sure if that has anything to do with the issue or not. 

Kimai version Stable 1.1.0

**Comment by simonschaufi** [comment]
This is a known bug.

**Comment by tarceri** [comment]
Is there an existing issue with more information? It really bugging me so would be happy to try fix it if you could point me in the right direction.

**Comment by tarceri** [comment]
This is really driving me nuts. I'll offer $US150 to anyone who can fix this and satisfy the following.

1. Provide me with an invoice (I can provide a template for you).
2. Fix must work in firefox.
3. Fix must be in a stable release (hopefully 1.1.1) before payment is made.

**Comment by simonschaufi** [comment]
I think this is related: #493

**Comment by tarceri** [comment]
I meant tax invoice, so I can write the payment off as a business expense. I'd also like to add another $50 to my initial reward for a total of $US200, and offer payment via crypto coin if preferred since this will avoid expensive international transfer fees via normal banking.

**Comment by RStudios** [comment]
The pull request fixes this issue on the buzzer

**Comment by tarceri** [comment]
I've been running the most recent pull request for over a week now and everything is working fantastic. Great to be rid of this bug, would be great if the fixes can make it into master.

**Comment by simonschaufi** [comment]
Let me test it in dev branch for a while but it looks great so far!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
