### ISSUE TITLE
timeEntry_edit: Column 'rate' cannot be null (#1048)

### ISSUE THREAD

**Issue by CC-Netzwerk** [kimai/kimai#909]
#### Expected behaviour
Die Änderung wird übernommen.

#### Actual behaviour
Bei der Veränderung des Projektes oder der Tätigkeit werden diese bei einem bestehenden Eintrag nicht nachträglich verändert. Im Debug-Log wird gezeigt: timeEntry_edit: Column 'rate' cannot be null (#1048)

Änderung des Standardwertes auf NULL löst das Problem.

**Comment by simonschaufi** [comment]
this is already fixed in latest master
