### ISSUE TITLE
Bugg in no-bo translasion and export to exel not working

### ISSUE THREAD

**Issue by atlem** [kimai/kimai#910]
#### Actual behaviour
Cant add new customer when changing to No-bo  translation. error in local in debug
exel export currently not working
#### Reproducable on demo.kimai.org? [yes|
yes
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
current
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
look in demo page debug. timestamp 05.02.17-09:09:03

**Comment by simonschaufi** [comment]
Cannot reproduce the add new customer bug.
Excel Export is already fixed.
