### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by atlem** [kimai/kimai#911]
have some requests 

1.  add posebility to change local time to date.  to (No-Bo)

2.  add driving distance (home adress -> projectsadress) = km + km value rate = output
     or the easy way (km distance db input in projects)+(km value rate in user setting)
3. time sheet print sort by user . user1 sheet 1  user 2 sheet 2.
4. show project title . username title. customer title. sort by user/customer/progject. when exporting

great work this is awsome

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
