### ISSUE TITLE
TimeTrapp Login and Permissions issue

### ISSUE THREAD

**Issue by Hanner72** [kimai/kimai#915]
Hello,

First, sorry for my english.

I have installed KIMAI on my own server, which is also running.
Now i want to use the app TimeTrapp.

When I enter the data from my server and my login data
the app says:

> ERROR
> Error while calling Kimai [authenticate]:
> !DOCTYPE HTML PUBLIC
> "-//IETF
> etc...

![screenshot_2017-02-10-07-55-20](https://cloud.githubusercontent.com/assets/25680545/22817275/8c0a42e8-ef66-11e6-89f0-429bdbb9da64.jpg)

Kimai on my server: http://zeit.strabag-sport.at
User: demo1
PW: demo1

Test on demo.kimai.org:
Everything is working fine

Kimai version 1.1.0

Please help me.

Thanks

**Comment by simonschaufi** [comment]
Hi, thank you for using kimai. Sorry to tell you that we are not responsible for any 3rd party app. We are just maintaining kimai and a jquery mobile version, nothing else. Please get in contact with the app developer directly.

**Comment by Viras-** [comment]
@simonschaufi you can also mention me in such issue and I will take care of it - at least if it is regarding the TimeTrapp App.

**Comment by simonschaufi** [comment]
ok, will do so! what exactly is the problem here?

**Comment by Viras-** [comment]
the problem was tricky to identify. The App does not send a "Referer" header (which actually is correct, since the app has no URI per se) - however the webserver of @Hanner72 requires us to send the Referer header when sending a POST request. Thus the app needs to be modified.

**Comment by simonschaufi** [comment]
A webserver who **requires** a referer? What?

**Comment by Viras-** [comment]
Well there is the http Referer header, which is actually correct to be sent by a POST request (thus stating the origin of the request). This particular configuration only allows POST requests if the Referer is set correctly.
