### ISSUE TITLE
Add possibility to get extra time of the user

### ISSUE THREAD

**Issue by ilstarno** [kimai/kimai#916]
For example the days of work are from monday.
If the user works saturn day it should be recognized as an extra time.
The normal hours of work are from 8 ambto 4 pm and if the user works till 6 or 7 pm it should calculate extra time and get and different pay rate.

**Comment by simonschaufi** [comment]
This feature has been requested multiple times already but is a huge effort to implement. Since kimai is coded in our free time, we only implement those huge features with sponsorships.

**Comment by simonschaufi** [comment]
duplicate of #678

**Comment by kevinpapst** [comment]
find out more at #1088
