### ISSUE TITLE
Different hourly rate per project for activities.

### ISSUE THREAD

**Issue by sollermun** [kimai/kimai#919]

**Comment by sollermun** [comment]
I am wondering if we could have something like Fixed Rate, for activities by project, but for hourly rates. I generally have the same categories of activities for each project, but want to charge different hourly rates for different projects.

I am using Kimai 1.1

**Comment by guysoft** [comment]
Hey,
I have this issue - there is only an option for "fixed rate" Should I repopen? Is there an answer somewhere?
