### ISSUE TITLE
NEW UI

### ISSUE THREAD

**Issue by ilstarno** [kimai/kimai#922]
The Ui of kimai its an little bit old and i suggest to develop an new one based on twitter bootstrap 4.
This way it can be accessed on any kinda of device

**Comment by simonschaufi** [comment]
Feel free to make a pull request! There will be a huge party when I merge it :tada: Since many weeks I'm actually also thinking about a new UI based on google material design. This is what I found: https://mdbootstrap.com/product/material-design-for-bootstrap-pro/
A UI like this would be awesome.

**Comment by mattonit** [comment]
@simonschaufi I'm so glad to see you're interested in MDBootstrap. Please, let me know if you need help. We'll be more than happy to help you

**Comment by simonschaufi** [comment]
@mattonit did you come here because of a referer information or how did you find out?
Right now the first thing we need are some basic ideas how the new ui could look like. I will come back to you sooner or later :)

**Comment by mattonit** [comment]
We use dedicated service, that's why we can always be in place when someone needs our help

**Comment by simonschaufi** [comment]
I wrote your company an Email some days ago but didn't get any response yet :(

**Comment by mattonit** [comment]
Could you please send me an email to b.malanowski@mdbootstrap.com?
