### ISSUE TITLE
HowTo set rights that customers can only export projects of them?

### ISSUE THREAD

**Issue by q00d0** [kimai/kimai#923]
Hey guys,

I want to configure kimai that customers can log in into kimai and see all employees and only projects and activitys of them.

So I've tried to create a group "worker" and "customer" and a group for every single "customer_id". All employees are member of the group "admin" and "worker".
There is only one activity called "design" - it's connected to all groups.
There are two projects. Project-A and Project-B. Project-A is for customer A and Project-B is for customer B.
So every project is connected to the designated customer and to the groups admin and worker.
The customer is member of the group customer and member of the group with his customer_id.

And I want that customers can only use the export function, nothing more.

It is not working like i expected it. Can you tell me where I misconfigured Kimai?

**Comment by simonschaufi** [comment]
Hi,
don't use "users" as customers. Customers itself are also users. Just give them a password and they can login!

**Comment by q00d0** [comment]
Thanks Simon for you quick answer and solving my problem 👍 
It was a fallacy of me.
