### ISSUE TITLE
 When we include a new note, the date displayed is always that of the day after

### ISSUE THREAD

**Issue by lucasgonzalesenginebr** [kimai/kimai#925]
#### Expected behaviour
Show current date

#### Actual behaviour
When we include a new note, the date displayed is always that of the day after, so we have to change the date every time manually
#### Steps to reproduce
Create a new point in the timesheet tab
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389
![kimai](https://cloud.githubusercontent.com/assets/25927683/23164768/9705370c-f817-11e6-9dbb-5eb993a589c4.JPG)

**Comment by simonschaufi** [comment]
could this be a timezone issue? are you on the same time as the server?

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
