### ISSUE TITLE
Buzzer time added in total

### ISSUE THREAD

**Issue by danielvandenberg95** [kimai/kimai#927]
#### Expected behaviour
I'd expect (or like) the time on the buzzer to be added up to the total, as shown in the field up top (of which I could not find the name).
[Imgur](http://i.imgur.com/Dehq9z5.png)

#### Actual behaviour
The time is only added after stopping the buzzer.

#### Steps to reproduce
Start the buzzer and uh, don't see the time tick up?

#### Reproducable on demo.kimai.org? [yes|no]
Yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
All versions

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
None

This feature would help me a great deal to keep track of how long I've already been working on a day (so to stick to 8-hour work days). I'd expect others would feel the same way.

If I'd get how the code works I'd create a pull request, so maybe with some help to get started I could look into making one, but honestly I don't have a clue where I would start.

**Comment by simonschaufi** [comment]
Hi Daniel!
Yes, this would be a great feature! Do you have some JavaScript coding skills? If so, you can look what is going on in those 2 files: https://github.com/kimai/kimai/tree/master/js

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
