### ISSUE TITLE
time zone support

### ISSUE THREAD

**Issue by ofarrill** [kimai/kimai#929]
#### Expected behaviour
Displaying the time should be translated in to the current local time. The local time zone might change often.

#### Actual behaviour
Time is always calculated from the same time zone.

#### Steps to reproduce
Switch your client OS to another timezone and do something in kimai.

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
all

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
n/a

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
