### ISSUE TITLE
Installer fails when checking requirements

### ISSUE THREAD

**Issue by tbhartman** [kimai/kimai#930]
#### Expected behaviour
it should check requirements

#### Actual behaviour
it does not check requirements.  on the "check requirements" step, I get this in the browser console:

```
Uncaught SyntaxError: Unexpected token <
    at Object.success (installscript.js:110)
    at c (jquery-1.9.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.9.1.min.js:2)
    at k (jquery-1.9.1.min.js:4)
    at XMLHttpRequest.r (jquery-1.9.1.min.js:4)
```

I get that because `processor.php?axAction=checkRequirements` returns HTML in what should be a pure javascript string (because it gets `eval`ed):

```
<br />
<b>Notice</b>:  A non well formed numeric value encountered in <b>D:\www\kimai2\installer\processor.php</b> on line <b>38</b><br />
$('#installsteps button.sp-button').hide();$('#installsteps button.proceed').show();resetRequirementsIndicators();$('#installsteps button.sp-button').hide();$('#installsteps button.proceed').show();
```

This happens in the `return_bytes` function:

```php
function return_bytes($val) {
    $val = trim($val);
    $last = strtolower($val[strlen($val) - 1]);
    switch ($last) {
        // The 'G' modifier is available since PHP 5.1.0
        case 'g':
            $val *= 1024;
        case 'm':
            $val *= 1024;
        case 'k':
            $val *= 1024;
    }

    return $val;
}
```

I add an if statement to strip the M/G/K off the string:

```php
function return_bytes($val) {
    $val = trim($val);
    $last = strtolower($val[strlen($val) - 1]);
    if ($last) {
        $val = substr($val,0,strlen($val)-1);
    }
    switch ($last) {
        // The 'G' modifier is available since PHP 5.1.0
        case 'g':
            $val *= 1024;
        case 'm':
            $val *= 1024;
        case 'k':
            $val *= 1024;
    }

    return $val;
}
```

and now it works

#### Reproducable on demo.kimai.org? [yes|no]
not sure if I can install there?

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Installation v1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
no log in `logfile.txt`

**Comment by simonschaufi** [comment]
How does the value of the variable look like? I installed kimai plenty of times already and never had that issue

**Comment by tbhartman** [comment]
`$val == '128M'`
`$last == 'm'`

I am getting just a notice
`<b>Notice</b>:  A non well formed numeric value encountered in <b>D:\www\kimai_1.1.0\installer\processor.php</b> on line <b>40</b><br />`
but the javascript that follows appears valid (and would give me the "proceed" button).

I am using PHP Version 7.1.2.

**Comment by simonschaufi** [comment]
Is this PHP 7.1 specific? I'm using PHP 7.0.
