### ISSUE TITLE
Update results to inconsitent data

### ISSUE THREAD

**Issue by Starkmann** [kimai/kimai#931]
#### Expected behaviour
Data is consistent after upgrade
#### Actual behaviour
After upgrading from 0.9.2.1306 to 1.10 if have the situation that some projects/clients have no title.
Also some comments are missing.
The upgrade wizard shows no problems.

#### Steps to reproduce
Upgrading from 0.9.2.1306 to 1.10

#### Reproducable on demo.kimai.org? [yes|no]
Cant do it.

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.10

**Comment by simonschaufi** [comment]
your logfile records would be really helpful in this case, otherwise we cannot help you as upgrade went without errors as you said.

**Comment by Starkmann** [comment]
[logfile.txt](https://github.com/kimai/kimai/files/845258/logfile.txt)

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
