### ISSUE TITLE
Everything gone?!?!

### ISSUE THREAD

**Issue by ddewilt** [kimai/kimai#932]
#### Expected behaviour

I installed a new version. I copied all of the contents and replaced everything just like the documents said and I made a backup of the autoconf.php. I also changed the permissions of the folders.

#### Actual behaviour

When I went to log in, I get a http 500 error. So now, all my projects are gone? 
I don't know what to do, please help me!

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]

My old version was, wich I saw on the 'About' page, is version 1.0.1..... 

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
My log file is still intact, but nothing I can see what is relevant...

Who can help me with this...
[logfile.txt](https://github.com/kimai/kimai/files/851819/logfile.txt)

**Comment by timlegge** [comment]
Look in your webserver log file to see if there are any errors

**Comment by ddewilt** [comment]
Thank you for your comment, I just fixed it!! I deleted everything except the autoconf.php, dropped the new version via FTP and replaced the file...! Thanks for the help!
