### ISSUE TITLE
Ldap.php does not correctly set Default Groups

### ISSUE THREAD

**Issue by timlegge** [kimai/kimai#933]
#### Expected behaviour
Creation of a User with the ldap authenticator should create set the a group for the User role based on the Auth/Abstract.php getDefaultGroups

#### Actual behaviour

When user is created using "ldap" authenticator the group is not set and error is shown setGroupMemberships: Column 'membershipRoleID' cannot be null (#1048) 

#### Steps to reproduce

enable the ldap authenticator and create a new user

#### Reproducable on demo.kimai.org? [yes|no]
unknown

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai dev 1.2.1.1395 

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

[17.03.2017 22:58:01] setGroupMemberships: Column 'membershipRoleID' cannot be null (#1048)

**Comment by timlegge** [comment]
```
diff --git a/libraries/Kimai/Database/Mysql.php b/libraries/Kimai/Database/Mysql.php
index 5b7479b..43608d0 100644
--- a/libraries/Kimai/Database/Mysql.php
+++ b/libraries/Kimai/Database/Mysql.php
@@ -2050,7 +2050,7 @@ class Kimai_Database_Mysql
             }
         }
 
-        foreach ($groups as $group => $role) {
+        foreach ($groups[0] as $group => $role) {
             $data['groupID'] = MySQL::SQLValue($group, MySQL::SQLVALUE_NUMBER);
 
             // Check whether a row for userId and groupID already exists
diff --git a/libraries/Kimai/Auth/Abstract.php b/libraries/Kimai/Auth/Abstract.php
index 6a2e7d2..c79e61d 100644
--- a/libraries/Kimai/Auth/Abstract.php
+++ b/libraries/Kimai/Auth/Abstract.php
@@ -164,9 +164,9 @@ abstract class Kimai_Auth_Abstract
 
         $memberships = $database->membership_roles();
         $membership = $memberships[0]['membershipRoleID'];
-        foreach ($memberships as $membership) {
-            if ($membership['name'] == 'User') {
-                $membership = $membership['membershipRoleID'];
+        foreach ($memberships as $membership_tmp) {
+            if ($membership_tmp['name'] == 'User') {
+                $membership = $membership_tmp['membershipRoleID'];
             }
         }
 


```

**Comment by timlegge** [comment]
okay, this took me a long time to track down and I am unsure whether the fix is safe in all cases.  Basically the Abstract.php code should be breaking out ot the loop whne it finds the User role and getting the membershipRoleID.  However, as it continues to loop it makes what should be a $membershipRoleID to be an Array which is not accounted for in the code

The fix simply only keeps the membershipRoleID for the User role

The Database/Mysql.php needs to be corrected for the $groups array

**Comment by timlegge** [comment]
I have a better fix that does not affect Database/Mysql.php that I will post shortly.

TIm

**Comment by timlegge** [comment]
I pushed a fix for this issue to 

https://github.com/timlegge/kimai/commit/e66a01cea59f4a9d42172dc7e443bf074bffa743

**Comment by simonschaufi** [comment]
Great. can you please make a pull request so I can merge it?

**Comment by timlegge** [comment]
Can I make a pull request for individual fixes that are in https://github.com/kimai/kimai/pull/920

**Comment by timlegge** [comment]
pull request submitted

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
