### ISSUE TITLE
Ihre Eingabe für die Uhrzeit oder das Datum ist nicht gültig.

### ISSUE THREAD

**Issue by Grimmwicht** [kimai/kimai#935]
Hi folks,

after upgrading my kimai installation I can't edit recorded dates. Another upgrade to last kimai dev version didn't help either.

#### Expected behaviour
Change recorded time/date.

#### Actual behaviour
Changing of a recorded time or date results in error: „Ihre Eingabe für die Uhrzeit oder das Datum ist nicht gültig.” (date/time is not valid)

#### Reproducable on demo.kimai.org? [yes|no]
no

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai dev 1.2.1.1393

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[21.03.2017 11:57:23] E_NOTICE iconv_strpos(): Wrong charset, conversion from `UTF-8' to `UCS-4LE' is not allowed [...] /web/timemanagement/libraries/zendframework/zendframework1/library/Zend/Locale/Format.php line 843

**Comment by simonschaufi** [comment]
Hi, this is the first time ever that somebody reports a charset conversion error. Really strange. I'm sure it has something to do with your hosting environment.
I can offer payed support (auf deutsch) so that I can debug the issue on your server.

**Comment by Grimmwicht** [comment]
Hi,

thanks for the offer of paid support, but I'm affraid that's out of the question at the moment.  :)  Instead I thought about a small donation, but on your website you just offer amazon whishlist and paypal – which both I don't use. Is there a possibility to just send you a few bucks via bank transfer (german accout)?

I made a fresh install of kimai at the same server, with a fresh database, and got the same error. The database is set to utf8_general_ci collation. If you could just point me to a general direction, what could be the problem here, I would be very grateful, and temper around with this server on my own, from time to time.

Thanks so far, and keep up the good work!

**Comment by Grimmwicht** [comment]
Recently I worked on this still unsolved problem again. The use of `iconv_strpos()` or `iconv_strlen()` should return integers, but instead returns false. This is clearly no problem with kimai, but some kind of faulty php setup by our webhoster. So the bug label can be released, and I close this issue. Thanks.
