### ISSUE TITLE
Duplicate entry for other users

### ISSUE THREAD

**Issue by piflixe** [kimai/kimai#938]
#### Expected behaviour
When viewing an entry from the user currently logged in, an entry shall be duplicated to apply to another user as well.

This can be useful when one user tracked the time using kimai, but another user was actually working as well (eg. meeting or brainstorming together). Then afterwards, the existing entry could be duplicated to apply to several users.

![kimaiapplytootheruser](https://cloud.githubusercontent.com/assets/6273829/24206661/3727c178-0f1f-11e7-9afc-4db426598c7c.PNG)

#### Actual behaviour
When manually adding entries afterwards, they can be added to multiple users at once. When time-tracking, this can only be done for a single user (currently logged on). There is no option to do time tracking for multiple users at once (i.e. start a tracking for a user currently NOT logged in) or duplicate entries to apply to other users as well.

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version
1.1.0.1389

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
