### ISSUE TITLE
Advanced LDAP-Authentication isn't working

### ISSUE THREAD

**Issue by DevSec-Ops** [kimai/kimai#942]
#### Expected behaviour
Login Page should accept unregistered users.

#### Actual behaviour
Blank Login Page is there, after performing steps mentioned in (http://www.kimai.org/documentation/administrator/authenticator.html)

#### Steps to reproduce
1. Change $authenticator = "ldapadvanced"; in includes/autoconf.php
2. Change the default values in includes/auth.php [Snapshot Attached]
![ldap](https://cloud.githubusercontent.com/assets/8300079/24499361/098a3b6a-155f-11e7-97b0-44914615dbe2.jpg)

#### Reproducable on demo.kimai.org? [yes|no]
No

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai 1.1.0.1389 - Stable

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
Not Available

**Comment by timlegge** [comment]
There were a number of issues around the authentication that I have fixed in:

https://github.com/kimai/kimai/pull/918 which fixed an issue where case sensitivity would prevent the creation of a user when using ldapadvanced.

https://github.com/kimai/kimai/pull/940 fixes other issues for the other authenticators.

I have tested than on Windows AD ldap (which it was written for) and since then against openldap and it has no issues with either.

Tim

**Comment by GruLab** [comment]
Thanks @timlegge , i'll check your points on my machine.

**Comment by timlegge** [comment]
Did you get it working?  There are several issues I uncovered recently that will prevent logins in ldapadvanced.  I have documented them in https://github.com/kimai/kimai/issues/946

**Comment by GruLab** [comment]
Sorry for delayed response, i've tried to change the setting in auth.php ; still it isn't working.

It'll be better, if step by step procedure to enable ldap-advanced is added into documentation.

**Comment by timlegge** [comment]
Hi

I can help you troubleshoot the problem with the current code for LDAP is that the logging kind of sucks.

If you are able to edit libraries/Kimai/Auth/Ldapadvanced.php to add some logging it would help

Take a look at https://github.com/timlegge/kimai/blob/develop/libraries/Kimai/Auth/Ldapadvanced.php for lines to add.  They look like:

Kimai_Logger::logfile('ldapAdvanced: Cannot connect to ...' . somevariable );

The version I reference has a lot of changes so you can't assume the exact lines will work for your version.  

Tim

**Comment by blu-IT** [comment]
Can you post an example of your LDAP-tree structure (without data) here?

**Comment by timlegge** [comment]
@blu-IT Are you lookiing for help setting up ldap or were you trying to help the original poster?

**Comment by blu-IT** [comment]
@timlegge: I was trying to help the original poster... already solved?

**Comment by timlegge** [comment]
They have not reposted.  I assumed that you were asking the original poster
but wasn't sure.  I have been going to write up some details on how to use
something like Softerra LDAP explorer to figure out the settings

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
