### ISSUE TITLE
Issues with Installer on PHP Write Permissions

### ISSUE THREAD

**Issue by jadcsi** [kimai/kimai#943]
I am stuck on the step where it checks for PHP write permissions to the following files/folders:

/temporary (Directory)
/temporary/logfile.txt (File)
/includes/autoconf.php (File) and /includes (Directory)

Now under the web directory where I extracted the ZIP I downloaded from the web site I see the temporary and includes subdirectories and have applied chmod -R 777 and restarted Apache to no avail

**Comment by timlegge** [comment]
Hi

You should change the owner to be the web server as in:

chown -R apache:apache kimai-directory
or
chown -R www-wata:www-data kimai-directory

you can see the owner by: 

ps axu | grep apache

I would delete that directory and reinstall in case the permissions were set to be something outer than world writable.

Tim

**Comment by jadcsi** [comment]
Thanks Tim, I did as recommended and error persists.

 another thing I am seeing is that there is no autoconf.php under the /includes subdirectory

**Comment by timlegge** [comment]
I believe that autoconf.conf is generated as part ot the installation after you get the write errors sorted.

in the directory where you installed kimai do the followin and post the results:

ls -l
ps axu | grep apache

Is this ubuntu?

Tim

**Comment by jadcsi** [comment]
No its CentOS.  See below:

[jad@kimai kimai]$ ls -l
total 96
-rw-r--r--.  1 apache root 35147 Mar 31 18:11 COPYING
drwxr-xr-x.  2 apache root  4096 Mar 31 18:11 core
-rw-r--r--.  1 apache root  1422 Mar 31 18:11 error.php
drwxr-xr-x. 10 apache root  4096 Mar 31 18:11 extensions
-rw-r--r--.  1 apache root  1150 Mar 31 18:11 favicon.ico
-rw-r--r--.  1 apache root  2604 Mar 31 18:11 forgotPassword.php
drwxr-xr-x.  2 apache root  4096 Mar 31 18:11 includes
-rw-r--r--.  1 apache root  7906 Mar 31 18:11 index.php
drwxr-xr-x.  4 apache root  4096 Mar 31 18:11 installer
-rw-r--r--.  1 apache root  4628 Mar 31 18:11 INSTALL.md
drwxr-xr-x.  2 apache root    34 Mar 31 18:11 js
drwxr-xr-x.  2 apache root  4096 Mar 31 18:11 language
drwxr-xr-x. 11 apache root  4096 Mar 31 18:11 libraries
-rw-r--r--.  1 apache root  1992 Mar 31 18:11 processor.php
drwxr-xr-x.  5 apache root    46 Mar 31 18:11 skins
drwxr-xr-x.  4 apache root    34 Mar 31 18:11 templates
drwxr-xr-x.  2 apache root    22 Mar 31 18:11 temporary
drwxr-xr-x.  2 apache root  4096 Mar 31 18:11 updater
[jad@kimai kimai]$ ps axu | grep apache
apache    8253  0.0  0.2 352840  9828 ?        S    17:51   0:00 /usr/sbin/httpd -DFOREGROUND
apache    8254  0.0  0.2 352840  9800 ?        S    17:51   0:00 /usr/sbin/httpd -DFOREGROUND
apache    8255  0.0  0.2 352840  9812 ?        S    17:51   0:00 /usr/sbin/httpd -DFOREGROUND
apache    8256  0.0  0.2 353096  9572 ?        S    17:51   0:00 /usr/sbin/httpd -DFOREGROUND
apache    8257  0.0  0.2 352692  9660 ?        S    17:51   0:00 /usr/sbin/httpd -DFOREGROUND
apache    8258  0.0  0.2 352548  8096 ?        S    17:51   0:00 /usr/sbin/httpd -DFOREGROUND
apache    8259  0.0  0.2 352584  9348 ?        S    17:51   0:00 /usr/sbin/httpd -DFOREGROUND
apache    8260  0.0  0.2 352548  9236 ?        S    17:51   0:00 /usr/sbin/httpd -DFOREGROUND
jad       9085  0.0  0.0 112644   956 pts/0    R+   18:13   0:00 grep --color=auto apache

**Comment by timlegge** [comment]
id apache

my apache server runs as www-data so I did:

chown -R www-data:www-data kimai

you should probably be 

chown -R apache:apache kimai

the group permissions are root for your instal.. it should still work though.

also cd temporaty and 

ls -l

Tim

**Comment by jadcsi** [comment]
Still didnt work after applying chown -R apache:apache kimai

[jad@kimai temporary]$ ls -l
total 0

**Comment by timlegge** [comment]
what was the result of:

id apache

**Comment by jadcsi** [comment]
[jad@kimai temporary]$ id apache
uid=48(apache) gid=48(apache) groups=48(apache)

**Comment by timlegge** [comment]
and do your files should up now as owned by apache group apache (or root):

-rw-r--r--. 1 apache apache 35147 Mar 31 18:11 COPYING

.... do you have selinux enabled?

sestatus

Tim

**Comment by jadcsi** [comment]
Yes it shows up as owned by apache group apache
[jad@kimai temporary]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

**Comment by timlegge** [comment]
lol.  you have two choices.  disable selinux or learn to configure it.  I could do it if I had to with some googling:

https://blog.lysender.com/2015/07/centos-7-selinux-php-apache-cannot-writeaccess-file-no-matter-what/

Tim

**Comment by timlegge** [comment]
This might work

if kimai is in /data/www/kimai

sudo chcon -t httpd_sys_content_t /data/www/kimai -R

 # Allow write only to specific dirs
sudo chcon -t httpd_sys_rw_content_t /data/www/kimai/temporary -R
sudo chcon -t httpd_sys_rw_content_t /data/www/kimai/includes -R

**Comment by jadcsi** [comment]
Thanks Tim, the info in the link was super helpful.  I was able to follow it and get past that step in the install :)

**Comment by timlegge** [comment]
nice.  Selinux is fantastic but a bit of a pain if you don't deal with it regularly.  It does not respect the unix style permissions (that is it overrides them).

Tim
