### ISSUE TITLE
Timer counter starts at 0-1:49:57 rather than 0:00:00

### ISSUE THREAD

**Issue by rwoolf** [kimai/kimai#947]
#### Expected behaviour
When I select the timer button it should begin at 00:00:00 and count up.
#### Actual behaviour
When I select the timer button it flashes 00:00:00 and then quickly changes to 0-1:49:57 and begins counting up.  After ten minutes it zero's itself out to 00:00:00 and continues to count up.  So after 10 minutes, the visible counter is ten minutes off.  If at any time while it is running a page refresh can be done and the counter corrects itself to the correct time.
#### Steps to reproduce
On our system we simply select the green start button.
#### Reproducable on demo.kimai.org? [yes|no]
No
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389 - © 2006-17 by the Kimai-Team:

**Comment by timlegge** [comment]
Check your time on the server versus your browser computer.  I believe the start time in the database is based on the server time and the timer is browser based javascript so they could show differences.  I have noticed some negative times at work when I set the start time manually back in time.

**Comment by rwoolf** [comment]
Thanks, that solved the problem

**Comment by simonschaufi** [comment]
We decided to use the server time for time tracking. Time zones are a nightmare to do right....
