### ISSUE TITLE
Bug in filtering for activities

### ISSUE THREAD

**Issue by wpcata** [kimai/kimai#952]
#### Expected behaviour
After activating a filter for an activity, the filter should stay marked or should be deactivated when switching to another project.

#### Actual behaviour
After activating a filter for an activity, the filter remains active after switching to another project.
When switching back to the first project with the previously activated filter, it isn't marked anymore.
Activating or deactivating this filter does nothing with the effect, that the showed entries are filtered like in the first place.

After refreshing the website the filter gets deactivated.

#### Steps to reproduce
1. Filter the entries for an activity
2. Switch to another project (so other activities are showed)
3. Switch back to the prior project

#### Reproducable on demo.kimai.org? [yes|no]
Yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.1.0.1389 stable

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

I don't know if this bug was reported before, so I'm sorry if it was.
I couldn't find a similar issue.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
