### ISSUE TITLE
Bug: Editing of running activities not possible with "No entries can be added X days in the past"-Option active

### ISSUE THREAD

**Issue by wpcata** [kimai/kimai#953]
#### Expected behaviour
Ability to edit running activities.

#### Actual behaviour
When active the option to disable the editing or creating of entries a certain time in the past, also disables the button to edit running activities.

#### Steps to reproduce
1. Start an activity with the buzzer
2. Activate the option to prevent adding or editing entries in the past with a random number of days
3. Go back to the timesheet-page

#### Reproducable on demo.kimai.org? [yes|no]
Yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.1.0.1389 stable

**Comment by timlegge** [comment]
Looks like if you stop the running activity you can edit the activity

**Comment by timlegge** [comment]
Strange I am sure in the stable version I can edit the end time of a finished activitu and clear it to start the timer again.  Doesn't seem to work here

**Comment by wpcata** [comment]
To be clear:
When the option to disable editing entries some days in the past in the admin-config is not activated, you can edit entries whenever you want. Even while running.
If this option is active you can only edit them when finished.
But I would like to edit entries whenever I want without the need of stopping until the set amount days.
So...

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
