### ISSUE TITLE
Feature Request: bitcoin donation

### ISSUE THREAD

**Issue by juanjgit** [kimai/kimai#955]
Please, add a bitcoin address so you can recive donations in bitcoin

**Comment by simonschaufi** [comment]
So far none of the kimai developers has a bitcoin account. Right now we only accept "real" money.

**Comment by juanjgit** [comment]
What a pity... you still think that those paper notes and that numbers in the Oracle databases of your bank are "real" ;-)
Anyway, I love Kimai. Good work!

**Comment by simonschaufi** [comment]
Bitcoins are basically just a "mathematical calculation" if I understood it right.

**Comment by juanjgit** [comment]
Bitcoin is a distributed ledger not controlled my any goverment or company, fully peer to peer, like torrent. It's a protocol to exchange value and yes, mathematical calulations are used as part of this protocol, to secure the transactions. Bitcoin is both a payment network and a currency, backed by math, not by a central bank. You can use bitcoin directly to buy or convert it to your local currency quite easily. 

USD used to be backed by gold but now it is only backed by "God" ("In God we Trust" says). In Europe we are more atheists, so EUR it is only backed by our trust in Mario Draghi. Bitcoin is backed by maths. I prefer maths to God ;-)

If you have some spare time, I advice you to read something more about bitcoin. As a developer you will quickly understand the concept and you will love it.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
