### ISSUE TITLE
Table layout in timesheet view

### ISSUE THREAD

**Issue by timlegge** [kimai/kimai#956]
#### Expected behaviour
The username column should be over the usename data in the table

#### Actual behaviour
The columns are out of alignment on the time sheet view.  THe username heading is not displayed over the username data,

#### Steps to reproduce
It appears that if  Tracking Number is editable is enabled the column headings are correct.  Disable this setting and you will see the issue
#### Reproducable on demo.kimai.org? [yes]
It appears that if  Tracking Number is editable is enabled the column headings are correct.  Disable this setting and you will see the issue
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai dev 1.2.1.1393
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
not applicable
![image](https://cloud.githubusercontent.com/assets/1029883/24980812/39fec580-1fb0-11e7-9861-51c630abe003.png)

**Comment by simonschaufi** [comment]
This is a known problem. The main issue is that the table header is not part of the table below and it's almost impossible to sync the width of the columns. if you have a solution with "sticky table header", a pull request is highly welcome!

**Comment by timlegge** [comment]
I started to look at it last night but GUI stuff is not my favourite thing
to work on :-)  I will probably take a look but if you guys have not found
a solution I doubt if I will...

**Comment by simonschaufi** [comment]
I'm a backend developer myself. There are some sticky header solutions but I haven't looked deeper inside them to find out if they also handle resizing correctly.

**Comment by on-jz** [comment]
There's a colgroup in both timesheet tables (div id="timeSheet_head" ... table and div id="timeSheet" ... table):

```
<colgroup>
	<col class="option">
	<col class="date">
	<col class="from">
	<col class="to">
	<col class="time">
	<col class="wage">
	<col class="client">
	<col class="project">
	<col class="activity">
	<col class="description">
	<col class="trackingnumber">
	<col class="username">
</colgroup>
```
As every colgroup has a class assigned, you could assign a width to these classes and "sync" both tables. 

Is there a technical reason why there are two separate tables? Otherwise it would probably be easier to go with a layout like this:
```
<table>
	<colgroup>
	  <col class="options">
	  [...]
	  <col class="username">
	</colgroup>
	<thead id="timeSheet_head">
		<tr>
			<th></th>
			[...]
			<th></th>
		</tr>
	</thead>
	<tbody id="timeSheet">
		<tr id="timeSheetEntry1" class="odd">
			<td></td>
			[...]
			<td></td>
		</tr>
		[...]
	</tbody>
</table>
```

No split tables, no column issues any more. 

Ajax responses could either return the <thead></thead> or the <tbody></tbody> part, as they both have separate ids. What do you think about this?

**Comment by kevinpapst** [comment]
The idea is good and the reason why it is still there is only "history".
I tried in the past to fix it - but the javascript (calculation of table size when resizing the window) is hardly coupled to the HTML. That was invented before there were responsive designs and CSS frameworks.
If you want to fix it and sent in a pull request, make sure to check the javascript!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
