### ISSUE TITLE
Manual Database entry during installation

### ISSUE THREAD

**Issue by JipFransen** [kimai/kimai#957]
#### Expected behaviour
It would be nice to be able to enter a manual DB name if the installer fails to retreive a list of DB's. 

#### Actual behavior
Currently the installer attempts to get a list of DB's from the SQL server. Hower when the DB is hosted on a provider this may fail due to insufficient rights. Therefore the one available DB can not be created. 
For instance with one.com. Also see this older thread:
https://forum.kimai.org/index.php?topic=2245.0

#### Steps to reproduce
Start installation proces on a one.com hosted webspace with DB. Click on to the DB selection screen. Will get error message.

#### Reproducable on demo.kimai.org? [yes|no]
Have not tried, but as it is the installer I think it can not be reproduced on demo.

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v0.9.2.1306 got this version 2017-04-13 from sourceforge.

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
I was able to work around this by disableing the DB lookup and optional DB creation part in install file "60_db_select_mysql" and replacing it with "$return.="<input id='db_names' type='hidden' value='<MYDBNAME>'/>";

**Comment by kevinpapst** [comment]
Seems you are using an old version. 
There is a fallback for a simple text input field in case the database query is failing.
It would be great if you could use the newest version from our website and test if this feature works.

**Comment by simonschaufi** [comment]
no response after 2 weeks.
