### ISSUE TITLE
SAML support

### ISSUE THREAD

**Issue by timlegge** [kimai/kimai#961]
Hi

I am looking at implementing SAML support for my use in our instalation.  I am now looking at how the php-saml library should be installed.

It looks like I can use composer but that would install its own vendor directory instead of the libraries directory that the other libraries use.  

Should I simply download the php-saml library and add it to the libraries directory or does it make sens to go the composer route?

Tim

**Comment by simonschaufi** [comment]
Yes we do use composer but additionally also add the libraries directly in the git repo. This will change sooner or later to cleanup the repo and only have the nessesary code in the repo.
When you add composer stuff, the content should automatically all go into the libraries folder. See here: https://github.com/kimai/kimai/blob/master/composer.json#L14

**Comment by timlegge** [comment]
perfect.  I looked all around and then saw a google result that said the vendor directory was hard to override so assumed it was not in use.  Thanks.  

I will likely add the ability to config to the GUI work I was doing.  Did you make any progress to the API you were going to work on for the config writing to the file.  I did figureout how to write to the current autoconf.php file so I can modify my changes to use the current mechanism to use the autoconf.php

Tim

**Comment by timlegge** [comment]
I did the following and got a number of updates.  Is there anything I should be aware of there?  I assuem you would prefer to update the libraries in a seperate commit?

composer require onelogin/php-saml

Using version ^2.10 for onelogin/php-saml
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing onelogin/php-saml (2.10.5)
    Loading from cache

  - Installing symfony/yaml (v2.8.19)
    Downloading: 100%         

  - Installing phpunit/php-text-template (1.2.1)
    Loading from cache

  - Installing phpunit/phpunit-mock-objects (1.2.3)
    Loading from cache

  - Installing phpunit/php-timer (1.0.9)
    Downloading: 100%         

  - Installing phpunit/php-file-iterator (1.4.2)
    Downloading: 100%         

  - Installing phpunit/php-token-stream (1.2.2)
    Loading from cache

  - Installing phpunit/php-code-coverage (1.2.18)
    Loading from cache

  - Installing phpunit/phpunit (3.7.38)
    Loading from cache

    Skipped installation of bin composer/bin/phpunit for package phpunit/phpunit: name conflicts with an existing file
  - Installing components/jquery (3.2.1)
    Downloading: 100%         

  - Installing malsup/form (3.51)
    Loading from cache

phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.0.5)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Package malsup/form is abandoned, you should avoid using it. Use jquery-form/form instead.

**Comment by simonschaufi** [comment]
please use the ``--no-dev`` parameter.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
