### ISSUE TITLE
How mass delete timesheet entries?

### ISSUE THREAD

**Issue by yardstudio** [kimai/kimai#962]
#### Expected behaviour
Wish mass delete timesheet entries

#### Actual behaviour
only one per one is possible delete

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
latest

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
![2017-04-25_11-04-53](https://cloud.githubusercontent.com/assets/25852179/25384168/8fb4808c-29bf-11e7-9556-277a9c487a58.png)

**Comment by simonschaufi** [comment]
Will not be implemented for now.
