### ISSUE TITLE
Customers in admin group?

### ISSUE THREAD

**Issue by yardstudio** [kimai/kimai#963]
Why are in demo customers assigned to admin group? This is only for example, or must be set for funkctionality? Can I create my own group, named customers and assign they there ?

**Comment by timlegge** [comment]
It appears that they are currently:

// A new customer is assigned to the group of the current user by default.

Actually, it appears that the groups of the user creating the customer is used.  Seems odd but if you create user witht he groups you want the customer to have and use that user to create the user then it will do what you are looking for.

Tim

**Comment by simonschaufi** [comment]
You can do with the groups whatever you want. It's not on purpose that all new users automatically get the admin group.
