### ISSUE TITLE
German Umlauts problem

### ISSUE THREAD

**Issue by svebal** [kimai/kimai#968]
#### Expected behaviour
Should be ü ä ö ...
> Linie zwischen zwei Einträgen zeichnen, wenn dort eine zeitliche Lücke ist.

#### Actual behaviour
its shown wrong over the whole UI, e.g.
>Linie zwischen zwei EintrÃ¤gen zeichnen, wenn dort eine zeitliche LÃ¼cke ist.

#### Steps to reproduce
Open "Administration" tab on your installation

#### Reproducible on demo.kimai.org? [yes|no]
no

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai v1.1.0.1389 from https://github.com/kimai/kimai/releases/download/1.1.0/kimai_1.1.0.zip

**Comment by simonschaufi** [comment]
I cannot reproduce it.

**Comment by duckbrain** [comment]
That looks to me like a character encoding issue. It could have something to do with your webserver (Apache?) configuration. I'm going to guess it's best to put everything to UTF-8. I'd check if the character encoding is being set in the HTTP headers.
