### ISSUE TITLE
Problem mit dem export in eine PDF Datei 

### ISSUE THREAD

**Issue by Maler1** [kimai/kimai#970]
Hallo, ich hab ein Problem mit der Ausgabe in eine PDF Datei. In der Zusammenfassung oben werden ein paar Stunden einfach nicht angezeigt. Das Problem hab ich nur wenn ich die "Standard time" Einstellung verwende. Da stimmt dann unten die komplette Zeitangabe auch nicht mehr. Siehe Bilder.

![2017-04-29 1](https://cloud.githubusercontent.com/assets/28198306/25557357/015fa952-2d10-11e7-8d74-13ec4bc607ef.png)
![2017-04-29](https://cloud.githubusercontent.com/assets/28198306/25557358/0161707a-2d10-11e7-9491-9c37c102ad47.png)

Bei einer Ausgabe in "Decimal time" funktioniert es. Siehe Bild. Ich hätte jedoch gerne die Standard Zeit.

![2017-04-29 3](https://cloud.githubusercontent.com/assets/28198306/25557397/a1373bc0-2d10-11e7-9e21-24dc0f0943fb.png)

Ich benutze die stable Version. PHP Version ist PHP 5.6. Eine Umstellung auf PHP 7.1 bringt keine Änderung.

**Comment by Maler1** [comment]
Komisch ist das ganze. Ich bekomme jetzt auch eine Fehlermeldung von der App Timetrapp.
**Error while calling "getTasks": An unhandled error occured.**

Ich hab soweit ich weiß nichts geändert. Kann es sein, dass mein Provider was geändert hat?!
Bei meiner Kimai Installation geht's jedenfalls drunter und drüber. Es werden Tasks angezeigt, die nichts mit dem Projekt zu tun haben usw.

Über Hilfestellung wäre ich dankbar.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
