### ISSUE TITLE
How can I delete record in Timesheet

### ISSUE THREAD

**Issue by yardstudio** [kimai/kimai#972]
#### Expected behaviour
I wish delete some test records from Timesheet

#### Actual behaviour

Can´t find any button for delete

#### Steps to reproduce
Start recording again will create new entry. I wish have posibility delete it

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]

v1.1.0.1389 - © 2006-17 

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

![2017-05-03_11-24-47](https://cloud.githubusercontent.com/assets/25852179/25655106/05ddac18-2ff4-11e7-8f47-d459427c9bab.png)

**Comment by simonschaufi** [comment]
Generally, deleting is possible, it also depends on your user settings or your user rights.
