### ISSUE TITLE
Why time counting not start from 0?

### ISSUE THREAD

**Issue by yardstudio** [kimai/kimai#973]
#### Expected behaviour
When start recording I wish count time from 0

#### Actual behaviour
timer start at 0-1:59:00 then going to 00:00

#### Steps to reproduce
start counting

#### Reproducable on demo.kimai.org? [yes|no]
maybe
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389 - © 2006-17 by the Kimai-Team: 
![2017-05-03_11-33-04](https://cloud.githubusercontent.com/assets/25852179/25655265/a05d809c-2ff4-11e7-9c3f-dffb1f531e89.png)
![2017-05-03_11-33-14](https://cloud.githubusercontent.com/assets/25852179/25655268/a4e6e4f0-2ff4-11e7-9de8-10414274c97b.png)

**Comment by timlegge** [comment]
See: https://github.com/kimai/kimai/issues/947

**Comment by yardstudio** [comment]
OK, but what is the solution ?  How can I solve this? Where in preferences I can set something?

**Comment by timlegge** [comment]
HI

The only real solution is to have time synced via ntp on your server and client

Tim
