### ISSUE TITLE
Timesheet entries don't stay where they should

### ISSUE THREAD

**Issue by sjaeckel** [kimai/kimai#974]
#### Expected behaviour
The entries in the list stay in the order they are entered

#### Actual behaviour
The entries are grouped by rounding interval and then ordered by ?

This also applies to recordings of different customers within the same rounding interval

#### Steps to reproduce
Configure rounding to e.g. 5 minutes
1. record an entry, put a note on it. ![screenshot_2017-05-04_12-41-51](https://cloud.githubusercontent.com/assets/294374/25700762/5ef01a22-30c9-11e7-9341-db7c85103b3d.png)

2. record a second entry in the same interval
![screenshot_2017-05-04_12-42-37](https://cloud.githubusercontent.com/assets/294374/25700769/6a7ecf96-30c9-11e7-82dd-521edac9ffd4.png)

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
not required I guess, can be created if you need them

**Comment by timlegge** [comment]
I am not sure what you are saying.  The two activities you have entered appear to have overlapping times (The red line indicates times that overlap).

Tim

**Comment by sjaeckel** [comment]
Yes, they have overlapping times, but I would expect that also overlapping times show up in order they were entered.

currently the list is ordered like this if I create three entries where 2 and 3 overlap
```
entry2
entry3
entry1
```
but I would expect them to be ordered like this
```
entry3
entry2
entry1
```
clear now?

**Comment by timlegge** [comment]
Yes, i tried on the latest git from devel and I can't reproduce your issue.  I do't have a release version available at the moment.

Tim

**Comment by sjaeckel** [comment]
I just tried again on demo and I can still reproduce (most likely I just didn't explain it clear enough)

1. go to http://www.kimai.org/demo/, click "create account", on the newly opened window click "login"
2. admin panel->advanced, set "Round time to" to 5
3. record entry 1, add a note
4. record entry 2, as soon as you stop the list will be re-ordered

![screenshot_2017-05-12_23-52-49](https://cloud.githubusercontent.com/assets/294374/26018288/2ccfc096-376e-11e7-90da-bc8f1b7b88c1.png)

![screenshot_2017-05-12_23-53-02](https://cloud.githubusercontent.com/assets/294374/26018289/2cd1dafc-376e-11e7-890f-e97a88c2a226.png)

Thanks, Steffen

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
