### ISSUE TITLE
Default skin not used for users not having changed their preferences

### ISSUE THREAD

**Issue by Kyoshiro-san** [kimai/kimai#975]
#### Expected behaviour
Setup default skin as global option in includes/autoconf.php
It should be used for all users not having defined their prefered skin.

#### Actual behaviour
Default skin is used.

#### Steps to reproduce
Setup this line in includes/autoconf.php:
`$skin = "zadia"; `

#### Kimai version
1.1.0

#### Fix
Apply this patch
```
--- ./libraries/Kimai/Database/Mysql.php.orig   2017-05-05 09:39:16.969437953 +0000
+++ ./libraries/Kimai/Database/Mysql.php        2017-05-05 09:23:45.073637855 +0000
@@ -2926,7 +2926,7 @@
         }
 
         $this->kga['conf']['rowlimit'] = 100;
-        $this->kga['conf']['skin'] = Kimai_Config::getDefault(Kimai_Config::DEFAULT_SKIN);
+        $this->kga['conf']['skin'] = isset($this->kga['skin']) ? $this->kga['skin'] : Kimai_Config::getDefault(Kimai_Config::DEFAULT_SKIN);
         $this->kga['conf']['autoselection'] = 1;
         $this->kga['conf']['quickdelete'] = 0;
         $this->kga['conf']['flip_project_display'] = 0;

```

**Comment by timlegge** [comment]
In the current code base a fix like the following would work also:

`
diff --git a/includes/basics.php b/includes/basics.php
index 4ad9a52..bc9d6a6 100644
--- a/includes/basics.php
+++ b/includes/basics.php
@@ -74,7 +74,13 @@ if (isset($billable)) {
     $kga->setBillable($billable);
 }
 if (isset($skin)) {
-    $kga->setSkin($skin);
+    foreach(glob(('../skins/*'), GLOB_ONLYDIR) as $dir) {
+        if($skin == basename($dir)) {
+            $kga->setSkin($dir);
+        } else {
+            Kimai_Config::getDefault(Kimai_Config::DEFAULT_SKIN);
+        }
+    }
 }

 date_default_timezone_set($defaultTimezone);
diff --git a/libraries/Kimai/Config/Settings.php b/libraries/Kimai/Config/Settings.php
index 47a9f03..fa9eda4 100644
--- a/libraries/Kimai/Config/Settings.php
+++ b/libraries/Kimai/Config/Settings.php
@@ -49,7 +49,7 @@ class Kimai_Config_Settings extends Kimai_ArrayObject
     {
         return array(
             'rowlimit' => 100,
-            'skin' => Kimai_Config::getDefault(Kimai_Config::DEFAULT_SKIN),
+            'skin' => $this->get('skin'),
             'autoselection' => 1,
             'quickdelete' => 0,
             'flip_project_display' => 0,

`

**Comment by simonschaufi** [comment]
The whole settings are currently being refactored. It feels almost like a new kimai version.

**Comment by timlegge** [comment]
I figured that it would probably conflict with that work so I did not go any further.  There is likely a couple of other settings that don't work in develop as well.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
