### ISSUE TITLE
Week/Calendar view

### ISSUE THREAD

**Issue by NisseNilssons** [kimai/kimai#976]
Thanks for a fantastic product! Here is a suggestion that I believe would benefit many: Week/Calendar view

I would very much like my teams to be able to view their reported time in a kalendar fashion - ie monday / tuesday / wednesday and each reported time as a slot in that calendar.

Benefit: being able to easily see total time reported per day (typically there is a working time of X hours and X*Y% needs to be billable). Also, it is easy to then see if overlapping time has been reported. As of now, it is not very easy.

[![bountysource](https://api.bountysource.com/badge/issue?issue_id=44875710)](https://www.bountysource.com/issues/44875710)

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
