### ISSUE TITLE
New feature: Daily rate with pro rata calculation

### ISSUE THREAD

**Issue by injehiko** [kimai/kimai#979]
#### Expected behaviour
A daily rate with pro rata calculation is required for my projects. If worked more then the defined max. hours (usually 8hrs) it will cut the cost to daily rate. If worked less then it will only calculate pro rata (for each day individually).

#### Actual behaviour
There is only a hourly rate available. No max 

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai 1.1.0.1389

**Comment by simonschaufi** [comment]
I think this is very unique and very customer specific. Kimai tries to support as much as possible but there are plenty of other companies who have extra rules. The  best is to implement that requirement for yourself in a separate branch and then rebase that once in a while with the master branch.
