### ISSUE TITLE
Enter time for other user requires permission in all groups

### ISSUE THREAD

**Issue by timlegge** [kimai/kimai#980]
#### Expected behaviour
When a "proxy" user has permission to enter time for another user the proxy should only need ki_timesheets-otherEntry-ownGroup-* permission for that user's group.

Realistically if a proxy user has permission to add time entries for any of the joint groups of the user it should probably be able to create time entries for the other user.
  
#### Actual behaviour
The code requires the "proxy" user to have that permission for all groups that they and the user are a member of  at the same time.
 
#### Steps to reproduce
Create three groups for the user and the proxy user.  Assign a responsibility group to one of the shared groups to the proxy user where the permission is ki_timesheets-otherEntry-ownGroup-Add.  

Check whether the proxy can create a time entry for the user - should fail

Assign the responsibility group with a permission of  ki_timesheets-otherEntry-ownGroup-Add to all groups shared by the users - adding a time entry should work

#### Reproducable on demo.kimai.org? [yes|no]
likely
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.2.1.1395 and 1.1.0

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
n/a

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
