### ISSUE TITLE
XLS file is NULL

### ISSUE THREAD

**Issue by yardstudio** [kimai/kimai#982]
#### Expected behaviour
create XLS from project

#### Actual behaviour
XLS is created with NULL size

#### Steps to reproduce
place Slovak diacritics chars into projects and try create XLS

#### Reproducable on demo.kimai.org? [yes|no]
maybe

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
latest

**Comment by simonschaufi** [comment]
could you try to fix it yourself? any help would be highly appreciated!
PS: we use https://github.com/PHPOffice/PHPExcel for it.
