### ISSUE TITLE
Is possible select and edit more than one item in timesheet?

### ISSUE THREAD

**Issue by yardstudio** [kimai/kimai#983]
#### Expected behaviour
I need edit more items (need set it as cleared). Is possible make this by one step? 

http://i.imgur.com/CkujYgY.png

**Comment by simonschaufi** [comment]
No, it's not possible at the moment. Clearing timesheet entries works well in the export module (the checkbox in the last column)

**Comment by yardstudio** [comment]
I am sorry,

but can´t find any clear checkbox, where is it ?
