### ISSUE TITLE
API Authentication

### ISSUE THREAD

**Issue by charlieMonroe** [kimai/kimai#984]
Would there be a kind soul who'd give me a cURL sample command for authenticating via the API? I've looked on the mobile jQuery RPC repo, but can't figure out why I'm getting 204 (no content) response. Or does the demo.kimai.org installation have the API disabled?

Thanks!

**Comment by davidrei** [comment]
This works for me:

`curl --data '{"jsonrpc":"2.0","method":"authenticate","params":["username","password"],"id":"1"}' https://demo.kimai.org/core/json.php`
