### ISSUE TITLE
Past  - time tracking - retrospective

### ISSUE THREAD

**Issue by Peterlundorf** [kimai/kimai#987]
#### Expected behaviour
I would like to enter time consumption back in time (retrospective) - fx for 2016 - for different users
#### Actual behaviour
I can only enter time tracking 1 month in the past - i.e. the same month we are in. It is not possible to enter time for 2016 fx.

Is there a way how to enter values retrospective?

Thanks  - Peter

**Comment by simonschaufi** [comment]
You can go back in time as far as you want. The thing that does not work is to enter data for another user. you have to logout and login as that user.

**Comment by Peterlundorf** [comment]
Ok - thank you.
But the next problem is - the employee is no longer working here and I have tried to make a new password so I can log in as the old employee - but it keeps on saying "wrong username and/or password".
What to do now?

Thank you very much for your help :-)

**Comment by Peterlundorf** [comment]
Problem solved!
I didn´t adjust the "timeframe" in the top of the screen to go back in time. I had already entered some values/dates but couldn´t see them bacause of the insufficient time-period.

Have a nice day - Peter
