### ISSUE TITLE
Auto-Stop clock at end of day

### ISSUE THREAD

**Issue by UJAGTA** [kimai/kimai#988]
Similar to the question on the previous forum (https://forum.kimai.org/index.php?topic=3780.0), it happens sometimes that users forget to stop recording their hours and just shut down at the day's end, so that the following morning it shows they've been working on a project for 24hours straight.

Is there an option or code change to have the clock stop logging time after "X" o'clock?  

Please and Thank you!

**Comment by simonschaufi** [comment]
Everybody is responsible for his own time tracking. If he forgets to stop the timer, he can stop the timer whenever he logs in again and adjusts the time when he stopped working. If we stop the timer automatically, he might forget to adjust the time himself afterwards.
