### ISSUE TITLE
Assign others same time

### ISSUE THREAD

**Issue by UJAGTA** [kimai/kimai#989]
Hello!

Is it possible to assign others to the same time tracking to literally add them into the same task at the same time? 

 EG. In a planning session with 4 users, could one log the hour via web, assign show as there with me, and also log it in their respective time trackers?

Please and thank you!

**Comment by simonschaufi** [comment]
Hello, this is not possible right now.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
