### ISSUE TITLE
Installed Kimai 1.1.0.1389 and can't login after creating users

### ISSUE THREAD

**Issue by Cravenschild** [kimai/kimai#991]
Just completed install of Kimai, went into database for PHPmyadmin and changed the admin password and added an additional user. They both have "active" set to 1 and neither will login with the username/password. Says they are incorrect and no amount of changing it or deleting and re-adding users allows me to log in.

**Comment by timlegge** [comment]
Hi

the password is an md5 hash of a salt combined with the password as in:

salt . changeme . salt

so:

1) get the salt:
```
grep salt includes/autoconf.php 
$password_salt = "rglb34K3sPk36yuijcdeL";
```
2) Combine them intp a string with at default (or your chosen password:

```
rglb34K3sPk36yuijcdeL + changeme +rglb34K3sPk36yuijcdeL
rglb34K3sPk36yuijcdeLchangemerglb34K3sPk36yuijcdeL
```

3) run it through md5:

```
php -a
Interactive mode enabled

php > print md5("rglb34K3sPk36yuijcdeLchangemerglb34K3sPk36yuijcdeL");
62f1fc60671f3949cf6b2ed3466be4ae
php > 

```
4) Update the user table with the password hash from above:

62f1fc60671f3949cf6b2ed3466be4ae

**Comment by Cravenschild** [comment]
That may be part of the problem as I have looked at the original download files and re-downloaded them and there is no autoconf.php file anywhere in it. So I am unable to find this file or any other file with a salt value.

**Comment by Cravenschild** [comment]
Well, re-installed and just logged in with the changeme password and can create users from there as I couldn't get it to take any kind of password or locate the salt before. Thanks.
