### ISSUE TITLE
How to un-ban a user?

### ISSUE THREAD

**Issue by UJAGTA** [kimai/kimai#992]
I'm the admin for the site, and one of my users has entered in his credentials too many times incorrectly. He's now "banned"

How do I remove this flag so that he is no longer banned?
I've reset his password and that has not worked.

There's got to be some simple way within the GUI to reset the "banned" flag and re-enable the user. Please advise.

**Comment by timlegge** [comment]
If I am not missing anthing it appears that the admn can adjust a field in advanced rto set the number of failures for the ban and the number of seconds to stay banned.

It defaults to 3 times and 900 seconds so you need to wait 15 minutes

Tim

**Comment by UJAGTA** [comment]
In this case it's not a matter of doing it in advance, the user is already locked out and "banned." Has been for hours.

I think 3 password failures is plenty, so how do I un-ban someone who has already had 3 failed attempts ?

Please and Thank you


Sent from my Samsung device


...................................................
Matt Roher  |  Manager, Application Support
United Jewish Appeal of Greater Toronto

phone: 416.631.5897

email: mroher@ujafed.org



Thank you for helping us raise $1 Million for UJA's 2017 Walk with Israel.


...................................................

[UJA Federation]





This message may contain sensitive personal and/or confidential information.  If you have received this email in error, or are not the intended recipient, you may not use, copy, disseminate or distribute it.  Do not open any attachments.  Delete it immediately and notify the sender promptly by email that you have done so.  Thank you.



-------- Original message --------

**Comment by timlegge** [comment]
I logged in 3 times incorrectly, was banned and waited 25 minutes and was able to login.  What version are you on?

That does the advanced option of  login ban time in seconds have as a value:

You may need to do a mysql update:

select userID, Name, ban, bantime from kimai_users where Name = 'Username';

to check the current values

**Comment by kevinpapst** [comment]
Let rephrase that to a feature request:
Show "banned" status in user administration and add a simple way of resetting the ban status. And now lets see if more people vote on this feature request.

**Comment by 0yz** [comment]
here's an easy workaround to unban a user:
1. login as admin
2. if the username of the banned account is f.e. "myuser" then change it to "myuser1"
3. (not sure if necessary) login with "myuser1" and your password. if it worked log out again.
4. log back in as admin & rename "myuser1" back to "myuser" 

voilà, user unbanned

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
