### ISSUE TITLE
best way to export specific db entries and import in other db

### ISSUE THREAD

**Issue by q00d0** [kimai/kimai#993]
Hey,

I want to export DB entries of my Kimai installation and import it to an other installation.
Only entries connected with his ID should be exported. I know th IDs of everything on boths installations.
What is the best way to do this?

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
current stable

**Comment by simonschaufi** [comment]
Use phpmyadmin or any other tool that can limit the entries
