### ISSUE TITLE
Kimai randomly adds/subtracts 30min to start/end time when editing entry

### ISSUE THREAD

**Issue by galapogos** [kimai/kimai#994]
#### Expected behaviour
Start and stop time should be as the user enters

#### Actual behaviour
Often, 30min gets added or subtracted to the start/end time.

#### Steps to reproduce
Create new entry from 06.07.2017 09:00 to 06.07.2017 10:00.
Click OK.
Entry that is added becomes 06.07.2017 09:30 to 06.07.2017 10:30

#### Reproducable on demo.kimai.org? [yes|no]
No

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.2.1.1393

**Comment by simonschaufi** [comment]
The times are saved depending on the time(zone) of the server.
