### ISSUE TITLE
StartTime/Date and EndTime/Date Issues

### ISSUE THREAD

**Issue by sandyst78** [kimai/kimai#995]
Hi Kimai Team,
 I have two questions:
1. Is it possible- when Timesheet new entry is processed, the 'start_time' field to be filed with the 'end_time' of the  last record for the selected day ('start_day').

2. Is it possible to make a setup of max hours of a given day. For example 8 hours for day and isn't possible to enter more records for this day. 

Thanks in advanced.
Al.Stoev

**Comment by kevinpapst** [comment]
Lets see if more people vote on this Feature Request.

**Comment by sollermun** [comment]
One issue I just noticed is that picking dates for expenses does not work with this modification.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
