### ISSUE TITLE
Installation requires php-dom

### ISSUE THREAD

**Issue by greemo** [kimai/kimai#996]
#### Expected behaviour
Installation instructions tell you this

#### Actual behaviour
They don't

#### Steps to reproduce
Install php-7.0 and php-xml according to instructions
Cannot save new time entry as it says class DomDocument not found

#### Reproducable on demo.kimai.org? [yes|no]
no

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389

**Comment by simonschaufi** [comment]
The installer checks for the extension to be installed and the documentation also says it clearly. See http://www.kimai.org/documentation/installation/index.html
