### ISSUE TITLE
install problem halt while in last step

### ISSUE THREAD

**Issue by hsy75** [kimai/kimai#998]
#### Steps to reproduce
![qq 20170621145309](https://user-images.githubusercontent.com/6957467/27371268-ad76ec04-5692-11e7-81f9-455ad72e3db2.png)
![qq 20170621145321](https://user-images.githubusercontent.com/6957467/27371269-ad880372-5692-11e7-9cd1-357d52d9148f.png)
![qq 20170621145352](https://user-images.githubusercontent.com/6957467/27371270-ad8e9dfe-5692-11e7-97cb-8cffc6eeeb2d.png)
![qq 20170621145518](https://user-images.githubusercontent.com/6957467/27371271-ad99ddb8-5692-11e7-81e8-3bca1e354207.png)

there are some steps while install , it seems all is well done in the former steps but it halt in the last step.

#### Relevant l
![001](https://user-images.githubusercontent.com/6957467/27371224-7ff1a436-5692-11e7-9e81-8d0def4b197b.png)
og entries from log file (debug tab or temporary/logfile.txt)

it keeps this screen and never finish.

**Comment by hsy75** [comment]
the install halt I do not know what the reason.

**Comment by simonschaufi** [comment]
Which php version? Please also check the browser dev tools for the network requests. On windows it's F12 key.

**Comment by their** [comment]
Was at this same point. To fix here: Changed ```includes``` permissions from 756 to 777.

**Comment by simonschaufi** [comment]
I'm just completely rewriting the installer but I'm not finished yet. It will work a lot more stable.
