### ISSUE TITLE
[PRAISE] Well done, guys!

### ISSUE THREAD

**Issue by BastianBalthasarBux** [kimai/kimai#999]
Really well done! The upgrade from a pre-existing 9.3 to the latest stable 1.1 is just straight forward!

One pitfall might occur: if you accidenally call the installer first, you will have errors, if the db-backup of kimais installer/updater has been fullfilled already.
Solution is dead-simple: restore your previously created db-backup and run the updater again, and exactly one time!

Many thanks for the great work you guys do for us!

**Comment by simonschaufi** [comment]
Thank you! I made sure the upgrade process works well ;)
